New branding properties
microsoftgraph/microsoft-graph-docs pull request #15003
Opened 2021-11-20 03:52 UTC by AlexanderMars

- Added new properties to the property list in the resource and UPDATE pages
- Updated the first examples in LIST localizations, GET branding, and GET localization
- Changelog is not updated yet
- Added "hideAccountResetCredentials" according to the Pull Request 5352767: Exposing hideAccountResetCredentials property in PPE

2021-11-20 03:53 UTC, opbld30 commented
Docs Build status updates of commit _[1e99587](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e99587bfb10e7f8fbf8fb4217143b82def280fb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-86730b9b)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-86730b9b)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-86730b9b)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-86730b9b)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-86730b9b)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-86730b9b)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-86730b9b"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 315, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-86730b9b"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 67, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 149, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-86730b9b"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 69, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 139, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 192, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="b474f523557c213b527ea0fc6e060a09-86730b9b"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 61, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-86730b9b"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 56, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="90592e6421307e4e6ae931d0003205f5-86730b9b"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 57, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c49 [...]

2021-11-20 04:04 UTC, opbld31 commented
Docs Build status updates of commit _[6539b3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6539b3de1ba7bb05c2f09773a8508ae92ae80c82)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-257d5c6f)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-257d5c6f)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-257d5c6f)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-257d5c6f"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 315, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-257d5c6f"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 149, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-257d5c6f"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 139, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 192, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200402205941-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T04%3A04%3A04Z&sr=b&sp=r&sig=%2BTTUERc%2F9lsPZr0WZDu65DlD6oVO33If4C6a7YbMb70%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 04:19 UTC, opbld32 commented
Docs Build status updates of commit _[a18660a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a18660afd6748ddce0a67fe847dd8f7b6964dd06)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-ac651d12)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-ac651d12)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-ac651d12)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-ac651d12"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 315, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-ac651d12"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 149, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-ac651d12"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 139, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 192, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200417303950-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T04%3A19%3A07Z&sr=b&sp=r&sig=RdrAAe3LoWbMiAFVgrzsuNY91htYFqlR6ETJVkbomR4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 04:44 UTC, opbld33 commented
Docs Build status updates of commit _[7134e1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7134e1c3181c8f578ea14a58ba0ebeb9a4246e58)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-16210f8b)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-16210f8b)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-16210f8b)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-16210f8b"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 315, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-16210f8b"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-16210f8b"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200443050449-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T04%3A44%3A32Z&sr=b&sp=r&sig=yT78H9VkQNSUPUn7dEsqNi6fHbz9r%2BYgJhQdc5VxXhs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 04:54 UTC, opbld34 commented
Docs Build status updates of commit _[424224f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/424224fadfae954f6205ee76bd994aceb51a907b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-94fe9bed)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-94fe9bed)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-94fe9bed)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-94fe9bed"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 315, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-94fe9bed"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-94fe9bed"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200453066043-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T04%3A54%3A31Z&sr=b&sp=r&sig=ry8yQVx%2BQbTZkFOiEo2i84nb%2FnlxuF4UWUGXdnKxnpE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 05:15 UTC, opbld30 commented
Docs Build status updates of commit _[53c58f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53c58f3b5061c8abdd0722a3b1677f2ea3f153e7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-46b6eab7)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-46b6eab7)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-46b6eab7)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-46b6eab7"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 315, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-46b6eab7"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-46b6eab7"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200513460838-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T05%3A15%3A17Z&sr=b&sp=r&sig=Rl35PPq4q1gAiXhdcpN%2FuZ8jzU4TFXewt7H%2F%2BFPcBik%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 05:33 UTC, opbld31 commented
Docs Build status updates of commit _[d1e3e16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1e3e163df09cdc89a243df3c14832be76528fe0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-f2ea3c8a)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-f2ea3c8a)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-f2ea3c8a)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-f2ea3c8a"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-f2ea3c8a"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-f2ea3c8a"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200532092565-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T05%3A33%3A39Z&sr=b&sp=r&sig=l5cuejJi%2BrPrPYvPhTMx2SNOX8sQEztvITAFB1cfHOQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 05:44 UTC, opbld31 commented
Docs Build status updates of commit _[e6ae8df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6ae8dfdcb1d16c0714bae9b82ea6a3b42f2d12b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-6973d6f2)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-6973d6f2)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-6973d6f2)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-6973d6f2"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-6973d6f2"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-6973d6f2"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200542121468-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T05%3A44%3A05Z&sr=b&sp=r&sig=27y5jPJ3vg75BlrghFrwVq9zd40Niq6VPi1CJYBa9Ms%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[fe45d5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe45d5f1555b16a3ed307a6941eafe82df4f80e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-41959a27)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-41959a27)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-41959a27)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-41959a27"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-41959a27"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-41959a27"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200603155372-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T06%3A05%3A31Z&sr=b&sp=r&sig=XycrTJUtcbOsD2XJvw%2FQHOJIA4MSDRAnczUCjIb9Hks%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 06:24 UTC, opbld32 commented
Docs Build status updates of commit _[5206c8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5206c8d12006a64bc27b3362ca93150438ae7722)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-c1692f0c)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-c1692f0c)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-c1692f0c)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-c1692f0c"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-c1692f0c"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-c1692f0c"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200622025981-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T06%3A24%3A13Z&sr=b&sp=r&sig=kWouWoPSF2SGanuiNdKG5iRSoUyh%2FHjQEb%2FEqXZjjzs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 06:36 UTC, opbld34 commented
Docs Build status updates of commit _[461aec5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/461aec5d25c4ff1ecfd2635607a9c6a66023b716)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-1fd4df11)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-1fd4df11)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-1fd4df11)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-1fd4df11"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-1fd4df11"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-1fd4df11"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200634128325-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T06%3A36%3A18Z&sr=b&sp=r&sig=TeTujYC2zbtsHF0%2BVVzu7ZwadK5H9MTpzgH6GTtjiC4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 06:58 UTC, opbld33 commented
Docs Build status updates of commit _[88ab1c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88ab1c8cbd2b538d4faa9ab997d75b87e2bf5505)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-35446613)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-35446613)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-35446613)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-35446613"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-35446613"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-35446613"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200656155690-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T06%3A58%3A32Z&sr=b&sp=r&sig=MCzSOAHCIumITIoFiJ1u4phSKHiA1NGrHRf2ylfdlfQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 07:13 UTC, opbld34 commented
Docs Build status updates of commit _[ec09e8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec09e8c63e1989ac25c814488dbfcb3aa6c60f1f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-a84b511c)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-a84b511c)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-a84b511c)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-a84b511c"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-a84b511c"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-a84b511c"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200711071900-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T07%3A13%3A23Z&sr=b&sp=r&sig=olInmeaczgdt%2F6qu7%2F5NF7qloXQwkSJeZrT%2FIkj1zqc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 07:28 UTC, opbld30 commented
Docs Build status updates of commit _[e190048](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e190048eb761b71d7022ff9c9c4ce0e8192737ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-591e8100)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-591e8100)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-591e8100)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-591e8100"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-591e8100"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-591e8100"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200726539381-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T07%3A28%3A25Z&sr=b&sp=r&sig=UUrOovsaOvJBCX%2FP9Vu2RdUOGHDIyc6iVGqBr02i%2FjI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 16:34 UTC, opbld32 commented
Docs Build status updates of commit _[c55cedf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c55cedf6d0f1f3a7b091ef728337cf8309aa6f9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-f42b28c7)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-f42b28c7)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-f42b28c7)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-f42b28c7"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-f42b28c7"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-f42b28c7"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111201633083603-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T16%3A34%3A56Z&sr=b&sp=r&sig=iFnRGohfCDjSaGWLxDdMHSLyZvAcf5VsoONRV9m8mHs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 17:25 UTC, opbld30 commented
Docs Build status updates of commit _[8a72028](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a7202853125617543455335476d2cdc452d55ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-576f3d6b)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-576f3d6b)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-576f3d6b)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-576f3d6b"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-576f3d6b"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-576f3d6b"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111201724222608-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T17%3A25%3A53Z&sr=b&sp=r&sig=6CKNMRYExumpAmPYESWxN7JXnn2bTb%2BgIpZrdTJ9c9Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 17:42 UTC, opbld33 commented
Docs Build status updates of commit _[d210e27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d210e272bd848f3572923ecd751e232d7658d9b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-21d86dfa)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-21d86dfa)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-21d86dfa)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-21d86dfa"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-21d86dfa"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-21d86dfa"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111201741281363-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T17%3A42%3A54Z&sr=b&sp=r&sig=Wq%2Btiksb8suD8nZ8C4%2Fn8S8E0lMgy36nao%2BwwhMS6hs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 18:21 UTC, opbld32 commented
Docs Build status updates of commit _[172d9fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/172d9fb12af13c26a6a5387728486646650513b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-effe6eb5)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-effe6eb5)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-effe6eb5)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-effe6eb5"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-effe6eb5"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-effe6eb5"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111201820000996-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T18%3A21%3A28Z&sr=b&sp=r&sig=GWoClq3W1jlARnmQg8f079V9d4tCMUOnwo66gy9D8KY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 20:29 UTC, opbld32 commented
Docs Build status updates of commit _[125315d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/125315dfb55eb8438969973f4dd8121151fb3548)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-899e073d)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-899e073d)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-899e073d)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-899e073d"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-899e073d"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-899e073d"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111202028249348-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T20%3A29%3A51Z&sr=b&sp=r&sig=DjTUf9RDZJW%2FhWXyOAZ86Gwr9c98IDPz1Nzxf5CkLgE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 20:48 UTC, opbld34 commented
Docs Build status updates of commit _[6985dc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6985dc2cba54132b7c9cb303cbcf58bd7dd3cd3a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-c9419cf0)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-c9419cf0)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-c9419cf0)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-c9419cf0"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-c9419cf0"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-c9419cf0"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111202046350707-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T20%3A48%3A02Z&sr=b&sp=r&sig=hPhEQFc7w8Tz%2Fk6O6NuQDdtWqRKTL3Mi3ODIOWpM64E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 21:32 UTC, opbld32 commented
Docs Build status updates of commit _[73361b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73361b0e889b83f43c66904d8dcc1106668a525c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-8d10f233)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-8d10f233)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-8d10f233)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-8d10f233"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-8d10f233"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 143, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-8d10f233"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 133, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 186, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111202129420487-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T21%3A32%3A14Z&sr=b&sp=r&sig=y4CEsGcfMqkdLJcNCfa2bVpiSMntpjCyb5%2Fa1gi1iYA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 21:44 UTC, opbld33 commented
Docs Build status updates of commit _[de19695](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de1969501294433dbe26e0aa7f6a56fd0ea55f2e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-7cdfb6f8)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-7cdfb6f8)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-7cdfb6f8)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-7cdfb6f8"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-7cdfb6f8"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-7cdfb6f8"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111202142496693-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T21%3A44%3A19Z&sr=b&sp=r&sig=QlhHjQRr1hKudC4gR%2F9ldqO7PkS20%2BX5rgpw0VMkGg0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 23:27 UTC, opbld32 commented
Docs Build status updates of commit _[44ddf57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44ddf57a8f237dd786687a548b5eec69a401953e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-0b5cd79e)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-0b5cd79e)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-0b5cd79e)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-0b5cd79e"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-0b5cd79e"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-0b5cd79e"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111202325430787-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T23%3A27%3A27Z&sr=b&sp=r&sig=jK1cjs3i5W1Nkpu18ASVcfAPgPUJSNWbm00gYIBnED8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 23:35 UTC, opbld32 commented
Docs Build status updates of commit _[b495116](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4951160141b5cfa5399a11a57318fd32eedb232)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-8d148e5d)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-8d148e5d)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-8d148e5d)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-8d148e5d"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 312, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-8d148e5d"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-8d148e5d"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111202334040622-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T23%3A35%3A52Z&sr=b&sp=r&sig=XAlMZziWX9IMLHuGqjNRDXS%2F6hanczjznd5m6%2FGBe6I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 06:09 UTC, FaithOmbongi commented
@AlexanderMars Once the PR is complete, passed validation, and is ready for content review, please remember to add the **ready for content review** label.

2021-11-24 16:55 UTC, opbld30 commented
Docs Build status updates of commit _[d4543c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4543c730f9704041f8686e48bb97f6d087f0351)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-72a5c7e8)

<a id="72a5c7e8"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241655143729-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T16%3A55%3A43Z&sr=b&sp=r&sig=wWynEQwOWQS2ftsnJDM6AAxOdNYG1wOAr%2FuRFpWS34Y%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 17:21 UTC, opbld32 commented
Docs Build status updates of commit _[1aa1d60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1aa1d60e910abf22b3c9654a520a4067f80360ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-bfb2a188)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-bfb2a188)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-bfb2a188)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-bfb2a188"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-bfb2a188"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-bfb2a188"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241718457043-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T17%3A21%3A43Z&sr=b&sp=r&sig=HR9M5p2EX2zspvlnUQGmUT85%2BMLCgzBn3BQJi8DKmDs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 17:45 UTC, FaithOmbongi requested changes
@AlexanderMars left a few comments mostly related to the API doctor error.

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +  }
This should resolve an API doctor error
```suggestion
  "loginPageTextVisibilitySettings": {
    "@odata.type": "microsoft.graph.loginPageTextVisibilitySettings"
  }
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +  }
For API doctor
```suggestion
  "loginPageTextVisibilitySettings": {
    "@odata.type": "microsoft.graph.loginPageTextVisibilitySettings"
  }
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandingproperties.md
> +  }
For API doctor
```suggestion
  "loginPageTextVisibilitySettings": {
    "@odata.type": "microsoft.graph.loginPageTextVisibilitySettings"
  }
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandingproperties.md
> +| text visibility | [loginPageTextVisibilitySettings](../resources/loginpagetextvisibilitysettings.md) complex type | Represent the various texts that can be hidden. |
Doesn't exist in the public metadata

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandingproperties.md
> +| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on
```suggestion
| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on the login page for a tenant. |
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on
Property is defined in organizationalBrandingProperties resource. So it's inherited from that resource.
```suggestion
| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on the login page for a tenant. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +| text visibility | [loginPageTextVisibilitySettings](../resources/loginpagetextvisibilitysettings.md) complex type | Represent the various texts that can be hidden. |
Doesn't exist in the public metadata

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on
Same comment as before
```suggestion
| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on the login page for a tenant. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/loginpagetextvisibilitysettings.md
> +| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on
Not a property. But we're missing some 2 other properties and hideAccountResetCredentials should be **hideResetItNow**

<img width="410" alt="image" src="https://user-images.githubusercontent.com/14026935/143288531-54248812-688a-4d1c-83ac-25d95f7376cc.png">

```suggestion
```

2021-11-24 17:45 UTC, FaithOmbongi commented on api-reference/beta/resources/loginpagetextvisibilitysettings.md
> +}
Same spirit as the Proeprties table
```suggestion
{
  "@odata.type": "#microsoft.graph.loginPageTextVisibilitySettings",
  "hideCannotAccessYourAccount": "Boolean",
  "hideForgotMyPassword": "Boolean",
  "hideResetItNow": "Boolean",
  "hidePrivacyAndCookies": "Boolean",
  "hideTermsOfUse": "Boolean"
}
```

2021-11-24 19:06 UTC, opbld30 commented
Docs Build status updates of commit _[452ed0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/452ed0cad4abdf6f6cab04d51a029bd6c687a2e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-2445dd4e)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-2445dd4e)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-2445dd4e)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-2445dd4e"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-2445dd4e"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-2445dd4e"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241904265040-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T19%3A06%3A11Z&sr=b&sp=r&sig=vjQXuwe7e2EhYwaeclrzv3gL4a6Ck7gSRVV2o%2F0j6FA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 11:08 UTC, opbld33 commented
Docs Build status updates of commit _[9858ffa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9858ffad08cc700cbe8678ef2e86e175ca10d98d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-ea89e91e)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-ea89e91e)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-ea89e91e)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-ea89e91e"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 313, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-ea89e91e"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-ea89e91e"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 134, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111291107013815-15003%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T11%3A08%3A54Z&sr=b&sp=r&sig=5Higd%2Bv7XKBAXWTfNIPX6LZV0yex2uV97eQkLyPrxSM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 23:28 UTC, AlexanderMars commented on api-reference/beta/resources/loginpagetextvisibilitysettings.md
> +| loginPageTextVisibilitySettings | [loginPageTextVisibilitySettings](../resources/loginPageTextVisibilitySettings.md) | This is a complex type that represents the various texts that can be hidden on
We have another PR to add "hideAccountResetCredentials" https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5352767
This is a single replacement property for those I've removed - hideResetItNow, hideForgotMyPassword and hideCannotAccessYourAccount.

2021-11-29 23:28 UTC, AlexanderMars commented on api-reference/beta/resources/loginpagetextvisibilitysettings.md
> +}
We have another PR to add "hideAccountResetCredentials" https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5352767
This is a single replacement property for those I've removed - hideResetItNow, hideForgotMyPassword and hideCannotAccessYourAccount.

2022-02-09 01:50 UTC, opbld34 commented
Docs Build status updates of commit _[5cdfbe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cdfbe7eff65c7f0cb310d77a42fd02e17019333)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-97f5da5d)

<a id="97f5da5d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090150114361-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T01%3A50%3A48Z&sr=b&sp=r&sig=nY5qWmQFnwzIFsci97Zzdohgt7llmPEMfqwws2Ky3LQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 01:56 UTC, opbld32 commented
Docs Build status updates of commit _[b9ecc67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9ecc67d571e6dce44b59d92c3200feb87951b54)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4a285153)

<a id="4a285153"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090156078395-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T01%3A56%3A45Z&sr=b&sp=r&sig=Tuor1P%2BVCrpXa5n1z3QOdj5UwBiDIu2A2YqpTVxxbNU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:10 UTC, opbld31 commented
Docs Build status updates of commit _[4ca4483](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ca4483e847f830baf4c48e67cb7ed9a5a5350a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-006130f7)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-006130f7)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-006130f7"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-006130f7"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090208172872-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A10%3A44Z&sr=b&sp=r&sig=LTOJKtGtadCC5gKDs%2Bg7IOm3VLknJz1T6ReZ7ixlQis%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:28 UTC, opbld34 commented
Docs Build status updates of commit _[40c9f12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40c9f122085e2b2671aa53b84498d9c7fe176679)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-52ac9b06)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-52ac9b06)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-52ac9b06"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-52ac9b06"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090226020601-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A28%3A19Z&sr=b&sp=r&sig=DZAtyuY1eAVP18hEBVokK1qbGO1PIBvJhhBc2evSK9Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:36 UTC, opbld33 commented
Docs Build status updates of commit _[5889cf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5889cf954927e2bf007b45eaa141a6a2ff8d7583)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-c55cdc90)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-c55cdc90)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-c55cdc90"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-c55cdc90"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090234211082-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A36%3A34Z&sr=b&sp=r&sig=CM%2B0cClXr1sRj5Jr%2FG3LgS%2B84%2B6Lf1l9b1TtFPTaW68%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:44 UTC, opbld33 commented
Docs Build status updates of commit _[b406439](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4064395bfe31762b1d4c8dbff9a100326094c1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-0db5a95c)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-0db5a95c)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |

<a id="7a3ff4d0a9b5e523e426549db1076fde-0db5a95c"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-0db5a95c"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090242163963-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A44%3A30Z&sr=b&sp=r&sig=NJIz4kDFJO1fuRpjeh58XZUMID%2FNpxj88G0%2FS6lSrYs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[674b845](https://github.com/microsoftgraph/microsoft-graph-docs/commits/674b845ae7496f77eb2b48daf0da601065820118)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-f684e70e)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-f684e70e)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7a3ff4d0a9b5e523e426549db1076fde-f684e70e"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-f684e70e"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202092143289234-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T21%3A45%3A33Z&sr=b&sp=r&sig=A3c4VmrkHMT7BASIdRB1AGYyR%2Fv3R7Mn9J3iW1FPsWA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 22:20 UTC, opbld30 commented
Docs Build status updates of commit _[5c6bbe2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c6bbe2151026f02ba0d014eedf09fcd4e18423a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-89e589ef)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-89e589ef)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7a3ff4d0a9b5e523e426549db1076fde-89e589ef"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-89e589ef"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202092218211511-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T22%3A20%3A19Z&sr=b&sp=r&sig=RIsCPtVd8sdV6Brse8R1Mvw5j9KqYX6iKz7M58KgWYc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 15:55 UTC, opbld33 commented
Docs Build status updates of commit _[dbadaea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbadaeaa4536f7c00d4631b8e5e393b649db867b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-91f0bf3b)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-91f0bf3b)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-91f0bf3b)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7a3ff4d0a9b5e523e426549db1076fde-91f0bf3b"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-91f0bf3b"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 60, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageTextVisibilitySettings.md'.`````
 - **Line 143, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-91f0bf3b"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 63, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageTextVisibilitySettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202101553300658-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T15%3A55%3A33Z&sr=b&sp=r&sig=IV1MY%2BHNv2Aa5xdrvhtw8azs4UiIXVoA5lLzsWMI8XU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help [...]

2022-02-10 15:58 UTC, opbld33 commented
Docs Build status updates of commit _[d193a00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d193a000f8d1e9a59a2967835a252ae8ca94be48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-c7f808d4)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-c7f808d4)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-c7f808d4)
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7a3ff4d0a9b5e523e426549db1076fde-c7f808d4"></a>
### [api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md)
 - **Line 329, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="07280cc683676b06b71713506b889387-c7f808d4"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 60, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageTextVisibilitySettings.md'.`````
 - **Line 143, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="53221b760b874006c0148a869739927c-c7f808d4"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 63, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageTextVisibilitySettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202101556133788-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T15%3A58%3A09Z&sr=b&sp=r&sig=zaXBrlnGtl4pZb3L1f7Ds0%2BJ6kFwqgfbXCO4lZTUkQI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help [...]

2022-02-10 16:01 UTC, opbld30 commented
Docs Build status updates of commit _[cbcc5b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbcc5b298d65e9945f51067fe949142c6abde035)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202101559020683-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T16%3A01%3A07Z&sr=b&sp=r&sig=ewULyDrpZT%2B1cARwZ12pDS2p1gK%2Fpii4jahURk53Xzo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 17:30 UTC, opbld34 commented
Docs Build status updates of commit _[db0a750](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db0a750c961bdab1ccdd236a4498fd6028bddef7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202101728280638-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T17%3A30%3A24Z&sr=b&sp=r&sig=%2FJmTtGLPlVtknG1xSeIlA9VSjUUdr6Yb9pNk7KI%2BMjk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 02:13 UTC, opbld30 commented
Docs Build status updates of commit _[cfc9264](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfc9264cdf6a39fb352be54133d54a652b9394a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202110210353663-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T02%3A13%3A49Z&sr=b&sp=r&sig=%2BTG4Djo25Ai1e%2Bi8wQdSpsEYxOmUu3Gu7x698FrKNnQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 02:17 UTC, opbld31 commented
Docs Build status updates of commit _[b705219](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b705219cb513b421503984fb9fc6f4e8ba14a2e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202110215120186-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T02%3A17%3A57Z&sr=b&sp=r&sig=PHLrf3JjwjhlBVm%2BgxNw2xK%2FzrKrvx0R8SFO%2B2J3sXw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 15:32 UTC, opbld30 commented
Docs Build status updates of commit _[fcd2398](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcd2398aecfc541d2d6c670f6aa187ba70ef8120)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202111530159925-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T15%3A32%3A20Z&sr=b&sp=r&sig=KCGXscIvT4XIjxe3CJaO%2FFICIg9Qu40SJ26ghDJbyKE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 18:42 UTC, opbld32 commented
Docs Build status updates of commit _[af20b6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af20b6ff66334b7d477a311309fdda6358edf0f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-78e944ba)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-78e944ba)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="07280cc683676b06b71713506b889387-78e944ba"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 60, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageTextVisibilitySettings.md'.`````

<a id="53221b760b874006c0148a869739927c-78e944ba"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md)
 - **Line 63, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageTextVisibilitySettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202111840003925-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T18%3A42%3A50Z&sr=b&sp=r&sig=J531S26ywduLZ1U6wEtOI%2FboGI0wpj1YgoAomMo2q6Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 18:47 UTC, opbld32 commented
Docs Build status updates of commit _[dfeef8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfeef8eecf76bb8c58fff446186bfc5795c8916b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/loginpagetextvisibilitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/loginpagetextvisibilitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagetextvisibilitysettings?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-15003) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202111844506422-15003%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T18%3A47%3A03Z&sr=b&sp=r&sig=I7%2F%2BmjofVUbsBJHYWFMrhdgd%2FInNYEKKd9ou23Y6mSI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 18:48 UTC, FaithOmbongi approved these changes

2022-02-12 01:46 UTC, merged