Minor updates to access review beta to expose top-level decisions navigation route
microsoftgraph/microsoft-graph-docs pull request #15036
Opened 2021-11-23 20:18 UTC by shubhamguptacal

…igation route

2021-11-23 20:20 UTC, opbld33 commented
Docs Build status updates of commit _[c414534](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/c4145348bb28eeac2401446100dbf0beaae77e66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111232018521952-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T20%3A20%3A35Z&sr=b&sp=r&sig=bjQFP3fILHEL0FN32RE%2BC28fdMWFlgV13ZKPgWjsIJo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:02 UTC, opbld33 commented
Docs Build status updates of commit _[126792f](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/126792f3d3ac73b635646da5587be3747e79da83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241900329295-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T19%3A02%3A32Z&sr=b&sp=r&sig=Wul1%2FBzJDvle5iraZqSANnAPtR%2BkyCDItVeQJiHiBos%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:07 UTC, opbld31 commented
Docs Build status updates of commit _[3e13c41](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/3e13c418fa831b317b55bfaaff4ef04c78648fad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241905328025-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T19%3A07%3A09Z&sr=b&sp=r&sig=cFr%2BmV1tliHkS%2Fwhw4YGFG%2Bp9wNAmug4UH5Jx1uArH4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:11 UTC, opbld31 commented
Docs Build status updates of commit _[139e37d](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/139e37d7488c8295b70b16f1c6e27dfe632bad13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241909506570-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T19%3A11%3A26Z&sr=b&sp=r&sig=Rs7wCLUbt4efIORKj9pDhOrnvp1jlOevQMQYZ3JjeM8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[4742dda](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4742dda8bac1a502ddc60bd92dc012e8e7f68611)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241910366134-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T19%3A13%3A00Z&sr=b&sp=r&sig=uoOKXuy7z9gIW3KJRl7WJd5ucGDG90dNueq6DUbZ3sc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:14 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
> +As a reviewer for an access review, record a decision on every [accessReviewInstanceDecisionItem](../resources/accessReviewInstanceDecisionItem.md) assigned to you that matches the principal and/or r
@shubhamguptacal could you review this please?

2021-11-24 19:14 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
> +POST https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/recordAllDecisions
should this have the filter by current user? @shubhamguptacal

2021-11-24 19:14 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +|type|String|Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.|
@shubhamguptacal shouldnt we only include the access package one as the type option here? and likewise for all the other files

2021-11-24 19:14 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +Every decision item in an access review represents a principal's access to a resource. All accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource objects represent access to access pac
@shubhamguptacal did i capture this right?

2021-11-24 19:14 UTC, opbld31 commented
Docs Build status updates of commit _[7be7158](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/7be71581bda1f2f775cdf1b51f534e1505682a68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241912408754-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T19%3A14%3A59Z&sr=b&sp=r&sig=h5ZrX2r9H37tQP2dgGAYPCybKvsQoW2R%2FMDYXiPKCw4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:53 UTC, shubhamguptacal commented on api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
> +As a reviewer for an access review, record a decision on every [accessReviewInstanceDecisionItem](../resources/accessReviewInstanceDecisionItem.md) assigned to you that matches the principal and/or r
Looks good.

2021-11-24 19:53 UTC, shubhamguptacal commented on api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
> +POST https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/recordAllDecisions
Yes, this should have filterByCurrentUser in the route. The route should be 

POST https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/filterByCurrentUser(on='reviewer')/recordAllDecisions

2021-11-24 19:54 UTC, shubhamguptacal commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +|type|String|Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.|
Yes, that makes sense.

2021-11-24 19:54 UTC, shubhamguptacal commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +Every decision item in an access review represents a principal's access to a resource. All accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource objects represent access to access pac
This makes sense.

2021-11-24 22:04 UTC, isabelleatmsft approved these changes

2021-11-24 22:05 UTC, opbld31 commented
Docs Build status updates of commit _[e5dbe8e](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/e5dbe8ea931f0e50d1c74db35a90596a4e875a7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111242203584524-15036%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T22%3A05%3A43Z&sr=b&sp=r&sig=XZL7OkxabHhhQHsbuRDpj1TB%2FqMhDdL1Yu7CZ9vDxwc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 08:51 UTC, FaithOmbongi requested changes
@shubhamguptacal , left comments for fixes here and there.

I see accessReviewInstanceDecisionItemResource is the base type for the 3 resources you're introducing here. Is that true? If so, I recommend the following:

- Please update the CSDL to indicate that accessReviewInstanceDecisionItemResource is an abstract type
- Update the description of accessReviewInstanceDecisionItemResource.md to indicate that it's an abstract type inherited by the 3 resources. Please see [accessReviewScope](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta) for an example. This helps establish the parent r/ship and removes the idea that these 3 resources are standalone.

Please move the changelog to top of doc

cc @isabelleatmsft

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md
> +---
Wong file. The HTTP request syntax indicates that this is part of the existing [List decisions API](https://docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&tabs=http)

Please move the example to the **List decisions** API as Example 2. Also please correct the request URL (Line 57) when you move the example. Note that you shouldn't add `# [HTTP](#tab/http)` to the new example, that line is autoadded by the snippets generator.

Remember to delete this file after moving the example to the correct file

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +Every decision item in an access review represents a principal's access to a resource. All accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource objects represent access to access pac
```suggestion
Represents a principal's access to an access package assignment policy. accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource is an open type that allows other properties to be passed in.

Inherits from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +|type|String|Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.|
```suggestion
| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
| id | String | Identifier of the decision item resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +|accessPackageDisplayName|String| Access Package Display name |
```suggestion
|accessPackageId|String| Identifier of the access package to which access has been granted. |
|accessPackageDisplayName|String| Display name of the to which access has been granted. |
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +  "openType": true
```suggestion
  "blockType": "resource",
  "@odata.type": "microsoft.graph.accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource",
  "baseType": "microsoft.graph.accessReviewInstanceDecisionItemResource",
  "openType": true
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +Every decision item in an access review represents a principal's access to a resource. All accessReviewInstanceDecisionItemAzureRoleResource objects represent access to Azure resource roles. accessRe
```suggestion
Represents access to Azure resource roles. accessReviewInstanceDecisionItemAzureRoleResource is an open type that allows for other properties to be passed in.

Inherits from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).

```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +Every decision item in an access review represents a principal's access to a resource. All accessReviewInstanceDecisionItemAzureRoleResource objects represent access to Azure resource roles. accessRe
```suggestion
Represents access to Azure resource roles. accessReviewInstanceDecisionItemAzureRoleResource is an open type that allows for other properties to be passed in.

Inherits from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).

```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +|scope|[accessReviewInstanceDecisionItemResource](../resources/accessreviewinstancedecisionitemresource.md)| Details of the scope this role is associated with|
Same changes as before apply here
```suggestion
| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
| id | String | Identifier of the decision item resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
| scope | [accessReviewInstanceDecisionItemResource](../resources/accessreviewinstancedecisionitemresource.md) | Details of the scope this role is associated with. |
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +  "openType": true
```suggestion
  "blockType": "resource",
  "@odata.type": "microsoft.graph.accessReviewInstanceDecisionItemAzureRoleResource",
  "baseType": "microsoft.graph.accessReviewInstanceDecisionItemResource",
  "openType": true
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +title: "accessreviewinstancedecisionitemserviceprincipalresource resource type"
Same case as in the schema
```suggestion
title: "accessReviewInstanceDecisionItemServicePrincipalResource resource type"
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +# accessreviewinstancedecisionitemserviceprincipalresource resource type
```suggestion
# accessReviewInstanceDecisionItemServicePrincipalResource resource type
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +Every decision item in an access review represents a principal's access to a resource. All accessreviewinstancedecisionitemserviceprincipalresource objects represent assignment to service principals.
```suggestion
Represents assignment to service principals. accessReviewInstanceDecisionItemServicePrincipalResource is an open type that allows for other properties to be passed in.

Inherits from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +|appId|String| Application Id |
Reorder properties to alphabetical order
Other changes same as in previously reviewed files
```suggestion
| appId | String | The globally unique identifier of the application to which access has been granted. |
| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
| id | String | Identifier of the decision item resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-11-29 08:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +  "openType": true
```suggestion
  "blockType": "resource",
  "@odata.type": "microsoft.graph.accessreviewinstancedecisionitemserviceprincipalresource",
  "baseType": "microsoft.graph.accessReviewInstanceDecisionItemResource",
  "openType": true
```

2021-11-29 08:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [recordAllDecisions](https://docs.microsoft.com/en-us/graph/api/recordAllDecisions?view=graph-rest-beta) method to the [recordAllDecisions](https://docs.micros
```suggestion
              "Description": "Added the [recordAllDecisions](https://docs.microsoft.com/en-us/graph/api/recordAllDecisions?view=graph-rest-beta) method to the [accessReviewInstanceDecisionItem](https://docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem?view=graph-rest-beta) resource.",
```

2021-11-29 08:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +            },
```suggestion
```
Not introduced here but highlights a gap in the access reviews docs.

@isabelleatmsft , I'll ping you internally to discuss this.

2021-11-29 08:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +        }
```suggestion
          "WorkloadArea": "Identity and access",
          "SubArea": "Governance"
        }
```

2021-11-29 08:59 UTC, FaithOmbongi requested changes

2021-12-06 01:35 UTC, opbld34 commented
Docs Build status updates of commit _[78914f0](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/78914f06c4810d1d8de330754d5733dbae4c4caf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060133036576-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T01%3A34%3A59Z&sr=b&sp=r&sig=M%2B2GFADxrRu%2Fm8AW0Bn6lQ0zmyT%2FviwW%2FH07Bmc4nYc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 01:56 UTC, opbld31 commented
Docs Build status updates of commit _[4880ddf](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4880ddfa992fc75f317796ae9b40204f258a30c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060154396318-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T01%3A56%3A29Z&sr=b&sp=r&sig=BpMHkhUucchF3bGpiBWiFTQfZSjOJkXsbXLgzXTAGLY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 02:11 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +## Example 2
@FaithOmbongi i moved the list-all example in to this file. did i format it correctly?

2021-12-06 02:11 UTC, opbld34 commented
Docs Build status updates of commit _[fa67acf](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/fa67acfebe0557710f1410f320a6e37daf7b3011)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list-all.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list-all?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060210189300-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T02%3A11%3A58Z&sr=b&sp=r&sig=Zxr9yJohUEenFhO2pehLQbLTHQTx72wtl%2BP5mvzS418%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 02:12 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +GET https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/filterByCurrentUser(on='reviewer')?$expand=instance($expand=definition)
@FaithOmbongi you mentioned correcting this line - what needs to be corrected?

2021-12-06 02:15 UTC, opbld30 commented
Docs Build status updates of commit _[10f9737](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/10f9737d82bae51659cc901ed28df2709feea30a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060213025730-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T02%3A15%3A00Z&sr=b&sp=r&sig=uq6f%2F%2FnLHzpN0il7omNtOF36JkhghBnzMlULZyUcyjY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 02:17 UTC, isabelleatmsft commented
> @shubhamguptacal , left comments for fixes here and there.
> 
> I see accessReviewInstanceDecisionItemResource is the base type for the 3 resources you're introducing here. Is that true? If so, I recommend the following:
> 
> * Please update the CSDL to indicate that accessReviewInstanceDecisionItemResource is an abstract type
> * Update the description of accessReviewInstanceDecisionItemResource.md to indicate that it's an abstract type inherited by the 3 resources. Please see [accessReviewScope](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta) for an example. This helps establish the parent r/ship and removes the idea that these 3 resources are standalone.
> 
> Please move the changelog to top of doc
> 
> cc @isabelleatmsft

I'm updating the description to clarify that it is now an abstract type. @shubhamguptacal , could you please update the CSDL?

2021-12-06 02:41 UTC, opbld31 commented
Docs Build status updates of commit _[2e5ef26](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/2e5ef26010f8547249543bd1bcb43b08c5a00af6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060240062610-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T02%3A41%3A39Z&sr=b&sp=r&sig=RAm9vrKga1fDxItJznG4zmNUDWygCSVza98kmmnZWgw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 17:00 UTC, FaithOmbongi requested changes
Hi @isabelleatmsft,

- Very minor comments before approval.
- Remember to delete the accessreviewinstancedecisionitem-list-all.md file.

Regarding the following comment:

"edit: i'm unclear on which are the 3 resources inheriting, so i'll hold off updating and get clarification from y'all tmw"

The change is to update [accessReviewInstanceDecisionItemResource.md](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemResource?view=graph-rest-beta)'s description and indicate that it's an abstract type for the 3 resources you've introduced here. You can follow the same concept you applied in [accessReviewScope](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta), 1st paragraph, 2nd description.

2021-12-30 20:30 UTC, isabelleatmsft requested changes

2021-12-30 20:30 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +## Example 1
```suggestion
### Example 1
```

2021-12-30 20:30 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +## Example 2
```suggestion
### Example 2
```

2021-12-30 20:30 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +                    "displayName": "Shubham Gupta",
```suggestion
                    "displayName": "Adele Vance,
```

2021-12-30 20:30 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +                    "userPrincipalName": "shugup@microsoft.com"
```suggestion
                    "userPrincipalName": "adele@contoso.com"            
```

2021-12-30 20:31 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +## Example 2
done!

2021-12-30 20:33 UTC, isabelleatmsft requested changes

2021-12-30 20:33 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +                    "userPrincipalName": "shugup@microsoft.com"
```suggestion
                    "displayName": "Adele Vance",
                    "userPrincipalName": "adele@contoso.com"            
```

2021-12-30 20:33 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +                    "userPrincipalName": "johndoe@microsoft.com"
```suggestion
                    "userPrincipalName": "johndoe@contoso.com"            
```

2021-12-30 20:33 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +                    "userPrincipalName": "johndoe1@microsoft.com"
```suggestion
                    "userPrincipalName": "johndoe1@contoso.com"            
```

2021-12-30 20:34 UTC, opbld30 commented
Docs Build status updates of commit _[b1b25a1](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/b1b25a1a8e0e1c5dba3062e55fe55ee6797f00e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7a88ecde)

<a id="7a88ecde"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302033543226-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T20%3A34%3A24Z&sr=b&sp=r&sig=Tc7ZZDuLccgjGpXBsDurZgvlX%2F7EuHCWWpM9DbvzVaE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 20:40 UTC, isabelleatmsft requested changes

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +## Example 1
```suggestion
## Examples
### Example 1
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +### Example 1
```suggestion
## Examples
### Example 1
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +GET https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/filterByCurrentUser(on='reviewer')?$expand=instance($expand=definition)
```suggestion
<!-- {
  "blockType": "request",
  "name": "list_accessReviewInstanceDecisionItem"
}-->
GET https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/filterByCurrentUser(on='reviewer')?$expand=instance($expand=definition)
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```suggestion
| displayName | String | Display name of the access package. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResourc
```suggestion
| type | String | Type of resource. Type will always be `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```suggestion
| displayName | String | Display name of the Azure role. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResourc
```suggestion
| type | String | Type of resource. Type will always be `AzureRole`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-12-30 20:40 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResourc
```suggestion
| type | String | Type of resource. Type will always be `ServicePrincipal`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-12-30 20:41 UTC, opbld31 commented
Docs Build status updates of commit _[4697737](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4697737cd3aaece5747727d3a1511c29d1a4c980)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d1abc7b1)

<a id="d1abc7b1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302040583726-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T20%3A41%3A26Z&sr=b&sp=r&sig=F7YGKZeyt%2FCXBQ74za1sb021cZewWPNQ4NZR39lYETM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-03 23:09 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +GET https://graph.microsoft.com/beta/identityGovernance/accessReviews/decisions/filterByCurrentUser(on='reviewer')?$expand=instance($expand=definition)
should be fixed now

2022-01-03 23:10 UTC, opbld32 commented
Docs Build status updates of commit _[20e0d12](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/20e0d12c20a71eda10f42a9455d3e439f9b3f9bf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-adcde38b)

<a id="adcde38b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201032309080917-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-03T23%3A10%3A08Z&sr=b&sp=r&sig=U2lkbejZYDI0Cr6%2FGLXiwibjTmHqqFlvzNRtR5Os5qU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 00:28 UTC, opbld30 commented
Docs Build status updates of commit _[92a8adf](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/92a8adfe83845f1ddcbb5d0c3c5839187b053f2b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e8b22518)

<a id="e8b22518"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040028242231-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T00%3A28%3A47Z&sr=b&sp=r&sig=KsNH8pgisqTk0go3TjjAGDVrbaGWed9s9cD9XIigQWg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 00:35 UTC, opbld34 commented
Docs Build status updates of commit _[bd42ea5](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/bd42ea567235f9d17a4a754ba284744c42d287ba)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d1b5262b)

<a id="d1b5262b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040035311666-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T00%3A35%3A57Z&sr=b&sp=r&sig=8GOvP3cT0ft6tGtjz9TIbyqJxlqa1qyUDdG2jPVEaa0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 00:37 UTC, isabelleatmsft approved these changes

2022-01-10 08:29 UTC, FaithOmbongi requested changes
Hi @isabelleatmsft, @shubhamguptacal,

Please merge **main** into your branch to bring it up to date with the latest changes and avoid overwriting the live docs especially for these two files:

- a**ccessreviewsv2-root.md** is now **accessreviewsv2-overview.md**
- **accessreviewinstancedecisionitem-list.md** is now named **accessreviewinstance-list-decisions.md**.

2022-01-10 08:29 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +Represents a principal's access to an access package assignment policy. accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource is an open type that allows other properties to be passed
```suggestion
Represents an access package assignment policy to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta) object. **accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource** is an open type that allows other properties to be passed in.
```

2022-01-10 08:29 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
> +Represents access to Azure resource roles. accessReviewInstanceDecisionItemAzureRoleResource is an open type that allows for other properties to be passed in.
```suggestion
Represents Azure resource roles to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta) object. **accessReviewInstanceDecisionItemAzureRoleResource** is an open type that allows for other properties to be passed in.
```

2022-01-10 08:29 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +Represents assignment to service principals. accessReviewInstanceDecisionItemServicePrincipalResource is an open type that allows for other properties to be passed in.
```suggestion
This resource represents service principals to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta) object. **accessReviewInstanceDecisionItemServicePrincipalResource** is an open type that allows for other properties to be passed in.
```

2022-01-10 08:29 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +description: "Represents assignment to service principals. "
```suggestion
description: "Represents service principals to which access has been granted through an accessReviewInstanceDecisionItem object."
```

2022-01-10 08:29 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [accessReviewInstanceDecisionItemServicePrincipalResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemServicePrincipa
```suggestion
              "Description": "Added the [accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource?view=graph-rest-beta) resource type. This resource represents an access package assignment policy to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta) object.",
              "Target": "accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource"
            },
            {
              "Id": "c749c50d-8b7b-4274-ab46-45a49b9609c3",
              "ApiChange": "Resource",
              "ChangedApiName": "accessReviewInstanceDecisionItemAzureRoleResource",
              "ChangeType": "Addition",
              "Description": "Added the [accessReviewInstanceDecisionItemAzureRoleResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemAzureRoleResource?view=graph-rest-beta) resource type. This resource represents Azure resource roles to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta) object.",
              "Target": "accessReviewInstanceDecisionItemAzureRoleResource"
            },
            {
              "Id": "c749c50d-8b7b-4274-ab46-45a49b9609c3",
              "ApiChange": "Resource",
              "ChangedApiName": "accessReviewInstanceDecisionItemServicePrincipalResource",
              "ChangeType": "Addition",
              "Description": "Added the [accessReviewInstanceDecisionItemServicePrincipalResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemServicePrincipalResource?view=graph-rest-beta) resource type. This resource represents service principals to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta) object.",
```

2022-01-10 08:29 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +            {
These aren't part of your changes
```suggestion
            {
```

2022-01-18 01:12 UTC, opbld31 commented
Docs Build status updates of commit _[118b709](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/118b709d5b7a1c8197867c44423fd437b5db8fcd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a430ccb0)

<a id="a430ccb0"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180106450319-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T01%3A12%3A20Z&sr=b&sp=r&sig=4SzpY5x%2FWNoNx0x1uj0vwE8eap4zvzWlJkQaV72ORCE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 01:12 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +description: "Represents a principal's access to an access package assignment policy. "
@FaithOmbongi : I think the wording of the remaining suggestions is slightly inaccurate where it says access has been **granted** through an ARIDI object. I would say access is **represented** through that object. 
How do you feel about: "Represents an access package assignment policy for which access is represented through an accessReviewInstanceDecisionItem object."

2022-01-18 01:13 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
@FaithOmbongi I'm having trouble doing this since Shubham started this branch in his own repo. Do you know how to merge in main here - if so, would you mind doing so? Otherwise I'll ping shubham for help

2022-01-18 07:40 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
@isabelleatmsft, sent you a message on Teams.

2022-01-18 07:45 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +description: "Represents a principal's access to an access package assignment policy. "
Your change sounds good, @isabelleatmsft. Go for it.

2022-01-18 19:12 UTC, opbld31 commented
Docs Build status updates of commit _[97fa39a](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/97fa39a6c90d90143ee7f06125318b16501b15cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-521cdaea)

<a id="521cdaea"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201181912096048-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T19%3A12%3A31Z&sr=b&sp=r&sig=Fk%2F8UZI7BjOCQkpKAqsA6P0xdzOFAfpXgvDTtbHYiaw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 19:16 UTC, opbld33 commented
Docs Build status updates of commit _[829c69e](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/829c69e3189584b149c12cf6cb9f4523a122d574)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1423757c)

<a id="1423757c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201181913340417-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T19%3A16%3A04Z&sr=b&sp=r&sig=0OdEhhE1rTJAMdh53f%2B4hHbc72ZSBdNwVwFx0ulx%2B8s%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 19:16 UTC, opbld31 commented
Docs Build status updates of commit _[9f94a8b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/9f94a8bc81906caf96ceab58ba7ae9f282af8cd9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d6f22102)

<a id="d6f22102"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201181914319114-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T19%3A16%3A36Z&sr=b&sp=r&sig=suxvWY7Dro%2FCw1BT4ZgZHIKgmVMeyEr%2B67waxuORO3k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 19:18 UTC, opbld31 commented
Docs Build status updates of commit _[549160c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/549160c684c88c1a316ee8c7a337f0d70d1054dd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b499507b)

<a id="b499507b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201181917052910-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T19%3A18%3A06Z&sr=b&sp=r&sig=1m7GjNnsniVr%2F9ud%2BkDOit%2FOfP0iIBLQ8RirIwCWaCk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 20:30 UTC, opbld33 commented
Docs Build status updates of commit _[29683ef](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/29683efc3dcf01dcd8c3c3b67b20efadca8ad828)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-2159f347fb4af621fdb9f6540d0188ae-9f8e53e1)
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-84ff4dc3f3cea8481ae231527c712ae1-9f8e53e1)
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-3f356fb100f1fcec7868bfa48c26a3e2-9f8e53e1)
[]() | :warning:Warning | | [Details](#user-content-9f8e53e1)
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="2159f347fb4af621fdb9f6540d0188ae-9f8e53e1"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 17, Column 127**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 127**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 127**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="84ff4dc3f3cea8481ae231527c712ae1-9f8e53e1"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md)
 - **Line 17, Column 112**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 112**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 112**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="3f356fb100f1fcec7868bfa48c26a3e2-9f8e53e1"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md)
 - **Line 17, Column 120**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For [...]

2022-01-18 20:49 UTC, isabelleatmsft commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [accessReviewInstanceDecisionItemServicePrincipalResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemServicePrincipa
@FaithOmbongi could you please update these strings to match the changes we made above? TY!

2022-01-19 09:01 UTC, opbld33 commented
Docs Build status updates of commit _[6b21273](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/6b21273d9451b10f519eef2e675c02714ad842f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-2159f347fb4af621fdb9f6540d0188ae-f927c26a)
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-84ff4dc3f3cea8481ae231527c712ae1-f927c26a)
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-3f356fb100f1fcec7868bfa48c26a3e2-f927c26a)
[]() | :warning:Warning | | [Details](#user-content-f927c26a)
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="2159f347fb4af621fdb9f6540d0188ae-f927c26a"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 17, Column 127**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 127**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 127**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="84ff4dc3f3cea8481ae231527c712ae1-f927c26a"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md)
 - **Line 17, Column 112**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 112**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 112**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="3f356fb100f1fcec7868bfa48c26a3e2-f927c26a"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md)
 - **Line 17, Column 120**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For [...]

2022-01-19 09:03 UTC, opbld33 commented
Docs Build status updates of commit _[6b21273](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/6b21273d9451b10f519eef2e675c02714ad842f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-2159f347fb4af621fdb9f6540d0188ae-ffff9ee7)
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-84ff4dc3f3cea8481ae231527c712ae1-ffff9ee7)
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-3f356fb100f1fcec7868bfa48c26a3e2-ffff9ee7)
[]() | :warning:Warning | | [Details](#user-content-ffff9ee7)
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="2159f347fb4af621fdb9f6540d0188ae-ffff9ee7"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 17, Column 127**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 127**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 127**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="84ff4dc3f3cea8481ae231527c712ae1-ffff9ee7"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md)
 - **Line 17, Column 112**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 112**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 112**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="3f356fb100f1fcec7868bfa48c26a3e2-ffff9ee7"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md)
 - **Line 17, Column 120**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For [...]

2022-01-19 09:24 UTC, opbld31 commented
Docs Build status updates of commit _[1d62bed](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/1d62bede0e5650c8b7ac800b7012766926ddc9ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-2159f347fb4af621fdb9f6540d0188ae-8ff3ba1c)
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-84ff4dc3f3cea8481ae231527c712ae1-8ff3ba1c)
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-3f356fb100f1fcec7868bfa48c26a3e2-8ff3ba1c)
[]() | :warning:Warning | | [Details](#user-content-8ff3ba1c)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="2159f347fb4af621fdb9f6540d0188ae-8ff3ba1c"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 17, Column 127**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 127**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 127**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="84ff4dc3f3cea8481ae231527c712ae1-8ff3ba1c"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md)
 - **Line 17, Column 112**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 112**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 112**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="3f356fb100f1fcec7868bfa48c26a3e2-8ff3ba1c"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta [...]

2022-01-19 09:29 UTC, opbld31 commented
Docs Build status updates of commit _[ecfe5d8](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/ecfe5d8385ad5c0a02ba440a03c2b61cdd37c1d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-84ff4dc3f3cea8481ae231527c712ae1-692b0c6c)
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-3f356fb100f1fcec7868bfa48c26a3e2-692b0c6c)
[]() | :warning:Warning | | [Details](#user-content-692b0c6c)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="84ff4dc3f3cea8481ae231527c712ae1-692b0c6c"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md)
 - **Line 17, Column 112**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 112**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 112**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="3f356fb100f1fcec7868bfa48c26a3e2-692b0c6c"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md)
 - **Line 17, Column 120**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 120**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 120**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="692b0c6c"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accessreviewinstancedecisionitem-list.md' are still in the repo. After adding a file [...]

2022-01-19 09:31 UTC, opbld31 commented
Docs Build status updates of commit _[3a547d2](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/3a547d2a83bff9d9172e56f4c650985688abaad1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-6c9828f4)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="6c9828f4"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accessreviewinstancedecisionitem-list.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190929157790-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A31%3A36Z&sr=b&sp=r&sig=4HyZlBYuEAU2GrQGLrPKJKltmbfR6xBc4I9kjT8cncg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:32 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [accessReviewInstanceDecisionItemServicePrincipalResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemServicePrincipa
Done.

2022-01-19 09:34 UTC, opbld31 commented
Docs Build status updates of commit _[049c5f7](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/049c5f75c039027588bded0ecce566c4b66980d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-2159f347fb4af621fdb9f6540d0188ae-1f47197e)
[]() | :warning:Warning | | [Details](#user-content-1f47197e)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="2159f347fb4af621fdb9f6540d0188ae-1f47197e"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 17, Column 91**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewinstancedecisionitem'.`````

<a id="1f47197e"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accessreviewinstancedecisionitem-list.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190930138054-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A34%3A04Z&sr=b&sp=r&sig=qgq68fZgjabokBIpe9tZwgsja4c8OebKBH25YwiQZDc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:37 UTC, opbld30 commented
Docs Build status updates of commit _[da1fa2b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/da1fa2bfa0e387de973d89e2f46321039f9f5d15)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) | [Details](#user-content-2159f347fb4af621fdb9f6540d0188ae-1f575331)
[]() | :warning:Warning | | [Details](#user-content-1f575331)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="2159f347fb4af621fdb9f6540d0188ae-1f575331"></a>
### [api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 17, Column 91**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewinstancedecisionitem'.`````

<a id="1f575331"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accessreviewinstancedecisionitem-list.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190932290082-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A37%3A15Z&sr=b&sp=r&sig=iflBYLATjQxfrYd3WwuBiYJuFCIjFiY1fAnxDJPU11U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:40 UTC, opbld34 commented
Docs Build status updates of commit _[a1316b7](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/a1316b787ff7bcc7e9c49c0b67d20e29944e83d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-aa131946)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="aa131946"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accessreviewinstancedecisionitem-list.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190935169397-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A40%3A04Z&sr=b&sp=r&sig=ELvPVyVQCVF17EN6%2F9pN39Ktv2pWeiAtXsJndHfl3TE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:42 UTC, opbld32 commented
Docs Build status updates of commit _[5dbc1e2](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/5dbc1e221304fa74c014e9dbe20a63b346cd8578)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-23332615)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="23332615"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accessreviewinstancedecisionitem-list.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190939270434-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A42%3A27Z&sr=b&sp=r&sig=MqJEg1F%2FrjVXD6AFWojq97dgM19s50hPJekQPpqLshE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:46 UTC, opbld33 commented
Docs Build status updates of commit _[cfcc0e6](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/cfcc0e6e52e935b4670b40298f93048d3181907f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190944347412-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A46%3A30Z&sr=b&sp=r&sig=EYwQrps4Utl9WLTMuVrky7lvheXS4tleVcip4vecMXI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:55 UTC, opbld33 commented
Docs Build status updates of commit _[ed5eb55](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/ed5eb55b1d1d45fa616e62658fe8d087228043aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190953342464-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A55%3A53Z&sr=b&sp=r&sig=ADhOmpQzBn58pBDjkIXHyAQLc0%2By07ZdTZkOaR1loRM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:59 UTC, opbld34 commented
Docs Build status updates of commit _[ed5eb55](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/ed5eb55b1d1d45fa616e62658fe8d087228043aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190953447232-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A59%3A18Z&sr=b&sp=r&sig=LOD5xwjg3ih7Kbrydz1S8FB4jGAfx29Wme0AmZF8wyg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:02 UTC, opbld32 commented
Docs Build status updates of commit _[4a89d40](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4a89d4054cf27a6ece5690a15efaa98530e3a9cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190957388623-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A02%3A57Z&sr=b&sp=r&sig=0JDjgDlvhVW%2BSjbOUOOGaHh%2BgCN4OwVBy3cJ8ubzd9o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:11 UTC, FaithOmbongi approved these changes

2022-01-19 10:28 UTC, opbld31 commented
Docs Build status updates of commit _[0cc84e6](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/0cc84e67ce143d49938c1cf2ecd87d19c11cd8bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191026345841-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A28%3A29Z&sr=b&sp=r&sig=L0CyvyETXZzJY9tdNdUYnpFBzvAIV3pLZWkPUWICkjo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 05:54 UTC, Lauragra commented on api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
> +title: "accessReviewInstanceDecisionItem: recordAllDecisions"
Please surface the method topic in the beta TOC.

2022-01-20 07:42 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
> +title: "accessReviewInstanceDecisionItem: recordAllDecisions"
Done.

2022-01-20 07:49 UTC, opbld32 commented
Docs Build status updates of commit _[d8b51a2](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d8b51a29c68063545559df8033f2d662cc14af3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200746538842-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T07%3A49%3A21Z&sr=b&sp=r&sig=uJjBHHsiiIHImORS%2BbS%2BPPGKwyTlsIQbkRoZyOUu1Lk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 07:51 UTC, opbld33 commented
Docs Build status updates of commit _[bc947fd](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/bc947fd7e7c8c71f9f57f981805609e241f19aaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-recordalldecisions?view=graph-rest-beta&branch=pr-en-us-15036) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-mydecisions-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200749116275-15036%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T07%3A51%3A45Z&sr=b&sp=r&sig=%2BVQbsI3WqTXMOmm7h49cqfbvd4ZSGCeHi3vWVT46JA8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 01:33 UTC, merged