[Azure AD roles] Resource namespace and resource action (Preview)
microsoftgraph/microsoft-graph-docs pull request #15043
Opened 2021-11-24 19:22 UTC by rolyon

2021-11-24 19:24 UTC, opbld32 commented
Docs Build status updates of commit _[0c87929](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c8792920e3e9e7b9888832a0aed6887e8661f54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ba36f7e553c2690bc273e38546b7673c-29790062)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-564400cd293d6adc9a307d79a0a2fd59-29790062)
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-4f4df3405858423e11dd519f1a445c85-29790062)
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-d8e65ed23f48aa228ca8f399025890f0-29790062)
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-937ccc1d7a96cfece8c312cff6b779f9-29790062)
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-33d1815b740e4521f75c307f68c1a156-29790062)
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-2a45668bfde500f4850cf42950c56297-29790062)
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-fd5eed1974caee87c2b1b477c0462adb-29790062)
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-565870a17407a90b48d46ceb18f50eea-29790062)
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ac538a35510ec39d56214d806ae0a540-29790062)
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-29790062)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-29790062)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |

<a id="ba36f7e553c2690bc273e38546b7673c-29790062"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="564400cd293d6adc9a307d79a0a2fd59-29790062"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/ [...]

2021-11-24 19:42 UTC, opbld30 commented
Docs Build status updates of commit _[8b095ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b095ce3fda49dae5cb0f5767404c2b2ce0f6d73)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ba36f7e553c2690bc273e38546b7673c-0393192c)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-564400cd293d6adc9a307d79a0a2fd59-0393192c)
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-4f4df3405858423e11dd519f1a445c85-0393192c)
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-d8e65ed23f48aa228ca8f399025890f0-0393192c)
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-937ccc1d7a96cfece8c312cff6b779f9-0393192c)
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-33d1815b740e4521f75c307f68c1a156-0393192c)
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-2a45668bfde500f4850cf42950c56297-0393192c)
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-fd5eed1974caee87c2b1b477c0462adb-0393192c)
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-565870a17407a90b48d46ceb18f50eea-0393192c)
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ac538a35510ec39d56214d806ae0a540-0393192c)
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-0393192c)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-0393192c)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |

<a id="ba36f7e553c2690bc273e38546b7673c-0393192c"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="564400cd293d6adc9a307d79a0a2fd59-0393192c"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/ [...]

2021-11-24 19:59 UTC, opbld33 commented
Docs Build status updates of commit _[1774010](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1774010fc6bad463dd1ed880ce995c0a3adb4e2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ba36f7e553c2690bc273e38546b7673c-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-564400cd293d6adc9a307d79a0a2fd59-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-4f4df3405858423e11dd519f1a445c85-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-d8e65ed23f48aa228ca8f399025890f0-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-937ccc1d7a96cfece8c312cff6b779f9-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-33d1815b740e4521f75c307f68c1a156-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-2a45668bfde500f4850cf42950c56297-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-fd5eed1974caee87c2b1b477c0462adb-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-565870a17407a90b48d46ceb18f50eea-8e75bd2d)
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ac538a35510ec39d56214d806ae0a540-8e75bd2d)
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-8e75bd2d)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-8e75bd2d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |

<a id="ba36f7e553c2690bc273e38546b7673c-8e75bd2d"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="564400cd293d6adc9a307d79a0a2fd59-8e75bd2d"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/ [...]

2021-11-24 20:10 UTC, opbld33 commented
Docs Build status updates of commit _[2eeb1bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eeb1bdb102a247e2e08a133c8a786cf33f30a45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ba36f7e553c2690bc273e38546b7673c-90e70b9f)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-564400cd293d6adc9a307d79a0a2fd59-90e70b9f)
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-4f4df3405858423e11dd519f1a445c85-90e70b9f)
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-d8e65ed23f48aa228ca8f399025890f0-90e70b9f)
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-937ccc1d7a96cfece8c312cff6b779f9-90e70b9f)
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-33d1815b740e4521f75c307f68c1a156-90e70b9f)
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-2a45668bfde500f4850cf42950c56297-90e70b9f)
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-fd5eed1974caee87c2b1b477c0462adb-90e70b9f)
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-565870a17407a90b48d46ceb18f50eea-90e70b9f)
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-ac538a35510ec39d56214d806ae0a540-90e70b9f)
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-90e70b9f)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-90e70b9f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |

<a id="ba36f7e553c2690bc273e38546b7673c-90e70b9f"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="564400cd293d6adc9a307d79a0a2fd59-90e70b9f"></a>
### [api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/ [...]

2021-11-24 20:26 UTC, opbld31 commented
Docs Build status updates of commit _[f5cf9b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5cf9b1446986647257e5b1d860f58f6b2f3f234)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-cf4a4a49)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-cf4a4a49)
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |

<a id="c4da98f122a96a887edca6fa53aa4d30-cf4a4a49"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-cf4a4a49"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111242024564161-15043%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T20%3A26%3A28Z&sr=b&sp=r&sig=Gf%2Bn%2Fxtvt%2FkONMyZN%2FPFzK06aksL3vDbDdX%2BxYgZWcY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try s [...]

2021-11-24 20:43 UTC, opbld31 commented
Docs Build status updates of commit _[ad99b09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad99b093b42d9e60572396a4ad0732c64d6f0f96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-e5a60a0b)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-e5a60a0b)
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c4da98f122a96a887edca6fa53aa4d30-e5a60a0b"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-e5a60a0b"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111242041583473-15043%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T20%3A43%3A47Z&sr=b&sp=r&sig=5NfZ4Hx34ZmQTrhHET3LqRmcPYgYBcxZMjZ8yCrMcKw%3D).

**Note:** Broken links written as relative paths are included in the above build r [...]

2021-11-24 20:51 UTC, opbld33 commented
Docs Build status updates of commit _[92dac3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92dac3b3bd5bb1e3d4b927a31dea55d93970e21f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-c8f182a7)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-c8f182a7)
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c4da98f122a96a887edca6fa53aa4d30-c8f182a7"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-c8f182a7"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111242049285352-15043%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T20%3A51%3A02Z&sr=b&sp=r&sig=ZaZB7FDOZr07cXpwPsVTB6rp%2B0tLRWt5CY9SJyaUZQQ%3D).

**Note:** Broken links written as relative paths are included in the above build [...]

2021-12-03 21:58 UTC, opbld32 commented
Docs Build status updates of commit _[8e25b9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e25b9ca9c839e44dd7fab2252612b84ad5b6dfd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-dfe12802)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-dfe12802)
[api-reference/beta/api/unifiedrbacresourceaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-post-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-post-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-update?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-delete?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c4da98f122a96a887edca6fa53aa4d30-dfe12802"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-dfe12802"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032156341723-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T21%3A58%3A14Z&sr=b&sp=r&sig=IOzT0eVPluBMDfnoIUqe8MFs8VPjRT8aJu%2BH7Obk8Uc%3D).

**Note:** Broken links written as relative paths are included in the above build  [...]

2021-12-03 22:10 UTC, opbld32 commented
Docs Build status updates of commit _[a463b97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a463b974b6ce32513285648f2a9a41a2c55d7f1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-b436634a)
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-b436634a)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="cf858620f49ead84f7524a2b73ce15a7-b436634a"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/unifiedrbacresourcenamespace-post-resourceactions.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="c4da98f122a96a887edca6fa53aa4d30-b436634a"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032209176608-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T22%3A10%3A50Z&sr=b&sp=r&sig=3QWH2x5F5wHaXZLQr0SCPtTLEtvnoPyEBN4hgnADr9A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 22:18 UTC, opbld33 commented
Docs Build status updates of commit _[2556b6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2556b6e964ae664c565342a520a5a76135198bab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-854cf90e)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-854cf90e)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c4da98f122a96a887edca6fa53aa4d30-854cf90e"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-854cf90e"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032216331615-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T22%3A18%3A12Z&sr=b&sp=r&sig=is8a2assz7cgzXw2pAAbK4vfwhZXgxhgcWWPcOTo0ao%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 22:56 UTC, opbld30 commented
Docs Build status updates of commit _[6cf403a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cf403a8160d79f3ffa565c61eb4d39812d5aa0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-fef85674)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-fef85674)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c4da98f122a96a887edca6fa53aa4d30-fef85674"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-fef85674"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032254239836-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T22%3A56%3A36Z&sr=b&sp=r&sig=8puMmaKnezHCKalmJc4J%2BnaTToxK9CsjOT778WGqe7c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 23:12 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourceaction-get.md
> +## Optional query parameters
@rolyon - Supported query parameters should be in the PR.

2021-12-03 23:12 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourceaction-get.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/resourceNamespaces/{unifiedRbacResourceNamespaceId}/resourceActions/{unifiedRbacResourceActionId}
@rolyon - Replace placeholders with actual example.

2021-12-03 23:14 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourceaction-get.md
> +  "value": {
@rolyon - Add actual response here.

2021-12-03 23:14 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourceaction-get.md
> +|Application|**TODO: Provide applicable permissions.**|
@rolyon  What's this 'todo' perm?

2021-12-03 23:17 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourceaction-list.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/resourceNamespaces/{unifiedRbacResourceNamespaceId}/resourceActions
@rolyon - Same comment as above.

2021-12-03 23:17 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourcenamespace-get.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/resourceNamespaces/{unifiedRbacResourceNamespaceId}
@rolyon - Replace placeholders with actual examples.

2021-12-03 23:19 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md
> +title: "List resourceActions"
@rolyon - How is this file different from this file - api-reference/beta/api/unifiedrbacresourceaction-list.md

2021-12-03 23:23 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +|[List resourceActions](../api/unifiedrbacresourcenamespace-list-resourceactions.md)|[unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) collection|Get the unifiedRbacResourceActio
@rolyon - We generally write functions associated with the entity here. not its child. Why do we need List resourceActions here?

2021-12-03 23:23 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +|id|String|**TODO: Add Description**|
@rolyon - Descriptions missing. Use the info from PR.

2021-12-03 23:23 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +|resourceActions|[unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) collection|**TODO: Add Description**|
@rolyon - Descriptions missing.

2021-12-03 23:24 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +**TODO: Add Description**
@rolyon - Description missing.

2021-12-03 23:24 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +**TODO: Add Description**
@rolyon - Description mising.

2021-12-03 23:25 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +|[List unifiedRbacResourceActions](../api/unifiedrbacresourceaction-list.md)|[unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) collection|Get a list of the [unifiedRbacResourceAc
@rolyon  Descriptions missing

2021-12-04 01:07 UTC, opbld34 commented
Docs Build status updates of commit _[901078c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/901078c453c82c4742994f44eaeb0d28eca16165)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-c4da98f122a96a887edca6fa53aa4d30-a0e06f3d)
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-a0e06f3d)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c4da98f122a96a887edca6fa53aa4d30-a0e06f3d"></a>
### [api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

<a id="cf858620f49ead84f7524a2b73ce15a7-a0e06f3d"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/unifiedrbacresourceaction.md(3,14)', 'beta/resources/unifiedrbacresourcenamespace.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112040105318826-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-04T01%3A07%3A19Z&sr=b&sp=r&sig=ZtjItBl9VYSsTypAzQMSDGaEYq3kAozptAAHVrcW28c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 23:55 UTC, opbld32 commented
Docs Build status updates of commit _[e759aad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e759aad7d501f478af0272d2f256f542e630127d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6d5c2f9e)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6d5c2f9e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml)
 - **Line 12521, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201062353342405-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T23%3A55%3A28Z&sr=b&sp=r&sig=ihDRceaXwaLCEGv%2FynWQdPCsN0v1o0%2FpzAIoJRvdE4U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 18:55 UTC, opbld34 commented
Docs Build status updates of commit _[f4dd5c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4dd5c8b2062ec63004acc36d85ed70b8ca5fff8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201071853451459-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T18%3A55%3A33Z&sr=b&sp=r&sig=XmxSc4Mndarw2ONh2IG7vzXD1BsmZSAwW%2FDDIzlDA%2Fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 21:24 UTC, opbld33 commented
Docs Build status updates of commit _[6bb62b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bb62b6de77edf5bf4b3f2246162caf0717d23bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-cf858620f49ead84f7524a2b73ce15a7-7ee9b47c)
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="cf858620f49ead84f7524a2b73ce15a7-7ee9b47c"></a>
### [api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/unifiedrbacresourcenamespace-list-resourceactions.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201112122581931-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T21%3A24%3A50Z&sr=b&sp=r&sig=pdiwP1JKLjbEO2VRv4YZncrprXfCZ7VytMXYLVSJmHA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 21:32 UTC, opbld30 commented
Docs Build status updates of commit _[8ca0040](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ca0040754f06a515225c91d137a2930feb1f654)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201112130315058-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T21%3A32%3A42Z&sr=b&sp=r&sig=0Yzi%2B3O8NeV3vZbLHf9GYdHVIDmKlyN4T7xje52VNSU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 00:11 UTC, opbld34 commented
Docs Build status updates of commit _[015447e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/015447e39b74622600714f887916b128078ab951)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201120009142919-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T00%3A11%3A18Z&sr=b&sp=r&sig=0Cn1pJIAfgqIgdCGmlP%2BY%2B6SmaVf5YtBjMlaJp06a34%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[aabd5cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aabd5cc8a4d856299305fe11e4e679dd4c1457c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201202154051644-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T21%3A56%3A35Z&sr=b&sp=r&sig=Aei%2FCIyg0LLflpl8f5Z4CzJKb94on7dDxLEgtQcmKik%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 08:53 UTC, FaithOmbongi requested changes
Thank you @rolyon for your work on this PR. Left suggestions for minor fixes plus the following major
- Left comments in the descriptions for unifiedRbacResourceNamespace and unifiedRbacResourceAction resource type files. We've not explained the goal and benefits of these resources/APIs. A number of Qs are left unanswered.
- Document the resourceNamespaces r/ship in the [rbacApplicationMultiple](https://docs.microsoft.com/en-us/graph/api/resources/rbacApplicationMultiple?view=graph-rest-beta) resource page.
- File name changes (applying the file naming guidance):
    - unifiedrbacresourcenamespace-list.md => **rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md**
    - unifiedrbacresourceaction-list.md => **unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md**
- Missing doc for the unifiedRbacResourceScope resource type (and possibly its associated methods). **unifiedRbacResourceScope** is the return type for the **resourceScope** r/ship in a  **unifiedRbacResourceAction** object.
- Move the changelog to the top of the file, starting Line 3.

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +|[List unifiedRbacResourceActions](../api/unifiedrbacresourceaction-list.md)|[unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) collection|Get a list of the [unifiedRbacResourceAc
```suggestion
|[List unifiedRbacResourceActions](../api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md)|[unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) collection|Get a list of the [unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) objects and their properties.|
```

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +
Missing **resourceScopeId** property

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +  "blockType": "resource",
This r/ship should be **resourceScope** as per the schema; return type is **unifiedRbacResourceScope**.

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +}
Added resourceScopeId
```suggestion
{
  "@odata.type": "#microsoft.graph.unifiedRbacResourceAction",
  "id": "String (identifier)",
  "actionVerb": "String",
  "description": "String",
  "name": "String",
  "resourceScopeId": "String"
}
```

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrbacresourceaction-list.md
> +This method supports the `$filter`, `$top`, and `$skiptoken` OData query parameters to help customize the response. This method supports `$filter` for `actionVerb`, `description`, `id`, and `name`. T
Could you confirm that 
```suggestion
This method supports the `$filter`, `$select`, `$top`, and `$skipToken` OData query parameters to help customize the response. This method supports `$filter` (`eq`) for **actionVerb**, **description**, **id**, and **name** properties. This method returns a default page size of 100 **resourceActions** and supports `$top` and `$skipToken` for paging. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +|name|String|Name for the action within the directory resource namespace, such as `microsoft.insights/programs/update`. Can include slash character (`/`). Case insensitive. Required.|
```suggestion
|actionVerb|String|HTTP method for the action, such as `DELETE`, `GET`, `PATCH`, `POST`, `PUT`, or `null`. Supports `$filter` (`eq`) but not for `null` values. |
|description|String|Description for the action. Supports `$filter` (`eq`). |
|id|String|Unique identifier for an action within the directory resource namespace, such as `microsoft.insights-programs-update-patch`. Cannot include slash character (`/`). Case insensitive. Required. Supports `$filter` (`eq`). |
|name|String|Name for the action within the directory resource namespace, such as `microsoft.insights/programs/update`. Can include slash character (`/`). Case insensitive. Required. Supports `$filter` (`eq`). |
```

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrbacresourceaction-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```suggestion
This method supports the `$select` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-01-24 08:53 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: api/unifiedrbacresourceaction-get.md
Proposing to move Resource actions a level inside because it's dependent on Resource namespace
```suggestion
          - name: Resource namespace
            href: resources/unifiedrbacresourcenamespace.md
            items:
            - name: List
              href: api/unifiedrbacresourcenamespace-list.md
            - name: Get
              href: api/unifiedrbacresourcenamespace-get.md
            - name: Resource actions
              href: resources/unifiedrbacresourceaction.md
              items:
              - name: List
                href: api/unifiedrbacresourceaction-list.md
              - name: Get
                href: api/unifiedrbacresourceaction-get.md
```

2022-01-24 08:53 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    {
Please move your changelog record to the top of the file and then also add an entry for unifiedRbacResourceScope (and associated methods?) once you add the file.

2022-01-27 21:38 UTC, opbld30 commented
Docs Build status updates of commit _[d266048](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2660480660751e2b28e2e07a26515ecb08e717a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272135457253-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T21%3A38%3A03Z&sr=b&sp=r&sig=mVK4we3TgOQqd0QlrDtzWIyJS2snScTPldBf95RVwMM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 21:41 UTC, rolyon commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +|[List unifiedRbacResourceActions](../api/unifiedrbacresourceaction-list.md)|[unifiedRbacResourceAction](../resources/unifiedrbacresourceaction.md) collection|Get a list of the [unifiedRbacResourceAc
Added descriptions

2022-01-27 21:42 UTC, opbld33 commented
Docs Build status updates of commit _[ac8003f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac8003fa326af1dc892877f8d3adc932347c9f46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272140156406-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T21%3A42%3A20Z&sr=b&sp=r&sig=ovmSgTVRTfKOqd94im9r79iA6N5z0nbjiZCGcBB2XSY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[30ace1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30ace1b1d121f39d38bcd32b87026aecd7daeaab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272141009112-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T21%3A45%3A27Z&sr=b&sp=r&sig=c8%2FHUwwxFxJRZjJ%2FRXT5deh8gkzIOpF9qPppqzYBMl0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 21:57 UTC, opbld32 commented
Docs Build status updates of commit _[aa60bef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa60befc595f039cd2a1e1c900e2c87dd63551db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272155243237-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T21%3A57%3A54Z&sr=b&sp=r&sig=RPMhIgUwd4sG13qQslVOexNkK1gnduylAzVIdtrgLF0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 22:22 UTC, opbld31 commented
Docs Build status updates of commit _[1169c2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1169c2a0620700a05bc24d9d433ba93977954433)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272220204434-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T22%3A22%3A54Z&sr=b&sp=r&sig=CwR55D40jwCGluheKxpCl9l0sp%2B5onR6KiFp8pYbu0Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 22:27 UTC, rolyon commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +
@abhijeetsinha 
Can you respond to Faith's comment?

2022-01-27 22:27 UTC, rolyon commented on api-reference/beta/resources/unifiedrbacresourceaction.md
> +  "blockType": "resource",
@abhijeetsinha 
Can you respond about resourceScope and unifiedRbacResourceScope?

2022-02-17 21:14 UTC, opbld30 commented
Docs Build status updates of commit _[29b1c13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29b1c132194d654f27424a3a14a07c7eaf8a46a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202172111077278-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T21%3A14%3A14Z&sr=b&sp=r&sig=%2BblNeuaq%2BivKCweqV789T3RR6R9r1ew9NYQDFn4CEKM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 01:29 UTC, opbld33 commented
Docs Build status updates of commit _[9179db7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9179db7664d0caad07cbbf104450e6108f986429)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-c4096113)
[api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcescope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcescope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcescope?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-c4096113"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202180127448553-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T01%3A29%3A46Z&sr=b&sp=r&sig=a07LN4bDP0ag%2FfoAAnDmzKfNyAZ1wsVfcxi2U9a0nrE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 19:46 UTC, opbld33 commented
Docs Build status updates of commit _[8e44b2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e44b2c11f2d31800bc954a2fdf63279269b661a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-7cb8bedc)
[api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcescope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcescope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcescope?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-7cb8bedc"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202181944262821-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T19%3A46%3A34Z&sr=b&sp=r&sig=k7z1TEcrWAxN8V7sy4ev%2FsdD%2FBmb0mQlrqhGL14CBHA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 20:30 UTC, opbld34 commented
Docs Build status updates of commit _[c1e096c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1e096c8baf3b1c44ce04a624774cb764b6d0798)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-8cae500b)
[api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-8cae500b"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202182028226801-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T20%3A30%3A35Z&sr=b&sp=r&sig=cCZAsX%2BpkBHlZAmfV404gmP5SG6Buk4PgMVeEQA4sNk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 22:45 UTC, opbld31 commented
Docs Build status updates of commit _[1083d75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1083d75895c73284249e45f4ec86cf547e417785)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-2ba8226d)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-2ba8226d"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202182242570096-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T22%3A45%3A23Z&sr=b&sp=r&sig=Hb0erw1GZWukyKO%2F9MwOLYJkKnmfTsY4%2FYhBTQLj%2FtI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 23:16 UTC, opbld33 commented
Docs Build status updates of commit _[64f99dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64f99dd52dbb248494aac77a7f44709fd33232cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-fa7e2a98)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-fa7e2a98"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202182314400690-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T23%3A16%3A43Z&sr=b&sp=r&sig=G6%2BT9QxRQ39oEGJmDlYAhNL1HoRX2GO5sxlTGPyeS2M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 07:06 UTC, opbld33 commented
Docs Build status updates of commit _[2067801](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2067801182ca70f9405908784b986444af3fd516)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-33d54573)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-33d54573"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202210702594982-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T07%3A06%3A13Z&sr=b&sp=r&sig=skItU7C2rhvvSM%2Bm2iD6BfDT48xhSOd38wT4QZ%2BEhyw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 07:56 UTC, FaithOmbongi commented
Hi @rolyon, I had to comment out the **resourceScope** relationship to bypass the API doctor error.

2022-02-22 09:26 UTC, rolyon commented on api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md
> +title: "List resourceActions"
We removed unifiedrbacresourceaction-list.md

2022-02-22 09:33 UTC, opbld34 commented
Docs Build status updates of commit _[39518a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39518a2999dcc0b0c40e2e9a77acba36acd3a164)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-1b590a88)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-1b590a88"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202220932044053-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T09%3A33%3A52Z&sr=b&sp=r&sig=wdkXh35f3P50GvY5JhFoGHTQbyE6MJ9LGBqf6yLZX64%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 09:37 UTC, rolyon commented
Hi @FaithOmbongi 
Is content review still in progress?
thanks

2022-02-24 21:58 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +An object that represents a collection of related actions. Inherits from [entity](entity.md).
@rolyon  - Modify the description to this "Represents the namespace of the area to which the role permission belongs to. "

2022-02-24 22:34 UTC, opbld31 commented
Docs Build status updates of commit _[9b3a890](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b3a8906dd376ba804a3fb58d3951482f50ca41d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-1b8ec83a)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-1b8ec83a"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202242232127069-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T22%3A34%3A23Z&sr=b&sp=r&sig=mngHt%2Bef2ezH9ZxahoMQaDpePsoI7ZeI0fxITZOx31Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 11:51 UTC, FaithOmbongi approved these changes
Thank you @rolyon for addressing the feedback. I've also found and reviewed the related API.md and shared suggestions to consider. Otherwise, approved.

2022-02-25 11:51 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +Represents the namespace of the area to which the role permission belongs to. Inherits from [entity](entity.md).
I suggest a change after reviewing the new description, the return objects, and the related API.md that I found.
Reason for suggestion: This resource doesn't define the permissions directly (that's resourceActions), but the namespaces for the areas which in turn define permissions.
If this suggestion is correct and acceptable, please also update the metadata description with the new description.
```suggestion
Represents the namespaces for areas or services such as Azure AD, Intune, and Exchange that define role permissions. Inherits from [entity](entity.md).
```

2022-02-25 11:51 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedrbacresourcenamespace.md
> +|name|String|Name of the directory resource namespace. Typically, the same name as the **id** property, such as `microsoft.aad.b2c`. Required. Supports `$filter` (`eq`, `startsWith`).|
Suggestion to remove the word "directory" because that seems to limit the description to the `microsoft.directory` namespace when there are other 40+ namespaces exposed by this resource.
```suggestion
|id|String|Unique identifier of the resource namespace that defines permissions, such as `microsoft.aad.b2c`. Required.|
|name|String|Name of the resource namespace. Typically, the same name as the **id** property, such as `microsoft.aad.b2c`. Required. Supports `$filter` (`eq`, `startsWith`).|
```

2022-02-25 22:16 UTC, opbld32 commented
Docs Build status updates of commit _[1d31941](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d3194137347dfd51910a9b9cdb46c43105576b9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e929df37)

<a id="e929df37"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252215371402-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T22%3A16%3A37Z&sr=b&sp=r&sig=Eln1yIyK8p5oodp1RaOD3PgEA4e%2B6ZawQuaGpZQDSzQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 22:17 UTC, opbld34 commented
Docs Build status updates of commit _[1d31941](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d3194137347dfd51910a9b9cdb46c43105576b9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-671ed5ec)

<a id="671ed5ec"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252215471264-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T22%3A17%3A16Z&sr=b&sp=r&sig=qeqv627HfJc8XCxu7P3RfdxYe5y%2FPCMItF0ucpgoY7U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 22:35 UTC, opbld34 commented
Docs Build status updates of commit _[b43e029](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b43e029e8f618600823fa971d87b7abd16bb3af1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-931a2cb3)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-931a2cb3"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252226202095-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T22%3A35%3A36Z&sr=b&sp=r&sig=6ltGE6m1YZcjRT0G60l7jbO%2FHjfvecH5nGfBJWfGbRg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 22:47 UTC, opbld30 commented
Docs Build status updates of commit _[9e17159](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e1715956c855c27eb9f57bc419fc9bb38a1093c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-9d4b5997)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-9d4b5997"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252245449985-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T22%3A47%3A41Z&sr=b&sp=r&sig=T8UzWmHrWWpzhkafaC2dLCk8Ey%2Fox20RlCKdTPyzpQc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 22:52 UTC, opbld32 commented
Docs Build status updates of commit _[b6d768b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6d768b4467cf79174708d874b3530f1c55fa894)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-27dd8199)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-27dd8199"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252251079368-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T22%3A52%3A53Z&sr=b&sp=r&sig=zAEx8gMtjpMvZZEn3rf0b8vIr7B2xY1AnvCZdPLKj70%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 23:03 UTC, opbld31 commented
Docs Build status updates of commit _[4238f4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4238f4f0980132fb9d97a79502b4ba8ffe88adb3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-74d544bd)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-74d544bd"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252301020509-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T23%3A03%3A02Z&sr=b&sp=r&sig=%2BDeE0QLT8FR9KnTXs7FdERrtXb7EQKcYl7BDgHAcQAI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[fb2183e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb2183e5a18b74143d3258b8f7a514d3a5707f84)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-88b09265)
[api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourceaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourceaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourceaction-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-get?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedrbacresourcenamespace-list-resourceactions?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourceaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourceaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourceaction?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/resources/unifiedrbacresourcenamespace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/unifiedrbacresourcenamespace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrbacresourcenamespace?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-resourcenamespaces?view=graph-rest-beta&branch=pr-en-us-15043) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-88b09265"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-namescopes-nameactions-beta/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202252347183157-15043%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T23%3A49%3A24Z&sr=b&sp=r&sig=EqvFTTFQSJGC%2BGSfPQpfFkAPMY76Bd5RIZhJqNdUYZ0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-26 06:16 UTC, merged