GetSubmission and GetSubmissions - Adding Prefer header and expand options in Examples
microsoftgraph/microsoft-graph-docs pull request #15065
Opened 2021-11-29 15:14 UTC by cristobal-buenrostro

the purpose of the PR is;

to mention the prefer request header in both pages.
show example of how to use $expand options in GetSubmission.

2021-11-29 15:16 UTC, opbld32 commented
Docs Build status updates of commit _[b9b0492](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9b04926f6ff11475b3ec4e7da1b09a7e8bd3f3c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) | [Details](#user-content-81fcb7e3ceea2c528466a9c5be9260b4-6fad61f4)
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) | [Details](#user-content-fc2eb492c12ff8f0217d4d103e2217b8-6fad61f4)
[api-reference/v1.0/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-1.0&branch=pr-en-us-15065) (>= graph-rest-1.0) | [Details](#user-content-0f10d743bbd31fa195ea5fbfc1b55778-6fad61f4)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-15065) (>= graph-rest-1.0) |

<a id="81fcb7e3ceea2c528466a9c5be9260b4-6fad61f4"></a>
### [api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-list-submissions.md)
 - **Line 306, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="fc2eb492c12ff8f0217d4d103e2217b8-6fad61f4"></a>
### [api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-get.md)
 - **Line 157, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 238, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="0f10d743bbd31fa195ea5fbfc1b55778-6fad61f4"></a>
### [api-reference/v1.0/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationsubmission-get.md)
 - **Line 143, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111291514302010-15065%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T15%3A16%3A24Z&sr=b&sp=r&sig=O7HK876dc8Kj5fVZluHV0vi4Pd1jf2E1cRfQSyCR4nU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 20:37 UTC, opbld34 commented
Docs Build status updates of commit _[a39583b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a39583b35a0b7959cd50c0b2cdb6e9b10c712a1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-15065) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-1.0&branch=pr-en-us-15065) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111302035551931-15065%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T20%3A37%3A44Z&sr=b&sp=r&sig=15EG2FACxRKHZUeik8ArlL4pIPH55bgYy4BvLWYS8ps%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 20:41 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-get.md
> -
Why are we removing this tab? I believe these are automatically generated and we should not manually edit the tabs. 

Is there a reason for this change?

2021-11-30 20:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationsubmission-get.md
> +GET https://graph.microsoft.com/beta/education/classes/59069eb2-2a09-4d90-bb19-2089cc69d613/assignments/80da1069-a635-4913-813f-d775a5470a8f/submissions/869369de-3e5a-89eb-6f2d-83cd88f860b5?$expand=*
This is a v1 document and in the example you are listing a request to the beta endpoint. Please revise to v1.

2021-11-30 20:49 UTC, isvargasmsft requested changes
Hi Cristobal, 

Thank you very much for your work in this PR. Very good shape overall. 

Please take a look at 2 comments:
1. Please clarify the reason to remove the Go snippets. 
2. Please make sure the endpoint in the examples are consistent with the version of the file. 

Feel free to ping me on the side if you have questions. 

Here to help!

Isaac

2021-12-09 00:05 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-get.md
> -
I didn't remove that snipped probably pushed incorrectly or was a conflict.
Done, added back

2021-12-09 00:05 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationsubmission-get.md
> +GET https://graph.microsoft.com/beta/education/classes/59069eb2-2a09-4d90-bb19-2089cc69d613/assignments/80da1069-a635-4913-813f-d775a5470a8f/submissions/869369de-3e5a-89eb-6f2d-83cd88f860b5?$expand=*
done

2021-12-09 00:07 UTC, opbld30 commented
Docs Build status updates of commit _[880e805](https://github.com/microsoftgraph/microsoft-graph-docs/commits/880e8051c02bc1950e83126dd91146425fbe4464)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-15065) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-15065) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/docbugs-nov21/api-reference/v1.0/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-1.0&branch=pr-en-us-15065) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090006083707-15065%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T00%3A07%3A54Z&sr=b&sp=r&sig=%2F2%2FikkQIjzYIp6jprh3VuPjQbZ1oIzTpMZkb6a8MRiE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 14:08 UTC, isvargasmsft approved these changes

2021-12-10 00:22 UTC, merged