[CloudPC]2021-12-2 Graph deployment
microsoftgraph/microsoft-graph-docs pull request #15071
Opened 2021-11-30 03:48 UTC by AshleyYangSZ

This PR contianis
1. adding dnsCheckNameWithInvalidCharacter 101 error type.

2. Adding azureAdDeviceSyncCheckScpNotConfigured-404 error type.

3. Onboarding ChangeUserRole API & Add UserRole/osVersion to CloudPC Entity.

4. Add pendingProvision for cloudPcStatus.

5. Onboard organization setting entity.

2021-11-30 03:50 UTC, opbld31 commented
Docs Build status updates of commit _[f151066](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f151066feb8ff2e5744c1f712fe2ec53a1e70621)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-1138b774fdf9a311a5491f2f0c733a5d-6c8fff62)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-6c8fff62)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |

<a id="1138b774fdf9a311a5491f2f0c733a5d-6c8fff62"></a>
### [api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md)
 - **Line 53, Column 18**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcorganizationsettings.md/'.`````
 - **Line 54, Column 12**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcorganizationsettings.md/'.`````

<a id="0094819f09e3340df09eb0358fea0d24-6c8fff62"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md)
 - **Line 44, Column 12**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcOperatingSystem-values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcoperatingsystem--values'?`````
 - **Line 51, Column 18**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcUserAccountType-values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcuseraccounttype--values'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300348512901-15071%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T03%3A50%3A29Z&sr=b&sp=r&sig=dNBWj8Ss4ovEja5pTfYTsFisByPLj1VnklF%2Fki%2FPEFw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 04:05 UTC, opbld30 commented
Docs Build status updates of commit _[f90e273](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f90e273db33516cf8cfe3aa95f76e336df0fa988)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-1138b774fdf9a311a5491f2f0c733a5d-40334a50)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-40334a50)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="1138b774fdf9a311a5491f2f0c733a5d-40334a50"></a>
### [api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md)
 - **Line 53, Column 18**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcorganizationsettings.md/'.`````
 - **Line 54, Column 12**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcorganizationsettings.md/'.`````

<a id="0094819f09e3340df09eb0358fea0d24-40334a50"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md)
 - **Line 44, Column 12**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcOperatingSystem-values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcoperatingsystem--values'?`````
 - **Line 51, Column 18**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcUserAccountType-values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcuseraccounttype--values'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300404121987-15071%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T04%3A05%3A41Z&sr=b&sp=r&sig=vgxJTIcsExfqyS7Df%2FmI%2FnamQtr60677o%2BqXhw9Vusk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 05:05 UTC, opbld34 commented
Docs Build status updates of commit _[1d7dc26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d7dc26d99517478d04f65ba0eeac79f2176fae7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300503177314-15071%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T05%3A05%3A00Z&sr=b&sp=r&sig=1ncxp2uB%2BngfFzTncTBcxh4Vd3flmBECboGRI8uQKMg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 05:55 UTC, opbld33 commented
Docs Build status updates of commit _[daa16b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/daa16b6dc233447110cd6f309024fdee5e5a88ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-1138b774fdf9a311a5491f2f0c733a5d-8ab74e8a)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-8ab74e8a)
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-c0624c6eac38d673f569f47792d35b61-8ab74e8a)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="1138b774fdf9a311a5491f2f0c733a5d-8ab74e8a"></a>
### [api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md)
 - **Line 53, Column 12**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcoperatingsystem--values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcoperatingsystem-values'?`````
 - **Line 54, Column 18**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcuseraccounttype--values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcuseraccounttype-values'?`````

<a id="0094819f09e3340df09eb0358fea0d24-8ab74e8a"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md)
 - **Line 44, Column 12**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcoperatingsystem--values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcoperatingsystem-values'?`````
 - **Line 51, Column 18**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcuseraccounttype--values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcuseraccounttype-values'?`````

<a id="c0624c6eac38d673f569f47792d35b61-8ab74e8a"></a>
### [api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md)
 - **Line 28, Column 12**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcoperatingsystem--values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcoperatingsystem-values'?`````
 - **Line 29, Column 18**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcuseraccounttype--values' in 'beta/resources/cloudpcorganizationsettings.md', did you mean '#cloudpcuseraccounttype-values'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300553122995-15071%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T05%3A54%3A59Z&sr=b&sp=r&sig=yQojlrVA4oyDOGaQUKjRNgMVehyZr7BhngvzQabkRrk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 06:18 UTC, opbld30 commented
Docs Build status updates of commit _[e8017af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8017af2a22b7618b6c44dff552a578138a938c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300616030938-15071%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T06%3A18%3A00Z&sr=b&sp=r&sig=N0FQwK5YukdzY2zG9XnFsxI9CPheCQ8YaJdKFrsMOW8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 22:34 UTC, JarbasHorst requested changes

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-changeuseraccounttype.md
> +|userAccountType|[cloudPcUserAccountType](../resources/cloudpcorganizationsettings.md#cloudpcuseraccounttype-values)|The account type of user on provisioned Cloud PCs. Possible values: `standardUser`
For consistency, please add "are" after "values". Also, please add a comma after \`administrator\`. Suggested revision:

- Possible values are: \`standardUser\`, \`administrator\`, and \`unknownFutureValue\`.

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-changeuseraccounttype.md
> +POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/cloudPCs/{id}/changeUserAccountType
For clarity and to help users to work with your API, please replace the placeholder {id} with an example of a Cloud PC ID.

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-changeuseraccounttype.md
> +  "userAccountType": "String"
Please, be specific. Replace "String" with the value that you would get when requesting this API.

Please, apply this change also here:

- api-reference/beta/api/cloudpc-reprovision.md

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-reprovision.md
> +|osVersion|[cloudPcOperatingSystem](../resources/cloudpcorganizationsettings.md#cloudpcoperatingsystem-values)|The version of OS to provision on Cloud PCs. Possible values: `windows10`, `windows11` a
For clarity and consistency, please

- add "the" before "OS"
- spell out OS
- add "are" after "values"
- add a comma after `windows11`

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-reprovision.md
> +|userAccountType|[cloudPcUserAccountType](../resources/cloudpcorganizationsettings.md#cloudpcuseraccounttype-values)|The account type of user on provisioned Cloud PCs. Possible values: `standardUser`
For clarity, please 

- add "the" before user
- add the reference link for user
- add "are" after "values"
- add a comma after `administrator`

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcorganizationsettings-get.md
> +Read the properties and relationships of the [cloudPcOrganizationSettings](../resources/cloudpcorganizationsettings.md) of current tenant. And there's only one [cloudPcOrganizationSettings](../resour
Please, rephrase this sentence for clarity:

- ...in the current tenant. A tenant only contains one [cloudPcOrganizationSettings](../resources/cloudpcorganizationsettings.md) object.

2021-12-01 22:34 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcorganizationsettings-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
As a customer, I'd like to know what OData query parameters I can use. For example, "This method supports the $select and $expand OData query parameters to help customize the response.". Could you provide this information?

2021-12-02 10:58 UTC, opbld33 commented
Docs Build status updates of commit _[6fd1ea2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fd1ea2fe5a3ea174fa01cfd3091001b1f3b85da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112021057094825-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T10%3A58%3A50Z&sr=b&sp=r&sig=YNz1%2BrXMRSoTRAIAg6mO0YzQnWcvpsaL72lwQm2gvqo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 11:05 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-changeuseraccounttype.md
> +Change the account type of the user on a specific Cloud PC.
@JarbasHorst The provisioned CloudPC will belong to an end user, he/she can sign in with his account, by default the end user is not the local admin of the CloudPC. This API is to tell our service which type of the user can be set, admin or just end user. So the user is not an Graph entity just refer to the CloudPC's user. Is it OK with out link?

2021-12-02 11:11 UTC, opbld33 commented
Docs Build status updates of commit _[af86668](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af86668d5c77d194e2ac1c0b1732111c1345f325)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112021109471675-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T11%3A11%3A20Z&sr=b&sp=r&sig=dP%2Fbbq9JL%2BScyGp4jO767bJrwZd53vhn5H1nq6k6WBU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 19:26 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-changeuseraccounttype.md
> +Change the account type of the user on a specific Cloud PC.
Thanks for clarifying. It makes sense to leave it as is.

2021-12-06 21:01 UTC, JarbasHorst requested changes

2021-12-08 04:09 UTC, opbld33 commented
Docs Build status updates of commit _[5f79911](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f79911ea26b83176f685c26e01254fcf14a68b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112080408097039-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T04%3A09%3A52Z&sr=b&sp=r&sig=A28ErTvv%2BaoYS4YRd7kbM0U%2FxFuoDfQW%2Bx2a9eeD3nM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 04:11 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcorganizationsettings-get.md
> +GET https://graph.microsoft.com/beta/cloudPcOrganizationSettings
Correct! Updated.

2021-12-08 05:14 UTC, opbld30 commented
Docs Build status updates of commit _[d68619d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d68619dc111232f9239884272ebe3c8da4417977)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b9b6b348)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-b9b6b348"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 9638, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112080512243753-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T05%3A14%3A19Z&sr=b&sp=r&sig=RKoBEpDEEyRRFNiuhbraQ31bMxdRAPeCZlMzHL%2FQd8g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 05:26 UTC, opbld32 commented
Docs Build status updates of commit _[e96c444](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e96c444a2735371f7cb207ee819dd4721452baeb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f1d1dd7c)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-f1d1dd7c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 9638, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090524398530-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T05%3A26%3A13Z&sr=b&sp=r&sig=pc8UKE3l6LF0CVCZYy%2FNEKsY4VGf62Qv5mCI7RCOTDY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 05:43 UTC, opbld31 commented
Docs Build status updates of commit _[7f5de26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f5de262a796a2fa76e9b0dc04a16f34e50db6eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-04407399)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-04407399"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 9638, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090541149014-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T05%3A43%3A13Z&sr=b&sp=r&sig=DFzRR91hlO2rT1VbzdbBLMXdWEtseyJHDFTK2uST6Sw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-10 02:38 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Id": "b525ecf3-5191-11ec-a817-519c224fca78",
Sorry, as I used doc generator created this changelog, and the IDs looks similar, thus I supposed they're same. Already updated.

2021-12-10 02:49 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpc.md
> +|[Get cloudPC remote action results](../api/manageddevice-getcloudpcremoteactionresults.md)|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|Check the [Cloud PC-specified remote
Thank you so much for your detailed review and caught lots of typo and error. All updated.

2021-12-10 02:50 UTC, opbld30 commented
Docs Build status updates of commit _[38404a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38404a710e54c15d06326df4ecfad1e91cf1d357)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-07079a91)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-07079a91"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 9642, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112100248435622-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-10T02%3A50%3A21Z&sr=b&sp=r&sig=B0r88YxsCKur6hn15XTcHHvMn2VrxOQtP2TsYGy%2BDwM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-14 21:55 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Id": "b525ecf3-5191-11ec-a817-519c224fca78",
No worries. Thanks for the update.

2021-12-14 22:17 UTC, JarbasHorst requested changes

2021-12-14 22:17 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcorganizationsettings-get.md
> +Read the properties and relationships of a [cloudPcOrganizationSettings](../resources/cloudpcorganizationsettings.md) from the current tenant, which has only one **cloudPcOrganizationSettings** objec
Sorry for the confusion, this might have been a copy and paste issue. In this case, "a" should be replace with "the". Suggested revision:

- ...relationships of the [cloudPcOrganizationSettings]...

2021-12-14 22:17 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Id": "b5238b12-5191-11ec-a817-519c224fca78",
Please, replace "b5238b12-5191-11ec-a817-519c224fca78" with "b50951e4-5191-11ec-a817-519c224fca78".

2022-01-04 05:34 UTC, opbld33 commented
Docs Build status updates of commit _[4ec587a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ec587acb5a938dc147b9b4537d05866a6b07b79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c6b1243e)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-c6b1243e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 12514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040531178734-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T05%3A34%3A09Z&sr=b&sp=r&sig=1R45LW6uKU7MJy0byJXeZ9pEwxhx8iM4Es4bd6Iilaw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 20:21 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2022-01-05 01:16 UTC, opbld32 commented
Docs Build status updates of commit _[4b292aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b292aa5c979d6b3216153327383b289eb99122f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-759593a5)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-759593a5"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 12514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050113502789-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T01%3A15%3A59Z&sr=b&sp=r&sig=NpxLSOw%2FZgjYl0jHNTiVucyF2kAMYL7oAzai8q4Yeac%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 01:28 UTC, Lauragra commented on api-reference/beta/api/cloudpcorganizationsettings-get.md
> +Read the properties and relationships of the [cloudPcOrganizationSettings](../resources/cloudpcorganizationsettings.md) from the current tenant, which has only one **cloudPcOrganizationSettings** obj
I think that these are two separate thoughts. Suggest revising as:

Read the properties and relationships of the [cloudPcOrganizationSettings](../resources/cloudpcorganizationsettings.md) from the current tenant.

A tenant has only one **cloudPcOrganizationSettings** object.

2022-01-05 01:31 UTC, Lauragra commented on api-reference/beta/api/cloudpcorganizationsettings-update.md
> +Update the properties of the [cloudPcOrganizationSettings](../resources/cloudpcorganizationsettings.md) object in a tenant, which has only one **cloudPcOrganizationSettings** object.
Same comment here. Alternatively, you can state this in the resource topic only, since it's slightly tangential to the update operation, and you have a link to the resource topic.

2022-01-05 02:06 UTC, Lauragra commented on api-reference/beta/resources/cloudpcorganizationsettings.md
> +  "userAccountType": "String",
Please show the properties here in alphabetical order.

2022-01-05 03:24 UTC, opbld31 commented
Docs Build status updates of commit _[85cd1a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85cd1a98ad26935f7bef6ef1d784cca70c19cf5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-648385a2)
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-648385a2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml)
 - **Line 12514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050322186054-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T03%3A24%3A04Z&sr=b&sp=r&sig=BBXIFjk4KJN9Z%2Bs9WHzDH2ejj9C%2BeRS%2BompfSNYlMMc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-08 02:26 UTC, opbld34 commented
Docs Build status updates of commit _[1b56de4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b56de4a06b7eab741a25101c185d9c36b427e8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201080224278655-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-08T02%3A26%3A26Z&sr=b&sp=r&sig=jvUTW5HB0CfHgtenVBQglM3bJakRlW83mrED1iJUjRQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-08 02:26 UTC, Lauragra commented on changelog/Microsoft.CloudManagedDesktop.json
> +        {
Are the changes in the diff here primarily formatting changes? Can you provide the ID for the ChangeList item that applies specifically to this PR? Thanks.

2022-01-08 02:28 UTC, opbld32 commented
Docs Build status updates of commit _[1b56de4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b56de4a06b7eab741a25101c185d9c36b427e8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201080224381191-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-08T02%3A28%3A33Z&sr=b&sp=r&sig=vgGQDlnmE8%2B%2BGEW%2B8ZM%2BXq%2BGXLrYDnR0rKmCIcXpNnk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-09 12:44 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +        {
b50951e4-5191-11ec-a817-519c224fca78 This is the ID for this PR's changeList, others are only formatting, no content change.

2022-01-19 03:43 UTC, Lauragra approved these changes

2022-01-19 03:45 UTC, opbld30 commented
Docs Build status updates of commit _[716876b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/716876bc469f22a84dcbc9bfcfe1820196477bb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-changeuseraccounttype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-changeuseraccounttype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-changeuseraccounttype?view=graph-rest-beta&branch=pr-en-us-15071) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/2021-12-2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190343076446-15071%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T03%3A45%3A27Z&sr=b&sp=r&sig=6mz5foa9SV1x0jSAp4f%2B4xAxmF9oVohmjo7UGazOAE4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 03:50 UTC, merged