v1.0 Doc updates - user assignments, reassign submission and addToCalendar
microsoftgraph/microsoft-graph-docs pull request #15094
Opened 2021-12-01 17:45 UTC by cristobal-buenrostro

update v1.0 with current beta changes

* reassign submission
* user assignments
* addToCalendar

2021-12-01 17:47 UTC, opbld30 commented
Docs Build status updates of commit _[89acdad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89acdadbe96a46472112e4543ee8c92b12835bde)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :x:Error | | [Details](#user-content-5b8a42be6ebf0c4b83650a471998d059-5d2c718a)
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :x:Error | | [Details](#user-content-91bc6aabd5b9e1aa60b4ca142c41bf62-5d2c718a)

<a id="5b8a42be6ebf0c4b83650a471998d059-5d2c718a"></a>
### [api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/educationsubmission-reassign-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/educationsubmission-reassign-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/educationsubmission-reassign-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/educationsubmission-reassign-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/educationsubmission-reassign-go-snippets.md'.`````
 - **Line 164, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/educationsubmission-prefer-reassign-csharp-snippets.md'.`````
 - **Line 168, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/educationsubmission-prefer-reassign-javascript-snippets.md'.`````
 - **Line 172, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/educationsubmission-prefer-reassign-objc-snippets.md'.`````
 - **Line 176, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/educationsubmission-prefer-reassign-java-snippets.md'.`````
 - **Line 180, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/educationsubmission-prefer-reassign-go-snippets.md'.`````

<a id="91bc6aabd5b9e1aa60b4ca142c41bf62-5d2c718a"></a>
### [api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md)
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-me-assignments-csharp-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-me-assignments-javascript-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-me-assignments-objc-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-me-assignments-java-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-me-assignments-go-snippets.md'.`````
 - **Line 212, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-user-assignments-csharp-snippets.md'.`````
 - **Line 216, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-user-assignments-javascript-snippets.md'.`````
 - **Line 220, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-user-assignments-objc-snippets.md'.`````
 - **Line 224, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-user-assignments-java-snippets.md'.`````
 - **Line 228, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-user-assignments-go-snippets.md'.`````
 - **Line 354, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-user-assignments-expand-submissions-csharp-snippets.md'.`````
 - **Line 358, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-user-assignments-expand-submissions-javascript-snippets.md'.`````
 - **Line 362, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-user-assignments-expand-submissions-objc-snippets.md'.`````
 - **Line 366, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-user-assignments-expand-submissions-java-snippets.md'.`````
 - **Line 370, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-user-assignments-expand-submissions-go-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011745426680-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T17%3A47%3A05Z&sr=b&sp=r&sig=ADwnJf48aFv92vUBm1%2BqyFALDuNT4yG%2BwKb0rfjhp5U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 17:57 UTC, opbld32 commented
Docs Build status updates of commit _[6e65ab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e65ab9b08d03a05e5d4adb38ba3176f33c81cc6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :x:Error | | [Details](#user-content-91bc6aabd5b9e1aa60b4ca142c41bf62-6570d476)

<a id="91bc6aabd5b9e1aa60b4ca142c41bf62-6570d476"></a>
### [api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md)
 - **Line 314, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-user-assignments-expand-submissions-csharp-snippets.md'.`````
 - **Line 318, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-user-assignments-expand-submissions-javascript-snippets.md'.`````
 - **Line 322, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-user-assignments-expand-submissions-objc-snippets.md'.`````
 - **Line 326, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-user-assignments-expand-submissions-java-snippets.md'.`````
 - **Line 330, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-user-assignments-expand-submissions-go-snippets.md'.`````
 - **Line 304, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011756068974-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T17%3A57%3A23Z&sr=b&sp=r&sig=QU1xSnr%2FOwly8x%2FhjUcgp7F%2BtaY7Lb2neoxpg%2F9JHYo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 18:00 UTC, opbld30 commented
Docs Build status updates of commit _[622172c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/622172c6d5a4be264038d3711f21ed4cdbadf5c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011758424054-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T18%3A00%3A37Z&sr=b&sp=r&sig=5zbb8Eoxbtm7NS3oL87g0egOX%2FoGjjTvPaT0glEctGg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-10 17:43 UTC, opbld31 commented
Docs Build status updates of commit _[89989da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89989dadad98bf502505d03a65001d1fe4b9c1dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112101741349323-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-10T17%3A43%3A15Z&sr=b&sp=r&sig=o6cE7dC1kKEbtEOD5h8H4UvmZB%2B%2BYICqK8Fw1ddbLi8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-13 19:37 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +# [HTTP](#tab/http)
Line 304: This should be automatically generated. Please remove this line. Apply to all files in this PR if and where applicable.

2021-12-13 19:38 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +```msgraph-interactive
310: Please replace `msgraph-interactive` with `http`.

2021-12-13 19:38 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +```msgraph-interactive
SImilar observation above.

2021-12-13 19:38 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +# [HTTP](#tab/http)
Similar above.

2021-12-14 20:19 UTC, Danielabom commented on api-reference/v1.0/api/educationsubmission-reassign.md
> +# [HTTP](#tab/http)
Line 133: Please remove this line. Snippets are automatically generated.

2021-12-14 22:09 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +Returns a list of assignments assigned to a user for all classes.
Please include reference links in the mentions of assignment and classes resource types.

2021-12-14 22:10 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This utility namespace allows a caller to find all the assignments belonging to a student or a teacher in a single call rather than having to request assignments from each class. The assignment list
Bold the mentions of resource types like assignments and class.

2021-12-14 22:10 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This utility namespace allows a caller to find all the assignments belonging to a student or a teacher in a single call rather than having to request assignments from each class. The assignment list
Are the users familiar with the concept of a namespace? What do you mean when you say "class namespace"?

2021-12-14 22:16 UTC, Danielabom requested changes
Hi @cristobal-buenrostro,

Please review some comments we shared. Thanks in advance!

2021-12-15 16:47 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This utility namespace allows a caller to find all the assignments belonging to a student or a teacher in a single call rather than having to request assignments from each class. The assignment list
@isvargasmsft 
yes, they are familiar =P.
class namespace = "/education/**classes**/{id}/assignments/{id}", all the endpoints related to assignments under classes namespace.

2021-12-15 16:50 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +# [HTTP](#tab/http)
done

2021-12-15 16:50 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +```msgraph-interactive
done

2021-12-15 16:50 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +# [HTTP](#tab/http)
done

2021-12-15 16:50 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationsubmission-reassign.md
> +# [HTTP](#tab/http)
done

2021-12-15 16:51 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This utility namespace allows a caller to find all the assignments belonging to a student or a teacher in a single call rather than having to request assignments from each class. The assignment list
done

2021-12-15 16:52 UTC, opbld33 commented
Docs Build status updates of commit _[81d397d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81d397d03f5992ab988ec1af845bf8897d357b8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112151649533482-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T16%3A52%3A00Z&sr=b&sp=r&sig=FqryUe3V3Z1%2BH3x7tvvQqNK2uPNOdXYGcEkROFcPcNY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 16:55 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +Returns a list of assignments assigned to a user for all classes.
done

2021-12-15 16:56 UTC, opbld34 commented
Docs Build status updates of commit _[646fc87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/646fc8704b57d4628b9931a3d81c69475ab3f234)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112151655027311-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T16%3A56%3A58Z&sr=b&sp=r&sig=KnHxEqIcZyYSFTB%2F42TDt3y7gFESfyZs5I5kmKRz2H4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 17:12 UTC, opbld31 commented
Docs Build status updates of commit _[e9cc7bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9cc7bc932c1e179607343ad816488f59fe5127d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112151710170105-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T17%3A12%3A03Z&sr=b&sp=r&sig=QayBSPppdIxZV95dGotYSdt16CMPamy%2FfDnnP9irSzY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 15:32 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> +          "ApiChange": "Resource",
Line 55: This value should be Relationship instead of Resource.

2021-12-17 15:39 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +Returns a list of assignments assigned to a user for all classes.
Please add reference links to assignments, user and classes. And bold subsequent mentions.

2021-12-17 15:44 UTC, opbld32 commented
Docs Build status updates of commit _[66a536c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66a536cdfa75d7f6e477cba5c020f39a585a75e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112171542443936-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T15%3A44%3A41Z&sr=b&sp=r&sig=dlqiI8172GEG4bhjRc0ShoqSU6iSvgWPofhE5nuXFh8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 15:59 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This utility namespace allows a caller to find all the **[educationAssignment](../resources/educationassignment.md)** objects belonging to a student or a teacher in a single call rather than having t
For clarity, please rephrase to "This method allows a caller...

2021-12-17 16:00 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This utility namespace allows a caller to find all the **[educationAssignment](../resources/educationassignment.md)** objects belonging to a student or a teacher in a single call rather than having t
please remove the bolding when you are adding links. The rule is to add links in the first mention and bold subsequent mentions.

2021-12-17 16:11 UTC, isvargasmsft commented on api-reference/v1.0/api/educationuser-list-assignments.md
> +This method supports the [OData Query Parameters](/graph/query-parameters) to help customize the response.
I'd deeply appreciate if you can specify which query parameters are supported.

2021-12-17 16:26 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationSubmissionStatus"
I am noticing something about this enum:
- In the CSDL it seems like we are just adding a member to the enum, but in the enums.md it seems we are adding the entire enum from scratch. Could you please clarify? If the latter is true, then we need to change this entry to reflect that the enum is completely new to v1.

2021-12-17 16:35 UTC, isvargasmsft requested changes
Please take a look at some comments for consistency and completeness. 

Thank you!

2021-12-17 16:54 UTC, cristobal-buenrostro commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationSubmissionStatus"
we are only adding a new member, but I noticed that enums.md file didn't have the enum. I just added it there.

2021-12-17 16:57 UTC, opbld32 commented
Docs Build status updates of commit _[a3af8f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3af8f0fffc9229cd8c7ff687f37159a0bc8ae24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112171655596694-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T16%3A57%3A49Z&sr=b&sp=r&sig=s7rSGqjydcNWuavBq%2BXSKTUaTvdmgharvktZ%2FXinBXo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-18 00:04 UTC, opbld32 commented
Docs Build status updates of commit _[88f70be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88f70be2d78c90edeb5e45eba11c7f8055a26b7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/education-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15094) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/v1.0docs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112180001459695-15094%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-18T00%3A04%3A18Z&sr=b&sp=r&sig=l9iDQJtZh1XgsDXL6X6%2B8tZCOxQ9Q6cRrmLiO%2Bk5Zvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-18 00:04 UTC, isvargasmsft approved these changes

2021-12-18 00:08 UTC, merged