introduce policy and OBO to entitlement management in Graph v1.0
microsoftgraph/microsoft-graph-docs pull request #15098
Opened 2021-12-01 19:53 UTC by markwahl-msft

2021-12-01 19:55 UTC, opbld32 commented
Docs Build status updates of commit _[c9a0bd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9a0bd180665f97bc706cc6881f22bd8ce4a7295)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-caf65d576218e8d250798c27ce7df3e1-a28e0c92)
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-b159c315bae899fd9ba92cbdf499c081-a28e0c92)
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-6faf67f04c319470adccff7980bae394-a28e0c92)
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

<a id="caf65d576218e8d250798c27ce7df3e1-a28e0c92"></a>
### [api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md)
 - **Line 52, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/requestorsettings.md'.`````
 - **Line 53, Column 26**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/approvalsettings.md'.`````

<a id="b159c315bae899fd9ba92cbdf499c081-a28e0c92"></a>
### [api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md)
 - **Line 13, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageapprovalsettings.md'.`````

<a id="6faf67f04c319470adccff7980bae394-a28e0c92"></a>
### [api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md)
 - **Line 15, Column 40**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/entitlementmanagement-post-assignmentrequests.md'.`````
 - **Line 20, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentpolicy-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011953358593-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T19%3A55%3A22Z&sr=b&sp=r&sig=zFW%2BVo2doyhPTjAVTWEKScKSdXm3lOGq7uao7VAH1q0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 23:02 UTC, opbld32 commented
Docs Build status updates of commit _[d61d49d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d61d49d69ea2f306a0a6d763dec65155bd7dc25c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-6faf67f04c319470adccff7980bae394-a0d227f7)
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

<a id="6faf67f04c319470adccff7980bae394-a0d227f7"></a>
### [api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md)
 - **Line 15, Column 40**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/entitlementmanagement-post-assignmentrequests.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112012300581155-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T23%3A02%3A31Z&sr=b&sp=r&sig=kwSlm36MVZdK6wawOTYHRHQy8oI51u9z2nmIU8yfhqk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 23:26 UTC, opbld30 commented
Docs Build status updates of commit _[35403cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35403cf0da43f89adfd13a26f8c425c5332a3e3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112012324333699-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T23%3A26%3A21Z&sr=b&sp=r&sig=mXlLskMR4eRs6%2FNF3cFRqGRl2cJr%2BeVKpX5nhhnoZdU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 20:50 UTC, opbld32 commented
Docs Build status updates of commit _[ea20796](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea207965c782875d97f80b72030fae532e611c3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112022048373927-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T20%3A50%3A29Z&sr=b&sp=r&sig=wElJlK30Q4%2B1u5mBm2GLX4wKPzIwCYbnIxmLSBg8TAY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 22:53 UTC, opbld32 commented
Docs Build status updates of commit _[4caff83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4caff8340a89682656d71a90978661468c22801a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112022251313156-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T22%3A53%3A27Z&sr=b&sp=r&sig=itZTzQD0YlGTLWiQ7FDxJP0ZnrKl5G99Lgr%2BJXsM4HM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 23:08 UTC, opbld33 commented
Docs Build status updates of commit _[c9fa6a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9fa6a19244758dd06e52ec539d922f17c0debd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112022306578022-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T23%3A08%3A32Z&sr=b&sp=r&sig=j8HLQVH8H2sIJ8qnLn4UGw%2B5pZw%2B4uEUBbytoVlM7Ls%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 20:25 UTC, opbld34 commented
Docs Build status updates of commit _[922a94b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/922a94ba44ee0e664db57cb70a6dc993e3226aaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032023023822-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T20%3A25%3A16Z&sr=b&sp=r&sig=%2B2tBO%2BH4aVehcXj9isw6oEZZiNQQKjHg3608N4qmTTI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Pos [...]

2021-12-03 20:30 UTC, opbld33 commented
Docs Build status updates of commit _[dd7257c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd7257c2de01d09e2c979307d963ebbd494a8cd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032028141950-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T20%3A30%3A02Z&sr=b&sp=r&sig=lJyuw4S6J7ULyd9IRp0vqdtUqtFoyPbfMDD5u59QogY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post yo [...]

2021-12-03 20:32 UTC, opbld34 commented
Docs Build status updates of commit _[74dbb87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74dbb873e83d949dc8c5e2d3387dd517071b754e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032028241331-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T20%3A31%3A59Z&sr=b&sp=r&sig=OBzH0AMOGNWlQGb3loT%2BavJRmiIMVPMTyQXqQem%2BQFI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Pos [...]

2021-12-03 23:11 UTC, opbld33 commented
Docs Build status updates of commit _[265acdd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/265acddcf3e56364c36b23fff13e4c58fb90982d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032310215991-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T23%3A11%3A54Z&sr=b&sp=r&sig=GFXHJ9JSPmu3cj%2B3Bf%2Bcru%2B8xjJseDbEk6n9qxxSPtk%3D).

**Note:** Broken links written as relative paths a [...]

2021-12-09 17:38 UTC, opbld31 commented
Docs Build status updates of commit _[74f1a56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74f1a56cc5045a693c08bbb917c2d648f77964e8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a08ae2b5)

<a id="a08ae2b5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112091738091902-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T17%3A38%3A29Z&sr=b&sp=r&sig=E6%2Fc8pDqgFNH%2BhAgrmbUbspSh5dD%2BSIX49nicl4lhvg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 17:43 UTC, opbld32 commented
Docs Build status updates of commit _[aa2fa69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa2fa6908016ade6ac99606a03b4fb481749d6e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-6faf67f04c319470adccff7980bae394-18910148)
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-root.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-3f351afe4b69b7f0922dd53d3f03e12b-18910148)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-18910148)
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) | [Details](#user-content-f4d871dcc26ef03da09086aa8cf72fc7-18910148)
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

<a id="6faf67f04c319470adccff7980bae394-18910148"></a>
### [api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md)
 - **Line 15, Column 40**: **[Warning: file-not-found - [See documentation](https://r [...]

2021-12-09 19:45 UTC, opbld30 commented
Docs Build status updates of commit _[967c19b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/967c19bd26e66c982f7bacbee506f89b134c6d90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112091943322182-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T19%3A45%3A13Z&sr=b&sp=r&sig=LISvc2P94QugiJmqnTJoSzebtAONPAM7uZ8aIUb%2FFmY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post  [...]

2022-01-04 21:15 UTC, opbld31 commented
Docs Build status updates of commit _[883aba5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/883aba5e44dd81a18d9624c5fa1b9528413eb1a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042113142878-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T21%3A15%3A24Z&sr=b&sp=r&sig=%2BQJX8B2Jlj3UpO6Q72YZZlujXq00fXZZJbz1%2F857dIE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></l [...]

2022-01-05 19:44 UTC, opbld34 commented
Docs Build status updates of commit _[8940107](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8940107b96de6e7a06747fdc781d979bfb9dd3c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051942315310-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T19%3A44%3A35Z&sr=b&sp=r&sig=veFDLTu0tVDep1HVv%2FFqUiONZrATvbcmcsJe7hcpiyI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li> [...]

2022-01-07 18:24 UTC, opbld32 commented
Docs Build status updates of commit _[47976a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47976a0e52a170901fdedb20d45a97800ceaffa6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201071822279809-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T18%3A24%3A35Z&sr=b&sp=r&sig=hlJmSgJx2rBGE3CQ57%2FKP1CrFExcxfU0paBb539yxLM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li> [...]

2022-01-17 18:33 UTC, FaithOmbongi commented
Heads up @markwahl-msft, I think I see the schema changes for this docs PR are live. Kindly expedite the work on this PR so that the docs can be published in good time.

2022-01-20 17:35 UTC, opbld31 commented
Docs Build status updates of commit _[76af3e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76af3e3ff0f72339f44f98f3f04926b6dc390a0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201201732469777-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T17%3A35%3A07Z&sr=b&sp=r&sig=XHDsBYVdu1Z%2FWPlzGskvgq5dcBHwQuNXsLjgWR3jmfk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li [...]

2022-01-29 00:22 UTC, opbld32 commented
Docs Build status updates of commit _[b7c3e9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7c3e9de07febbd9b104d5e47ab35d96e734c3f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290020145079-15098%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T00%3A22%3A33Z&sr=b&sp=r&sig=kttrZ9fqbGq9U1UjQigOJp%2FMyq3jm7Me67V68SF2aNI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li [...]

2022-01-29 01:00 UTC, opbld30 commented
Docs Build status updates of commit _[c21c92a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c21c92aa991c6e999d7f00ee56c8131bc0d7e452)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290058218850-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-02-08 18:52 UTC, opbld33 commented
Docs Build status updates of commit _[c4bbd59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4bbd59896df32e34c1ccfbfac985c8d31ac3282)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081849299427-15098%5Cworkflow_report.html?sv=2020-08-04&se= [...]

2022-02-08 18:59 UTC, opbld30 commented
Docs Build status updates of commit _[7bf61ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bf61eea652b261d342f38186cc856e3ac590df5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081856357402-15098%5Cworkflow_report.html?sv=2020-08-04&se= [...]

2022-02-22 17:26 UTC, opbld31 commented
Docs Build status updates of commit _[c73ee5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c73ee5c7bf462c17b811c9778dd80e49c7045d8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202221724149236-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-04 23:13 UTC, Lauragra commented
@markwahl-msft , is this PR ready for a content review? The schema for this PR has already been released. Thanks.

2022-03-06 23:57 UTC, opbld30 commented
Docs Build status updates of commit _[5d268f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d268f1a4ad1823eb57ce05a48921847b2b26150)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203062355312044-15098%5Cworkflow_report.html?sv=2020-08-04&se= [...]

2022-03-09 09:12 UTC, FaithOmbongi requested changes
Thank you @markwahl-msft for your comprehensive work on this PR. I've suggested a number of changes - some of which will make descriptions in v1.0 docs different from beta docs; but better to correct here then later sync beta docs to catch up.
- Document the **assignmentPolicy** relationship in the accessPackageAssignment resource doc.
- You've got more changes than currently documented in the changelog. Schema PR 5428695 has all the records you'll need.
- You can move your changelog to the Microsoft.IGAELM.json file.
- Please document targetApplicationOwners and targetManager in the subjectSet resource type doc

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
> +|reviewSettings|[accessPackageReviewSettings](../resources/accesspackageassignmentreviewsettings.md)|Settings for access reviews of assignments from this policy.|
Let's align these descriptions with the changes you make to the main Properties table in the resource topic.

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md
> +description: "List the accessPackageAssignmentPolicy objects."
```suggestion
title: "List assignmentPolicies"
description: "List the accessPackageAssignmentPolicy objects."
```

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), retrieve a list of [accessPackageAssignmentPolicy](../resources/accesspackageassignmentpolicy.md) objects. If the
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), retrieve a list of [accessPackageAssignmentPolicy](../resources/accesspackageassignmentpolicy.md) objects. If the delegated user is in a directory role, the resulting list includes all the assignment policies that the caller has access to read, across all catalogs and access packages. If the delegated user is an access package manager or catalog owner, they should instead retrieve the policies for the access packages they can read with [list accessPackages](entitlementmanagement-list-accesspackages.md) by including `$expand=accessPackageAssignmentPolicies` as a query parameter.
```

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve an access package assignment policy with a specified display name, include `$filter=di
Sounds like all 3 are supported going by your previous descriptions
```suggestion
This method supports some of the `$filter`, `$select`, and `$expand` OData query parameters to help customize the response. For example, to retrieve an access package assignment policy with a specified display name, include `$filter=displayName eq 'Employee sales support'` in the query. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
> +title: "Create accessPackageAssignmentPolicy"
```suggestion
title: "Create assignmentPolicies"
```

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
> +# Create accessPackageAssignmentPolicy
```suggestion
# Create assignmentPolicies
```

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
> +|accessPackage|[accessPackage](../resources/accesspackage.md)| Access package containing the policy.|
Let's sync these descriptions with those you'll apply to the main Properties table in the resource topic.

2022-03-09 09:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
> +}
Maybe no effect, but real values will be good here and in the response object.

2022-03-09 09:12 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "ChangeList": [
This PR contains more changes than this. You can copy the changelog from internal schema PR 5428695 - might require a few fixes due to a bug.

Also, feel free to use the Microsoft.IGAELM.json file instead of this. Will save you merge conflicts between now and merge.

2022-03-23 16:37 UTC, opbld30 commented
Docs Build status updates of commit _[e88a318](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e88a318df36b30b477c8921239be5a4f0525d1ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203231635326572-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:32 UTC, opbld33 commented
Docs Build status updates of commit _[b01805d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b01805d6ea7af5f7035a6224b18fcff623c4a6d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242029481631-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:33 UTC, opbld30 commented
Docs Build status updates of commit _[67c4e1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67c4e1da313e6d3a444115f7fca344576a3f1761)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242031085168-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:36 UTC, opbld34 commented
Docs Build status updates of commit _[67c4e1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67c4e1da313e6d3a444115f7fca344576a3f1761)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242032494486-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:38 UTC, opbld31 commented
Docs Build status updates of commit _[2d9c169](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d9c169e82ffdd75e828f0c8a75435bae3b5cd39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242035342623-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:40 UTC, opbld34 commented
Docs Build status updates of commit _[74274b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74274b80196852dc4e0537e05537f9e0a5f0f6e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242037263980-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:43 UTC, opbld32 commented
Docs Build status updates of commit _[9855b6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9855b6b9a357f437102a527b76342965d1b1e9ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242040505944-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:46 UTC, opbld30 commented
Docs Build status updates of commit _[9857f7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9857f7a04e88dcbddccd4ed8573585c817f8499d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242044069867-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:48 UTC, opbld34 commented
Docs Build status updates of commit _[76168b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76168b05fccc7ff7d2caa2005aede28b5e619556)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242045050710-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:50 UTC, opbld33 commented
Docs Build status updates of commit _[22a1d40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22a1d4017d2e3600b57c8acaeeddfabf0b3d1e67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242046409267-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 20:59 UTC, opbld31 commented
Docs Build status updates of commit _[46f95be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46f95be6f173e35f276c75c343bc60f16fcad264)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242047312958-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:01 UTC, opbld34 commented
Docs Build status updates of commit _[58a7666](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58a766650d69edcffacd1f421cf8c1cae5fd4777)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242056324858-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:05 UTC, opbld33 commented
Docs Build status updates of commit _[d5b0622](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5b0622c20f4f4ffaf8b46572f725a527a3ff129)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242100102297-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:10 UTC, opbld32 commented
Docs Build status updates of commit _[9b0c798](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b0c798fa7077a50170007a95af9c7f5bbf32eda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242057350276-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:12 UTC, opbld32 commented
Docs Build status updates of commit _[fcc46fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcc46fab329d56d70070ff5ce138cbc385133a46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242058411811-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:14 UTC, opbld34 commented
Docs Build status updates of commit _[e76d2e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e76d2e0a6dc348b4e7993dc5ef2c716dea6b57b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242049569692-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:17 UTC, opbld31 commented
Docs Build status updates of commit _[cf2266c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf2266c08505ff25dc35f955e31d3f61054386e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242050243991-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:40 UTC, opbld32 commented
Docs Build status updates of commit _[474e5ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/474e5ec88d026f61245309c4a26c186956886d28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242137431118-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 21:42 UTC, opbld34 commented
Docs Build status updates of commit _[9942f16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9942f16ae3a5440792b0f44381538e5c4b377dc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242139174373-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 23:25 UTC, opbld30 commented
Docs Build status updates of commit _[f96fe14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f96fe1474b75e13e47402d3b3a334986dd812abb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242320456286-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 23:27 UTC, opbld31 commented
Docs Build status updates of commit _[010c2f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/010c2f714ad64a4c1ef3cf4e2aa169d6ebbde221)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242322359035-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 23:31 UTC, opbld32 commented
Docs Build status updates of commit _[e61dff9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e61dff972cfb5578dfd7fffcd08aa1ed82faef35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242326592422-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 23:36 UTC, opbld31 commented
Docs Build status updates of commit _[010c2f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/010c2f714ad64a4c1ef3cf4e2aa169d6ebbde221)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242324454818-15098%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-24 23:53 UTC, opbld34 commented
Docs Build status updates of commit _[c79e2fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c79e2fc9d80c0beae1aa88df109565edd9c0f15b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildusersto [...]

2022-03-25 17:34 UTC, opbld33 commented
Docs Build status updates of commit _[a6894eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6894ebacaabe468ca0153d603d06098f22d8c15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-03-25 19:14 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentpolicy.md
> +|catalog|[accessPackageCatalog](../resources/accesspackagecatalog.md)|Catalog of access package containing this policy. Read-only.|
Nope, as in beta, a catalog contains access packages, and an access package contains policies, assignments and requests.  I'm going to leave these two strings as they are, and in entitlementmanagement-post-assignmentpolicies, clarify that when creating a policy, the access package that will contain that policy must already exist.

2022-03-25 19:15 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md
> +Used for the requestor settings of an [access package assignment policy](accesspackageassignmentpolicy.md). Provides additional settings to select who can create a request for an access package on th
Nope, the access package still contains the policy, the settings control who can request.  I expanded it to "Provides additional settings to select who can create a request for an access package on that policy, and what they can include in their request."

2022-03-25 19:16 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md
> +Used for the access reviews of access review assignments, configured in an [access package assignment policy](accesspackageassignmentpolicy.md). Provides additional settings to select who must review
Yep and there was a typo, access review assignments should have been access package assignments.  Simplified it to "Settings configured in an [access package assignment policy] for the access reviews of assignments to an access package that were made through that policy. Provides settings to select reviewers of those assignments, and how often the assignments must be reviewed."

2022-03-25 19:17 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md
> +|schedule|[entitlementManagementSchedule](../resources/entitlementmanagementschedule.md)|When the first review should start and how often it should recur.|
updating, thanks.

2022-03-25 19:19 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md
> +description: "Used for the request approval settings of an access package assignment policy. Provides additional settings to select who must approve each request."
Simplifying it to "Specifies the settings for approval of a request for an access package assignment in an access package assignment policy."

2022-03-25 19:20 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md
> +Used for the request approval settings of an [access package assignment policy](accesspackageassignmentpolicy.md). Provides additional settings to select who must approve each request.
updating, thanks.

2022-03-25 19:20 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md
> +|stages|[accessPackageApprovalStage](../resources/accesspackageapprovalstage.md) collection|If approval is required, the one or two elements of this collection define each of the stages of approval.
updated.  FYI three stages of approval just went GA so included that here too.

2022-03-25 19:29 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
> +|reviewSettings|[accessPackageReviewSettings](../resources/accesspackageassignmentreviewsettings.md)|Settings for access reviews of assignments from this policy.|
updating, thanks

2022-03-25 19:29 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackageassignmentpolicy-get.md
> +}
added, thanks

2022-03-25 19:29 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
> +|accessPackage|[accessPackage](../resources/accesspackage.md)| Access package containing the policy.|
updated, thanks

2022-03-25 19:31 UTC, opbld32 commented
Docs Build status updates of commit _[3a952eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a952eb7815a41d26138356d7d3266bf1db2539f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-03-25 19:35 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
> +}
The beta article for creating a policy had 4 examples of different policies that could be created.  I plan to bring those over as the features light up in v1.0, but since the policy data structure is different, I'd like to work on the examples in a separate PR to this one, OK?

2022-03-30 16:43 UTC, opbld33 commented
Docs Build status updates of commit _[54bf383](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54bf383037ed52f0ca3f81fd8692045765e5b44e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-03-30 17:06 UTC, opbld34 commented
Docs Build status updates of commit _[db84aa5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db84aa514ddff7f496b258f896099df86987976c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-03-31 15:32 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageassignmentpolicy.md
> +|catalog|[accessPackageCatalog](../resources/accesspackagecatalog.md)|Catalog of access package containing this policy. Read-only.|
Hmm - I have to deep dive into the EM APIs to understand these better.

2022-03-31 18:21 UTC, FaithOmbongi approved these changes
Hi @markwahl-msft, thank you for addressing the review feedback. Just one more for the changelog. I've added suggestions for entries for the new objects that you've added. Approved with suggestions.

2022-03-31 18:21 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +          "Description": "Added the **assignmentPolicies** relationship to [accessPackage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackage?view=graph-rest-1.0) resource.",
Changelog generation bug
```suggestion
          "Description": "Added the **assignmentPolicies** relationship to the [accessPackage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackage?view=graph-rest-1.0) resource.",
```

2022-03-31 18:21 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +          "Description": "Added the **assignmentPolicy** relationship to [accessPackageAssignment](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignment?view=graph-rest-1.0) re
```suggestion
          "Description": "Added the **assignmentPolicy** relationship to the [accessPackageAssignment](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignment?view=graph-rest-1.0) resource.",
```

2022-03-31 18:21 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +          "Description": "Added the **assignmentPolicies** relationship to [entitlementManagement](https://docs.microsoft.com/en-us/graph/api/resources/entitlementManagement?view=graph-rest-1.0) reso
```suggestion
          "Description": "Added the **assignmentPolicies** relationship to the [entitlementManagement](https://docs.microsoft.com/en-us/graph/api/resources/entitlementManagement?view=graph-rest-1.0) resource.",
```

2022-03-31 18:21 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +        }
I see you're missing a few entries for the added resources and the new enums.
```suggestion
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Enum type",
          "ChangedApiName": "accessReviewExpirationBehavior",
          "ChangeType": "Addition",
          "Description": "Added the **accessReviewExpirationBehavior** enumeration type.",
          "Target": "accessReviewExpirationBehavior"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Enum type",
          "ChangedApiName": "allowedTargetScope",
          "ChangeType": "Addition",
          "Description": "Added the **allowedTargetScope** enumeration type.",
          "Target": "allowedTargetScope"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Resource",
          "ChangedApiName": "accessPackageApprovalStage",
          "ChangeType": "Addition",
          "Description": "Added the [accessPackageApprovalStage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageApprovalStage?view=graph-rest-1.0) resource type.",
          "Target": "accessPackageApprovalStage"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Resource",
          "ChangedApiName": "accessPackageAssignmentApprovalSettings",
          "ChangeType": "Addition",
          "Description": "Added the [accessPackageAssignmentApprovalSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignmentApprovalSettings?view=graph-rest-1.0) resource type.",
          "Target": "accessPackageAssignmentApprovalSettings"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Resource",
          "ChangedApiName": "accessPackageAssignmentRequestorSettings",
          "ChangeType": "Addition",
          "Description": "Added the [accessPackageAssignmentRequestorSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignmentRequestorSettings?view=graph-rest-1.0) resource type.",
          "Target": "accessPackageAssignmentRequestorSettings"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Resource",
          "ChangedApiName": "accessPackageAssignmentReviewSettings",
          "ChangeType": "Addition",
          "Description": "Added the [accessPackageAssignmentReviewSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignmentReviewSettings?view=graph-rest-1.0) resource type.",
          "Target": "accessPackageAssignmentReviewSettings"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Resource",
          "ChangedApiName": "targetApplicationOwners",
          "ChangeType": "Addition",
          "Description": "Added the [targetApplicationOwners](https://docs.microsoft.com/en-us/graph/api/resources/targetApplicationOwners?view=graph-rest-1.0) resource type.",
          "Target": "targetApplicationOwners"
        },
        {
          "Id": "f0b1d404-83b8-4796-ac5f-748597e9df5e",
          "ApiChange": "Resource",
          "ChangedApiName": "targetManager",
          "ChangeType": "Addition",
          "Description": "Added the [targetManager](https://docs.microsoft.com/en-us/graph/api/resources/targetManager?view=graph-rest-1.0) resource type.",
          "Target": "targetManager"
        },
```

2022-03-31 18:58 UTC, opbld31 commented
Docs Build status updates of commit _[1b04be3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b04be35e72a4fd3e1bc2877f32e825e95415f6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-03-31 19:00 UTC, opbld31 commented
Docs Build status updates of commit _[a9a49e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9a49e833b9bddeed97c918503bf80deaec936e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-04-01 03:21 UTC, opbld33 commented
Docs Build status updates of commit _[b0dcf34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0dcf34ade2f85666a07397386be18bb81ae4782)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageapprovalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageapprovalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageapprovalstage?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentapprovalsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestorsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentreviewsettings?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subjectset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/subjectset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subjectset?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetapplicationowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetapplicationowners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetapplicationowners?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/targetmanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-b/api-reference/v1.0/resources/targetmanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/targetmanager?view=graph-rest-1.0&branch=pr-en-us-15098) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/micro [...]

2022-04-01 03:23 UTC, merged