second draft commit to ebasseri fork
microsoftgraph/microsoft-graph-docs pull request #15101
Opened 2021-12-01 20:26 UTC by ebasseri

2021-12-01 20:28 UTC, opbld34 commented
Docs Build status updates of commit _[f5cc59a](https://github.com/ebasseri/microsoft-graph-docs/commits/f5cc59a32d9370daffcfa61417f1ee8fa991705b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-bee5f600)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-bee5f600)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-bee5f600)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-bee5f600)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-bee5f600"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-bee5f600"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 47, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/riskyserviceprincipalhistoryitem.md'.`````
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="dded2166454c2d90f035d9e327b8a868-bee5f600"></a>
### [api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list.md'.`````
 - **Line 25, Column 63**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/riskyserviceprincipalhistoryitem.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-bee5f600"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md)
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/serviceprincipalriskdetection-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112012026261266-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T20%3A28%3A03Z&sr=b&sp=r&sig=G7kPT%2BTiWoNGL9toAkNFFsiFfuM8OCk6fOj5VNgT1H8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes [...]

2021-12-03 13:28 UTC, FaithOmbongi requested changes
Thank you @ebasseri for working on this PR. Great work for a first major docs add!

Most inline comments are minor fixes. The major gaps:

- Add the 2 new enum members to the [riskDetail enumtype](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta#riskdetail-values) declaration & a new member to the [activityType](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta#activitytype-values) enum type declaration.
    - Note that in the Changelog, these are entered in a different changelog file because they target the Reporting workload changelog, not the Identity Protection workload changelog.

- Note: all inline enum members should be listed in the order of their integer weight.
- Add the two new relationships to the identityProtectionRoot resource.
- Add 2 missing resources: riskyServicePrincipalHistoryItem (entity type and it's methods, one of which is List history) and the riskServicePrincipalActivity complex type.
- I see you've introduced new permissions. Please remember to document them in the [permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#identity-risk-permissions).
- Note that riskyserviceprincipal-list-history.md is a method that should be listed in the riskyServicePrincipalHistoryItem resource type Methods table.
- Don't forget to add the TOC
- Don't forget to add the changelog

Another note: I've recommended changes to some descriptions to use the term "service principal" over "workload identities" because of consistency, align with the resource names, & that service principals is a more familiar term for Microsoft Graph customers.

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/resources/serviceprincipalriskdetection.md
> +|tokenIssuerType|tokenIssuerType|Indicates the type of token issuer for the detected sign-in risk. The possible values are: `AzureAD`, `UnknownFutureValue`, `AzureADBackupAuth`. Note that you must us
For inline enums declarations e.g. for riskDetail: 

- Members should be listed in the order of their Integer weight. 
- All members must be listed, for example, riskEventType below doesn't list all member values.

```suggestion
|activityDateTime|DateTimeOffset|Date and time when the risky activity occurred. The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`|
|additionalInfo|String|Additional information associated with the risk detection in JSON format.|
|appId|String|The unique identifier for the associated application.|
|correlationId|String|Correlation ID of the sign-in activity associated with the risk detection. This property is `null` if the risk detection is not associated with a sign-in activity.|
|detectedDateTime|DateTimeOffset|Date and time when the risk was detected. The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`.|
|detectionTimingType|riskDetectionTimingType|Timing of the detected risk , whether real-time or offline). The possible values are: `notDefined`, `realtime`, `nearRealtime`, `offline`, `unknownFutureValue`.|
|id|String|Unique identifier of the risk detection. Inherited from [entity](../resources/entity.md).|
|ipAddress|String|Provides the IP address of the client from where the risk occurred.|
|keyIds|String collection|The unique identifier (GUID) for the key credential associated with the risk detection.|
|lastUpdatedDateTime|DateTimeOffset|Date and time when the risk detection was last updated.|
|location|[signInLocation](../resources/signinlocation.md)|Location of the sign-in.|
|requestId|String|Request identifier of the sign-in activity associated with the risk detection. This property is `null` if the risk detection is not associated with a sign-in activity.|
|riskDetail|riskDetail|Details of the detected risk. <br>**Note:** Details for this property are only available for Azure AD Premium P2 customers. P1 customers will be returned `hidden`. The possible values are: `none`, `adminConfirmedSigninSafe`, `aiConfirmedSigninSafe`, `adminConfirmedSigninCompromised`, `hidden`, `unknownFutureValue`, `adminConfirmedServicePrincipalCompromised`, `adminDismissedAllRiskForServicePrincipal`. Note that you must use the `Prefer: include - unknown -enum-members` request header to get the following value(s) in this [evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations): `adminConfirmedServicePrincipalCompromised` , `adminDismissedAllRiskForServicePrincipal`.|
|riskEventType|String|The type of risk event detected. The possible values are: `investigationsThreatIntelligence`, `suspiciousSignIns`,`leakedCredentials`, and `unknownFutureValue`.|
|riskLevel|riskLevel|Level of the detected risk. <br>**Note:** Details for this property are only available for Azure AD Premium P2 customers. P1 customers will be returned `hidden`. The possible values are: `low`, `medium`, `high`, `hidden`, `none`, `unknownFutureValue`.|
|riskState|riskState|The state of a detected risky service principal or sign-in activity. The possible values are: `none`, `confirmedSafe`, `remediated`, `dismissed`, `atRisk`, `confirmedCompromised`, `unknownFutureValue`.|
|servicePrincipalDisplayName|String|	The display name for the service principal.|
|servicePrincipalId|String|The unique identifier for the service principal.|
|source|String|Source of the risk detection. For example, `identityProtection`.|
|tokenIssuerType|tokenIssuerType|Indicates the type of token issuer for the detected sign-in risk. The possible values are: `AzureAD`, `ADFederationServices`, `UnknownFutureValue`, `AzureADBackupAuth`. Note that you must use the `Prefer: include - unknown -enum-members` request header to get the following value(s) in this [evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations): `AzureADBackupAuth`.|
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/resources/serviceprincipalriskdetection.md
> +riskyServicePrincipals (ADD LINK HERE).
I don't see any relationships declared in the CSDL.
```suggestion
None.
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +description: "Get the servicePrincipalRiskDetection resources from the servicePrincipalRiskDetections navigation property."
```suggestion
description: "Retrieve the properties of a collection of servicePrincipalRiskDetection objects."
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +Retrieve the properties of a collection of servicePrincipalRiskDetection objects.
```suggestion
Retrieve the properties of a collection of [servicePrincipalRiskDetection](../resources/serviceprincipalriskdetection.md) objects.
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +This method supports `$filter` and `$select` to customize the query response. See the example later in this topic.
```suggestion
This method supports the `$filter` and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +    "additionalInfo": "[{\"Key\":\"alertUrl\",\"Value\":null}]"
GLOBAL: I don't think null values are supposed to be returned in quotes. Kindly confirm and resolve in this and other examples in this PR.

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +
Same comment about quoting null values.

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +    "requestId": "null",
Same comment about quoting null values.

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +Read the properties and relationships of one or more [servicePrincipalRiskDetection](../resources/serviceprincipalriskdetection.md) objects.
Get on a single object.
```suggestion
Read the properties and relationships of a [servicePrincipalRiskDetection](../resources/serviceprincipalriskdetection.md) object.
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +GET /identityProtection/servicePrincipalRiskDetections/{servicePrincipalRiskDetectionId}
/identityProtection/servicePrincipalRiskDetections is the syntax for the LIST operation (aleardy documented in identityprotectionroot-list-serviceprincipalriskdetections.md).
```suggestion
GET /identityProtection/servicePrincipalRiskDetections/{servicePrincipalRiskDetectionId}
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +    "requestId": "null",
Same comment about quoting `null`.

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +>**Note:** The response should include a single object.
Restoring the boilerplate text
```suggestion
>**Note:** The response object shown here might be shortened for readability.
```

2021-12-03 13:28 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +### Example 1: Get all risk detections
Same comment as in the HTTP request. "Get all risk detections" is covered in the LIST operation doc. Kindly remove this example. In this doc, what's currently Example 2 is the correct syntax.

2021-12-03 13:56 UTC, FaithOmbongi requested changes
Additional comments to help resolve some validation errors

2021-12-03 13:56 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md
> +
Add the missing closing backticks. To help resolve one of the validation errors (GitHub doesn't allow me to add only backticks so won't be visible in this suggestion)
```suggestion

```


```

2021-12-03 13:56 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-list-history.md
> +}
Added missing closing backticks. To help resolve one of the validation errors (GitHub doesn't allow me to add only backticks so won't be visible in this suggestion)
```suggestion
}
```

```

2021-12-21 19:14 UTC, opbld33 commented
Docs Build status updates of commit _[f8cd81e](https://github.com/ebasseri/microsoft-graph-docs/commits/f8cd81ea211f12dc40d371336a8bccb54f1fed3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-652a128f)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-652a128f)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-652a128f)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-652a128f)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-652a128f)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-652a128f"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-652a128f"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="dded2166454c2d90f035d9e327b8a868-652a128f"></a>
### [api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list.md'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-652a128f"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-652a128f"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md)
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/serviceprincipalriskdetection-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112211912106442-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T19%3A14%3A02Z&sr=b&sp=r&sig=XgqrO72CFbdxF1sljGqxqThYEkF0STwMcH95ofiM9Mk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to [...]

2021-12-21 19:35 UTC, opbld34 commented
Docs Build status updates of commit _[298fc76](https://github.com/ebasseri/microsoft-graph-docs/commits/298fc76bbc28c2c017c8696b1b4e835261dc8bdd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-2d13b914)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-2d13b914)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-2d13b914)
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-4bc8d4c4db887bb90e97d1794c545321-2d13b914)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-2d13b914)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-2d13b914)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-2d13b914"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-2d13b914"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="dded2166454c2d90f035d9e327b8a868-2d13b914"></a>
### [api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list.md'.`````

<a id="4bc8d4c4db887bb90e97d1794c545321-2d13b914"></a>
### [api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-2d13b914"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-2d13b914"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/b [...]

2021-12-21 21:18 UTC, opbld33 commented
Docs Build status updates of commit _[38665c9](https://github.com/ebasseri/microsoft-graph-docs/commits/38665c93a94e75ecc99851f272a5f21aed76a741)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-f0888777)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-f0888777)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-f0888777)
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-4bc8d4c4db887bb90e97d1794c545321-f0888777)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-f0888777)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-f0888777)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-f0888777"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-f0888777"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="dded2166454c2d90f035d9e327b8a868-f0888777"></a>
### [api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list.md'.`````

<a id="4bc8d4c4db887bb90e97d1794c545321-f0888777"></a>
### [api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-f0888777"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-f0888777"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/b [...]

2021-12-21 21:20 UTC, opbld31 commented
Docs Build status updates of commit _[9f3f457](https://github.com/ebasseri/microsoft-graph-docs/commits/9f3f457628baea8ed31859567c8e71a2a6139834)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-5ac292b7)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-5ac292b7)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-5ac292b7)
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-4bc8d4c4db887bb90e97d1794c545321-5ac292b7)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-5ac292b7)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-5ac292b7)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-5ac292b7"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-5ac292b7"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="dded2166454c2d90f035d9e327b8a868-5ac292b7"></a>
### [api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list.md'.`````

<a id="4bc8d4c4db887bb90e97d1794c545321-5ac292b7"></a>
### [api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-5ac292b7"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-5ac292b7"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/b [...]

2021-12-21 21:22 UTC, opbld32 commented
Docs Build status updates of commit _[a4deb0c](https://github.com/ebasseri/microsoft-graph-docs/commits/a4deb0c31f87b783ee3ba3b79f5c6ff8f21c3bb8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-596412de)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-596412de)
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-4bc8d4c4db887bb90e97d1794c545321-596412de)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-596412de)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-596412de)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-596412de"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-596412de"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="4bc8d4c4db887bb90e97d1794c545321-596412de"></a>
### [api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-596412de"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-596412de"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md)
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/serviceprincipalriskdetection-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112212119393345-1 [...]

2022-01-06 17:21 UTC, opbld30 commented
Docs Build status updates of commit _[0cbdca5](https://github.com/ebasseri/microsoft-graph-docs/commits/0cbdca554c7a4fc2bc7f2e7d9a9cd65dea48940f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-901da05f)

<a id="901da05f"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061720112998-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T17%3A21%3A49Z&sr=b&sp=r&sig=L4ja04c3GJEZTxUhCpDBtUecnynnOHyjhZNf6RDLnnI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 17:29 UTC, opbld31 commented
Docs Build status updates of commit _[4e38ed8](https://github.com/ebasseri/microsoft-graph-docs/commits/4e38ed8c6596121d0121ac8ad1cb2930bc8f7434)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-d56df157)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-d56df157)
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-4bc8d4c4db887bb90e97d1794c545321-d56df157)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-d56df157)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-d56df157)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-d56df157"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-d56df157"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="4bc8d4c4db887bb90e97d1794c545321-d56df157"></a>
### [api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-d56df157"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-d56df157"></a>
### [api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md)
 - **Line 27, Column 2**: **[Warning: file-not-found - [See d [...]

2022-01-06 17:43 UTC, opbld30 commented
Docs Build status updates of commit _[f72745f](https://github.com/ebasseri/microsoft-graph-docs/commits/f72745ffd8078bc219a0ba463d96a76a56829a00)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-702044f9)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-702044f9)
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-4bc8d4c4db887bb90e97d1794c545321-702044f9)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-702044f9)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-702044f9)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="947d8642473ba32273c0a1cc56197e16-702044f9"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-702044f9"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="4bc8d4c4db887bb90e97d1794c545321-702044f9"></a>
### [api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-702044f9"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

<a id="61b5e9f830d86ff06efea1db5bab6259-702044f9"></a>
### [api-reference/beta/resources/serviceprincipalr [...]

2022-01-07 23:07 UTC, opbld33 commented
Docs Build status updates of commit _[61377c0](https://github.com/ebasseri/microsoft-graph-docs/commits/61377c07770385476f243126adb9b36236bfa27f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-0c3c5a8d)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-0c3c5a8d)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="a52075278831cedb9dbb9a05745c5d34-0c3c5a8d"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-0c3c5a8d"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201072304546320-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T23%3A07%3A01Z&sr=b&sp=r&sig=TrYjxq03yRlwxrzjCofxuUtFqHXM%2BXor1lpiCqNNoRA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the  [...]

2022-01-10 17:34 UTC, opbld30 commented
Docs Build status updates of commit _[ec4833a](https://github.com/ebasseri/microsoft-graph-docs/commits/ec4833a93a3e0d9ec9806303a2ec2ac8b5557054)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-92bc2ee8)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-92bc2ee8)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="a52075278831cedb9dbb9a05745c5d34-92bc2ee8"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-92bc2ee8"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101732206260-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T17%3A34%3A28Z&sr=b&sp=r&sig=OU4%2Fm5RsMjwMhFdRP5lWOvPfZ9mz%2BYh3eh122SXicmM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in t [...]

2022-01-10 17:55 UTC, opbld31 commented
Docs Build status updates of commit _[f2c9acf](https://github.com/ebasseri/microsoft-graph-docs/commits/f2c9acf527967c6269d5b6782e1fc51a30fb3010)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-d2f85706)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-d2f85706)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="a52075278831cedb9dbb9a05745c5d34-d2f85706"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-d2f85706"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101753435888-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T17%3A55%3A54Z&sr=b&sp=r&sig=efVTK03AQWfSZ1%2BshOYDfsR8N3dAzdxHjIIt%2B1htHCE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in t [...]

2022-01-10 18:07 UTC, opbld34 commented
Docs Build status updates of commit _[29ba94f](https://github.com/ebasseri/microsoft-graph-docs/commits/29ba94f2a6754f894a18d897a829e5c134b7255d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-323a5d02)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-323a5d02)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="a52075278831cedb9dbb9a05745c5d34-323a5d02"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-323a5d02"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101805360605-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T18%3A07%3A49Z&sr=b&sp=r&sig=YGOLWv%2FVbuV8pe0AXJ0U7ig%2Bs4VBqkncsfwSK11MaGk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in t [...]

2022-01-10 18:25 UTC, opbld31 commented
Docs Build status updates of commit _[e803318](https://github.com/ebasseri/microsoft-graph-docs/commits/e8033189eda8adb9af9e7bfa0649fadce97a3eed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-9323c7bf)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-9323c7bf)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="a52075278831cedb9dbb9a05745c5d34-9323c7bf"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-9323c7bf"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101823100720-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T18%3A25%3A10Z&sr=b&sp=r&sig=GD%2B57RYHFCQslfsaNV70Isbi3xrvEwXKOL09aMZu1iw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the [...]

2022-01-10 18:27 UTC, opbld33 commented
Docs Build status updates of commit _[e803318](https://github.com/ebasseri/microsoft-graph-docs/commits/e8033189eda8adb9af9e7bfa0649fadce97a3eed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-169fe19a)
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-169fe19a)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="a52075278831cedb9dbb9a05745c5d34-169fe19a"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-169fe19a"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101823207048-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T18%3A27%3A15Z&sr=b&sp=r&sig=%2FwYUAE4PkC0HHkQTREceSAYOGYFg45vRCDrsap9uS%2F0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in t [...]

2022-01-10 18:29 UTC, opbld30 commented
Docs Build status updates of commit _[6faedbb](https://github.com/ebasseri/microsoft-graph-docs/commits/6faedbb4760db7d62c9ae309162c18cff56df844)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-9282b1a5)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-9282b1a5"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101826517756-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T18%3A29%3A16Z&sr=b&sp=r&sig=XLCtg9qL9H0%2BMOAcdvXjcBH6TGH4eiu0hhMAmxHhjSg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 00:59 UTC, opbld34 commented
Docs Build status updates of commit _[2eee5e3](https://github.com/ebasseri/microsoft-graph-docs/commits/2eee5e32b955a00fa3c09d5d2c964ea105357589)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110057122403-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T00%3A59%3A12Z&sr=b&sp=r&sig=8PQoXcKzifZ9%2BH39cfKQOn0BRDhvD3LyYO5uJl4Iy68%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 16:39 UTC, FaithOmbongi requested changes
Hi Etan,

Some feedback in this second review. Most of these are bumping up review comments from the initial review - it seems GitHub's collapse review comments feature was making them "invinsible".
1. In Enums.md, add the 2 new enum members (`adminConfirmedServicePrincipalCompromised`, `adminDismissedAllRiskForServicePrincipal`) to the [riskDetail enumtype](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta#riskdetail-values) declaration & a `servicePrincipal` member to the [activityType](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta#activitytype-values) enum type declaration. You made the changes here, please copy them over. Please copy over these changes from this PR you raised: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15300#pullrequestreview-837109178
2. Add the two new relationships to the identityProtectionRoot resource. Please copy the changes (and feedback) you made here https://github.com/microsoftgraph/microsoft-graph-docs/pull/15317#pullrequestreview-838092135
3. Question about riskyServicePrincipalActivity complex type. Is this type named riskServicePrincipalActivity or risk**y**ServicePrincipalActivity? The schema says riskServicePrincipalActivity, unless this is a typo.
4. You've introduced 4 new permissions. Please copy the changes through this PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/15318#pullrequestreview-838099143 into the [permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#identity-risk-permissions) doc in this PR.
5. For example responses, please confirm that these are the exact responses returned by testing using Graph Explorer. This is because I see some different odata.type values and this will break the code snippets generator, preventing code snippets from being correctly autogenerated for your examples.
6. Add the TOC
7. Add the other items in the changelog. For the methods, instead of adding separate changelist objects for each method, expand the description of the parent resource to say "and  related methods". Example of a rendered entry in the [changelog](https://developer.microsoft.com/en-us/graph/changelog/?search=and%20related%20methods#b3431682-f63b-46c0-9317-deb79df71eedv1.0)

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/resources/riskyserviceprincipal.md
> +|servicePrincipalType|String|Identifies whether the service principal represents an application, a managed identity, or a legacy application. This is set by Azure AD internally. Inherits from [servic
@ebasseri, bumping this change suggestion

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/resources/riskyserviceprincipal.md
> +None.
@ebasseri, bumping this change suggestion

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/resources/riskyserviceprincipalhistoryitem.md
> +| activity       | [riskyServicePrincipalHistoryItem](riskyserviceprincipalactivity.md)| The activity related to service principal risk level change. |
Is the complex type riskServicePrincipalActivity or risk**y**ServicePrincipalActivity? The schema says riskServicePrincipalActivity - unless this is a typo in the schema?
```suggestion
| servicePrincipalId         | String  | The identifier of the service principal. |
| initiatedBy    | String    | The identifier of the actor that does the operation. |
| activity       | [riskServicePrincipalActivity](riskyserviceprincipalactivity.md)| The activity related to the service principal risk. | 
```

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/resources/riskyserviceprincipalactivity.md
> +| detail     | riskDetail  | The possible values are `none`, `adminConfirmedSigninSafe`, `aiConfirmedSigninSafe`, `adminConfirmedSigninCompromised`, `hidden`, `unknownFutureValue`, `adminConfirmedSer
Same comment as before - the enum members should be listed in the order of the int value + please list all members.
riskEventType also seems to list fewer supported values than are expected. or is this property different across APIs?
```suggestion
|riskEventType|String|The type of risk event detected. The possible values are `investigationsThreatIntelligence`, `suspiciousSignIns`,`leakedCredentials`, and `unknownFutureValue`.|
| detail     | riskDetail  | The possible values are `none`, `adminConfirmedSigninSafe`, `aiConfirmedSigninSafe`, `adminConfirmedSigninCompromised`, `hidden`, `unknownFutureValue`, `adminConfirmedServicePrincipalCompromised`, ### `adminDismissedAllRiskForServicePrincipal`.
```

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md
> +Retrieve the properties and relationships of a collection of **riskyServicePrincipal** objects.
@ebasseri, bumping this change suggestion

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md
> +|Application|IdentityRiskyServicePrincipal.Read.All, IdentityRiskyServicePrincipal.ReadWrite.All|
@ebasseri, bumping this change suggestion. Copy over the changes from the PR you raised https://github.com/microsoftgraph/microsoft-graph-docs/pull/15318#pullrequestreview-838099143

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md
> +This method supports `$filter` to customize the query response. See the example later in this topic.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +description: "Get the servicePrincipalRiskDetection resources from the servicePrincipalRiskDetections navigation property."
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +Retrieve the properties of a collection of servicePrincipalRiskDetection objects.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +This method supports `$filter` and `$select` to customize the query response. See the example later in this topic.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +    "additionalInfo": "[{\"Key\":\"alertUrl\",\"Value\":null}]"
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
> +    "requestId": "null",
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md
> +description: "Confirm one or more riskyServicePrincipal object as compromised."
@ebasseri, bumping this change suggestion because this PI supports adding a collection of IDs.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md
> +Confirm one or more [riskyServicePrincipal](../resources/riskyserviceprincipal.md) objects as compromised. This action sets the targeted account's risk level to high.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md
> +In the request body, specify the servicePrincipalIds to confirm as compromised.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-dismiss.md
> +description: "Dismiss the risk of one or more riskyServicePrincipal object."
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-dismiss.md
> +Dismiss the risk of one or more [riskyServicePrincipal](../resources/riskyserviceprincipal.md) objects. This action sets the targeted account's risk level to none. The maximum count of accounts to di
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-dismiss.md
> +In the request body, specify the servicePrincipalIds to dismiss.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-get.md
> +Here is an example of the request.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-get.md
> +The following example shows how to use `$filter` to get the collection of riskyServicePrincipal whose aggregate risk level is High.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-get.md
> +GET https://graph.microsoft.com/beta/identityProtection/riskyServicePrincipals$filter=riskLevel eq microsoft.graph.riskLevel'high'
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-list-history.md
> +description: "Get the riskyServicePrincipalHistoryItem resources from the history navigation property."
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/riskyserviceprincipal-list-history.md
> +Get the risk history of a [riskyServicePrincipal](../resources/riskyServicePrincipal.md) resource.
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +### Example 1: Get all risk detections
@ebasseri, bumping this change suggestion.

2022-01-12 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalriskdetection-get.md
> +    "requestId": "null",
@ebasseri, bumping this change suggestion.

2022-01-13 16:08 UTC, opbld32 commented
Docs Build status updates of commit _[5d7e29c](https://github.com/ebasseri/microsoft-graph-docs/commits/5d7e29c761604d839f6eb51a59a95965d88ea867)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131606243772-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A08%3A29Z&sr=b&sp=r&sig=ZY%2Bi5SdrDuGv4es68eAO9s44xZMGHOcncezZQxnckpQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:13 UTC, opbld34 commented
Docs Build status updates of commit _[c355607](https://github.com/ebasseri/microsoft-graph-docs/commits/c355607faf256942ade57c321b61ffcb556c7bf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131608373250-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A13%3A52Z&sr=b&sp=r&sig=mfUrePVXjY3SSnblB65o22Hpc9IQJO1xgiDkNALmiOk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:16 UTC, opbld31 commented
Docs Build status updates of commit _[7faf3aa](https://github.com/ebasseri/microsoft-graph-docs/commits/7faf3aa2361960f7d17b81fae088e88c35ee697d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131614202591-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A16%3A17Z&sr=b&sp=r&sig=HIiGUMg9pOpXNj%2FrYJQw%2FAGhXOWGTmhW78KFeRCm5ps%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:18 UTC, opbld30 commented
Docs Build status updates of commit _[8dfe6be](https://github.com/ebasseri/microsoft-graph-docs/commits/8dfe6be373c73c0e0723b3a88c0fe2ebf1a9f288)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131615212859-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A18%3A24Z&sr=b&sp=r&sig=YiVVUeJ7tMr0I99CbuG4II0m%2FBuyRN5O56g3sh57pAc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:20 UTC, opbld30 commented
Docs Build status updates of commit _[e794613](https://github.com/ebasseri/microsoft-graph-docs/commits/e794613933c84efa317a7ba84f61cfbf42128777)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131616359490-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A20%3A28Z&sr=b&sp=r&sig=Rihkt0oIMMyc6UAMxEUJQcrXVIJjA0uARVNDiF40P6U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:24 UTC, opbld34 commented
Docs Build status updates of commit _[819af2c](https://github.com/ebasseri/microsoft-graph-docs/commits/819af2c6b117003de94c0a447edbfee433f63d91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131621573288-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A24%3A34Z&sr=b&sp=r&sig=ySetKSjvLypsk8uw27C%2FF9ahu4JwfSDirOgcQ967WbI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:26 UTC, opbld30 commented
Docs Build status updates of commit _[4e99477](https://github.com/ebasseri/microsoft-graph-docs/commits/4e99477a92553fed484ba2fc997ce52bc2d59008)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131622257469-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A26%3A32Z&sr=b&sp=r&sig=TyQGUwIQ815%2BvbajYpX5j24g0rfk9XwAsPxgXYmFkJQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:28 UTC, opbld30 commented
Docs Build status updates of commit _[c27cafa](https://github.com/ebasseri/microsoft-graph-docs/commits/c27cafa04992fb0c769e4c2ab72dd7fa4213ed3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131625458808-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A28%3A42Z&sr=b&sp=r&sig=c8882hNLvAwLdxMDMV26tFBYsXKBCJ%2B7as0oTxH46Bo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:30 UTC, opbld33 commented
Docs Build status updates of commit _[0042d2b](https://github.com/ebasseri/microsoft-graph-docs/commits/0042d2b59c2e941c168cb6ef23f86235deff49ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131627260188-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A30%3A38Z&sr=b&sp=r&sig=eyokcGmcmaEER%2Bba3Gyd2Qv9FwLH4G8lTFfzvE7sDeE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:38 UTC, opbld30 commented
Docs Build status updates of commit _[ec21e9e](https://github.com/ebasseri/microsoft-graph-docs/commits/ec21e9e56c549f211a92e328e4cd4aada9c5b02d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131634083523-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A38%3A31Z&sr=b&sp=r&sig=BECiNYecDc5%2FuuJtkOjvYRmYQF7%2FA4n%2Bodh8CgBOZUw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:40 UTC, opbld33 commented
Docs Build status updates of commit _[1d82232](https://github.com/ebasseri/microsoft-graph-docs/commits/1d822322d3d8349120dbdf73840c1ae6e2843f3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131636191406-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T16%3A40%3A36Z&sr=b&sp=r&sig=Ikn7M7wkBRSzg6d7xE6QWVHU7LWWF25NCWxhvZTI1H0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 02:59 UTC, opbld31 commented
Docs Build status updates of commit _[6c1fd38](https://github.com/ebasseri/microsoft-graph-docs/commits/6c1fd387ec686804e97899cbabd2b1397bfe6ccb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200256537975-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T02%3A59%3A02Z&sr=b&sp=r&sig=aE0rqHJ5kOLaVbnXX8Bolm4yd1n6WctLgv7rFVdYol0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 03:37 UTC, opbld30 commented
Docs Build status updates of commit _[66cdf41](https://github.com/ebasseri/microsoft-graph-docs/commits/66cdf415dbdf06e851febdfeb875073a7d9a33fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200334485176-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T03%3A37%3A02Z&sr=b&sp=r&sig=efchCu3bcTIqwxXJDMIqmt4vvOXeHukb2Lu5ehL%2BksY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 05:12 UTC, opbld32 commented
Docs Build status updates of commit _[4809fa0](https://github.com/ebasseri/microsoft-graph-docs/commits/4809fa05a7943500ad154385547e900e794b86ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200510059547-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T05%3A12%3A21Z&sr=b&sp=r&sig=F%2F%2BBNWvYokfjg2o7EUgaBNnJppDE2DpfPNV4tq4MSf8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 10:43 UTC, opbld32 commented
Docs Build status updates of commit _[b3dc331](https://github.com/ebasseri/microsoft-graph-docs/commits/b3dc331e29155a7f8a53783b3aba6c0fac18e779)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201211040453384-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T10%3A43%3A15Z&sr=b&sp=r&sig=zVDkEEzkYtpwer5xROmFVKJG6%2BtOYTb%2BBgYMWSJBsCA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 10:49 UTC, FaithOmbongi requested changes
Hi @ebasseri, I've pushed a few commits to resolve some pending review comments. Two things to note:

+ I've updated the identity protection overview article and grouped the APIs into user risks (the existing riskyUser and riskDetections APIs) and service principal risks. Kindly confirm that this is the correct grouping. If this is correct, I also recommend applying the grouping to the TOC for easier navigation.

+ Please ensure that the schema is fixed from riskServicePrincipalActivity to riskyServicePrincipalActivity before the API goes live and the docs are published.

+ The only major pending item is the complete changelog.

2022-01-21 10:53 UTC, FaithOmbongi requested changes
Few items pending for approval. Please see the previous message for feedback.

2022-01-26 23:20 UTC, opbld31 commented
Docs Build status updates of commit _[c0b90e3](https://github.com/ebasseri/microsoft-graph-docs/commits/c0b90e353de2f3f176791c3b079a6b61f976eb2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262318277454-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A20%3A30Z&sr=b&sp=r&sig=d97tLkzOxaeIlNZ3WTuhig8s9n5fJmKGHah%2FnLJ9few%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:28 UTC, opbld33 commented
Docs Build status updates of commit _[c0b90e3](https://github.com/ebasseri/microsoft-graph-docs/commits/c0b90e353de2f3f176791c3b079a6b61f976eb2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262326402837-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A28%3A34Z&sr=b&sp=r&sig=RQR3Urm%2FkMnOO18zzYAPDHJ%2BttBzuehfPPxcZGTMbLs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:48 UTC, opbld34 commented
Docs Build status updates of commit _[4d055e9](https://github.com/ebasseri/microsoft-graph-docs/commits/4d055e9b006267dbecbda6b43c44482069bc6038)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262346416550-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A48%3A48Z&sr=b&sp=r&sig=MDU7HRade3nmWMgFC3GN1g3mhRSu6vFy%2FJVs4D%2BhgZ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 00:14 UTC, ebasseri commented
> Hi @ebasseri, I've pushed a few commits to resolve some pending review comments. Two things to note:
> 
> * I've updated the identity protection overview article and grouped the APIs into user risks (the existing riskyUser and riskDetections APIs) and service principal risks. Kindly confirm that this is the correct grouping. If this is correct, I also recommend applying the grouping to the TOC for easier navigation.
> * Please ensure that the schema is fixed from riskServicePrincipalActivity to riskyServicePrincipalActivity before the API goes live and the docs are published.
> * The only major pending item is the complete changelog.

Thank you @FaithOmbongi this helps. 

1. I made some updates to your updates on the overview article for accuracy. I have grouped things in the TOC already, if it doesn't show correctly we need to address. 
2. I confirmed the correct schema is riskServicePrincipalActivity and have fixed it globally (I think)
3. Changelog is in progress; I pinged my Eng teammates for the content.

2022-02-07 18:14 UTC, opbld31 commented
Docs Build status updates of commit _[36e39ec](https://github.com/ebasseri/microsoft-graph-docs/commits/36e39ec23d14ba2cc39870e1b8b9f49a4bcf8eec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071812043684-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T18%3A14%3A04Z&sr=b&sp=r&sig=OURxqw23JCumlEJhQXfJlLgXZ4NHJLMv5C7puahs%2FIw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 13:01 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  },
Looks like another tooling bug.
```suggestion
			  {
				"Id": "5a2defb1-0d73-4133-867b-e6d90f45701d",
				"ApiChange": "Resource",
				"ChangedApiName": "riskyServicePrincipal",
				"ChangeType": "Addition",
				"Description": "Added the [riskyServicePrincipal](https://docs.microsoft.com/en-us/graph/api/resources/riskyServicePrincipal?view=graph-rest-beta) resource and related methods. Use this API to access all at-risk service principals in your Azure AD tenant.",
				"Target": "riskyServicePrincipal"
			  },
			  {
				"Id": "5a2defb1-0d73-4133-867b-e6d90f45701d",
				"ApiChange": "Resource",
				"ChangedApiName": "servicePrincipalRiskDetection",
				"ChangeType": "Addition",
				"Description": "Added the [servicePrincipalRiskDetection](https://docs.microsoft.com/en-us/graph/api/resources/servicePrincipalRiskDetection?view=graph-rest-beta) resource and related methods. Use this API to access all service principal risk detections in your Azure AD environment.",
				"Target": "servicePrincipalRiskDetection"
			  },
			  {
				"Id": "5a2defb1-0d73-4133-867b-e6d90f45701d",
				"ApiChange": "Relationship",
				"ChangedApiName": "riskyServicePrincipals",
				"ChangeType": "Addition",
				"Description": "Added the **riskyServicePrincipals** navigation property to the [identityProtectionRoot](https://docs.microsoft.com/en-us/graph/api/resources/identityProtectionRoot?view=graph-rest-beta) resource.",
				"Target": "identityProtectionRoot"
			  },
			  {
				"Id": "5a2defb1-0d73-4133-867b-e6d90f45701d",
				"ApiChange": "Relationship",
				"ChangedApiName": "servicePrincipalRiskDetections",
				"ChangeType": "Addition",
				"Description": "Added the **servicePrincipalRiskDetections** navigation property to the [identityProtectionRoot](https://docs.microsoft.com/en-us/graph/api/resources/identityProtectionRoot?view=graph-rest-beta) resource.",
				"Target": "identityProtectionRoot"
			  },
```

2022-02-08 13:05 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +				"Description": "Added the [riskyServicePrincipalHistoryItem](https://docs.microsoft.com/en-us/graph/api/resources/riskyServicePrincipalHistoryItem?view=graph-rest-beta) resource",
```suggestion
				"Description": "Added the [riskyServicePrincipalHistoryItem](https://docs.microsoft.com/en-us/graph/api/resources/riskyServicePrincipalHistoryItem?view=graph-rest-beta) resource and related methods. Use this API to retrieve the risk history of an Azure AD service principal as determined by Azure AD Identity Protection.",
```

2022-02-08 13:19 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  },
Already added higher up
```suggestion
```

2022-02-08 13:30 UTC, FaithOmbongi commented on api-reference/beta/resources/riskyserviceprincipalactivity.md
> +description: author
```suggestion
description: "Represents the risk activity of an Azure AD service principal as determined by Azure AD Identity Protection."
```

2022-02-08 13:49 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            - name: Get risk detection
Your can use only the verb here because only CRUD operations are supported - unlike the next API group in the TOC which also supports actions/functions
```suggestion
            - name: List
              href: api/identityprotectionroot-list-serviceprincipalriskdetections.md
            - name: Get
```

2022-02-09 02:31 UTC, opbld31 commented
Docs Build status updates of commit _[4da6aad](https://github.com/ebasseri/microsoft-graph-docs/commits/4da6aad601fbf28e976683f4d44d6de15bf2fed5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090229127407-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A31%3A13Z&sr=b&sp=r&sig=uzeMYWpHh87kYwSQ%2FQtMJxZ63PBTPOSMLdEWAw41QzI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:33 UTC, opbld34 commented
Docs Build status updates of commit _[e511ca8](https://github.com/ebasseri/microsoft-graph-docs/commits/e511ca81f9e35b7593d0c07e4271fb3d970c9285)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090230455905-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A33%3A25Z&sr=b&sp=r&sig=lJ%2BtZ2KQpepwuv28sO%2FPYw3i7wxlNbczD%2FGPRznhm4M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:35 UTC, opbld31 commented
Docs Build status updates of commit _[e55fb1a](https://github.com/ebasseri/microsoft-graph-docs/commits/e55fb1adb7c6b7fe5f440930c99ffff71c7aadfb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090232568997-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A35%3A45Z&sr=b&sp=r&sig=Nohzw407uAvRYAcl%2Bxys74dSLCxMhuaO5AjVnl1YPLc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:38 UTC, opbld32 commented
Docs Build status updates of commit _[c9f8c69](https://github.com/ebasseri/microsoft-graph-docs/commits/c9f8c69859468522d835da0c08b99a8cd0722e6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) | [Details](#user-content-28b38fb0a6a8641ea07c9edc5749b1d7-82bad832)
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

<a id="28b38fb0a6a8641ea07c9edc5749b1d7-82bad832"></a>
### [api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md)
 - **Line 30, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'riskserviceprincipalactivity.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090233474210-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A38%3A20Z&sr=b&sp=r&sig=FQ3l3lin%2FYzRJom4s7s8yh%2FWeyqrk29APLmwleg6nwU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https [...]

2022-02-09 02:52 UTC, opbld34 commented
Docs Build status updates of commit _[da5af10](https://github.com/ebasseri/microsoft-graph-docs/commits/da5af106067ef345954876544c2cbf06e3b97938)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090249582439-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A52%3A10Z&sr=b&sp=r&sig=F59tkGXO7izLrSM65hrmT0e912c7aE90DllpVCPpkiE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:54 UTC, opbld30 commented
Docs Build status updates of commit _[9359bae](https://github.com/ebasseri/microsoft-graph-docs/commits/9359bae696aa95554b62c1088bdc322cad567ad5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090251500571-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A54%3A28Z&sr=b&sp=r&sig=PtN6YPf313RkXacihrF%2FlXAhUUPt%2FquId0YHB%2BojnYQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:56 UTC, opbld33 commented
Docs Build status updates of commit _[590a248](https://github.com/ebasseri/microsoft-graph-docs/commits/590a248ee9930db2888dabf106ca62b68ce13f3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090253183694-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T02%3A56%3A55Z&sr=b&sp=r&sig=0UFPvND7a8IRFucB6lcwslmcKtIO6MD7Lg5MXedYrIg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 02:59 UTC, ebasseri commented
@FaithOmbongi thanks so much for these edits. 


GLOBAL fix across the PR: You confirmed that the correct resource name is riskServicePrincipalActivity. Please resolve all references to riskyServicePrincipalActivity => riskServicePrincipalActivity in your PR, including the file name and titles.
   _this is fixed_

Changelog fixes. All the issues are because of a bug in the tooling. I'll raise a bug report with the team about these.
   _ok, I incorporated your suggestions. hope we are good to go live now!_

2022-02-09 08:40 UTC, opbld32 commented
Docs Build status updates of commit _[5da4f0b](https://github.com/ebasseri/microsoft-graph-docs/commits/5da4f0b2e4352ee6bce56e949ea8ac1cd447e881)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090837560345-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T08%3A40%3A24Z&sr=b&sp=r&sig=mFMpP3RNdd8qG0pKOlkyPIMDW65ehOPrXIM3pvCUfvA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 09:02 UTC, opbld32 commented
Docs Build status updates of commit _[e86e7e3](https://github.com/ebasseri/microsoft-graph-docs/commits/e86e7e38cd9809c538fece25659d688b1e253b04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotection-overview.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotection-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotection-overview?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/identityprotectionroot.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/identityprotectionroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskserviceprincipalactivity.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskserviceprincipalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskserviceprincipalactivity?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/riskyserviceprincipalhistoryitem.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/riskyserviceprincipalhistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipalhistoryitem?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-15101) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/ebasseri/microsoft-graph-docs/blob/ebasseri-draftdocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090900257762-15101%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T09%3A02%3A37Z&sr=b&sp=r&sig=ljNJxgRfYO%2FRgKG6cJW%2FEtQqoXavB5x7fiZQ2SVkObY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 09:07 UTC, FaithOmbongi approved these changes
Thank you @ebasseri for your work on this PR. I've made a fresh pass and pushed commits for LIST (returns collections) and GET (returns single objects) examples before approval.

2022-02-09 18:20 UTC, ebasseri commented
@FaithOmbongi thank you. I've replaced the labels. Anything else I need to do for these docs to go live?

2022-02-09 19:15 UTC, FaithOmbongi commented
Hi @ebasseri, after replacing the **do not merge** with **ready to merge** label, nothing more is required. The PR is now in Laura's queue, and she'll do a pre-merge pass before merging it. 

**BTW:** I don't see that the API schema has gone live yet—I can't locate the entities in the [public metadata](http://graph.microsoft.com/beta/$metadata). You can restore back the **do not merge** label and only add replace it with the **ready to merge** label when your schema is public.

2022-02-09 20:24 UTC, ebasseri commented
@FaithOmbongi here is the completed PR https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5625317

2022-02-10 04:34 UTC, merged