Updates to authentication and authorization basics article
microsoftgraph/microsoft-graph-docs pull request #15110
Opened 2021-12-02 11:16 UTC by FaithOmbongi

2021-12-02 11:18 UTC, opbld33 commented
Docs Build status updates of commit _[2e71115](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e71115d26694b3243bb5bdd26b9ca7f3fab8200)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) | [Details](#user-content-42fa002b83bd8e2db08601ab170f59af-f02448fc)
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) |

<a id="42fa002b83bd8e2db08601ab170f59af-f02448fc"></a>
### [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md)
 - **Line 20, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../permissions-reference.md'.`````
 - **Line 21, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../permissions-reference.md'.`````
 - **Line 22, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../permissions-reference.md'.`````
 - **Line 23, Column 5**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../permissions-reference.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112021116166064-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T11%3A18%3A00Z&sr=b&sp=r&sig=PRd54JC%2FFFUxij7pw1iwTzgdIp2pd%2BhA9fPyj87%2FnfM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 11:24 UTC, opbld30 commented
Docs Build status updates of commit _[2d4d97d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d4d97d03b2462a6632df648edb150a65e41ab5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112021123082277-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T11%3A24%3A38Z&sr=b&sp=r&sig=cxi0JI91fMGoJS37uEGBNOkQCciiphx3%2BSv3AZn6TZE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 20:18 UTC, opbld33 commented
Docs Build status updates of commit _[727338b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/727338b58c9648650862d4d56e44ac4ec82e441d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-13780fba)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-13780fba"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112022016312456-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T20%3A18%3A05Z&sr=b&sp=r&sig=TTLwiylMVOgI3RBBWQmrP4EIDEFGLxsELRxFmpScBh8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 10:37 UTC, opbld30 commented
Docs Build status updates of commit _[f41c415](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f41c41552a04dee967c52628e2fcf529cfc2026e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-cd9300af)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-cd9300af"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112091031175002-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T10%3A37%3A19Z&sr=b&sp=r&sig=ETUzv6FSEI8ZtA52l5PrUtyJ5Q9mJo%2Fv4ovUpZVMq7I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 12:05 UTC, opbld32 commented
Docs Build status updates of commit _[bf75cf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf75cf15780c27779818140ad8431aafa46128aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-5b729ff8)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-5b729ff8"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112091202465501-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T12%3A05%3A54Z&sr=b&sp=r&sig=kMFSCFWabXMg%2B1i%2Fr54eOcG5wFywnz0siSnGcHD%2FdBw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 17:03 UTC, opbld33 commented
Docs Build status updates of commit _[b1be32c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1be32c0c6a1a5553f59c061da228b4fc2d7986e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-0762e1d1)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-0762e1d1"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112091700383415-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T17%3A03%3A30Z&sr=b&sp=r&sig=qZxJtWmzC%2FPqa%2Bfqqnw3gP27TFAVMwMSefTzEq585iw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 16:49 UTC, opbld33 commented
Docs Build status updates of commit _[5281654](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5281654da0a0232ed393bc53517ada1e3ee36195)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-36ff9c01)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-36ff9c01"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202111646479879-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T16%3A49%3A37Z&sr=b&sp=r&sig=9vF%2BSPQaKr7z991fryBGFLORYXdV4p%2FmpjKo5ET7A6k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 10:25 UTC, opbld32 commented
Docs Build status updates of commit _[0c06515](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c06515935da0f7268470e1bbb4db7c4ce2aa3c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-1fe8cca2)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-1fe8cca2"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141022555186-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T10%3A25%3A10Z&sr=b&sp=r&sig=fSjZ9BlQ2EkBaVtfF6Z9kYu4Ru%2FHUnDNK1QaMvLY4co%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 10:40 UTC, FaithOmbongi commented
Hi @Jackson-Woods, bumping this up in your review queue. Could you review these updates? Thanks.

2022-02-14 10:49 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +| Common names | <li>OAuth2 permissions   <li>Impersonation access permission <li>[oAuth2PermissionGrants](/graph/api/resources/oauth2permissiongrant) | <li> App roles <li>App-only permissions <li> [
@psignoret I would appreciate your input if these common names are appropriate

2022-02-14 18:26 UTC, Jackson-Woods commented on concepts/auth-limit-mailbox-access.md
> +>Administrators can configure [application access policy](#configure-applicationaccesspolicy) to limit app access to _specific_ mailboxes.
Is this a link to itself?

2022-02-14 18:35 UTC, Jackson-Woods commented on concepts/auth-v2-service.md
> +> We recommend that you configure the least privileged set of permissions required by your app. This improves the privilege security of your app. For more information, see [Enhance security with the
Suggest "This improves the security of your app" for second sentence.

2022-02-14 18:45 UTC, Jackson-Woods commented on concepts/auth/auth-concepts.md
> +Access tokens issued by the Microsoft identity platform contain information (claims) that web APIs secured by the Microsoft identity platform, such as Microsoft Graph, use to validate the caller and
1. Access tokens can be decoded - I think they should be "treated as" opaque, but it should not be assumed the caller can't see any of the data the access token contains. 
2. "transport layer security" is the name of the technology, with no hyphen.

2022-02-14 18:55 UTC, Jackson-Woods commented on concepts/auth/auth-concepts.md
> +| Common names | <li>OAuth2 permissions   <li>Impersonation access permission <li>[oAuth2PermissionGrants](/graph/api/resources/oauth2permissiongrant) | <li> App roles <li>App-only permissions <li> [
I would add a fourth row and change as below:

| <!-- No header--> | Delegated permissions | Application permissions |
|--|--|--|
| ... | ... | ... |
| Also called (or, Other names) | <li>scopes <li>oauth2 permissions | <li>App roles <li>App-only permissions <li>Direct access permissions |
| Result of consent | oauth2PermissionsGrants | AppRoleAssignments |

2022-02-15 00:20 UTC, Jackson-Woods commented on concepts/best-practices-concept.md
> +To access the data through Microsoft Graph, your application will need to acquire an OAuth 2.0 access token, and present it to Microsoft Graph in either of the following options:
I'd remove "the" in opening sentence "To access *the* data through Microsoft Graph..."

2022-02-15 00:30 UTC, Jackson-Woods commented on concepts/best-practices-concept.md
> +  - Ensure that you understand the difference between [static and dynamic or incremental consent](/azure/active-directory/develop/v2-permissions-and-consent#consent-types).
Static, dynamic, and incremental are three separate concepts. 
- Static: scopes registered on your app in the portal will all be requested for consent as a group. Updating the list does not automatically prompt for new consent grants.
- Dynamic: any scope or set of scopes can be requested in code during sign in, no need to register the scopes in the portal.
- Incremental consent: it's best practice to ask for scopes incrementally, as new functionality is needed. This might mean that you make a static request on launch for one or more "basic" scopes that will always be needed by your app, then request additional scopes in code using dynamic consent only once the user indicates they need to use a new feature.

2022-02-15 00:31 UTC, Jackson-Woods commented on concepts/permissions-reference.md
I think we can rewrite this to make the relationship more clear - the "privileges" referred to in statement 1 are often defined by Azure AD roles, or roles in other RBAC systems like Exchange RBAC.

2022-02-15 00:34 UTC, Jackson-Woods commented on concepts/best-practices-concept.md
> +
Let's follow up on best way to talk about least privilege. Line 31 to me is a relatively clear statement of least privilege: only ask for what you need. But then we've retitled and added Line 33 which sort of restates the case. I think it would be useful to explain which permission is least privileged (farthest to left in docs, and the one that allows the least access) and to reduce the overall length of the guidance.

2022-02-15 00:34 UTC, Jackson-Woods commented on concepts/best-practices-concept.md
> -    >**Note:** Using application permissions for interactive scenarios can put your application at compliance and security risk. It can inadvertently elevate a user's privileges to access data, circu
Any reason we "demoted" this guidance?

2022-02-15 00:36 UTC, Jackson-Woods requested changes
Thanks for all of this work @FaithOmbongi! I've reviewed the PR and added comments wherever I had a question or thought a change might be needed. We can follow up on a call for the more complex questions, if that would help.

2022-02-21 08:28 UTC, FaithOmbongi commented on concepts/auth-limit-mailbox-access.md
> +>Administrators can configure [application access policy](#configure-applicationaccesspolicy) to limit app access to _specific_ mailboxes.
Yes, it is. It links to the instructions in the next section.

2022-02-21 08:38 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +Access tokens issued by the Microsoft identity platform contain information (claims) that web APIs secured by the Microsoft identity platform, such as Microsoft Graph, use to validate the caller and
Well noted. Updated both sentences.

2022-02-21 08:43 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +  For example, assume your app has been granted the *User.ReadWrite.All* delegated permission and calls the [Update user](/graph/api/user-update) API. This permission nominally grants your app permis
Will come back to this.

2022-02-21 08:53 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +| Common names | <li>OAuth2 permissions   <li>Impersonation access permission <li>[oAuth2PermissionGrants](/graph/api/resources/oauth2permissiongrant) | <li> App roles <li>App-only permissions <li> [
Done.

2022-02-21 09:07 UTC, FaithOmbongi commented on concepts/best-practices-concept.md
> +
Agreed. I've retained the **Use least privilege** paragraph. The term least privilege is more discoverable and better aligned to our Zero Trust guidance. I've also updated the paragraph to address avoiding both unused and reducible permissions.

2022-02-21 09:12 UTC, FaithOmbongi commented on concepts/best-practices-concept.md
> -    >**Note:** Using application permissions for interactive scenarios can put your application at compliance and security risk. It can inadvertently elevate a user's privileges to access data, circu
This type of note format is more likely to be missed. Let me promote the note to use a more visible alert box.

2022-02-21 09:41 UTC, FaithOmbongi commented on concepts/permissions-reference.md
Changes the note a bit. Hope this makes it clearer.

2022-02-21 09:56 UTC, opbld32 commented
Docs Build status updates of commit _[08fb3a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08fb3a5938e7f670fb7479320cec76faab983e23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-af800970)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-af800970"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202210942345175-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T09%3A56%3A15Z&sr=b&sp=r&sig=NRhK0I0fBDyWi0ePdEOSQ55qMEYBftbbOUW0expQdDE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 10:43 UTC, opbld33 commented
Docs Build status updates of commit _[4e6afb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e6afb5ac66b124ebb2b361c861d77c262e975c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-a19ef960)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-a19ef960"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202211040207654-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T10%3A43%3A05Z&sr=b&sp=r&sig=3zjQmqHStxkwA7uLPrGgzo5bhCNXKU6vyHPbtI%2BgEuw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 21:55 UTC, Jackson-Woods commented on concepts/permissions-reference.md
Hmm, this still doesn't make sense to me. Privileges and roles apply to everyone, not just admins. I think it should be something like:

"In delegated scenarios, your app's access is also limited by the privileges of the signed-in user. These privileges are determined by the user's assigned roles and their relationship to the data being accessed." 

Optional third sentence with example: "For example, if the signed-in user does not have appropriate rights to view a particular file, then the client app will not be able to read that file either, even if the File.Read.All permission is granted to the app."

2022-02-22 21:56 UTC, Jackson-Woods commented on concepts/best-practices-concept.md
> -    >**Note:** Using application permissions for interactive scenarios can put your application at compliance and security risk. It can inadvertently elevate a user's privileges to access data, circu
Looks good, thanks!

2022-02-22 22:00 UTC, Jackson-Woods commented on concepts/best-practices-concept.md
> +
Thanks, I think this is a lot more clear!

2022-02-23 07:50 UTC, opbld31 commented
Docs Build status updates of commit _[78cf7a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78cf7a2061e0da9bfd27cb06183d16825a2f9167)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-1d476ee9)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-1d476ee9"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230748323664-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T07%3A50%3A36Z&sr=b&sp=r&sig=w9nkLyueeMvTaeECCFLx%2FWCSUnNhNQm6w%2BCn0jR2Yg8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 19:42 UTC, opbld33 commented
Docs Build status updates of commit _[e1ca5de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1ca5de9bc6f028eb60b487da01a7ca65e0ecca0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-abd8a595)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-abd8a595"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202231940295356-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T19%3A42%3A29Z&sr=b&sp=r&sig=FWWIhFAla9z%2FD92Eoiig%2BoMRxB6SS%2Fdb8SyDZgrWSsE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 19:43 UTC, FaithOmbongi commented on concepts/permissions-reference.md
Resolved.

2022-02-23 19:44 UTC, opbld32 commented
Docs Build status updates of commit _[fc6e012](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc6e01283d193c48d1f569e837039553d47ad4be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-85fa003b)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-85fa003b"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202231942533933-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T19%3A44%3A55Z&sr=b&sp=r&sig=1XuXuG3of%2FT%2FzBBTzvSI4raM%2FQpVMK4mxywS1aC8gMk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 20:00 UTC, Jackson-Woods commented on concepts/permissions-reference.md
LGTM!

2022-02-25 07:16 UTC, Jackson-Woods commented on concepts/auth-v2-service.md
> +With the OAuth 2.0 client credentials grant flow, your app authenticates directly at the Microsoft identity platform `/token` endpoint using the Application ID assigned by Azure AD and the applicatio
Why is Application ID capital but Application Secret is not? 

Also note we call these "Client secrets" in the Azure portal, with a note that says "A secret string that the application uses to prove its identity when requesting a token. Also can be referred to as application password."

2022-02-25 07:17 UTC, Jackson-Woods commented on concepts/auth-v2-service.md
> +> We recommend that you configure the least privileged set of permissions required by your app. This improves the security of your app. For more information, see [Enhance security with the principle
This should be stronger - "Always configure the least privileged set of permissions..." or similar.

2022-02-25 07:18 UTC, Jackson-Woods commented on concepts/auth-v2-service.md
> +In the OAuth 2.0 client credentials grant flow, you use the Application ID and application secret values that you saved when you registered your app to request an access token directly from the Micro
Same capitalization question as above, "Application ID" vs "application secret"

2022-03-01 19:44 UTC, FaithOmbongi commented on concepts/auth-v2-service.md
> +With the OAuth 2.0 client credentials grant flow, your app authenticates directly at the Microsoft identity platform `/token` endpoint using the Application ID assigned by Azure AD and the applicatio
Fixed instances of ~A~application ID and used the term client secret for consistency.

2022-03-01 19:55 UTC, FaithOmbongi commented on concepts/auth-v2-service.md
> +> We recommend that you configure the least privileged set of permissions required by your app. This improves the security of your app. For more information, see [Enhance security with the principle
OK, changed the two sentences to "Configure the least privileged set of permissions required by your app to improve its security."

2022-03-01 20:01 UTC, FaithOmbongi commented on concepts/auth-v2-service.md
> +In the OAuth 2.0 client credentials grant flow, you use the Application ID and application secret values that you saved when you registered your app to request an access token directly from the Micro
This might have been inherited from a previous decision. I see in our CDK we also recommend using the word "app secret" over "password" but "client secret" wins over "application secret" in search trends. I've fixed this and will fix the CDK as well.

2022-03-01 21:11 UTC, opbld31 commented
Docs Build status updates of commit _[2d76de2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d76de260a9875bcd40320a657e9207d7d04a67b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-2a9d84e1)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-2a9d84e1"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203012109397790-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T21%3A11%3A44Z&sr=b&sp=r&sig=l0PjQ%2F7mlsAPPeVPsk6Di9OdnZijyM1fkYxgqzjJXJA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 21:55 UTC, Jackson-Woods approved these changes
Approved, looks good. One comment - we should disambiguate app id vs object id wherever possible. I have this tracked separately as part of our content refresh workstream.

2022-03-02 14:08 UTC, opbld33 commented
Docs Build status updates of commit _[97c2bf4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97c2bf4cd9c59ddac03bfb1c4c75fe297306b3cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/auth/auth-concepts?branch=pr-en-us-15110) | [Details](#user-content-d4ab88c1452499ac58b968f86358c08f-279b00f2)
[concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-limit-mailbox-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-limit-mailbox-access?branch=pr-en-us-15110) |
[concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/best-practices-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/best-practices-concept?branch=pr-en-us-15110) |
[concepts/images/auth-v2/admin-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/admin-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-application-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-application-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-service?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent-old.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent-old.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-consumer-consent-old.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-consumer-consent.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-consumer-consent.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/auth-v2-user?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-delegated-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-delegated-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-delegated-permissions.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-service-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-service-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-service-registration.png?branch=pr-en-us-15110) |
[concepts/images/auth-v2/v2-web-registration.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/images/auth-v2/v2-web-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/auth-v2/v2-web-registration.png?branch=pr-en-us-15110) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15110) |

<a id="d4ab88c1452499ac58b968f86358c08f-279b00f2"></a>
### [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/freshpassAuthBasics/concepts/auth/auth-concepts.md)
 - **Line 90, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203021405247756-15110%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-02T14%3A08%3A33Z&sr=b&sp=r&sig=5ZFyQfxW6q3%2F4UZ6T5ppV7kAouewS%2BY7cRRQ5ZU9CWk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 03:37 UTC, merged