Exposing Entitlement Management access package assignment approvals in v1.0
microsoftgraph/microsoft-graph-docs pull request #15132
Opened 2021-12-03 22:43 UTC by shubhamguptacal

Exposing Entitlement Management access package assignment approvals in v1.0

2021-12-03 22:45 UTC, opbld34 commented
Docs Build status updates of commit _[4895ecf](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4895ecf59ee22de9f582acfd8e53bdc2460a515f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-root.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) | [Details](#user-content-3f351afe4b69b7f0922dd53d3f03e12b-7a408693)
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="3f351afe4b69b7f0922dd53d3f03e12b-7a408693"></a>
### [api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-root.md)
 - **Line 68, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approval-get.md'.`````
 - **Line 69, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approval-list-stages.md'.`````
 - **Line 70, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approvalstage-get.md'.`````
 - **Line 71, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approvalstage-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032243098617-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T22%3A45%3A07Z&sr=b&sp=r&sig=8vwCK5YO3MkUnnw16WaA2DJcY3G5%2BhOwnU6QcmMM3oY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 21:35 UTC, opbld31 commented
Docs Build status updates of commit _[90f1cc9](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/90f1cc986bcdfcbda31b920220ea02355285bd02)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-root.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) | [Details](#user-content-3f351afe4b69b7f0922dd53d3f03e12b-2fc13bd5)
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |

<a id="3f351afe4b69b7f0922dd53d3f03e12b-2fc13bd5"></a>
### [api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-root.md)
 - **Line 69, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approval-get.md'.`````
 - **Line 70, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approval-list-stages.md'.`````
 - **Line 71, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approvalstage-get.md'.`````
 - **Line 72, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/approvalstage-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302134029556-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T21%3A35%3A41Z&sr=b&sp=r&sig=mjfEt6WpcGnrplZJIabg5msI77W13g5K%2FiL5WibAmFQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 21:45 UTC, opbld30 commented
Docs Build status updates of commit _[6ce1558](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/6ce15580f53e4450213346f3bef820f52d4f70d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302143234946-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T21%3A45%3A19Z&sr=b&sp=r&sig=0KWlORvz8iJ8jbT7lXL22Wautys0Q0EXocdNG1wExI8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 21:53 UTC, opbld34 commented
Docs Build status updates of commit _[5690c62](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/5690c626966af5c3c59de02f251ecd829b786b86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302150596150-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T21%3A53%3A05Z&sr=b&sp=r&sig=49AA4UziKr8m1LradiWfl%2BZjDlQ2fB34gB%2FEW3rh4oI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 21:48 UTC, opbld33 commented
Docs Build status updates of commit _[9bd68bd](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/9bd68bddd375a90921fc99ebdb4ae9ac0f17838b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042145223054-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T21%3A48%3A25Z&sr=b&sp=r&sig=m9OI33J%2BTfaBvjfUiuR0ij%2B1NqitFwwfTdYNLMR%2B4GY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 22:31 UTC, opbld32 commented
Docs Build status updates of commit _[68a0060](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/68a00607d0bac2c12d7f66541741ed9cbae9612b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042229455716-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T22%3A31%3A34Z&sr=b&sp=r&sig=LiWRxfMuTaAFdxXpFbHKfYOscWiQzbrA%2BsJad7aofs0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 23:43 UTC, opbld32 commented
Docs Build status updates of commit _[7813247](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/7813247706ecaad800ca7bda1bf5160dd9469281)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042340551680-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T23%3A43%3A02Z&sr=b&sp=r&sig=iCNm5OautpzViORTPnLCJn201gupDSsY7EVB%2Febrf4k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 10:55 UTC, FaithOmbongi requested changes
Thank you @shubhamguptacal, @markwahl-msft, for raising this PR. A few changes:
- Add accessPackageAssignmentApprovals relationship to [entitlementManagement](https://docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0) resource doc
- File name fixes:
    - entitlementmanagement-accesspackageassignmentapproval-get.md => **approval-get.md**
    - entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md => **approval-filterbycurrentuser.md**
    - entitlementmanagement-accesspackageassignmentapproval-stage-list.md => **approval-list-stages.md**
    - entitlementmanagement-accesspackageassignmentapproval-stage-get.md => **approvalstage-get.md**
    - entitlementmanagement-accesspackageassignmentapproval-stage-update.md => **approvalstage-update.md**
- Please add an changelog entry for the new enum
- I see a docs gap in the beta docs. We haven't documented the filterByCurrentUser function for [approvals](https://docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta).
- I posted a Q about approvalFilterByCurrentUserOptions and it's allowed options. Is it only approver or does the associated method also support **target** and **createdBy** values?

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md
> +---
Fix file name to be **approval-filterbycurrentuser.md** following the syntax _bindingParameterType-functionName.md_

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md
> +# FilterByCurrentUser accessPackageAssignmentApprovals
Following the guidance, title name has the syntax _bindingParameterType: functionName_.
```suggestion
title: "approval: filterByCurrentUser"
description: "Get the approval resources from the accessPackageAssignmentApprovals navigation property."
author: "markwahl-msft"
ms.localizationpriority: medium
ms.prod: "governance"
doc_type: apiPageType
---

# approval: filterByCurrentUser
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md
> +In Azure AD entitlement management, return a collection of the access package assignment approvals.  With the option of `approver`, this returns the access package assignment approvals that the calli
The `approver` value is required in the URL path so no need to mention it here
```suggestion
In Azure AD entitlement management, return a collection of the access package assignment approvals for which the calling user is an approver.
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md
> +This method supports the OData query parameters for paging through a large result set. For general information, see [OData query parameters](/graph/query-parameters).
Functions typically have a function parameters section

Q: approvalFilterByCurrentUserOptions has other values - `target`, `createdBy`, and it seems EM is the only workload using this enum. Does this function also support these two values?
```suggestion
## Function parameters
In the request URL, provide the following query parameters with values.
The following table shows the parameters that can be used with this function.

|Parameter|Type|Description|
|:---|:---|:---|
|on|approvalFilterByCurrentUserOptions| The allowed value is `approver`. Required.|

```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +---
Fix file name to be **approval-list-stages.md** following the syntax: _parententityname-list-navpropertyname.md_

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +# List approvalStages
Title syntax is _List navPropertyName_
```suggestion
title: "List stages"
description: "List approval stages associated with an approval object."
ms.localizationpriority: medium
author: "markwahl-msft"
ms.prod: "governance"
doc_type: "apiPageType"
---

# List stages
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), lists the [approvalStage](../resources/approvalstage.md) objects associated with an [approval](../resources/appro
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), lists the [approvalStage](../resources/approvalstage.md) objects associated with an [approval](../resources/approval.md) object. This call can be made by an approver, providing the identifier of the [access package assignment request](../resources/accesspackageassignmentrequest.md).
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +If successful, this method returns a `200 OK` response code and a collection of the [approvalStage](../resources/approvalstage.md) objects in the response body. However, if the caller does not have t
```suggestion
If successful, this method returns a `200 OK` response code and a collection of the [approvalStage](../resources/approvalstage.md) objects in the response body. If the caller does not have the right permissions, the method returns a `403 Forbidden` response code.
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +GET /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{id}/stages
```suggestion
GET /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{accessPackageAssignmentRequestId}/stages
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +  "name": "get_approval"
Unique name to avoid name clash with approval-get.md
```suggestion
  "name": "list_approvalStage"
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md
> +  "name": "list_approval"
```suggestion
  "name": "approvalthis-filterbycurrentuser"
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +---
Fix file name to approvalstage-get.md

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +author: "sbounouh"
```suggestion
author: "markwahl-msft"
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), retrieve the properties of an [approvalStage](../resources/approvalstage.md) object.  An approval stage is contai
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), retrieve the properties of an [approvalStage](../resources/approvalstage.md) object. An approval stage is contained within an [approval](../resources/approval.md) object.
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +GET /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{id}/stages/{id}
To remove ambiguity
```suggestion
GET /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{accessPackageAssignmentRequestId}/stages/{approvalStageId}
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +If successful, this method returns a `200 OK` response code and the [approvalStage](../resources/approvalstage.md) object in the response body. However, if the caller does not have the right permissi
```suggestion
If successful, this method returns a `200 OK` response code and the [approvalStage](../resources/approvalstage.md) object in the response body. If the caller does not have the right permissions, the method returns a `403 Forbidden` response code.
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +  "name": "get_approvalstage_2"
```suggestion
  "name": "get_approvalstage"
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +author: "sbounouh"
```suggestion
author: "markwahl-msft"
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), apply an approve or deny decision on an [approvalStage](../resources/approvalstage.md) object.
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), approve or deny an [approvalStage](../resources/approvalstage.md) object.
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +PATCH /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{id}/stages/{id}
To remove ambiguity
```suggestion
PATCH /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{accessPackageAssignmentRequestId}/stages/{approvalStageId}
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +If successful, this method returns a `204 No Content` response code in the response body. However, if the caller does not have the right permissions, the method returns a `403 Forbidden` response cod
```suggestion
If successful, this method returns a `204 No Content` response code in the response body. If the caller does not have the right permissions, the method returns a `403 Forbidden` response code. If the approval id is not found, the method returns `404 Not found` response code. If the request has already been approved by another approver in the same approval stage, the method returns `409 Conflict` response code.
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +> **Note:** The response object shown here might be shortened for readability.
No need to have this here because there's no response body so nothing to truncate.
```suggestion
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +Content-Type: application/json
```suggestion
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +---
Fix file name to **approvalstage-update.md**

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/resources/entitlementmanagement-overview.md
> +|[Update approvalStage](../api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | None | Apply approve or deny decision on an **approvalStage** object. |
```suggestion
|[Get approval](../api/approval-get.md) | [approval](approval.md) | Retrieve the properties of an **approval** object. |
|[filterByCurrentUser](../api/approval-filterbycurrentuser.md)| [approval](approval.md) collection| Retrieve the **approval** objects for an approver.|
|[List approvalStages](../api/approval-list-stages.md) | [approvalStage](approvalstage.md) collection | List the **approvalStage** objects associated with an **approval** object. |
|[Get approvalStage](../api/approvalstage-get.md) | [approvalStage](approvalstage.md) | Retrieve the properties of an **approvalStage** object. |
|[Update approvalStage](../api/approvalstage-update.md) | None | Apply approve or deny decision on an **approvalStage** object. |
```

2022-01-11 10:55 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +              href: api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
Let's align this with the beta TOC: https://docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta, but keeping in mind approvalStep (beta) => approvalStage (v1.0), and add the Filer by current user

2022-01-11 10:55 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [filterByCurrentUser](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser) operation to the [appro
```suggestion
          "Description": "Added the [filterByCurrentUser](https://docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser.md) operation to the [approval](https://docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0) resource. Use this method in Azure AD Entitlement Management to retrieve approval objects for which the calling user is an approver.",
```

2022-01-11 10:55 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [get](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get) operation to the [approval](https://docs.microsoft.com/
```suggestion
          "Description": "Added the [get](https://docs.microsoft.com/en-us/graph/api/approval-get.md) operation to the [approval](https://docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0) resource. Use this method in Azure AD Entitlement Management to retrieve approval objects for an [access package assignment request](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest.md) object.",
```

2022-01-11 10:55 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Target": "approval"
```suggestion
          "Description": "Added the [list](https://docs.microsoft.com/en-us/graph/api/approval-list-stages.md) operation to the [approvalStage](https://docs.microsoft.com/en-us/graph/api/resources/approvalStage?view=graph-rest-1.0) resource. Use this method in Azure AD Entitlement Management to retrieve the approval stages associated with an [access package assignment request](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest.md) object.",
          "Target": "approvalStage"
```

2022-01-11 10:55 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [get](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get) operation to the [approvalStage](https://docs.mic
```suggestion
          "Description": "Added the [get](https://docs.microsoft.com/en-us/graph/api/approvalstage-get.md) operation to the [approvalStage](https://docs.microsoft.com/en-us/graph/api/resources/approvalStage?view=graph-rest-1.0) resource. Use this method in Azure AD Entitlement Management to retrieve the details of an approval stage associated with an [access package assignment request](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest.md) object.",
```

2022-01-11 10:55 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [update](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update) operation to the [approvalStage](https://do
```suggestion
          "Description": "Added the [update](https://docs.microsoft.com/en-us/graph/api/approvalstage-update.md) operation to the [approvalStage](https://docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0) resource. Use this method in Azure AD Entitlement Management to update the approval decision of an approval stage associated with an [access package assignment request](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest.md) object.",
```

2022-01-11 10:55 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +      ],
Please add an entry for the approvalFilterByCurrentUserOptions enum.

2022-02-04 17:27 UTC, FaithOmbongi commented
Hi @shubhamguptacal @markwahl-msft - bumping this up in your inbox because this API has been live for a while without docs.

2022-03-07 00:06 UTC, opbld31 commented
Docs Build status updates of commit _[0e1dc52](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/0e1dc52155e7515b7a97a6adcf840e5c77b78e05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203070004304345-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T00%3A06%3A32Z&sr=b&sp=r&sig=XG0WVCW8ZiiRSv2I9mo0V%2Fy1mwWYVbOJMkSeiGiTAz0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 00:08 UTC, opbld34 commented
Docs Build status updates of commit _[f59dbf7](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/f59dbf7a56b1bbb9d8cf5f98f97629c8cfee8c2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203070004460267-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T00%3A08%3A35Z&sr=b&sp=r&sig=QKzO4E7G1tPjGSRHUFJek53wXFXSzt1ctrCDWIUMxL4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[53a40c2](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/53a40c2ee62d696e2d34a6a825823684773995f7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-74a897dc)
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-list?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-accesspackageassignmentapproval-stage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-74a897dc"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml)
 - **Line 5472, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203070031497864-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T00%3A33%3A47Z&sr=b&sp=r&sig=hyM2hmQp4%2F7Ekwk7HQmwKLSieIhO3QPFw0tyJ4ZKa20%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 00:41 UTC, opbld34 commented
Docs Build status updates of commit _[25e6831](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/25e6831a8beb0696d8dfabe854d859ee312963bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) | [Details](#user-content-5735240f16d31699396d5da855f8a598-d53c8219)
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5735240f16d31699396d5da855f8a598-d53c8219"></a>
### [api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md)
 - **Line 71, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md'.`````
 - **Line 72, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md'.`````
 - **Line 73, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203070039365927-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T00%3A41%3A40Z&sr=b&sp=r&sig=dQ%2B%2BGUoLjj0xTgCk%2BP6Lc4HyIG4YzkDUAczt%2BN1Q40Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 00:43 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md
> +---
updating

2022-03-07 00:43 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-get.md
> +author: "sbounouh"
updating

2022-03-07 00:44 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-filterByCurrentUser.md
> +---
updating

2022-03-07 00:44 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-list.md
> +---
updating

2022-03-07 00:45 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-get.md
> +---
updating

2022-03-07 00:45 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +author: "sbounouh"
updating

2022-03-07 00:45 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-accesspackageassignmentapproval-stage-update.md
> +---
updating

2022-03-07 00:49 UTC, opbld34 commented
Docs Build status updates of commit _[262eaa5](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/262eaa5c036e8a38dd5820ed8b97ca4518e15b0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203070047228911-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T00%3A49%3A14Z&sr=b&sp=r&sig=vsMQ%2BUkhDi10dow55Uxi74GhUYasJeN9%2BxUgXZ%2BSCUI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 04:34 UTC, FaithOmbongi approved these changes
Thank you @markwahl-msft, @shubhamguptacal for addressing the feedback. Approved.

I propose that EM starts using the Microsoft.IGAELM.json changelog file instead of the DirectoryServices one so the merge conflicts will be a bit more manageable. The doc stubs already get generated into the Microsoft.IGAELM.json because it corresponds to your workload name, so this wouldn't be a problem. I'll push a commit to this branch to move this PR's changelog to the new file.

2022-03-08 04:34 UTC, FaithOmbongi commented on api-reference/v1.0/api/approval-list-stages.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), lists the [approvalStage](../resources/approvalstage.md) objects associated with an [approval](../resources/appro
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), list the [approvalStage](../resources/approvalstage.md) objects associated with an [approval](../resources/approval.md) object. This call can be made by an approver, providing the identifier of the [access package assignment request](../resources/accesspackageassignmentrequest.md).
```

2022-03-08 04:34 UTC, FaithOmbongi commented on api-reference/v1.0/api/approval-get.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), retrieves the properties of an [approval](../resources/approval.md) object.  This call can be made by an approver
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), retrieve the properties of an [approval](../resources/approval.md) object.  This call can be made by an approver, providing the identifier of the [access package assignment request](../resources/accesspackageassignmentrequest.md).
```

2022-03-08 05:23 UTC, opbld34 commented
Docs Build status updates of commit _[6ffaf57](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/6ffaf57fc93554f1d59205b0d6384b1b46878b1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080521549116-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A23%3A56Z&sr=b&sp=r&sig=wRGkWvl1uGdhwZ6rAZIS9HePgO3tdlPu%2BxcDUtLIzjE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 05:26 UTC, opbld34 commented
Docs Build status updates of commit _[b4e4861](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/b4e486184f86a22bcd72a0885ab4c87a5e34e0ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080523575975-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A26%3A00Z&sr=b&sp=r&sig=fBVcLs6kTNyY6EHoQZWFvukbe6vNlWoayoB7jwtSx8U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 03:18 UTC, opbld34 commented
Docs Build status updates of commit _[5afe3d0](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/5afe3d0d57405b7ef2165df79bda3c2d4ab34f4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203090317001164-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T03%3A18%3A38Z&sr=b&sp=r&sig=xOB9QZ0zWXZ2%2FSfBtEofUg%2BFtFOlNsNe%2BDYdDdzvaeE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 05:30 UTC, Lauragra commented on api-reference/v1.0/api/approval-filterbycurrentuser.md
> +title: "approval: filterByCurrentUser"
We seem to be missing this file in the /beta folder, but I can verify that this function is defined in the /beta metadata. Please add a beta topic for this function. Please also surface this method in the v1.0 (and beta) TOC.

2022-03-09 05:45 UTC, opbld33 commented
Docs Build status updates of commit _[42874ae](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/42874ae6a4f72eedbbbb946816b88a2e9bf2acec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203090538529311-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T05%3A45%3A20Z&sr=b&sp=r&sig=vO03HZfKbculJ4SR3UiRm%2B9asYF3uR94tEhV6oHjr9o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 06:03 UTC, opbld30 commented
Docs Build status updates of commit _[3e659f6](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/3e659f614b018ef2831db89d911e1bd6da4b7b96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.github/workflows/changelog-validation.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/.github/workflows/changelog-validation.yml) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203090600572659-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T06%3A03%3A04Z&sr=b&sp=r&sig=t2GhfKpW7VObXJ6w7v4x333eNfN4ctZ6RdDpCVdutmo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 06:10 UTC, opbld31 commented
Docs Build status updates of commit _[3af5cc9](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/3af5cc9f9957eec21f36d8970908b8c2381edb61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/approval-filterbycurrentuser.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-get.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-get?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approvalstage-update.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/api/approvalstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approvalstage-update?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/entitlementmanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-15132) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup/approvals-1_0/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203090609108415-15132%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T06%3A10%3A55Z&sr=b&sp=r&sig=Hdnmm6EcclDN3U9M3PFQ4Ya6Xaz1QsNuwgZN9qPctvQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 06:14 UTC, merged

2023-03-17 09:25 UTC, FaithOmbongi commented
The changes are live. Removing the changes requested label to avoid unactionable notifications. Might need to tweak the bot a bit.