Move attendance report documentation to v1
microsoftgraph/microsoft-graph-docs pull request #15149
Opened 2021-12-06 20:29 UTC by frankpeng7

2021-12-06 20:31 UTC, opbld33 commented
Docs Build status updates of commit _[7870412](https://github.com/microsoftgraph/microsoft-graph-docs/commits/787041267fe6f8987c60af747a934f5053d794c6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :x:Error | | [Details](#user-content-f4d26a1b279e3975b94a05f09a275950-5b13d230)
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :warning:Warning | | [Details](#user-content-38caf890e73c10d19ebce876db482fbb-5b13d230)
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :warning:Warning | | [Details](#user-content-d0a9d39312289c9738a98a6e6adafd22-5b13d230)

<a id="f4d26a1b279e3975b94a05f09a275950-5b13d230"></a>
### [api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md)
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-attendancerecord-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-attendancerecord-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-attendancerecord-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-attendancerecord-java-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-attendancerecord-go-snippets.md'.`````

<a id="38caf890e73c10d19ebce876db482fbb-5b13d230"></a>
### [api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md)
 - **Line 60, Column 201**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-2-get-the-latest-attendance-report-for-an-online-meeting' in 'v1.0/api/meetingattendancereport-get.md'.`````

<a id="d0a9d39312289c9738a98a6e6adafd22-5b13d230"></a>
### [api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md)
 - **Line 26, Column 25**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attendanceInterval.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112062029381045-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T20%3A31%3A06Z&sr=b&sp=r&sig=xjAOi%2BGPIO49wDpZ9C7ok4MvakY%2BRoHWHbIdsF95VbE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 20:34 UTC, opbld32 commented
Docs Build status updates of commit _[3eae867](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3eae867683f680fab37004660e266ce9c543ee2c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :x:Error | | [Details](#user-content-f4d26a1b279e3975b94a05f09a275950-8a9f01c5)
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :warning:Warning | | [Details](#user-content-38caf890e73c10d19ebce876db482fbb-8a9f01c5)
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :warning:Warning | | [Details](#user-content-d0a9d39312289c9738a98a6e6adafd22-8a9f01c5)

<a id="f4d26a1b279e3975b94a05f09a275950-8a9f01c5"></a>
### [api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md)
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-attendancerecord-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-attendancerecord-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-attendancerecord-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-attendancerecord-java-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-attendancerecord-go-snippets.md'.`````

<a id="38caf890e73c10d19ebce876db482fbb-8a9f01c5"></a>
### [api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md)
 - **Line 60, Column 201**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-2-get-the-latest-attendance-report-for-an-online-meeting' in 'v1.0/api/meetingattendancereport-get.md'.`````

<a id="d0a9d39312289c9738a98a6e6adafd22-8a9f01c5"></a>
### [api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md)
 - **Line 26, Column 25**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attendanceInterval.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112062032531071-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T20%3A34%3A21Z&sr=b&sp=r&sig=0sNb%2FERYgzkl5wijdjDnbQDqkSNUOWu6ryiUJIFN8lc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 20:38 UTC, opbld32 commented
Docs Build status updates of commit _[428f732](https://github.com/microsoftgraph/microsoft-graph-docs/commits/428f732d69ba51adacc54a23890cab82140f4f92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112062036114484-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T20%3A38%3A11Z&sr=b&sp=r&sig=sxuxYwv3r1L97rtOBfXtryTosXpldpXoTHoIixJ%2FEMQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 21:44 UTC, JarbasHorst requested changes

2021-12-08 21:44 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +| attendanceIntervals | [attendanceInterval](attendanceInterval.md) collection | List of time periods between joining and leaving. |
For clarity, please add "a meeting" after "leaving".

2021-12-08 21:44 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +| role | String | Role of the attendee. Possible values are `None`, `Attendee`, `Presenter`, and `Organizer`.  |
For consistency, please add colon after are.

2021-12-08 21:44 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +| identity | [Identity](identity.md) | Identifier, such as display name. |
1) For clarity, please describe what identity represents. For example,

- The user associated with this action.

2) Note that entity names in Microsoft Graph are lower camel case, so Identity in this case should be lower case.

2021-12-08 21:44 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +| role | String | Role of the attendee. Possible values are `None`, `Attendee`, `Presenter`, and `Organizer`.  |
Please, replace String with the corresponding enum for role.

2021-12-08 21:44 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +| emailAddress | String | Email address. |
Is this the email address of a user? Please be more specific in the description.

2021-12-08 21:44 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the [attendanceRecord](https://docs.microsoft.com/en-us/graph/api/resources/attendanceRecord?view=graph-rest-1.0) resource",
For consistency, please add "and a supported method." after "resource". Also, please add a period at the end of the sentence.

2021-12-08 21:44 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the [meetingAttendanceReport](https://docs.microsoft.com/en-us/graph/api/resources/meetingAttendanceReport?view=graph-rest-1.0) resource",
For consistency, please add "and supported methods." after "resource". Also, please add a period at the end of the sentence.

2021-12-08 21:44 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Relationship".

2021-12-08 21:44 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the **attendanceReports** relationship to [onlineMeeting](https://docs.microsoft.com/en-us/graph/api/resources/onlineMeeting?view=graph-rest-1.0) resource.",
Please, add "the" before "onlineMeeting".

2021-12-09 01:06 UTC, frankpeng7 commented on api-reference/v1.0/api/attendancerecord-list.md
> +This method supports the [OData query parameters](/graph/query-parameters) to help customize the response.
We don't support those query parameters

2021-12-09 01:24 UTC, frankpeng7 commented on api-reference/v1.0/resources/attendanceInterval.md
> +> When data is lacking, the value of **joinDateTime** or **leaveDateTime** will be set to `null`, and the value of **durationInSeconds** will be set to `0` in the response body of the [Get meeting at
changed to another way. Please let me know if it's ok.

2021-12-09 01:37 UTC, opbld31 commented
Docs Build status updates of commit _[379d702](https://github.com/microsoftgraph/microsoft-graph-docs/commits/379d702416d53505152637e1654714c377f49b70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090136242523-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T01%3A37%3A57Z&sr=b&sp=r&sig=dtpglbzRN9Ss9Bk%2F5yGMpsPiq1ZLc3m9bYk3tQKOxZQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 22:32 UTC, JarbasHorst commented on api-reference/v1.0/api/attendancerecord-list.md
> +To use application permission for this API, tenant administrators must create an application access policy and grant it to a user. This authorizes the app configured in the policy to fetch online mee
I noticed that you removed the reference link from "application access policy". This is not needed because in that case the reference link was describing the process. Now, if it's a reference to the topic itself, then you should use the topic title. For simplicity, I recommend you to revert this change. In detail, please remove this sentence "For more details, see Allow applications to access online meetings on behalf of a user." and add a reference link to "application access policy".

Please, apply this change also here:

- api-reference/v1.0/api/meetingattendancereport-get.md
- api-reference/v1.0/api/meetingattendancereport-list.md

2021-12-09 22:32 UTC, JarbasHorst commented on api-reference/v1.0/api/attendancerecord-list.md
> +>- `userId` is the object ID of a user in [Azure user management portal](https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade). For more details, see [application access policy]
This change is still needed: The link "Application access policy" is a reference to a concept topic. In this case, please replace "application access policy" with "Allow applications to access online meetings on behalf of a user".

Please, apply this change to the same section in the following API topics:

- api-reference/v1.0/api/meetingattendancereport-get.md
- api-reference/v1.0/api/meetingattendancereport-list.md

2021-12-09 22:32 UTC, JarbasHorst commented on api-reference/v1.0/api/attendancerecord-list.md
> +This method supports the [OData query parameters](/graph/query-parameters) to help customize the response.
This sentence "This method supports the $count, $expand, $filter, $orderBy, $search, $select, and $top OData query parameters to help customize the response." is just an example. The idea is to be more specific and provide the OData query parameters that are supported for this API. If only $select is supported, then you should update the sentence to contain this information.

2021-12-09 22:32 UTC, JarbasHorst commented on api-reference/v1.0/api/attendancerecord-list.md
> +      "emailAddress": "(email address)",
Please replace all placeholders in this example, such as (email address), (redacted), and (display name), with fictitious values. 

Please, apply this change also here:

- api-reference/v1.0/api/meetingattendancereport-get.md
- api-reference/beta/api/attendancerecord-list.md

2021-12-09 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +| role | String | Role of the attendee. Possible values are `None`, `Attendee`, `Presenter`, and `Organizer`.  |
Thanks for clarifying.

2021-12-09 23:00 UTC, JarbasHorst requested changes

2021-12-09 23:00 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the [attendanceRecord](https://docs.microsoft.com/en-us/graph/api/resources/attendanceRecord?view=graph-rest-1.0) resource and supported methods.",
Please, replace "supported methods" with "a supported method". This resource type introduces only one API topic.

2021-12-09 23:00 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendanceInterval.md
> +| durationInSeconds | Int32 | Duration of the meeting interval in seconds; that is, the difference between **joinDateTime** and **leaveDateTime**. |
For consistency and to improve scanning, please move **durationInSeconds** to come before **joinDateTime**.

2021-12-09 23:00 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendanceInterval.md
> +
Please, remove this empty line. Please, apply this change also to line 46.

2021-12-09 23:00 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +Contains information associated with an attendance record in a meeting attendance report.
For clarity, I recommend you to replace "meeting attendance report" with \[meetingAttendanceReport\](../resources/meetingAttendanceReport.md). If you take this revision, please replace "meeting attendance report" with "meetingAttendanceReport" (line 3).

2021-12-09 23:00 UTC, JarbasHorst commented on api-reference/v1.0/resources/attendancerecord.md
> +
Please, remove this empty line. Please, apply this change also to line 60.

2021-12-09 23:00 UTC, JarbasHorst commented on api-reference/v1.0/resources/meetingattendancereport.md
> +{
Please, add the **id** property to the JSON representation.

2021-12-09 23:39 UTC, frankpeng7 commented on api-reference/v1.0/api/attendancerecord-list.md
> +To use application permission for this API, tenant administrators must create an application access policy and grant it to a user. This authorizes the app configured in the policy to fetch online mee
> This is not needed because in that case the reference link was describing the process.

Yes the reference link IS describing the process.

2021-12-09 23:44 UTC, frankpeng7 commented
> This sentence "This method supports the $count, $expand, $filter, $orderBy, $search, $select, and $top OData query parameters to help customize the response." is just an example. The idea is to be more specific and provide the OData query parameters that are supported for this API. For example, if only $select is supported for this API, then you should update the sentence to contain this information.

@JarbasHorst  we don't support any of those. If I could I would remove this section but it's required.

2021-12-09 23:45 UTC, opbld32 commented
Docs Build status updates of commit _[1d37b6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d37b6bc269383d5a640b8e8e2e6b513632d88e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7f56e3b1)

<a id="7f56e3b1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112092345075807-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T23%3A45%3A28Z&sr=b&sp=r&sig=635xclcBBj89loqkIWOfPZ5jwaScZ7jPSqB5lXveY3g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 23:48 UTC, opbld34 commented
Docs Build status updates of commit _[f21ac6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f21ac6f423dc26d32c8fcdfbb03d84a183c9d37c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112092347016880-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T23%3A48%3A40Z&sr=b&sp=r&sig=iygOeL0el1dZyQ%2FBnyUa1GUvQ0mCYyRLGGWYOv%2FOIuE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-13 22:15 UTC, mkhribech commented
@JarbasHorst please let us know when the PR will be released.

2021-12-14 00:39 UTC, JarbasHorst commented
Hello @mkhribech, the PR can be merged after we finished the content review work and the PR author set the label ready to merge. Currently, the content review work is still in progress. Please contact us via Teams if you want to share some urgency about this PR.

2021-12-14 22:31 UTC, JarbasHorst commented
@isvargasmsft this PR is ready for final review.

2021-12-15 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[5d4691a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d4691aff100b2f023e3ce6d30360d661bc81f14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112151606556218-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T16%3A08%3A37Z&sr=b&sp=r&sig=y2GVKLFrzTgQd1z5uTJql9J%2FtnBtVjO2Kmx%2FGvTd68g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 20:37 UTC, isvargasmsft commented on api-reference/v1.0/resources/meetingattendancereport.md
> +| attendanceRecords | [attendanceRecord](attendanceRecord.md) collection | List of attendance records of an attendance report. Read-only. |
Attentance records is not a navigation property in the CSDL, but a regular property. Please clarify.

2021-12-15 20:49 UTC, opbld33 commented
Docs Build status updates of commit _[edf1803](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edf180323bcffe3291c74d0f54379b3c4fc24627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceInterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152047494754-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T20%3A49%3A40Z&sr=b&sp=r&sig=z4E8XCBLiLzAYhiqGOrFoyjEUq6ySHbnGKEpO6sOfJs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 20:51 UTC, opbld34 commented
Docs Build status updates of commit _[06210b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06210b29fc1cdd54768fb6b98b5c01bde234665f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceinterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceinterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152048444109-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T20%3A51%3A29Z&sr=b&sp=r&sig=nDZLjUeh9NsYv6Z%2ByWkxVwoGHmIcrHmcknGK3qWQzF8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 20:55 UTC, opbld31 commented
Docs Build status updates of commit _[869ae73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/869ae73b7c07edb190d8dec80dc290a74e7ef896)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceinterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceinterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152053551400-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T20%3A55%3A37Z&sr=b&sp=r&sig=GAENnrehQtDfNu3bUgZuarqVFOXMpRT7UUlFn2r1KdM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 20:58 UTC, isvargasmsft approved these changes

2021-12-15 21:38 UTC, opbld34 commented
Docs Build status updates of commit _[de742db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de742db3104eab867921a33eb9623ce821c4ff93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendanceinterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/beta/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/beta/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-15149) (graph-rest-beta) |
[api-reference/v1.0/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/api/meetingattendancereport-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/api/meetingattendancereport-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendanceinterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingattendancereport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/meetingattendancereport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-1.0&branch=pr-en-us-15149) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attendance-reports-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152136453199-15149%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T21%3A38%3A17Z&sr=b&sp=r&sig=GFaoZpbltdY7%2Fy4F6A%2B0yum1KLeuZAnZzgAsUCnIuks%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 22:04 UTC, merged