added documentation for live event captions (beta)
microsoftgraph/microsoft-graph-docs pull request #15152
Opened 2021-12-07 00:14 UTC by frankpeng7

2021-12-07 00:16 UTC, opbld34 commented
Docs Build status updates of commit _[8151e19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8151e19b7d30878e4b23b22bba2babe3b9e19890)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/broadcastmeetingcaptionsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingcaptionsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingcaptionsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112070014334412-15152%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T00%3A16%3A13Z&sr=b&sp=r&sig=YYcHyCURNG%2FFDO4bAKwFUg%2BSO%2FTTdJwTrGvuXcP2WWI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 00:23 UTC, opbld32 commented
Docs Build status updates of commit _[a628895](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a628895a7de8439a63356dffccd2a0dd2f4e5f77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/broadcastmeetingcaptionsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingcaptionsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingcaptionsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112070021429537-15152%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T00%3A23%3A40Z&sr=b&sp=r&sig=NCID3S2UKLrzvwJUz39BnNE6V6RQirvGzK1twpYorQc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 19:48 UTC, JarbasHorst requested changes

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +Caption settings related to a [Microsoft Teams live event](/microsoftteams/teams-live-events/what-are-teams-live-events). Refer to [see also](#see-also) section for Teams client behavior of this feat
Similar to the description attribute above, I recommend you to rephrase the first sentence. In case of the second sentence, I recommend you to either bring the "Use live captions in a live event" link to the summary section or remove this sentence and keep the See also section. From the UX point of view, I first need to click on a link to click on a second link where I will finally find more details. Suggested revision:

-  Represents caption settings related to a \[live event\](/microsoftteams/teams-live-events/what-are-teams-live-events) in Microsoft Teams. For details about how to use live captions in Teams clients, see \[Use live captions in a live event\](https://support.microsoft.com/en-us/office/use-live-captions-in-a-live-event-1d6778d4-6c65-4189-ab13-e2d77beb9e2a).

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| isCaptionEnabled     | Boolean           | Indicates if caption is enabled.     |
Please, replace "if" with "whether".

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +>- Translation language must be different from spoken language.
Please, provide more details here. Does it mean that all languages added to the translationLanguages collection must be different than the spoken language specified in the spokenLanguage property?

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +>- See following tables for supported language codes for spoken language and translation languages.
I recommend you to remove this sentence and move the descriptions to the corresponding enums. Suggested revision:

### spokenLanguage values

The following lists the supported language codes for spoken languages.

### translationLanguaes values

The following lists the supported language codes for translation languages.

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +>- You can only provide up to 6 translation languages.
This information is already present in the Properties table. In this case, I recommend you to remove this sentence.

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| Bosnia (Latin)                           | bs      |
Please, replace "Bosnia" with "Bosnian".

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| Creole (Haiti)                           | ht      |
In this case, creole is the language family. For clarity, please replace "Creole" with "Haitian Creole".

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| Norwegian (Norway)                       | nb      |
"nb" represents Norwegian Bokmål. Should it be no (Norwegian) instead?

2021-12-08 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingsettings.md
> +| captions | [broadcastMeetingCaptionSettings](../resources/broadcastmeetingcaptionsettings.md) | Teams live event caption settings. |
For consistency with the resource topic, I recommend you to replace "Teams live event caption settings." with:

- Caption settings related to a live event in Teams.

2021-12-08 19:48 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the **captions** property to [broadcastMeetingSettings](https://docs.microsoft.com/en-us/graph/api/resources/broadcastMeetingSettings?view=graph-rest-beta) resource.",
Please, add "the" before broadcastMeetingSettings.

2021-12-08 22:50 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +>- Translation language must be different from spoken language.
That's correct. You can't translate a language into the same language. Would this sound better?

> Translation languages cannot contain the same language code as spoken language.

2021-12-08 22:55 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| Creole (Haiti)                           | ht      |
![image](https://user-images.githubusercontent.com/16726609/145304363-cb8964f1-56c2-4585-a20c-f7577945c83f.png)

I'm not the expert here to argue about language code, but I got the label from Teams client and thought keeping the words the same would help with any confusion it might cause

2021-12-08 23:05 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| Norwegian (Norway)                       | nb      |
Yea I'll need to double check with the team on this. I think the code they're using for this is `nb-no` but that seems to be another format. Anyone I'll take this down from the documentation for now.

2021-12-08 23:30 UTC, frankpeng7 commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the **captions** property to [broadcastMeetingSettings](https://docs.microsoft.com/en-us/graph/api/resources/broadcastMeetingSettings?view=graph-rest-beta) resource.",
This was auto generated - I suppose I shouldn't modify it, but I'll update this.

2021-12-08 23:33 UTC, frankpeng7 commented
Hi @JarbasHorst thanks for the feedback. I've made some changes accordingly and left some comments open for discussion.

2021-12-08 23:34 UTC, opbld31 commented
Docs Build status updates of commit _[28d6549](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28d654986f2310ab9623d7a5810ff7210bcce8f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/broadcastmeetingcaptionsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingcaptionsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingcaptionsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112082332100764-15152%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T23%3A34%3A04Z&sr=b&sp=r&sig=9q4FsOLlYwsbGDkh5UoyrwQZM9mSY7ljZtmrtIdawu8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 23:35 UTC, opbld34 commented
Docs Build status updates of commit _[35296f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35296f75724380289c319fba2f08a9b3d9bef556)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/broadcastmeetingcaptionsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingcaptionsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingcaptionsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112082332378620-15152%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T23%3A35%3A51Z&sr=b&sp=r&sig=kn5d7kziuARhsDtCKOFV2fKo2CEQDlQlHn6Ze3cuIZE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 21:42 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +The following lists the supported language codes for spoken language.
For clarity, please replace "lists" with "table shows".

2021-12-09 21:42 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +The following lists the supported language codes for translation languages.
For clarity, please replace "lists" with "table shows".

2021-12-09 21:42 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +Represents caption settings related of a Microsoft Teams [live event](/microsoftteams/teams-live-events/what-are-teams-live-events). For details about how to use live captions in Teams client, see [U
1) Please remove "related". Suggested revision:

- Represents caption settings of a Microsoft Teams...

2) Please add "a" before Teams. Suggested revision:

- ...live captions in a Teams client, see...

2021-12-09 21:47 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +| Creole (Haiti)                           | ht      |
Thanks for clarifying! I think we can keep "Creole" because it should be clear for users.

2021-12-09 21:52 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the **captions** property to [broadcastMeetingSettings](https://docs.microsoft.com/en-us/graph/api/resources/broadcastMeetingSettings?view=graph-rest-beta) resource.",
Thanks for updating the description. In general, you can edit the changelog if needed.

2021-12-09 22:06 UTC, opbld34 commented
Docs Build status updates of commit _[af8a0e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af8a0e77bf35728847f780381a67fb4972fbdcff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/broadcastmeetingcaptionsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingcaptionsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingcaptionsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-15152) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live-event-captions-beta/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112092204384039-15152%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T22%3A06%3A27Z&sr=b&sp=r&sig=%2FK%2BhTAtKcNLv5iYhhgnTQoGtwC70JGXlTmn1YPhxBwM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 23:14 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +Represents caption settings related of a Microsoft Teams [live event](/microsoftteams/teams-live-events/what-are-teams-live-events). For details about how to use live captions in Teams client, see [U
The idea is to distinguish between a specific Teams client and any. I recommend you to use "a Teams client".

2021-12-10 16:56 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +Represents caption settings related of a Microsoft Teams [live event](/microsoftteams/teams-live-events/what-are-teams-live-events). For details about how to use live captions in Teams client, see [U
Hi @JarbasHorst I'm afraid I don't understand "a specific Teams client and any". As I said this is referring to the one and only Teams app. Would it be better to understand if I just use "Microsoft Teams"?

2021-12-10 18:31 UTC, JarbasHorst commented on api-reference/beta/resources/broadcastmeetingcaptionsettings.md
> +Represents caption settings related of a Microsoft Teams [live event](/microsoftteams/teams-live-events/what-are-teams-live-events). For details about how to use live captions in Teams client, see [U
I got your point. Let's leave it as it.

2021-12-10 18:33 UTC, JarbasHorst commented
@isvargasmsft this PR is ready for final review.

2021-12-10 22:00 UTC, isvargasmsft approved these changes

2021-12-15 21:34 UTC, merged