Asaniyer bookingsbetaupdate
microsoftgraph/microsoft-graph-docs pull request #15164
Opened 2021-12-07 21:28 UTC by razortbone

This PR handles changes needed to add the following properties:

1. customQuestions property in bookingBusiness and associated changes in bookingAppointment, bookingService. 
2. maxAttendeeCount and FilledAttendeeCount in bookingAppointment
3. maxAttendeeCount in bookingService 
4. customer property in bookingAppointment, customQuestionAnswers as a property within customer

2021-12-07 21:30 UTC, opbld34 commented
Docs Build status updates of commit _[36929ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36929ae771c20e5ffd6186a7dd90b2c7c4ebb34b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-6e686a32)
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-140e771a89e71d65f0ab2e645de48438-6e686a32)
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-ba20ba3feb6e07e8f7e20d7bd46c4ae0-6e686a32)
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-f7d89acf707e1aec62f3404f2f0d1b66-6e686a32)
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-b1a450c3b16413f976950bcaa8a87f49-6e686a32)
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-acc1d6617ea62a7007fcb30a4184e643-6e686a32)
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-34fd6efb02497e67af3b4b7c26590dd6-6e686a32)
[api-reference/beta/resources/bookingquestionanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionanswer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionanswer?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c51b43a524eca7c53ddc1034b66b51c8-6e686a32)
[api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionassignment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c95143d128113350ea9cb6ef6d183fbf-6e686a32)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-6e686a32)
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-23c51c60d9b0f6d5ba3f5a9e5b525e8f-6e686a32)
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a600ec9b891f2774d399346bb18914b4-6e686a32)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

<a id="e25f8c561ce16dfb6b0055b43d384dd5-6e686a32"></a>
### [api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See docu [...]

2021-12-07 22:21 UTC, opbld32 commented
Docs Build status updates of commit _[3a69538](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a69538217ff4b31747a90b4bf0cbe2d436729ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-0c4f7912)
[api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionassignment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c95143d128113350ea9cb6ef6d183fbf-0c4f7912)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-0c4f7912)
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-23c51c60d9b0f6d5ba3f5a9e5b525e8f-0c4f7912)
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a600ec9b891f2774d399346bb18914b4-0c4f7912)
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingquestionanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionanswer?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

<a id="e25f8c561ce16dfb6b0055b43d384dd5-0c4f7912"></a>
### [api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List customQuestions - Microsoft Graph beta' is duplicated in: 'beta/api/bookingbusiness-list-customquestions.md(2,8), beta/api/meetingregistration-list-customquestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List customQuestions' is duplicated with other articles: 'beta/api/bookingbusiness-list-customquestions.md(10,1), beta/api/meetingregistration-list-customquestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c95143d128113350ea9cb6ef6d183fbf-0c4f7912"></a>
### [api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contrib [...]

2021-12-07 22:59 UTC, opbld32 commented
Docs Build status updates of commit _[c4f00a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4f00a97ed902b9e9666cfef0cca05611a477364)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-849409fb)
[api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionassignment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c95143d128113350ea9cb6ef6d183fbf-849409fb)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-849409fb)
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-23c51c60d9b0f6d5ba3f5a9e5b525e8f-849409fb)
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a600ec9b891f2774d399346bb18914b4-849409fb)
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingquestionanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionanswer?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

<a id="e25f8c561ce16dfb6b0055b43d384dd5-849409fb"></a>
### [api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List customQuestions - Microsoft Graph beta' is duplicated in: 'beta/api/bookingbusiness-list-customquestions.md(2,8), beta/api/meetingregistration-list-customquestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List customQuestions' is duplicated with other articles: 'beta/api/bookingbusiness-list-customquestions.md(10,1), beta/api/meetingregistration-list-customquestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c95143d128113350ea9cb6ef6d183fbf-849409fb"></a>
### [api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contrib [...]

2021-12-08 22:05 UTC, opbld30 commented
Docs Build status updates of commit _[5dabcec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dabceca660f18e7e07efe9e65b802c326665ad5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-672e7457)
[api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionassignment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c95143d128113350ea9cb6ef6d183fbf-672e7457)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-672e7457)
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-23c51c60d9b0f6d5ba3f5a9e5b525e8f-672e7457)
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a600ec9b891f2774d399346bb18914b4-672e7457)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingquestionanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionanswer?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

<a id="e25f8c561ce16dfb6b0055b43d384dd5-672e7457"></a>
### [api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [S [...]

2021-12-08 22:27 UTC, opbld32 commented
Docs Build status updates of commit _[757983e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/757983e3c1b7f814859ff9a1b2d48aa03e12cfd4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-3d4d2f1b)
[api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionassignment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c95143d128113350ea9cb6ef6d183fbf-3d4d2f1b)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-3d4d2f1b)
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-23c51c60d9b0f6d5ba3f5a9e5b525e8f-3d4d2f1b)
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a600ec9b891f2774d399346bb18914b4-3d4d2f1b)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingquestionanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionanswer?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

<a id="e25f8c561ce16dfb6b0055b43d384dd5-3d4d2f1b"></a>
### [api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [S [...]

2021-12-09 08:08 UTC, opbld32 commented
Docs Build status updates of commit _[f3dfac6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3dfac6c8fd5eb202b403f07013ea7d4fcdfcba7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-60877842)
[api-reference/beta/resources/bookingquestionassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionassignment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-c95143d128113350ea9cb6ef6d183fbf-60877842)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-60877842)
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-23c51c60d9b0f6d5ba3f5a9e5b525e8f-60877842)
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a600ec9b891f2774d399346bb18914b4-60877842)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingquestionanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingquestionanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingquestionanswer?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

<a id="e25f8c561ce16dfb6b0055b43d384dd5-60877842"></a>
### [api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [S [...]

2021-12-10 20:06 UTC, opbld31 commented
Docs Build status updates of commit _[eff0145](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eff0145c3dc48ec68c63c72a385c495044db2484)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-52f6d99c)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-52f6d99c)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-10 20:17 UTC, opbld34 commented
Docs Build status updates of commit _[a834443](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a83444383f18e7ac30062f1dabf73fb3224fed5a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-77d8f7ec)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-77d8f7ec)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-10 20:31 UTC, opbld34 commented
Docs Build status updates of commit _[6274296](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62742964296ef4e6aeff7ad2a552debef3d430bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-b72e9bf8)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-b72e9bf8)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-10 20:38 UTC, opbld30 commented
Docs Build status updates of commit _[557387c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/557387c41434ed576bb4da24c68c9cf8f500b454)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-a059e29a)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-a059e29a)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-13 16:01 UTC, isvargasmsft commented on changelog/Microsoft.Bookings.json
> +                    "Id": "cf0d6a74-9a5a-4748-96be-761807da48c7",
Is there a reason to modify pre-existing changelist entries? Can you please revert these changes and edit only the newly added records?

2021-12-13 16:02 UTC, isvargasmsft commented on changelog/Microsoft.Bookings.json
> +                    "Id": "cf0d6a74-9a5a-4748-96be-761807da48c7",
I see, please add a new changelist for the new records.

2021-12-13 16:35 UTC, opbld33 commented
Docs Build status updates of commit _[082d5cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/082d5cf395c0af0967cd30607cde4e741cfca527)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-0336dead)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-0336dead)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-13 17:19 UTC, opbld32 commented
Docs Build status updates of commit _[9e060ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e060eacda287a4f9bf6dadf7d477cffb63fee21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-0d485d00)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-0d485d00)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-13 18:05 UTC, isvargasmsft commented on api-reference/beta/resources/bookingappointment.md
> +|invoiceId (deprecated)|String|The ID of the invoice.|
Apply to all files in this PR: Please order properties alphabetically.

2021-12-13 21:04 UTC, isvargasmsft commented on api-reference/beta/resources/bookingappointment.md
> +|customers|[bookingCustomerInformation](../resources/bookingcustomerinformation.md) collection|It lists down the customer properties for an appointment. An appointment will contain a list of customer
Line 33: In the api.md file the type is `Collection(bookingCustomerInformationBase)`. Could you please clarify?

2021-12-13 22:05 UTC, opbld31 commented
Docs Build status updates of commit _[e57673e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e57673e0a05ac804f111fa3ec841be8373a5b2ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-455c26a4)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-455c26a4)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-13 22:06 UTC, isvargasmsft commented on changelog/Microsoft.Bookings.json
> +                    "Target": "answerInputType"
I dont see a reference to this new enum in the api.md files, nor I see an addition in the enums.md file in this PR. 

Please clarify.

2021-12-13 22:16 UTC, isvargasmsft requested changes
Hello Aswin, 

Thank you for your work in this PR. 

Please ping me on the side if you have any questions regarding my comments. 

Kind regards,

Isaac

2021-12-14 17:40 UTC, razortbone commented on changelog/Microsoft.Bookings.json
> +                    "Target": "answerInputType"
answerInputType is used in api-reference/beta/resources/bookingcustomquestion.md.

2021-12-14 18:54 UTC, razortbone commented on api-reference/beta/resources/bookingappointment.md
> +|invoiceId (deprecated)|String|The ID of the invoice.|
Done

2021-12-14 18:54 UTC, razortbone commented on api-reference/beta/resources/bookingcustomerinformation.md
> +|customQuestionAnswers|[bookingQuestionAnswer](../resources/bookingquestionanswer.md) collection|It consists of the list of custom questions and answers given by the customer as part of the appointme
Done

2021-12-14 18:55 UTC, opbld34 commented
Docs Build status updates of commit _[ed88961](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed889614871b27acc1e8e317eb2d9e47b04e8477)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0bbaa232)

<a id="0bbaa232"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112141853412006-15164%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-14T18%3A55%3A25Z&sr=b&sp=r&sig=LV1iHelve%2FTq%2FPq3%2F%2For2VfOV%2ByfSQgWkwfOUmOoX9E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-14 18:55 UTC, razortbone commented on api-reference/beta/resources/bookingappointment.md
> +|customers|[bookingCustomerInformation](../resources/bookingcustomerinformation.md) collection|It lists down the customer properties for an appointment. An appointment will contain a list of customer
This can be retained as is. The Base type was introduced based on the recommendation of the Graph Review Team.

2021-12-14 18:56 UTC, razortbone commented on changelog/Microsoft.Bookings.json
> +                    "Target": "answerInputType"
Have added entry in enums.md file for this. Thanks

2021-12-14 18:57 UTC, razortbone commented
> Hello Aswin,
> 
> Thank you for your work in this PR.
> 
> Please ping me on the side if you have any questions regarding my comments.
> 
> Kind regards,
> 
> Isaac

Have addressed the comments in the latest commit. Please take a look and let me know if anything else is required.

2021-12-14 19:12 UTC, opbld33 commented
Docs Build status updates of commit _[b522ead](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b522ead376be7f244725fa84fdfbe9cd70e299ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-1a64fd84)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-1a64fd84)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-14 20:19 UTC, razortbone commented
> Hello Aswin,
> 
> Thank you for your work in this PR.
> 
> Please ping me on the side if you have any questions regarding my comments.
> 
> Kind regards,
> 
> Isaac

Fixed the PR with necessary changes. Please let me know if anything else is required.

2021-12-14 20:21 UTC, opbld32 commented
Docs Build status updates of commit _[b522ead](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b522ead376be7f244725fa84fdfbe9cd70e299ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-e1a5ee8d)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-e1a5ee8d)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-14 21:20 UTC, opbld32 commented
Docs Build status updates of commit _[b18a2ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b18a2ab12ec526ee47d7559fe0fafbbdbee9245e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-97d3a058)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-97d3a058)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingcustomquestion.md
> +| [Delete bookingCustomQuestion](../api/bookingcustomquestion-delete.md)         | None                                                                      | Deletes a [bookingCustomQuestion](../res
Please, replace "Deletes" with "Delete".

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingcustomquestion.md
> +| answerInputType | answerInputType   | The expected answer type.The possible values are: `text`, `radioButton`, `unknownFutureValue`.     |
Please, add space after type. Suggested revision:

- ...type. The...

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingnamedentity.md
> +description: "This is a base type for Microsoft Bookings entities that provide a display name, for example, bookingBusiness, bookingPerson, bookingService."
Please, add "and" before "bookingService."

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +|answerInputType|answerInputType|The expected answer type.The possible values are: `text`, `radioButton`, `unknownFutureValue`.|
Please, add space after type. Suggested revision:

- ...type. The...

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +description: "Contains a custom question, an answer given by the customer for the custom question and the properties of the custom question at the time of creation of the appointment."
For clarity, please add comma after "for the custom question". Suggested revision: 

- ...given by the customer for the custom question, and the properties of the...

Please, apply this change also to line 16.

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +|:---|:---|:---|
Please, add a period of the end of all descriptions in this table.

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +|answer|String|The answer given by the user in case the answerInputType is text |
Please, 

- apply bold formatting to "answerInputType" => \*\*answerInputType\*\*
- add backticks to text => \`text\`

Please, apply these change also to line 23.

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +|answerOptions|String collection|In case the answerInputType is dropdown, this will consists of a list of possible answer values |
Possible values for answerInputType are `text`, `radioButton`, `unknownFutureValue`. The answerInputType dropdown isn't mentioned there. In this case, should dropdown in this description be replaced with something else?

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +|isRequired|Boolean|If it is mandatory to answer the custom question |
For clarity, please rephrase. Suggested revision:

- Indicates whether it is mandatory to answer the custom question.

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionanswer.md
> +|questionId|String|The id of the custom question |
Please replace "id" with "ID".

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionassignment.md
> +|isRequired|Boolean|The id of the custom question |
Please,

- add a period at the end of the sentence
- replace "id" with "ID"

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingquestionassignment.md
> +|questionId|String|If it is mandatory to answer the custom question |
For clarity, please rephrase. Suggested revision:

- Indicates whether it is mandatory to answer the custom question.

2021-12-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/bookingservice.md
> +|customQuestions|[bookingQuestionAssignment](../resources/bookingquestionassignment.md) collection| Contains set of custom questions associated with a particular service. |
Please, add "the" before "set".

2021-12-14 22:55 UTC, opbld32 commented
Docs Build status updates of commit _[d2dea1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2dea1bbdddd1f072dcd21812badd0d590567f7d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-237df240)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-237df240)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-14 23:33 UTC, opbld33 commented
Docs Build status updates of commit _[4304a6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4304a6a7c07b9f062d10316c551e56ed4361d321)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-0b6e3749)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-0b6e3749)
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingcustomquestion-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2021-12-15 00:36 UTC, opbld34 commented
Docs Build status updates of commit _[a07c263](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a07c2638f78a56e624330abcd884cc0b39b97a9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-d355381f)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-d355381f)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 00:52 UTC, opbld34 commented
Docs Build status updates of commit _[34ebf7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34ebf7e6fc3ea81e2fdccdf63fff43b09ded0a50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-d774faca)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-d774faca)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 01:10 UTC, opbld30 commented
Docs Build status updates of commit _[978edf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/978edf1b755bb40a77cc4c295858cff6e5223bab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-380c9c76)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-380c9c76)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 04:59 UTC, razortbone commented on api-reference/beta/api/bookingappointment-update.md
> +|customerEmailAddress (deprecated)|String|Use the `customers` collection instead.|
Done

2021-12-15 04:59 UTC, razortbone commented on api-reference/beta/api/bookingappointment-update.md
> -The following example changes the date of service by a day, and updated the invoice date as well.
Done

2021-12-15 04:59 UTC, razortbone commented on api-reference/beta/api/bookingbusiness-list-customquestions.md
> +GET https://graph.microsoft.com/beta/bookingBusinesses/Contosolunchdelivery@M365B489948.onmicrosoft.com/customQuestions
DOne

2021-12-15 04:59 UTC, razortbone commented on api-reference/beta/api/bookingbusiness-list-customquestions.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Done

2021-12-15 04:59 UTC, razortbone commented on api-reference/beta/api/bookingbusiness-list-customquestions.md
> +      "displayName": "String",
Done

2021-12-15 05:08 UTC, razortbone commented on api-reference/beta/api/bookingbusiness-post-customquestions.md
> +In the request body, supply a JSON representation of the [bookingCustomQuestion](../resources/bookingcustomquestion.md) object.
Done

2021-12-15 05:08 UTC, razortbone commented on api-reference/beta/api/bookingbusiness-post-customquestions.md
> +| displayName     | String            | The question. Inherited from [bookingNamedEntity](../resources/bookingnamedentity.md). Required. |
Done

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/api/bookingbusiness-list-customquestions.md
> +  "@odata.type": "Collection(microsoft.graph.bookingCustomQuestion)"
Done

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/api/bookingcustomquestion-delete.md
> +description: "Deletes a bookingCustomQuestion object."
DOne

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/api/bookingcustomquestion-delete.md
> +> **Note:** The response object shown here might be shortened for readability.
Done

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/api/bookingcustomquestion-update.md
> +| displayName     | String            | The question. Inherited from [bookingNamedEntity](../resources/bookingnamedentity.md). Required. |
Done

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/api/bookingservice-update.md
> +|customQuestions|[bookingQuestionAssignment](../resources/bookingquestionassignment.md) collection|This contains set of custom questions associated with a particular service. Optional.|
DOne

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/resources/bookingappointment.md
> +|filledAttendeesCount|Int32|The current number of customers in the appointment |
Done

2021-12-15 05:09 UTC, razortbone commented on api-reference/beta/resources/bookingappointment.md
>  None
Done

2021-12-15 05:11 UTC, razortbone commented on api-reference/beta/resources/bookingcustomerinformation.md
> +|customQuestionAnswers|[bookingQuestionAnswer](../resources/bookingquestionanswer.md) collection|It consists of the list of custom questions and answers given by the customer as part of the appointme
DOne

2021-12-15 05:11 UTC, razortbone commented on api-reference/beta/resources/bookingcustomerinformation.md
> +|notes|String|Notes from the customer associated with this appointment. You can get the value only when reading this bookingAppointment by its ID. You can set this property only when initially creati
Done

2021-12-15 05:11 UTC, razortbone commented on api-reference/beta/resources/bookingcustomquestion.md
> +description: "Represents a custom question for a bookingBusiness"
Done

2021-12-15 05:11 UTC, razortbone commented on api-reference/beta/resources/bookingcustomquestion.md
> +| [Delete bookingCustomQuestion](../api/bookingcustomquestion-delete.md)         | None                                                                      | Deletes a [bookingCustomQuestion](../res
Done

2021-12-15 05:11 UTC, razortbone commented on api-reference/beta/resources/bookingcustomquestion.md
> +| answerInputType | answerInputType   | The expected answer type.The possible values are: `text`, `radioButton`, `unknownFutureValue`.     |
Done

2021-12-15 05:12 UTC, razortbone commented on api-reference/beta/resources/bookingnamedentity.md
> +description: "This is a base type for Microsoft Bookings entities that provide a display name, for example, bookingBusiness, bookingPerson, bookingService."
Done

2021-12-15 05:12 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +|answerInputType|answerInputType|The expected answer type.The possible values are: `text`, `radioButton`, `unknownFutureValue`.|
Done

2021-12-15 05:12 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +description: "Contains a custom question, an answer given by the customer for the custom question and the properties of the custom question at the time of creation of the appointment."
Done

2021-12-15 05:12 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +|:---|:---|:---|
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +|answer|String|The answer given by the user in case the answerInputType is text |
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +|answerOptions|String collection|In case the answerInputType is dropdown, this will consists of a list of possible answer values |
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +|isRequired|Boolean|If it is mandatory to answer the custom question |
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionanswer.md
> +|questionId|String|The id of the custom question |
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionassignment.md
> +description: "Contains set of custom questions associated with a particular service."
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionassignment.md
> +|isRequired|Boolean|The id of the custom question |
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingquestionassignment.md
> +|questionId|String|If it is mandatory to answer the custom question |
Done

2021-12-15 05:13 UTC, razortbone commented on api-reference/beta/resources/bookingservice.md
> +|customQuestions|[bookingQuestionAssignment](../resources/bookingquestionassignment.md) collection| Contains set of custom questions associated with a particular service. |
Done

2021-12-15 05:14 UTC, razortbone commented on api-reference/beta/resources/bookingworktimeslot.md
> +|end (deprecated)|TimeOfDay|Use `endTime` instead.|
Done

2021-12-15 11:36 UTC, opbld30 commented
Docs Build status updates of commit _[f5ea473](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5ea473017752bf2f392bef5e2cf91e94db3d5ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-2378ea71)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-2378ea71)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 13:06 UTC, opbld32 commented
Docs Build status updates of commit _[d5b8573](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5b857386cc67c64a4f28b1651347d6e4245f381)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-3d049fe9)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-3d049fe9)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 13:28 UTC, opbld34 commented
Docs Build status updates of commit _[9ee4f26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ee4f26196b908465868287f893dda2daba6d1d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-d36d6a0b)
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/resources/bookingcustomquestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-34fd6efb02497e67af3b4b7c26590dd6-d36d6a0b)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-d36d6a0b)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md)  [...]

2021-12-15 13:33 UTC, opbld33 commented
Docs Build status updates of commit _[ee773ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee773acf4b0ad7fd404eddc5c91ada5d99904572)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-171c96f1)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-171c96f1)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 13:36 UTC, opbld32 commented
Docs Build status updates of commit _[71634ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71634ee549b76465d05aecf743e9920cbf239700)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-b1468401)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-b1468401)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 14:04 UTC, isvargasmsft commented on api-reference/beta/resources/bookingappointment.md
>  |optOutOfCustomerEmail|Boolean|True indicates that the [bookingCustomer](bookingcustomer.md) for this appointment does not wish to receive a confirmation for this appointment.|
Missing property: onlineMeetingURL.

2021-12-15 14:08 UTC, isvargasmsft commented on api-reference/beta/resources/bookingappointment.md
>  |optOutOfCustomerEmail|Boolean|True indicates that the [bookingCustomer](bookingcustomer.md) for this appointment does not wish to receive a confirmation for this appointment.|
Also missing: startDateTime and endDateTime.

2021-12-15 14:32 UTC, opbld32 commented
Docs Build status updates of commit _[406f57d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/406f57dc1224f82c4e5d3ded88aab523d53ae0f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-e25f8c561ce16dfb6b0055b43d384dd5-17682265)
[api-reference/beta/api/meetingregistration-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/meetingregistration-list-customquestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/meetingregistration-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) | [Details](#user-content-a8555101724c93347b98040ff5b8bd8f-17682265)
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https:/ [...]

2021-12-15 14:40 UTC, isvargasmsft approved these changes

2021-12-15 15:31 UTC, opbld31 commented
Docs Build status updates of commit _[665919f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/665919fe4041ca7c454fc213e2f8a3f3f47bbd8f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-71616272)

<a id="71616272"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112151530586753-15164%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T15%3A31%3A21Z&sr=b&sp=r&sig=iqMzHOYMTJv3jI0RROWVha1sV3X8Yjkyz5nInBy3KJQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 15:37 UTC, opbld33 commented
Docs Build status updates of commit _[dd1cc29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd1cc29219506c1a77213234ac91c287082d98f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-publish?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/ [...]

2021-12-15 16:48 UTC, opbld30 commented
Docs Build status updates of commit _[01a96d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01a96d4e4c38ad41d780887c84d546c2ac9c63dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-customquestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-customquestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customquestions?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsbetaupdate/api-reference/beta/api/bookingbusiness-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-publish?view=graph-rest-beta&branch=pr-en-us-15164) (graph-rest-beta) |
[api-reference/ [...]

2021-12-15 16:51 UTC, merged