Adding a onBehalfOf property to chatMessageEntity
microsoftgraph/microsoft-graph-docs pull request #15186
Opened 2021-12-09 03:30 UTC by sumanac

2021-12-09 03:33 UTC, opbld32 commented
Docs Build status updates of commit _[afcbfcb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afcbfcbd2d8817e27bcee30990dba72734607333)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090330565446-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T03%3A33%3A08Z&sr=b&sp=r&sig=iyWOERNpsqX%2Bk4mlMuQSgX0WgLRb3cUo8YA0SmzZZ9A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-03 20:22 UTC, RamjotSingh commented
Update examples for chatMessage everywhere (channels and chats) to include the item as null. In channel examples, add one with the attribution in it as well

2022-01-03 20:22 UTC, RamjotSingh requested changes

2022-01-03 20:22 UTC, RamjotSingh commented on api-reference/beta/resources/chatmessage.md
> +|onBehalfOf|[chatMessageFromIdentitySet](chatmessagefromidentityset.md)| User attribution of the message when bot sends a messag on behalf of a user.|
message

Also add a link to the bot documentation. The link will be (might need a slash at start)

microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit#user-attribution-for-bots-messages

2022-01-03 20:22 UTC, RamjotSingh commented on api-reference/v1.0/resources/chatmessage.md
> +|onBehalfOf|[chatMessageFromIdentitySet](chatmessagefromidentityset.md)| User attribution of the message when bot sends a messag on behalf of a user.|
We arent releasing to v1 yet remove.

2022-01-03 21:01 UTC, sumanac commented on api-reference/v1.0/resources/chatmessage.md
> +|onBehalfOf|[chatMessageFromIdentitySet](chatmessagefromidentityset.md)| User attribution of the message when bot sends a messag on behalf of a user.|
removed

2022-01-03 21:02 UTC, opbld31 commented
Docs Build status updates of commit _[c433b12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c433b12ae7a24e6cc9b0417349b7149f2b174b5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201032100073604-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-03T21%3A02%3A17Z&sr=b&sp=r&sig=DHHRfQDukircirxC6eRq1D%2FVUR6B0GNxQcplInepWpw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-03 21:02 UTC, sumanac commented on api-reference/beta/resources/chatmessage.md
> +|onBehalfOf|[chatMessageFromIdentitySet](chatmessagefromidentityset.md)| User attribution of the message when bot sends a messag on behalf of a user.|
Updated

2022-01-04 20:25 UTC, opbld31 commented
Docs Build status updates of commit _[c5bb10e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5bb10ed1dcb1421420e43b0e3a2b7288decbb3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042018286489-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T20%3A25%3A40Z&sr=b&sp=r&sig=l6Eg9aP8dXQUU8rUFTMLGe8Hzfykfmdmujxj6Ek13fg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 21:57 UTC, Lauragra commented on api-reference/beta/resources/chatmessage.md
> +|onBehalfOf|[chatMessageFromIdentitySet](chatmessagefromidentityset.md)| User attribution of the message when [bot](/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-tas
This would be a good time to arrange the properties in the table in alphabetical order for easier scanning. Also, do you need to update any examples in API topics to show returning this property?

2022-01-04 21:59 UTC, opbld34 commented
Docs Build status updates of commit _[57ae84b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57ae84b0f2a78b91d747e2803090fe70b318118b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042158051617-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T21%3A59%3A53Z&sr=b&sp=r&sig=nZz%2BP1w1RU987zudYJIicLJD0XHDkNxa2mEzrZTRYkw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 17:10 UTC, opbld33 commented
Docs Build status updates of commit _[afe7823](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afe7823c3784650d6a0b65d4ce78b0cd84af2d25)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-04438412)
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/chat-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) | [Details](#user-content-1bd5f81a241c931f71ff5e76c235cb09-04438412)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmess [...]

2022-01-05 17:51 UTC, opbld33 commented
Docs Build status updates of commit _[eb4f420](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb4f4203ad746482e84cab8004bc2290fba2a263)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-15186) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/system-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-15186) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-15186) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-15186) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051748081460-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T17%3A51%3A00Z&sr=b&sp=r&sig=H%2Fa0sWCcm0060ulhUbfd%2FcFE%2B5brT3yjlQIZDWgcq3g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 18:07 UTC, sumanac commented
>

2022-01-05 18:13 UTC, opbld33 commented
Docs Build status updates of commit _[c4422cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4422cf01ca9fa8b8bb97363b500fcc8ab9da26e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/system-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-15186) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-15186) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-15186) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051811188767-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T18%3A13%3A04Z&sr=b&sp=r&sig=HgkBRwrgfjwVHArvTCBOK4rWVW3p%2B8N%2Bz5U11vlYYxw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 02:37 UTC, RamjotSingh approved these changes

2022-01-06 19:05 UTC, sumanac commented
@Lauragra - Could you please help merge this PR?

2022-01-06 23:15 UTC, Lauragra approved these changes

2022-01-07 00:38 UTC, opbld32 commented
Docs Build status updates of commit _[2bdb923](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bdb92325be9d4b9f6d2e490dfe83087169c1307)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/system-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-15186) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201070036342788-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T00%3A38%3A29Z&sr=b&sp=r&sig=gKe2fFgewy1KPAxhV36ynWBR68cJOTVtuYwzbjy3uo8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 00:48 UTC, opbld31 commented
Docs Build status updates of commit _[21696fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21696fddfd106e0570dbe215b1eea6a0e8c9e6b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-15186) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addonbehalfoftochatmessage/concepts/system-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-15186) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201070046110374-15186%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T00%3A48%3A06Z&sr=b&sp=r&sig=fkw3hjxfM6OZoIqBAbKElWWnF1TY2jtKBPxNn7%2Fiqds%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 01:14 UTC, merged