Expose contactedReviewers API in v1.0 and misc. updates
microsoftgraph/microsoft-graph-docs pull request #15239
Opened 2021-12-13 21:53 UTC by shubhamguptacal

2021-12-13 21:55 UTC, opbld33 commented
Docs Build status updates of commit _[61e0e2c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/61e0e2c3fbc6466dcce6eaa138322e8d5bb54fc2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-17731fee)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3effe2b1030d415f7e4eaf5798a5a534-17731fee)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="49b3d45645e9b2df44e5c28f034651f2-17731fee"></a>
### [api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

<a id="3effe2b1030d415f7e4eaf5798a5a534-17731fee"></a>
### [api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 19, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource resource type') are not allowed. You can only have one top-level heading.`````
 - **Line 27, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Properties''. Each second level heading (H2) in an article must be unique.`````
 - **Line 37, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 40, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'JSON representation''. Each second level heading (H2) in an article must be unique.`````
 - **Line 84, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Properties''. Each second level heading (H2) in an article must be unique.`````
 - **Line 96, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 102, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'JSON representation''. Each second level heading (H2) in an article must be unique.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112132153204838-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-13T21%3A55%3A22Z&sr=b&sp=r&sig=%2BFHCrvv%2FT%2F4wWNOXgfMeo%2FNuhwDM0qc24ZPGIWcURn0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) t [...]

2021-12-30 20:24 UTC, isabelleatmsft approved these changes

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +---
```suggestion
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResourc
```suggestion
| type | String | Type of resource. Type is always `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +|:---|:---|:---|
```suggestion

```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +``` json
```suggestion

```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +```
```suggestion
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md
> +| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResourc
```suggestion
| type | String | Type of resource. Type will always be `AzureRole`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```suggestion
| displayName | String | Display name of the access package. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md
> +| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```suggestion
| displayName | String | Display name of the Azure role. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +| displayName | String | Display name of the resource. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```suggestion
| displayName | String | Display name of the service principal. Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md).|
```

2021-12-30 20:24 UTC, isabelleatmsft commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +| type | String | Type of resource. Types include: `Group`, `ServicePrincipal`, `DirectoryRole`, `AzureRole`, `AccessPackageAssignmentPolicy`.  Inherited from [accessReviewInstanceDecisionItemResourc
```suggestion
| type | String | Type of resource. Type will always be:  `ServicePrincipal`.  Inherited from [accessReviewInstanceDecisionItemResource](accessreviewinstancedecisionItemresource.md). |
```

2021-12-30 20:25 UTC, opbld32 commented
Docs Build status updates of commit _[0741094](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/07410949767e9a34c2165fb8b125e9e20e8b260a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-60604d35)

<a id="60604d35"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302025319307-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T20%3A25%3A49Z&sr=b&sp=r&sig=4BcaET1U0Iqsc8KWfPtEN6AqRQSUoNbWgDR0kWujdII%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 15:40 UTC, opbld30 commented
Docs Build status updates of commit _[7fbc7df](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/7fbc7df92f982fab8fc4a5c2bd0d462c0c4afa71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-7bfe8580)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3effe2b1030d415f7e4eaf5798a5a534-7bfe8580)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="49b3d45645e9b2df44e5c28f034651f2-7bfe8580"></a>
### [api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

<a id="3effe2b1030d415f7e4eaf5798a5a534-7bfe8580"></a>
### [api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061538037665-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T15%3A40%3A09Z&sr=b&sp=r&sig=GVzYB8HARzo6E94OfWPGJp0nE27ki3HqdWlISXWPN4w%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 08:39 UTC, FaithOmbongi requested changes
Hi @isabelleatmsft, @shubhamguptacal—I've proposed a few changes, mostly to align these changes to decision items API with the changes you're making through [the PR that changes the beta docs](https://github.com/microsoftgraph/microsoft-graph-docs/pull/15036).

Also, please make the changes to the description of [accessReviewInstanceDecisionItemResource](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0). That's the cord that ties these 3 new resource files to existing files.

2022-01-10 08:39 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
> +---
Please sync the details in this file with the details in the beta file.

2022-01-10 08:39 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md
> +title: "accessReviewInstanceDecisionItemAzureRoleResource resource type"
Please sync the details in this file with the details in the beta file.

2022-01-10 08:39 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
> +---
Please sync the details in this file with the details in the beta file.

2022-01-10 08:39 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +        },
```suggestion
          "Description": "Added the [accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource?view=graph-rest-1.0) resource type. This resource represents an access package assignment policy to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-1.0) object.",
          "Target": "accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource"
        },
        {
          "Id": "b305ef66-8aaf-4a07-8b0e-7ccbdda4475f",
          "ApiChange": "Resource",
          "ChangedApiName": "accessReviewInstanceDecisionItemAzureRoleResource",
          "ChangeType": "Addition",
          "Description": "Added the [accessReviewInstanceDecisionItemAzureRoleResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemAzureRoleResource?view=graph-rest-1.0) resource type. This resource represents Azure resource roles to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-1.0) object.",
          "Target": "accessReviewInstanceDecisionItemAzureRoleResource"
        },
        {
          "Id": "b305ef66-8aaf-4a07-8b0e-7ccbdda4475f",
          "ApiChange": "Resource",
          "ChangedApiName": "accessReviewInstanceDecisionItemServicePrincipalResource",
          "ChangeType": "Addition",
          "Description": "Added the [accessReviewInstanceDecisionItemServicePrincipalResource](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItemServicePrincipalResource?view=graph-rest-1.0) resource type. This resource represents service principals to which access has been granted through an [accessReviewInstanceDecisionItem]((https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-1.0) object.",
          "Target": "accessReviewInstanceDecisionItemServicePrincipalResource"
        },
```

2022-01-10 08:39 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the **contactedReviewers** relationship to [accessReviewInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstance?view=graph-rest-1.0) resour
```suggestion
          "Description": "Added the **contactedReviewers** relationship to the [accessReviewInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstance?view=graph-rest-1.0) resource.",
```

2022-01-10 08:39 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [accessReviewReviewer](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewReviewer?view=graph-rest-1.0) resource",
```suggestion
          "Description": "Added the [accessReviewReviewer](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewReviewer?view=graph-rest-1.0) resource.",
```

2022-01-18 01:36 UTC, opbld33 commented
Docs Build status updates of commit _[a14bdef](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/a14bdefb38958e6ca0fe2b4f98100d6ee290cd5a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-7c31da5f)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3effe2b1030d415f7e4eaf5798a5a534-7c31da5f)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="49b3d45645e9b2df44e5c28f034651f2-7c31da5f"></a>
### [api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

<a id="3effe2b1030d415f7e4eaf5798a5a534-7c31da5f"></a>
### [api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180134336925-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T01%3A36%3A41Z&sr=b&sp=r&sig=tt%2Bvs5o75pTbzaDxCDUQeJYtuHGk01tYJtjYMdp77Oc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 07:33 UTC, opbld30 commented
Docs Build status updates of commit _[4c0da1b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4c0da1bf1670b6cb621f4042dfa00fcedb85b35b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-40f238d1)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3effe2b1030d415f7e4eaf5798a5a534-40f238d1)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="49b3d45645e9b2df44e5c28f034651f2-40f238d1"></a>
### [api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

<a id="3effe2b1030d415f7e4eaf5798a5a534-40f238d1"></a>
### [api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180730116632-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T07%3A33%3A07Z&sr=b&sp=r&sig=Ua3gDQXle6MUlevaQ7y78eX1ohZeVeL7eMmRHm6%2FGXY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:20 UTC, opbld33 commented
Docs Build status updates of commit _[846318d](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/846318d041f04e5d08eca3b9b48298845fa1db43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-c538cb4f)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3effe2b1030d415f7e4eaf5798a5a534-c538cb4f)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="49b3d45645e9b2df44e5c28f034651f2-c538cb4f"></a>
### [api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

<a id="3effe2b1030d415f7e4eaf5798a5a534-c538cb4f"></a>
### [api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191016468644-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A20%3A30Z&sr=b&sp=r&sig=C5cjtbXZa6rFIOfZ0xNZG94MWJovgdHEeTkXKUXKJwE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:22 UTC, opbld34 commented
Docs Build status updates of commit _[7cb76b6](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/7cb76b655ed9f2018b8d9182c35786746870fb02)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-f0a319a5)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3effe2b1030d415f7e4eaf5798a5a534-f0a319a5)
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="49b3d45645e9b2df44e5c28f034651f2-f0a319a5"></a>
### [api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

<a id="3effe2b1030d415f7e4eaf5798a5a534-f0a319a5"></a>
### [api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'accessReviewInstance resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/accessreviewinstance.md(2,8), v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents a recurrence of an `accessReviewScheduleDefinition`.' is duplicated in 'v1.0/resources/accessreviewinstance.md(3,14)', 'v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191020238975-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A22%3A36Z&sr=b&sp=r&sig=RuStTpReJWhCK9gJmjUk93hBDMkAOt0W7164FvhrrxI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:24 UTC, opbld33 commented
Docs Build status updates of commit _[5816d2f](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/5816d2f49a92788975dacb6b76c467ec273d118d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191021511152-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A24%3A54Z&sr=b&sp=r&sig=5C7BsaZqSi%2FttvXR8pOZXxiIk9ctFjntrgvU9AQKUUQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:27 UTC, opbld31 commented
Docs Build status updates of commit _[6e35777](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/6e35777021aecad9ca4e48ccb5df3c277dee0f99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191023051409-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A27%3A12Z&sr=b&sp=r&sig=%2BaPTzUh4X%2Bj42Gc3PVvGAr9H%2Ffx%2BUdI59yKLMm5Rsjg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:30 UTC, opbld33 commented
Docs Build status updates of commit _[8341258](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/83412588951cd725e1c821e64b4a55a7ac62039b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191028416879-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A30%3A51Z&sr=b&sp=r&sig=S61ptXGSKbYe6G37NFBdFa4vVECCzj5Xh7kIxCfh1Dg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:30 UTC, FaithOmbongi approved these changes
Hi @shubhamguptacal, @isabelleatmsft, pushed a few commits to sync the decisionItemResource inherited types to the changes in PR #15036. This PR is also good to go.

2022-01-19 10:32 UTC, opbld30 commented
Docs Build status updates of commit _[171b5f5](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/171b5f5d41deeea43863c012bd04e7308f2981a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191029217016-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A32%3A39Z&sr=b&sp=r&sig=5PYp%2F5BuUSZJEz3Za%2FeiIBsKetJPHB05Oa7noUGFLlE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 19:05 UTC, opbld33 commented
Docs Build status updates of commit _[863767b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/863767b97fbc9b73f67a4558c73bf1833735a5a0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-decisions - contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions%20-%20contactedreviewers.md) | :x:Error | | [Details](#user-content-bfcd395f6ae1f4cb7a3c09324d404c94-71d62c61)
[api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions.md) | :warning:Warning | | [Details](#user-content-8b7ab358db642df4f24ac9b54f72a222-71d62c61)

<a id="bfcd395f6ae1f4cb7a3c09324d404c94-71d62c61"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-decisions - contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions%20-%20contactedreviewers.md)
 - **Line 66, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-accessReviewReviewer-csharp-snippets.md'.`````
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-accessReviewReviewer-javascript-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-accessReviewReviewer-objc-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-accessReviewReviewer-java-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-accessReviewReviewer-go-snippets.md'.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List decisions' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-decisions - contactedreviewers.md(10,1), v1.0/api/accessreviewinstance-list-decisions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="8b7ab358db642df4f24ac9b54f72a222-71d62c61"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List decisions' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-decisions - contactedreviewers.md(10,1), v1.0/api/accessreviewinstance-list-decisions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191903470369-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T19%3A05%3A42Z&sr=b&sp=r&sig=yp5lnbBE%2FxOGDPds2%2Bw2z159%2BaF41GcLcSIaE21OsIg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 19:08 UTC, opbld30 commented
Docs Build status updates of commit _[8c23ed9](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/8c23ed9870db25a8115d961f1b41b6056fa6fad1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md) | :x:Error | | [Details](#user-content-3003063b96c6268eb2af92033b2681d9-451b5ea0)
[api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions.md) | :warning:Warning | | [Details](#user-content-8b7ab358db642df4f24ac9b54f72a222-451b5ea0)

<a id="3003063b96c6268eb2af92033b2681d9-451b5ea0"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md)
 - **Line 66, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-accessReviewReviewer-csharp-snippets.md'.`````
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-accessReviewReviewer-javascript-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-accessReviewReviewer-objc-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-accessReviewReviewer-java-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-accessReviewReviewer-go-snippets.md'.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List decisions' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-contactedreviewers.md(10,1), v1.0/api/accessreviewinstance-list-decisions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="8b7ab358db642df4f24ac9b54f72a222-451b5ea0"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List decisions' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-contactedreviewers.md(10,1), v1.0/api/accessreviewinstance-list-decisions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191904394281-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T19%3A08%3A21Z&sr=b&sp=r&sig=21CIyRUAl3tFYyvj3e5dZ5K8goejVBcnSwMhI9rbNWk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 08:18 UTC, opbld30 commented
Docs Build status updates of commit _[8e89d10](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/8e89d10b599b124429b4fd138694a9c6dc29304e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b44b7cd)

<a id="7b44b7cd"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200818026127-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T08%3A18%3A37Z&sr=b&sp=r&sig=89KcmTq1hgLxlQ0BR1UXbejAdJ62goQHEu4sopM43%2FY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 08:23 UTC, opbld32 commented
Docs Build status updates of commit _[959b6c7](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/959b6c717be5d1e4eb1b6bb614ff2e035354cf0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-3003063b96c6268eb2af92033b2681d9-0ecfeb65)
[api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) | [Details](#user-content-8b7ab358db642df4f24ac9b54f72a222-0ecfeb65)
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="3003063b96c6268eb2af92033b2681d9-0ecfeb65"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List decisions' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-contactedreviewers.md(10,1), v1.0/api/accessreviewinstance-list-decisions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="8b7ab358db642df4f24ac9b54f72a222-0ecfeb65"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-decisions.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List decisions' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-contactedreviewers.md(10,1), v1.0/api/accessreviewinstance-list-decisions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200820388202-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T08%3A23%3A06Z&sr=b&sp=r&sig=cwBW5cTJdJJ3oFbUuMoGOTTEKQh%2F8bICwFFM9SZrpPM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 08:30 UTC, opbld33 commented
Docs Build status updates of commit _[8e522d2](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/8e522d25b4632ec90fdf189f332c3bdd9b3cad0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200828115074-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T08%3A30%3A48Z&sr=b&sp=r&sig=ZD%2FcLFXPB44U%2FqojXyjEiu%2FQThGVMiRlxPXZd6knK4o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 09:04 UTC, opbld33 commented
Docs Build status updates of commit _[e83588c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/e83588cb4b6871b1dc48da989386dff07dad4b7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200901445307-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T09%3A04%3A16Z&sr=b&sp=r&sig=HhcTougbCjrDhC21urQmSw269PlEsEOWFqqEnzendoE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 09:08 UTC, opbld34 commented
Docs Build status updates of commit _[66d0ea2](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/66d0ea29cca017bc0f8a396dbeb2275419dc83ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200906411240-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T09%3A08%3A51Z&sr=b&sp=r&sig=%2FrwEJNl1aHjWBOfzNNS0socNji7sJJp6F6A6tlJ0%2Bcc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 09:17 UTC, opbld34 commented
Docs Build status updates of commit _[add9f69](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/add9f69f4c264f183cd822fc73608fb744a7b68c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemazureroleresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipalresource?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-contactedreviewers?view=graph-rest-1.0&branch=pr-en-us-15239) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-contactedreviewers/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200915030322-15239%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T09%3A17%3A10Z&sr=b&sp=r&sig=5Cqk%2FhengYxDkMdNXiro%2FZTouylCBGwtSkV0zIOH2Kk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 01:42 UTC, merged