Adding teams/getAllMembers subscription resource
microsoftgraph/microsoft-graph-docs pull request #15254
Opened 2021-12-15 00:08 UTC by prshinde-msft

2021-12-15 00:10 UTC, opbld33 commented
Docs Build status updates of commit _[ef8d4d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef8d4d8bb15d688a5aaf9585768acb7e261830bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112150008116023-15254%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T00%3A10%3A08Z&sr=b&sp=r&sig=lzlMr%2FUvRrUz%2FBhXQ0zquj2SGF9ruuoFq3iIwS4bH1s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 01:57 UTC, nkramer requested changes

2021-12-15 01:57 UTC, nkramer commented on api-reference/beta/api/subscription-delete.md
>  |[conversationMember](../resources/conversationmember.md) (/teams/{id}/channels/getAllMembers) | Not supported | Not supported | ChannelMember.Read.All |
The order of the various conversationMember rows is kinda random -- first a team membership API, then a couple chat membership APIs, then a couple more team membership APIs.

2021-12-15 01:57 UTC, nkramer commented on api-reference/beta/api/subscription-update.md
> +|[conversationMember](../resources/conversationmember.md) (/teams/getAllMembers) | Not supported | Not supported | TeamMember.Read.All, TeamMember.ReadWrite.All |
We also need to add this API to the Notes section where we talk about modernization requirements for certain kinds of subscriptions.

Oddly, we don't need to change the monetization page https://docs.microsoft.com/en-us/graph/teams-licenses because we talk about conversationMember in general terms.

2021-12-15 02:00 UTC, prshinde-msft commented on api-reference/beta/api/subscription-update.md
> +|[conversationMember](../resources/conversationmember.md) (/teams/getAllMembers) | Not supported | Not supported | TeamMember.Read.All, TeamMember.ReadWrite.All |
@nkramer are you referring to this notes section? It already covers teams/getAllMembers
![image](https://user-images.githubusercontent.com/81260346/146109194-44aa3d7c-31f7-45ae-aa7d-bd9206c5e4fa.png)

2021-12-15 02:31 UTC, opbld32 commented
Docs Build status updates of commit _[b22da4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b22da4f62c83f98dca79aadb0679c26537a713ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112150229540965-15254%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T02%3A31%3A29Z&sr=b&sp=r&sig=8nRlsBGKxAJwaDELnKtHvt8sEsBYVjVyCU6KIWOA52A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 02:35 UTC, prshinde-msft commented on api-reference/beta/api/subscription-delete.md
>  |[conversationMember](../resources/conversationmember.md) (/teams/{id}/channels/getAllMembers) | Not supported | Not supported | ChannelMember.Read.All |
Reordered. Now it's all chat membership APIs and then all team membership APIs.

2021-12-15 02:36 UTC, prshinde-msft commented on api-reference/beta/api/subscription-update.md
> +|[conversationMember](../resources/conversationmember.md) (/teams/getAllMembers) | Not supported | Not supported | TeamMember.Read.All, TeamMember.ReadWrite.All |
Confirmed offline that this is already covered.

2021-12-15 02:36 UTC, opbld34 commented
Docs Build status updates of commit _[ad413df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad413df7bedf38df87151a8997a9135cbd7e91ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/prshinde-adding-new-ChangeNotification-resource/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15254) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112150234185080-15254%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T02%3A36%3A33Z&sr=b&sp=r&sig=JsDuKlIdUWqQPC%2BO2bXSSVi3Y46QKSoGkFMiUOTd7Dw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 17:38 UTC, nkramer approved these changes

2021-12-15 17:50 UTC, hikum approved these changes

2022-01-05 19:40 UTC, isvargasmsft approved these changes

2022-01-06 02:34 UTC, merged