Clarifying how far back lastsignindatetime goes
microsoftgraph/microsoft-graph-docs pull request #15289
Opened 2021-12-17 21:04 UTC by besiler

2021-12-17 21:06 UTC, opbld31 commented
Docs Build status updates of commit _[b4a2797](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4a279711cda66264561b9e976f394fca8724d43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/besiler-patch-2/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-15289) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112172104467095-15289%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T21%3A06%3A45Z&sr=b&sp=r&sig=fNuD5lJ6SLH9ky2mQCzNfePo69VuwTOPgwWXltbflqQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-20 19:15 UTC, FaithOmbongi reviewed
Thank you @besiler for raising this PR. 

A point of confusion though: doesn't the note contradict the messaging we give about sign-in logs being governed by [Azure AD retention policies](https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-reports-data-retention#how-long-does-azure-ad-store-the-data)?

2021-12-20 20:55 UTC, besiler commented
@FaithOmbongi we think of signinactivity as being a property of the user object rather than activity data, since it's a stable piece of info that is only updated periodically rather than a report of all activities that happened in the last 30 days. 

However, if you're raising this point we'll definitely have customers who make the same point. What if we added this disclaimer in the description signinactivity.md: "signinactivity is a resource that describes a property of the user object in your tenant. Azure AD stores signinactivity for your users for as long as the user objects exist."?

2021-12-21 09:01 UTC, FaithOmbongi requested changes
Thank you @besiler for raising this PR. Looks good but for 2 gaps:
- Please document the 2 new members in tokenIssuerType enum
- Document the changelog

I also support your suggestion to enhance the resource description. Go for it.

2021-12-21 18:20 UTC, besiler commented on api-reference/beta/resources/signinactivity.md
> +|lastNonInteractiveSignInDateTime|DateTimeOffset|The last non-interactive sign-in date for a specific user. You can use this field to calculate the last time a client signed in to the directory on be
Yep, that should be non-interactive

2021-12-21 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[c2cc2cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2cc2cf59e950d5a8efeb9f68ddd17fd650fe157)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/besiler-patch-2/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-15289) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112211821024528-15289%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T18%3A23%3A31Z&sr=b&sp=r&sig=1SHqy4BL9EQiABUuMjzwd%2FzGm7BQt5LmcAjo%2FfcuR6E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 18:29 UTC, opbld33 commented
Docs Build status updates of commit _[8e19079](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e19079ccaf8841473036b8368a97f371a861879)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/besiler-patch-2/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-15289) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112211825583634-15289%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T18%3A29%3A06Z&sr=b&sp=r&sig=z0ize2l3dXEVlxsMUMLh7VfVqO0CeLNrYh2TynnsENg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 18:33 UTC, FaithOmbongi approved these changes

2021-12-22 01:10 UTC, besiler commented
Marking ready to merge since @FaithOmbongi approved

2021-12-23 21:02 UTC, merged