Updates for Azure AD reporting Q2 FY22
microsoftgraph/microsoft-graph-docs pull request #15284
Opened 2021-12-17 01:48 UTC by besiler

Added

- AuthenticationContext resource
- AuthenticationContextDetail enums
- New tokenIssuerType enums
- AzureResourceId property
- federatedCredentialId property
- resourceServicePrincipalId property
- sessionLifetimePolicies resource

2021-12-17 01:48 UTC, opbld30 commented
Docs Build status updates of commit _[b7a6579](https://github.com/besiler/microsoft-graph-docs/commits/b7a657903d0f32ef87c8f580b375d2df0fe4ca3b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f19d8da6)

<a id="f19d8da6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112170148322530-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T01%3A48%3A57Z&sr=b&sp=r&sig=7uDhxKQPI0t6AfqLNmxEQoX2IiMl%2FWnKV%2FcpsIkMTlk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 01:52 UTC, opbld30 commented
Docs Build status updates of commit _[b7a6579](https://github.com/besiler/microsoft-graph-docs/commits/b7a657903d0f32ef87c8f580b375d2df0fe4ca3b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e6984da1)

<a id="e6984da1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112170152252922-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T01%3A52%3A46Z&sr=b&sp=r&sig=tjZ6S9MvglHnkq%2F6ku3bELlpzVVi8axpFrKhNOrFx90%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 05:42 UTC, opbld32 commented
Docs Build status updates of commit _[ea22fe2](https://github.com/besiler/microsoft-graph-docs/commits/ea22fe2b05c0ae28e85f911b1fb0e84215c6facf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112170540295185-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T05%3A42%3A58Z&sr=b&sp=r&sig=bFfdnjCmAs12ZZW9H9X21LHW97Ck3x98A7xbnIpImrc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 05:56 UTC, opbld32 commented
Docs Build status updates of commit _[913a168](https://github.com/besiler/microsoft-graph-docs/commits/913a1686a1fabbc55638238f7bdee8d38ed2f32a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112170555213391-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T05%3A56%3A57Z&sr=b&sp=r&sig=7uARp5%2B8yDj%2BaoGULqtoNAK4L02XUEAE8ctb5ygpRSc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 06:03 UTC, opbld32 commented
Docs Build status updates of commit _[8bace04](https://github.com/besiler/microsoft-graph-docs/commits/8bace040ed42723234f7e475d5febe463046d3d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112170601419887-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T06%3A03%3A27Z&sr=b&sp=r&sig=%2FlJ8RWCjswChKX1toupRrjBb6FzR%2BpEZNECt7wj2UT4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 06:09 UTC, besiler commented
@FaithOmbongi just FYI, the auth methods docs that are also part of this quarter's schema change are covered here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15181

2021-12-21 08:46 UTC, FaithOmbongi requested changes
Thank you @besiler for raising this PR. Looks good but for two minor gaps:
- Also document the 2 new members in **tokenIssuerType** enum
- Add the changelog

then the PR will be good to publish.

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|authenticationContextClassReferences|[authenticationContext](../resources/authenticationcontext.md) collection|Contains a collection of values that represent the conditional access authentication co
Just confirm the description. The 2nd sentence is incomplete.
```suggestion
|authenticationContextClassReferences|[authenticationContext](authenticationcontext.md) collection|Contains a collection of values that represent the conditional access authentication contexts applied to the sign-in. A user may satisfy the authentication context by providing a s|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|azureResourceId|String|Contains fully qualified Azure Resource Manager ID of an Azure resource accessed as a target of the sign in when an Azure resource was accessed.|
```suggestion
|azureResourceId|String|Contains a fully qualified Azure Resource Manager ID of an Azure resource accessed during the sign-in.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|federatedCredentialId|String|Contains the identifier of an application's federated identity credential if a federated identity credential was used to sign in.|
```suggestion
|federatedCredentialId|String|Contains the identifier of an application's federated identity credential, if a federated identity credential was used to sign in.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|sessionLifetimePolicies|[sessionLifetimePolicy](../resources/sessionlifetimepolicy.md) collection|Any conditional access session management policies that were applied during the sign-in event.|
```suggestion
|sessionLifetimePolicies|[sessionLifetimePolicy](sessionlifetimepolicy.md) collection|Any conditional access session management policies that were applied during the sign-in event.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|tokenIssuerType|tokenIssuerType|The type of identity provider. The possible values are: `AzureAD`, `ADFederationServices`, `UnknownFutureValue`, `AzureADBackupAuth`, `ADFederationServicesMFAAdapter`
Resolving a docs generation error
```suggestion
|tokenIssuerType|tokenIssuerType|The type of identity provider. The possible values are: `AzureAD`, `ADFederationServices`, `UnknownFutureValue`, `AzureADBackupAuth`, `ADFederationServicesMFAAdapter`, `NPSExtension`. Note that you must use the `Prefer: include - unknown -enum-members` request header to get the following value(s) in this [evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations): `AzureADBackupAuth` , `ADFederationServicesMFAAdapter` , `NPSExtension`.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|tokenIssuerType|tokenIssuerType|The type of identity provider. The possible values are: `AzureAD`, `ADFederationServices`, `UnknownFutureValue`, `AzureADBackupAuth`, `ADFederationServicesMFAAdapter`
Resolving a docs generation error
```suggestion
|tokenIssuerType|tokenIssuerType|The type of identity provider. The possible values are: `AzureAD`, `ADFederationServices`, `UnknownFutureValue`, `AzureADBackupAuth`, `ADFederationServicesMFAAdapter`, `NPSExtension`. Note that you must use the `Prefer: include-unknown-enum-members` request header to get the following values in this [evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations): `AzureADBackupAuth` , `ADFederationServicesMFAAdapter` , `NPSExtension`.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationcontext.md
> +|detail|authenticationContextDetail|Describes how the conditional access authentication context was triggered. A value of `previouslySatisfied` means the authcontext was because the user already sati
```suggestion
|detail|authenticationContextDetail|Describes how the conditional access authentication context was triggered. A value of `previouslySatisfied` means the auth context was because the user already satisfied the requirements for that authentication context in some previous authentication event. A value of `required` means the user had to meet the authentication context requirement as part of the sign-in flow. The possible values are: `required`, `previouslySatisfied`, `notApplicable`, `unknownFutureValue`.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationcontext.md
> +|detail|authenticationContextDetail|Describes how the conditional access authentication context was triggered. A value of `previouslySatisfied` means the authcontext was because the user already sati
```suggestion
|detail|authenticationContextDetail|Describes how the conditional access authentication context was triggered. A value of `previouslySatisfied` means the auth context was because the user already satisfied the requirements for that authentication context in some previous authentication event. A value of `required` means the user had to meet the authentication context requirement as part of the sign-in flow. The possible values are: `required`, `previouslySatisfied`, `notApplicable`, `unknownFutureValue`.|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationcontext.md
> +description: "Provides information about the authenticationContext resource type"
```suggestion
description: "Describes the conditional access authentication context of a sign-in event."
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/sessionlifetimepolicy.md
> +description: "Provides information about the sessionlifetimepolicy resource type"
```suggestion
description: "Describes the session lifetime policies Azure AD applied to a sign-in event."
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +|NPSExtension|
Adding the missing member
```suggestion
|unknownFutureValue|
|AzureADBackupAuth|
|ADFederationServicesMFAAdapter|
|NPSExtension|
```

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/api/signin-list.md
> +      "federatedCredentialId": "729ab02a-edd5-4ef5-a285-2d91a3c772ab",
I'm not knowledgeable about Azure Resource Manager but, just confirm if you can have both azureResourceId and federatedCredentialId.

2021-12-21 08:46 UTC, FaithOmbongi commented on api-reference/beta/api/signin-get.md
> +  "federatedCredentialId": "729ab02a-edd5-4ef5-a285-2d91a3c772ab",
Same comment as in the List operation.

2021-12-21 17:11 UTC, besiler commented on api-reference/beta/api/signin-list.md
> +      "federatedCredentialId": "729ab02a-edd5-4ef5-a285-2d91a3c772ab",
I would think so - I'll double check with Abbe

2021-12-21 17:15 UTC, opbld32 commented
Docs Build status updates of commit _[b4367d5](https://github.com/besiler/microsoft-graph-docs/commits/b4367d5332b388222bbf57fa66bce9e06edd675c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112211714040419-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T17%3A15%3A54Z&sr=b&sp=r&sig=yOc%2FbPcw%2FrTVyxZFy3N51dGaSpipwpbiERGrlN2aq3g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 17:23 UTC, besiler commented on api-reference/beta/resources/signin.md
> +|authenticationContextClassReferences|[authenticationContext](../resources/authenticationcontext.md) collection|Contains a collection of values that represent the conditional access authentication co
Deleted that unfinished sentence since the info is in the authenticationcontext resource linked in that field

2021-12-21 17:32 UTC, besiler commented on api-reference/beta/api/signin-list.md
> +      "federatedCredentialId": "729ab02a-edd5-4ef5-a285-2d91a3c772ab",
> Thank you @besiler for raising this PR. Looks good but for two minor gaps:
> 
> * Also document the 2 new members in **tokenIssuerType** enum
> * Add the changelog
> 
> then the PR will be good to publish.

Thanks for the review! Which members are missing from tokenIssuerType? We have these enums in the csdl, and it looks like signins.md and enums.md are both up to date with the same values

![image](https://user-images.githubusercontent.com/69605773/146973438-39dc03a2-3167-4b17-a314-9d5bb9eecf12.png)

2021-12-21 17:40 UTC, besiler commented on api-reference/beta/api/signin-list.md
> +      "federatedCredentialId": "729ab02a-edd5-4ef5-a285-2d91a3c772ab",
Confirmed that we can have both azureResourceId and federatedCredentialId in one sign-in event

2021-12-21 17:55 UTC, FaithOmbongi commented on api-reference/beta/api/signin-list.md
> +      "federatedCredentialId": "729ab02a-edd5-4ef5-a285-2d91a3c772ab",
Confirmed this was a mix-up in the schema update PR.

2021-12-21 18:02 UTC, opbld34 commented
Docs Build status updates of commit _[831693c](https://github.com/besiler/microsoft-graph-docs/commits/831693cc188f99f1d2991d0d2a61e238c17f5895)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112211759211006-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T18%3A02%3A54Z&sr=b&sp=r&sig=XHciheQlLY2k3sAdB92bxW0TOBQmQMxbeVkyPeCTkEg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 19:37 UTC, opbld33 commented
Docs Build status updates of commit _[a72bf35](https://github.com/besiler/microsoft-graph-docs/commits/a72bf35a65b6e3b8e6c7db9eca49632d9a1dcc93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112281935346955-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T19%3A37%3A35Z&sr=b&sp=r&sig=Nsu%2F%2FJpw6iaDRMT5w4SRmXScLniQ%2BleFTNyrzt0C8Ls%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 19:41 UTC, FaithOmbongi approved these changes
Hi @besiler, LGTM! Approved but pushed a minor change to avoid duplication.

2021-12-29 08:08 UTC, opbld34 commented
Docs Build status updates of commit _[31c7594](https://github.com/besiler/microsoft-graph-docs/commits/31c75941cad0ec7e88faa4e00aa0f5758d5ec297)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-282d61cb)

<a id="282d61cb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112290808074031-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-29T08%3A08%3A35Z&sr=b&sp=r&sig=ozNLmo%2BW4VOuSGZN57fbQZi7FMbT7LPXMoWCdVnKuqo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 07:22 UTC, opbld30 commented
Docs Build status updates of commit _[4e3ca74](https://github.com/besiler/microsoft-graph-docs/commits/4e3ca74bbc752fa316f9fb87c464c64c59836c70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112300720443637-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T07%3A22%3A33Z&sr=b&sp=r&sig=vjjNRYpRcsJf0nMVNxVl9%2Bco8Q%2FeO2Vr1HM3Az10S4A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 16:54 UTC, FaithOmbongi commented
Heads up, @besiler. I see the changes in this PR are now in the public schema. I'm setting this PR to ready to merge. If there's any reason we should hold it back from publishing, please feel free to replace the **ready to merge** label with the **do not merge** label.

2022-01-19 16:54 UTC, opbld33 commented
Docs Build status updates of commit _[226f12b](https://github.com/besiler/microsoft-graph-docs/commits/226f12b6a8055bcfbaf6a8b11cdb646cdde1e37f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191652357159-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T16%3A54%3A55Z&sr=b&sp=r&sig=XGXGFFuQqSg%2FqjnKMCHzebHTcSghNSgfmLVKsDb5lx0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 17:04 UTC, opbld31 commented
Docs Build status updates of commit _[9ea5e8a](https://github.com/besiler/microsoft-graph-docs/commits/9ea5e8a2f8d427d9bc00cc29d9cee2b822c3d402)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191702073562-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T17%3A04%3A28Z&sr=b&sp=r&sig=kQXuzyjVWCkJW5n14yRb49Hu9ak22VmV1tWMNivqD8c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 06:01 UTC, opbld32 commented
Docs Build status updates of commit _[98f38c1](https://github.com/besiler/microsoft-graph-docs/commits/98f38c12f935a8a98637dd36878353621173f4a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200558229717-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T06%3A01%3A07Z&sr=b&sp=r&sig=5gQ7Dirv4X%2BRo3gpxSZNlNgdmjaa6%2Baglj7LMPPf4nU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 06:04 UTC, opbld31 commented
Docs Build status updates of commit _[aa12817](https://github.com/besiler/microsoft-graph-docs/commits/aa128177745e57d54e7efb2dc844affab39d3571)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcontext.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/authenticationcontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontext?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/sessionlifetimepolicy.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/sessionlifetimepolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sessionlifetimepolicy?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-15284) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/besiler/microsoft-graph-docs/blob/AADReportingDocsQ2_2022/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200601345378-15284%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T06%3A04%3A12Z&sr=b&sp=r&sig=uIq%2Fb77B1R50ZhwcUSweCpp2EoxXg0lWQHb5EaLZbOY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 06:08 UTC, merged