Update externalconnectors-externalitem-create.md
microsoftgraph/microsoft-graph-docs pull request #15299
Opened 2021-12-20 18:13 UTC by Arvind-Ravi

Fix for Missmatch between the request documentation and the http example #15125. 

The HTTP Request section was incorrect. It was defined as a POST but the method supported is actually PUT.

2021-12-20 18:15 UTC, opbld31 commented
Docs Build status updates of commit _[1877005](https://github.com/Arvind-Ravi/microsoft-graph-docs/commits/1877005f114c97376efdaa3ae74d4450b582d694)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalitem-create.md](https://github.com/Arvind-Ravi/microsoft-graph-docs/blob/main/api-reference/v1.0/api/externalconnectors-externalitem-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-create?view=graph-rest-1.0&branch=pr-en-us-15299) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112201813383149-15299%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-20T18%3A15%3A33Z&sr=b&sp=r&sig=kDpvxxlIyORKaGQ2nYjhuOw2fkQ6Ackl604N5h%2F30hI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-20 18:21 UTC, Arvind-Ravi commented
@mecampos - Acking you explicitly here. The "Reviewers" section on top doesn't permit me to add any reviewers to this PR.

2021-12-20 18:30 UTC, mecampos commented
12/20/2021: Reviewed doc and agreed updates. PR ready for content review.

2022-01-05 20:03 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalitem-create.md
> +PUT /external/connections/{connection-id}/items/{item-id}
This method is to create a brand new item, so why are we adding an {item-ID} in the HTTP request? Shouldn't that be specified in the request body?

2022-01-05 20:03 UTC, isvargasmsft commented
https://github.com/microsoftgraph/microsoft-graph-docs/issues/15125

2022-01-05 20:05 UTC, isvargasmsft requested changes
Please clarify the reason to add /{itemID} to the HTTP request.

2022-01-05 20:23 UTC, isvargasmsft approved these changes
Thank you for the clarification on the side.

2022-01-05 20:30 UTC, Arvind-Ravi commented
Thanks so much @mecampos for adding the labels!

2022-01-06 02:36 UTC, merged