Update Speller Doc For Graph Search API
microsoftgraph/microsoft-graph-docs pull request #15325
Opened 2021-12-22 13:04 UTC by ZChristine

2021-12-22 13:05 UTC, opbld31 commented
Docs Build status updates of commit _[5c23917](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c239177af1bd1570c78ca465ff2539d4b29990e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-5384b5e3)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

<a id="464f6e6261c8b38a41277608d7460584-5384b5e3"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112221304079910-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-22T13%3A05%3A53Z&sr=b&sp=r&sig=cXcfSMD%2FEsEhTx7aLRZvkoKg%2B%2BytY1GA5xM%2BwYNiXdA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 13:58 UTC, isvargasmsft commented on api-reference/beta/api/search-query.md
> +If successful, this method returns a `HTTP 200 OK` response code and a [searchResponse](../resources/searchresponse.md) collection object in the response body.
Please rephrase to "and a collection of searchResponse objects in the response body.

2022-01-11 14:03 UTC, isvargasmsft commented on api-reference/beta/resources/searchresponse.md
> +Represents results from a search query, and the terms used for the query.
Lines 3 and 16: These descriptions should match. Please copy the description in line 3 as well.

2022-01-11 16:21 UTC, opbld34 commented
Docs Build status updates of commit _[2873001](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28730010587dc4867a6a3cceafc8d196f1d15708)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-b1df6b21)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

<a id="464f6e6261c8b38a41277608d7460584-b1df6b21"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201111619194991-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T16%3A21%3A28Z&sr=b&sp=r&sig=I%2FlLYnmb9EWo4oJ%2F37fN6ayPjyXKy3w0EVAAXmq%2Fc3g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 19:47 UTC, opbld31 commented
Docs Build status updates of commit _[e274614](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e274614a448ed730d0256283318f1b036146f66b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201241943363709-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T19%3A47%3A39Z&sr=b&sp=r&sig=wz%2FG6z%2BfIqKZot0yVFhVfhVZ3mTGL%2BE6MutKy38tMY0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 20:19 UTC, isvargasmsft commented on changelog/Microsoft.MicrosoftSearch.json
> +        }
Please explain this changes: it seems we are adding and removing the same method.

2022-01-25 16:14 UTC, isvargasmsft requested changes
Please clarify the changes to the query method.

2022-01-25 23:29 UTC, ZChristine commented on changelog/Microsoft.MicrosoftSearch.json
> +        }
this changes were auto generated in https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/5503545?path=/Schemas/beta-Prod.csdl&_a=files when i update the CSDL in our API. It might mean that the change to the query method. see https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/5503545?path=/Schemas/beta-Prod.csdl&_a=files

2022-01-28 00:08 UTC, opbld34 commented
Docs Build status updates of commit _[302bc62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/302bc62547745f70ccd3d266c8d25207de5f0b7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201280006354296-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T00%3A08%3A43Z&sr=b&sp=r&sig=P6wFlME3j87ppkN9Z7qzWoO9i%2BE33rqXO%2BsVPs%2Fc7SE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 00:09 UTC, isvargasmsft approved these changes

2022-01-29 02:01 UTC, opbld34 commented
Docs Build status updates of commit _[78374d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78374d2e54eb672adecc209e64bb1a0d72c0a272)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290158517653-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T02%3A01%3A40Z&sr=b&sp=r&sig=7nF8gtX8%2F8LheImNIo7hQy9yWxPOVvVd6p2FL26rTRo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 02:08 UTC, opbld33 commented
Docs Build status updates of commit _[1995e2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1995e2b8defe6391d2b78ffd241459c47058b444)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290206313121-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T02%3A08%3A54Z&sr=b&sp=r&sig=g3IHNX%2FRqCYGCmqUW8HjP%2F5UDv87Ustl3WW5Yy51%2BQA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 02:22 UTC, opbld30 commented
Docs Build status updates of commit _[311d62d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/311d62d901a2dd060e3c6f0c4e53d41c29b3df53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290220220653-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T02%3A22%3A34Z&sr=b&sp=r&sig=jSEU2Y0Mrcup8wz4Ir0sqZ8QpVj0YUoTL2vDAAyFr54%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 02:30 UTC, opbld31 commented
Docs Build status updates of commit _[4440d70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4440d701102dc906c46124433ca6c8d92b03006c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290228092450-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T02%3A30%3A17Z&sr=b&sp=r&sig=QGQy%2FExxyh4ZnK4mlGZOgCLkjObLyBk7uDFkaU53tcQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 02:34 UTC, opbld34 commented
Docs Build status updates of commit _[459d451](https://github.com/microsoftgraph/microsoft-graph-docs/commits/459d4514523a405db973b5b307b7af3c2431f1a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-beta&branch=pr-en-us-15325) (graph-rest-beta) |
[api-reference/beta/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/api-reference/beta/resources/searchresultset.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-speller.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/spellerRevision/concepts/search-concept-speller.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-speller?branch=pr-en-us-15325) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290232246324-15325%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T02%3A34%3A39Z&sr=b&sp=r&sig=cKcxAiY2auU3V7yuSMrh4g4%2FX7R99ag7ckhARMCPLwQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 02:37 UTC, merged