Add Transcript APIs and Resources.
microsoftgraph/microsoft-graph-docs pull request #15348
Opened 2021-12-27 08:58 UTC by mankadnandan

2021-12-27 19:50 UTC, opbld34 commented
Docs Build status updates of commit _[c14c215](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c14c215b570afb3d0076430ce9cca0f859544b89)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2853b9b1)
[]() | :x:Error | | [Details](#user-content-2853b9b1)

<a id="2853b9b1"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````
 - **[Warning: InvalidJsonLogLine]** 
`````
The log line content '{"message' can't be converted to log item. Details: System.ArgumentException: Invalid json string ---> Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '', line 1, position 9.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.OpenPublishing.Build.Common.JsonUtility.FromJsonString[T](String value) in C:\__w\1\s\Libraries\Common\JsonUtility.cs:line 113
   --- End of inner exception stack trace ---
   at Microsoft.OpenPublishing.Build.Common.JsonUtility.FromJsonString[T](String value) in C:\__w\1\s\Libraries\Common\JsonUtility.cs:line 117
   at Microsoft.OpenPublishing.Build.WorkflowTasks.RunPowershellScript.ReplayLogFiles(BuildResult result, String innerRawLogFile, String arguments, Action`1 logItemProcessor) in C:\__w\1\s\Libraries\WorkflowTasks\RunPowershellScript.cs:line 495
`````
 - **[Warning: InvalidJsonLogLine]** 
`````
The log line content '{"message' can't be converted to log item. Details: System.ArgumentException: Invalid json string ---> Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '', line 1, position 9.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.OpenPublishing.Build.Common.JsonUtility.FromJsonString[T](String value) in C:\__w\1\s\Libraries\Common\JsonUtility.cs:line 113
   --- End of inner exception stack trace ---
   at Microsoft.OpenPublishing.Build.Common.JsonUtility.FromJsonString[T](String value) in C:\__w\1\s\Libraries\Common\JsonUtility.cs:line 117
   at Microsoft.OpenPublishing.Build.MessageProcessors.HostedEnvironmentMessageProcessorWithMSBuild.ReplayDocsPrepareErrorLog(MessageProcessResult processResult, String errorMessage, String outputFolder, ILogger logger, BuildStatus buildStatus, Boolean& hasSystemError) in C:\__w\1\s\Libraries\MessageProcessors\HostedEnvironmentMessageProcessorWithMSBuild.cs:line 351
`````

<a id="2853b9b1"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````
 - **[Warning: InvalidJsonLogLine]** 
`````
The log line content '{"message' can't be converted to log item. Details: System.ArgumentException: Invalid json string ---> Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '', line 1, position 9.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.OpenPublishing.Build.Common.JsonUtility.FromJsonString[T](String value) in C:\__w\1\s\Libraries\Common\JsonUtility.cs:line 113
   --- End of inner exception stack trace ---
   at Microsoft.OpenPublishing.Build.Common.JsonUtility.FromJsonString[T](String value) in C:\__w\1\s\Libraries\Common\JsonUtility.cs:line 117
   at Microsoft.OpenPublishing.Build.WorkflowTasks.RunPowershellScript.ReplayLogFiles(BuildResult result, String innerRawLogFile, String arguments, Action`1 logItemProcessor) in C:\__w\1\s\Libraries\WorkflowTasks\RunPowershellScript.cs:line 495
`````
 - **[Warning: InvalidJsonLogLine]** 
`````
The log line content '{"message' can't be converted to log item. Details: System.ArgumentException: Invalid json string ---> Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '', line 1, position 9.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, Js [...]

2021-12-29 09:43 UTC, opbld31 commented
Docs Build status updates of commit _[8c2caef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c2caefa58dc731ac1f53177806adee460a1ccee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112290940502943-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-29T09%3A43%3A50Z&sr=b&sp=r&sig=33EOqOtofFrNsn0Wt3rI2GqNzJtTyKLenECS36uYZ%2F4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +description: "Retrieve single callTranscript content associated to a Microsoft Teams Online Meeting."
associated with* ?

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 3: Get a callTranscript Content specifying Accept query param
Accept header

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +Response contains bytes for the transcript in the body. `content-type` header specifies type of the transcript content.
Uppercase c in Content-Type

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 4: Get a callTranscript Content with $format getting precedence
maybe complete the sentence- getting precedence over the Accept header

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get.md
> +description: "Retrieve single callTranscript associated to a Microsoft Teams Online Meeting."
associated with*

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get.md
> +description: "Retrieve single callTranscript associated to a Microsoft Teams Online Meeting."
here and in other places

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get.md
> +users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})
Prefix with GET

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})/content
Prefix with GET

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})/content
We should also include an example with /me.
That's what they seem to be doing for attendance report too: https://docs.microsoft.com/en-us/graph/api/meetingattendancereport-get?view=graph-rest-1.0

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get.md
> +This operation does not currently support [OData query parameters](/graph/query-parameters) to customize the response.
Can we remove this section entirely if it's not supported?

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-list.md
> +description: "Retrieve the list of transcripts associated to a Microsoft Teams Online Meeting."
associated with*. Here and in other places

2021-12-30 10:28 UTC, shantanu1singh commented on api-reference/beta/toc.yml
> +      - name: Online meetings
I can see an existing section for Online meetings in the toc. Let's update that one instead to include the new docs

2022-01-03 07:06 UTC, opbld33 commented
Docs Build status updates of commit _[4f58a2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f58a2c885923df1e89df81519ba3eeb01037ce1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-aa461651)
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-aa461651"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml)
 - **Line 12488, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201030704027453-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-03T07%3A06%3A10Z&sr=b&sp=r&sig=kT3bkbIMYI4U1WumhZt1mrxcyZtKg3sgA809lYpcyxE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 11:24 UTC, opbld34 commented
Docs Build status updates of commit _[db0c430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db0c430f3f3fd990738225d0ffe8cdc25f65e7d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6669aeb1)
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6669aeb1"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml)
 - **Line 12505, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051121174100-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T11%3A24%3A25Z&sr=b&sp=r&sig=OrSw4yR9bPWBGIMpkTtaDyMPUyY1r89Z42iPp76Yf4k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 11:32 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +description: "Retrieve single callTranscript content associated to a Microsoft Teams Online Meeting."
Done

2022-01-05 11:32 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 3: Get a callTranscript Content specifying Accept query param
Done

2022-01-05 11:33 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +Response contains bytes for the transcript in the body. `content-type` header specifies type of the transcript content.
Done

2022-01-05 11:33 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get.md
> +users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})
Done

2022-01-05 11:33 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get.md
> +description: "Retrieve single callTranscript associated to a Microsoft Teams Online Meeting."
Done

2022-01-05 11:34 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})/content
Done

2022-01-05 11:34 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})/content
Added

2022-01-05 11:34 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-list.md
> +description: "Retrieve the list of transcripts associated to a Microsoft Teams Online Meeting."
Done

2022-01-05 11:37 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get.md
> +This operation does not currently support [OData query parameters](/graph/query-parameters) to customize the response.
Done

2022-01-05 11:40 UTC, mankadnandan commented on api-reference/beta/toc.yml
> +      - name: Online meetings
The existing section for Online meetings falls under Cloud Communications. I thought of adding this under Teamwork for transcripts.

2022-01-07 07:14 UTC, opbld33 commented
Docs Build status updates of commit _[14401f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14401f583de6a844501c82deb6d7887235e08d0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201070712027966-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T07%3A14%3A00Z&sr=b&sp=r&sig=u8xSsgYnHb9%2B%2FEEvjAUhe1mWz0ySt6WR6xh8h7yTZus%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 12:30 UTC, shantanu1singh approved these changes
LGTM

2022-01-07 12:30 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +> This API is in beta and might undergo changes with respect to the request and/or response schema. Use of this API in production applications is not recommended.
Maybe just say This API might undergo changes...

since they already know that this is the /beta API documentation overall

2022-03-05 01:59 UTC, Lauragra commented
@mankadnandan , is this PR ready for content review? If so, please apply the **ready for content review** label. The schema associated with the PR has already been release so we need to get the docs published. Thanks.

2022-03-23 09:09 UTC, opbld31 commented
Docs Build status updates of commit _[82736bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82736bcb0e82add10d3d42ec81b2646b79ae5c98)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-66cdb87f)

<a id="66cdb87f"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203230908323494-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T09%3A09%3A14Z&sr=b&sp=r&sig=qyZ%2FB44wYeqJoSU1T%2BOcp5qmTSnfaa0%2Fs4f2Ude6rsM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 09:22 UTC, opbld33 commented
Docs Build status updates of commit _[d28e5b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d28e5b6afdc0014b6e66b63a2bbab6d05dfc46a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203230920291994-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T09%3A22%3A40Z&sr=b&sp=r&sig=hrEfjCL1gtlSLeZydOT80kiQi2%2BIldR444iS4hiJcQs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 09:48 UTC, opbld32 commented
Docs Build status updates of commit _[b82f9f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b82f9f6afd0d3fabe579700fde2eb7c7d1b3b3da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203300946518922-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T09%3A48%3A38Z&sr=b&sp=r&sig=iirnB2zD%2F0S0UGiA9QdZqTMeVy5ZD0fc8fHJd2Ot8sI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 10:11 UTC, opbld30 commented
Docs Build status updates of commit _[ff349fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff349fc994d4fd1b782171c6b7bd11987fe61a75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301007465697-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T10%3A11%3A32Z&sr=b&sp=r&sig=YZausKHL2CxI4F6FZYh1cy0%2B7FCBcTKvx83MCj1PqzE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 10:26 UTC, opbld32 commented
Docs Build status updates of commit _[0d8c3b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d8c3b95295e9e2d4457754453becd596e28a405)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301022575930-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T10%3A26%3A02Z&sr=b&sp=r&sig=t4gOKCJyJ3x5qXLjOHLsDxfrUU9MMI7X2vaaS4K%2BdWs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 10:52 UTC, opbld31 commented
Docs Build status updates of commit _[0a21f48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a21f489a10add22d1d90781087e48ef3a5d164c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311050322334-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T10%3A52%3A35Z&sr=b&sp=r&sig=pGmj2PRztSLJxUyjmDRVyk7els3kGozczmyz%2BoMkRLA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 07:20 UTC, shantanu1singh approved these changes

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-list.md
> +    ]
Not sure but maybe reduce the number of items we are returning in the sample response just to keep things concise.

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-list.md
> +| Server-side pagination |     ✓     | `@odata.nextLink`                      | |
Looks like the following was added under the 'Notes' column for servcer-side pagination in other docs:

You will get a continuation token in the response, when a result set spans multiple pages.

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +This method supports the `$format` [OData query parameters](/graph/query-parameters) to help customize the response.
singular - parameter?

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +This method supports the `$format` [OData query parameters](/graph/query-parameters) to help customize the response.
Maybe reword to the following?

This method supports the `$format` [OData query parameter](/graph/query-parameters) that allows response customization?

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 1: Get a callTranscript Content
lowercase - content?

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 2: Get a callTranscript Content specifying $format query param
lowercase - content?

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 3: Get a callTranscript Content specifying Accept header
lowercase - content?

2022-04-01 07:20 UTC, shantanu1singh commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 4: Get a callTranscript Content with $format getting precedence over the Accept header
lowercase - content?

2022-04-04 09:42 UTC, opbld31 commented
Docs Build status updates of commit _[ff0ab28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff0ab28076ca01dd70288b1106d0d6a1c309af33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204040940018165-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T09%3A42%3A02Z&sr=b&sp=r&sig=H8oBSNiMAO7qGqjUURXSddtDpl6y5vYURdTWBy0j9wU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 09:48 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-list.md
> +| Server-side pagination |     ✓     | `@odata.nextLink`                      | |
Added

2022-04-04 09:49 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +This method supports the `$format` [OData query parameters](/graph/query-parameters) to help customize the response.
Done

2022-04-04 09:50 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 1: Get a callTranscript Content
Done

2022-04-04 09:50 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 2: Get a callTranscript Content specifying $format query param
Done

2022-04-04 09:51 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 3: Get a callTranscript Content specifying Accept header
Done

2022-04-04 09:51 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +### Example 4: Get a callTranscript Content with $format getting precedence over the Accept header
Done

2022-04-07 19:52 UTC, isvargasmsft commented on api-reference/beta/resources/callTranscript.md
> +---
Please remove the capitalization from the file name. It should be calltranscript.md

2022-04-07 19:58 UTC, isvargasmsft commented on api-reference/beta/resources/callTranscript.md
> +---
Please apply to the other file names. We use camel caps for titles but small caps for file names.

2022-04-07 19:59 UTC, isvargasmsft commented on api-reference/beta/resources/callTranscript.md
> +| createdDateTime| dateTimeOffset|  Date and time at which the transcript was created. Read-only.|
Property missing: content.
 <Property Name="content" Type="Edm.Stream" />

2022-04-07 19:59 UTC, isvargasmsft commented on api-reference/beta/resources/callTranscript.md
> +  "createdDateTime": "dateTimeOffset",
Missing property: content.
 <Property Name="content" Type="Edm.Stream" />

2022-04-07 20:04 UTC, opbld34 commented
Docs Build status updates of commit _[9ec9096](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ec90967cebb6fe175f9c526bca9d2803b991fbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callTranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/callTranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/callTranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/callTranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/callTranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204072002598724-15348%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T20%3A04%3A52Z&sr=b&sp=r&sig=6QhlyRWDOYLXbn6oNZ5lBqc%2FcAjCUV1aFI1evktptco%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 20:07 UTC, isvargasmsft commented on api-reference/beta/api/callTranscript-get-content.md
> +# Get callTranscript content
It seems like the content property is being treated as a navigation property, but in the CSDL it is being introduced as a regular property. Please clarify.

2022-04-07 20:10 UTC, isvargasmsft commented on api-reference/beta/api/callTranscript-list.md
> +﻿---
I believe the file name should be: onlinemeeting-list-transcripts. According to the file name guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming?anchor=microsoft-graph-file-naming-guidelines

<img width="597" alt="image" src="https://user-images.githubusercontent.com/70350956/162287804-5814efbd-5d7e-4a38-a27e-18d0609fb1d6.png">

2022-04-07 20:12 UTC, isvargasmsft commented on api-reference/beta/resources/onlinemeeting.md
> +| transcripts | [callTranscript](callTranscript.md) collection | The transcripts of an online meeting. Read-only. |
In the methods column in this topic, please add the List transcripts operation. We should also add the List operations for the attendanceReport navigation property that is also a collection of objects.

2022-04-07 20:14 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +        }
Please follow the guidelines to add changelog entries for CRUD operations, specifically example 6 of this list: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-properties

We should add one changelog entry for each element.

2022-04-07 20:15 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
In this case, the ApiChange is not a resource, but a Relationship. Please follow example 3 here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

2022-04-07 20:22 UTC, isvargasmsft requested changes
Hello @mankadnandan, 

Thank you very much for your work in this PR. 

Just a few comments:
1. Please remove the capitalization from file names and review the structure of file name for list operations. 
2. Please clarify of the content property of callTranscript is a navigation property or a regular property. And please document it accordingly in the callTranscript resource topic. 
3. Please take a look at some changelog documentation issues. I pasted the guidelines with examples in the comments. 

Regarding the TOC and the area, please let me ask whether this belongs to teamwork or to cloud communications. 

Please ping me on the side if you have questions. 

Kind regards, 

Isaac

2022-04-11 10:06 UTC, mankadnandan commented on api-reference/beta/resources/callTranscript.md
> +---
Thanks. Done.

2022-04-11 10:07 UTC, opbld31 commented
Docs Build status updates of commit _[2adc640](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2adc6405d07a5653548165c1c274b58b60155806)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204111004468813-15348%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T10%3A07%3A15Z&sr=b&sp=r&sig=AZm2dUbmixnVnRQfnA97X8GR6GrwyBsKHS%2FhX0T3q%2Fw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 10:07 UTC, mankadnandan commented on api-reference/beta/resources/callTranscript.md
> +| createdDateTime| dateTimeOffset|  Date and time at which the transcript was created. Read-only.|
The content property is not directly exposed in the response.

2022-04-11 10:08 UTC, mankadnandan commented on api-reference/beta/resources/callTranscript.md
> +  "createdDateTime": "dateTimeOffset",
The content property is not directly exposed in the response.

2022-04-11 10:09 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-get-content.md
> +# Get callTranscript content
Content property is a regular property but is not directly exposed in the response.

2022-04-11 10:34 UTC, mankadnandan commented on api-reference/beta/api/callTranscript-list.md
> +﻿---
I see. I thought it was more intuitive to have the file named in the current way as the get API are also named in the similar fashion. Let me know if thats fine or we should follow the guideline and I can rename it accordingly.

2022-04-11 12:07 UTC, mankadnandan commented on api-reference/beta/resources/onlinemeeting.md
> +| transcripts | [callTranscript](callTranscript.md) collection | The transcripts of an online meeting. Read-only. |
Sure. Should we add only the list method or we should also add Get and Get Content methods too? Actually attendanceReport is not owned by our team so we might have to involve Frank Peng for it.

2022-04-11 12:25 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +        }
Sure, changed.

2022-04-11 12:25 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Sure, changed.

2022-04-11 12:29 UTC, mankadnandan commented
> 
Hi @isvargasmsft Thanks for your review. Appreciate it.

I have made most of the changes. I have replied for few of them where I had a few questions. Let me know and I will work on them quickly to push them.

2022-04-12 06:16 UTC, mankadnandan commented
@Lauragra - While @isvargasmsft is out this week, can we get someone to check this PR?

2022-04-19 19:08 UTC, opbld34 commented
Docs Build status updates of commit _[fe61629](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe616290ebd021494f7d09ed77439dc52bf6f5f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204191906290952-15348%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T19%3A08%3A27Z&sr=b&sp=r&sig=CPV%2FvAIkuig75l9q3iv3G2eLTSNvONN4rJYSeWXLDZI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 19:11 UTC, opbld31 commented
Docs Build status updates of commit _[fb57749](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb57749b1e6d41418fd1840cc7d0814a0f62f0dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204191908483266-15348%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T19%3A11%3A14Z&sr=b&sp=r&sig=wxG2PSnDnZzZFeX747%2BneKLH8d6r7xvI8Z1tZA5BfgY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 19:12 UTC, isvargasmsft commented on api-reference/beta/resources/onlinemeeting.md
> +| transcripts | [callTranscript](callTranscript.md) collection | The transcripts of an online meeting. Read-only. |
Only the list transcript method, please.

2022-04-19 19:15 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +      - name: Online meetings
Checking with the docs team. Please bear with me.

2022-04-20 14:49 UTC, isvargasmsft commented
Blocking this PR until we resolve whether these resources are for private preview or beta. 

After checking with architects, we found some inconsistencies in the schema files. 

Please review with onboarding team and clarify.

2022-05-09 08:25 UTC, mankadnandan commented
> Blocking this PR until we resolve whether these resources are for private preview or beta.
> 
> After checking with architects, we found some inconsistencies in the schema files.
> 
> Please review with onboarding team and clarify.

Hi @isvargasmsft  - This

2022-05-09 08:27 UTC, opbld31 commented
Docs Build status updates of commit _[fb57749](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb57749b1e6d41418fd1840cc7d0814a0f62f0dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090825455888-15348%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T08%3A27%3A38Z&sr=b&sp=r&sig=ZRmCMmw4RYk%2FEYZhfBBZnj5vvnVziZIVxoDziXjZl%2Fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 07:20 UTC, opbld34 commented
Docs Build status updates of commit _[a0eaa12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0eaa12fd8403160c459da190f45fce782bbe33e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ceb76eac)

<a id="ceb76eac"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207080719257633-15348/BuildReport?accessString=c29559b598dfbc36405dfcb07f500a5072847cae9c09e5eae96097db8867dffd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 07:39 UTC, opbld34 commented
Docs Build status updates of commit _[6c30e9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c30e9bb99e7012aec61cb08aa02c6e5c2e871fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207080737156730-15348/BuildReport?accessString=c1a4727130a1314dcf74fe932949835499acc4a6ef384886569698f719dcec84).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 07:50 UTC, opbld32 commented
Docs Build status updates of commit _[1c4b190](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c4b19018a472bd97ee326bebe3ffa18597f9386)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207080748383889-15348/BuildReport?accessString=1c2995f69bf95b10cebad9b4210dd2aacc38cd61124b2f4b3965e537fc60fce7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 17:28 UTC, isvargasmsft commented on api-reference/beta/resources/calltranscript.md
> +| createdDateTime| dateTimeOffset|  Date and time at which the transcript was created. Read-only.|
Please add the property "content":
Even if it is not returned in get operations, it is still a valid property and should be documented.

2022-07-08 17:29 UTC, isvargasmsft commented on api-reference/beta/resources/calltranscript.md
> +  "createdDateTime": "dateTimeOffset",
Please add the property "content" as per my last comment.

2022-07-08 17:32 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +      - name: Online meetings
Please use the existing Online meetings node in the TOC. Do not create additional node under Teamwork for now.

2022-07-08 17:34 UTC, isvargasmsft commented on api-reference/beta/resources/onlinemeeting.md
> +| transcripts | [callTranscript](callTranscript.md) collection | The transcripts of an online meeting. Read-only. |
The CSDL PR is not introducing this new navigation property to beta, only the new entity. Could you please clarify? Is there another CSDL PR?

2022-07-08 17:41 UTC, opbld30 commented
Docs Build status updates of commit _[e705701](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e705701f4b826b2789f7e6c875be5c0da33083e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207081739107762-15348/BuildReport?accessString=adaee581ea309912d05f369541ae8ad1edc8a7c6cb8c924fb1ae4bbbf4b47c02).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 17:42 UTC, isvargasmsft requested changes
Hello team, 

Thank you very much for the work in this PR. Please review the following:
1. Let's use the existing Online meetings node in the TOC. Do not create a new one under Teamwork for now. 
2. Please add the property "content" to the properties table and the JSON representation of the resource topic. Even if it is not returned by GET operations, it is still a valid property and should be documented.
3. I noticed the CSDL PR is not introducing the new navigation property (callTranscripts) to the onlineMeeting resource. Please take a look. If there is another CSDL PR that introduced the change, please share it with me on the side. 

Thank you very much. 

Isaac

2022-07-11 05:14 UTC, opbld33 commented
Docs Build status updates of commit _[3246796](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32467961b63c5da8f9a58f522320e78744ad875c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110511289675-15348/BuildReport?accessString=0f03a9c2e7242139b4c8efe3641639278f441a6ac741ffba4990a2bcd6d68836).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 05:14 UTC, mankadnandan commented on api-reference/beta/resources/calltranscript.md
> +| createdDateTime| dateTimeOffset|  Date and time at which the transcript was created. Read-only.|
Sure, makes sense. Added.

2022-07-11 05:16 UTC, opbld34 commented
Docs Build status updates of commit _[4ee1ca7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ee1ca76f10b0cd2de51776cac2a36c1c3f35a5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110513598533-15348/BuildReport?accessString=909544444653d3888691025a39db4c68a5aee5ddfafb62c261665cbb090ddf80).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 05:17 UTC, mankadnandan commented on api-reference/beta/resources/calltranscript.md
> +  "createdDateTime": "dateTimeOffset",
Added.

2022-07-11 05:18 UTC, opbld33 commented
Docs Build status updates of commit _[f22aafa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f22aafa71166a25fa75cb6d6e9c98814f05e8d00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110516397346-15348/BuildReport?accessString=53e30509a898c91948389940dd87a5dfcc0a80c06f825cb2eb0892838fb5af0f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 05:20 UTC, mankadnandan commented on api-reference/beta/toc.yml
> +      - name: Online meetings
Sure, thanks. Done.

2022-07-11 05:21 UTC, mankadnandan commented on api-reference/beta/resources/onlinemeeting.md
> +| transcripts | [callTranscript](callTranscript.md) collection | The transcripts of an online meeting. Read-only. |
In the original CSDL PR https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5458466?_a=files&path=/Schemas/beta-Prod.csdl we have added that on the line number 23255.

Let me know if this looks good.

2022-07-11 05:42 UTC, opbld32 commented
Docs Build status updates of commit _[1026c5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1026c5c9994bd609fccd03a23840824e14581da2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110539447434-15348/BuildReport?accessString=49dd428d9b8f97c412cb09264bf40123aa49e106469e412b320db843f416de1e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 05:58 UTC, opbld31 commented
Docs Build status updates of commit _[d919721](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d919721e33c867cbb94ff951c9b40c2faad520f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-list?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110555570406-15348/BuildReport?accessString=b1e3a535906cc82b14615b45b4658a232f33ed3251c0b866a2b2fd7c5ffa7470).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:07 UTC, isvargasmsft commented on api-reference/beta/api/calltranscript-get.md
> +GET users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})
Please include the leading /
```suggestion
GET /me/onlineMeetings({meetingId})/transcripts({transcriptId})
GET /users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})
```

2022-07-11 16:12 UTC, isvargasmsft commented on api-reference/beta/api/calltranscript-get-content.md
> +# Get callTranscript content
After consulting with my team, we decided the consistent way to show this use case of getting the content of a transcript is in the calltranscript-get.md topic. Make a mention of that in the top section; link to an example below. In the HTTP request section, show a separate description and syntax line after the existing 2 lines (lines 36-39). In the Examples section, add an example with a section title that captures getting the content of a transcript.

We can then delete this separate topic.

2022-07-11 16:15 UTC, opbld32 commented
Docs Build status updates of commit _[0575099](https://github.com/microsoftgraph/microsoft-graph-docs/commits/057509981a295b49f6b360b06113c8729ec7b941)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-6d2a9396c3b64afa15a79ef3cd19c5ad-3eff4f95)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3eff4f95)
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

<a id="6d2a9396c3b64afa15a79ef3cd19c5ad-3eff4f95"></a>
### [api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calltranscript-list.md'.`````

<a id="0817dce4456c16725d5333633847d38f-3eff4f95"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml)
 - **Line 1690, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/calltranscript-list.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111613139199-15348/BuildReport?accessString=610adc6c9a5614f953799f94c15aaaa401fb05ad587213a8ac9d71905229ea3f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:17 UTC, opbld34 commented
Docs Build status updates of commit _[0ca7f50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ca7f50dab7f8106051967bed480016247594f32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-6d2a9396c3b64afa15a79ef3cd19c5ad-50e01266)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-50e01266)
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

<a id="6d2a9396c3b64afa15a79ef3cd19c5ad-50e01266"></a>
### [api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calltranscript-list.md'.`````

<a id="0817dce4456c16725d5333633847d38f-50e01266"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml)
 - **Line 1690, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/calltranscript-list.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111613324287-15348/BuildReport?accessString=b5108cb718499776534d25da17bdf83f6b3f9a346f01f5e0eed790476d8e281f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:18 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +        }
Per my last comment, we can delete this changelog entry.
```suggestion
        }
```

2022-07-11 16:20 UTC, opbld32 commented
Docs Build status updates of commit _[44e6cac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44e6cac13902c9e4e0fc8f918108a62f784ef541)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-6d2a9396c3b64afa15a79ef3cd19c5ad-85d4e215)
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

<a id="6d2a9396c3b64afa15a79ef3cd19c5ad-85d4e215"></a>
### [api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calltranscript-list.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111617037303-15348/BuildReport?accessString=8578a32e6569d17a52600b1c7de04576a82bea69c757ed103c5211c3edb25b11).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:24 UTC, isvargasmsft requested changes
Let's move the information about getting the content of a call transcript to the get operation of the call transcript and delete the separate get-content topic.

2022-07-11 16:51 UTC, opbld34 commented
Docs Build status updates of commit _[edd27e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edd27e267304eedf55dd02fdaa11178113c4875f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-6d2a9396c3b64afa15a79ef3cd19c5ad-4e49c7eb)
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

<a id="6d2a9396c3b64afa15a79ef3cd19c5ad-4e49c7eb"></a>
### [api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calltranscript-list.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111617280002-15348/BuildReport?accessString=98d00ec31a43e8fb2427c3523e1f19b7a8e3c1f51ba9b801a9a0c59112d36a2b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:56 UTC, opbld32 commented
Docs Build status updates of commit _[9d93cbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d93cbd1f8674784a625bf3c3c96ec2930d51f82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111627034530-15348/BuildReport?accessString=ccd4e89704a1bca2b3d31abd3f16b431dd34f555c596216c514c2c4454e27ccc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:58 UTC, opbld30 commented
Docs Build status updates of commit _[710dd47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/710dd47431ac12e57189dcf7e25da90131f65bbe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-6d2a9396c3b64afa15a79ef3cd19c5ad-ca840fcb)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ca840fcb)
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-15348) |

<a id="6d2a9396c3b64afa15a79ef3cd19c5ad-ca840fcb"></a>
### [api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calltranscript-list.md'.`````

<a id="0817dce4456c16725d5333633847d38f-ca840fcb"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml)
 - **Line 1690, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/onlinemeeting-list-transcripts.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111615587124-15348/BuildReport?accessString=95b033443416f1b44ea01a92bdeeb8f6fb7f84aaee9297a3d7c96bfb70d4dfb6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 12:26 UTC, opbld32 commented
Docs Build status updates of commit _[1977d1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1977d1c4881866bb4851ef41b1737704b754bf44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) | [Details](#user-content-f71c153ecd635647f60fe424acb38b6b-977c1ff9)
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/calltranscript-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get-content?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f71c153ecd635647f60fe424acb38b6b-977c1ff9"></a>
### [api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md)
 - **Line 29, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calltranscript-list.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121224067588-15348/BuildReport?accessString=eccffc73834406a93d171a04cb001e9657dd7386648ea37d933484fd4d8dfcf7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 12:56 UTC, opbld30 commented
Docs Build status updates of commit _[7d8480a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d8480ab9fc688e75ad8d53f62551d2376211538)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121252570617-15348/BuildReport?accessString=3be956dfb0ae41798a1d79e1d14c620398f9a7c0a72ddb52180a994d73b93ef2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 13:02 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +        }
Done

2022-07-12 13:06 UTC, mankadnandan commented on api-reference/beta/api/calltranscript-get-content.md
> +# Get callTranscript content
Sure. So I have removed the topic calltranscript-get-content.md and have updated calltranscript-get.md to include the content details, as per my understanding. Though I am not sure if it covers all the asks, so let me know if we need to change a bit more.

Also, the content page had some examples some more examples of showing how to use some other query params ($format), and headers? Shouldn't we include those examples too to make sure the api developer knows what all options they have while calling the /content endpoint?

2022-07-12 15:08 UTC, opbld32 commented
Docs Build status updates of commit _[1303fb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1303fb6c640ff5f5b80e925a372c2658b55e074e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121505567822-15348/BuildReport?accessString=b610e2f267085248c59a9fea39df8b6a8f7859fa608481f42c9f40840540e963).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 15:19 UTC, isvargasmsft commented on api-reference/beta/api/calltranscript-get.md
> +Retrieve a [callTranscript](../resources/calltranscript.md) object associated with an [onlineMeeting](../resources/onlinemeeting.md).
Please add a sentence explaining the difference between getting the transcript and getting the context of the transcript.

2022-07-12 17:34 UTC, mankadnandan commented on api-reference/beta/api/calltranscript-get.md
> +Retrieve a [callTranscript](../resources/calltranscript.md) object associated with an [onlineMeeting](../resources/onlinemeeting.md).
Added

2022-07-12 17:35 UTC, mankadnandan commented on api-reference/beta/api/calltranscript-get-content.md
> +# Get callTranscript content
Included other examples as discussed.

2022-07-12 17:36 UTC, opbld32 commented
Docs Build status updates of commit _[fe56bda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe56bdabc59d3e2abfc387625dd42da86bf7c7ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121733373270-15348/BuildReport?accessString=3b12762b3a7f394b6e660b3d68396bede6bdd8b0dce38bb990b706bf4b71b684).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 17:52 UTC, opbld33 commented
Docs Build status updates of commit _[459f5f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/459f5f80c24cdc3f45a2d76acbe8187835f61e77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121749216258-15348/BuildReport?accessString=1bb285e0b810f4e0a70b3e8309590774cf33a9cc073fba0e5f0cf3cd751685c7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 07:59 UTC, opbld30 commented
Docs Build status updates of commit _[f279d23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f279d23afc636cc7eebf667d98cb7ab43f7c94a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207220756217394-15348/BuildReport?accessString=06462e6ab3e0596eb35b85ca8fa096fab82a0a140cac11bc1c570531dd43621f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:48 UTC, opbld31 commented
Docs Build status updates of commit _[9b33998](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b339981f8ba013c0d9fa171f3ae3aa549f1205c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020446094663-15348/BuildReport?accessString=e1e3a53b9eadb86ea2cd8692db694018fe2a7715aa0ddc2f2b96e14234c925b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:50 UTC, opbld34 commented
Docs Build status updates of commit _[83e8f8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83e8f8cb3d9799ea14bdf54473aa3ae6fcc47cd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020447248987-15348/BuildReport?accessString=4b95a4db2ed07893f99eaef347fccaa81237c50a74412f31d6d5331532da9c6b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:53 UTC, opbld30 commented
Docs Build status updates of commit _[f176721](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f176721e9a8814176cdc3616f161285938c33641)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/calltranscript-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/api/onlinemeeting-list-transcripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/calltranscript.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/calltranscript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&branch=pr-en-us-15348) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-transcript-api-changes/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020449291052-15348/BuildReport?accessString=9f28eaf41695a7ac6616043bfb1c7125a183bb9ff881ac6565e39d6046239b0c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:56 UTC, merged