Add multi-stage scenarios in Access Review API beta
microsoftgraph/microsoft-graph-docs pull request #15387
Opened 2022-01-04 00:56 UTC by kaiwenfeng4086

2022-01-04 00:56 UTC, opbld30 commented
Docs Build status updates of commit _[9cdcbbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9cdcbbf50023526efe5e8e36994aea44effd096f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-de7cd6cd)

<a id="de7cd6cd"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040056060411-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T00%3A56%3A30Z&sr=b&sp=r&sig=ER08BIZ8yNxrivwxZrhFkpvticzJTACuLOe4XVzMqqs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 20:16 UTC, opbld31 commented
Docs Build status updates of commit _[abc59de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abc59defea2d392242a61533f08539bf6f28e352)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-8c03c390)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-8c03c390)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-8c03c390)
[]() | :warning:Warning | | [Details](#user-content-8c03c390)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-8c03c390"></a>
### [api-reference/beta/api/accessreviewinstancedecisioni [...]

2022-01-04 21:23 UTC, opbld31 commented
Docs Build status updates of commit _[fee62ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fee62efe1c7beb636b07ba5895eabcef4cd5ac3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-854fc701)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-854fc701)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-854fc701)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-854fc701"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 41, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Function parameters''. Each second level heading (H2) in an article mu [...]

2022-01-04 23:01 UTC, opbld31 commented
Docs Build status updates of commit _[ebac263](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebac263c7224231fed89c3e8160f507c99cc7757)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-3ec71a74)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-3ec71a74)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-3ec71a74)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-3ec71a74"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 41, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Function parameters''. Each second level heading (H2) in an article mu [...]

2022-01-04 23:11 UTC, isabelleatmsft reviewed
filterbycurrentuser file suggestions

2022-01-04 23:11 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
>  Retrieves all [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) objects on a given [accessReviewInstance](../resources/accessreviewinstance.md) for which the callin
```suggestion
Retrieves all [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) objects on a given [accessReviewInstance](../resources/accessreviewinstance.md) or [accessReviewStage](../resources/accessReviewStage.md) for which the calling user is the reviewer.
```

2022-01-04 23:11 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +If it is a multi-stage access review, retrieves all [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) objects on a given [accessReviewStage](../resources/accessRevi
```suggestion
```

2022-01-04 23:11 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +If it is a multi-stage access review, retrieves all [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) objects on a given [accessReviewStage](../resources/accessRevi
i think we can just explain this in the examples

2022-01-04 23:11 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +>reviewer can retrieve the decisions from other stages if the decisionHistoriesForReviewersEnabled is enabled in [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md)
```suggestion
>Reviewers can retrieve the decisions from previous stages on the instance if the decisionHistoriesForReviewersEnabled property is enabled in [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md) on the [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md)
```

2022-01-04 23:13 UTC, opbld34 commented
Docs Build status updates of commit _[ab011dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab011ddbec1d0eb4b51120835cba37dd56b0ceea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-938ae465)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-938ae465)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-938ae465)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-938ae465"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 40, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Function parameters''. Each second level heading (H2) in an article mu [...]

2022-01-04 23:23 UTC, opbld34 commented
Docs Build status updates of commit _[16fc4e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16fc4e6b2d545c4ad9a28c6c6d8d969fe0f60027)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-3a794848)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-3a794848)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-3a794848)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-3a794848"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7857ef1820a4f51f4a9e8cde19ef0d88-3a794848"> [...]

2022-01-05 00:36 UTC, isabelleatmsft approved these changes

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection|The stage settings of an access review series. Stages will be created sequentially based on the depend
```suggestion
|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created sequentially based on the dependsOn property. Each stage can have different set of reviewer, fallback reviewers and settings. See [accessReviewStageSettings](../resources/accessreviewstagesettings.md). Optional.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewset-post-definitions.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection|The stage settings of an access review series. Stages will be created sequentially based on the depend
```suggestion
|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created sequentially based on the dependsOn property. Each stage can have different set of reviewer, fallback reviewers and settings. See [accessReviewStageSettings](../resources/accessreviewstagesettings.md). Optional.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewset-post-definitions.md
> +### Example 4: Create an access review on a group with multi-stage
```suggestion
### Example 4: Create an access review on a group with multiple stages
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-list-decisions.md
> +>The default page size for this API is 100 accessReviewInstance objects. To improve efficiency and avoid timeouts due to large result sets, apply pagination using the `$skip` and `$top` query paramet
```suggestion
>The default page size for this API is 100 accessReviewStage objects. To improve efficiency and avoid timeouts due to large result sets, apply pagination using the `$skip` and `$top` query parameters. For more information, see [Paging Microsoft Graph data in your app](/graph/paging).
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-list.md
> +Retrieve the [accessReviewStage](../resources/accessreviewstage.md)objects for a specific [accessReviewInstance](../resources/accessreviewinstance.md).
```suggestion
Retrieve the [accessReviewStage](../resources/accessreviewstage.md) objects for a specific [accessReviewInstance](../resources/accessreviewinstance.md).
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-stop.md
> +Stop a currently active [accessReviewStage](../resources/accessReviewStage.md). After the access review stage stops, the instance status will be in `Completed` status, the reviewers can no longer giv
```suggestion
Stop a currently active [accessReviewStage](../resources/accessReviewStage.md). After the access review stage stops, the stage status will be in `Completed` status and the reviewers can no longer give input. If there are other stages depend on the completed stage, the next stage will be created. 
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-update.md
> +> Updating an **accessReviewStage** will update only that instance. The parent **accessReviewInstance** and any future **accessReviewStage** objects won't change. To make updates that apply to all fu
```suggestion
> Updating an **accessReviewStage** will update only that stage. The parent **accessReviewInstance** and any future **accessReviewStage** objects won't change. To make updates that apply to all future instances and stages, update the parent [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object.
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstance.md
> +|stages|[accessReviewStage](../resources/accessreviewstage.md) collection|Returns the collection of stages if it is a multi-stage access review. The new stage will only be created when the previous s
```suggestion
|stages|[accessReviewStage](../resources/accessreviewstage.md) collection| If the instance has multiple stages, this returns the collection of stages. A new stage will only be created when the previous stage ends. The existence, number, and settings of stages on a review instance are created based on the [accessReviewStageSettings](accessreviewstagesettings.md) on the parent [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) |
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection|The stage settings of an access review series. Stages will be created sequentially based on the depend
```suggestion
|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection|The stage settings of an access review series. If a review series has stages, each review instance will be broken down in to up to 3 sequential stages, where each stage can have different set of reviewer, fallback reviewers and settings. Stages will be created sequentially based on the dependsOn property. Optional.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +|decisionHistoriesForReviewersEnabled|Boolean|Indicate whether decision histories are available for reviewers for multi-stage access review. If not provided, default is disabled.|
```suggestion
|decisionHistoriesForReviewersEnabled|Boolean| Indicates whether decisions on previous access review stages are available for reviewers on an accessReviewInstance with multiple subsequent stages. If not provided, default is disabled.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +Represents an Azure AD [access review](accessreviewsv2-overview.md) recurrence. If the  [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) has the stageSettings set up, the parent [a
```suggestion
Represents a stage of an Azure AD [access review](accessreviewsv2-overview.md) recurrence. If the  [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) has the stageSettings property filled, the parent [accessReviewInstance](accessReviewInstance.md) will be comprised of up to three subsequent stages. Each stage may have a different set of reviewers who can act on the stage decisions, and settings determining which decisions will pass from stage to stage.
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +|id|String|Unique identifier of the instance. Supports `$select`. Read-only.|
```suggestion
|id|String|Unique identifier of the stage. Supports `$select`. Read-only.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +|startDateTime|DateTimeOffset|DateTime when review instance is scheduled to start. May be in the future. The DateTimeOffset type represents date and time information using ISO 8601 format and is alwa
```suggestion
|startDateTime|DateTimeOffset|DateTime when review stage is scheduled to start. May be in the future. The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`. Supports `$select`. Read-only. |
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +|status|String|Specifies the status of an accessReview. Possible values: `Initializing`, `NotStarted`, `Starting`, `InProgress`, `Completing`, `Completed`, `AutoReviewing`, and `AutoReviewed`. Suppor
```suggestion
|status|String|Specifies the status of an accessReviewStage. Possible values: `Initializing`, `NotStarted`, `Starting`, `InProgress`, `Completing`, `Completed`, `AutoReviewing`, and `AutoReviewed`. Supports `$select`, `$orderby`, and `$filter` (`eq` only). Read-only.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +|decisions|[accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) collection|Each user reviewed in an accessReviewInstance has a decision item representing if they were
```suggestion
|decisions|[accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) collection|Each user reviewed in an accessReviewStage has a decision item representing if they were approved, denied, or not yet reviewed.|
```

2022-01-05 00:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstagesettings.md
> +|dependsOn|String collection|Define the sequential or parallel order of each stageSettings. Currently only support single dependency|
```suggestion
|dependsOn|String collection|Define the sequential or parallel order of each stageSettings. Only sequential stages are currently supported.|
```

2022-01-05 00:40 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-update.md
> +To update an **accessReviewStage**, it's **status** must be `InProgress`.
```suggestion
To update an **accessReviewStage**, it's **status** must be `NotStarted`, `Initializing`, or `InProgress`.
```

2022-01-05 00:41 UTC, opbld33 commented
Docs Build status updates of commit _[ceb4a94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ceb4a94cfc5196c56cffb1a80c1a45b6bf67da1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-eeca25cb)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-eeca25cb)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-eeca25cb)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-eeca25cb"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7857ef1820a4f51f4a9e8cde19ef0d88-eeca25cb"> [...]

2022-01-05 00:44 UTC, opbld32 commented
Docs Build status updates of commit _[91a4ab2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91a4ab2dd9ff1439566f497e6a5b94c2d3c722d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-533764c6)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-533764c6)
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-afc6076d43ccceede526d6afc40debee-533764c6)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-533764c6"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7857ef1820a4f51f4a9e8cde19ef0d88-533764c6"> [...]

2022-01-13 14:56 UTC, opbld31 commented
Docs Build status updates of commit _[0dc1e6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0dc1e6bef2a6a4ef4fe26d0c2dfc52f070c97982)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-3aabea78)
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-7857ef1820a4f51f4a9e8cde19ef0d88-3aabea78)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-3aabea78"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7857ef1820a4f51f4a9e8cde19ef0d88-3aabea78"></a>
### [api-reference/beta/api/accessreviewinstancedec [...]

2022-01-13 15:05 UTC, opbld34 commented
Docs Build status updates of commit _[c3a625c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3a625c53578d01e329bc54435dc4432364c4925)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-b2061c03)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-b2061c03"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735 [...]

2022-01-13 15:10 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +Retrieves all [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) objects on a given [accessReviewInstance](../resources/accessreviewinstance.md) or [accessReviewStag
```suggestion
Retrieves all decision items on an instance of an access review or a stage of an instance of a multi-stage access review, for which the calling user is the reviewer. The decision items are presented by a [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) objects on a given [accessReviewInstance](../resources/accessreviewinstance.md) or [accessReviewStage](../resources/accessReviewStage.md) for which the calling user is the reviewer.
```

2022-01-13 15:11 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +description: "Retrieves all accessReviewInstanceDecisionItem objects on an accessReviewInstance or accessReviewStage for which the calling user is the reviewer."
Same principle of making the description as user-friendly as possible.
```suggestion
description: "Retrieves all decision items on an instance of an access review or a stage of an instance of a multi-stage access review, for which the calling user is the reviewer."
```

2022-01-13 15:13 UTC, opbld30 commented
Docs Build status updates of commit _[74fc49c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74fc49c0bf2329d2956c77ab8f2f459b05742202)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-7b81d908)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-7b81d908"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735 [...]

2022-01-13 15:17 UTC, opbld34 commented
Docs Build status updates of commit _[509069b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/509069b4cdf56ba385ac3abca3e50e7af9b6b77a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-5eaf37cb0af2788ed3f1118803277489-0d15f5e1)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5eaf37cb0af2788ed3f1118803277489-0d15f5e1"></a>
### [api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 178, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735 [...]

2022-01-13 15:17 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +>[!NOTE]
Could this note possibly be in the wrong doc? Coz the scope of this 2nd URL is a particular stageId. Could this note be intended for the first syntax? Or maybe somewhere else?

2022-01-13 15:21 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +  "name": "accessreviewinstancedecisionitem_filterbycurrentuser"
Please make this a unique name. Helps avoid clashes in code snippet names and the wrong snippet being appended to an example.

2022-01-13 15:23 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +               "Description":"Added the **decisionHistoriesForReviewersEnabled** property to the [accessReviewScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewSchedu
```suggestion
               "Description":"Added the **decisionHistoriesForReviewersEnabled** property to the [accessReviewScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta) resource. Indicates whether decisions on previous access review stages are available for reviewers in a multi-stage access review.",
```

2022-01-13 15:24 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +               "Description":"Added the **stageSettings** property to the [accessReviewScheduleDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewScheduleDefinition?view=gra
```suggestion
               "Description":"Added the **stageSettings** property to the [accessReviewScheduleDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta) resource. Defines the stages and their settings in a multi-stage access review.",
```

2022-01-13 15:26 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +               "Description":"Added the [accessReviewStageSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewStageSettings?view=graph-rest-beta) resource type.",
```suggestion
               "Description":"Added the [accessReviewStageSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta) resource type. Exposes the properties used to configure stages and their settings in a multi-stage access review.",
```

2022-01-13 15:28 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +               "Description":"Added the [accessReviewStage](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewStage?view=graph-rest-beta) resource type.",
```suggestion
               "Description":"Added the [accessReviewStage](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta) resource type and associated methods. Represents a stage in an [accessReviewInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta).",
```

2022-01-13 15:33 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +            }
These are already catered for by the "and associated methods" statement in the entry for accessReviewStage.

Instead, I recommend that you add entries for the new PATCH, GET, and filterByCurrentUser methods that you've introduced in accessReviewInstanceDecisionItem docs. Unlike the existing methods, these methods act on stages of an accessReviewInstance rather than just the accessReviewInstance.
```suggestion
            }
```

2022-01-13 15:43 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewstage-filterbycurrentuser.md
> +## Optional query parameters
```suggestion
```

2022-01-18 01:47 UTC, opbld32 commented
Docs Build status updates of commit _[da64cf0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da64cf01e0c0dd4860094d832ff556adfe86005a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180144486683-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T01%3A47%3A47Z&sr=b&sp=r&sig=lWNnYT9g04UROHzc3Zla6cJe9CIo6knkRRU%2B%2B4qGvgI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branc [...]

2022-01-18 01:48 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +  "name": "accessreviewinstancedecisionitem_filterbycurrentuser"
```suggestion
  "name": "accessreviewinstancedecisionitem_filterbycurrentuser_2"
```

2022-01-18 01:56 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created se
```suggestion
|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created sequentially based on the dependsOn property. Each stage can have different set of reviewer, fallback reviewers and settings. Only reviewers and fallback reviewers are updatable. See [accessReviewStageSettings](../resources/accessreviewstagesettings.md). Optional.|
```

2022-01-18 02:02 UTC, opbld32 commented
Docs Build status updates of commit _[d99e99b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d99e99be9d46721df2d5b293bd28c698a78f55f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-28e170c7d985b4e9e2b46bdb8f9bf05f-a0a6ca69)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="28e170c7d985b4e9e2b46bdb8f9bf05f-a0a6ca69"></a>
### [api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md)
 - **Line 665, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180200273268 [...]

2022-01-18 02:04 UTC, opbld30 commented
Docs Build status updates of commit _[c3754b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3754b396f9378d29c811b9d5048fb9be27fb3a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180201147235-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T02%3A04%3A31Z&sr=b&sp=r&sig=Jah3Qd%2Bjx785Y5K8WjFzneEcgxUn1Z%2FJPWFEpUZ0RW8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branc [...]

2022-01-18 02:05 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-stop.md
> +description: "Stop a currently active accessReviewStage."
```suggestion
description: "Stop an inProgress accessReviewStage."
```

2022-01-18 02:06 UTC, opbld32 commented
Docs Build status updates of commit _[6fd8146](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fd8146f5f896f544f3bc7bcb2b3dc048a4b896b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-26ace98ebf8d7f6bf86e27ffed17cb3b-9f5523a8)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="26ace98ebf8d7f6bf86e27ffed17cb3b-9f5523a8"></a>
### [api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewstage-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180203557294-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T02%3A06%3A39Z&sr=b&sp=r&sig=lvHzKhfcGEFkAHqk9CyZsszqIWfqQ%2B4mZIs1Tcxu9EQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-tr [...]

2022-01-18 02:11 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-stop.md
> +Stop a currently active [accessReviewStage](../resources/accessReviewStage.md). After the access review stage stops, the stage status will be in `Completed` status and the reviewers can no longer giv
Same comment as in the description above: Recommending that instead of the term "active", we use one of "Initializing", "NotStarted", "Starting", "InProgress", etc which relates to the status value of the status property. Pre-empts Qs.
Q on the impact of this statement: "After the access review stage stops, the stage status will be in Completed status and the reviewers can no longer give input. If there are other stages depend on the completed stage, the next stage will be created."
What is the impact on the decisions nav property? What will be the value of the applyResult, decision etc properties of the decisions nav property?
```suggestion
Stop an inProgress [accessReviewStage](../resources/accessReviewStage.md). After the access review stage stops, the stage status will be `Completed` and the reviewers can no longer give input. If there are subsequent stages that depend on the completed stage, the next stage will be created. 

 The [accessReviewInstanceDecisionItems](../resources/accessreviewinstancedecisionitem.md) objects will always reflect the last decision recorded across all stages at that given time, regardless of the status of the stages.
```

2022-01-18 02:13 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection|The stage settings of an access review series. If a review series has stages, each review instance wil
No error if same reviewer

2022-01-18 02:14 UTC, opbld30 commented
Docs Build status updates of commit _[0b4bd37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b4bd37b02677dd293bf544c3674f7cb1cfce5b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-26ace98ebf8d7f6bf86e27ffed17cb3b-2e7150c1)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="26ace98ebf8d7f6bf86e27ffed17cb3b-2e7150c1"></a>
### [api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewstage-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180212269768-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T02%3A14%3A33Z&sr=b&sp=r&sig=uLwwyzdBpcxUVzJRsoTl5vAIc0FBB6wjCFNl46Bx2fg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-trou [...]

2022-01-18 02:15 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +|[List accessReviewStages](../api/accessreviewstage-list.md)|[accessReviewStage](../resources/accessreviewstage.md) collection|Get a list of the [accessReviewStage](../resources/accessreviewstage.md)
```suggestion
|[List accessReviewStages](../api/accessreviewinstance-list-stages.md)|[accessReviewStage](../resources/accessreviewstage.md) collection|Get a list of the [accessReviewStage](../resources/accessreviewstage.md) objects and their properties.|
```

2022-01-18 02:16 UTC, opbld34 commented
Docs Build status updates of commit _[289c167](https://github.com/microsoftgraph/microsoft-graph-docs/commits/289c167ddba2cce976a40132522e18b6ce916ab9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) | [Details](#user-content-26ace98ebf8d7f6bf86e27ffed17cb3b-02b88138)
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="26ace98ebf8d7f6bf86e27ffed17cb3b-02b88138"></a>
### [api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewstage-list.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180213478516-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T02%3A16%3A31Z&sr=b&sp=r&sig=j0oTHTJd%2B5XZnrrDBc5XHJJJZIsSDy0evtdWuLtcvMY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-tr [...]

2022-01-21 19:15 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +>[!NOTE]
@FaithOmbongi I checked with Kai, and we agree this is in the right place. Per kai, the idea behind this note is to relay that the reviewer can retrieve the decisions from previous stages if the setting is turned on

2022-01-21 19:15 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +>Reviewers can retrieve the decisions from previous stages on the instance if the decisionHistoriesForReviewersEnabled property is enabled in [accessReviewScheduleSettings](../resources/accessreviews
```suggestion
>Reviewers of multi-stage reviews can retrieve the decisions from previous stages on the decsion item if the decisionHistoriesForReviewersEnabled property is enabled in [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md) on the [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md)
```

2022-01-21 19:18 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +PATCH /identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinitionId}/instances/{accessReviewInstanceId}/stages/{accessReviewStageId}/decisions/{accessReviewInstanceDecisionItemId}
```suggestion
PATCH /identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinitionId}/instances/{accessReviewInstanceId}/decisions/{accessReviewInstanceDecisionItemId}
```

2022-01-21 19:19 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +Update a decision from a stage of an accessReviewInstance
```suggestion
Update a decision on a stage of an accessReviewInstance that has multiple stages
```

2022-01-21 19:23 UTC, opbld33 commented
Docs Build status updates of commit _[432f10e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/432f10ed73ce3e96c1203caad622fa30b197429b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-194439ec)

<a id="194439ec"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201211922493854-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T19%3A23%3A57Z&sr=b&sp=r&sig=NAo651QYGsIOiyMAYZSHCP9FJE17cEl3xj1ZQmjChdE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 19:31 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created se
@isabelleatmsft note: stagesettings will overwrite reviewers - note this ARSD-post doc

2022-01-21 20:03 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewset-post-definitions.md
>  | reviewers | [accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection | Defines who the reviewers are. If none are specified, the review is a self-review (users review their
```suggestion
| reviewers | [accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection | Defines who the reviewers are. If none are specified, the review is a self-review (users review their own access).  For examples of options for assigning reviewers, see [Assign reviewers to your access review definition using the Microsoft Graph API](/graph/accessreviews-reviewers-concept). If stageSettings are specified, the contents of this property will be ignored. |
```

2022-01-21 20:03 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewset-post-definitions.md
>  | reviewers | [accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection | Defines who the reviewers are. If none are specified, the review is a self-review (users review their
@FaithOmbongi stageSettings has a reviewers property that overwrites this reviewers property. do you have any suggestions for informing readers of this info?

2022-01-26 21:55 UTC, opbld34 commented
Docs Build status updates of commit _[c34c107](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c34c107cbf54e124bb22cc5b8d33b008ac425a5a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-73ca86bc)

<a id="73ca86bc"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262155100514-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T21%3A55%3A53Z&sr=b&sp=r&sig=%2BMch6d89VfW9oT0oT5M0kqXkvZ74gJwEZTi4Y%2BUdOWU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 21:58 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +PATCH /identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinitionId}/instances/{accessReviewInstanceId}/stages/{accessReviewStageId}/decisions/{accessReviewInstanceDecisionItemId}
I believe the description is correct. We deprecated the "/me" format, but the impact of the API is still the same

2022-01-26 21:58 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-filterbycurrentuser.md
> +## Request headers
@isabelleatmsft fill in the accessreviewstagefilterbycurrentuseroptions and add it to enums file

2022-01-26 22:02 UTC, opbld34 commented
Docs Build status updates of commit _[039fadc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/039fadc2a81f735bd4fb475bc900c63ee8b6f52b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-78ca0466)

<a id="78ca0466"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262202209751-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A02%3A55Z&sr=b&sp=r&sig=ifr72q1fn57nBsINAumpL8%2BFUWCc1qX7ywba7nEU3jE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 22:15 UTC, opbld30 commented
Docs Build status updates of commit _[d10258f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d10258ff374c17818bbb6295cd121d412727551d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c0b485e9)

<a id="c0b485e9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262215151007-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A15%3A57Z&sr=b&sp=r&sig=jK5SP6GgVfvore4jRW0oiZqzGUkbciLoSYcj3DH5dYQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 22:28 UTC, opbld30 commented
Docs Build status updates of commit _[687fa6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/687fa6db21db29b93141fc0634905fa68c3c7420)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-387fc9a8)

<a id="387fc9a8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262227589610-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A28%3A39Z&sr=b&sp=r&sig=VRgkjIzmJl2CXzUXKzrzi7MxFExodH%2Fhvaoy%2F3zeI0o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 22:53 UTC, opbld31 commented
Docs Build status updates of commit _[927ce4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/927ce4cf3ef061efd1406f217a0ee9d3eac36b17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6d03e3ae)

<a id="6d03e3ae"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262252231976-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A52%3A59Z&sr=b&sp=r&sig=dE1f9awbZxVBxyWLv8iq5Ffpbju1u%2FIic%2BXXMVQ%2BhaQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 22:56 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewstage-stop.md
> + The [accessReviewInstanceDecisionItems](../resources/accessreviewinstancedecisionitem.md) objects will always reflect the last decision recorded across all stages at that given time, regardless of t
@FaithOmbongi im trying to answer your question of "what is the impact of decisions on a stage on the overall decision items" with this statement. Does this make sense? Should we add it anywhere else?

An example of what im trying to explain:
3 stage review. For one decision item, it was approved in the first stage (decision item shows approved), unreviewed in the second stage (decision item still shows approved), then denied in the third stage (decision item shows denied  now). when the third stage is stopped, the review instance ends, and the user is denied.

2022-01-26 22:57 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstage.md
> +Every **accessReviewStage** contains a list of [decisions](accessreviewinstancedecisionitem.md) that reviewers can take action on. There is one decision per identity being reviewed.
to answer your Q, here's an example: 
3 stage review. For one decision item, it was approved in the first stage (decision item shows approved), unreviewed in the second stage (decision item still shows approved), then denied in the third stage (decision item shows denied now). when the third stage is stopped, the review instance ends, and the user is denied.

2022-01-26 23:06 UTC, opbld30 commented
Docs Build status updates of commit _[6c491a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c491a4c47b3e16dc190704641204dc7e30fe9b0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0bee3564)

<a id="0bee3564"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262305337035-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A06%3A26Z&sr=b&sp=r&sig=JHy08%2FUIprrFpZCqQquFbAYLcsOng2LgYMDfD1%2FsDgE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:08 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstagesettings.md
> +|fallbackReviewers|[accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection|If provided, the fallback reviewers are asked to complete a review if the primary reviewers do not
Faith:
Please reorder this table by property name in alphabetical order

Missing recommendationInsightSettings property

After reviewing the new example 4 in POST accessReviewScheduleDefinition, I think we need a little more clarity on stageId and dependsOn. From the example, it seems stageId is a number you assign to the stage, and dependsOn indicates the preceding stageId. Trouble is, stageId is a String, leaving room for too much choice.

Can alphabets work? What about decimals?
If only integer numbers are allowed/recommended, please indicate in the description that stageId is a numeric value between 1-3 (or is it 0-2?, 0-3?).
For dependOn, please append examples to illustrate dependency on one stage and sequential order; "For example, "1" or "1", "2"" (please correct this if it's wrong)

2022-01-26 23:08 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstagesettings.md
> +|stageId|String|Unique identifier of the **accessReviewStageSettings**. The stageId will be used in **dependsOn** property to indicate the stage relationship. Required. |
Faith:
Please reorder this table by property name in alphabetical order

Missing recommendationInsightSettings property

After reviewing the new example 4 in POST accessReviewScheduleDefinition, I think we need a little more clarity on stageId and dependsOn. From the example, it seems stageId is a number you assign to the stage, and dependsOn indicates the preceding stageId. Trouble is, stageId is a String, leaving room for too much choice.

Can alphabets work? What about decimals?
If only integer numbers are allowed/recommended, please indicate in the description that stageId is a numeric value between 1-3 (or is it 0-2?, 0-3?).
For dependOn, please append examples to illustrate dependency on one stage and sequential order; "For example, "1" or "1", "2"" (please correct this if it's wrong)

2022-01-26 23:15 UTC, opbld31 commented
Docs Build status updates of commit _[6c491a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c491a4c47b3e16dc190704641204dc7e30fe9b0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-954b7995)

<a id="954b7995"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262315068794-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A15%3A48Z&sr=b&sp=r&sig=I08ewA7FiTquIROR4DRlptlxUebj%2FulIl7NyA6UVGQM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:17 UTC, opbld32 commented
Docs Build status updates of commit _[fd36671](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd36671cde2e219a3d5eae8f21c4d945bc824357)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f92813fc)

<a id="f92813fc"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262317104063-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A17%3A45Z&sr=b&sp=r&sig=0D2GeZwarPy0nHjz79odtwtXafc%2BCh9ruRgteVDS%2Boo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:18 UTC, opbld31 commented
Docs Build status updates of commit _[49e6ac8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49e6ac80048ed44c31851917ab9f4a67527b0333)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-924b48a7)

<a id="924b48a7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262318043049-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A18%3A36Z&sr=b&sp=r&sig=82Awul%2Fx4rfbXl61RYgfXjsTPxP5QR2YWMKMLEWq9sw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:22 UTC, opbld33 commented
Docs Build status updates of commit _[b0a070c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0a070c951aec0634d18855ca70b5f3a1e81e647)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4300c86b)

<a id="4300c86b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262320598426-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A22%3A10Z&sr=b&sp=r&sig=m97T%2B6kvK2vlkZ8pJbH7F1jMrxQFo9Wa6noKP5IApI4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 23:25 UTC, opbld32 commented
Docs Build status updates of commit _[9085d57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9085d574a219d140027158e8642413d10d823776)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bc55e930)

<a id="bc55e930"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262324363374-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A25%3A13Z&sr=b&sp=r&sig=h4dSo7fdz3JsRjF9B%2Ba3M1LZsP%2F0CVHi4ATf26n22FM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 18:15 UTC, opbld30 commented
Docs Build status updates of commit _[512b69c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/512b69caa16a87e0675737fdf65cfc27cb637f1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201271812578095-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T18%3A15%3A32Z&sr=b&sp=r&sig=swBWIijxY%2F5lCzYc0vZ1Y8lLq5ZNDzZ9%2BQSbpdr4M%2Bs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides< [...]

2022-01-28 22:25 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstagesettings.md
> +|dependsOn|String collection|Define the sequential or parallel order of each stageSettings. Only sequential stages are currently supported. Required. |
```suggestion
|dependsOn|String collection|Define the sequential or parallel order of each stageSettings. Only sequential stages are currently supported. For example, if stageId is "2", then dependsOn must be "1". If stageId is "1", do not specify dependsOn. Required. |
```

2022-01-28 22:30 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewstagesettings.md
> +|stageId|String|Unique identifier of the **accessReviewStageSettings**. The stageId will be used in **dependsOn** property to indicate the stage relationship. Required. |
```suggestion
|stageId|String|Unique identifier of the **accessReviewStageSettings**. The stageId will be used in **dependsOn** property to indicate the stage relationship. We recommend using numeric values 1, 2, and 3. Required. |
```

2022-02-01 06:53 UTC, opbld32 commented
Docs Build status updates of commit _[1b99c3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b99c3ad163164e0a1e74d14df47d07440955007)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202010651286718-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T06%3A53%3A33Z&sr=b&sp=r&sig=G1G3tUXcJV3yg53MqgyzQjufmzcMsO6Jc9MDFXA1Qgw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li [...]

2022-02-01 06:55 UTC, opbld34 commented
Docs Build status updates of commit _[1b99c3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b99c3ad163164e0a1e74d14df47d07440955007)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202010651389691-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T06%3A55%3A47Z&sr=b&sp=r&sig=5UlTyG4oCpolHK17MPOCy4CV%2B%2Faffs3X4ET%2FowJw3As%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</ [...]

2022-02-01 10:09 UTC, FaithOmbongi requested changes
Hi @isabelleatmsft, re-reviewed the PR and added a few change suggestions to address your comment about how properties/values in stageSettings override those in the base AR definition + settings property:
- I recommend that for completeness, also update the descriptions of properties that will/might be overridden in the [accessReviewScheduleDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta) and [accessReviewScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta).
- Q: Does the same override also apply to settings/instanceDurationInDays vs stageSettings>durationInDays?

Please remember to add the TOC entry

2022-02-01 21:59 UTC, opbld31 commented
Docs Build status updates of commit _[b01fc70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b01fc70c5b34728d8bbae79d6aa60ebb79c5284f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012157292168-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T21%3A59%3A41Z&sr=b&sp=r&sig=YaQHdO76RW1%2BAOBqCmI2LBkI0%2BsYwCrQmwxUm52ZB4c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a> [...]

2022-02-01 22:22 UTC, opbld33 commented
Docs Build status updates of commit _[25d34cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25d34cc73e2fef4067134dcdf436b50fbca1c2f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012220359973-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T22%3A22%3A47Z&sr=b&sp=r&sig=G6sLy927JHVkYuc%2BqZ1siBfehG0QlxqHkKH9ufsM8gI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></ [...]

2022-02-01 22:35 UTC, opbld30 commented
Docs Build status updates of commit _[074acd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/074acd10fbcd9a36486b5836e25c81efac6cc47c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012231272439-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T22%3A35%3A02Z&sr=b&sp=r&sig=3dwGFr6%2F9xxDISnQ%2FeAvSY2bOo4nmRG%2BLblNtvzrwqc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</ [...]

2022-02-01 22:57 UTC, opbld32 commented
Docs Build status updates of commit _[994781f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/994781f48dd2022a5072dd19d474913d5ca54828)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012254186261-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T22%3A57%3A50Z&sr=b&sp=r&sig=v5%2Fw8R0vp2K7hlpg187hDQG5nIMxbAX7qGoooduiC6c%3D).

**Note:** Broken links written as relative paths are included in the above build rep [...]

2022-02-02 07:51 UTC, opbld31 commented
Docs Build status updates of commit _[1581430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15814305fd2133b1cfe6d77d3677a67de126cae5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202020749304817-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T07%3A51%3A32Z&sr=b&sp=r&sig=LViEkP%2B0YwnXf3EqNw0yhhhbz4CwW1mNJ9RpMm9PL80%3D).

**Note:** Broken links written as relative paths are included in the above build rep [...]

2022-02-02 08:01 UTC, FaithOmbongi approved these changes

2022-02-15 02:49 UTC, opbld34 commented
Docs Build status updates of commit _[c0de99e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0de99ec844135fa39491cba4e476431d27ab43d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150247438241-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T02%3A49%3A45Z&sr=b&sp=r&sig=bn0W3%2BZZB9s3pB0ddbOy9PwDLBeFZ6DwaGFYWQvfasE%3D).

**Note:** Broken links written as relative paths are included in the above build re [...]

2022-02-15 02:51 UTC, opbld34 commented
Docs Build status updates of commit _[c0de99e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0de99ec844135fa39491cba4e476431d27ab43d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150247541430-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T02%3A51%3A55Z&sr=b&sp=r&sig=3P0ZWZinnymRboGdqYaWFr8WleXeri4C4GoG6RqD2uM%3D).

**Note:** Broken links written as relative paths are included in the above build repo [...]

2022-02-15 02:54 UTC, opbld31 commented
Docs Build status updates of commit _[78bf82c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78bf82c7f797695c07a7eba539614f01585ebca0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150251352800-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T02%3A54%3A14Z&sr=b&sp=r&sig=jVboCzaKIXHZEnpR1UVjQke2QsPzm99eNkQdpPjaOy8%3D).

**Note:** Broken links written as relative paths are included in the above build repo [...]

2022-02-15 02:56 UTC, opbld33 commented
Docs Build status updates of commit _[efad86d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efad86d85a424216dbf795443d72f8fd84d6bc07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150253136250-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T02%3A56%3A38Z&sr=b&sp=r&sig=Izgcfpt9HuGzoCMRDaFESxKsTYrbl53YbcEJjnOKOhU%3D).

**Note:** Broken links written as relative paths are included in the above build repo [...]

2022-02-15 03:00 UTC, opbld34 commented
Docs Build status updates of commit _[403ecae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/403ecaece9e2d9118bce5763942a9a83f612748f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150258261722-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T03%3A00%3A30Z&sr=b&sp=r&sig=RqbYloQRkiSqFv0wskmm5CfUAzin%2FLZ1iyFBdRjMt6g%3D).

**Note:** Broken links written as relative paths are included in the above build re [...]

2022-02-15 03:02 UTC, opbld31 commented
Docs Build status updates of commit _[403ecae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/403ecaece9e2d9118bce5763942a9a83f612748f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150258363329-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T03%3A02%3A46Z&sr=b&sp=r&sig=1KfuLxee4%2Fcb6BkRA1C0sURFL88jCi3V2m0aDTbfdsg%3D).

**Note:** Broken links written as relative paths are included in the above build re [...]

2022-02-15 03:05 UTC, opbld32 commented
Docs Build status updates of commit _[00a1ea9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00a1ea9936967555325d3ce0c45f0a49633a47fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150303266431-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T03%3A05%3A38Z&sr=b&sp=r&sig=M%2ByCstiQjbka0mRN87eW1Gwim6inXbkWbfw86dW4Ack%3D).

**Note:** Broken links written as relative paths are included in the above build re [...]

2022-02-15 03:09 UTC, opbld31 commented
Docs Build status updates of commit _[942d24d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/942d24da41267e0a0288ae0ece0317c9c2eb069e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15387) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-12-30-kafen-multi-stage/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150307286534-15387%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T03%3A09%3A34Z&sr=b&sp=r&sig=c1skTSQF3pdBbuRjlH2LsdoVfAS3tJJVywLmbwwtykM%3D).

**Note:** Broken links written as relative paths are included in the above build repo [...]

2022-02-15 03:18 UTC, merged