New concept doc to explain how to build notificationChannelurl
microsoftgraph/microsoft-graph-docs pull request #15385
Opened 2022-01-03 22:59 UTC by cristobal-buenrostro

2022-01-03 23:01 UTC, opbld31 commented
Docs Build status updates of commit _[4d86f5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d86f5bb234e853d12fccec09802f40ce28be48e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201032259173702-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-03T23%3A01%3A34Z&sr=b&sp=r&sig=vAG6ngxWwOvYq%2F5AGkTE2glXo1q55J6r0cHVr8E6464%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-03 23:31 UTC, sharad-sharma-msft requested changes

2022-01-03 23:31 UTC, sharad-sharma-msft commented on concepts/education-build-notificationchannelurl.md
> +# Build notificationChannelUrl property value using the Microsoft Graph API
I would suggest adding the answer to "why". Why does one need this url? what are the use cases?

2022-01-03 23:31 UTC, sharad-sharma-msft commented on concepts/education-build-notificationchannelurl.md
> +Before you can build the property, you must have identified the team for the current **assignment** and the channel name.
will some screenshots here be more helpful?

2022-01-03 23:31 UTC, sharad-sharma-msft commented on concepts/education-build-notificationchannelurl.md
> +You have now successfully built the url, you can set it in any of these calls
set -> consume

2022-01-03 23:31 UTC, sharad-sharma-msft commented on concepts/toc.yml
> +          - name: Build notificationChannelUrl value
value ->property value

2022-01-26 16:18 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +You have now successfully built the url, you can set it in any of these calls
done

2022-01-26 16:19 UTC, cristobal-buenrostro commented on concepts/toc.yml
> +          - name: Build notificationChannelUrl value
done

2022-01-26 16:50 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +# Build notificationChannelUrl property value using the Microsoft Graph API
done

2022-01-26 16:50 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +Before you can build the property, you must have identified the team for the current **assignment** and the channel name.
done

2022-01-26 16:54 UTC, opbld34 commented
Docs Build status updates of commit _[2362a78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2362a78efe7814c5a901da3048dc22f901d294da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261652191076-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T16%3A54%3A41Z&sr=b&sp=r&sig=Cz9c5Rehc%2BByXSEeiDYVggk1HZBKn8ApUWxiWtemuhA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 18:43 UTC, sharad-sharma-msft requested changes

2022-01-26 18:43 UTC, sharad-sharma-msft commented on concepts/education-build-notificationchannelurl.md
> +This article describes how to use the education API in Microsoft Graph to build the `notificationChannelUrl` property for an [educationAssignment](/graph/api/resources/educationassignment).
should you also mention here the data type for this property?

2022-01-26 18:43 UTC, sharad-sharma-msft commented on concepts/education-build-notificationchannelurl.md
> +* [Update educationAssignmentDefaults](/graph/api/educationassignmentdefaults-update)
shall we also include a link to this article in these pages?

2022-01-31 22:59 UTC, isvargasmsft commented on concepts/education-build-notificationchannelurl.md
> +![Identifying team](./images/notificationchannel-team.png)
Please add proper alt text to the images. Please keep in mind users that rely on screen readers.

2022-01-31 23:00 UTC, isvargasmsft commented on concepts/education-build-notificationchannelurl.md
> +## notificationChannelUrl property
I'd suggest a more descriptive title for this header. Something that let's the readers know what is this section about

2022-01-31 23:00 UTC, isvargasmsft commented on concepts/education-build-notificationchannelurl.md
> +### Step 1 - Get teamd id
teamd: is this a typo?

2022-01-31 23:03 UTC, isvargasmsft commented on concepts/education-build-notificationchannelurl.md
> +Make a GET request with the team name.
Please provide a better description for the step. Explain the goal of the step (get the team id) and how to achieve it (using a GET request with filter by name). Add a clarification to the user: if you already have the team id, you can skip this step.

2022-01-31 23:04 UTC, isvargasmsft commented on concepts/education-build-notificationchannelurl.md
> +Make a GET request with the team name.
Apply this to the step 2 as well.

2022-01-31 23:08 UTC, isvargasmsft commented on concepts/education-build-notificationchannelurl.md
> +```
This step is not clear. How does the developer construct the property?

2022-01-31 23:14 UTC, isvargasmsft requested changes
Please provide better descriptions to the steps. Put yourself in the shoes of a developer who is starting with Graph.

2022-02-01 20:56 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +This article describes how to use the education API in Microsoft Graph to build the `notificationChannelUrl` property for an [educationAssignment](/graph/api/resources/educationassignment).
done

2022-02-01 20:57 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +![Identifying team](./images/notificationchannel-team.png)
done

2022-02-01 20:57 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +### Step 1 - Get teamd id
done

2022-02-01 20:57 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +Make a GET request with the team name.
done

2022-02-01 20:58 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +```
it is crystal clear =s

it is just to replace the placeholders with the values obtained in previous calls, the table gives details on that.
I just changed a bit the paragraph format to make it more understandable.

2022-02-01 20:59 UTC, opbld31 commented
Docs Build status updates of commit _[7030f9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7030f9a4231d21a8dd8c1c8c982e086bccda56a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012056117035-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T20%3A59%3A54Z&sr=b&sp=r&sig=sZBpnwKCiP2gBKL1fiI8knlm7RwEj9WuBgGdvbptSsY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 21:01 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +## notificationChannelUrl property
done

2022-02-01 21:03 UTC, opbld33 commented
Docs Build status updates of commit _[66a571c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66a571c20392b0410b4b0e766c6dfad31437d3c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012101194694-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T21%3A03%3A28Z&sr=b&sp=r&sig=CNyU1nUb9c00pUbTEzJnBn1lQ1r3M6zAwMTZCC2HWuw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 21:12 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +* [Update educationAssignmentDefaults](/graph/api/educationassignmentdefaults-update)
good idea, done

2022-02-01 21:14 UTC, opbld33 commented
Docs Build status updates of commit _[fe1ab0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe1ab0e155f2ed3981b6d6f0b198824d77931a59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012112190467-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T21%3A14%3A20Z&sr=b&sp=r&sig=yFpEX8jGcKEU%2BANr%2FlGlDUW8RdJRNN1yIgnVWL9BYQ0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 21:30 UTC, sharad-sharma-msft approved these changes

2022-02-04 15:51 UTC, opbld34 commented
Docs Build status updates of commit _[f7d4e6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7d4e6f88807c1a34b9586a8eb3230b147832b40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202041543532579-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T15%3A51%3A40Z&sr=b&sp=r&sig=NwZzZuq9xbLrMhvhkhF73qlLUAik%2FaA%2FPWGd1la9W6k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 16:47 UTC, opbld33 commented
Docs Build status updates of commit _[32cefa8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32cefa8975ed8ab93c30fb63e0906b865f331531)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202041643418208-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T16%3A47%3A03Z&sr=b&sp=r&sig=brJiV%2FiTDbLsFIpML4CUTe9NWMOKueOp5FJ3fk0oO%2FM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 16:53 UTC, opbld31 commented
Docs Build status updates of commit _[171e23b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/171e23b8c54483f8647353b7f3775c7ae73e0b8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202041651163481-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T16%3A53%3A19Z&sr=b&sp=r&sig=r7Enmo%2FkSrt6treNy8qGviQ%2FTYiUzWv%2FBpxO%2B1l4LPU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 18:00 UTC, opbld33 commented
Docs Build status updates of commit _[b4db83a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4db83a1a615917e40982e5b657c95c263666d47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-2962f993)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-2962f993)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-2962f993)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-70d8230b1c27deb48a93504ab2e36495-2962f993)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-382c17fcce2c98c9ebb5ad3b6cac0dfe-2962f993)
[api-reference/beta/api/connectorgroup-post-connectorgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/connectorgroup-post-connectorgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-connectorgroups?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-7b96b57a0f9252ab27f0a53dc6d112d5-2962f993)
[api-reference/beta/api/connectorgroup-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/connectorgroup-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-9e07aab7b660fda52d94dc5b63fcb717-2962f993)
[api-reference/beta/api/contactfolder-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/contactfolder-post-contacts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactfolder-post-contacts?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-1523fc41a65661e2bcac193087f5180f-2962f993)
[api-reference/beta/api/educationroot-list-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationroot-list-users.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationroot-list-users?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-bff84ec24c45ed47392d322d4e7c76f0-2962f993)
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/event-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-99ac693d69098ffe5f947fc89879ad01-2962f993)
[api-reference/beta/api/get-device-command-status.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/get-device-command-status.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/get-device-command-status?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-83d1e4946001029d2406b1afd2bf46fa-2962f993)
[api-reference/beta/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/group-list-transitivemembers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-95a8b458c832e094c1236ff15a13aa90-2962f993)
[api-reference/beta/api/inferenceclassification-list-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassification-list-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-list-overrides?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-45e2e3913062b41f99c426a76f7b7d62-2962f993)
[api-reference/beta/api/inferenceclassification-post-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassification-post-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-post-overrides?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-b5c664a0e2d7a4de57531ca383a16063-2962f993)
[api-reference/beta/api/inferenceclassificationoverride-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassificationoverride-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-delete?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-2bdbefd2975a8106864bd5338894a864-2962f993)
[api-reference/beta/api/inferenceclassificationoverride-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassificationoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-d777505cacf8f7b07c21de712111275b-2962f993)
[api-reference/beta/api/intune-shared-devicemanagementscript-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/intune-shared-devicemanagementscript-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementscript-create?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-13e7e74f2ffdf12b33398628f58be59d-2962f993)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdev [...]

2022-02-04 18:19 UTC, opbld30 commented
Docs Build status updates of commit _[2231f11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2231f113768fd925c0d4ce1ab678e0b49bb9ff90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-38eb28c8)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-38eb28c8)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-38eb28c8)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-70d8230b1c27deb48a93504ab2e36495-38eb28c8)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-382c17fcce2c98c9ebb5ad3b6cac0dfe-38eb28c8)
[api-reference/beta/api/connectorgroup-post-connectorgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/connectorgroup-post-connectorgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-connectorgroups?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-7b96b57a0f9252ab27f0a53dc6d112d5-38eb28c8)
[api-reference/beta/api/connectorgroup-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/connectorgroup-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-9e07aab7b660fda52d94dc5b63fcb717-38eb28c8)
[api-reference/beta/api/contactfolder-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/contactfolder-post-contacts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactfolder-post-contacts?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-1523fc41a65661e2bcac193087f5180f-38eb28c8)
[api-reference/beta/api/educationroot-list-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationroot-list-users.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationroot-list-users?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-bff84ec24c45ed47392d322d4e7c76f0-38eb28c8)
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/event-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-99ac693d69098ffe5f947fc89879ad01-38eb28c8)
[api-reference/beta/api/get-device-command-status.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/get-device-command-status.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/get-device-command-status?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-83d1e4946001029d2406b1afd2bf46fa-38eb28c8)
[api-reference/beta/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/group-list-transitivemembers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-95a8b458c832e094c1236ff15a13aa90-38eb28c8)
[api-reference/beta/api/inferenceclassification-list-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassification-list-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-list-overrides?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-45e2e3913062b41f99c426a76f7b7d62-38eb28c8)
[api-reference/beta/api/inferenceclassification-post-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassification-post-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-post-overrides?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-b5c664a0e2d7a4de57531ca383a16063-38eb28c8)
[api-reference/beta/api/inferenceclassificationoverride-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassificationoverride-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-delete?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-2bdbefd2975a8106864bd5338894a864-38eb28c8)
[api-reference/beta/api/inferenceclassificationoverride-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassificationoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-d777505cacf8f7b07c21de712111275b-38eb28c8)
[api-reference/beta/api/intune-shared-devicemanagementscript-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/intune-shared-devicemanagementscript-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementscript-create?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-13e7e74f2ffdf12b33398628f58be59d-38eb28c8)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdev [...]

2022-02-04 18:24 UTC, opbld33 commented
Docs Build status updates of commit _[75ee258](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75ee25812c08e25ae68910fb824370115f19fda5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-c5ebc643)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-c5ebc643)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-c5ebc643)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-70d8230b1c27deb48a93504ab2e36495-c5ebc643)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-382c17fcce2c98c9ebb5ad3b6cac0dfe-c5ebc643)
[api-reference/beta/api/connectorgroup-post-connectorgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/connectorgroup-post-connectorgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-connectorgroups?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-7b96b57a0f9252ab27f0a53dc6d112d5-c5ebc643)
[api-reference/beta/api/connectorgroup-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/connectorgroup-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-9e07aab7b660fda52d94dc5b63fcb717-c5ebc643)
[api-reference/beta/api/contactfolder-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/contactfolder-post-contacts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactfolder-post-contacts?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-1523fc41a65661e2bcac193087f5180f-c5ebc643)
[api-reference/beta/api/educationroot-list-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationroot-list-users.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationroot-list-users?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-bff84ec24c45ed47392d322d4e7c76f0-c5ebc643)
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/event-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-99ac693d69098ffe5f947fc89879ad01-c5ebc643)
[api-reference/beta/api/get-device-command-status.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/get-device-command-status.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/get-device-command-status?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-83d1e4946001029d2406b1afd2bf46fa-c5ebc643)
[api-reference/beta/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/group-list-transitivemembers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-95a8b458c832e094c1236ff15a13aa90-c5ebc643)
[api-reference/beta/api/inferenceclassification-list-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassification-list-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-list-overrides?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-45e2e3913062b41f99c426a76f7b7d62-c5ebc643)
[api-reference/beta/api/inferenceclassification-post-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassification-post-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-post-overrides?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-b5c664a0e2d7a4de57531ca383a16063-c5ebc643)
[api-reference/beta/api/inferenceclassificationoverride-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassificationoverride-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-delete?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-2bdbefd2975a8106864bd5338894a864-c5ebc643)
[api-reference/beta/api/inferenceclassificationoverride-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/inferenceclassificationoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-d777505cacf8f7b07c21de712111275b-c5ebc643)
[api-reference/beta/api/intune-shared-devicemanagementscript-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/intune-shared-devicemanagementscript-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementscript-create?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) | [Details](#user-content-13e7e74f2ffdf12b33398628f58be59d-c5ebc643)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdev [...]

2022-02-04 18:32 UTC, opbld33 commented
Docs Build status updates of commit _[fe1ab0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe1ab0e155f2ed3981b6d6f0b198824d77931a59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202041828142901-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T18%3A32%3A18Z&sr=b&sp=r&sig=qu3Un848J%2F23zpJdrcLJtoY2xaZb7ZhDe5dIX%2BgVlAQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 18:36 UTC, opbld30 commented
Docs Build status updates of commit _[854d93c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/854d93c19b7fbc52f9be9e4ecba24159ee61285c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202041831109874-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T18%3A36%3A34Z&sr=b&sp=r&sig=dtzdVCNGQnzEhQVzikd31Tros0O1vbJ2OclBAKe5EII%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 19:47 UTC, opbld31 commented
Docs Build status updates of commit _[fb00479](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb004790acec6a8351a5db169afc8230f34f727a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202041945033442-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T19%3A47%3A10Z&sr=b&sp=r&sig=9aNhJ%2FbuY9L1BNdvUC2iYboNOlHsaU%2B99J2OY9fn8gQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 20:43 UTC, opbld34 commented
Docs Build status updates of commit _[d898bbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d898bbfd0e8c6dfc8837d79332298068cbb4ca42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202042040583761-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T20%3A43%3A07Z&sr=b&sp=r&sig=sLSzcsukpkeAhhrmyGFpVe9v58XbYXC%2Fcw%2BTldVSk%2BM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 20:54 UTC, opbld34 commented
Docs Build status updates of commit _[829a621](https://github.com/microsoftgraph/microsoft-graph-docs/commits/829a621c3491e7b0915c76093f6566abfbf0a537)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202042050369906-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T20%3A54%3A38Z&sr=b&sp=r&sig=nwHHx0b4FGLOk%2BptELm3PasksK3KPWMYAUXnZ%2Fl9xZs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 20:58 UTC, isvargasmsft approved these changes

2022-02-05 02:30 UTC, Lauragra commented on concepts/education-build-notificationchannelurl.md
> +# Build notificationChannelUrl for an education assignment using the Microsoft Graph API
Can we update the title to more clearly reflect the action that the user can accomplish? For example, "Specify the default channel for education assignment notifications using the Microsoft Graph API"

2022-02-05 02:31 UTC, Lauragra commented on concepts/education-build-notificationchannelurl.md
> +### Step 1 - Get the team id based on your team name
Please change id to ID when you're referring to an identifier and not specifically an **id** property.

2022-02-05 02:40 UTC, Lauragra commented on concepts/education-build-notificationchannelurl.md
> +You have now successfully built the url, it's time to assign the value to the property. You can perform this operation by updating either the **educationAssignment** or **educationAssignmentDefaults*
Please revise the first sentence to be two separate sentences and capitalize url: "You have now successfully built the URL. It's time to assign the value to the property."

2022-02-05 02:40 UTC, Lauragra commented on concepts/toc.yml
> +          - name: Build notificationChannelUrl property value
Update the TOC entry to reflect the update to the topic title.

2022-02-05 02:44 UTC, Lauragra commented on concepts/education-build-notificationchannelurl.md
> +### Pre-requisite 1: Identify the team
I don't know that we need subheadings here; they take a lot of vertical space in the article. Please change this to a sentence. Please also use text in addition to the illustration with alt text to explain the step. Suggested text to replace the H3 heading: "To identify the team for the assignment, in the left menu in Teams, click **Teams** and then select the appropriate team."

2022-02-05 02:44 UTC, Lauragra commented on concepts/education-build-notificationchannelurl.md
> +Before building the property, identify the corresponding team for the **assignment** and the name of the channel.
I think you're just referring to the assignment here, not the resource type, so please remove the bold formatting.

2022-02-05 02:45 UTC, Lauragra commented on concepts/education-build-notificationchannelurl.md
> +### Pre-requisite 2: Identify the channel
Replace the heading with: "Identify the appropriate channel within the team that you selected."

2022-02-05 02:58 UTC, opbld32 commented
Docs Build status updates of commit _[f9906fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9906fcb0c9699ef4e3a705c5d88721098dc3ac6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202050256444031-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-08T02%3A58%3A56Z&sr=b&sp=r&sig=08gXF8bBnAuwGMUb2%2FUFXuJ7qR6ZRYB4SPMTvoNprLk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 23:48 UTC, opbld34 commented
Docs Build status updates of commit _[cd99d03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd99d03321524f4d84efbe50940ef55d590e1b9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202072346372078-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T23%3A48%3A39Z&sr=b&sp=r&sig=tIv2F9iYPCApVW3a%2FASEYxhZHX%2FoEBHGW7FIM1aPYd8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 00:36 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +# Build notificationChannelUrl for an education assignment using the Microsoft Graph API
done

2022-02-08 00:36 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +### Step 1 - Get the team id based on your team name
done

2022-02-08 00:36 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +You have now successfully built the url, it's time to assign the value to the property. You can perform this operation by updating either the **educationAssignment** or **educationAssignmentDefaults*
done

2022-02-08 00:36 UTC, cristobal-buenrostro commented on concepts/toc.yml
> +          - name: Build notificationChannelUrl property value
done

2022-02-08 00:37 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +### Pre-requisite 1: Identify the team
done

2022-02-08 00:37 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +Before building the property, identify the corresponding team for the **assignment** and the name of the channel.
done

2022-02-08 00:37 UTC, cristobal-buenrostro commented on concepts/education-build-notificationchannelurl.md
> +### Pre-requisite 2: Identify the channel
done

2022-02-08 02:57 UTC, opbld34 commented
Docs Build status updates of commit _[4f84c0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f84c0f7d6c728a5fcfb8810d95be1d289b00d78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202080255495049-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T02%3A57%3A50Z&sr=b&sp=r&sig=ZDNHYor6oBp0rpOjuCV4CxkD%2Ff3Y0AQ5Qj5K%2BJtmnAs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 03:00 UTC, opbld32 commented
Docs Build status updates of commit _[6cd8992](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cd8992d65d4806697a03e8ca5caad5393c55848)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202080256305811-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T03%3A00%3A07Z&sr=b&sp=r&sig=W1Q%2FJAv0BuHksHbuTEv7dnC1kzRVIC3TsKSK9oOKLjM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 03:02 UTC, opbld33 commented
Docs Build status updates of commit _[0229ee6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0229ee6b059bcdcd8535d82792be6a70a329f7c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202080258011450-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T03%3A02%3A10Z&sr=b&sp=r&sig=xLHTneOHY9GEGqvzSC0I%2BHypFfaAUvt3zUI74Nauf9Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[ba13ed6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba13ed6734a4b71e9df30b5cba6bc408020dc223)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/beta/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-beta&branch=pr-en-us-15385) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-15385) (>= graph-rest-1.0) |
[concepts/education-build-notificationchannelurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/education-build-notificationchannelurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-channel.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-channel.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/images/notificationchannel-team.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/images/notificationchannel-team.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/channelurl/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-build-notificationchannelurl?branch=pr-en-us-15385) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202080302147677-15385%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T03%3A04%3A23Z&sr=b&sp=r&sig=sJleVfejCSGDVDG8ARK6F%2FQAmlJlAdPn5Au9PfxpGAc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 03:07 UTC, merged