Adding OrderBy Query Option to Chat.GetMessages Requests
microsoftgraph/microsoft-graph-docs pull request #15398
Opened 2022-01-04 21:09 UTC by evanypark

Updating Documentations/Change logs for Enabling new Query Option, OrderBy, when handling Chat.GetMessages Requests.
Users will be allowed to sort chat messages in order of LastModifiedDateTime or CreatedDateTime.

2022-01-04 21:11 UTC, opbld31 commented
Docs Build status updates of commit _[4bdca01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bdca018da09894a9e9c268cc11319c538b1b931)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/v1.0/api/chat-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-15398) (>= graph-rest-1.0) | [Details](#user-content-1bd5f81a241c931f71ff5e76c235cb09-2845cdfc)
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="1bd5f81a241c931f71ff5e76c235cb09-2845cdfc"></a>
### [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/v1.0/api/chat-list-messages.md)
 - **Line 243, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042109236075-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T21%3A11%3A38Z&sr=b&sp=r&sig=8nSf%2Bdh2VXU7tWj6zmC5qYgTVHY%2BQWkB4U3ru47bd0Y%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 22:03 UTC, sumanac commented on api-reference/beta/api/chat-list-messages.md
> +| [$top](/graph/query-parameters#top-parameter)      | Control the number of items per response. Maximum allowed `$top` value is 50.  |
Controls?

2022-01-04 23:02 UTC, opbld30 commented
Docs Build status updates of commit _[97f42e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97f42e067a6cd066260e3842411603386bb45cd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/v1.0/api/chat-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-15398) (>= graph-rest-1.0) | [Details](#user-content-1bd5f81a241c931f71ff5e76c235cb09-0b319d67)
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="1bd5f81a241c931f71ff5e76c235cb09-0b319d67"></a>
### [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/v1.0/api/chat-list-messages.md)
 - **Line 243, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201042300040959-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T23%3A02%3A01Z&sr=b&sp=r&sig=J%2B7imfN4PIqK2KHnyiAPZ9NqvnddMLLYC1hyAaezqN0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 00:43 UTC, eddie-lee-msft commented
Can you add an example (or two) of using the new OrderBy query option?

2022-01-05 00:46 UTC, eddie-lee-msft requested changes

2022-01-05 00:46 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-list-messages.md
> +| [$orderBy](/graph/query-parameters#orderBy)  | Currently supports **LastModifiedDateTime** and **CreatedDateTime**.|
Can you add an example (or two) of using the new OrderBy query option? Here and in the v1.0 doc.

2022-01-05 03:23 UTC, RamjotSingh requested changes

2022-01-05 03:23 UTC, RamjotSingh commented on api-reference/v1.0/api/chat-list-messages.md
> +
Let's remove v1 for now. Let's first ensure API is stable in beta and then move it to v1

2022-01-05 05:44 UTC, evanypark commented on api-reference/beta/api/chat-list-messages.md
> +| [$orderBy](/graph/query-parameters#orderBy)  | Currently supports **LastModifiedDateTime** and **CreatedDateTime**.|
Added orderBy query parameter to the sample below

2022-01-05 05:47 UTC, opbld30 commented
Docs Build status updates of commit _[da7a37d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da7a37dc542a01025f001ac836b1418cb37988cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/v1.0/api/chat-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-15398) (>= graph-rest-1.0) | [Details](#user-content-1bd5f81a241c931f71ff5e76c235cb09-e03ca846)
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="1bd5f81a241c931f71ff5e76c235cb09-e03ca846"></a>
### [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/v1.0/api/chat-list-messages.md)
 - **Line 243, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050545251024-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T05%3A47%3A40Z&sr=b&sp=r&sig=m6n%2F2DTCKU5ZH1MI5NhtVAu61Ys%2BCqqCoXDgpAlp68g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 05:54 UTC, opbld31 commented
Docs Build status updates of commit _[9790b05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9790b05b9c01a6b0deee5f2fe573378aadbf1167)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050552038818-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T05%3A54%3A06Z&sr=b&sp=r&sig=eVqrML5P7aj4ZqwE1vWgFJ9NK0Pp2lIPvdh1zpreghA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 23:04 UTC, eddie-lee-msft approved these changes

2022-01-06 02:39 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "OrderBy",
ChangedApiName is prob going to be chatMessage and ApiChange is not property def. @Lauragra might be able to suggest correct stuff to put here.

2022-01-06 02:39 UTC, RamjotSingh approved these changes

2022-01-12 00:44 UTC, opbld33 commented
Docs Build status updates of commit _[874e559](https://github.com/microsoftgraph/microsoft-graph-docs/commits/874e5596cd6231df7ff99dd4b276696c7a664754)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201120041425844-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T00%3A44%3A23Z&sr=b&sp=r&sig=fXaly5dnZNMVX6yEydkLi8vIzj7mHiFYWW4cqTuUdsc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 02:41 UTC, Lauragra commented on api-reference/beta/api/chat-list-messages.md
> -You can use the [$top](/graph/query-parameters#top-parameter) query parameter to control the number of items per response. Maximum allowed `$top` value is 50.
Please add an introductory sentence here: "This method supports the following [OData query parameters](/graph/query-parameters)."

2022-01-12 17:31 UTC, opbld31 commented
Docs Build status updates of commit _[64d5e3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64d5e3af5693b61fa77ab7934ca9b16725b17be4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201121729163507-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T17%3A31%3A13Z&sr=b&sp=r&sig=LIcCfCHbvVv7vCtfw6DOonoeN2jOhtd1hwlIVyT3Zdo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 19:12 UTC, Lauragra commented on api-reference/beta/api/chat-list-messages.md
> +GET https://graph.microsoft.com/v1.0/chats/19:2da4c29f6d7041eca70b638b43d45437@thread.v2/messages?$top=2&$orderBy=createdDateTime
Why did we change the example from beta to v1.0? This topic is in the beta folder so it should be using /beta in the query URL.

2022-01-12 19:25 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "queryOption",
For this value, I think you want to use "Parameter".

2022-01-12 19:27 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "chatMessage",
This would be the verb, in this case LIST.

2022-01-12 19:28 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "chat"
The target is chatMessage.

2022-01-12 19:32 UTC, opbld30 commented
Docs Build status updates of commit _[da3fe9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da3fe9a5eac217ca3730b18fa2070c9f32b44db7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201121929236427-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T19%3A32%3A11Z&sr=b&sp=r&sig=DwJNqWnvcOjldImOYVBS4%2F80IkvCbfXascaXxR4q5l0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 20:02 UTC, opbld34 commented
Docs Build status updates of commit _[a9b946f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9b946f9c97e0ad69ea7f45a177d42c7a589e996)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-15398) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2021-01-04-Chat-Message-OrderBy/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201122000559455-15398%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T20%3A02%3A53Z&sr=b&sp=r&sig=47n1uaTDCuAVCjepy3ZTZG%2BYhZ5%2Bjz%2BDmj6nLKyASxA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 20:05 UTC, Lauragra approved these changes

2022-01-13 01:48 UTC, merged