Adding ContactMergeSuggestion User Privacy setting to contact merge suggestion feature
microsoftgraph/microsoft-graph-docs pull request #15392
Opened 2022-01-04 09:44 UTC by jagadeesh-vadivel

2022-01-04 09:47 UTC, opbld30 commented
Docs Build status updates of commit _[3a95a65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a95a65f173930a4da4e54f82aa6ebd114935e23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040944477519-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T09%3A47%3A51Z&sr=b&sp=r&sig=X01pUNoHvKu2GDuOsSuAg6t6OLLWJTq7M4t6YdK8Ht0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 10:00 UTC, opbld33 commented
Docs Build status updates of commit _[2341e20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2341e20e3f19a48a2cd855bced63474300b7f279)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040957520391-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T10%3A00%3A55Z&sr=b&sp=r&sig=JsWxPOHDuEPqz1S0pFbDkgKE19KvxF7r%2FWXOJwtnG4g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 10:14 UTC, opbld30 commented
Docs Build status updates of commit _[4e55706](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e55706e73370eb59c9580bc824b601399d857e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201041011356411-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T10%3A14%3A33Z&sr=b&sp=r&sig=BqjjCE1eOmR2FMIA%2BMtBMKLFN55PlGqBoQc8QtF0Afs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 09:51 UTC, opbld30 commented
Docs Build status updates of commit _[02c275f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02c275f5c63bc991560574e8800034e2d19d3a1f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bb5c8b18)
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-bb5c8b18"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml)
 - **Line 343, Column 15**: **[Warning: missing-attribute]** `````Missing required attribute: 'name'.`````
 - **Line 12515, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050948159919-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T09%3A51%3A08Z&sr=b&sp=r&sig=wROOY3D7LBKsglDr4%2F4CdkPGN6nne%2FkdShRNElszUyg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 09:55 UTC, opbld33 commented
Docs Build status updates of commit _[14b5c6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14b5c6b6a7bc853c382750291521998972a0ee48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-45300c65)
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-45300c65"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml)
 - **Line 12515, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050953138530-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T09%3A55%3A29Z&sr=b&sp=r&sig=iP89Ln3%2BJRZ8t4D5999LLzUoB8x7453m1vjkbhx6mOM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 20:49 UTC, Danielabom commented on api-reference/beta/resources/contactmergesuggestions.md
> +|isEnabled|Boolean|'true' if duplicate contact merge suggestions feature is enabled for user; 'false' if duplicate contact merge suggestions feature is disabled. Default is 'true'.|
Please enclose the values true and false in tick marks ``. Ex: `true`, `false`.

2022-01-07 21:14 UTC, Danielabom commented on api-reference/beta/api/contactmergesuggestions-update.md
> +```
The response section in this topic indicates that this method should return a 200 ok response  plus a contactMergeSuggestions object in the response body. 
Would you mind reviewing this example?

2022-01-07 21:22 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Added the **contactMergeSuggestions** relationship to the [userSettings](https://docs.microsoft.com/en-us/graph/api/resources/userSettings?view=graph-rest-beta) resource.",
I noticed that we are adding a new nav property to the userSettings resource type. This requires adding it to the relationships table of the userSettings resource topic and probably we should also add it to all the Get, Update and other operations that return a userSettings object in the response body.

2022-01-07 21:29 UTC, Danielabom commented on api-reference/beta/resources/contactmergesuggestions.md
> +Use this resource to disable / enable the duplicate contacts merge suggestions.
Descriptions in lines 3 and 16: Please consider the following:
* These two sentences should match,
* Please note these descriptions are used by search engines to display results. Please rewrite the description in a way that you would Bing it. 
Ping me aside if you need any assistance.

2022-01-07 21:30 UTC, Danielabom requested changes
Hello, thank you for working on this PR. 

Please review some comments regarding completeness and feel free to contact me if you have any questions. 

Kind regards,
Dani

2022-01-11 16:06 UTC, opbld32 commented
Docs Build status updates of commit _[57d9bdc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57d9bdcddb86fdefe4e9c63e4c5840b6633b5575)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201111604284667-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T16%3A06%3A28Z&sr=b&sp=r&sig=pLb17DxAQaihWGYlg2zeAQRwWpwmke8OHwVz7IIyXx0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 16:17 UTC, jagadeesh-vadivel commented on api-reference/beta/api/contactmergesuggestions-update.md
> +```
204 is the correct respone. Updated the response body. Thank you for pointing out.

2022-01-11 16:22 UTC, opbld31 commented
Docs Build status updates of commit _[859fe07](https://github.com/microsoftgraph/microsoft-graph-docs/commits/859fe072546131abb92b58be1c9e17ad5843c1c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201111620429845-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T16%3A22%3A57Z&sr=b&sp=r&sig=eTUJmyDVRN39E34vXg%2B2WqxVCPPICXafBHTeFk1fDyw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 16:34 UTC, jagadeesh-vadivel commented on api-reference/beta/resources/contactmergesuggestions.md
> +Use this resource to disable / enable the duplicate contacts merge suggestions.
Updated the lines 3 and 16 so that they both match. I have rewritten the description to the best of my knowledge. Please do feel free to provide any suggestion on the same. And I will update it accordingly.

2022-01-11 16:37 UTC, jagadeesh-vadivel commented on api-reference/beta/resources/contactmergesuggestions.md
> +|isEnabled|Boolean|'true' if duplicate contact merge suggestions feature is enabled for user; 'false' if duplicate contact merge suggestions feature is disabled. Default is 'true'.|
Thanks for pointing it out. I have update the ' to ` as suggested.

2022-01-11 16:39 UTC, jagadeesh-vadivel commented
@Danielabom Thanks a lot for taking the time and reviewing the changes. This is great help. I have addressed your comments and updated the PR. 
It would be great if you could review the latest changes whenever possible. If there are more comments. I will reach out offline as suggested to close on the changes. :)

2022-01-11 21:00 UTC, opbld31 commented
Docs Build status updates of commit _[c89a4d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c89a4d4d44e5b15bb7fc5523efc74b0e8a3cc2be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201112058229121-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T21%3A00%3A18Z&sr=b&sp=r&sig=vmCDbK5lw4WzrIFii7K%2FTNCVXAvY38jYyBn2UIhLAiA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 15:29 UTC, opbld34 commented
Docs Build status updates of commit _[31e08bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31e08bcd0d190e12e4126ac463547e08fed91c42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131527188070-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T15%3A29%3A07Z&sr=b&sp=r&sig=0gS%2BPs%2Fc2Rjy3unRNIeow5tVt1eLi7f%2F3BBo4MPY%2Flo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 16:46 UTC, Danielabom approved these changes
Thank you for addressing my comments. The PR is in good shape to me.

2022-01-21 02:29 UTC, opbld31 commented
Docs Build status updates of commit _[29907f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29907f675119ca370b6c3b9b133b1bbdac777c2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210226270892-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T02%3A28%3A59Z&sr=b&sp=r&sig=tco3Pa3C8%2BiSjMOo8GpQaSIWb%2FJY9zxzGN%2Bq23pZigs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 17:28 UTC, Danielabom approved these changes

2022-02-03 04:21 UTC, opbld34 commented
Docs Build status updates of commit _[3ef4abb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ef4abb980654b54c32af6b12d805351a6551078)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202030419076428-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T04%3A21%3A35Z&sr=b&sp=r&sig=5nMJCg4nKtHVRFhmUsBcFYSJtqjyyVJkR%2Fn6QoGPZX8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 04:23 UTC, opbld32 commented
Docs Build status updates of commit _[b3a2d36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3a2d36da60e2c6161cf813dc14e6fdecf18fcfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202030421327074-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T04%3A23%3A51Z&sr=b&sp=r&sig=UlP5ENEuchw4UIQFcI0bP1IJU6sJ5hdZuXWg505ayeo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 04:46 UTC, opbld30 commented
Docs Build status updates of commit _[74443b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74443b28e882a904846d594cd02c924dd0a45a4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202030440174482-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T04%3A46%3A19Z&sr=b&sp=r&sig=yJ0vuYIRcxVaB8J6kU%2FDtx%2BvB%2B%2Bi5tuhVpWrKYiJ4fQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 04:52 UTC, opbld33 commented
Docs Build status updates of commit _[66fa903](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66fa9034e17589d54569f74ac9391ccd88823c56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202030444303038-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T04%3A52%3A55Z&sr=b&sp=r&sig=52KWL4oQDaNppkBFmJIE5eU8tx7Gy9uE5KFF5RxaPGk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 04:52 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Merge duplicate contacts
I don't think that we have the right TOC structure here. Is this where we should be exposing this feature? Or should it be surfaced here perhaps, since this appears to be a user setting? https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392

I also think that we have too many levels. I suggest we have a node for the resource with the operations surfaced beneath, so:

Contact merge suggestions
     Get
     Update

2022-02-03 04:55 UTC, Lauragra commented on changelog/Microsoft.People.json
> +			"WorkloadArea": "People and workplace intelligence",
Please clarify the workloadArea and SubArea. Is this API related to People and workplace intelligence? We seem to be surfacing it under Users in the TOC. The new topics are using the "outlook" value which doesn't align. I think we want to use "users" for ms.prod and for the WorkloadArea. 

If this is a People and Workplace intelligence API, this should we be surfacing it in that node, as a peer of this topic? https://docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta

2022-02-03 04:59 UTC, Lauragra commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
Please see my comment on the changelog file. The ms.prod value and the WorkloadArea values should correspond. We use service names (i.e. mail, contacts) rather than product names for ms.prod. For details, please see this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211756/Metadata.

2022-02-04 14:29 UTC, jagadeesh-vadivel commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
Hi @Lauragra 
Thanks a lot for pointing this out. 
We went through the pointed out metadata wiki. And as this feature revolves around user's personal contact list, We feel that personal-contacts could be the right service and ms.prod for this feature. And we also suggest to move the above nodes in TOC to "Personal Contacts" section. 
But before doing the above changes, we would like to know your comments on our proposed changes and whether its the right direction to move forward.
Kindly let us know if any other information is needed.

2022-02-09 00:26 UTC, angelgolfer-ms commented on api-reference/beta/resources/contactmergesuggestions.md
> +
Line 16:
We've got 5 nouns in a row - "duplicate contact merge suggestions feature". Loc will definitely find this challenging. Typically we don't want to have 3 nouns or more in a row. 
Also, your description just repeated the same 3 words in the same order as the resource name - "contact merge suggestions".  Customers unfamiliar with that feature would need a more helpful description.

May I suggest to rephrase this description to make the feature clearer? Heads-up: there are aspects I need your confirmation though.
"Represents the feature to suggest merging contact items when Outlook detects duplicates in the user's default contacts folder. 
Users have the option to enable or disable the feature in the privacy settings for Outlook. By default, suggestion is enabled. Duplicate contact items remain as such unless the user selects merging the duplicates."

Questions:
1. This is in the context of Outlook contact items, and applies to contact items being imported into Outlook, is that correct? If that's the case, we should specify "Outlook" in the description.

2. Second paragraph, first sentence - I put "... enable or disable the feature in the privacy settings **for Outlook**" - is that correct? 
Your second sentence makes me think you're referring to the Outlook UI, not programmatically.
For my work account, I actually didn't manage to figure out if this setting is something I can control as a user, or our organization manages this on our behalf and we as individual users have no direct control about the suggestion feature coming on or not. We can only control whether we want to merge a specific contact item when Outlook calls out a duplicate.
If you confirm that all users can enable or disable this feature, that's good, I'll stick to the rephrase above. Hope that's correct then.
If you confirm that this is actually dependent on the organization, then I'd suggest we clarify the first sentence of my second paragraph this way:
"Depending on the privacy settings managed by the organization, a user may have the option to enable or disable the feature in the user's privacy settings for Outlook. "

2022-02-16 07:24 UTC, jagadeesh-vadivel commented on api-reference/beta/resources/contactmergesuggestions.md
> +
Hi @angelgolfer-ms 
Thanks a lot for your comments. This is great help. Kindly find my response below:
1. Yes, that is correct. This feature is for the outlook contacts. 
2. Actually, this feature is build on the latest version of the Contacts API. (This version is rolled out only to internal rings as of now.) And in this version, there is no concept of folders. There is only one list of contacts and the user can categorize their contacts by providing custom labels. 
3. This specific API is exposed for user-level control. Using this API the user can decide whether they want the suggestion to be shown or not.  Kindly note that we are also planning expose a organization level privacy setting for  this API in the near future. But this API is for **User Level Control.** Finally, today we are planning to integrating this API with My account privacy page (https://myaccount.microsoft.com/settingsandprivacy). So that user will have both programmatic and user-interface way to opt-in / opt-out for the feature.

2022-02-16 08:54 UTC, opbld33 commented
Docs Build status updates of commit _[b2d8910](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2d8910513aee0364e9327e39a4687aa1c76b7cb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-60ffcbd1)

<a id="60ffcbd1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202160853467321-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T08%3A54%3A16Z&sr=b&sp=r&sig=xjdNSHODAbe7s0qOYkLAZv2d0MPk%2FjuFRR1SLgJR5jY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 09:10 UTC, opbld34 commented
Docs Build status updates of commit _[e3e9908](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3e9908e09664aa361249b26b0895b1566dceb1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4b4cde67ab6990d14f4f235249feffee-3dd31540)
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-eb35fe5074ded7ba58df4876b9940d89-3dd31540)
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-9b86bc10b7f0bbfef1108130886dceec-3dd31540)
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-3dd31540)
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-3dd31540)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-3dd31540)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-3dd31540)
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-3dd31540)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-70d8230b1c27deb48a93504ab2e36495-3dd31540)
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessage-post-replies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4864f2658a11c76cebf44cd5fbe45988-3dd31540)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-382c17fcce2c98c9ebb5ad3b6cac0dfe-3dd31540)
[api-reference/beta/api/connectorgroup-post-connectorgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/connectorgroup-post-connectorgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-connectorgroups?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-7b96b57a0f9252ab27f0a53dc6d112d5-3dd31540)
[api-reference/beta/api/connectorgroup-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/connectorgroup-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-9e07aab7b660fda52d94dc5b63fcb717-3dd31540)
[api-reference/beta/api/contactfolder-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactfolder-post-contacts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactfolder-post-contacts?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-1523fc41a65661e2bcac193087f5180f-3dd31540)
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-3dd31540)
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-f8f3702874260569eab0d768f0cba1fa-3dd31540)
[api-reference/beta/api/directorysetting-post-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/directorysetting-post-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-post-settings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-423d9b238a941cf2932c3da893db848d-3dd31540)
[api-reference/beta/api/ediscovery-case-list-op [...]

2022-02-16 12:55 UTC, opbld31 commented
Docs Build status updates of commit _[e80658a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e80658adb19b0b8493a3bad461e8978786a9427b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4b4cde67ab6990d14f4f235249feffee-6440a5ab)
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-eb35fe5074ded7ba58df4876b9940d89-6440a5ab)
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-9b86bc10b7f0bbfef1108130886dceec-6440a5ab)
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-6440a5ab)
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-6440a5ab)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-6440a5ab)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-6440a5ab)
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-6440a5ab)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-70d8230b1c27deb48a93504ab2e36495-6440a5ab)
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessage-post-replies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4864f2658a11c76cebf44cd5fbe45988-6440a5ab)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-382c17fcce2c98c9ebb5ad3b6cac0dfe-6440a5ab)
[api-reference/beta/api/connectorgroup-post-connectorgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/connectorgroup-post-connectorgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-connectorgroups?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-7b96b57a0f9252ab27f0a53dc6d112d5-6440a5ab)
[api-reference/beta/api/connectorgroup-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/connectorgroup-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-9e07aab7b660fda52d94dc5b63fcb717-6440a5ab)
[api-reference/beta/api/contactfolder-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactfolder-post-contacts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactfolder-post-contacts?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-1523fc41a65661e2bcac193087f5180f-6440a5ab)
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-6440a5ab)
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-f8f3702874260569eab0d768f0cba1fa-6440a5ab)
[api-reference/beta/api/directorysetting-post-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/directorysetting-post-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-post-settings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-423d9b238a941cf2932c3da893db848d-6440a5ab)
[api-reference/beta/api/ediscovery-case-list-op [...]

2022-02-16 13:05 UTC, opbld33 commented
Docs Build status updates of commit _[7722408](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7722408271a2e185b2c63b48928632b90fd6a5ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4b4cde67ab6990d14f4f235249feffee-a3229600)
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-eb35fe5074ded7ba58df4876b9940d89-a3229600)
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/accessreviewpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-9b86bc10b7f0bbfef1108130886dceec-a3229600)
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-a3229600)
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-a3229600)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-a3229600)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-a3229600)
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-a3229600)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-70d8230b1c27deb48a93504ab2e36495-a3229600)
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessage-post-replies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-4864f2658a11c76cebf44cd5fbe45988-a3229600)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-382c17fcce2c98c9ebb5ad3b6cac0dfe-a3229600)
[api-reference/beta/api/connectorgroup-post-connectorgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/connectorgroup-post-connectorgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-connectorgroups?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-7b96b57a0f9252ab27f0a53dc6d112d5-a3229600)
[api-reference/beta/api/connectorgroup-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/connectorgroup-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-9e07aab7b660fda52d94dc5b63fcb717-a3229600)
[api-reference/beta/api/contactfolder-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactfolder-post-contacts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactfolder-post-contacts?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-1523fc41a65661e2bcac193087f5180f-a3229600)
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-a3229600)
[api-reference/beta/api/directorysetting-post-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/directorysetting-post-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-post-settings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-423d9b238a941cf2932c3da893db848d-a3229600)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-a3229600)
[api-reference/beta/api/educationroot-list-u [...]

2022-02-16 13:07 UTC, opbld30 commented
Docs Build status updates of commit _[7722408](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7722408271a2e185b2c63b48928632b90fd6a5ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d6563beb)

<a id="d6563beb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202161304127611-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T13%3A07%3A26Z&sr=b&sp=r&sig=a%2Bsw%2FeP4DdrP7yrgy8NZ%2Bu4YcIAn39h6vR5vrkVcl9Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 13:09 UTC, opbld33 commented
Docs Build status updates of commit _[7722408](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7722408271a2e185b2c63b48928632b90fd6a5ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-262f37bd)
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-194267c81ecbbe8a27b471e5ad429604-262f37bd)
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="3bb1f9a698692f441083446cb3d31a46-262f37bd"></a>
### [api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'personal-contacts'.`````

<a id="194267c81ecbbe8a27b471e5ad429604-262f37bd"></a>
### [api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'personal-contacts'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202161304228441-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T13%3A09%3A34Z&sr=b&sp=r&sig=R45LAhdEtQEcgQuIVTro8uZF%2BPaWG%2FywYlJCC7JGvk0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 13:30 UTC, opbld31 commented
Docs Build status updates of commit _[15c0bda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15c0bda554fa55bf65f5edb68bdbfbe47183f485)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202161328338832-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T13%3A30%3A23Z&sr=b&sp=r&sig=f4lDq6%2BltxWPHZqaTeel0pUMnNBDETyxDXxMyrS5flU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 13:40 UTC, jagadeesh-vadivel commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
As per this documentation : https://review.docs.microsoft.com/en-us/help/contribute/metadata-taxonomies?branch=main#msprod, 'contacts' falls under 'outlook' category. 
Therefore, we have updated the value to Outlook itself. Kindly let us know if we are missing something here.

2022-02-16 13:43 UTC, jagadeesh-vadivel commented on changelog/Microsoft.People.json
> +			"WorkloadArea": "People and workplace intelligence",
Updated the workload area to 'Personal Contacts' as this feature works user's personal contact list. Kindly let us know your comments on the same. :)

2022-02-23 06:42 UTC, angelgolfer-ms commented
Hi @jagadeesh-vadivel , I have a few more questions based on your reply. Can you please take a look at the email I just sent? Thanks!

2022-02-23 09:28 UTC, opbld30 commented
Docs Build status updates of commit _[d82bfc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d82bfc25984d0f53b34d4dc519fa46a712919efb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230926208161-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T09%3A28%3A14Z&sr=b&sp=r&sig=uUQdK1HD2LgzNBQI7CR4RXU9h6g3pAsSxVNaS%2FDkTqU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 08:57 UTC, angelgolfer-ms commented on changelog/Microsoft.People.json
> +			"ChangeList": [
@jagadeesh-vadivel , I just noticed this - you added your changelog JSON to Microsoft.People.json instead of Microsoft.Exchange.json.
I'm curious if the changelog JSON was indeed generated in Microsoft.People.json?

The existing changelog items that pertain to personal contacts are in Microsoft.Exchange.json. 
How that matters is if internally, a partner tries to mirror or troubleshoot a changelog item, that person would have to identify which changelog JSON file to look at.
Typically, changelog records that have the same WorkloadArea value would reside in the same changelog JSON.

Can you move your changelog JSON to Microsoft.Exchange.json please?

2022-02-24 09:06 UTC, angelgolfer-ms commented on api-reference/beta/api/contactmergesuggestions-get.md
> +author: "jagadeesh-vadivel"
GLOBAL for this PR:
@jagadeesh-vadivel , to follow the same approach for the "author" field, FYI I have replaced your Github name by kevinbellinger in the 3 new topics in this PR. 
In general, to minimize orphaned topics when the original topic author moves on to another project, we generally have each partner team determine a PM who is more stable in the project and all the topics for that partner team use the same "author" value. That person can in turn assign any Github issues or third-party PRs to other folks on their team to follow up.
If you don't think that Github name is appropriate, please let me know on Teams.
Please see this CDK topic that describes the approach: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211777/GitHub-owners

2022-02-24 09:10 UTC, angelgolfer-ms requested changes
@jagadeesh-vadivel , there's just one more comment for you to follow up about the changelog JSON file to use.
After you incorporate that feedback, I think this PR is good to be published.

2022-02-24 09:11 UTC, opbld33 commented
Docs Build status updates of commit _[6546f48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6546f48f0a5e057efc02d8b780a1353e7ac508bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202240909068266-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T09%3A11%3A07Z&sr=b&sp=r&sig=OxH%2Bgsdyocf5GO44VomI6RSRVnbNbMy9UWQIjzvg%2FBg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 09:51 UTC, jagadeesh-vadivel commented on api-reference/beta/api/contactmergesuggestions-get.md
> +author: "jagadeesh-vadivel"
We completely agree with the reasoning @angelgolfer-ms. Thanks for pointing it out. Kevin bellinger has contributed to lot of contacts graph resources. And we agree that he would be a better person to handle any Github issues :)

2022-03-02 08:03 UTC, angelgolfer-ms commented
@jagadeesh-vadivel , thanks for confirming that the changelog JSON was generated in Microsoft.People.json.

2022-03-03 03:56 UTC, Lauragra commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
The value we should use here then is "personal-contacts", so that this content is grouped together with other content under the Personal contacts nodes when we look at reports and so on. This also maps to the value you're using for the WorkloadArea in the changelog entry.

2022-03-03 04:17 UTC, Lauragra commented on api-reference/beta/resources/usersettings.md
> +- [Suggesting to merge duplicate contacts](../resources/contactmergesuggestions.md).
This might be a better phrase: "Suggestions for merging duplicate contacts".

2022-03-03 04:23 UTC, jagadeesh-vadivel commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
Hi @Lauragra 

We had tried the value "personal-contacts" a while ago. And we got the following warning:
![image](https://user-images.githubusercontent.com/30215636/156495718-1bc85259-6d9f-4544-a735-ff3058e79eda.png)

And that's why we reverted the changes. Kindly let us know if we can ignore this warning. then I can update the ms.prod value to the suggested value: "Personal-Contacts"

2022-03-03 04:35 UTC, opbld30 commented
Docs Build status updates of commit _[41a23b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41a23b7d2542362dda2a0e3212d73bc285c00274)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-40101657)
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="3bb1f9a698692f441083446cb3d31a46-40101657"></a>
### [api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'personal-contacts'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030430337807-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A35%3A13Z&sr=b&sp=r&sig=ZBs%2BE8FdVsaXCILgwyswCjtMHp4hgD%2FTbX7HZdv29UA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:37 UTC, Lauragra commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
I see. I suppose for now we should leave outlook as the value because I see that we're using that for all Outlook features, and this is something we can follow up on globally later.

2022-03-03 04:40 UTC, opbld31 commented
Docs Build status updates of commit _[a7b5161](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7b51616142fe4137b5741fcfedf859ce5be78e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030438135598-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A40%3A41Z&sr=b&sp=r&sig=n3F%2F0qV22x9g%2B5mNHyPkMn4gOLPMlrA5KsjlvnWFZNM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:42 UTC, opbld32 commented
Docs Build status updates of commit _[e02f04f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e02f04fb4d1d0887525606af5efbe2a7532429b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/api/contactmergesuggestions-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-15392) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-04-add-endpoint-contactmergesuggestions/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030438424890-15392%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A42%3A46Z&sr=b&sp=r&sig=CCGYcN0Y3KValxqPiKT%2B1ltYEsIZuQxgpuAm%2B0CSnkg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:47 UTC, jagadeesh-vadivel commented on api-reference/beta/api/contactmergesuggestions-get.md
> +ms.prod: "outlook"
Great. Thank you @Lauragra for the update. :)

2022-03-03 04:53 UTC, merged