[CloudPC]Update restore API request body
microsoftgraph/microsoft-graph-docs pull request #15404
Opened 2022-01-05 06:08 UTC by rongting

2022-01-05 06:09 UTC, opbld33 commented
Docs Build status updates of commit _[1fce9fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fce9fd2309a9d34c470553c9a6d02aa3f13c46d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :x:Error | | [Details](#user-content-51fa16021253b8c7db27c1b27d9f5db1-9db623fe)

<a id="51fa16021253b8c7db27c1b27d9f5db1-9db623fe"></a>
### [api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md)
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/manageddevice-restorecloudpc-javascript-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050608087345-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T06%3A09%3A47Z&sr=b&sp=r&sig=oAWUpMBxJHPo5togn%2Bg29pkbVZqzJdOlaMYhawyWRJ4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 06:16 UTC, opbld32 commented
Docs Build status updates of commit _[4b1a1b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b1a1b980acdcd7cc0c3aaf81c0ff7c8a61f3f9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/manageddevice-restorecloudpc-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/csharp/manageddevice-restorecloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/manageddevice-restorecloudpc-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/go/manageddevice-restorecloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/manageddevice-restorecloudpc-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/java/manageddevice-restorecloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/manageddevice-restorecloudpc-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/javascript/manageddevice-restorecloudpc-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/manageddevice-restorecloudpc-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/objc/manageddevice-restorecloudpc-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201050614130103-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T06%3A16%3A17Z&sr=b&sp=r&sig=q9tSOh39sessTqJ%2FM5a8bWDKMbpzxIhJZmmfHFuLwGk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 10:58 UTC, opbld30 commented
Docs Build status updates of commit _[f20fe7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f20fe7dde7037dea5bbe548e930478242de43fd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkrestorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-bulkrestorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/manageddevice-restorecloudpc-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/csharp/manageddevice-restorecloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/manageddevice-restorecloudpc-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/go/manageddevice-restorecloudpc-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/manageddevice-restorecloudpc-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/java/manageddevice-restorecloudpc-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/javascript/manageddevice-restorecloudpc-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/javascript/manageddevice-restorecloudpc-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/objc/manageddevice-restorecloudpc-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/includes/snippets/objc/manageddevice-restorecloudpc-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcbulkremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcbulkremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcbulkremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201071056426640-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T10%3A58%3A48Z&sr=b&sp=r&sig=Jd%2FeETN6wk4GhttHgcyG31klHx%2F46DEqqyIU4LQCuJg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 11:01 UTC, opbld34 commented
Docs Build status updates of commit _[ffbfc40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffbfc40a42901fd8e0c0fae706a3888edc56b58b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkrestorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-bulkrestorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcbulkremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcbulkremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcbulkremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201071059462741-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T11%3A01%3A48Z&sr=b&sp=r&sig=FbPdJ%2FyHLeNzQL9AWXTNqeVuNuNfd%2F2UqYMXiuDrbDI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 06:55 UTC, AshleyYangSZ requested changes

2022-01-10 08:50 UTC, RuiHou105 commented on api-reference/beta/api/manageddevice-bulkrestorecloudpc.md
> +|timeRange|restoreTimeRange|The time range of restore point.|
Added.

2022-01-10 08:51 UTC, RuiHou105 commented on api-reference/beta/api/manageddevice-restorecloudpc.md
> +POST /deviceManagement/managedDevices/{managedDeviceId}/restoreCloudPc
Updated.

2022-01-10 09:01 UTC, opbld34 commented
Docs Build status updates of commit _[e2c1f14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2c1f1492a130325c575c5fd218af7002c69decd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkrestorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-bulkrestorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcbulkremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcbulkremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcbulkremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100859126102-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T09%3A01%3A12Z&sr=b&sp=r&sig=gKgl0jyStoabRZr%2BYagOg71NQPwjQT8T%2FdYoEeSCaHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 04:28 UTC, rongting commented on api-reference/beta/resources/cloudpcbulkremoteactionresult.md
> +|failedDeviceIds|String collection|A list of all the managedDevice DeviceID's that completed the bulk action successfully.|
should be managed device id.

2022-01-11 04:48 UTC, opbld34 commented
Docs Build status updates of commit _[3bdf829](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bdf8295ee02aecc5b0b660c1b2262b114d8d5a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkrestorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-bulkrestorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcbulkremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcbulkremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcbulkremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110446468130-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T04%3A48%3A42Z&sr=b&sp=r&sig=n1124q%2B2bo1LnWj%2FWs%2FdjSm1FM%2FPL83B0zAlOgLNEtg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 04:51 UTC, opbld34 commented
Docs Build status updates of commit _[27182dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27182dd2d1604772f47f71312e6efb50fb2a4f3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkrestorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-bulkrestorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcbulkremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcbulkremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcbulkremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110449504419-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T04%3A51%3A49Z&sr=b&sp=r&sig=zSzcOQgMghiahN2dl0tpobednJsuwj8f%2BzT7%2FWt%2B9CU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 08:28 UTC, AshleyYangSZ commented on api-reference/beta/api/manageddevice-bulkrestorecloudpc.md
> +    "String"
This should be an example value of managedDeviceId, not the type of this property. Same as below.

2022-01-17 02:45 UTC, AshleyYangSZ requested changes

2022-01-17 12:03 UTC, opbld34 commented
Docs Build status updates of commit _[06c86d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06c86d8f7756158514d2a629f367bf8fd079755f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkrestorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-bulkrestorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkrestorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-restorecloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/api/manageddevice-restorecloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-restorecloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcbulkremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcbulkremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcbulkremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/api-reference/beta/resources/cloudpcremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcremoteactionresult?view=graph-rest-beta&branch=pr-en-us-15404) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tiron/add-restore-schema/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171200366080-15404%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T12%3A03%3A05Z&sr=b&sp=r&sig=NzA17Bsxv0queam0UzC%2FDdd64qJNV6jYFsFgAW%2B6FIM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 06:54 UTC, rongting commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **restoring** member to the **cloudPcStatus** enumeration.",
updated

2022-01-19 07:26 UTC, AshleyYangSZ approved these changes
Please  resolve conflicting.

2022-01-19 10:24 UTC, closed without merging