Add restorePointSetting to cloudPcUserSetting
microsoftgraph/microsoft-graph-docs pull request #15418
Opened 2022-01-06 06:54 UTC by RuiHou105

2022-01-06 06:56 UTC, opbld30 commented
Docs Build status updates of commit _[8b72caa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b72caa6a04bb46c35e8d13a61f2e8d5b93ecb76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060654173641-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T06%3A56%3A14Z&sr=b&sp=r&sig=Acd2gNJ1iRBOnjlzifPLmsLHo0ByQLxsrHhBBDqLQas%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 06:57 UTC, RuiHou105 commented
**Roadmap workitem:** 

Feature 12481: [Devices and apps][Cloud PC] Add restorePointSetting to cloudPcUserSetting

2022-01-10 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[888c703](https://github.com/microsoftgraph/microsoft-graph-docs/commits/888c7038d38e5725b908ebe374c306c0d2c8680c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100301426221-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T03%3A04%3A57Z&sr=b&sp=r&sig=P3OhZyRWvIj0RG0LsW%2Bm5hf9u8a6XIGSVCBtZnjY6QQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 03:21 UTC, opbld31 commented
Docs Build status updates of commit _[b64f841](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b64f841a03485c2a0e70e038fab967d64ea88aac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100319448839-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T03%3A21%3A44Z&sr=b&sp=r&sig=hQHjEYnMplgoHx7k8EFB60m3CQrr2L0tXZ5%2F3EolTWw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 06:11 UTC, opbld33 commented
Docs Build status updates of commit _[b0a6daf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0a6daf17a7ec97ec9070dd10302d130fb705b30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100609591724-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T06%3A11%3A49Z&sr=b&sp=r&sig=Xw6FXWzsxL9jmxGZwJTYBcD5cw6KKOq%2B5YaMnP96IVs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 06:22 UTC, opbld33 commented
Docs Build status updates of commit _[c9830c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9830c49a2746e28c47eda06fe2a9472267a522f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100620475859-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T06%3A22%3A42Z&sr=b&sp=r&sig=uEvvDRfdIQLZiS5%2FiurQ%2FzRiHaKLuw8LGBEeD3r4vl0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 08:26 UTC, AshleyYangSZ approved these changes

2022-01-25 04:08 UTC, RuiHou105 commented
@isvargasmsft  @Danielabom  @JarbasHorst  @Lauragra  
As the graph schema already went alive, could you please help review this PR? Thanks!

2022-01-25 20:47 UTC, opbld32 commented
Docs Build status updates of commit _[dd6a65e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd6a65ef15840de60347167e996ac70db983e370)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201252044553499-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T20%3A47%3A55Z&sr=b&sp=r&sig=vaPDYWZXMYJ5PuKvriC5mURa%2F7gsZhKSH7h%2F%2BlbTzA8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 22:17 UTC, Danielabom commented on api-reference/beta/resources/cloudpcrestorepointsetting.md
> +|frequencyInHours|Int32|The time interval for auto taking snapshots (restore points) of a Cloud PC. Possible values are: 4 hours, 6 hours, 12 hours, 18 hours, 24 hours. The default frequency is 12 ho
Line 22: The second part of the description lists the possible values of the property. However, the type is an Int32 which allows the user to enter any number that qualifies as an Int32. How do you control that users will not enter other values from the ones listed in this description?

In addition, the get and update examples display a value of 16 hours which is not even listed as a possible value here.

2022-01-25 22:33 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +        },
Missing in this PR:
Entity: cloudPcSnapshot
Complex type: cloudPcSnapshotstatus
Complex type: cloudPcBulkRemoteActionResult
Enum: restoreTimeRange

Please review whether these resources have to be added.

2022-01-25 22:35 UTC, Danielabom requested changes
Hi Rui, Thank you for working on this PR. Please review my comments and address them accordingly. 
Thanks,
Dani

2022-01-26 07:15 UTC, opbld33 commented
Docs Build status updates of commit _[e54bbe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e54bbe7b3fd29caea936c5cbc5a494422777f492)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260713082487-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T07%3A15%3A20Z&sr=b&sp=r&sig=%2BCRqM4RjlftH9EkriK8163iskBSVBvKbghhKkfxkZaE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 07:16 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcrestorepointsetting.md
> +|frequencyInHours|Int32|The time interval for auto taking snapshots (restore points) of a Cloud PC. Possible values are: 4 hours, 6 hours, 12 hours, 18 hours, 24 hours. The default frequency is 12 ho
Hi @Danielabom 
Q1: Here I attach the UX screenshot. You can see that there is a dropdown with options that users can choose. So it's impossible that users will enter an invalid number. 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/77313233/151117892-3af3d0c0-0778-4601-a952-5f375f1b4e55.png">


Q2: All possible values are: 4, 6, 12, 16, 24. I corrected the values. Please check. Thanks!

2022-01-26 07:21 UTC, opbld31 commented
Docs Build status updates of commit _[a41bb8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a41bb8e9305a31e95bc59e1f7a2580846ca85fe4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260719086828-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T07%3A21%3A31Z&sr=b&sp=r&sig=F6SLttETayMlvIorS59q6QgGpnJkhPflqAgU%2BOvDGgw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 07:24 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +        },
Hi @Danielabom ,
Entity: `cloudPcSnapshot` and complex type: `cloudPcSnapshotStatus` are recorded in this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15416

complex type: `cloudPcBulkRemoteActionResult` and enumeration `restoreTimeRange` are recorded  in this one: 
https://github.com/microsoftgraph/microsoft-graph-docs/pull/15556

2022-01-26 21:01 UTC, Danielabom commented on api-reference/beta/resources/cloudpcrestorepointsetting.md
> +|frequencyInHours|Int32|The time interval for auto taking snapshots (restore points) of a Cloud PC. Possible values are: 4 hours, 6 hours, 12 hours, 18 hours, 24 hours. The default frequency is 12 ho
Line 22: The first part of my comment was not addressed. Please consider changing line 22 to: "The time interval in hours to take snapshots automatically (restore points) of a Cloud PC. Possible values are 4, 6, 12 16, 18, and 24. The default frequency is 12 hours."

2022-01-27 07:48 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcrestorepointsetting.md
> +|frequencyInHours|Int32|The time interval for auto taking snapshots (restore points) of a Cloud PC. Possible values are: 4 hours, 6 hours, 12 hours, 18 hours, 24 hours. The default frequency is 12 ho
Thanks @Danielabom . Description updated. Please check.

2022-01-27 07:52 UTC, opbld34 commented
Docs Build status updates of commit _[314276e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/314276e832cc10322299a059299c6a28525ed65a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201270750229989-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T07%3A52%3A34Z&sr=b&sp=r&sig=36%2F7z8k%2FFSJOuTCddSII8VUxkXi3gPnjbyZR3sLkjjo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 20:12 UTC, Danielabom approved these changes

2022-02-25 09:20 UTC, opbld34 commented
Docs Build status updates of commit _[67a5105](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67a510514341ab1151100e6da1561de0fe8d22f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202250918411546-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T09%3A20%3A50Z&sr=b&sp=r&sig=foYC6qKdg5GIN1e5UMXPfx1A%2FZknhivI0SyAjM%2FFZrY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-28 05:52 UTC, RuiHou105 commented
@Lauragra , if you don't have other concerns. could you please help merge this PR? Thanks!

2022-03-01 01:56 UTC, opbld30 commented
Docs Build status updates of commit _[115f3c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/115f3c99c009ded609d368f315d089dfedf70046)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203010154478123-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T01%3A56%3A45Z&sr=b&sp=r&sig=5PvyxwxYEQe3x1%2BGlIoiF3SI2bL%2FtdZSAcKSECG8Mvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 01:59 UTC, opbld33 commented
Docs Build status updates of commit _[1601922](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16019228b061d92ed42d7df9c0205a257b4f880c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203010155489572-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T01%3A59%3A02Z&sr=b&sp=r&sig=D5c2BU%2F8Bu%2BTy6FtPQRtHDyndR6gkpMb1OfORGrQnmg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 02:41 UTC, opbld34 commented
Docs Build status updates of commit _[93eff49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93eff490f4226fe72b342850180eb77728b04d51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203010239102726-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T02%3A41%3A07Z&sr=b&sp=r&sig=Let5s1ehrIYq6u%2F3OYFQOZXp5F%2BQNsRMOxBCaPQoILk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 02:41 UTC, Lauragra approved these changes

2022-03-01 02:43 UTC, opbld31 commented
Docs Build status updates of commit _[5e04188](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e04188216a2674710c4930ef6922cee4603f324)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203010239572492-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T02%3A43%3A03Z&sr=b&sp=r&sig=HayZkfRHEdbKGB3HJcl%2FbVVyH2LEfkaAMZBu0R94Cw0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 02:45 UTC, opbld32 commented
Docs Build status updates of commit _[96674e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96674e2e65b75cdcee5def831a65d57d8d312e4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcrestorepointsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcrestorepointsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcrestorepointsetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-15418) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addRestorePointSetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203010241122505-15418%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T02%3A45%3A11Z&sr=b&sp=r&sig=DHhAc8zMvZ0XSuxjtvv%2BMhifok4kB7I7s6gCyPMRKho%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 03:11 UTC, merged