Add Snapshots relationship to cloudpc virtualendpoint
microsoftgraph/microsoft-graph-docs pull request #15416
Opened 2022-01-06 06:14 UTC by xintaozMS

2022-01-06 06:17 UTC, opbld32 commented
Docs Build status updates of commit _[cc91ee0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc91ee0280571351cbe13dbbf5eb069028aaf998)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1c3fe1f8)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | |
[doc-stubs/resource/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/resource/cloudpcsnapshot.md) | :white_check_mark:Succeeded | |
[doc-stubs/resource/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/resource/enums.md) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-1c3fe1f8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml)
 - **Line 10107, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot.md'.`````
 - **Line 10110, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualenpoint-list-snapshots.md'.`````
 - **Line 10112, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot-get.md'.`````
 - **Line 12512, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060614202888-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T06%3A17%3A00Z&sr=b&sp=r&sig=ZxYOjD2JXK04np43h9hrdp7A0KUSnJ%2FpmKr7aCJHJmc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 06:47 UTC, opbld31 commented
Docs Build status updates of commit _[ee08652](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee0865269fef5c81b566dfdb88e1e2087f62b922)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a2961c4a)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | |
[doc-stubs/resource/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/resource/cloudpcsnapshot.md) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a2961c4a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml)
 - **Line 10107, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot.md'.`````
 - **Line 10110, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualenpoint-list-snapshots.md'.`````
 - **Line 10112, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot-get.md'.`````
 - **Line 12512, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060644512907-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T06%3A47%3A38Z&sr=b&sp=r&sig=hc4XqarZPoIO5VTG2cyxatsq%2FCADhgG1Yw31X%2FtpHXw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:11 UTC, opbld31 commented
Docs Build status updates of commit _[83a196a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83a196aac4e09e6bbf98ec6ce6bd4c38f03334af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d2eb108b)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/doc-stubs/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d2eb108b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml)
 - **Line 10107, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot.md'.`````
 - **Line 10110, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualenpoint-list-snapshots.md'.`````
 - **Line 10112, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot-get.md'.`````
 - **Line 12512, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060708195993-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A11%3A17Z&sr=b&sp=r&sig=yW4fLhclh2V7jlpIn5KFqSACJBjYgvZqE3ktWrd99I4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:21 UTC, opbld32 commented
Docs Build status updates of commit _[391548d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/391548dfb2f8a444de63462ab13e06f5fba0e4fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-88ba474c4075741e19e011f294b6a03f-8f0c112e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8f0c112e)
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="88ba474c4075741e19e011f294b6a03f-8f0c112e"></a>
### [api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/cloudpcsnapshot-list.md'.`````
 - **Line 34, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcSnapshotStatus-values' in 'beta/resources/cloudpcsnapshot.md', did you mean '#cloudpcsnapshotstatus-values'?`````

<a id="0817dce4456c16725d5333633847d38f-8f0c112e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml)
 - **Line 10107, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot.md'.`````
 - **Line 10110, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualenpoint-list-snapshots.md'.`````
 - **Line 12512, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060719409963-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A21%3A42Z&sr=b&sp=r&sig=hyyN%2F5VMS5y78st6KgiG9Np%2BbgYCbWuJ5phId2OdDQo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:29 UTC, opbld32 commented
Docs Build status updates of commit _[2d91241](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d9124186d6bc8579b154d1533a73f11866b6ae1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bd12f91d)
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-bd12f91d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml)
 - **Line 10107, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcsnapshot.md'.`````
 - **Line 10110, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualenpoint-list-snapshots.md'.`````
 - **Line 12512, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060727215909-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A29%3A12Z&sr=b&sp=r&sig=FRw4MtnYAVTmQ3rXiDjo2qoNnJCf6kt2IW%2F%2BvPAqvBI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:40 UTC, opbld31 commented
Docs Build status updates of commit _[aa4c481](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa4c481dd6ad86c965e8a3d57802184a703bcbc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-005cac06)
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-005cac06"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml)
 - **Line 12512, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060739100159-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A40%3A57Z&sr=b&sp=r&sig=28BhsBC0iJ9XndjM8EP5EtuUJb2L46AnfTcNp%2BtBhAY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 07:23 UTC, opbld30 commented
Docs Build status updates of commit _[a2c0b79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2c0b79a5fe00840241a569add0f9cfe15263289)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100721530476-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T07%3A23%3A58Z&sr=b&sp=r&sig=8%2F74zyupqUPdbLnKkdZFf%2F1yiKRVFPT%2Bb6aPp7TgIO0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 09:13 UTC, opbld34 commented
Docs Build status updates of commit _[60ae0ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60ae0ad2114f8b007c58d28dd954f79a79ff1de7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100911104723-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T09%3A13%3A14Z&sr=b&sp=r&sig=y2Or42znoHxgeDrrnsTD4QvBwjsVjRHf6%2BrVnf22Oos%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 03:04 UTC, AshleyYangSZ requested changes

2022-01-17 03:04 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +|Delegated (work or school account)|CloudPC.ReadWrite.All|
Please update to `CloudPC.Read.All, CloudPC.ReadWrite.All`

2022-01-17 03:04 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +|Application|CloudPC.ReadWrite.All|
Please update to `CloudPC.Read.All, CloudPC.ReadWrite.All`

2022-01-17 03:04 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +    "cloudPcId": "String",
This should be a example value, not the type of this property. Same as rest of properties.

2022-01-17 03:04 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +      "cloudPcId": "String",
This should be the example value not the type of the property. Same as others.

2022-01-17 04:50 UTC, xintaozMS commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +Get the cloudPcSnapshot resources from the snapshots navigation property.
updated

2022-01-17 04:51 UTC, xintaozMS commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +|Delegated (work or school account)|CloudPC.ReadWrite.All|
updated

2022-01-17 04:51 UTC, xintaozMS commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +|Application|CloudPC.ReadWrite.All|
updated

2022-01-17 04:51 UTC, xintaozMS commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
updated

2022-01-17 04:51 UTC, xintaozMS commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +      "cloudPcId": "String",
updated

2022-01-17 04:53 UTC, opbld30 commented
Docs Build status updates of commit _[699327c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/699327c2db7693386f23524a37b69aefa6f10922)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201170450437657-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T04%3A53%3A36Z&sr=b&sp=r&sig=Oy%2FZcrcj7fKxpZxojzCEqeWEQ2YN38ZFOPFvAZttifA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 08:46 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Same here, please specify the supported OData query parameters.

2022-01-17 10:30 UTC, xintaozMS commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
specified ```select```

2022-01-17 10:32 UTC, opbld31 commented
Docs Build status updates of commit _[1a9703c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a9703c6587ee852cd86ee59a0186085007779d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171030079012-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T10%3A32%3A44Z&sr=b&sp=r&sig=3b34Qrr2lfUr%2BkrkvV%2BYmdGJ1T%2BP6kfcnnX%2BguEtjX8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 04:45 UTC, opbld32 commented
Docs Build status updates of commit _[294b76f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/294b76fcc205e86488db7ffc3f9e0ea6281c670f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190443501187-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T04%3A45%3A44Z&sr=b&sp=r&sig=qSsM8UY9PtgYY%2B3mmVgaeL1Q63vaw%2BqrLvLHyqqx33I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 07:29 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +Get the cloudPcSnapshot resources from the snapshots navigation property.
Sorry, the description should be " List properties and relationships of the cloudPcSnapshot objects."

2022-01-19 07:30 UTC, AshleyYangSZ approved these changes
Please update the description of List snapshots API as I commented before

2022-01-25 08:16 UTC, RuiHou105 commented
@Lauragra  @JarbasHorst  @isvargasmsft  @Danielabom 

Kindly ping to review this PR as the graph schema already went alive. Thanks!

2022-01-26 08:13 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +>**Note:** The response object shown here might be shortened for readability.
Can delete this note.

2022-01-26 08:14 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +>**Note:** The response object shown here might be shortened for readability.
This note is extra. Can remove.

2022-01-26 20:30 UTC, JarbasHorst commented
Sure, @RuiHou105! I will review this PR.

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|cloudPcId|String|The Cloud PC id.|
For consistency, please replace this description with:
- The unique identifier for the Cloud PC.

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|createdDateTime|DateTimeOffset|The date and time at which the snapshot was taken. The time is shown in ISO 8601 format and Coordinated Universal Time (UTC) time. For example, midnight UTC on Jan 1,
1) For consistency and clarity, please replace the second appearance of "time" with "timestamp" and remove "time" after "(UTC)". Suggested revision.

The timestamp is shown in ISO 8601 format and Coordinated Universal Time (UTC).

2) For simplicity, please replace "appears as" with "is". Also, please replace '2014-01-01T00:00:00Z' with \`2014-01-01T00:00:00Z\`.

Suggested revision:

- The timestamp is shown in ISO 8601 format and Coordinated Universal Time (UTC). For example, midnight UTC on Jan 1, 2014 is \`2014-01-01T00:00:00Z\`.

Please, use this description also in line 33.

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|id|String|The snapshot id of Cloud PC previous point-in-time state. Inherited from [entity](../resources/entity.md).|
For clarity, I recommend you to rephrase this sentence. Suggested revision:

- The unique identifier for the snapshot of the Cloud PC device at a specific point in time. Inherited from...

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|lastRestoredDateTime|DateTimeOffset|The date and time that snapshot has been used for restore. The time is shown in ISO 8601 format and Coordinated Universal Time (UTC) time. For example, midnight U
For clarity, I recommend you to rephrase this first sentence. Suggested revision:

- The date and time at which the snapshot was last used to restore the Cloud PC device.

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|status|[cloudPcSnapshotStatus](#cloudpcsnapshotstatus-values)|Status of the Cloud PC snapshot. Possible values include "ready". The possible values are: `ready`, `unknownFutureValue`.|
1) Please, add "The" before "status".

2) Second sentence: Do you mean "Default value is: `ready`"? Since you already have a sentence that explains what are the possible values for the status property, I recommend you to remove the second sentence.

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|ready|The snapshot is ready to be used for restore.|
For clarity, please replace "to be used for restore" with "to restore the Cloud PC". Suggested revision:

- The snapshot is ready to restore the Cloud PC device.

2022-01-26 21:55 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **snapshots** relationship to [virtualEndpoint](https://docs.microsoft.com/en-us/graph/api/resources/intune-virtualEndpoint?view=graph-rest-beta) resourc
Your PR doesn't include changes to the [virtualendpoint](https://docs.microsoft.com/en-us/graph/api/resources/virtualendpoint) resource type. Are you missing something? :)

2022-01-26 21:55 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **snapshots** relationship to [virtualEndpoint](https://docs.microsoft.com/en-us/graph/api/resources/intune-virtualEndpoint?view=graph-rest-beta) resourc
1) Please, add "the" before [virtualEndpoint].

2) The URL in the description is wrong => **intune-virtualEndpoint** should be **virtualendpoint**.

2022-01-26 21:55 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [cloudPcSnapshot](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcSnapshot?view=graph-rest-beta) resource",
1) Please, add a period at the end of the sentence.

2) The URL in the description is wrong => **intune-cloudPcSnapshot** should be **cloudpcsnapshot**.

2022-01-26 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|[List cloudPcSnapshots](../api/virtualendpoint-list-snapshots.md)|[cloudPcSnapshot](../resources/cloudpcsnapshot.md) collection|Get a list of the [cloudPcSnapshot](../resources/cloudpcsnapshot.md) o
For consistency, please replace **List cloudPcSnapshots** with **List snapshots**.

2022-01-27 07:21 UTC, opbld34 commented
Docs Build status updates of commit _[ccdeef9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccdeef9034b5b9a747b0ae073903a1f9f9fe23a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201270718483628-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T07%3A21%3A31Z&sr=b&sp=r&sig=qfpXkdsRyFKGy77sLOd5k0zwqVnOD2%2FH0cbzCcgvZ%2BA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 07:54 UTC, xintaozMS commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **snapshots** relationship to [virtualEndpoint](https://docs.microsoft.com/en-us/graph/api/resources/intune-virtualEndpoint?view=graph-rest-beta) resourc
added

2022-01-27 08:00 UTC, opbld34 commented
Docs Build status updates of commit _[a5977d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5977d2a35ea88ead50d4d7b003b19a9d43e6770)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201270757466685-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T08%3A00%3A11Z&sr=b&sp=r&sig=ps%2Faim8w%2BSXjJJ%2FCsE4qqxmOBuVcAeGS9xYiX28M1jc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 08:02 UTC, opbld31 commented
Docs Build status updates of commit _[35de976](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35de976f5d2112433e7257ac93fcaccec4c97d55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201270759255275-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T08%3A02%3A33Z&sr=b&sp=r&sig=Uwvc64FMU88cFpTlLecgFyvJQqrxthtX%2BUrpn2ETUDw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 08:38 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +>**Note:** The response object shown here might be shortened for readability.
Hey, remember to delete this extra note :)

2022-01-27 08:40 UTC, RuiHou105 commented on api-reference/beta/resources/virtualendpoint.md
> +|snashots|[cloudPcSnapshot](../resources/cloudpcsnapshot.md) collection|Cloud PC snapshots.|
typo: snapshots

2022-01-27 08:42 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsnapshot.md
> +  "id": "String (identifier)",
@xintaozMS  I think in this json format, the property order should be: cloudPcId, createdDateTime, id, lastRestoredDateTime, status.

2022-01-27 21:21 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +<!-- {
For consistency, please add the following boilerplate text here:

``` 
### Request

The following is an example of a request.

<!-- {
```

2022-01-27 21:21 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcsnapshot-get.md
> +>**Note:** The response object shown here might be shortened for readability.
For consistency, please add the following boilerplate text here:

``` 
### Response

The following is an example of the response.

<!-- {
```

2022-01-27 21:21 UTC, JarbasHorst commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +<!-- {
For consistency, please add the following boilerplate text here:

``` 
### Request

The following is an example of a request.

<!-- {
```

2022-01-27 21:21 UTC, JarbasHorst commented on api-reference/beta/api/virtualendpoint-list-snapshots.md
> +<!-- {
For consistency, please add the following boilerplate text here:

``` 
### Response

The following is an example of the response.

<!-- {
```

2022-01-28 03:20 UTC, opbld31 commented
Docs Build status updates of commit _[3ca6488](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ca6488e822e042265cb396d1f32e1f327e0b780)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201280318494708-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T03%3A20%3A51Z&sr=b&sp=r&sig=Y31fXzQW6U%2BbUpps5Xzw1iKZnhBb0hjy4iqVzrY4SHI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-30 21:11 UTC, JarbasHorst commented
@Lauragra, this PR is ready for final review.

2022-02-15 03:42 UTC, xintaozMS commented
@Lauragra, would you be able to review this PR?

2022-02-16 00:54 UTC, Lauragra commented on api-reference/beta/resources/cloudpcsnapshot.md
> +Represents a Cloud PC snapshot.
Do you need to provide some additional context here, i.e. "that is used to restore system settings"? We generally try to avoid using the same words that are in the resource name to describe the resource. For example the description could be "Represents a snapshot of the device settings of a Cloud PC that can be used to restore the device system."

2022-02-16 00:58 UTC, opbld33 commented
Docs Build status updates of commit _[9783b2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9783b2b3be79461d51bfb778b57dae3581e55501)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202160056452314-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T00%3A58%3A56Z&sr=b&sp=r&sig=40zt2AEEdU1wu3czglU32xfvzpLExFsFgb7DI%2B1cVCw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 01:05 UTC, opbld33 commented
Docs Build status updates of commit _[6fc5060](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fc50602459927f0e0b515f6b1ef2d1a7989ad11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202160103413584-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T01%3A05%3A40Z&sr=b&sp=r&sig=SnDVnMJde9%2BABXSArjIreej%2F6aFQPWuZTbi20%2FHDsa0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 08:56 UTC, xintaozMS commented on api-reference/beta/resources/cloudpcsnapshot.md
> +Represents a Cloud PC snapshot.
sure, updated.

2022-02-16 09:00 UTC, opbld34 commented
Docs Build status updates of commit _[45a8f60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45a8f6017bad9109d3a82f75190abda5bd089680)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/cloudpcsnapshot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-snapshots.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/api/virtualendpoint-list-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-snapshots?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsnapshot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/cloudpcsnapshot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-get?view=graph-rest-beta&branch=pr-en-us-15416) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-06-xintaoz-cloudpc-update-snapshot/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202160856247666-15416%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T09%3A00%3A00Z&sr=b&sp=r&sig=FXvMAN1%2B07udgPanwtROWWplq7UxSo%2FwtZ4NJVYXRjk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 04:19 UTC, Lauragra approved these changes

2022-02-17 04:20 UTC, merged