Adding tenant usage
microsoftgraph/microsoft-graph-docs pull request #15424
Opened 2022-01-06 17:56 UTC by KyleWirpel

API Documentation update for tenant usage.

2022-01-06 17:58 UTC, opbld30 commented
Docs Build status updates of commit _[231bbc7](https://github.com/KyleWirpel/microsoft-graph-docs/commits/231bbc77c27e243022587c130739a879d3627aaf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-tenantusage-list.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-tenantusage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenantusage-list?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-5ed79e3617bff28822ccac16bb6b58bc-506a6c2d)
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenantusage-list?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-506a6c2d)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |

<a id="5ed79e3617bff28822ccac16bb6b58bc-506a6c2d"></a>
### [api-reference/beta/api/managedtenants-tenantusage-list.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-tenantusage-list.md)
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/tenantusage.md'.`````

<a id="0817dce4456c16725d5333633847d38f-506a6c2d"></a>
### [api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml)
 - **Line 10353, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/managedtenants-managedtenant-list-tenantusage.md'.`````
 - **Line 12510, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061756264596-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T17%3A58%3A17Z&sr=b&sp=r&sig=6%2Ft%2FyGK4Z9%2BG%2BWhF7MnDKABIRmlj2C3QicTo7%2F5mmOE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 18:05 UTC, opbld31 commented
Docs Build status updates of commit _[5e77374](https://github.com/KyleWirpel/microsoft-graph-docs/commits/5e77374c6f7390d6b371ee72ce4817a495f56fee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-2416e4254b0fe9caa7ff96cfa5230cd5-7882115d)
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7882115d)
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |

<a id="2416e4254b0fe9caa7ff96cfa5230cd5-7882115d"></a>
### [api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/managedtenants-tenantusage-list.md'.`````

<a id="0817dce4456c16725d5333633847d38f-7882115d"></a>
### [api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml)
 - **Line 10353, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/managedtenants-managedtenant-list-tenantusage.md'.`````
 - **Line 12510, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061803450946-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T18%3A05%3A30Z&sr=b&sp=r&sig=hEj%2BtopHTJoqSTejsX8HWomkRTLk1gePBUKGgSsVHKk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 18:07 UTC, opbld33 commented
Docs Build status updates of commit _[939932e](https://github.com/KyleWirpel/microsoft-graph-docs/commits/939932efa059ce1119c98fc0076971b6adcc1d78)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-2416e4254b0fe9caa7ff96cfa5230cd5-ff73ed62)
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ff73ed62)
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |

<a id="2416e4254b0fe9caa7ff96cfa5230cd5-ff73ed62"></a>
### [api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/managedtenants-tenantusage-list.md'.`````

<a id="0817dce4456c16725d5333633847d38f-ff73ed62"></a>
### [api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml)
 - **Line 10353, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/managedtenants-managedtenant-list-tenantusage.md'.`````
 - **Line 12510, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061805099444-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T18%3A07%3A19Z&sr=b&sp=r&sig=s0TXYs7vw1G%2Fk402Iq%2FQOOh9RqZMexXBgFS1YtyuKYI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 19:18 UTC, opbld30 commented
Docs Build status updates of commit _[eb194f7](https://github.com/KyleWirpel/microsoft-graph-docs/commits/eb194f7f48a9525bdd790e8e219acf3f4736407a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-2416e4254b0fe9caa7ff96cfa5230cd5-01e2bf41)
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-01e2bf41)
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |

<a id="2416e4254b0fe9caa7ff96cfa5230cd5-01e2bf41"></a>
### [api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/managedtenants-managedtenant-list-tenantusage.md'.`````

<a id="0817dce4456c16725d5333633847d38f-01e2bf41"></a>
### [api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml)
 - **Line 10353, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/managedtenants-managedtenant-list-tenantusage.md'.`````
 - **Line 12510, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061914394266-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T19%3A18%3A12Z&sr=b&sp=r&sig=PG0zTP9x6zu06GoZ5ub0tTeZjcZ0NTUwYEo0UdqSEHk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 19:23 UTC, opbld32 commented
Docs Build status updates of commit _[ead08f2](https://github.com/KyleWirpel/microsoft-graph-docs/commits/ead08f2022cc8c16f2a8ef0603a2c240af9ef3ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-298c7bfb)
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-298c7bfb"></a>
### [api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml)
 - **Line 12510, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061920043805-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T19%3A23%3A51Z&sr=b&sp=r&sig=EFMdwwRFfsFbjtgzYgsjWXxagdqbmi8rf7cVBDeZ0MQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 21:50 UTC, Danielabom commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|[List tenantUsages](../api/managedtenants-managedtenant-list-tenantusage.md)|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|Get a list of the [te
The api.md file mentions this resource supports both List and Get operations. However, I don't see the Get operation on this table. Is there a reason for that?

2022-01-11 21:56 UTC, Danielabom commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|[List tenantUsages](../api/managedtenants-managedtenant-list-tenantusage.md)|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|Get a list of the [te
In the same matter, I do not see the Get topic in this PR. Please clarify or add the topic. Thanks

2022-01-11 21:59 UTC, Danielabom commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
It is recommended to add the parameters supported by the method. In the case of the **Filter** query parameter, indicate which properties are supported.

2022-01-11 22:09 UTC, Danielabom commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +|monthlyActiveUsers|Int32|Number of Monthly Active Users for the service. Required. Read-only.|
We only capitalize branded names. Please use small caps for monthly active users.

2022-01-11 22:24 UTC, Danielabom commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +|tenantUsage|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|The collection of tenant usage across managed tenants.|
Even though I understand why adding this relationship is logical, I do not see this change on the api.md nor the CSDL file. Is this nav property actually being added to the resource type?

2022-01-11 22:26 UTC, Danielabom commented on api-reference/beta/toc.yml
> +            href: api/managedtenants-managedtenant-list-tenantusage.md
Missing in this PR:
Updates to the changelog file for the new resource type, the new complex type, methods and the relationship of the managed tenant resource.

2022-01-11 22:27 UTC, Danielabom requested changes
Thank you for working on this PR. Please review my comments and address the changes required.

2022-01-12 20:13 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|[List tenantUsages](../api/managedtenants-managedtenant-list-tenantusage.md)|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|Get a list of the [te
Current implementation is LIST only and we will update the documentation with GET functionality once it is made available.

2022-01-12 20:23 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +|monthlyActiveUsers|Int32|Number of Monthly Active Users for the service. Required. Read-only.|
Thank you for the feedback. The document has been edited accordingly.

2022-01-12 20:33 UTC, KyleWirpel commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Thank you for the feedback. The document has been edited accordingly.

2022-01-12 20:35 UTC, KyleWirpel commented on api-reference/beta/toc.yml
> +            href: api/managedtenants-managedtenant-list-tenantusage.md
This has been updated accordingly.

2022-01-12 20:39 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +|tenantUsage|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|The collection of tenant usage across managed tenants.|
This property is now present.

2022-01-12 20:41 UTC, idwilliams approved these changes

2022-01-13 17:13 UTC, opbld33 commented
Docs Build status updates of commit _[1c42037](https://github.com/KyleWirpel/microsoft-graph-docs/commits/1c42037ab1c3d9f492156e978a5d8d751eee3d4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131710570741-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T17%3A13%3A47Z&sr=b&sp=r&sig=6KMD5HFFM2dh5x9ia%2F8kFaTr4ffoGI0cJbenJwKYybE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 23:03 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +Represents Microsoft 365 service usage for a managed tenant.
Line 16:
@KyleWirpel , can you please elaborate the description? The resource name and the key words in the description are using the same words "service usage".
As a suggestion:
"Represents monthly active usage data for a service in a managed tenant."

Because the description is at the top of the topic, we should include the info that most customers want to see there.


You can see more guidance on this regarding the [Microsoft Voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28361):
"Get to the point fast. Start with the key takeaway. Put the most important thing in the most noticeable spot..."

2022-01-13 23:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +Represents Microsoft 365 tenant usage for a managed tenant.
For example, taken from your api.md file, is the following accurate? If it is, I think this would be helpful for customers.

"Represents the number of monthly active users per service in a managed tenant for the previous month. The time period for the data is a sliding window that takes a snapshot once a day."

2022-01-13 23:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|serviceUsages|[microsoft.graph.managedTenants.serviceUsage](../resources/managedtenants-serviceusage.md) collection|The number of active users by service. Example services: `Excel`, `Exchange`, `Int
Line 29:
To be clearer, I think this description should say "The number of monthly active users for each service in the tenant."

2022-01-13 23:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|totalActiveUsers|Int32|The total number of active users. Required. Read-only.|
Line 31:
Is this correct:
"The total number of monthly active users for all the services in the tenant."
If so, please update the description.

2022-01-13 23:34 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +Namespace: microsoft.graph.managedTenants
Line 10:
@KyleWirpel , please change the topic title to "List tenantUsage".
For API topics, their topic titles follow a convention. For list operation topics, the convention is "List {navigation property name}".
More info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title

2022-01-13 23:50 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +
Line 15:
The description would be more helpful if it can use other words to describe what "tenant usage" is, as the same words are used in the topic title.
As a suggestion:
"Get the monthly usage data for each service in a managed tenant."

Then make "monthly usage data for each service" a link to the serviceUsage resource topic, and "managed tenant" a link to the managedTenant resource topic.

In contrast, when your team is ready to release the GET operation, that operation can have the following description:
"Get the monthly usage data for a specific service in a managed tenant."

Provide the similar links to that description please.

2022-01-14 00:04 UTC, angelgolfer-ms commented on changelog/Microsoft.MultiTenantPlatform.json
> +          }
@KyleWirpel , please add a changelist record for the list operation.
Please see example 6 in this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples

2022-01-14 00:06 UTC, angelgolfer-ms requested changes
HI @KyleWirpel , thanks for the PR. Please see my comments and ping me on Teams if you have specific questions.

2022-01-18 19:32 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +Represents Microsoft 365 tenant usage for a managed tenant.
Thank you for the feedback. The document has been updated accordingly!

2022-01-18 19:32 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +Represents Microsoft 365 service usage for a managed tenant.
Thank you for the feedback. The document has been updated accordingly!

2022-01-18 19:33 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|serviceUsages|[microsoft.graph.managedTenants.serviceUsage](../resources/managedtenants-serviceusage.md) collection|The number of active users by service. Example services: `Excel`, `Exchange`, `Int
Thank you for the feedback! The document has been updated accordingly.

2022-01-18 19:41 UTC, KyleWirpel commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +Namespace: microsoft.graph.managedTenants
Thank you for the feedback! The document has been updated accordingly.

2022-01-18 19:41 UTC, KyleWirpel commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +
Thank you for the feedback! The document has been updated accordingly.

2022-01-18 20:00 UTC, KyleWirpel commented on changelog/Microsoft.MultiTenantPlatform.json
> +          }
Thanks for the feedback! The document has been updated accordingly.

2022-01-18 20:03 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|totalActiveUsers|Int32|The total number of active users. Required. Read-only.|
Thanks for the feedback! The documented has been updated to clarify that this is in reference to unique, active users.

2022-01-18 20:14 UTC, opbld32 commented
Docs Build status updates of commit _[2e1c66d](https://github.com/KyleWirpel/microsoft-graph-docs/commits/2e1c66df0b0b04b64fd5e6e287e0748450ad0f83)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-1cca731a3fe4e2ad570426b1136ecbe3-33a1c676)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="1cca731a3fe4e2ad570426b1136ecbe3-33a1c676"></a>
### [api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md)
 - **Line 15, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '.../resources/managedtenants-serviceusage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182011225898-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T20%3A14%3A33Z&sr=b&sp=r&sig=e%2FNcue8qUuxnC9rfe6eh2K7F9rXfDrnngKc3R24JP1M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 04:03 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +Represents monthly active usage data for a service in a managed tenant.
@KyleWirpel , thanks for the update.
The original description you used specified the service was a Microsoft 365 service. I guess that is still true, in the context of measuring service usage?
If so, can you add that to the current description please?
Also, please add a link to "managed tenant" to go to the managedTenant topic?
That would be helpful especially this topic (by design) is not in the TOC. That link will help customers navigate to other related topics, through the managedTenant topic, or through the TOC (because managedTenant is in the TOC).
Thanks!

2022-01-20 04:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +
@KyleWirpel , thanks for enhancing the description!
Similar to my comment in the serviceUsage topic, assuming the service in context is a Microsoft 365 service, can you please add that to the current description?
Also, please add a link to "managed tenant" to go to the managedTenant topic for fuller context. Thanks!

2022-01-20 04:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +
Line 3:
Please use the same description there as in line 16. That would help SEO.

2022-01-20 04:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +Represents monthly active usage data for a service in a managed tenant.
Also, in line 3, please use the same description there as in line 16. That would help SEO.

2022-01-20 04:30 UTC, angelgolfer-ms commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [tenantUsage](https://docs.microsoft.com/en-us/graph/api/resources/managedTenant?view=graph-rest-beta) resource",
Line 520:
Might have overlooked commenting on this last time... doesn't matter, in general, if you include a full URL to a page on docs.microsoft.com, like in this case, please make sure you remove the segment with the locale (en-us in this case).

2022-01-20 04:32 UTC, angelgolfer-ms commented on changelog/Microsoft.MultiTenantPlatform.json
> +          }
Did you add the list operation somewhere in this file?
Was this changelist record (lines 523-530) meant for that? 
Line 528 refers to the same thing as line 520 in the preceding changelist record.
Please update.

2022-01-20 04:37 UTC, angelgolfer-ms commented on changelog/Microsoft.MultiTenantPlatform.json
> +        ],
Also, please add a changelist record for adding the tenantUsage navigation property to the managedTenant resource.
You can please take a look at example 3 in this CDK topic that shows a changelist record to add a nav property: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

2022-01-20 04:42 UTC, angelgolfer-ms requested changes
@KyleWirpel , thanks for addressing the last set of comments. 
Just a couple more to enhance the descriptions with relevant links for SEO and navigation, and a couple about the changelog.

2022-01-20 20:40 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +Represents monthly active usage data for a service in a managed tenant.
Thank you for the feedback! The document has been updated accordingly.

2022-01-20 20:40 UTC, KyleWirpel commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +
Thank you for the feedback! The document has been updated accordingly.

2022-01-20 20:42 UTC, KyleWirpel commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [tenantUsage](https://docs.microsoft.com/en-us/graph/api/resources/managedTenant?view=graph-rest-beta) resource",
Thank you for the feedback! The document has been updated accordingly.

2022-01-20 23:03 UTC, opbld34 commented
Docs Build status updates of commit _[a107620](https://github.com/KyleWirpel/microsoft-graph-docs/commits/a107620519cb6583a84043c128b0f9abb5d97f93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-1cca731a3fe4e2ad570426b1136ecbe3-9dd8cdc4)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="1cca731a3fe4e2ad570426b1136ecbe3-9dd8cdc4"></a>
### [api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md)
 - **Line 15, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '.../resources/managedtenants-serviceusage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201202300561242-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T23%3A03%3A58Z&sr=b&sp=r&sig=nTbt8sPheK9B3YXLE1FDS%2F6XPag%2BC1gXLWUZFA5vhgQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:19 UTC, opbld30 commented
Docs Build status updates of commit _[98e3eb6](https://github.com/KyleWirpel/microsoft-graph-docs/commits/98e3eb62f9c032311914429b2d5ff7066f89b408)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-1cca731a3fe4e2ad570426b1136ecbe3-9a076733)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="1cca731a3fe4e2ad570426b1136ecbe3-9a076733"></a>
### [api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md)
 - **Line 15, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '.../resources/managedtenants-serviceusage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272316482583-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T23%3A19%3A16Z&sr=b&sp=r&sig=JGk9RXTdfuDf6ymuWkAHQyC0WcNzZWSLgaMs7IQmE2E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:20 UTC, idwilliams commented on changelog/Microsoft.MultiTenantPlatform.json
> +          }
@angelgolfer-ms I just made some updates and asked @Danielabom to double the changes to verify that I did not miss anything.

2022-01-27 23:21 UTC, opbld33 commented
Docs Build status updates of commit _[4b374d3](https://github.com/KyleWirpel/microsoft-graph-docs/commits/4b374d35d91cafaebcebbd6d52724bb4c18962d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) | [Details](#user-content-1cca731a3fe4e2ad570426b1136ecbe3-ed4bc95c)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="1cca731a3fe4e2ad570426b1136ecbe3-ed4bc95c"></a>
### [api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md)
 - **Line 15, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '.../resources/managedtenants-serviceusage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272317472791-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T23%3A21%3A13Z&sr=b&sp=r&sig=ibZbxsr9phHYZTLU1rarLL8XuyOK7x6ibhQ62tat25M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:24 UTC, opbld34 commented
Docs Build status updates of commit _[feb4d54](https://github.com/KyleWirpel/microsoft-graph-docs/commits/feb4d5416f73271cf9c6f889f6317afb49e648da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272321583235-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T23%3A24%3A03Z&sr=b&sp=r&sig=QH8dNKzhnanNb2xRqfr9QwGk2bXx8KdTKUusLJU%2BKAU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:26 UTC, idwilliams commented on changelog/Microsoft.MultiTenantPlatform.json
> +        ],
@angelgolfer-ms I recently made this update and asked @Danielabom to double check that I have it correct.

2022-01-27 23:33 UTC, idwilliams commented
> @KyleWirpel , thanks for addressing the last set of comments. Just a couple more to enhance the descriptions with relevant links for SEO and navigation, and a couple about the changelog.
> 
> BTW, you have an API Doctor error - you see the red cross adjacent to the following line on this page: "microsoft-graph-docs apidoctor-beta Failing after 2m — Build #74429 failed"
> 
> Not sure if you had run into and fixed API Doctor errors before. If not, you might find this topic helpful the first time to look for the error: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211769/API-Doctor-validate-examples
> 
> If you follow those steps, you'd see your error on this [page](https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=74429&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=60418): "Publishing metadata... Finished publishing metadata. Error: /api/managedtenants-managedtenant-list-tenantusage.md: FileNotFound: '[.../resources/managedtenants-serviceusage.md](monthly usage data for each service)'. "
> 
> There in managedtenants-managedtenant-list-tenantusage.md, you see the three dots instead of two, in that link to managedtenants-serviceusage.md. I'll let you fix it. :-)

Just got this one fixed.

2022-02-01 20:23 UTC, isvargasmsft commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the **tenantUsage** navigation property to the [managedTenant](https://docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta
Line 528: Please remove the localization (en-us) from the link. Apply to all links where applicable.

2022-02-01 20:23 UTC, isvargasmsft commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the **tenantOnboardingEligibilityReason** property to [tenantStatusInformation](https://docs.microsoft.com/en-us/graph/api/resources/tenantStatusInformation?view=gra
Line 494: Please remove the localization from the link: "/en-us"

2022-02-01 20:24 UTC, isvargasmsft commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [apply](https://docs.microsoft.com/en-us/graph/api/managementAction-apply?view=graph-rest-1.0) method to the [managementAction](https://docs.microsoft.com/en-us/
Please remove localization in the link

2022-02-01 20:24 UTC, isvargasmsft commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [apply](https://docs.microsoft.com/en-us/graph/api/managementAction-apply?view=graph-rest-1.0) method to the [managementAction](https://docs.microsoft.com/en-us/
Please apply to all other links in this changelog.

2022-02-01 20:28 UTC, Danielabom requested changes
Please review the comments regarding localization in some links. Go to the changelog.

2022-02-01 21:23 UTC, KyleWirpel commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the **tenantUsage** navigation property to the [managedTenant](https://docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta
All instances of localization have been removed.

2022-02-01 21:23 UTC, KyleWirpel commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the **tenantOnboardingEligibilityReason** property to [tenantStatusInformation](https://docs.microsoft.com/en-us/graph/api/resources/tenantStatusInformation?view=gra
All instances of localization have been removed.

2022-02-01 21:24 UTC, KyleWirpel commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [apply](https://docs.microsoft.com/en-us/graph/api/managementAction-apply?view=graph-rest-1.0) method to the [managementAction](https://docs.microsoft.com/en-us/
All instances of localization have been removed.

2022-02-01 21:24 UTC, opbld31 commented
Docs Build status updates of commit _[b98267a](https://github.com/KyleWirpel/microsoft-graph-docs/commits/b98267a71351a60d10fdbfba044b4a970f0f447d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202012122492425-15424%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T21%3A24%3A58Z&sr=b&sp=r&sig=0rQLPzPFhUapu2LP4S5ihg71JCqpkA%2FJt6Ti6jqI3dc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 21:31 UTC, idwilliams commented
@Danielabom and @isvargasmsft we have PR #15663 to address all the other issues with the changelog. There are some broken links and various localization issues that were introduced through another change that is not related to this one. So, we wanted to get everything corrected in one change since there were other issues unrelated to this change.

2022-02-02 17:16 UTC, Danielabom approved these changes

2022-05-05 19:39 UTC, opbld30 commented
Docs Build status updates of commit _[a7c3228](https://github.com/KyleWirpel/microsoft-graph-docs/commits/a7c3228521657158cabf7e3ff1a47a9da783b1fb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-09f6ae39)

<a id="09f6ae39"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205051939056352-15424%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T19%3A39%3A43Z&sr=b&sp=r&sig=XteSwMnDZPrKMkIjjZMRrcgxOBTgej7iPB81dPu2lck%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 20:03 UTC, opbld30 commented
Docs Build status updates of commit _[06473d2](https://github.com/KyleWirpel/microsoft-graph-docs/commits/06473d2fa2a68f08dfeda8b4ea4a1c46f60afe9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205051959391638-15424%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T20%3A03%3A18Z&sr=b&sp=r&sig=Q2CX5fGZsNjOudpzfT6ydG1w2OlTONu90fxBFLdR2NQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 03:57 UTC, Lauragra commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +title: "List tenantUsages"
Is the navigation property name singular or plural? Please make sure the title and H1 match.

2022-05-06 03:59 UTC, Lauragra commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|[List tenantUsages](../api/managedtenants-managedtenant-list-tenantusage.md)|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|Get a list of the [te
Please update the description for this method to match the description in the method topic.

2022-05-06 04:00 UTC, Lauragra commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +|serviceName|String|Name of the service. Example services: `Excel`, `Exchange`, `Intune`, `Outlook`, `Teams`, `Word`. Required. Read-only.|
Are these the only possible values, or just examples of values? If they're the only possible values, we should state that explicitly, i.e. "The following are the possible values:".

2022-05-06 04:02 UTC, Lauragra commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [serviceUsage](https://docs.microsoft.com/graph/api/resources/managedtenants-serviceUsage?view=graph-rest-beta) resource",
Please make sure that the descriptions consistently end with a period.

2022-05-06 04:04 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List tenant usage
We can streamline the TOC here by not including the resource name, since this is a CRUD operation, so please change the entry for the operation to "List".

2022-05-12 19:25 UTC, opbld34 commented
Docs Build status updates of commit _[ee571d5](https://github.com/KyleWirpel/microsoft-graph-docs/commits/ee571d584a0b183058d45867562d7ee4870bd9dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121922218276-15424/BuildReport?accessString=a156d0afcaf95c42d5194b61c8fa0210ee28fa45e7cdd25435c7ff0e984070ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 19:33 UTC, idwilliams commented on api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
> +title: "List tenantUsages"
This has been addressed it should be singular.

2022-05-12 19:36 UTC, opbld32 commented
Docs Build status updates of commit _[cbf3348](https://github.com/KyleWirpel/microsoft-graph-docs/commits/cbf3348cbbfa8fbcb85a7b1f763ffe74fe38b9ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121933171990-15424/BuildReport?accessString=f8e31095311dc5b15421d3d903785bcb9f6035782be1082dd684a8b7841757fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 19:42 UTC, opbld32 commented
Docs Build status updates of commit _[2f608bd](https://github.com/KyleWirpel/microsoft-graph-docs/commits/2f608bde789e49d99bf1e0fd1f0e6fc7d6e5b8e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121940095040-15424/BuildReport?accessString=76524b2c3e356adba7572eef803abb94221d70a9589eaf4bef28f0f429eef1ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 19:43 UTC, idwilliams commented on api-reference/beta/resources/managedtenants-tenantusage.md
> +|[List tenantUsages](../api/managedtenants-managedtenant-list-tenantusage.md)|[microsoft.graph.managedTenants.tenantUsage](../resources/managedtenants-tenantusage.md) collection|Get a list of the [te
This update has been made.

2022-05-12 19:44 UTC, opbld33 commented
Docs Build status updates of commit _[7928fb0](https://github.com/KyleWirpel/microsoft-graph-docs/commits/7928fb01cb051f58d7732980a55656042df662d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121941364775-15424/BuildReport?accessString=207a4fcd182bbbe82aa66668e6369dc3b99a210f1af69b9d9e6c1824a3abebe3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 19:48 UTC, idwilliams commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +|serviceName|String|Name of the service. Example services: `Excel`, `Exchange`, `Intune`, `Outlook`, `Teams`, `Word`. Required. Read-only.|
We are following up with the team that owns the data we are ingesting for this. If they have a fixed list, then we will revise this statement following your recommendation.

2022-05-12 19:50 UTC, idwilliams commented on changelog/Microsoft.MultiTenantPlatform.json
> +            "Description": "Added the [serviceUsage](https://docs.microsoft.com/graph/api/resources/managedtenants-serviceUsage?view=graph-rest-beta) resource",
This is a good catch; a period has been added to the two sentences where a period was missing.

2022-05-12 19:51 UTC, opbld31 commented
Docs Build status updates of commit _[2633d7d](https://github.com/KyleWirpel/microsoft-graph-docs/commits/2633d7dc3f766665c9d47748abf41681e9b2a9cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121949377785-15424/BuildReport?accessString=57a25aad2539ff1e3a38b500c489d7ed1e8b49e58e9b5f0c13a0cb0a796a4858).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 19:52 UTC, idwilliams commented on api-reference/beta/toc.yml
> +          - name: List tenant usage
@Lauragra this is a great recommendation. I just made the change for the tenant usage line. There are a few other places in our documentation where this convention is not followed. Let's leave those for now, and we can open a separate PR to address those.

2022-05-12 19:54 UTC, opbld30 commented
Docs Build status updates of commit _[4c32f0c](https://github.com/KyleWirpel/microsoft-graph-docs/commits/4c32f0ce430795e631fef4b265ff624139d17ae1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121951281638-15424/BuildReport?accessString=74ab002d39ad54c8f11ed4e0267b996fbc60142f754d15d494bb3a049460c05b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 20:16 UTC, idwilliams commented on api-reference/beta/resources/managedtenants-serviceusage.md
> +|serviceName|String|Name of the service. Example services: `Excel`, `Exchange`, `Intune`, `Outlook`, `Teams`, `Word`. Required. Read-only.|
The source for this data does not have a defined list of values that could be present in this property. So, I have updated the wording to avoid us providing a list. That way we do not inadvertently cause any confusion.

2022-05-12 20:17 UTC, opbld31 commented
Docs Build status updates of commit _[67f94b2](https://github.com/KyleWirpel/microsoft-graph-docs/commits/67f94b2eede9b400a73b33b41bf048b76687a78b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205122015236744-15424/BuildReport?accessString=b4fa020f6ddab8b3524144ec0ffb5cfaa19e047dfa217eaecbdc755c05c06b1f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 05:15 UTC, opbld33 commented
Docs Build status updates of commit _[d055fad](https://github.com/KyleWirpel/microsoft-graph-docs/commits/d055fad442f6a7f70747588b98832300ab23c6fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-managedtenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-serviceusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-serviceusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-serviceusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-tenantusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-tenantusage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenantusage?view=graph-rest-beta&branch=pr-en-us-15424) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/KyleWirpel/microsoft-graph-docs/blob/users/kywirpel/tenantusage/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205130513114674-15424/BuildReport?accessString=357ab17c4850526cc1943997127f4c5e426b647ee398ab01315489e9ace8b24a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 05:22 UTC, merged