Create external-identity-policy.md
microsoftgraph/microsoft-graph-docs pull request #15444
Opened 2022-01-10 07:54 UTC by KuiGithui

2022-01-10 07:57 UTC, opbld32 commented
Docs Build status updates of commit _[37775cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37775cfcef8cc8edc2a3a25bf444e63e3f1a18e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/external-identity-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/external-identity-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/external-identity-policy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-61c200696a06bc2af3efbfd45c5008bf-5f765acb)

<a id="61c200696a06bc2af3efbfd45c5008bf-5f765acb"></a>
### [api-reference/beta/api/external-identity-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/external-identity-policy.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201100754494586-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T07%3A57%3A16Z&sr=b&sp=r&sig=LoVyqEEKE%2BPbBvYg2xshiyEucQxtKB4iIchpLGXbOiY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 19:51 UTC, opbld34 commented
Docs Build status updates of commit _[1ee6eb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ee6eb59c7eb3121609cbbe6687803d5d1104f55)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101949205203-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T19%3A51%3A19Z&sr=b&sp=r&sig=CHWm1AQ8xckOo9ppnSsuXesHn%2BBLEB4JPDNlxUFNum8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 20:56 UTC, opbld32 commented
Docs Build status updates of commit _[e2e1acf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2e1acfea9ea31cd8305243ced534290fd699d27)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-166d1380236671ff17d4991b00e708e6-07126c08)

<a id="166d1380236671ff17d4991b00e708e6-07126c08"></a>
### [api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalidentitiespolicy-get.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalidentitiespolicy-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201102054527657-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T20%3A56%3A51Z&sr=b&sp=r&sig=aXZoezeD%2BH73bBYHGSiicEefT1VQ9B5aes182Xet%2F1g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 21:26 UTC, opbld32 commented
Docs Build status updates of commit _[f19db1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f19db1cd6d80b0739c9516396ede76ce25a38e4f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-166d1380236671ff17d4991b00e708e6-30bad6b3)
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |

<a id="166d1380236671ff17d4991b00e708e6-30bad6b3"></a>
### [api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalidentitiespolicy-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201102124597892-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T21%3A26%3A57Z&sr=b&sp=r&sig=F81J4GIKrkTft2mL0Cna%2BiDTuXzfZKRIQ7KjfLdK2l8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 21:40 UTC, opbld31 commented
Docs Build status updates of commit _[3b65a08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b65a08c39ee67be5414e2d24bbcc4357b5141da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-166d1380236671ff17d4991b00e708e6-24aff6e7)
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |

<a id="166d1380236671ff17d4991b00e708e6-24aff6e7"></a>
### [api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalidentitiespolicy-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201102138157693-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T21%3A40%3A36Z&sr=b&sp=r&sig=BUvvyD%2B2xIE6gYkckRfqKpGGumdBVwVT61dp3%2FMSWv0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 10:19 UTC, opbld33 commented
Docs Build status updates of commit _[de07678](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de0767802716715fa908f0492ab84910af739fa3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201111017374683-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T10%3A19%3A41Z&sr=b&sp=r&sig=Z8BUU12xg52GD8WkKmlb%2FAnqFV73Nxnvv9LiYBGkmFo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 09:27 UTC, opbld34 commented
Docs Build status updates of commit _[a5a2690](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5a2690273086b656157dc57cf3a33616afc9f22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201120925105383-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T09%3A27%3A08Z&sr=b&sp=r&sig=2RLUrWKrSojsTQHC1PjXGQnEJgNMvMsgkP9H4XIv6F8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 09:45 UTC, opbld33 commented
Docs Build status updates of commit _[df7cd89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df7cd89154de210318a6b0b1d7ac6c36e5cf613c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201130943456151-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T09%3A45%3A40Z&sr=b&sp=r&sig=Kp5jk4cew90K1nRnuB4toDy9uJGR3e8480oeK9AZZYc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 10:01 UTC, opbld32 commented
Docs Build status updates of commit _[0e2f63b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e2f63bfe4cbc73d3374afe8972ecd720e3dcafa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201130959160410-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T10%3A01%3A19Z&sr=b&sp=r&sig=r3sw411jH94wwzVEaTevedNV6L9CW0wkfnbC9EMYsXw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 14:38 UTC, opbld32 commented
Docs Build status updates of commit _[b6bb5de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6bb5de413049d1be383f4ca9fd64d5007dc0ed4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131436313767-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T14%3A38%3A28Z&sr=b&sp=r&sig=4olekI%2BQDmNQeOUhFvuylq2LkOw6XZ0Na7anfrLpdGY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 12:56 UTC, bashirkunya approved these changes

2022-01-17 13:55 UTC, bashirkunya commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +[!INCLUDE [In the request body, supply the values for relevant fields that should be updated. Existing properties that are not included in the request body will maintain their previous values or be r
This text should not be in brackets

2022-01-18 08:09 UTC, opbld33 commented
Docs Build status updates of commit _[245ce63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/245ce6314137d7018d497511dcc35dcfba489b44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180807158651-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T08%3A09%3A14Z&sr=b&sp=r&sig=Hspvfc2odXhFqEpVpYDEvuK84awBZElweXZcGeDqB%2BA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 07:06 UTC, opbld31 commented
Docs Build status updates of commit _[ecfb087](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecfb0874ff0762e2ae286b86e5efc389bc8863a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190704145449-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T07%3A06%3A22Z&sr=b&sp=r&sig=f4zAIrE9xMf%2BVmbfObKJvbYxoKzwAdGpz9bi5oBGIMw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 07:51 UTC, FaithOmbongi requested changes
Thank you @KuiGithui for working on this PR. I've recommended some minor fixes. The only gap:
- Please document the **externalIdentitiesPolicy** relationship in [policyRoot](https://docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta).

And we'll be good to go.

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/resources/externalidentitiespolicy.md
> +description: "Resources for External Identities Policy"
Ideally, could be similar to the first sentence of the description below. Also good for SEO.
```suggestion
description: "Represents the tenant-wide policy that controls whether external users can leave an Azure AD tenant via self-service controls."
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/resources/externalidentitiespolicy.md
> +Gives tenant administrator control over external identities by allowing or restricting external identities to leave an organization via self-service controls. When permitted by the administrator, ext
Suggestion to be explicit about what these self-service capabilities are/allowed them to do
```suggestion
Represents the tenant-wide policy that controls whether external users can leave the guest Azure AD tenant via self-service controls. When permitted by the administrator, external users can leave the guest Azure AD tenant through the **organizations** menu of the [My Account](https://myaccount.microsoft.com/) portal.
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/resources/externalidentitiespolicy.md
> +|displayName|String|Contains string data for policy display information. Inherited from [policyBase](../resources/policybase.md).|
```suggestion
|allowDeletedIdentitiesDataRemoval|Boolean|Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home tenant. |
|allowExternalIdentitiesToLeave|Boolean|Defines whether external users can leave the guest tenant. If set to `false`, self-service controls are not enabled, and the admin of the guest tenant must manually remove the external user from the guest tenant.|
|displayName|String|The policy name. Inherited from [policyBase](../resources/policybase.md).|
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/resources/externalidentitiespolicy.md
> +}
The JSON representation has data types and shouldn't be confused with a response object.
Added the properties inherited from policyBase and upstream resources/base types.
```suggestion
{
  "@odata.type": "#microsoft.graph.externalIdentitiesPolicy",
  "id": "String (identifier)",
  "deletedDateTime": "String (timestamp)",
  "description": "String",
  "displayName": "String",
  "allowExternalIdentitiesToLeave": "Boolean",
  "allowDeletedIdentitiesDataRemoval": "Boolean"
}
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-get.md
> +description: "Read the properties and relationships of an externalIdentitiesPolicy object."
Suggestion to make it user/SEO friendly
```suggestion
description: "Read the properties and relationships of the tenant-wide externalIdentitiesPolicy object that controls whether external users can leave an Azure AD tenant via self-service controls."
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-get.md
> +Read the properties and relationships of an [externalIdentitiesPolicy](../resources/externalidentitiespolicy.md) object.
```suggestion
Read the properties and relationships of the tenant-wide [externalIdentitiesPolicy](../resources/externalidentitiespolicy.md) object that controls whether external users can leave an Azure AD tenant via self-service controls.
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
I see query parameters are marked as unsupported in your API.md
```suggestion
This method does not support the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-get.md
> +GET https://graph.microsoft.com/v1.0/policies/externalidentitiespolicy
```suggestion
GET https://graph.microsoft.com/beta/policies/externalIdentitiesPolicy
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-get.md
> +    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#policies/externalIdentitiesPolicy/$entity",
```suggestion
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#policies/externalIdentitiesPolicy/$entity",
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +description: "Update the properties of an externalIdentitiesPolicy object."
```suggestion
description: "Update the settings of the tenant-wide externalIdentitiesPolicy object that controls whether external users can leave an Azure AD tenant via self-service controls."
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +Update the properties of an [externalIdentitiesPolicy](../resources/externalidentitiespolicy.md) object.
```suggestion
Update the settings of the tenant-wide [externalIdentitiesPolicy](../resources/externalidentitiespolicy.md) object that controls whether external users can leave an Azure AD tenant via self-service controls.
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +|allowExternalIdentitiesToLeave|Boolean|The setting will inform AAD whether allow or restrict external identities to leave the tenant.If set to false, self service is not enabled, and therefore admin
Aligning with the descriptions in the properties table
```suggestion
|allowDeletedIdentitiesDataRemoval|Boolean|Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home tenant. Required.|
|allowExternalIdentitiesToLeave|Boolean|Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home tenant. Required.|
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +## Example 1: Update or set external identity not to leave tenant.
You have only 1 example, so no need for this.
```suggestion
```

2022-01-19 07:51 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +PATCH https://graph.microsoft.com/v1.0/policies/externalidentitiespolicy
```suggestion
PATCH https://graph.microsoft.com/beta/policies/externalIdentitiesPolicy
```

2022-01-19 07:51 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [externalIdentitiesPolicy](https://docs.microsoft.com/en-us/graph/api/resources/externalIdentitiesPolicy?view=graph-rest-beta) resource",
Recommending a little more info to the customer.
```suggestion
          "Description": "Added the [externalIdentitiesPolicy](https://docs.microsoft.com/en-us/graph/api/resources/externalIdentitiesPolicy?view=graph-rest-beta) resource and associated methods. The external identity policy represents the tenant-wide policy that controls whether external users can leave an Azure AD tenant via self-service controls.",
```

2022-01-19 08:01 UTC, FaithOmbongi commented on api-reference/beta/api/externalidentitiespolicy-update.md
> +[!INCLUDE [In the request body, supply the values for relevant fields that should be updated. Existing properties that are not included in the request body will maintain their previous values or be r
+1, this was the cause of the validation error.

2022-01-19 08:42 UTC, opbld34 commented
Docs Build status updates of commit _[c99be3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c99be3a0cb0b24f8092f12c6d67586f76194d786)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190838191496-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T08%3A42%3A10Z&sr=b&sp=r&sig=18caG12xpkunTIxgyvOJRA4L8CwQTLgmNr3cLr%2Berqc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 08:56 UTC, opbld34 commented
Docs Build status updates of commit _[1022e24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1022e24eeb98607617d3e5192a7aa466ee332539)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190852540791-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T08%3A56%3A55Z&sr=b&sp=r&sig=EHEjKGWoTnOeLxm3bvK9M0YUsiSGlgi0P9b3h5zbMS8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 08:59 UTC, opbld30 commented
Docs Build status updates of commit _[30b76b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30b76b3f9be8839393fc570486b4defee4f684b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190854540666-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T08%3A59%3A18Z&sr=b&sp=r&sig=jC%2FxfsQk%2BvkuKuX0TtqlawZQmOHj2A7hmL5uKCyai%2Fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:01 UTC, opbld34 commented
Docs Build status updates of commit _[25251f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25251f75124391261d89d8ca2390bb28f9e1f8aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190859056176-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A01%3A46Z&sr=b&sp=r&sig=xxM3T2hHXEiXQPuI%2F%2FsccHMn4rxN56cVaMlFdGGoDVA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:20 UTC, opbld30 commented
Docs Build status updates of commit _[0d7f42a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d7f42a95a5f0aa3fe228648385145493a5c4081)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190917433198-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A20%3A34Z&sr=b&sp=r&sig=fNpLya7KwTllDM33Y0t79%2FP%2FBIeQg8ZlwUukT1niNo8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 09:22 UTC, opbld31 commented
Docs Build status updates of commit _[9934dc5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9934dc5e6c89807cbc64be3ad11dda1bf9e73eb5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190918025098-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T09%3A22%3A51Z&sr=b&sp=r&sig=uZ6zlKrteA84zLNV%2B0Y7rKo4O6yAkVFjQPhxZrqZhIk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 10:07 UTC, opbld32 commented
Docs Build status updates of commit _[fc089da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc089da950b515aec3d7b268c3847ba7729eae5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191005118916-15444%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A07%3A22Z&sr=b&sp=r&sig=tEsvqdxlMaX3XRfdkbxGr4z6ZISqIxFcz2z9EFn00Xc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 13:54 UTC, opbld33 commented
Docs Build status updates of commit _[fc089da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc089da950b515aec3d7b268c3847ba7729eae5e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f1cc8158)

<a id="f1cc8158"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206211353241459-15444/BuildReport?accessString=3001ff600bd8188ee7549df650a10f66b2564743f6a96f6a83cf9285c09ff28d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 10:47 UTC, opbld33 commented
Docs Build status updates of commit _[7139bc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7139bc9b6c224e69c5478b7f96ea4ea98d611189)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-72702d50608248b7e512712bc1e1bed9-ed939cc5)
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |

<a id="72702d50608248b7e512712bc1e1bed9-ed939cc5"></a>
### [api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md)
 - **Line 23, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 48, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< HEAD
| Relationship                              | Type                                                                                                      | Description                                                                                                                                                             |
|:------------------------------------------|:----------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| accessReviewPolicy                        | accessReviewPolicy                                                               | The policy that contains directory-level access review settings.                                                                                                        |
| activityBasedTimeoutPolicies              | activityBasedTimeoutPolicy collection                                    | The policy that controls the idle time out for web sessions for applications.                                                                                           |
| adminConsentRequestPolicy                 | adminConsentRequestPolicy                                                 | The policy by which consent requests are created and managed for the entire tenant.                                                                                     |
| appManagementPolicies                     | appManagementPolicy collection                                                  | The policies that enforce app management restrictions for specific applications and service principals, overriding the defaultAppManagementPolicy.                      |
| authenticationFlowsPolicy                 | authenticationFlowsPolicy                                                 | The policy configuration of the self-service sign-up experience of external users.                                                                                      |
| authenticationMethodsPolicy               | authenticationMethodsPolicy                                             | The authentication methods and the users that are allowed to use them to sign in and perform multi-factor authentication (MFA) in Azure Active Directory (Azure AD).    |
| authorizationPolicy                       | authorizationPolicy collection                                                  | The policy that controls Azure AD authorization settings.                                                                                                               |
| b2cAuthenticationMethodsPolicy            | b2cAuthenticationMethodsPolicy                                       | The Azure AD B2C policies that define how end users register via local accounts.                                                                                        |
| claimsMappingPolicies                     | claimsMappingPolicy collection                                                  | The claim-mapping policies for WS-Fed, SAML, OAuth 2.0, and OpenID Connect protocols, for tokens issued to a specific application.                                      |
| conditionalAccessPolicies                 | conditionalAccessPolicy                                                     | The custom rules that define an access scenario.                                                                                                                        |
| defaultAppManagementPolicy                | tenantAppManagementPolicy                                                 | The tenant-wide policy that enforces app management restrictions for all applications and service principals.                                                           |
| deviceRegistrationPolicy                  | deviceRegistrationPolicy                                                   | Represents the policy scope that controls quota restrictions, additional authentication, and authorization policies to register device identities to your organization. |
| externalIdentitiesPolicy                  | externalIdentitiesPolicy                                                   | Represents the tenant-wide policy that controls whether external users can leave an Azure AD tenant via self-service controls. |
| featureRolloutPolicies                    | featureRolloutPolicy collection                                                | The feature rollout policy associated with a directory object.                                                                                                          |
| homeRealmDiscoveryPolicies                | homeRealmDiscoveryPolicy collection                                        | The policy to control Azure AD authentication behavior for federated users.                                                                                             |
| identitySecurityDefaultsEnforcementPolicy | identitySecurityDefaultsEnforcementPolicy                 | The policy that represents the security defaults that protect against common attacks.                                                                                   |
| mobileAppManagementPolicies               | mobilityManagementPolicy collection                                        | The policy that defines auto-enrollment configuration for a mobility management (MDM or MAM) application.                      [...]

2022-06-22 18:45 UTC, opbld32 commented
Docs Build status updates of commit _[37c159e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37c159e27822691ee761f3ea8fc93c6ead0915a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-72702d50608248b7e512712bc1e1bed9-562f4d57)
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |

<a id="72702d50608248b7e512712bc1e1bed9-562f4d57"></a>
### [api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md)
 - **Line 23, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 48, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< HEAD
| Relationship                              | Type                                                                                                      | Description                                                                                                                                                             |
|:------------------------------------------|:----------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| accessReviewPolicy                        | accessReviewPolicy                                                               | The policy that contains directory-level access review settings.                                                                                                        |
| activityBasedTimeoutPolicies              | activityBasedTimeoutPolicy collection                                    | The policy that controls the idle time out for web sessions for applications.                                                                                           |
| adminConsentRequestPolicy                 | adminConsentRequestPolicy                                                 | The policy by which consent requests are created and managed for the entire tenant.                                                                                     |
| appManagementPolicies                     | appManagementPolicy collection                                                  | The policies that enforce app management restrictions for specific applications and service principals, overriding the defaultAppManagementPolicy.                      |
| authenticationFlowsPolicy                 | authenticationFlowsPolicy                                                 | The policy configuration of the self-service sign-up experience of external users.                                                                                      |
| authenticationMethodsPolicy               | authenticationMethodsPolicy                                             | The authentication methods and the users that are allowed to use them to sign in and perform multi-factor authentication (MFA) in Azure Active Directory (Azure AD).    |
| authorizationPolicy                       | authorizationPolicy collection                                                  | The policy that controls Azure AD authorization settings.                                                                                                               |
| b2cAuthenticationMethodsPolicy            | b2cAuthenticationMethodsPolicy                                       | The Azure AD B2C policies that define how end users register via local accounts.                                                                                        |
| claimsMappingPolicies                     | claimsMappingPolicy collection                                                  | The claim-mapping policies for WS-Fed, SAML, OAuth 2.0, and OpenID Connect protocols, for tokens issued to a specific application.                                      |
| conditionalAccessPolicies                 | conditionalAccessPolicy                                                     | The custom rules that define an access scenario.                                                                                                                        |
| defaultAppManagementPolicy                | tenantAppManagementPolicy                                                 | The tenant-wide policy that enforces app management restrictions for all applications and service principals.                                                           |
| deviceRegistrationPolicy                  | deviceRegistrationPolicy                                                   | Represents the policy scope that controls quota restrictions, additional authentication, and authorization policies to register device identities to your organization. |
| externalIdentitiesPolicy                  | externalIdentitiesPolicy                                                   | Represents the tenant-wide policy that controls whether external users can leave an Azure AD tenant via self-service controls. |
| featureRolloutPolicies                    | featureRolloutPolicy collection                                                | The feature rollout policy associated with a directory object.                                                                                                          |
| homeRealmDiscoveryPolicies                | homeRealmDiscoveryPolicy collection                                        | The policy to control Azure AD authentication behavior for federated users.                                                                                             |
| identitySecurityDefaultsEnforcementPolicy | identitySecurityDefaultsEnforcementPolicy                 | The policy that represents the security defaults that protect against common attacks.                                                                                   |
| mobileAppManagementPolicies               | mobilityManagementPolicy collection                                        | The policy that defines auto-enrollment configuration for a mobility management (MDM or MAM) application.                      [...]

2022-06-26 09:07 UTC, opbld32 commented
Docs Build status updates of commit _[c686318](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c686318c4b4c4b8097e9ce018fee158053f695c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) | [Details](#user-content-72702d50608248b7e512712bc1e1bed9-9690a200)
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="72702d50608248b7e512712bc1e1bed9-9690a200"></a>
### [api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md)
 - **Line 23, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 48, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< HEAD
| Relationship                              | Type                                                                                                      | Description                                                                                                                                                             |
|:------------------------------------------|:----------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| accessReviewPolicy                        | accessReviewPolicy                                                               | The policy that contains directory-level access review settings.                                                                                                        |
| activityBasedTimeoutPolicies              | activityBasedTimeoutPolicy collection                                    | The policy that controls the idle time out for web sessions for applications.                                                                                           |
| adminConsentRequestPolicy                 | adminConsentRequestPolicy                                                 | The policy by which consent requests are created and managed for the entire tenant.                                                                                     |
| appManagementPolicies                     | appManagementPolicy collection                                                  | The policies that enforce app management restrictions for specific applications and service principals, overriding the defaultAppManagementPolicy.                      |
| authenticationFlowsPolicy                 | authenticationFlowsPolicy                                                 | The policy configuration of the self-service sign-up experience of external users.                                                                                      |
| authenticationMethodsPolicy               | authenticationMethodsPolicy                                             | The authentication methods and the users that are allowed to use them to sign in and perform multi-factor authentication (MFA) in Azure Active Directory (Azure AD).    |
| authorizationPolicy                       | authorizationPolicy collection                                                  | The policy that controls Azure AD authorization settings.                                                                                                               |
| b2cAuthenticationMethodsPolicy            | b2cAuthenticationMethodsPolicy                                       | The Azure AD B2C policies that define how end users register via local accounts.                                                                                        |
| claimsMappingPolicies                     | claimsMappingPolicy collection                                                  | The claim-mapping policies for WS-Fed, SAML, OAuth 2.0, and OpenID Connect protocols, for tokens issued to a specific application.                                      |
| conditionalAccessPolicies                 | conditionalAccessPolicy                                                     | The custom rules that define an access scenario.                                                                                                                        |
| defaultAppManagementPolicy                | tenantAppManagementPolicy                                                 | The tenant-wide policy that enforces app management restrictions for all applications and service principals.                                                           |
| deviceRegistrationPolicy                  | deviceRegistrationPolicy                                                   | Represents the policy scope that controls quota restrictions, additional authentication, and authorization policies to register device identities to your organization. |
| externalIdentitiesPolicy                  | externalIdentitiesPolicy                                                   | Represents the tenant-wide policy that controls whether external users can leave an Azure AD tenant via self-service controls. |
| featureRolloutPolicies                    | featureRolloutPolicy collection                                                | The feature rollout policy associated with a directory object.                                                                                                          |
| homeRealmDiscoveryPolicies                | homeRealmDiscoveryPolicy collection                                        | The policy to control Azure AD authentication behavior for federated users.                                                                                             |
| identitySecurityDefaultsEnforcementPolicy | identitySecurityDefaultsEnforcementPolicy                 | The policy that represents the security defaults that protect against common attacks.                                                                                   |
| mobileAppManagementPoli [...]

2022-06-27 14:21 UTC, opbld34 commented
Docs Build status updates of commit _[24127b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24127b7d93b74233dd909f473f59e39d5fc08333)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206271418338019-15444/BuildReport?accessString=02aaf30e23decb44f823b55e500a5bd946a6ef4f6e46b904d97e595c8cd630bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-27 14:29 UTC, opbld30 commented
Docs Build status updates of commit _[e7fe245](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7fe2455321f613ec2a023fb4ed97b8dcf35d69f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206271427149486-15444/BuildReport?accessString=c91d32a3bae1698d37bbcbfa7c1ae41d95003d13ec5500b21f8ceb0bb6d155a2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-27 14:41 UTC, opbld31 commented
Docs Build status updates of commit _[135d6c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/135d6c7fb3229667e6468f74c9419b4673d3e701)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206271439272546-15444/BuildReport?accessString=00bccf781b6681e3fac3edf8c681fd79d8ce0846ad58f2e18236e44ec3a114e2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-27 15:01 UTC, opbld30 commented
Docs Build status updates of commit _[e4fa36a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4fa36afd3c3b3175309db768bfbe5ced69495a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-15444) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marthagithui-externalidentitiespolicyAPI/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206271459252371-15444/BuildReport?accessString=35f3d512c083240ab2bc5ccf5fcc9c0142871d1a5c4ebfc6359e6369d537e86a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 03:38 UTC, merged