[Azure AD roles] List transitiveRoleAssignments method
microsoftgraph/microsoft-graph-docs pull request #15458
Opened 2022-01-11 00:30 UTC by rolyon

2022-01-11 00:32 UTC, opbld34 commented
Docs Build status updates of commit _[450c291](https://github.com/microsoftgraph/microsoft-graph-docs/commits/450c29111e6b6ce2520bb29a497cc2790635da8f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) | [Details](#user-content-a39d854faa582dcd99d350ff1f687574-10067011)
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a39d854faa582dcd99d350ff1f687574-10067011"></a>
### [api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-identity-platform'.`````
 - **Line 16, Column 244**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/roles/groups-concept' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110030196852-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T00%3A32%3A21Z&sr=b&sp=r&sig=G9tpLlBGj3iwLDTktcA4jAo0eTNAFxIqa3dy7%2FSk5TY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 00:49 UTC, opbld31 commented
Docs Build status updates of commit _[b343c75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b343c75a781e9c0f46e9befed1513cf1a37c29d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110047085055-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T00%3A49%3A09Z&sr=b&sp=r&sig=P01mgmyDXQtpUPSgQaa%2FdZSiJCqyk8E9ph6TSh5IIuA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 01:07 UTC, opbld30 commented
Docs Build status updates of commit _[7afc235](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7afc2350dc1bf29e2fa8fcca84498ff7e3062445)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110105552028-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T01%3A07%3A57Z&sr=b&sp=r&sig=LoDQb0YfcoxcP1uENXoMQlKu3f070gM2yyvVReMDGY0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 01:25 UTC, opbld34 commented
Docs Build status updates of commit _[9bb307b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bb307b52a09c9997bff89c4aa9555e4f9ab5de1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110123530533-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T01%3A25%3A37Z&sr=b&sp=r&sig=unNbN38TJlQ%2Fqa%2F%2BAYjFJdnwadOINrHd0o5XQFxy78M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 01:39 UTC, opbld31 commented
Docs Build status updates of commit _[bb6ec87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb6ec8715be9ca767825c5d31a98abefcb028bf9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-roleassignments-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110137200866-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T01%3A39%3A23Z&sr=b&sp=r&sig=ap4Un2VwnRcMmfnovWwYVBn%2FKr%2F%2F9o8ndfVw9KLzlP4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 02:21 UTC, opbld33 commented
Docs Build status updates of commit _[667e85d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/667e85d14b73bf263e4aca7b56b9affbf4c90c44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroleassignment-list-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/unifiedroleassignment-list-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110219567823-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T02%3A21%3A56Z&sr=b&sp=r&sig=pCI6OZ4IDlERNP3e9YHr0v4zfu6XkJTP4GrOMirerqQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-22 00:00 UTC, opbld32 commented
Docs Build status updates of commit _[af8a680](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af8a68006b1033603f7d34510b0b90392d40640d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroleassignment-list-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/unifiedroleassignment-list-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201212358319901-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-22T00%3A00%3A35Z&sr=b&sp=r&sig=GBcDqXV5LDiYHEPVK9KzB55rgSCgQB6sPNAcA1ONQmY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 17:43 UTC, abhijeetsinha commented
@rolyon - changes look good to me

2022-01-24 17:43 UTC, abhijeetsinha approved these changes

2022-02-09 08:07 UTC, FaithOmbongi requested changes
Thank you @rolyon for your work on this PR. The major change requests are:
- Please add the **transitiveRoleAssignments** relationship to [rbacApplication](https://docs.microsoft.com/en-us/graph/api/resources/rbacApplication?view=graph-rest-beta) resource.
- I assume that the **transitiveRoleAssignments** relationship in [rbacApplicationMultiple](https://docs.microsoft.com/en-us/graph/api/resources/rbacApplicationMultiple?view=graph-rest-beta) isn't going public in this release? I see it referenced in the API.md but not the schema PR.
- (Let's follow this up internally) Could we get the opt-in to test this in a demo tenant? Then we can have contextual examples that customers can correlate with the scenario you provide in the doc.

2022-02-09 08:07 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: api/unifiedroleassignment-list-transitive.md
```suggestion
            - name: List transitive role assignments
              href: api/rbacapplication-list-transitiveroleassignments.md
```

2022-02-09 08:07 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
Please move your changelog to be the first object in the file, starting from line 3.
Added a changelist object for the new relationship
```suggestion
        {
          "Id": "1c8b1db6-2c25-402f-9bcd-3f5f0fae5a53",
          "ApiChange": "Relationship",
          "ChangedApiName": "transitiveRoleAssignments",
          "ChangeType": "Addition",
          "Description": "Added the **transitiveRoleAssignments** relationship to the [rbacApplication](https://docs.microsoft.com/en-us/graph/api/resources/rbacApplication?view=graph-rest-beta) resource.",
          "Target": "rbacApplication"
        },
        { 
          "Id": "1c8b1db6-2c25-402f-9bcd-3f5f0fae5a53",
          "ApiChange": "Method",
          "ChangedApiName": "transitiveRoleAssignments",
          "ChangeType": "Addition",
          "Description": "Added the [List transitiveRoleAssignments](https://docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive) method to the [unifiedRoleAssignment](https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta) resource.",
          "Target": "unifiedRoleAssignment"
        }
```

2022-02-13 20:51 UTC, opbld31 commented
Docs Build status updates of commit _[81d2f72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81d2f72e29196012e460451b145079fbbf2895d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroleassignment-list-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/unifiedroleassignment-list-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202132046514274-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-16T20%3A51%3A10Z&sr=b&sp=r&sig=o5Zx6%2BXOG4GM%2FoUGprpsxh7bSboZ3TMfoHGYnZMOWwI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-13 21:01 UTC, opbld31 commented
Docs Build status updates of commit _[4caa329](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4caa32978102ec5a5c9450865a41d299dbe897dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroleassignment-list-transitive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/unifiedroleassignment-list-transitive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-list-transitive?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202132057439763-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-16T21%3A01%3A23Z&sr=b&sp=r&sig=sfLCig9yCHbxjdsbDlwrwUXiFLQ3t35KPpPoFjb1AdM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-13 21:29 UTC, opbld30 commented
Docs Build status updates of commit _[7653732](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7653732608ebdd15a3133e87984e66b23940cb20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202132127429110-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-16T21%3A29%3A47Z&sr=b&sp=r&sig=%2FjcH4UtXlnzvKzYA2TXMvhPWP6bOwdL2pba5S9HVCkg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-13 21:59 UTC, opbld33 commented
Docs Build status updates of commit _[d5fce8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5fce8b64323654a71183b0602d4c95799cd2241)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202132157082421-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-16T21%3A59%3A12Z&sr=b&sp=r&sig=ZlYtpabSLdLM%2BhtPtHKLOLfgnoM4KXzE4YLh9wCd7To%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-13 22:13 UTC, rolyon commented on api-reference/beta/resources/rbacapplication.md
>  | [roleSchedules](../api/rbacapplication-roleschedules.md) | [unifiedRoleScheduleBase](unifiedroleschedulebase.md) collection | Function to retrieve a collection of unifiedRoleScheduleBase objects. |
Hi @FaithOmbongi 
Aren't relationships links types and not methods? The rbacApplication resource already has a link to the unifiedRoleAssignment resource.
If not, what relationship should be added?

2022-02-14 06:37 UTC, FaithOmbongi commented on api-reference/beta/resources/rbacapplication.md
>  | [roleSchedules](../api/rbacapplication-roleschedules.md) | [unifiedRoleScheduleBase](unifiedroleschedulebase.md) collection | Function to retrieve a collection of unifiedRoleScheduleBase objects. |
Hi @rolyon, the name of the new relationship is **transitiveRoleAssignments** and should be documented in the **Relationships** H2 section of this [rbacApplication](https://docs.microsoft.com/en-us/graph/api/resources/rbacApplication?view=graph-rest-beta) resource type page. And yes, its return type is **unifiedRoleAssignment**. Please see the schema:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/14026935/153812387-1be43dd8-32c0-42cd-b7c3-9e891ec4062e.png">

2022-02-14 18:06 UTC, opbld33 commented
Docs Build status updates of commit _[a35734c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a35734c1e18cb30c5e1d9e8df17020f14dd29842)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141803573994-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T18%3A06%3A21Z&sr=b&sp=r&sig=9Ht%2F4pL7PEbYUg7m3SLbL2%2FvUYpyL1%2F83NiNrmSRsU4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 18:21 UTC, opbld34 commented
Docs Build status updates of commit _[5b4d0d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b4d0d4ca2e62a96352e8cbaae2ffafc7477126e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141817115308-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T18%3A21%3A23Z&sr=b&sp=r&sig=ItLfywDiA6Q1k3cCqK8uMJHTjWF05H8mP2bWEc2SL30%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 18:46 UTC, opbld31 commented
Docs Build status updates of commit _[5b4d0d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b4d0d4ca2e62a96352e8cbaae2ffafc7477126e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141843358499-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T18%3A46%3A08Z&sr=b&sp=r&sig=Af6IlGJT7t6tv6TtUPHqszh7NxTaS30qxNUyLNMmdfo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 21:14 UTC, opbld31 commented
Docs Build status updates of commit _[5b4d0d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b4d0d4ca2e62a96352e8cbaae2ffafc7477126e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202142112026428-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T21%3A14%3A07Z&sr=b&sp=r&sig=lZ1fAgj4Uu1VdVlyrRFnaD3k4alQaK0eKO5jv2afPiE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 21:28 UTC, rolyon commented on api-reference/beta/resources/rbacapplication.md
>  | [roleSchedules](../api/rbacapplication-roleschedules.md) | [unifiedRoleScheduleBase](unifiedroleschedulebase.md) collection | Function to retrieve a collection of unifiedRoleScheduleBase objects. |
Hi @FaithOmbongi 
See changes. Let me know if I did not make changes correctly.

2022-02-15 18:52 UTC, rolyon commented on api-reference/beta/resources/rbacapplication.md
> +| [List transitiveRoleAssignments](../api/unifiedroleassignment-list-transitive.md) | [unifiedRoleAssignment](unifiedroleassignment.md) collection | Get direct and transitive unifiedRoleAssignments a
This was added

2022-02-15 18:52 UTC, rolyon commented on api-reference/beta/toc.yml
> +              href: api/unifiedroleassignment-list-transitive.md
This was added

2022-02-15 18:56 UTC, opbld30 commented
Docs Build status updates of commit _[f821d31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f821d31da5b86b3afe8c164af8d47c5a348bc1d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202151854297423-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T18%3A56%3A52Z&sr=b&sp=r&sig=mN5SvkG4WRQEKdLiBpq4dxkPZnDJdL71EuM4DqihFeY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:07 UTC, rolyon commented on changelog/Microsoft.DirectoryServices.json
> +        }
Moved to the top

2022-02-15 19:07 UTC, opbld30 commented
Docs Build status updates of commit _[641e95f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/641e95f05eaae0fbf64fabdfe9efa9fd8a0e7ca1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202151904270167-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T19%3A07%3A11Z&sr=b&sp=r&sig=Tx7Se55A0lnrpLWHPMUgT4TTqxe1IXgj%2Bs5oZChjeNg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:07 UTC, rolyon commented on api-reference/beta/api/unifiedroleassignment-list-transitive.md
> +---
Renamed file

2022-02-16 22:29 UTC, joaopprado commented on api-reference/beta/api/unifiedroleassignment-list-transitive.md
> +GET /roleManagement/directory/transitiveRoleAssignments?$filter=principalId eq '<Alice's ID>'
The base `/roleManagement/directory/transitiveRoleAssignments` query without parameters is not supported. Both $filter and $count are required.

2022-02-16 23:40 UTC, opbld31 commented
Docs Build status updates of commit _[90ad0b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90ad0b14adf4276fa8935694464224395edcf6f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202162338170128-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T23%3A40%3A18Z&sr=b&sp=r&sig=wm0mL6Up7ZDXILaW3kB54a%2B%2FyR%2FEJ0yv7e%2BUoEr9j28%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 00:04 UTC, joaopprado commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +            "roleDefinitionId": "<User Administrator role template ID>"
Should we use "role definition ID" instead of "role template ID" to stay consistent with RBACv2 terminology?

2022-02-17 00:11 UTC, rolyon commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +            "roleDefinitionId": "<User Administrator role template ID>"
@abhijeetsinha 
Do you have thoughts about using "role definition ID" instead of "role template ID"?

2022-02-17 00:18 UTC, opbld32 commented
Docs Build status updates of commit _[296d83d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/296d83d0211221863dad0c9ac3fa136848d4454c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202170014175131-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T00%3A18%3A03Z&sr=b&sp=r&sig=fxuBImCv0lD1bdTok9mq5WGHDjky3wpHaK3vPEkzr8Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 00:25 UTC, opbld32 commented
Docs Build status updates of commit _[9d4cea3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d4cea309d0c1219ca35524d74f3bc531947c5fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202170021406689-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T00%3A25%3A02Z&sr=b&sp=r&sig=f0TUo8jilen2SzLlI3CnUaEhKvdnPzmtuACAGs%2BWq9k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 19:38 UTC, rolyon commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +            "roleDefinitionId": "<User Administrator role template ID>"
@joaopprado 
I discussed this with Abhijeet. We should use "role template ID". "templateId" is what is used in the role definition.

2022-02-17 19:40 UTC, rolyon commented
Hi @FaithOmbongi 
I think all changes have been incorporated. Can you review?
thanks

2022-02-23 18:39 UTC, joaopprado commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +            "roleDefinitionId": "<User Administrator role template ID>"
Sounds good, thanks for checking.

2022-02-24 17:37 UTC, rolyon commented
Hi @FaithOmbongi 
Can you clarify what you mean by this comment?

> (Let's follow this up internally) Could we get the opt-in to test this in a demo tenant? Then we can have contextual examples that customers can correlate with the scenario you provide in the doc.

Is it that the examples don't include Guids? Since examples require multiple Guids, I think it is easier to understand examples with the placeholders.
thanks

2022-02-24 19:40 UTC, opbld32 commented
Docs Build status updates of commit _[a54f0b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a54f0b98ab3098e6c822ad0ecbdbe103749e0124)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202241938016209-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T19%3A40%3A10Z&sr=b&sp=r&sig=eiGXDaur%2FJsxJkqV5uyC88dmJ1%2F1ygBGyuzMzjjTxjk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 20:46 UTC, FaithOmbongi commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +Alice is assigned the User Administrator role directly at tenant scope with role assignment RA1. Alice is member of a group G1 and G1 is assigned the User Administrator role at tenant scope with role
Consider changing the structure of the table. Suggestion (could there be a better table header than ID for the 3 columns?)
```suggestion
For the examples in this section, consider the following role assignment scenario. A user Alice identified by ID `2c7936bc-3517-40f3-8eda-4806637b6516` has both direct and transitive role assignments as follows:

|Type | ID | ID | ID |
|:--- | :--- | :--- | :--- |
| Group memberships | - | G1 (ae2fc327-4c71-48ed-b6ca-f48632186510) | G2  (6ffb34b8-5e6d-4727-a7f9-93245e7f6ea8) |
| Role assignments | User Administrator (fe930be7-5e62-47db-91af-98c3a49a38b1) | User Administrator (fe930be7-5e62-47db-91af-98c3a49a38b1) | Helpdesk Administrator (729827e3-9c14-49f7-bb1b-9608f156bbb8) | 
| Role assignment ID | RA1 (857708a7-b5e0-44f9-bfd7-53531d72a739) | RA2 (8a021d5f-7351-4713-aab4-b088504d476e)  | RA3 (6cc86637-13c8-473f-afdc-e0e65c9734d2) |
| Scope | Tenant | Tenant | Administrative unit, AU1 (26e79164-0c5c-4281-8c5b-be7bc7809fb2) |

+ Alice is assigned the User Administrator role directly at the tenant scope with role assignment RA1.
+ Alice is member of a group G1 and G1 is assigned the User Administrator role at the tenant scope with role assignment RA2.
+ Alice is also a member of group G2 and G2 is assigned the Helpdesk Administrator role at an administrative unit AU1 scope with role assignment RA3.
```

2022-02-24 20:49 UTC, FaithOmbongi approved these changes
Thank you @rolyon for your work on this PR and for addressing the feedback. Approved with minor suggestions.

2022-02-24 20:49 UTC, FaithOmbongi commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/transitiveRoleAssignments?$count=true&$filter=principalId eq '{principal id}'
Replace placeholder with Alice's ID
```suggestion
GET https://graph.microsoft.com/beta/roleManagement/directory/transitiveRoleAssignments?$count=true&$filter=principalId eq '2c7936bc-3517-40f3-8eda-4806637b6516'
```

2022-02-24 20:49 UTC, FaithOmbongi commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +GET /roleManagement/directory/transitiveRoleAssignments?$filter=principalId eq '<Alice's ID>'
Placeholder principalId is OK here.
```suggestion
GET /roleManagement/directory/transitiveRoleAssignments?$filter=principalId eq '{principalId}'
```

2022-02-24 20:49 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        "CreatedDateTime": "2022-03-01T00:00:00.000Z",
Change to today's date if you intend to merge today
```suggestion
        "CreatedDateTime": "2022-02-24T00:00:00.000Z",
```

2022-02-24 21:05 UTC, opbld30 commented
Docs Build status updates of commit _[9105dcf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9105dcf295a1c92a7e8bf58338792d3e8d1f2c00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202242103089286-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T21%3A05%3A19Z&sr=b&sp=r&sig=RHMYRa2mGywoAuUy%2FE%2FVqB1P4Xn47o2gYx2A%2BrKrRMM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 21:10 UTC, opbld32 commented
Docs Build status updates of commit _[de524c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de524c3ca873292bf17000a051722f7a56ef3f67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202242108497492-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T21%3A10%3A55Z&sr=b&sp=r&sig=sqSJ9JF6q4WIohV6owOYFxVslFchk%2Fa%2B3xp%2BKKfO56Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 21:21 UTC, opbld32 commented
Docs Build status updates of commit _[8b3e79a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b3e79a9ceb701e724c474a3b70101a7fb76575a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&branch=pr-en-us-15458) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-role-assignment-transitive/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202242119483613-15458%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T21%3A21%3A46Z&sr=b&sp=r&sig=kSyzQ5ovna37Ygqz5TGsHQwgotDhwDek9WZ8wkWS1%2Fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 21:26 UTC, rolyon commented on api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
> +Alice is assigned the User Administrator role directly at tenant scope with role assignment RA1. Alice is member of a group G1 and G1 is assigned the User Administrator role at tenant scope with role
I made updates to table and added the bullets. I did not make structure change. I dont think it makes it easier to interpret.

2022-02-25 04:13 UTC, merged