updated docs for clientApplications
microsoftgraph/microsoft-graph-docs pull request #15453
Opened 2022-01-10 22:45 UTC by danielwood95

2022-01-10 22:47 UTC, opbld33 commented
Docs Build status updates of commit _[f397a6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f397a6b0b255b7752148689f0419074eddf45c31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessclientapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessclientapplications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessclientapplications?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201102245527161-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T22%3A47%3A55Z&sr=b&sp=r&sig=ikueR0iPbvb03ZZa59gFSWAOZH9JMZyPiR37%2FWgriZ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 22:55 UTC, opbld31 commented
Docs Build status updates of commit _[f5ca390](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5ca3908691b2b4027cae83a995968ad893b9ccf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f925fd89)

<a id="f925fd89"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201102254511584-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T22%3A55%3A45Z&sr=b&sp=r&sig=8m9HmfkNcAlOicg5wOwhqLZ2iIO6lsGyNPOAYSvQgDk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 09:03 UTC, opbld32 commented
Docs Build status updates of commit _[b60b2d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b60b2d23a4e0462dfeb1b3a02ff43c86ff952074)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessclientapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessclientapplications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessclientapplications?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201110900502112-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T09%3A03%3A07Z&sr=b&sp=r&sig=wCujS7sTtwYv02dv96DkjH3rBVDdWw9cKBfqaMSabI4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 09:12 UTC, FaithOmbongi requested changes
Thank you @danielwood95 for raising this PR.
- Left suggestions for minor changes to resolve before approval
- Q: Should the scope of this change also include adding the **applicationFilter** property in **conditionalAccessApplications**?

The previous error was due to your branch being too out of sync with the **main** branch at the time you pushed the commit. Resolved it by merging in main and resolving the merge conflict in the changelog.

2022-01-11 09:12 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccessconditionset.md
> +|clientApplications|[conditionalAccessClientApplications](../resources/conditionalaccessclientapplications.md)|Client applications (service principals, workload identities) included in and excluded f
```suggestion
|clientApplications|[conditionalAccessClientApplications](../resources/conditionalaccessclientapplications.md)|Client applications (service principals and workload identities) included in and excluded from the policy. Either **users** or **clientApplications** is required. |
```

2022-01-11 09:12 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the **clientApplications** property to the [conditionalAccessConditionSet](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessConditionSet?view=graph-res
Suggestion to enhance the description
```suggestion
					"Description": "Added the **clientApplications** property to the [conditionalAccessConditionSet](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessConditionSet?view=graph-rest-beta) resource. Use this property to configure the service principals and workload identities to include in or exclude from a conditional access policy.",
```

2022-01-18 22:19 UTC, opbld32 commented
Docs Build status updates of commit _[6058111](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60581115c7e9373bdb110537bc731438a2eaa722)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessclientapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessclientapplications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessclientapplications?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182217219725-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T22%3A19%3A33Z&sr=b&sp=r&sig=dpX8DgtxTDE53Vn42NK6YsYJxJyPHJk9LodsWczIrj0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 22:22 UTC, opbld34 commented
Docs Build status updates of commit _[a35ec47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a35ec4767049bd8e4172ab611a8bde02b2e67506)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessclientapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessclientapplications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessclientapplications?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182217427819-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T22%3A22%3A58Z&sr=b&sp=r&sig=InkFftY5Pr0PY1e7q7MRSO%2BaOCmbcXvTgfDc7ZNtLrk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 22:29 UTC, opbld31 commented
Docs Build status updates of commit _[d7d7de8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7d7de834ce9c75648ff6b58fe338b76d3ac6536)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessclientapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessclientapplications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessclientapplications?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182225564174-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T22%3A29%3A16Z&sr=b&sp=r&sig=JtscCp6MWA0Sx7y%2BylRYWAYcaQJHBGxyT97%2FIylW4X4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 22:30 UTC, danielwood95 commented
> Thank you @danielwood95 for raising this PR.
> 
> * Left suggestions for minor changes to resolve before approval
> * Q: Should the scope of this change also include adding the **applicationFilter** property in **conditionalAccessApplications**?
> 
> The previous error was due to your branch being too out of sync with the **main** branch at the time you pushed the commit. Resolved it by merging in main and resolving the merge conflict in the changelog.

Yes, this should include adding applicationFilter to conditionalAccessApplications. I can add that to this PR as well.

2022-01-26 18:15 UTC, opbld34 commented
Docs Build status updates of commit _[239c975](https://github.com/microsoftgraph/microsoft-graph-docs/commits/239c975700cb0adc3749f71f1b8a44856ce9887e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-eac7af9b)

<a id="eac7af9b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261814300087-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T18%3A15%3A41Z&sr=b&sp=r&sig=2Fpm4zpNXoD547HOf1L14glly%2F%2BGbo%2BqmyjGr6KMpqY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 18:21 UTC, opbld34 commented
Docs Build status updates of commit _[84dda0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84dda0cba208b073a71bdb02541d2728cdc0ed2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessclientapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessclientapplications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessclientapplications?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/api-reference/beta/resources/conditionalaccessconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-beta&branch=pr-en-us-15453) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dawoo/updateCaWorkloadIdentityDocs/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261819256953-15453%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T18%3A21%3A34Z&sr=b&sp=r&sig=qGhFuQ5iqcsa2c2TbmNdT0Dzpe9EzuJ%2BZYRkzrVYVBY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 18:22 UTC, FaithOmbongi approved these changes

2022-01-27 04:09 UTC, merged