Scheduled Access Review History Definition
microsoftgraph/microsoft-graph-docs pull request #15472
Opened 2022-01-11 19:46 UTC by leherpel

This is the documentation for scheduled access review history definitions.

2022-01-11 19:48 UTC, opbld31 commented
Docs Build status updates of commit _[55ad15b](https://github.com/leherpel/microsoft-graph-docs/commits/55ad15b31d6851386ffb48cef36abdb201983806)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201111946377747-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T19%3A48%3A56Z&sr=b&sp=r&sig=f3%2BirzmFzUERb7AkCIw%2BPJbJBgpk2ZabrKfeovZfkV4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 03:08 UTC, opbld33 commented
Docs Build status updates of commit _[bff8af4](https://github.com/leherpel/microsoft-graph-docs/commits/bff8af4a990c7f31247a9d4bf7e674ef76f50c7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-list.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-list?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201120305593381-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T03%3A08%3A21Z&sr=b&sp=r&sig=qNxJYA%2Bc6ATfqwNF3sV4BXmia6JLpNZaaVAKjzJysN4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 18:38 UTC, opbld31 commented
Docs Build status updates of commit _[d3b8bcb](https://github.com/leherpel/microsoft-graph-docs/commits/d3b8bcb22c7b3d100f2d97dae58ebcee3cbe1da4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-list.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-list?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201131836462014-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T18%3A38%3A56Z&sr=b&sp=r&sig=mL3HAguOzKCiGl0bmmNkajZ7g11hsPMkaiYPiYQt7Pw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 10:11 UTC, FaithOmbongi requested changes
Thank you @leherpel for working on this docs PR. Shared a few suggestions for changes + the following gaps:
- Filename changes: accessreviewhistoryinstance-list.md => **accessreviewhistorydefinition-list-instances.md**
- Please surface the docs (accessReviewHistoryInstance.md and LIST method) and  in the TOC. You can nest this under the current accessReviewHistoryDefinition node.
- I see that ChangeList objects for the Deleted properties (fulfilledDateTime, downloadUri) were not generated. Please create them manually following the [changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog). The ChangeType is **Deletion**.
    - Suggestion for one of the change descriptions: `Deleted the **downloadUri** property from the [accessReviewHistoryDefinition](https://docs.microsoft.com/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta) resource. Use the **downloadUri** property in the [accessReviewHistoryInstance](https://docs.microsoft.com/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta) instead.`

**Additional comments:**

1. Ideally, we would have followed the deprecation guidance and first marked the two properties as deprecated then deleted them later. But I see in your schema PR that you deleted the 2 properties and the last property will be removed on January 30. Because of this, we can just go ahead and add the 2 changelist items for **Deletion** ChangeType.
2. I see your schema update PR is already merged into the master schema branch. Please prioritize these changes so that these docs can be published when schema deployment is done and the API goes live..

2022-01-14 18:09 UTC, FaithOmbongi requested changes
2 minor additions - enhancements to current changelog descriptions.

2022-01-14 18:09 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [accessReviewHistoryScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryScheduleSettings?view=graph-rest-beta) resource type.
```suggestion
          "Description": "Added the [accessReviewHistoryScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta) resource type. Use this resource to configure the settings of an [accessReviewHistoryDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta) object.",
```

2022-01-14 18:09 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the **instances** relationship to [accessReviewHistoryDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryDefinition?view=graph-rest-be
```suggestion
          "Description": "Added the **instances** relationship to [accessReviewHistoryDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryDefinition?view=graph-rest-beta) resource. Represents the instances of a recurring acecss review history definition.",
```

2022-01-18 02:24 UTC, opbld34 commented
Docs Build status updates of commit _[2c4b3d6](https://github.com/leherpel/microsoft-graph-docs/commits/2c4b3d604e12a9a16a1cf283e0eaa22e03b3cc49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) | [Details](#user-content-59fa60837c95dea686d7c7ad6530bd40-b53ce3bd)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-list.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-list?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="59fa60837c95dea686d7c7ad6530bd40-b53ce3bd"></a>
### [api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewhistorydefinition-list-instances.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180222301636-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T02%3A24%3A35Z&sr=b&sp=r&sig=TKOsOKZuKVK7sTusYYOUk0ogvbowitVqcj%2BHZC%2B4YZQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 22:10 UTC, opbld34 commented
Docs Build status updates of commit _[30373d3](https://github.com/leherpel/microsoft-graph-docs/commits/30373d3c4de13503f59662ffc6d71584b21741b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) | [Details](#user-content-59fa60837c95dea686d7c7ad6530bd40-f54dabc6)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-list.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-list?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="59fa60837c95dea686d7c7ad6530bd40-f54dabc6"></a>
### [api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewhistorydefinition-list-instances.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182209090539-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T22%3A10%3A45Z&sr=b&sp=r&sig=jbVPO%2FdgN91OFarv9Xd8TZW0bgP1mzNpJJai6DkHZrU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 22:12 UTC, opbld33 commented
Docs Build status updates of commit _[d17523d](https://github.com/leherpel/microsoft-graph-docs/commits/d17523d749bbb59525caefbf0ca867bde1e9f30a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) | [Details](#user-content-59fa60837c95dea686d7c7ad6530bd40-56310801)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-list.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-list?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="59fa60837c95dea686d7c7ad6530bd40-56310801"></a>
### [api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewhistorydefinition-list-instances.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182210185761-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T22%3A12%3A34Z&sr=b&sp=r&sig=uyobfibffoChejKa%2FlUsKdzUNTesWvc9W04Oq37AUMQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 23:03 UTC, opbld34 commented
Docs Build status updates of commit _[26ee3af](https://github.com/leherpel/microsoft-graph-docs/commits/26ee3afbaf55fe432247ca81fa131c68be38685e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182301567593-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T23%3A03%3A42Z&sr=b&sp=r&sig=Vxk9gAEDDj%2Fe1foGhQLeu4vbFMvAuF96b1IkGqH8S6E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 23:14 UTC, opbld34 commented
Docs Build status updates of commit _[25e9c46](https://github.com/leherpel/microsoft-graph-docs/commits/25e9c4616200d86528d3dad63bb0fa99e83f3a66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182312419999-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T23%3A14%3A36Z&sr=b&sp=r&sig=d7W6KwrBAKjkN0DEl9Ovismx4QBE2gv2lb3iLauETp4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 23:24 UTC, opbld31 commented
Docs Build status updates of commit _[3c9c73c](https://github.com/leherpel/microsoft-graph-docs/commits/3c9c73c377b2c68e0eb8d7b663db47e0f3b90690)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201182321599074-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T23%3A24%3A07Z&sr=b&sp=r&sig=bTk7frd0U3skTEfo3NqTD5ooelK83%2FlUtw%2FCqPk9l%2Fw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 23:24 UTC, leherpel commented
@FaithOmbongi thank you so much for reviewing the PR. I updated the PR to reflect the changes you requested.

2022-01-19 08:42 UTC, opbld30 commented
Docs Build status updates of commit _[5b9ab3c](https://github.com/leherpel/microsoft-graph-docs/commits/5b9ab3cf67ae6e6a5263372a7ad84d5e2b377706)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190838333880-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T08%3A42%3A24Z&sr=b&sp=r&sig=LIVZDSYeMONSlnMyaAk1a%2Bb2ZPUycRTBI0H7KVmajWE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 08:48 UTC, FaithOmbongi requested changes
Hi @leherpel, I see you changed the file name for the generateDownloadUri method from accessreviewhistorydefinition-generatedownloaduri.md => accessreviewhistorydefinition-generatedownloaduri-instance.md.

Looking at your schema, both the binding parameter and return type for generateDownloadUri is accessReviewHistoryDefinition. So the previous filename is/was correct.

However, I also see major changes you're making in the body of the doc that the path for the action is now under accessReviewHistoryInstance, does this mean that both the binding parameter and return type for generateDownloadUri is ~accessReviewHistoryDefinition~ accessReviewHistoryInstance? If so, then the file will change to **accessreviewhistoryinstance-generatedownloaduri.md**. But let's discuss this internally to confirm the right changes.

2022-01-19 08:48 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            - name: Access review history definition instance
```suggestion
            - name: Access review history instance
```

2022-01-19 08:48 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewhistorydefinition.md
>  |scopes|[accessReviewQueryScope](accessreviewqueryscope.md) collection|Used to scope what reviews are included in the fetched history data. Fetches reviews whose scope matches with this provided scop
To match the change in the JSON representation and the details in the schema
```suggestion
|scopes|[accessReviewScope](accessreviewscope.md) collection|Used to scope what reviews are included in the fetched history data. Fetches reviews whose scope matches with this provided scope. Required.|
```

2022-01-19 18:03 UTC, opbld33 commented
Docs Build status updates of commit _[edd9b6e](https://github.com/leherpel/microsoft-graph-docs/commits/edd9b6e6d84160f442598dc301157e05f656c94c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191800537897-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T18%3A03%3A36Z&sr=b&sp=r&sig=1LgOBILg93fmZvt1QYEPuA9NhcEWiFJ%2BxDp7i3IpRn0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 18:07 UTC, opbld34 commented
Docs Build status updates of commit _[0a5e434](https://github.com/leherpel/microsoft-graph-docs/commits/0a5e434f0a72fe735707f366afdb0a45f6c21022)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri-instance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri-instance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191804357587-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T18%3A07%3A33Z&sr=b&sp=r&sig=KNyHigKHjA%2BQKvT0XbP3MwKgzdkbMrBsSl00aF0mUxU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 18:56 UTC, opbld30 commented
Docs Build status updates of commit _[c7553b6](https://github.com/leherpel/microsoft-graph-docs/commits/c7553b6541a185ebef6d661c6755d4de49b39b4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) | [Details](#user-content-d98150e2ecf38a401a348b610e579a35-d8c0c348)
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d8c0c348)
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="d98150e2ecf38a401a348b610e579a35-d8c0c348"></a>
### [api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md)
 - **Line 62, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewhistorydefinition-generatedownloaduri-instance.md'.`````

<a id="0817dce4456c16725d5333633847d38f-d8c0c348"></a>
### [api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml)
 - **Line 12344, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-generatedownloaduri-instance.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191853445756-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T18%3A56%3A12Z&sr=b&sp=r&sig=qLZ3BSVGQb47%2BJykU8Y9rvEv3dyq7zputiR%2FH1hXDU8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 19:06 UTC, opbld32 commented
Docs Build status updates of commit _[248aefd](https://github.com/leherpel/microsoft-graph-docs/commits/248aefda9470491c693f6d76aeaa68ffd90611a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201191904008859-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T19%3A06%3A37Z&sr=b&sp=r&sig=wk1EaDZVm3T1mFnZNm%2BCrnSntEGveOFLg1j7jljqL5c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 19:16 UTC, leherpel commented
Here is the PR to update the schema: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5591756

2022-01-20 20:35 UTC, opbld33 commented
Docs Build status updates of commit _[71e31dd](https://github.com/leherpel/microsoft-graph-docs/commits/71e31dd9c12aead870ec87a6c3388b760f295d09)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6dbc6f13)

<a id="6dbc6f13"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201202034207478-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T20%3A35%3A15Z&sr=b&sp=r&sig=lnUKY9Qy8EXDXRUrLWV1upSzkD07zDDQDqyeRSdBljM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 20:47 UTC, opbld33 commented
Docs Build status updates of commit _[3f0e087](https://github.com/leherpel/microsoft-graph-docs/commits/3f0e087d887d7ba1d780f6f82403e5589b2f113b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201202045185416-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T20%3A47%3A46Z&sr=b&sp=r&sig=4FMVBnYKNnRaI8%2BTjI4jzWdMqd8AnzpXLuNxS5j5N6E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 01:19 UTC, leherpel commented
Schema change: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5592092

2022-01-21 03:19 UTC, opbld32 commented
Docs Build status updates of commit _[d0a1971](https://github.com/leherpel/microsoft-graph-docs/commits/d0a1971517824b054eb792f00655e7a215dd0e66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210316218689-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T03%3A19%3A13Z&sr=b&sp=r&sig=lPrWwu3EC2BsJJQxvAtIWqWo0msDFEtkk8tMs6DXIwU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 07:42 UTC, opbld33 commented
Docs Build status updates of commit _[15fadc3](https://github.com/leherpel/microsoft-graph-docs/commits/15fadc367364a9c9f2b5a091770d1520f679fdd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210740379061-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T07%3A42%3A58Z&sr=b&sp=r&sig=lg%2BUrwwTLeJhdNS0WA4i9H%2Bh6XZ0cBfy7B8Ms3Gzmvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 07:47 UTC, opbld30 commented
Docs Build status updates of commit _[bc2b3fe](https://github.com/leherpel/microsoft-graph-docs/commits/bc2b3fe33c7061e6eb6d295e5da5459c37e6ead6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210745249074-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T07%3A47%3A32Z&sr=b&sp=r&sig=Pou5%2BvwhgcD8u5k2LgkKVez803euRYw2gWqp%2FrCQvhA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:00 UTC, opbld32 commented
Docs Build status updates of commit _[61ff947](https://github.com/leherpel/microsoft-graph-docs/commits/61ff94736a360f74339306a64712aaf52e2209be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210758274990-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A00%3A49Z&sr=b&sp=r&sig=NyA6KiX9JRjEXmGioZrfE4hl%2FB1EWDBddwI7a4eH0Gk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:14 UTC, opbld33 commented
Docs Build status updates of commit _[bdd7767](https://github.com/leherpel/microsoft-graph-docs/commits/bdd7767ec241c8f0787959393051e613bd7143e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210811459305-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A14%3A39Z&sr=b&sp=r&sig=6m76k%2Bw4knaPTS2olSj1iTpAQYcOI8xzmSuS6Yh34Vc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:17 UTC, opbld33 commented
Docs Build status updates of commit _[bdd7767](https://github.com/leherpel/microsoft-graph-docs/commits/bdd7767ec241c8f0787959393051e613bd7143e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210811564885-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A17%3A10Z&sr=b&sp=r&sig=2RqNUGa9dHZljTumf%2Fz%2FMvGqkWqL%2FFsQz2jKzMWzVWM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:39 UTC, FaithOmbongi approved these changes
Thank you @leherpel for the quick work addressing the schema gap.

2022-01-26 03:40 UTC, opbld30 commented
Docs Build status updates of commit _[7883f0b](https://github.com/leherpel/microsoft-graph-docs/commits/7883f0be25c10ed57810db9ef0eb6b5d5a3928c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260338041801-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T03%3A40%3A17Z&sr=b&sp=r&sig=dEDwksoAqZFz18dBJrA69UtbpYCcLnX1p%2BXE9FSXJ7c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 03:43 UTC, opbld31 commented
Docs Build status updates of commit _[ac58236](https://github.com/leherpel/microsoft-graph-docs/commits/ac5823656c490a2279a35596c0d9fdc83f122ca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260339072547-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T03%3A43%3A02Z&sr=b&sp=r&sig=D6U2EVjz1Utud4%2Fp4TtoF6cmKE8bggqrt%2F1QhOwMrcw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 03:45 UTC, opbld31 commented
Docs Build status updates of commit _[ad2266a](https://github.com/leherpel/microsoft-graph-docs/commits/ad2266afe75a20ba1fa1d49115d069772c670cec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-list-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-historydefinitions.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryinstance.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistoryschedulesettings.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-overview.md](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-15472) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/leherpel/microsoft-graph-docs/blob/leherpel-scheduledaccessreviewhistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260340440270-15472%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T03%3A45%3A04Z&sr=b&sp=r&sig=60Znwqtt%2F%2FNmobqLkfKG3KAE3LIWlMxlntyMP9xNkI8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 03:51 UTC, merged