[Azure ABAC] Custom security attribute with allowed values
microsoftgraph/microsoft-graph-docs pull request #15528
Opened 2022-01-14 23:15 UTC by rolyon

2022-01-14 23:17 UTC, opbld31 commented
Docs Build status updates of commit _[58fc5b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58fc5b22df92ee4ddb980aced84a25c02787f197)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directory-post-customsecurityattributedefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/directory-post-customsecurityattributedefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-customsecurityattributedefinitions?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201142315514679-15528%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T23%3A17%3A56Z&sr=b&sp=r&sig=77LlD7Ni1FOP0E3tIqRxJqPD05G1Vz51yPeB9PXDLMY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-15 00:20 UTC, opbld33 commented
Docs Build status updates of commit _[a457dd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a457dd83539da53c1a8965135e1d35bc46e33e77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/customsecurityattributedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/customsecurityattributedefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customsecurityattributedefinition-update?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |
[api-reference/beta/api/directory-post-customsecurityattributedefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/directory-post-customsecurityattributedefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-customsecurityattributedefinitions?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201150018463552-15528%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-15T00%3A20%3A37Z&sr=b&sp=r&sig=Wxc45CBOUKTZjrwPm8nP5N4ZC%2F%2FzFQqK2XMUd8koUFY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-15 00:30 UTC, opbld30 commented
Docs Build status updates of commit _[fa6fdc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa6fdc8398142ba7c6d134969e904bac31ae39ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/customsecurityattributedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/customsecurityattributedefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customsecurityattributedefinition-update?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |
[api-reference/beta/api/directory-post-customsecurityattributedefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/directory-post-customsecurityattributedefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-customsecurityattributedefinitions?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201150027432400-15528%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-15T00%3A30%3A05Z&sr=b&sp=r&sig=v%2Bd2JysLsuET368Tg4Guc0ADo2hRznjUCejc9Pq71J8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 11:03 UTC, FaithOmbongi requested changes
Thank you @rolyon for your work on this PR. Let a Q about the purpose of the header and scenarios where it's required. Let's clarify this internally.

2022-01-25 11:03 UTC, FaithOmbongi commented on api-reference/beta/api/customsecurityattributedefinition-update.md
> +> Value: 4.01
Hi @rolyon, is there a reason why only this scenario requires the header?
Also, should we then add this info to the **Request headers** sections of both the Update and POST operations?

2022-01-25 11:05 UTC, FaithOmbongi requested changes
Review feedback left here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15528#pullrequestreview-862122095

2022-01-27 20:36 UTC, loradule commented on api-reference/beta/api/customsecurityattributedefinition-update.md
> +> Value: 4.01
Hi Faith,

The update implementation leverages a feature called delta update that requires OData 4.01. This is specific to update, the POST does not need this particular header. Hope this helps!

2022-02-01 11:06 UTC, FaithOmbongi reviewed
Thank you @rolyon, @loradule for the clarification. Left inline suggestions based on the feedback.

2022-02-02 00:59 UTC, opbld31 commented
Docs Build status updates of commit _[cd2a9de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd2a9de8c925d0d68e5a8bbbbda6f7a68e02e324)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/customsecurityattributedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/customsecurityattributedefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customsecurityattributedefinition-update?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |
[api-reference/beta/api/directory-post-customsecurityattributedefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/directory-post-customsecurityattributedefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-customsecurityattributedefinitions?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202020057225446-15528%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T00%3A59%3A47Z&sr=b&sp=r&sig=bipaPUWLHIhk0qj7eZhXOix50c47uI7aj%2FylYuqQ8%2BM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 01:04 UTC, opbld32 commented
Docs Build status updates of commit _[6f614d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f614d3d6a9ca95da81731ebee86fded5055258f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/customsecurityattributedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/customsecurityattributedefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customsecurityattributedefinition-update?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |
[api-reference/beta/api/directory-post-customsecurityattributedefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/directory-post-customsecurityattributedefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-customsecurityattributedefinitions?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202020102138000-15528%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T01%3A04%3A16Z&sr=b&sp=r&sig=t5s9LDpM9tHc7R%2BSbZZBRqd5ceY5IVDy2l5OH1Q%2FCQg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 01:11 UTC, opbld32 commented
Docs Build status updates of commit _[12a0961](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12a096170eb5ff48c024eb891e35a606956f0be4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/customsecurityattributedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/customsecurityattributedefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customsecurityattributedefinition-update?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |
[api-reference/beta/api/directory-post-customsecurityattributedefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-abac-attributes-definition-allowed-values-update/api-reference/beta/api/directory-post-customsecurityattributedefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-customsecurityattributedefinitions?view=graph-rest-beta&branch=pr-en-us-15528) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202020109181075-15528%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T01%3A11%3A16Z&sr=b&sp=r&sig=FR76fk4OgwXal8McG8mVcOPR4PJovBt8YwXI49chCTg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 01:16 UTC, rolyon commented
Hi @FaithOmbongi 
See doc updates.
thanks

2022-02-02 05:35 UTC, FaithOmbongi approved these changes
Thank you @rolyon for your work on this PR and for bringing this new capability to the attention of our customers.

2022-02-05 02:21 UTC, merged