Add Certificate Based Authentication APIs, resources, and changelog
microsoftgraph/microsoft-graph-docs pull request #15524
Opened 2022-01-14 17:45 UTC by charlenezheng

Certificate Based Authentication is approaching the public preview. Publishing related APIs and resources are required. This PR is to introduce a new admin authentication method as X509Certificate authentication to MS Graph docs.

2022-01-14 17:47 UTC, opbld31 commented
Docs Build status updates of commit _[42086c7](https://github.com/charlenezheng/microsoft-graph-docs/commits/42086c7dea4b0fb6d19397c4488da50b52ef0ec4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :x:Error | | [Details](#user-content-4d6291c74454c2c5a9178eb15e2aa29b-025189ad)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :x:Error | | [Details](#user-content-4e562a6e9eb49cda907462d1f671f5b9-025189ad)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :x:Error | | [Details](#user-content-78dc60d8ef5ee60bb06f7ceedfe7fdee-025189ad)
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :warning:Warning | | [Details](#user-content-0a3e354796014c9a34d1ad5cb3a12b54-025189ad)
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :warning:Warning | | [Details](#user-content-f7aa563142397b0c52ab328c02fdd4b3-025189ad)

<a id="4d6291c74454c2c5a9178eb15e2aa29b-025189ad"></a>
### [api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-x509Certificateauthenticationmethodconfiguration-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-x509Certificateauthenticationmethodconfiguration-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-x509Certificateauthenticationmethodconfiguration-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-x509Certificateauthenticationmethodconfiguration-java-snippets.md'.`````

<a id="4e562a6e9eb49cda907462d1f671f5b9-025189ad"></a>
### [api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md)
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-x509Certificateauthenticationmethodconfiguration-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-x509Certificateauthenticationmethodconfiguration-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-x509Certificateauthenticationmethodconfiguration-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-x509Certificateauthenticationmethodconfiguration-java-snippets.md'.`````

<a id="78dc60d8ef5ee60bb06f7ceedfe7fdee-025189ad"></a>
### [api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md)
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-x509Certificateauthenticationmethodconfiguration-csharp-snippets.md'.`````
 - **Line 90, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-x509Certificateauthenticationmethodconfiguration-javascript-snippets.md'.`````
 - **Line 94, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-x509Certificateauthenticationmethodconfiguration-objc-snippets.md'.`````
 - **Line 98, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/update-x509Certificateauthenticationmethodconfiguration-java-snippets.md'.`````

<a id="0a3e354796014c9a34d1ad5cb3a12b54-025189ad"></a>
### [api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 310**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f7aa563142397b0c52ab328c02fdd4b3-025189ad"></a>
### [api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201141745308188-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T17%3A47%3A19Z&sr=b&sp=r&sig=4KzwzUJc1k2ufwoqr9cEYfw3Jr0kQLFkJCYfOhoR0Tk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

 [...]

2022-01-25 14:12 UTC, andrueastman submitted a review, later dismissed

2022-01-25 14:15 UTC, andrueastman commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
> +[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]
These section should be removed and will be re-inserted by the snippet generator. Same applies to other files

2022-01-25 14:34 UTC, opbld34 commented
Docs Build status updates of commit _[193a7e0](https://github.com/charlenezheng/microsoft-graph-docs/commits/193a7e0143c06772db3c8818e082d4ae8f80d326)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-0a3e354796014c9a34d1ad5cb3a12b54-c3d77479)
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-f7aa563142397b0c52ab328c02fdd4b3-c3d77479)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0a3e354796014c9a34d1ad5cb3a12b54-c3d77479"></a>
### [api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 310**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f7aa563142397b0c52ab328c02fdd4b3-c3d77479"></a>
### [api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251430537026-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T14%3A34%3A03Z&sr=b&sp=r&sig=UJs4KPfcAN9j%2BMzu00Kct%2FglW4hAj57MbcXNMqwk37k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 14:36 UTC, opbld33 commented
Docs Build status updates of commit _[8bff15d](https://github.com/charlenezheng/microsoft-graph-docs/commits/8bff15db52f569235ead125b89f1a8fb2fbcb2aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-0a3e354796014c9a34d1ad5cb3a12b54-3024cad8)
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-f7aa563142397b0c52ab328c02fdd4b3-3024cad8)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0a3e354796014c9a34d1ad5cb3a12b54-3024cad8"></a>
### [api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 310**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f7aa563142397b0c52ab328c02fdd4b3-3024cad8"></a>
### [api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251431494727-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T14%3A36%3A50Z&sr=b&sp=r&sig=PKk0kgpxaaEtMklQ0KBINiIqzqMBN27GgCPGRWwLmUA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 15:56 UTC, opbld34 commented
Docs Build status updates of commit _[2b7269c](https://github.com/charlenezheng/microsoft-graph-docs/commits/2b7269c16c99871182b2635877fa974e4815bec9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-0a3e354796014c9a34d1ad5cb3a12b54-c6e8c3d4)
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-f7aa563142397b0c52ab328c02fdd4b3-c6e8c3d4)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0a3e354796014c9a34d1ad5cb3a12b54-c6e8c3d4"></a>
### [api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 310**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f7aa563142397b0c52ab328c02fdd4b3-c6e8c3d4"></a>
### [api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251553414164-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T15%3A56%3A30Z&sr=b&sp=r&sig=JCUFtFaYWcbm4L3SoqcnVjM%2BlEcTL3AOrsZxicjC2E8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 16:10 UTC, opbld31 commented
Docs Build status updates of commit _[b0cc314](https://github.com/charlenezheng/microsoft-graph-docs/commits/b0cc3144e064cd4371b0ebfd8183d47b3f19adba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-0a3e354796014c9a34d1ad5cb3a12b54-68c6bd1b)
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-f7aa563142397b0c52ab328c02fdd4b3-68c6bd1b)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0a3e354796014c9a34d1ad5cb3a12b54-68c6bd1b"></a>
### [api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 310**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f7aa563142397b0c52ab328c02fdd4b3-68c6bd1b"></a>
### [api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251608359931-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T16%3A10%3A54Z&sr=b&sp=r&sig=sGUsG0HtU7tnXMWBi5ukl1gH%2FF%2BwNb7Hgd0fCiCjnxA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 16:20 UTC, opbld31 commented
Docs Build status updates of commit _[e18a292](https://github.com/charlenezheng/microsoft-graph-docs/commits/e18a292c761807bd58f97758798bb6050d3a06d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-0a3e354796014c9a34d1ad5cb3a12b54-6b8c38b6)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0a3e354796014c9a34d1ad5cb3a12b54-6b8c38b6"></a>
### [api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 310**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251618187261-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T16%3A20%3A56Z&sr=b&sp=r&sig=NxzsNptFidkSIap%2Bd%2FwTQo9W%2BaAtWz5zOoKH2grJ2Ms%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 05:57 UTC, andrueastman approved these changes
Looks good to me. The snippets should be injected once the PR is merged and the snippet generator runs on its next schedule.

2022-01-26 11:31 UTC, FaithOmbongi requested changes
Thank you @charlenezheng for your work on this PR. I've left inline suggestions plus the following:
- Please ensure that the GitHub alias "Vimala" has completed the Get started steps. I'm unable to locate the alias in the required orgs.
- Please surface the resource and methods in the TOC.
- Document this new method in the [Auth methods policy overview](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta) article
- Mention in [authenticationMethodConfiguration](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta) that this is one of the derived types
- Please move your changelog record to the top of the changelog file, starting at Line 3

2022-01-26 11:31 UTC, FaithOmbongi commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2022-01-26 11:31 UTC, FaithOmbongi commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +|[Delete x509CertificateAuthenticationMethodConfiguration](../api/x509certificateauthenticationmethodconfiguration-delete.md)|None|Reverts the x509CertificateAuthenticationMethodConfiguration object
This might change to **Disable** because the API doesn't technically delete, but changes the **state** property to `disable`.
```suggestion
|[Disable x509CertificateAuthenticationMethodConfiguration](../api/x509certificateauthenticationmethodconfiguration-delete.md)|None| Disables and restores the x509CertificateAuthenticationMethodConfiguration object to its default configuration.|
```

2022-01-26 11:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    },
- Please move your changelog record to the top of the file, starting at Line 3.

2022-01-26 11:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateRuleType](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
I hope that the previous descriptions weren't autogenerated as-was by Graph Studio?
```suggestion
              "ApiChange": "Enum type",
              "ChangedApiName": "x509CertificateAuthenticationMode",
              "ChangeType": "Addition",
              "Description": "Added the [x509CertificateAuthenticationMode](https://docs.microsoft.com/en-us/?view=graph-rest-beta) enumeration type.",
              "Target": "x509CertificateAuthenticationMode"
            },
            {
              "Id": "34b0a990-a3c9-4b70-92ac-a8ac93bf4860",
              "ApiChange": "Enum type",
              "ChangedApiName": "x509CertificateRuleType",
              "ChangeType": "Addition",
              "Description": "Added the [x509CertificateRuleType](https://docs.microsoft.com/en-us/?view=graph-rest-beta) enumeration type.",
```

2022-01-26 11:31 UTC, FaithOmbongi commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +A configuration entity that represents whether Azure AD native Certificate Based Authentication is enabled or disabled for the tenant and which users and groups can register and use it.
```suggestion
Represents the details of the Azure AD native Certificate-Based Authentication (CBA) in the tenant including whether the authentication method is enabled or disabled and the users and groups who can register and use it
```

2022-01-26 11:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateAuthenticationModeConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationModeConfiguration?view=graph
Suggestions to enhance the changelog description and provide a little more context
```suggestion
              "Description": "Added the [x509CertificateAuthenticationModeConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationModeConfiguration?view=graph-rest-beta) resource. Represents the details of the Azure AD native Certificate-Based Authentication (CBA) in the tenant including whether the authentication method is enabled or disabled and the users and groups who can register and use it.",
```

2022-01-26 11:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateRule](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateRule?view=graph-rest-beta) resource",
```suggestion
              "Description": "Added the [x509CertificateRule](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateRule?view=graph-rest-beta) resource. Use this resource to define the strong authentication configuration rules for the X.509 certificate.",
```

2022-01-26 11:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateUserBinding](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateUserBinding?view=graph-rest-beta) resource",
```suggestion
              "Description": "Added the [x509CertificateUserBinding](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateUserBinding?view=graph-rest-beta) resource. Use this resource to map the fields in the X.509 certificate to attributes of the Azure AD user object in order to bind the certificate to the user account.",
```

2022-01-26 11:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateAuthenticationMethodConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationMethodConfiguration?view=g
```suggestion
              "Description": "Added the [x509CertificateAuthenticationMethodConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationMethodConfiguration?view=graph-rest-beta) resource. Use this resource to define the strong authentication configurations for the X.509 certificate.",
```

2022-01-26 15:42 UTC, charlenezheng commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Yes you are correcr, I will push a fix

2022-01-26 15:43 UTC, charlenezheng commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
> +Read the properties and relationships of a [x509CertificateAuthenticationMethodConfiguration](../resources/x509certificateauthenticationmethodconfiguration.md) object.
Sounds good

2022-01-26 17:01 UTC, charlenezheng commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
> +description: "Deletes a x509CertificateAuthenticationMethodConfiguration object."
Yes, the target is to disable this auth method and reset as default values

2022-01-26 17:02 UTC, charlenezheng commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
> +Deletes a [x509CertificateAuthenticationMethodConfiguration](../resources/x509certificateauthenticationmethodconfiguration.md) object.
Yes, the target is to disable this auth method and reset as default values

2022-01-26 17:04 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +|[Delete x509CertificateAuthenticationMethodConfiguration](../api/x509certificateauthenticationmethodconfiguration-delete.md)|None|Reverts the x509CertificateAuthenticationMethodConfiguration object
Sounds good

2022-01-26 17:09 UTC, charlenezheng commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateRuleType](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
It was auto generated when I submit PR to CSDL, I will make this suggested changes

2022-01-26 17:19 UTC, opbld31 commented
Docs Build status updates of commit _[b6c6d15](https://github.com/charlenezheng/microsoft-graph-docs/commits/b6c6d153718dfeebb7609057619fe0d2be23158a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-78dc60d8ef5ee60bb06f7ceedfe7fdee-f24b278a)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="78dc60d8ef5ee60bb06f7ceedfe7fdee-f24b278a"></a>
### [api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md)
 - **Line 49, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261717265729-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T17%3A19%3A38Z&sr=b&sp=r&sig=t4U%2FbUm19NUy2ZE%2FEXnjE4JhUsbxd5bDIgz%2Be5AjIIY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 17:21 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +description: "A configuration entity that represents whether Azure AD native Certificate Based Authentication is enabled or disabled for the tenant and which users and groups can register and use it.
Sounds good

2022-01-26 17:22 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +author: "Vimala"
I will push myself as the owner. Should I put my Microsoft alias, or my Github username?

2022-01-26 17:22 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +|authenticationModeConfiguration|[x509CertificateAuthenticationModeConfiguration](../resources/x509certificateauthenticationmodeconfiguration.md)|Defines strong auth configurations. This configuratio
Sounds good

2022-01-26 17:22 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateuserbinding.md
> +description: "A complex type that defines the mapping from X.509 certificate field to directory user attribute to bind the certificate to the user account. This controls which certificate fields and
Sounds good

2022-01-26 17:22 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateuserbinding.md
> +to bind the certificate to the user.
fixed

2022-01-26 17:22 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
> +A configuration entity that represents whether Azure AD native Certificate Based Authentication is enabled or disabled for the tenant and which users and groups can register and use it.
fixed

2022-01-26 17:22 UTC, charlenezheng commented on changelog/Microsoft.DirectoryServices.json
> +              "Description": "Added the [x509CertificateAuthenticationModeConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationModeConfiguration?view=graph
fixed

2022-01-26 17:48 UTC, opbld32 commented
Docs Build status updates of commit _[e43f0dc](https://github.com/charlenezheng/microsoft-graph-docs/commits/e43f0dca7da910cd4d0c9b500b536d0b7590e98f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-78dc60d8ef5ee60bb06f7ceedfe7fdee-2b6e5d68)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="78dc60d8ef5ee60bb06f7ceedfe7fdee-2b6e5d68"></a>
### [api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md)
 - **Line 49, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261746455382-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T17%3A48%3A49Z&sr=b&sp=r&sig=nzdBoWmv6iOvbkx7lVPsIe%2FMIBcpyL%2BbA22SkWtGqhY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 17:54 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md
> +|x509CertificateAuthenticationDefaultMode|x509CertificateAuthenticationMode|The type of strong authentication mode, possible values are: `x509CertificateSingleFactor` and `x509CertificateMultiFactor`
Yes correct

2022-01-26 17:54 UTC, opbld33 commented
Docs Build status updates of commit _[76e49ea](https://github.com/charlenezheng/microsoft-graph-docs/commits/76e49ea75d64459d1a578bf2e8c0e85c47a17d8d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) | [Details](#user-content-78dc60d8ef5ee60bb06f7ceedfe7fdee-341be035)
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="78dc60d8ef5ee60bb06f7ceedfe7fdee-341be035"></a>
### [api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md)
 - **Line 49, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261752394631-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T17%3A54%3A50Z&sr=b&sp=r&sig=Do%2BXFzREfawGRnHpN8Yj7dTLxMr0Qmuyzpy%2BWNQeCUk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 17:58 UTC, charlenezheng commented
Hi @FaithOmbongi, thank you so much for reviewing this PR. Could you please review it again when available? Thanks a lot!
Regarding to the comments:
_Q: Does this new API inject any values into the reporting APIs? E.g. for signIn API, authenticationMethodsUsed or authenticationDetail properties? If so, let's add these new possible values to the respective property descriptions._
This new API won't inject any values. It is only part of the authentication method policy

2022-01-26 18:17 UTC, opbld31 commented
Docs Build status updates of commit _[5555183](https://github.com/charlenezheng/microsoft-graph-docs/commits/5555183b6e36187a3effa60bb8f41ed424c5c971)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261815154070-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T18%3A17%3A38Z&sr=b&sp=r&sig=XDrYJNl7gYi1PbIg2%2FjELxf4ezNbd2SStoWigLuQDQI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 20:23 UTC, vimrang commented on api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md
> +|rules|[x509CertificateRule](../resources/x509certificaterule.md) collection| Rules are configured in addition to the authentication mode to bind a specific **x509CertificateRuleType** to an **x509Ce
bing -> bind

2022-01-28 20:28 UTC, vimrang commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +|[x509CertificateAuthenticationMethodConfiguration](x509CertificateAuthenticationMethodConfiguration.md)|Define users who can use X.509 certiificate to sign in to Azure AD.|
certiificate  -> certificate

2022-02-03 11:22 UTC, opbld33 commented
Docs Build status updates of commit _[be073c4](https://github.com/charlenezheng/microsoft-graph-docs/commits/be073c4e1b5e831df86d26c8e3fe9774add0883f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a45f2ad3)

<a id="a45f2ad3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202031121275545-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T11%3A22%3A07Z&sr=b&sp=r&sig=FYqXiIklMil4FYdtJG2Nr9FKyQlqd08Vbke09grWkRI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 11:24 UTC, charlenezheng commented on api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md
> +|rules|[x509CertificateRule](../resources/x509certificaterule.md) collection| Rules are configured in addition to the authentication mode to bind a specific **x509CertificateRuleType** to an **x509Ce
fixed

2022-02-03 11:24 UTC, charlenezheng commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +|[x509CertificateAuthenticationMethodConfiguration](x509CertificateAuthenticationMethodConfiguration.md)|Define users who can use X.509 certiificate to sign in to Azure AD.|
fixed

2022-02-03 11:25 UTC, opbld31 commented
Docs Build status updates of commit _[e4223b3](https://github.com/charlenezheng/microsoft-graph-docs/commits/e4223b3cc41a69835100888585d884c98c28f89d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-43bf2123)

<a id="43bf2123"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202031124475558-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T11%3A25%3A31Z&sr=b&sp=r&sig=0GNYWZ%2BSeDrhyXyVEbkNpeAUED2Gk3m2QjjZgQZn%2FAA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 11:48 UTC, opbld34 commented
Docs Build status updates of commit _[31e8b86](https://github.com/charlenezheng/microsoft-graph-docs/commits/31e8b8612bf11c05e45ce0162b7a0904133334cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202031146248013-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T11%3A48%3A23Z&sr=b&sp=r&sig=K6%2FsaSAAhf7C01n7oyUnQsstUxdM%2FeacsCFyLCtT%2FZ8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 18:21 UTC, opbld30 commented
Docs Build status updates of commit _[369f96b](https://github.com/charlenezheng/microsoft-graph-docs/commits/369f96bb393470efcfcac289f354bdbab9406876)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202031818436711-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T18%3A21%3A44Z&sr=b&sp=r&sig=CtplBasitfJz%2FR1oy2LQXoGXvh0mni%2FV7L6cNIW%2B9Io%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 20:14 UTC, opbld30 commented
Docs Build status updates of commit _[54247a8](https://github.com/charlenezheng/microsoft-graph-docs/commits/54247a8a23f88845181245ae2df8af3a9620ed28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202032006569019-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T20%3A14%3A47Z&sr=b&sp=r&sig=NimNe9a%2B%2FoaxbMZ62UBsVR%2F1Im42Xl%2FYuID8y065O5U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 20:17 UTC, FaithOmbongi approved these changes
Thank you @charlenezheng for your work on this PR.

2022-02-03 20:20 UTC, opbld34 commented
Docs Build status updates of commit _[34cbd3f](https://github.com/charlenezheng/microsoft-graph-docs/commits/34cbd3f036a6f9bbd439841d66a7bfa363bf98da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202032016426723-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T20%3A20%3A45Z&sr=b&sp=r&sig=W442oSslmyAxZctq6xrSlaH%2BGv7P48TFQtvbD24VyDY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 20:24 UTC, opbld31 commented
Docs Build status updates of commit _[34cbd3f](https://github.com/charlenezheng/microsoft-graph-docs/commits/34cbd3f036a6f9bbd439841d66a7bfa363bf98da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202032016537411-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T20%3A24%3A07Z&sr=b&sp=r&sig=xYMwWcDur3ZB1iac2W42SE8q1yHigOePYRJnjsUiEvk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 09:47 UTC, opbld34 commented
Docs Build status updates of commit _[00dfcb4](https://github.com/charlenezheng/microsoft-graph-docs/commits/00dfcb474a064742e65e3b7b360304ec6732c8b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202040940380856-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T09%3A47%3A45Z&sr=b&sp=r&sig=X0Vd4kwU6%2FFtnPsM2KzjVacl2Ef%2BPwC5u8lWwJkQzGI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-05 02:18 UTC, opbld33 commented
Docs Build status updates of commit _[80d208d](https://github.com/charlenezheng/microsoft-graph-docs/commits/80d208dd0515238283108617bb480163710c1f9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202050216077124-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-08T02%3A18%3A25Z&sr=b&sp=r&sig=nffJIU%2BUv28ZBAk6krGyj6iTwJjL7eLU8lSCjxTr9l0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-05 02:20 UTC, opbld31 commented
Docs Build status updates of commit _[aa44731](https://github.com/charlenezheng/microsoft-graph-docs/commits/aa44731e772d3e9f28f578cc1cedc20aca3f3675)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202050217357222-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-08T02%3A20%3A57Z&sr=b&sp=r&sig=R1%2BJq4SJvjCzUNdNE4zHvBFKjg2JfCIDnyRKIspAoEY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-05 02:24 UTC, opbld30 commented
Docs Build status updates of commit _[bb25660](https://github.com/charlenezheng/microsoft-graph-docs/commits/bb25660c5168fdca15a8cd7c42dc8aa4eb9a23b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificaterule.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/resources/x509certificateuserbinding.md](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-15524) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/charlenezheng/microsoft-graph-docs/blob/zhengyue/add-cba-changelog/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202050221111432-15524%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-08T02%3A24%3A07Z&sr=b&sp=r&sig=fl50SMRSDVsaUb3NoAZUTourmzS%2BMrPUO%2Bceq5ZaBVI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-05 02:26 UTC, merged