Update max staff count in resources
microsoftgraph/microsoft-graph-docs pull request #15536
Opened 2022-01-17 16:27 UTC by razortbone

2022-01-17 16:30 UTC, opbld32 commented
Docs Build status updates of commit _[88e59df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88e59dff5a236b854986ccf550708ab2921164b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsv1update/api-reference/v1.0/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-1.0&branch=pr-en-us-15536) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171627493182-15536%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T16%3A30%3A34Z&sr=b&sp=r&sig=%2FykNANOFKURdcl9JB%2FjolgrXmcI5Qf3Ig%2F9hJSEKtek%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 13:54 UTC, isvargasmsft commented on api-reference/v1.0/resources/bookingstaffmember.md
> +Microsoft Bookings supports a maximum of 100 staff members in a booking calendar.
Please add these updates to the beta file as well.

2022-01-19 13:54 UTC, isvargasmsft requested changes
Please add these updates to the beta file as well.

2022-01-21 07:03 UTC, razortbone commented on api-reference/v1.0/resources/bookingstaffmember.md
> +Microsoft Bookings supports a maximum of 100 staff members in a booking calendar.
Updated the beta documentation in the latest iteration.

2022-01-21 07:05 UTC, opbld33 commented
Docs Build status updates of commit _[9d6e4f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d6e4f57b445b830135e7f1a27f2f637bd2718cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsv1update/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-15536) (graph-rest-beta) |
[api-reference/v1.0/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/asaniyer-bookingsv1update/api-reference/v1.0/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-1.0&branch=pr-en-us-15536) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210703154332-15536%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T07%3A05%3A51Z&sr=b&sp=r&sig=3VkqBJIJ%2BfWmMmqZ2su0QFU8plZte0cu8jGbdlhvkXE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 20:20 UTC, isvargasmsft approved these changes

2022-01-27 04:09 UTC, merged