Marks activateService and activateServicePlan public APIs as deprecated.
microsoftgraph/microsoft-graph-docs pull request #15534
Opened 2022-01-17 14:23 UTC by Mwongela

Marks the `user/activateServicePlan` and `organization/activateServicePlan` APIs as deprecated. 

API review URL: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/9899. 

The two APIs above will be deprecated from the public beta and then exposed as privileged APIs.

2022-01-18 16:54 UTC, eketo-msft approved these changes

2022-01-19 08:23 UTC, FaithOmbongi requested changes
Thank you @Mwongela for working on this PR. Just some minor fixes and please more the changelog to be the first object in the file (starting at Line 3).

2022-01-19 08:23 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [activateServicePlan](https://docs.microsoft.com/en-us/graph/api/user-activateServicePlan?view=graph-rest-beta) method from the [user](https://docs.microsoft.
ChangeType fix
```suggestion
          "ChangeType": "Deprecation",
          "Description": "Deprecated the [activateServicePlan](https://docs.microsoft.com/en-us/graph/api/user-activateServicePlan?view=graph-rest-beta) method from the [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta) resource. This method will stop returning data after March 15, 2022.",
```

2022-01-19 08:23 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [activateService](https://docs.microsoft.com/en-us/graph/api/organization-activateService?view=graph-rest-beta) method to the [user](https://docs.microsoft.co
```suggestion
          "ChangeType": "Deprecation",
          "Description": "Deprecated the [activateService](https://docs.microsoft.com/en-us/graph/api/organization-activateService?view=graph-rest-beta) method from the [user](https://docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta) resource. This method will stop returning data after March 15, 2022.",
```

2022-01-19 08:23 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
> +| [activateServicePlan](../api/user-activateserviceplan.md) (deprecated) | None | Activate a service with a given `servicePlanId` and `skuId` for a given [user](user.md). |
Please move it to be the last row in this **Directory objects** section. Approx Line 85. For more info, please see the docs deprecation guidance.

2022-01-19 08:23 UTC, FaithOmbongi commented on api-reference/beta/api/user-activateserviceplan.md
> +> The user `activateServicePlan` API will be deprecated and will stop return data on March 15, 2022.
```suggestion
> The **activateServicePlan** API is deprecated and will stop returning data on March 15, 2022.
```

2022-01-19 08:23 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +In the request body, supply a JSON representation of the [activateService](../resources/activateService.md) (deprecated) object.
No need to indicate this here. The titles (API + resource) are sufficient.
```suggestion
In the request body, supply a JSON representation of the [activateService](../resources/activateService.md) object.
```

2022-01-19 08:23 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +> The organization `activateService` API will be deprecated and will stop returning data on March 15, 2022.
```suggestion
> The **activateService** API is deprecated and will stop returning data on March 15, 2022.
```

2022-01-21 15:44 UTC, opbld33 commented
Docs Build status updates of commit _[85bb36e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85bb36e22299224f46d842d9c68c9bd8b55c5230)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201211542323386-15534%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T15%3A44%3A42Z&sr=b&sp=r&sig=IpH6Xy%2F2bmAO0OY6Htl8lCzzmlcllaGiNRf2%2BWcXMR4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 15:45 UTC, Mwongela commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [activateServicePlan](https://docs.microsoft.com/en-us/graph/api/user-activateServicePlan?view=graph-rest-beta) method from the [user](https://docs.microsoft.
I have implemented this suggestion.

2022-01-21 15:45 UTC, Mwongela commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [activateService](https://docs.microsoft.com/en-us/graph/api/organization-activateService?view=graph-rest-beta) method to the [user](https://docs.microsoft.co
I have implemented this suggestion.

2022-01-24 07:15 UTC, FaithOmbongi commented
Closing and reopening to rebuild.

2022-01-24 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[85bb36e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85bb36e22299224f46d842d9c68c9bd8b55c5230)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201240716250265-15534%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T07%3A20%3A00Z&sr=b&sp=r&sig=Gbztt8Jb6l3BOKBUdxZDamLMYC4BpRp%2FM6fTgol6ZK8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 07:23 UTC, FaithOmbongi approved these changes
LGTM.

2022-05-17 14:33 UTC, opbld31 commented
Docs Build status updates of commit _[e01deeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e01deeb55e9cea49e4989c06ea866e2582970b6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205171431038277-15534/BuildReport?accessString=8ea99262b3409c35aea7fb38a24c470e96521763b2f38179d865151306421779).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 14:40 UTC, opbld34 commented
Docs Build status updates of commit _[b62b42d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b62b42d066058839eac3879baba92364a5ec170e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205171437490183-15534/BuildReport?accessString=de1894e44a152d0331a0fc1b50e0d2faa77a7a6be3f0191ea8c1fd67e0dd407e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 11:38 UTC, opbld34 commented
Docs Build status updates of commit _[b4f49a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4f49a88d0914a0f7de71cc510563d019ac30ef4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181135467405-15534/BuildReport?accessString=05ca27a70fc3113517828697acc7e35c2d10bcdc8c3bbf5b8cc464f42a26f95d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-28 01:36 UTC, opbld34 commented
Docs Build status updates of commit _[c0f41d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0f41d6e2f6a51640b36358816cf0ab98b474088)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205280133522079-15534/BuildReport?accessString=dd8e2bd02aa50d5016dea9740de51d8b66a375c6532588a620b76b8f983143e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 04:15 UTC, opbld32 commented
Docs Build status updates of commit _[80bb1fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80bb1fd0421c81a50b06e62847803e083f96ee1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-activateserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-15534) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/deprecateLicensingApis/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010408220812-15534/BuildReport?accessString=032619f6d4666015761c20886567b80212cb6f90585879c368bcc08a8f21ab33).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 04:15 UTC, merged