Exo rich notifications beta
microsoftgraph/microsoft-graph-docs pull request #15568
Opened 2022-01-19 21:02 UTC by abheek-das

Doc update for support of rich notifications for Outlook resources

2022-01-19 21:05 UTC, opbld31 commented
Docs Build status updates of commit _[c9b10e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9b10e10ef72231d129bd2b33ceaa7999b221e33)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) | [Details](#user-content-692ed0b31a0dd04e556f2348ac6af77b-c205e7fe)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |

<a id="692ed0b31a0dd04e556f2348ac6af77b-c205e7fe"></a>
### [concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md)
 - **Line 120, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/contact.md'.`````
 - **Line 121, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/event.md'.`````
 - **Line 122, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/message.md'.`````
 - **Line 136, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/contact.md'.`````
 - **Line 137, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/event.md'.`````
 - **Line 138, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/message.md'.`````
 - **Line 169, Column 54**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/subscription.md'.`````
 - **Line 173, Column 70**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/subscription.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201192102424260-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T21%3A05%3A23Z&sr=b&sp=r&sig=Cgm%2By9zy06dfckto6QEKlmpAWTsvdInCHkYkrHY4%2FSs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 21:07 UTC, opbld34 commented
Docs Build status updates of commit _[35a698f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35a698f0853bb5126dfac4817b854a3de8fdeb80)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) | [Details](#user-content-692ed0b31a0dd04e556f2348ac6af77b-7ecbface)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |

<a id="692ed0b31a0dd04e556f2348ac6af77b-7ecbface"></a>
### [concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md)
 - **Line 120, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/contact.md'.`````
 - **Line 121, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/event.md'.`````
 - **Line 122, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/message.md'.`````
 - **Line 136, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/contact.md'.`````
 - **Line 137, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/event.md'.`````
 - **Line 138, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/message.md'.`````
 - **Line 169, Column 54**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/subscription.md'.`````
 - **Line 173, Column 70**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/subscription.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201192102523291-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T21%3A07%3A20Z&sr=b&sp=r&sig=rQpoPbz4ZDhhjkTQTeJopC3PLtg8Zag8wwWbDSs4TJY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 21:15 UTC, opbld32 commented
Docs Build status updates of commit _[f22c9d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f22c9d8dc14f1b36ada1b4c9f9299e9842927531)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) | [Details](#user-content-692ed0b31a0dd04e556f2348ac6af77b-074d3bb3)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |

<a id="692ed0b31a0dd04e556f2348ac6af77b-074d3bb3"></a>
### [concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md)
 - **Line 120, Column 3**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/contact.md' referenced by link '../api-reference/v1.0/resources/contact.md' will not be built because it is not included in build scope.`````
 - **Line 121, Column 3**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/event.md' referenced by link '../api-reference/v1.0/resources/event.md' will not be built because it is not included in build scope.`````
 - **Line 122, Column 3**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/message.md' referenced by link '../api-reference/v1.0/resources/message.md' will not be built because it is not included in build scope.`````
 - **Line 136, Column 2**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/contact.md' referenced by link '../api-reference/v1.0/resources/contact.md' will not be built because it is not included in build scope.`````
 - **Line 137, Column 2**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/event.md' referenced by link '../api-reference/v1.0/resources/event.md' will not be built because it is not included in build scope.`````
 - **Line 138, Column 2**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/message.md' referenced by link '../api-reference/v1.0/resources/message.md' will not be built because it is not included in build scope.`````
 - **Line 169, Column 54**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/subscription.md' referenced by link '../api-reference/v1.0/resources/subscription.md' will not be built because it is not included in build scope.`````
 - **Line 173, Column 70**: **[Warning: link-out-of-scope]** `````File '../api-reference/v1.0/resources/subscription.md' referenced by link '../api-reference/v1.0/resources/subscription.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201192113291556-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T21%3A15%3A36Z&sr=b&sp=r&sig=hVN6f0DnJdjEQNU855Wnnr8AonfYJjIXiZ0Y1FVxqDc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 21:30 UTC, opbld32 commented
Docs Build status updates of commit _[f050866](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0508665d4189b37a39c1e0c91abebbd3695f3a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201192127583106-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T21%3A30%3A16Z&sr=b&sp=r&sig=i0bwEuousMavQ2eydkEN%2Fmus9Z3KWd4hETHCBd1NeQs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 21:37 UTC, abheek-das commented
@angelgolfer-ms Hi Angela, This is another doc update that I was working on which is for EXO rich notification, and the capability is now present in Microsoft Graph beta. Since there was a couple of different aspects that needed to be covered with respect to Exchange change notification, I thought we might need a concept page for it. 

So, I created this draft PR and added a page with all the details that we would probably need to include. Could you please help take a look and provide some feedback/guidance? I am totally okay if you want to restructure the content or if you think a concept page might not be needed - I just though I'll make a start and put all the content in a single place first :smile:.

2022-01-20 06:26 UTC, opbld31 commented
Docs Build status updates of commit _[e6e6855](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6e6855c69315aaf72a9b959d35f6cbc3661d498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200623451095-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T06%3A26%3A25Z&sr=b&sp=r&sig=Cq9lbUDJ3Lr1E7OPoL22PJLMUnZmlC0sO0hNCE%2Fs2RM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 05:18 UTC, opbld30 commented
Docs Build status updates of commit _[e65416c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e65416c9bb3c661d12d2be12cd101c5e83772eeb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210515505906-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T05%3A18%3A24Z&sr=b&sp=r&sig=oBFFw0K8ylzdoR8QkeoUboej6RwrBi5zNLPh%2BhTrdXU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 09:12 UTC, opbld33 commented
Docs Build status updates of commit _[b7dd104](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7dd1048d07572af7e0502f2593769404ee10af8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201210909316737-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T09%3A12%3A16Z&sr=b&sp=r&sig=Mu3QeG%2BTwn5XeAddaJ23bLRAb%2FO6zMrUGYTe%2B0UXjIQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-22 12:40 UTC, opbld30 commented
Docs Build status updates of commit _[996485e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/996485ea417ec5fbe9ceea7b388469df9eedf10d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201221238126853-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-22T12%3A40%3A29Z&sr=b&sp=r&sig=6G2A5nNQ0YVmd0vtzsrxUImMd9rGakVgmf4Fa%2BVAGkE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 06:38 UTC, opbld31 commented
Docs Build status updates of commit _[1204737](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1204737503c9f18c259de5b3df95996df0fa78e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201250636189415-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T06%3A38%3A23Z&sr=b&sp=r&sig=6xFq%2FUJ4OFhEMDPFOC4cJ4xWo9%2FviMXp%2BrnFJljivMc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 12:17 UTC, opbld32 commented
Docs Build status updates of commit _[44934c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44934c634d153ed8a1dd89404b16c6633f13e1cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261214227551-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T12%3A17%3A43Z&sr=b&sp=r&sig=o2o3VShmkvoTXTyd%2B%2BPXvYNQasjcxzMsLToQXwJLXQo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 07:36 UTC, opbld33 commented
Docs Build status updates of commit _[8de6897](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8de6897b283e79f834cbca7075313b99b790e4bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201290733576739-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T07%3A36%3A45Z&sr=b&sp=r&sig=eaIhGpg12IQ3o%2FfiJ5IajhwR0xkfbjNld6m60%2BCNtCc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 09:50 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +# Change notifications for Outlook resources using Microsoft Graph
Line 10:
@abheek-das , FYI I changed "using" to the preposition "in".
Remind me we should change that in the title for teams-change-notification-in-microsoft-teams-overview.md as well.

2022-01-29 10:12 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +calling the API to get the payload.
Line 13:
I find this sentence (just as in the Teams concept topic) phrased in an odd way. I guess it's trying to say, because the approach is a subscription model where the overhead occurs just at the beginning when setting up the subscription, every subsequent notification incurs low latency (little delay between the time of the event and receiving its notification).
"The subscription approach reduces the delay between the time of a change and receiving its notification."

In addition, when setting up a subscription, you can specify notifications to include resource data, thereby avoiding a separate subsequent API call to get the resource payload."

2022-01-29 10:15 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +Create one or more single-value extended properties in a new or existing instance of a resource.
Line 117:
@abheek-das , can you update this sentence for Outlook resources please?

2022-01-29 10:20 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +## Subscribe to changes in mail, calendar or contacts
Lines 115-153:
I feel that we should first talk about setting up a subscription, then follow by the kinds of notifications.
Can you please move this section to before the "Notifications payload" section (line 20)?

2022-01-29 10:28 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +
Line 18 would not be necessary after you move the section titled "Subscribe to changes in mail, calendar or contacts" up here, before the "Notification payloads" section.

2022-01-29 10:40 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +
After line 125:
I think here we can again bring up that the above resources support subscriptions with or without data.
Then we should specify how the create subscription operation differs between both.
Make sure to point out with resource data is only available in beta.

That would be similar to the "Creating a subscription" section (https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data#creating-a-subscription).
Even though usually I wouldn't suggest repeating similar content, because creating subscriptions is a necessary step, we shouldn't make customers jump to another topic. If you can, please rephrase parts of that section so that search engines don't lower the search ranking of both topics.

2022-01-29 11:06 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +## HTTP request
Lines 155-176:
We try not to use any structure or section formatting in a concept topic that might make customers feel they're looking at a reference topic. Please delete these lines. Instead, I suggested above around line 125 linking to the subscription-post-subscriptions.md topic.

2022-01-29 11:07 UTC, angelgolfer-ms requested changes
@abheek-das , I commented about moving some sections around in your topic. 
After you do so, let me know and I'll see what else we can improve. Thanks!

2022-01-29 11:23 UTC, opbld33 commented
Docs Build status updates of commit _[be63b02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be63b02fbf5f2898b7bcb1e4fa947042dc5be510)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201291120325788-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-01T11%3A23%3A29Z&sr=b&sp=r&sig=u1OkpXRBbabk00BvI6OmI%2Fd3uMr37RyK5XPvxaOTvQg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 13:27 UTC, opbld30 commented
Docs Build status updates of commit _[f34d9d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f34d9d108456e4e95cbd8b46974a95800ecadc6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) | [Details](#user-content-692ed0b31a0dd04e556f2348ac6af77b-ba943e56)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |

<a id="692ed0b31a0dd04e556f2348ac6af77b-ba943e56"></a>
### [concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md)
 - **Line 55, Column 154**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#decrypting-resource-data-from-change-notifications' in 'outlook-change-notification-in-outlook-overview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071324452419-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T13%3A27%3A33Z&sr=b&sp=r&sig=FvetpNN6ANydz9kRL8sI2tpER53SRLy8Gzj3QNjPB9o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 13:31 UTC, opbld34 commented
Docs Build status updates of commit _[28aeaba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28aeaba7ec7c1ad7463ff0e77efc061e5c390636)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) | [Details](#user-content-692ed0b31a0dd04e556f2348ac6af77b-514b6235)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |

<a id="692ed0b31a0dd04e556f2348ac6af77b-514b6235"></a>
### [concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md)
 - **Line 55, Column 154**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#decrypting-resource-data-from-change-notifications' in 'outlook-change-notification-in-outlook-overview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071325201104-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T13%3A31%3A09Z&sr=b&sp=r&sig=e1JE%2BL7lWnG%2BbjKzo6ICxKQ61bZTfHze46MDpbb8r1g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 13:54 UTC, opbld31 commented
Docs Build status updates of commit _[f607116](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f607116c9448a88865d9f86317db48e0c2a29d2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071350564124-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T13%3A54%3A02Z&sr=b&sp=r&sig=EObFEn9tK8WMk0tY10Evkm1qtCIkCkm8k2sdUcd6OOA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 14:00 UTC, opbld31 commented
Docs Build status updates of commit _[02155a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02155a7154d063f6ff1d7e8f74fe91f05f410674)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-18ac2f4e)

<a id="18ac2f4e"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071358334356-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T14%3A00%3A13Z&sr=b&sp=r&sig=woAaKQuxfAf0dLWFkNsXBPa1LNfloPmpogLkQAr1MHA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 14:03 UTC, opbld34 commented
Docs Build status updates of commit _[3532932](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35329327499bac6435b096e4a98d0900229dde63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071359452183-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T14%3A03%3A12Z&sr=b&sp=r&sig=oKsPertR2hmYgYI1Vjr0rJxM2elP0FzoZGZO3lu0I4E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 18:36 UTC, opbld32 commented
Docs Build status updates of commit _[b3438d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3438d948993da0bceb02eafa5d06ea9dba9ff1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071833513193-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T18%3A36%3A03Z&sr=b&sp=r&sig=hsxZEqDr002XV69hPiK3wUPj2P7LN5zVDzT71M76K5E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 19:03 UTC, opbld31 commented
Docs Build status updates of commit _[ac2166a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac2166a7ae0382776434e4819f16931e3544a0c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081901213628-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T19%3A03%3A53Z&sr=b&sp=r&sig=pZC0tH5IeGnLMvwnMO3gabdN6aCheEvklTt%2BnEm1vzg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 05:35 UTC, opbld33 commented
Docs Build status updates of commit _[6a4d555](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a4d5550a510059be8222313a7050fdf52784855)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202140531365785-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T05%3A35%3A30Z&sr=b&sp=r&sig=l%2Flyy67H5bwzSfeExMHmBUs8qTWfNwmvoFezoIq5PQ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 05:21 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +Change notifications enable you to subscribe to changes (create, update, and delete) to a resource. The [subscription](/graph/api/resources/webhooks?preserve-view=true) approach reduces the delay bet
Line 12:
I think you used "change notifications" to refer to the feature and you mean to say, that {feature} enables customers to subscribe to changes and receive notifications. However, using "change notifications" that way can be confusing especially to Loc, because a change notification represents the web-based message about the change, which is enabled by an active subscription (the other way around).

So I am going to rephrase that first sentence, and roll in the term "webhooks" for SEO. Many people like to call this feature webhooks which in itself refers to the technique and is not privy to change notifications.

I'll also rewrite the sentence slightly to avoid the parentheses.

2022-02-16 08:57 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +## Creating a subscription
Section titles:
FYI I think for this topic (which is informative content), using infinitive without to in the section titles is appropriate. For example, "Create a subscription". More info here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=28110

2022-02-16 09:53 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The maximum time a subscription can last for an Outlook resource is 4320 minutes for notification without resource data and 1 day for notification with resource data; however, [subscriptions can be r
Line 77:
The last phrase is not clear to me. To me, it's saying "one can update a subscription and renew it until the caller has permissions to access the resource"?
Do you mean, sometimes the caller doesn't get granted the permissions to complete the subscription request before the expiry date-time. So the caller should keep extending the expiry until the caller gets permissions to access the resource and subscribe to its changes?

2022-02-16 10:09 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The maximum time a subscription can last for an Outlook resource is 4320 minutes for notification without resource data and 1 day for notification with resource data; however, [subscriptions can be r
If that's what you meant, then in place of the last phrase in line 77, I would suggest this:
```
Sometimes, a subscription request can expire before the user or administrator grants the requested permissions. In this case, [extend the expiry of the subscription](/graph/api/subscription-update) until you get the necessary permissions to complete the subscription request.
```

I would not characterize the action as renewing the subscription. "Renew" implies the subscription was already created. How about "extend the expiry"?

2022-02-16 10:11 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The maximum time a subscription can last for an Outlook resource is 4320 minutes for notification without resource data and 1 day for notification with resource data; however, [subscriptions can be r
Meanwhile, I kept your last phrase and just rephrased it in active voice:
```
You can [renew a subscription](/graph/api/subscription-update) until you get permissions to access the resource.
```

You can clarify what you meant please.

2022-02-16 10:43 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The payload looks like the following. This payload is for a message sent in a channel.
Line 144:
"This payload is for a message sent in a channel."
Isn't a message sent in a channel a chatMessage? That's different from a message resource.

I'm going to bring lines 164 and 166 up to before the JSON in line 146, so that the audience would not miss those lines. I'm going to assume the sentence "This payload is for a message sent in a channel." is irrelevant.
If I overlooked something, please update the related text (after I check in my changes).

2022-02-16 10:54 UTC, opbld31 commented
Docs Build status updates of commit _[446cbef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/446cbef21d92c107819984cc7a983802ec47eb12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202161052212972-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T10%3A54%3A49Z&sr=b&sp=r&sig=emzLgOdpOyK5lsWWV38GsmSV0tMdr0B5tWaZaXzk1YQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 10:58 UTC, opbld32 commented
Docs Build status updates of commit _[54cc021](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54cc021882e2404dabf38ebcadb39ac08988e4aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[concepts/outlook-change-notification-in-outlook-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notification-in-outlook-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notification-in-outlook-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202161052529324-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T10%3A58%3A33Z&sr=b&sp=r&sig=hlvAYLsa53l5%2BBjTeRpqdlB7bvBs1rtvZ%2FJ9hLaerHU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 10:59 UTC, angelgolfer-ms requested changes
Hi @abheek-das , I am about more than half way through, making edits directly in your PR for clarity and voice. I will continue and finish tomorrow, as it's pretty late right now over here.
Meanwhile, if you have a chance, you can please take a look at my comments. I think there's at least one that you might want to clarify, about "renewing" a subscription...
Otherwise, it's ok, I'll just wrap up my pass tomorrow and you can take a look at the entire article after I finish. BTW I'll be OOF 2/18 and 2/21 is a holiday in our time zone. So if you'd like to wrap this up this week, I would need to complete our collaborative review on 2/17. If not, we'll continue next week (and I know you mentioned the capability is already live).

2022-02-16 19:08 UTC, abheek-das commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The payload looks like the following. This payload is for a message sent in a channel.
Yes, "This payload is for a message sent in a channel." is for Teams chat messages. I might have overlooked it. Thanks for removing this!

2022-02-16 19:18 UTC, abheek-das commented
Thanks @angelgolfer-ms , I'll try to address any comments by 17th itself and hopefully we'll be able to publish it this week itself!

2022-02-16 19:29 UTC, abheek-das commented on concepts/outlook-change-notification-in-outlook-overview.md
> +Change notifications enable you to subscribe to changes (create, update, and delete) to a resource. The [subscription](/graph/api/resources/webhooks?preserve-view=true) approach reduces the delay bet
Sounds good! "Webhooks based change notification" can also work to remove all confusion. You are right that I was referring to the feature here, and I used "Change Notifications" because in one of our already published docs we used "Set up change notifications that include resource data" as title. But I'm in agreement with you in general!

2022-02-16 20:16 UTC, abheek-das commented
@angelgolfer-ms A few more questions:

1. There's some places in docs where the some parts of the information in this page is mentioned in fragments. E.g: About Number of subscription - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations, About permissions : https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#contact-event-and-message . Do you think to avoid duplication, we should just remove the above sections from corresponding pages and replace it with a link to the section in this new concept page? That way this concept-page becomes a single page reference for EXO notification.
2. Do we need a change-log entry here? As such there's no schema change etc. Just that an existing change notifications feature got enabled for Exchange service as well. If yes, could you point me to an example of how change-log entry looks like for concept pages?
3. I could not figure out how to make a new page show up in the index on the left side in the navigation pane. If you could help add that, it would be great! I think it would go under this section - 
![image](https://user-images.githubusercontent.com/65342232/154349608-5ce0ae9b-cee5-46de-b868-a403e8cd7e60.png)

2022-02-17 04:49 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The maximum time a subscription can last for an Outlook resource is 4320 minutes for notification without resource data and 1 day for notification with resource data; however, [subscriptions can be r
Oh, so what is the message we're trying to say? 

"If you lose the permission that was granted earlier for a subscription and the subscription expires, you will have to request permission again to create a new subscription?"

The section "Keep track of subscription lifetime" will go like this:
"Make sure to extend a subscription before it expires. The maximum lifetime for a subscription without Outlook resource data is 4320 minutes (under 3 days), and 1 day with resource data. 

If you lose the permission that was granted earlier for a subscription and the subscription expires meanwhile, request permission again to create a new subscription."

Add links to "extend" and "create", to link to the subscription update and create operations.

2022-02-17 10:34 UTC, angelgolfer-ms commented
> @angelgolfer-ms A few more questions:
> 
> 1. There's some places in docs today where some parts of the information in this page is mentioned in fragments. E.g: About Number of subscription - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations, About permissions : https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#contact-event-and-message . Do you think to avoid duplication, we should just remove the fragments from the existing pages and replace them with a link to the respective section in this new concept page? That way this concept-page becomes a single page reference for EXO notification.
> 2. Do we need a change-log entry here? As such there's no schema change etc. Just that an existing change notifications feature got enabled for Exchange service as well. If yes, could you point me to an example of how change-log entry looks like for concept pages (as in its neither going into beta or v1.0, but rather an information page)?
> 3. I could not figure out how to make a new page show up in the index on the left side in the navigation pane. If you could help add that, it would be great! I think it would go under this section -
>    ![image](https://user-images.githubusercontent.com/65342232/154349608-5ce0ae9b-cee5-46de-b868-a403e8cd7e60.png)

For #1: yes, thanks for bringing that up. We can use the !INCLUDE syntax.  We keep the repeated content in one file, and all instances of that content use the !INCLUDE syntax so that it's easier to maintain. That's how the Teams folks specify their section under the "Permissions" section in each of the create, get, update, delete operation topics for subscription. More info about the !INCLUDE syntax here: https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=main

In the interest of time, I implemented that and you can take a look to see if your concept topic and each of the create, get, update, delete operation topics for subscription looks right in their "Permissions" section. 

For #2: Well, rich notifications is the only thing new for Outlook resources in this PR, right. There is no _schema_ level change for the subscription entity, its create operation, and the [changeNotification](https://docs.microsoft.com/en-us/graph/api/resources/changenotification) entity. The change is the behavioral, e.g., the 3 properties (includeResourceData, encryptionCertificate, encryptionCertificateId) of subscription, and the 2 properties (encryptedContent and resourceData) of changeNotification used not to do anything but they work now to support subscribing to rich notifications for Outlook resources. So technically, these are still API-level behavioral changes that should be in the changelog. On the other hand, because the changelog today is driven/generated by any difference in the schema, we have to put together the changelog manually. In the interest of time, I added the changelist record updates - one set for v1, one set for beta - in Microsoft.Exchange.json in your PR. Please take a look. See more info about the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples).

For #3: Sure, I can add that to the toc.yml in the concepts folder. Please take a look. (There are altogether 3 toc.yml in the entire doc set right now, one for the conceptual section, one for v1, one for beta.)

BTW, there seems to be a little can of worms for the existing content. I attribute that to the complicated ownership for shared features like change notifications, and change of Identity side feature owner a couple of years back:
(A) Does this existing concept topic [Set up change notifications that include resource data](https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data) largely apply to Outlook resources as well? 
**If it does:
- Can you add the Outlook resources to this [section](https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data#supported-resources)?
- Can you also add a link to your new topic in the [See-also](https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data#see-also) section of that topic?**
FYI I added a link in your concept topic to go to the [Set up change notifications that include resource data](https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data) topic.

(B) It seems to me the [create subscription](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions) topic needs to point out at the top there's this option for rich notifications for some resources. The info is embedded for the Teams resources in the "Permissions" section right now, mixed in with a lot of other details for Teams. There's no mention of that capability for Outlook resources in that "create" API topic right now. The example doesn't show that either. At a glance, how would customers know this is a capability and an option for some resources?

I made a brief mention up top in the create operation topic and added links to that pre-existing rich notifications topic and your new concept topic.

2022-02-17 10:38 UTC, angelgolfer-ms commented on concepts/outlook-change-notification-in-outlook-overview.md
> +---
FYI I am renaming your file to outlool-change-notifications-overview.md to make it shorter.

2022-02-17 10:43 UTC, opbld30 commented
Docs Build status updates of commit _[c405871](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c405871d9130490e12f5cbb6777b0c8bce76be7d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :x:Error | | [Details](#user-content-1c503771e0b17f25a0067533ec73b472-267800a7)

<a id="1c503771e0b17f25a0067533ec73b472-267800a7"></a>
### [concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md)
 - **Line 32, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/outlook-subscription-notes.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171039553472-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T10%3A43%3A14Z&sr=b&sp=r&sig=p39S7VPBsLkZT2tqUXNoA%2Bi5S0dp6p%2BzDdgDujS0P6c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 10:52 UTC, opbld34 commented
Docs Build status updates of commit _[8ef9ff3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ef9ff3aa3e0eea21f395fb57f03cdefc6e30605)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171049375179-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T10%3A52%3A00Z&sr=b&sp=r&sig=4b9%2Fhflsou0H9AilAr3rW6%2BSqV38GhjTgYrOs8Jlegw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 10:55 UTC, angelgolfer-ms requested changes
Hi @abheek-das , I addressed most of the questions you brought up yesterday. Please take a look at my long comment reply to those questions.

Also, this one comment still needs your clarification: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15568#discussion_r808673053

I ended up spending most of the time this evening addressing the questions you brought up, so I haven't taken a look at the remaining parts of the concept topic, mostly the examples section. I'll continue tomorrow. 

If there are any remaining issues that I need you to address and they are straightforward, even though I'll be out starting tomorrow evening, you can still finish up and have Laura publish on 2/18 PST. But let's see how far you and I can get in the next day.

2022-02-17 10:59 UTC, angelgolfer-ms commented
Oh. @abheek-das , I forgot about handling this repetition you brought up in your first question:
About Number of subscription - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations,

Would you mind modelling what we did for the permissions limitations section, and implementing the !INCLUDE for that? You probably want to first verify how many places mention that 1000 subscriptions limit...

2022-02-17 11:09 UTC, opbld30 commented
Docs Build status updates of commit _[6cd3970](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cd3970649e39a0570cbf20fc4cc0e4f31b1c5dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171105510976-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T11%3A09%3A14Z&sr=b&sp=r&sig=5220nDf8baAm8DYem6TAEk5yHsBhoXVjlybQwfgeMB0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 11:32 UTC, opbld32 commented
Docs Build status updates of commit _[d8dec8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8dec8c627cfd4494668635e1be7e13b1a4e1b7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171130318339-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T11%3A32%3A51Z&sr=b&sp=r&sig=Bw0tIkcwWlbtgx8vdjfbsek9jrmCyjW9XjD0%2BTFw1b4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 11:37 UTC, opbld30 commented
Docs Build status updates of commit _[c9c0a9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9c0a9d40eb21e97802f8a711f99e61fa0d4f262)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171135340557-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T11%3A37%3A37Z&sr=b&sp=r&sig=dsywPRJv8Re%2BShUvN7vsiuuRwM5yT3kD9fwNBJ4WR%2F4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 19:21 UTC, abheek-das commented
> Oh. @abheek-das , I forgot about handling this repetition you brought up in your first question: About Number of subscription - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations,
> 
> Would you mind modelling what we did for the permissions limitations section, and implementing the !INCLUDE for that? You probably want to first verify how many places mention that 1000 subscriptions limit to see if using !INCLUDE makes sense though.

@angelgolfer-ms It looks like this is just repeated in one other place - here - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations. So maybe we should just let this be as it is?

2022-02-17 19:42 UTC, opbld31 commented
Docs Build status updates of commit _[53e2aca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53e2aca9555df444949b3aef9864266cb151dccf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/webhooks-with-resource-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171940118574-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T19%3A42%3A27Z&sr=b&sp=r&sig=6bAo4O42TwQOQMa8zBR5rchP6BEehaeFNTL%2BMiSfpII%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 19:54 UTC, abheek-das commented on concepts/outlook-change-notification-in-outlook-overview.md
> +The maximum time a subscription can last for an Outlook resource is 4320 minutes for notification without resource data and 1 day for notification with resource data; however, [subscriptions can be r
> Oh, so what is the message we're trying to say?
> 
> "If you lose the permission that was granted earlier for a subscription and the subscription expires, you will have to request permission again to create a new subscription?"
> 
> The section "Keep track of subscription lifetime" will go like this: "Make sure to extend a subscription before it expires. The maximum lifetime for a subscription without Outlook resource data is 4320 minutes (under 3 days), and 1 day with resource data.
> 
> If you lose the permission that was granted earlier for a subscription and the subscription expires meanwhile, request permission again to create a new subscription."
> 
> Add links to "extend" and "create", to link to the subscription update and create operations.

Yes this description looks perfect. I have made the changes and updated the section as per above. Added links to "extend" and "create", to link to the subscription update and create operations as well.

2022-02-17 19:54 UTC, opbld33 commented
Docs Build status updates of commit _[5a1957b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a1957b3150e7c17d02bff94e71791491a92981d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/webhooks-with-resource-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202171952432700-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T19%3A54%3A44Z&sr=b&sp=r&sig=1oXRMOh9M8RulqxwHjfjGiqHhaJMRSyEGTcTB0rZuHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 05:46 UTC, angelgolfer-ms commented
> > Oh. @abheek-das , I forgot about handling this repetition you brought up in your first question: About Number of subscription - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations,
> > Would you mind modelling what we did for the permissions limitations section, and implementing the !INCLUDE for that? You probably want to first verify how many places mention that 1000 subscriptions limit to see if using !INCLUDE makes sense though.
> 
> @angelgolfer-ms It looks like this is just repeated in one other place - here - https://docs.microsoft.com/en-us/graph/webhooks#outlook-resource-limitations. So maybe we should just let this be as it is?

Ok.

2022-02-18 05:58 UTC, opbld33 commented
Docs Build status updates of commit _[372325b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/372325b400ab54660933f6f2f8cbb8ff81a2df99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) | [Details](#user-content-1c503771e0b17f25a0067533ec73b472-f4c0aaa0)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/webhooks-with-resource-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

<a id="1c503771e0b17f25a0067533ec73b472-f4c0aaa0"></a>
### [concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md)
 - **Line 54, Column 8**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-2-create-a-subscription-to-get-change-notifications-with-resource-data-when-the-user-receives-a-new-message' in 'outlook-change-notifications-overview.md', did you mean '#example-1-create-a-subscription-to-get-change-notifications-without-resource-data-when-the-user-receives-a-new-message'?`````
 - **Line 58, Column 105**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-3-create-a-subscription-to-get-change-notifications-with-resource-data-for-a-message-based-on-a-condition' in 'outlook-change-notifications-overview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202180555386761-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T05%3A58%3A31Z&sr=b&sp=r&sig=u3r1zvGvX1jSiM%2FOi7hPLqrDFfTi2%2FRmAxBXe2CPiKU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https:// [...]

2022-02-18 06:00 UTC, opbld33 commented
Docs Build status updates of commit _[118c225](https://github.com/microsoftgraph/microsoft-graph-docs/commits/118c225fbc5dd951aac25de4cbb7f060af78cb30)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) | [Details](#user-content-1c503771e0b17f25a0067533ec73b472-106d0e91)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/webhooks-with-resource-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

<a id="1c503771e0b17f25a0067533ec73b472-106d0e91"></a>
### [concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md)
 - **Line 54, Column 8**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-2-create-a-subscription-to-get-change-notifications-with-resource-data-when-the-user-receives-a-new-message' in 'outlook-change-notifications-overview.md', did you mean '#example-1-create-a-subscription-to-get-change-notifications-without-resource-data-when-the-user-receives-a-new-message'?`````
 - **Line 58, Column 105**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-3-create-a-subscription-to-get-change-notifications-with-resource-data-for-a-message-based-on-a-condition' in 'outlook-change-notifications-overview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202180557034677-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T06%3A00%3A33Z&sr=b&sp=r&sig=sPjCbzIbmDrkFvigWCayz%2BbsBaQx%2F8ExwkT6bYq5rc8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https:// [...]

2022-02-18 07:59 UTC, opbld33 commented
Docs Build status updates of commit _[83137ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83137ef858c07808f1995347346fca4f42328edd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-15568) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-15568) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/concepts/webhooks-with-resource-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-15568) |
[includes/outlook-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/EXORichNotificationsBeta/includes/outlook-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-15568) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202180758039170-15568%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T07%3A59%3A47Z&sr=b&sp=r&sig=8P%2BjwTYuXbg5mkRa2iZECuaLLFw9tIHTOtvsfw%2FH7Pc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 08:15 UTC, angelgolfer-ms approved these changes
@abheek-das , I made a few more updates and fixed some overlooked issues in existing related topics. I think the PR is fine to publish. 
After you take a look and confirm things look good, please set the PR to ready to merge so that Lauragra can publish it.

2022-02-19 05:00 UTC, merged