Add SubscriptionId and SubscriptionDisplayName in cloudPcSourceDeviceImage
microsoftgraph/microsoft-graph-docs pull request #15606
Opened 2022-01-24 01:42 UTC by jianie365

2022-01-24 01:46 UTC, opbld32 commented
Docs Build status updates of commit _[de05033](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de0503376a0d4f0b46fc1a66270499eab4bb042d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcsourcedeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/resources/cloudpcsourcedeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsourcedeviceimage?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201240142269489-15606%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T01%3A46%3A57Z&sr=b&sp=r&sig=nzg5eQYtJ8mIZvVpjPZwB8mhjyawbh0qMQchO5yHJDA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 02:29 UTC, AshleyYangSZ commented
@jianie365 Change-log needed as well. See this for example https://github.com/microsoftgraph/microsoft-graph-docs/pull/15416

2022-01-25 07:52 UTC, RuiHou105 commented
@jianie365  Could you please also update `cloudpcdeviceimage-getsourceimages.md` file? And the `Microsoft.CloudManagedDesktop.json` file ( record the changelog)?

2022-03-03 03:43 UTC, opbld30 commented
Docs Build status updates of commit _[650bf5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/650bf5abc99781f126e1810fb8d8d99fdfad64ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsourcedeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/resources/cloudpcsourcedeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsourcedeviceimage?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030341352215-15606%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T03%3A43%3A26Z&sr=b&sp=r&sig=mrj2bOOqVifjBdz%2FD7tYVIwNR8XRmsf9rl04vL5KYEE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:57 UTC, AshleyYangSZ requested changes

2022-03-03 04:57 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the **subscriptionDisplayName** property to [cloudPcSourceDeviceImage](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcSourceDeviceImage?view=
Remove the intune- prefix, it's wrong.

2022-03-03 04:57 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the **subscriptionId** property to [cloudPcSourceDeviceImage](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcSourceDeviceImage?view=graph-res
Same here.

2022-03-03 05:45 UTC, opbld31 commented
Docs Build status updates of commit _[ee25dfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee25dfa1b12567e27c5698250a0a7b66598cfaf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsourcedeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/resources/cloudpcsourcedeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsourcedeviceimage?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030543218186-15606%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T05%3A45%3A18Z&sr=b&sp=r&sig=92XY8flTW2ewZYCm7EaC9wwxbDZbHZwrzWa4LrtqFKM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-13 12:46 UTC, AshleyYangSZ approved these changes

2022-03-15 03:32 UTC, RuiHou105 approved these changes

2022-03-20 08:08 UTC, AshleyYangSZ commented
@jianie365 Please add roadmap for this PR

2022-03-22 02:01 UTC, Lauragra approved these changes

2022-03-22 02:03 UTC, opbld32 commented
Docs Build status updates of commit _[d0ee695](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0ee69536b136d287a50b593cdc0a12763d06166)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsourcedeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/api-reference/beta/resources/cloudpcsourcedeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsourcedeviceimage?view=graph-rest-beta&branch=pr-en-us-15606) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jianie/image/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203220201164614-15606%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T02%3A03%3A15Z&sr=b&sp=r&sig=hJdHvp1dpHf%2FeM4R%2BTqjZt47w8EWVdcYIee59okPp6I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 02:08 UTC, merged

2022-03-23 02:43 UTC, jianie365 commented
Roadmap workitem:

https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/13520

2022-03-23 03:00 UTC, jianie365 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the **subscriptionId** property to [cloudPcSourceDeviceImage](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcSourceDeviceImage?view=graph-res
Fixed

2022-03-23 03:00 UTC, jianie365 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the **subscriptionDisplayName** property to [cloudPcSourceDeviceImage](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcSourceDeviceImage?view=
Fixed.