Dynamic AU Updates
microsoftgraph/microsoft-graph-docs pull request #15605
Opened 2022-01-23 20:30 UTC by DougKirschner

2022-01-23 20:31 UTC, opbld34 commented
Docs Build status updates of commit _[b929f1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b929f1b49402fcf988c95c80e79adf66c8213251)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ee074c6f)

<a id="ee074c6f"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201232031001508-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T20%3A31%3A36Z&sr=b&sp=r&sig=TqSzca4Kn71VnGybjVLZvnbep1mwB8NY0QtjTjsJLuU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-23 21:01 UTC, opbld30 commented
Docs Build status updates of commit _[8e2f972](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e2f972d13c6d45bac3d9778d671c9310e918dd5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-e27d2ede)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="587d07eace2c4d640a05d29494f64382-e27d2ede"></a>
### [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-members.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201232058310964-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T21%3A01%3A17Z&sr=b&sp=r&sig=JRTWYsejkoMlDARzqfkP4kmzfGoaq6zlWwd1jayz0hU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 09:05 UTC, FaithOmbongi requested changes
Thank you @DougKirschner for your work on this PR. I've left a few suggestions to address in addition to the following 2 major feedback:

- Gap: Document the 3 new properties in the administrativeUnit's doc Properties table.
- I recommend that you don't duplicate the changes in PR #14685. This will help you avoid unnecessary merge conflicts in ⁓8+ files. 
   - For example, the changes in the device resource are already in PR #14685. When that PR is merged first, those changes will already be live at the time of addressing merge conflicts in this PR. You'll then end up with (avoidable) merge conflicts in the device file in this PR - and the other ⁓7 files that are also part of PR #14685
   - You can safely revert the changes in those ⁓8 files to remove them from this PR.

2022-01-25 09:05 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +  {
No need to duplicate the changelog from PR #14685 because these changes will be merged through that PR.
```suggestion
```

2022-01-26 00:11 UTC, opbld30 commented
Docs Build status updates of commit _[687ad1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/687ad1ce9568334d0fa34624ada72904f3e36d3d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a4fe6e3d)

<a id="a4fe6e3d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260009578935-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A11%3A09Z&sr=b&sp=r&sig=nwBsfk7K9QeGpH%2BZBo07%2FbWiY%2B4YXAugaSJrALiTxNc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 00:17 UTC, opbld31 commented
Docs Build status updates of commit _[9bfa59e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bfa59e643a02e9bb73968fe198d700abd94d160)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d284a325)

<a id="d284a325"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260017015046-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A17%3A46Z&sr=b&sp=r&sig=nAtiacwrS5P%2BOaVfukmcP8A2qL1RgjtH499WFojzNEo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 00:18 UTC, opbld34 commented
Docs Build status updates of commit _[ed34502](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed3450252b30f9b8acde2a8196c1bf37953bccaf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-eec06b8b)

<a id="eec06b8b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260017576365-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A18%3A37Z&sr=b&sp=r&sig=sc%2FrgoE%2BRYq8eWOUCNcGaIMuueRH74i%2FnZuKFK9PXsQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 00:22 UTC, opbld31 commented
Docs Build status updates of commit _[fc1c2f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc1c2f51389fe6f3ee023b12db78e5cfb15d857b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-273f30ad)

<a id="273f30ad"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260022068718-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A22%3A33Z&sr=b&sp=r&sig=zJPlWO2mdHbtH%2FPxIfdBNc1VBJ5PUzNXL4Puad7LOaI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 00:22 UTC, opbld33 commented
Docs Build status updates of commit _[8f99ac9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f99ac9defdd3728188ef4a13d8132818f43867d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8b5554c3)

<a id="8b5554c3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260022149300-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A22%3A58Z&sr=b&sp=r&sig=UbFcjEtTdrEEBppTIiFpFjTvSm5Z1lZ2aE6FqYzgGTM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 00:25 UTC, opbld32 commented
Docs Build status updates of commit _[543017a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/543017aa18bff76815853fc244415dac67765d1a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-095a1ebd)

<a id="095a1ebd"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260024339156-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A25%3A08Z&sr=b&sp=r&sig=TiKZPOOQZiOAplVKlFAnHpwaUllpt77Z2moUAJl3rD4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 00:32 UTC, opbld34 commented
Docs Build status updates of commit _[dd0bdf8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd0bdf8b01cb08bcf23a60d1b9bfdc6d3ac90a43)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-39be6aea)

<a id="39be6aea"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260031223659-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T00%3A32%3A38Z&sr=b&sp=r&sig=xrM2P88prY5jfsADJ%2FjRq8Pf9EaQFFLq7BBpPUux8fg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 06:23 UTC, opbld33 commented
Docs Build status updates of commit _[f97bd43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f97bd431c2c1e3b3a8257451555673827ccb2898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201260621242256-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T06%3A23%3A26Z&sr=b&sp=r&sig=VGXmRuEBPXIryTksBZnmO5h7OYAF2TTuALYHyy8Bl5g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 09:59 UTC, FaithOmbongi reviewed
Hi @DougKirschner, thank you for addressing the initial feedback. Left minor suggestions to address and the PR will be good to go. 
1. alphabetically reorder the properties in the Properties table
2. create 3 changelist objects for the 3 new properties.

2022-01-27 09:59 UTC, FaithOmbongi commented on api-reference/beta/resources/administrativeunit.md
> +|membershipRuleProcessingState|String|Used to control whether the dynamic membership rule is actively processed. Set to `On` when you want the dynamic membership rule to be active and `Paused` if you
Listing the properties in alphabetical order helps with scanning
```suggestion
| membershipRule | String | Dynamic membership rule for the administrative unit. For more about the rules that you can use for dynamic administrative units and dynamic groups, see [Using attributes to create advanced rules](https://azure.microsoft.com/documentation/articles/active-directory-accessmanagement-groups-with-advanced-rules/). |
| membershipRuleProcessingState | String | Used to control whether the dynamic membership rule is actively processed. Set to `On` when you want the dynamic membership rule to be active and `Paused` if you want to stop updating membership dynamically. If not set, the default behavior is `Paused`. |
| membershipType | String | Membership type for the administrative unit. Can be `dynamic` or `assigned`. If not set, the default behavior is `assigned`. |
| visibility | String | Controls whether the administrative unit and its members are hidden or public. Can be set to `HiddenMembership` or `Public`. If not set, the default behavior is `Public`. When set to `HiddenMembership`, only members of the administrative unit can list other members of the administrative unit. |
```

2022-01-27 09:59 UTC, FaithOmbongi commented on api-reference/beta/api/administrativeunit-update.md
> +|membershipRuleProcessingState|string|Used to control whether the dynamic membership rule is actively processed. Set to `On` when you want the dynamic membership rule to be active and `Paused` if you
Applying an alphabetical order
```suggestion
|description|String|Description for the administrative unit.|
| displayName | String | Display name for the administrative unit. |
| membershipRule | String | Dynamic membership rule for the administrative unit. For more about the rules that you can use for dynamic administrative units and dynamic groups, see [Using attributes to create advanced rules](https://azure.microsoft.com/documentation/articles/active-directory-accessmanagement-groups-with-advanced-rules/).|
| membershipRuleProcessingState | String | Used to control whether the dynamic membership rule is actively processed. Set to `On` when you want the dynamic membership rule to be active and `Paused` if you want to stop updating membership dynamically. |
| membershipType | String | Membership type for the administrative unit. Can be `dynamic` or `assigned`. |
| visibility | String | Visibility for the administrative unit. If not set, then the default is `public`. Can be set to `HiddenMembership`, which hides the membership from non-members. |
```

2022-01-27 09:59 UTC, FaithOmbongi commented on api-reference/beta/api/administrativeunit-post-administrativeunits.md
> +|membershipRuleProcessingState|String|Used to control whether the dynamic membership rule is actively processed. Set to `On` when you want the dynamic membership rule to be active and `Paused` if you
```suggestion
| description | String | Description for the administrative unit. Optional. |
| displayName | String | Display name for the administrative unit. Required. |
| membershipRule | String | Dynamic membership rule for the administrative unit. For more about the rules that you can use for dynamic administrative units and dynamic groups, see [Using attributes to create advanced rules](https://azure.microsoft.com/documentation/articles/active-directory-accessmanagement-groups-with-advanced-rules/). Optional. |
| membershipRuleProcessingState | String | Used to control whether the dynamic membership rule is actively processed. Set to `On` when you want the dynamic membership rule to be active and `Paused` if you want to stop updating membership dynamically. Optional. |
| membershipType | String | Membership type for the administrative unit. Can be `dynamic` or `assigned`. Optional. |
| visibility |String | Visibility for the administrative unit. If not set, then the default is `public`. Can be set to `HiddenMembership`, which hides the membership from non-members. Optional. |
```

2022-01-27 09:59 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
Replace this with 3 changelist objects for adding the properties. See [Example 2 in the changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog).

2022-01-27 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[6629fd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6629fd75575cbafa7d14b590c10c07cc2bd86098)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201271910080892-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T19%3A13%3A23Z&sr=b&sp=r&sig=HvzZlvzvX%2F8ygpwbHilllhtBbaw7aXNWcsPF8rLqbZM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 19:25 UTC, opbld31 commented
Docs Build status updates of commit _[cdc37da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cdc37da877be9d15e9f4a346a50408b2bb47cf4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201271921326609-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T19%3A25%3A06Z&sr=b&sp=r&sig=OFutyS%2FSsuwcfF%2F05roNosPcYxr7oDxP9LDXwtl6WKc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 19:25 UTC, DougKirschner commented
@FaithOmbongi - updated per feedback.  Let's keep the do not merge until we are ready to roll out fully

2022-03-21 22:03 UTC, DougKirschner commented
Hi @FaithOmbongi we are ready to publish these updates at last, but I see there are some new conflicts.  I'm not able to resolve as GitHub is saying I don't have write access (even though I created the PR).  Are you able to resolve?

2022-03-23 06:58 UTC, opbld33 commented
Docs Build status updates of commit _[512f9bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/512f9bfe3f57dfdb15a2ec84afe929843a90f8b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-1207d7ef)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="587d07eace2c4d640a05d29494f64382-1207d7ef"></a>
### [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-post-members.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203230656069161-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T06%3A58%3A26Z&sr=b&sp=r&sig=2OhnL8az4WeZ%2Fmyrx9bBMWIAamV9zVS%2FuGlMDlgYEBk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 07:12 UTC, opbld30 commented
Docs Build status updates of commit _[57f94e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57f94e600575ea81a2081db355f25a03ee15565b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-15605) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-dynamicau/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203230710284814-15605%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T07%3A12%3A34Z&sr=b&sp=r&sig=iwgr4z3dd5XCglmBFcrKg%2B3Nx8%2BfY%2BHgaO7cSvVrqHM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 07:19 UTC, FaithOmbongi commented
> Hi @FaithOmbongi we are ready to publish these updates at last, but I see there are some new conflicts. I'm not able to resolve as GitHub is saying I don't have write access (even though I created the PR). Are you able to resolve?

Hi @DougKirschner, looks like you lost some memberships, specifically to the [Microsoft org](https://repos.opensource.microsoft.com/orgs/microsoft/people?q=DougKirschner) and [microsoft-graph-contributors](https://repos.opensource.microsoft.com/orgs/microsoftgraph/teams/graph-docs-contributors) team - don't know how. Can you retrace the steps in [Get started checklist](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started-with-GitHub?anchor=get-started-steps) to confirm/set up your membership in all the required orgs/teams? Thanks.

Otherwise, I think I resolved the conflicts (after a little mishap).

2022-03-23 07:20 UTC, FaithOmbongi approved these changes

2022-06-22 21:49 UTC, DougKirschner commented
Thanks, this content is external now and ready to be released.

2022-06-23 03:05 UTC, merged