Add the deprecation notice in all AR v1 docs
microsoftgraph/microsoft-graph-docs pull request #15630
Opened 2022-01-25 18:37 UTC by FaithOmbongi

2022-01-25 18:40 UTC, opbld30 commented
Docs Build status updates of commit _[b248eb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b248eb4003a7ffc0cd594dd5815ff19e0f1652ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreview-addreviewer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-addreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-addreviewer?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-create?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-delete?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-get?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-listdecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-listdecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-listdecisions?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-listmydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-listmydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-listmydecisions?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-listreviewers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-listreviewers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-listreviewers?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-removereviewer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-removereviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-removereviewer?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-reset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-reset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-reset?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-sendreminder?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-stop?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-update?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/approval-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/approval-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-get?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/businessflowtemplate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/businessflowtemplate-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/businessflowtemplate-list?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-create?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-delete?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-list?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-listcontrols.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-listcontrols.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-listcontrols?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-update?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/programcontrol-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/programcontrol-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/programcontrol-create?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/programcontrol-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ [...]

2022-01-25 23:01 UTC, isabelleatmsft commented on api-reference/beta/api/approval-get.md
> +[!INCLUDE [accessreviews-disclaimer](../../includes/accessreviews-disclaimer.md)]
```suggestion
```

2022-01-25 23:01 UTC, isabelleatmsft commented on api-reference/beta/api/approval-get.md
> +[!INCLUDE [accessreviews-disclaimer](../../includes/accessreviews-disclaimer.md)]
@FaithOmbongi this looks like an ELM doc, not access reviews. LMK if you disagree

2022-01-25 23:04 UTC, isabelleatmsft requested changes

2022-01-25 23:04 UTC, isabelleatmsft commented on api-reference/beta/api/approval-get.md
> +[!INCLUDE [accessreviews-disclaimer](../../includes/accessreviews-disclaimer.md)]
@FaithOmbongi Looks like this is ELM docs, not AR. LMK if you disagree

2022-01-26 03:45 UTC, Lauragra commented
@FaithOmbongi , it looks like Isabelle left some comments after you set Ready to merge. Please verify that we're ready to merge this PR? Thanks.

2022-01-26 07:20 UTC, FaithOmbongi commented on api-reference/beta/api/approval-get.md
> +[!INCLUDE [accessreviews-disclaimer](../../includes/accessreviews-disclaimer.md)]
Good catch, Isabelle. Yes, you're right. Pushing a commit to resolve this.

2022-01-26 07:23 UTC, FaithOmbongi commented
Hi, @Lauragra—Isabelle's feedback was right. I've addressed it.

2022-01-26 07:24 UTC, opbld34 commented
Docs Build status updates of commit _[eac1606](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eac16066161ac6807f9734cc37337ca3c9dfb983)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreview-addreviewer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-addreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-addreviewer?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-create?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-delete?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-get?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-listdecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-listdecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-listdecisions?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-listmydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-listmydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-listmydecisions?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-listreviewers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-listreviewers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-listreviewers?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-removereviewer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-removereviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-removereviewer?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-reset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-reset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-reset?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-sendreminder?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-stop?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/accessreview-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/accessreview-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-update?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/businessflowtemplate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/businessflowtemplate-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/businessflowtemplate-list?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-create?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-delete?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-list?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-listcontrols.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-listcontrols.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-listcontrols?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/program-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/program-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/program-update?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/programcontrol-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/programcontrol-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/programcontrol-create?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/programcontrol-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARv1Deprecation/api-reference/beta/api/programcontrol-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/programcontrol-delete?view=graph-rest-beta&branch=pr-en-us-15630) (graph-rest-beta) |
[api-reference/beta/api/programcontrol-list.md](https://github.com/microsoftgraph/m [...]

2022-01-26 19:12 UTC, isabelleatmsft approved these changes

2022-01-27 04:12 UTC, merged