Patch 9
microsoftgraph/microsoft-graph-docs pull request #15649
Opened 2022-01-26 15:33 UTC by Justinha

Adding errorStatus and description to provisioningStatus property of servicePlanInfo

2022-01-26 15:35 UTC, opbld30 commented
Docs Build status updates of commit _[821b30b](https://github.com/Justinha/microsoft-graph-docs/commits/821b30b667f3c2753732fbc16a6a4365e585384c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/beta/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-beta&branch=pr-en-us-15649) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/v1.0/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-1.0&branch=pr-en-us-15649) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261533299280-15649%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T15%3A35%3A49Z&sr=b&sp=r&sig=ekkBWQWg9%2BT7%2BvsIWbJWm8feXKkOtnilM%2F3%2BUdcm91k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 16:01 UTC, Justinha commented
#sign-off

2022-01-27 21:05 UTC, FaithOmbongi requested changes
Thank you @Justinha for your work on this PR. Left suggestions for minor fixes.

2022-01-27 21:05 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    },
Please move your changelog record to the top of the file, at line 3. It will also help others get "cleaner" merge conflicts.

2022-01-27 21:05 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "provisioningStatus"
Proposed change because your changes affect the property, not the resource.
```suggestion
          "Id": "0f3be1ec-d352-4eb8-ad76-c8e1e1a615eb",
          "ApiChange": "Property",
          "ChangedApiName": "provisioningStatus",
          "ChangeType": "Addition",
          "Description": "Added **ErrorStatus** to the list of possible values for the **provisioningStatus** property of the [servicePlanInfo](https://docs.microsoft.com/graph/api/resources/serviceplaninfo?view=graph-rest-1.0) resource.",
          "Target": "provisioningStatus"
```

2022-01-27 21:05 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "provisioningStatus"
```suggestion
          "Id": "0f3be1ec-d352-4eb8-ad76-c8e1e1a615eb",
          "ApiChange": "Property",
          "ChangedApiName": "provisioningStatus",
          "ChangeType": "Addition",
          "Description": "Added **ErrorStatus** to the list of possible values for the **provisioningStatus** property of the [servicePlanInfo resource type](https://docs.microsoft.com/graph/api/resources/serviceplaninfo?view=graph-rest-beta) resource.",
          "Target": "provisioningStatus"
```

2022-01-31 19:41 UTC, opbld34 commented
Docs Build status updates of commit _[5c283f2](https://github.com/Justinha/microsoft-graph-docs/commits/5c283f2d1e5f87e15d9f763b798292abab97bf82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/beta/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-beta&branch=pr-en-us-15649) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/v1.0/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-1.0&branch=pr-en-us-15649) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201311937297826-15649%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-03T19%3A41%3A24Z&sr=b&sp=r&sig=jH1O%2FRqQg5DsiGUz8uvMoGdSqhLUSrUayCWFCSdq%2Bf4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-31 19:43 UTC, opbld33 commented
Docs Build status updates of commit _[f876887](https://github.com/Justinha/microsoft-graph-docs/commits/f87688728dfbf2a1b0e41b19477a05b5bcfcc462)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/beta/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-beta&branch=pr-en-us-15649) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/v1.0/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-1.0&branch=pr-en-us-15649) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201311937360842-15649%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-03T19%3A43%3A29Z&sr=b&sp=r&sig=Gm57Ud5YnHwrby8PY%2FOh41RJEcFuz8sQ1w0b9IloTs0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-31 20:22 UTC, Justinha commented
#feedback-addressed

2022-02-01 06:46 UTC, FaithOmbongi approved these changes

2022-02-01 06:51 UTC, opbld31 commented
Docs Build status updates of commit _[80063c2](https://github.com/Justinha/microsoft-graph-docs/commits/80063c28b38c56d1b6d6a84346e99349834184f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/beta/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-beta&branch=pr-en-us-15649) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/v1.0/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-1.0&branch=pr-en-us-15649) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202010643358707-15649%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T06%3A51%3A12Z&sr=b&sp=r&sig=sJiOcAdk4zlqJRB%2BLuArH1ij2Zlcz9Y9kf%2BejYWJenk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 06:53 UTC, opbld33 commented
Docs Build status updates of commit _[d3836ab](https://github.com/Justinha/microsoft-graph-docs/commits/d3836abba6da514635cc761dbaf241812ad97230)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/beta/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-beta&branch=pr-en-us-15649) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/v1.0/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-1.0&branch=pr-en-us-15649) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202010645037188-15649%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T06%3A53%3A40Z&sr=b&sp=r&sig=UfrGBXjwidjN6gOR33zwcomYGExAQysLZxU41Dmb1dY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 03:00 UTC, opbld33 commented
Docs Build status updates of commit _[1806985](https://github.com/Justinha/microsoft-graph-docs/commits/1806985a705dbd72c67d3a25b556f74ac2e864bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/beta/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-beta&branch=pr-en-us-15649) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceplaninfo.md](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/api-reference/v1.0/resources/serviceplaninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceplaninfo?view=graph-rest-1.0&branch=pr-en-us-15649) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/Justinha/microsoft-graph-docs/blob/patch-9/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202020258154286-15649%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T03%3A00%3A34Z&sr=b&sp=r&sig=kAk1s9RGjzwfrYoVHITgEyDzqyglvtWhaf6%2Bcp%2FCCTI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 03:02 UTC, merged