Moving accessReviewHistoryDefinition to v1.0
microsoftgraph/microsoft-graph-docs pull request #15653
Opened 2022-01-26 19:37 UTC by leherpel

Moving accessReviewHistoryDefinition docs to v1.0

2022-01-26 19:39 UTC, opbld34 commented
Docs Build status updates of commit _[31bf171](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31bf171707d0eb8d74728697d7025685fc856681)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :x:Error | | [Details](#user-content-2f09786af2b98accaf18ad2155a131d0-e53e37ec)
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :x:Error | | [Details](#user-content-bc292ceb016f59ddcf1a63a4a0edb95f-e53e37ec)
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :x:Error | | [Details](#user-content-63082ab41ab7afd86356b29ec7d3c75b-e53e37ec)
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :warning:Warning | | [Details](#user-content-e66bac73712cefb68838e7a80d84cdba-e53e37ec)

<a id="2f09786af2b98accaf18ad2155a131d0-e53e37ec"></a>
### [api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md)
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-accessreviewhistorydefinition-csharp-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-accessreviewhistorydefinition-javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-accessreviewhistorydefinition-objc-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-accessreviewhistorydefinition-java-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-accessreviewhistorydefinition-go-snippets.md'.`````

<a id="bc292ceb016f59ddcf1a63a4a0edb95f-e53e37ec"></a>
### [api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md)
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-accessreviewhistorydefinition-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-accessreviewhistorydefinition-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-accessreviewhistorydefinition-objc-snippets.md'.`````
 - **Line 90, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-accessreviewhistorydefinition-java-snippets.md'.`````
 - **Line 94, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-accessreviewhistorydefinition-go-snippets.md'.`````

<a id="63082ab41ab7afd86356b29ec7d3c75b-e53e37ec"></a>
### [api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md)
 - **Line 140, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-accessreviewhistorydefinition-from--csharp-snippets.md'.`````
 - **Line 144, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-accessreviewhistorydefinition-from--javascript-snippets.md'.`````
 - **Line 148, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-accessreviewhistorydefinition-from--objc-snippets.md'.`````
 - **Line 152, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-accessreviewhistorydefinition-from--java-snippets.md'.`````
 - **Line 156, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-accessreviewhistorydefinition-from--go-snippets.md'.`````

<a id="e66bac73712cefb68838e7a80d84cdba-e53e37ec"></a>
### [api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List instances - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/accessreviewhistorydefinition-list-instances.md(2,8), v1.0/api/accessreviewscheduledefinition-list-instances.md(2,8), v1.0/api/event-list-instances.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List instances' is duplicated with other articles: 'v1.0/api/accessreviewhistorydefinition-list-instances.md(10,1), v1.0/api/accessreviewscheduledefinition-list-instances.md(10,1), v1.0/api/event-list-instances.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261937360455-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T19%3A39%3A42Z&sr=b&sp=r&sig=6wHzfp8irDqw%2BD9e1BhmYk4ZChMnebPnxxGvLxPEh28%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7 [...]

2022-01-26 19:50 UTC, opbld31 commented
Docs Build status updates of commit _[868c79d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/868c79d84a9de70ed1fc292c4e231c1e5fd2ebc5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) | [Details](#user-content-e66bac73712cefb68838e7a80d84cdba-3a426a69)
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="e66bac73712cefb68838e7a80d84cdba-3a426a69"></a>
### [api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List instances' is duplicated with other articles: 'v1.0/api/accessreviewhistorydefinition-list-instances.md(10,1), v1.0/api/accessreviewscheduledefinition-list-instances.md(10,1), v1.0/api/event-list-instances.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261948282581-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T19%3A50%3A32Z&sr=b&sp=r&sig=Oiw7TZEK25BB2oxOflWXbAJYPCSGzFMeDL62BivUx%2BQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 19:57 UTC, opbld31 commented
Docs Build status updates of commit _[51f4608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51f460864dede2913494ae7a671014eb365fd7f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) | [Details](#user-content-e66bac73712cefb68838e7a80d84cdba-54a32795)
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="e66bac73712cefb68838e7a80d84cdba-54a32795"></a>
### [api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List instances' is duplicated with other articles: 'v1.0/api/accessreviewhistorydefinition-list-instances.md(10,1), v1.0/api/accessreviewscheduledefinition-list-instances.md(10,1), v1.0/api/event-list-instances.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261954408922-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T19%3A57%3A14Z&sr=b&sp=r&sig=QP2YqZjQq9ibIhmoVUA5cwNUvlOCiKiBlVGkYvc5MVE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 09:48 UTC, FaithOmbongi requested changes
Thank you @leherpel for your work on this PR. I've proposed some minor changes including the following.
- Please add the historyDefinitions relationship to accessReviewSet.
- Please add all the new enums to the enums.md file

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewhistorydefinition.md
> +|status|String collection|Represents the status of the review history data collection. The possible values are: `done`, `inProgress`, `error`, `requested`, `unknownFutureValue`.|
```suggestion
|status| [accessReviewHistoryStatus](accessreviewhistorystatus.md) |Represents the status of the review history data collection. The possible values are: `done`, `inProgress`, `error`, `requested`, `unknownFutureValue`.|
```

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewhistoryinstance.md
> +|status|String collection|Represents the status of the review history data collection. The possible values are: `done`, `inProgress`, `error`, `requested`, `unknownFutureValue`. Once the **status** h
```suggestion
|status|accessReviewHistoryStatus|Represents the status of the review history data collection. The possible values are: `done`, `inProgress`, `error`, `requested`, `unknownFutureValue`. Once the **status** has been marked as `done`, a link can be generated to retrieve the instance's data by calling [generateDownloadUri](../api/accessreviewhistoryinstance-generatedownloaduri.md) method.|
```

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewhistorydefinition-get.md
> +Retrieve an [accessReviewHistoryDefinition](../resources/accessreviewhistorydefinition.md) object by its identifier. All of the properties of the access review history definition object are returned.
minor formatting change
```suggestion
Retrieve an [accessReviewHistoryDefinition](../resources/accessreviewhistorydefinition.md) object by its identifier. All of the properties of the access review history definition object are returned. If the definition is 30 days or older, a `404 Not Found` error is returned.
```

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md
> +title: "List access review history definition instances"
Might help differentiate this from the instances r/ship of the accessReviewScheduleDefinition while still applying the guidance
```suggestion
title: "List instances (of an accessReviewHistoryDefinition)"
```

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md
> +# List instances
```suggestion
# List instances (of an accessReviewHistoryDefinition)
```

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md
> +            "status": "Done",
Could you verify that this status is Pascal-cased (Done, InProgress) and not small case (done, inprogress) as defined in the schema? Also, please verify if this is case insensitive. We've had a couple of issues with case-sensitive enum members in Governance APIs where what the API accepts/returns is a different case from what's defined in the schema and it's better to add a note in the docs where applicable.


FY that the other examples show small case `done` as per the schema.

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewhistorydefinition-list-instances.md
> +title: "List accessReviewHistoryInstances"
As per the title guidance but recommending that you remove this file from this PR. I'm raising a fix for this through my fixes PR.
```suggestion
title: "List instances (of an accessReviewHistoryDefinition)"
```

2022-02-07 09:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewsv2-overview.md
> +|[List historyInstances](../api/accessreviewhistorydefinition-list-instances.md)|[accessReviewHistoryInstance](accessreviewhistoryinstance.md)|Retrieve a list of the [accessReviewHistoryInstance](acc
```suggestion
|[List instances](../api/accessreviewhistorydefinition-list-instances.md)|[accessReviewHistoryInstance](accessreviewhistoryinstance.md)|Retrieve a list of the [accessReviewHistoryInstance](accessreviewhistoryinstance.md) objects and their properties.|
```

2022-02-07 09:48 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +      "SubArea": ""
I understand from the onboarding team that this misrepresentation of WorkloadArea and SubArea is because you haven't defined the correct values in the workload-mapping.json file. Please fix the file so this resolves in future changelogs.
```suggestion
      "WorkloadArea": "Identity and access",
      "SubArea": "Governance"
```

2022-02-07 09:48 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [accessReviewHistoryScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryScheduleSettings?view=graph-rest-1.0) resource type."
Recommending enhancing the descriptions for added context for the customer.
```suggestion
          "Description": "Added the [accessReviewHistoryScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryScheduleSettings?view=graph-rest-1.0) resource type. Use this resource to configure the settings of an [accessReviewHistoryDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0) object.",
```

2022-02-07 09:48 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [accessReviewHistoryDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryDefinition?view=graph-rest-1.0) resource",
```suggestion
          "Description": "Added the [accessReviewHistoryDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryDefinition?view=graph-rest-1.0) resource and related methods. Represents a collection of access review historical data and the scopes used to collect that data.",
```

2022-02-07 09:48 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [accessReviewHistoryInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryInstance?view=graph-rest-1.0) resource",
```suggestion
          "Description": "Added the [accessReviewHistoryInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewHistoryInstance?view=graph-rest-1.0) resource and related methods. Represents the instances of a recurring access review history definition.",
```

2022-02-23 01:41 UTC, opbld33 commented
Docs Build status updates of commit _[9c9f5e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c9f5e8442a9becc5d65ab00a127a2363a2198da)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c1f84757)

<a id="c1f84757"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230141068323-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A41%3A42Z&sr=b&sp=r&sig=GZt21uD4UmrHnBZmpp%2Bzvwy5SotQIywk6ztYOtwIvEI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 01:42 UTC, opbld33 commented
Docs Build status updates of commit _[8272e7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8272e7f7e75e49634ac57593e5644225481df679)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-25461ec3)

<a id="25461ec3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230141143331-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A42%3A47Z&sr=b&sp=r&sig=FiH6k23lil08Eiq5btn177dYGVlPhJkpA1OTpuuLA%2B8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 01:43 UTC, opbld31 commented
Docs Build status updates of commit _[33d78e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33d78e943f7d776cdacf15f8140afa98803414f8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1612e06c)

<a id="1612e06c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230143092703-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A43%3A43Z&sr=b&sp=r&sig=Rj1QOzvh823zzM29WZMelGOvJlSATLw7MIMS7L0Sg9M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 01:45 UTC, opbld33 commented
Docs Build status updates of commit _[3ec0a53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ec0a53df3346caabb99e07186b8966ca9ea7f51)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-38e6737c)

<a id="38e6737c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230143391255-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A45%3A40Z&sr=b&sp=r&sig=s%2Fxt7ZrA2yh2weIRDzeH61ju0e1n5lY7lvqC98OrTag%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 01:46 UTC, opbld32 commented
Docs Build status updates of commit _[b35a3f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b35a3f3052fb78a68d7f8b35b4af13ac8ddd1a6a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f61b184f)

<a id="f61b184f"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230143525480-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A46%3A18Z&sr=b&sp=r&sig=5FY%2BNzLvJ3jEVuc%2BmaUotKvD7r55akuWUhZiOBzYYhE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 01:47 UTC, opbld32 commented
Docs Build status updates of commit _[8608e94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8608e947deb992673dfedf94810a4cfe1e397c02)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b494f86c)

<a id="b494f86c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230146016793-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A46%3A59Z&sr=b&sp=r&sig=9pPRyh5y1xFJqYBk2GncCEUUfgqWW1eZ5TOyVj3gxEY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 01:50 UTC, opbld33 commented
Docs Build status updates of commit _[164a670](https://github.com/microsoftgraph/microsoft-graph-docs/commits/164a670a74225278a00a73f2df44aa869f891c2a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4bb7eace)

<a id="4bb7eace"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230148302655-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T01%3A50%3A07Z&sr=b&sp=r&sig=xDuAdV0rY5MsfWRlHQQ0yrSaL6621%2BkPIgiQzlpjVkc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 02:21 UTC, leherpel commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +      "SubArea": ""
Here is the PR to fix the mapping json file: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5737975

2022-02-23 02:22 UTC, opbld33 commented
Docs Build status updates of commit _[efb80d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efb80d1d914c0be2e08c5e706fef655f648c8161)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b832e045)

<a id="b832e045"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230222004490-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T02%3A22%3A34Z&sr=b&sp=r&sig=oH1jOs5ODKUsYG9BUlkLE6aWcBNJ3J%2ByoJ%2BwXI6g7TU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 02:41 UTC, opbld32 commented
Docs Build status updates of commit _[12c2865](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12c2865e3ebe1d501c16b43abc9e16c76ee71b30)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-266abf2d)

<a id="266abf2d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230240435242-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T02%3A41%3A23Z&sr=b&sp=r&sig=zppFsraBzIsoU5z5rF26V02Iluf%2BoH4GFlLgRegNnAE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 02:44 UTC, opbld31 commented
Docs Build status updates of commit _[e86a199](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e86a199b3e2105ca2fee05c8683dfa2d060eb262)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) | [Details](#user-content-5e077cb68bb112229f833cbf0e4c8c82-00e6b498)
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewset?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5e077cb68bb112229f833cbf0e4c8c82-00e6b498"></a>
### [api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md)
 - **Line 39, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorystatus.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230242557512-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T02%3A44%3A53Z&sr=b&sp=r&sig=9mLfkUqFMI%2Fsxqdvk32rKtgUoMIoseGjr9E3ySq%2Fa6M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-o [...]

2022-02-23 02:48 UTC, opbld30 commented
Docs Build status updates of commit _[649f220](https://github.com/microsoftgraph/microsoft-graph-docs/commits/649f22046c3ca62ee7201a20c3f56e83dd751e58)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) | [Details](#user-content-5e077cb68bb112229f833cbf0e4c8c82-e0fe79d2)
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewset?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5e077cb68bb112229f833cbf0e4c8c82-e0fe79d2"></a>
### [api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md)
 - **Line 39, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorystatus.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230246139949-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T02%3A48%3A27Z&sr=b&sp=r&sig=i3IurMG8v4spOY%2F3p3FBfidstPHiAaJM8OBT5xO4z5o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or- [...]

2022-02-23 02:50 UTC, opbld33 commented
Docs Build status updates of commit _[b8c9142](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8c91429ffd81a8de42e67558c0fc00202476fdc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) | [Details](#user-content-5e077cb68bb112229f833cbf0e4c8c82-036cb7d1)
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewset?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5e077cb68bb112229f833cbf0e4c8c82-036cb7d1"></a>
### [api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md)
 - **Line 39, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorystatus.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230248235931-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T02%3A50%3A29Z&sr=b&sp=r&sig=7%2F%2FHPdpb09fD5lcLdK6qSMI4typWZ4oI0YBvz%2Bo1jo0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error [...]

2022-02-23 02:57 UTC, opbld32 commented
Docs Build status updates of commit _[1741c0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1741c0d15d1606987a0e430567e93a7c64748b25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewset?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202230255419446-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T02%3A57%3A34Z&sr=b&sp=r&sig=UOa9zjTNUMLe1WsClsSq%2Fec2EffuwQrC8EnC%2F66QgQY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 21:15 UTC, opbld34 commented
Docs Build status updates of commit _[7b0eef5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b0eef5137061fae750db6bf212da99050770621)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15653) (graph-rest-beta) |
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistorydefinition-list-instances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list-instances?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewhistoryinstance-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistoryinstance-generatedownloaduri?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-list-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-historydefinitions?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryinstance?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistoryschedulesettings?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewset?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/accessreviewsv2-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-15653) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/leherpel/accessreviewhistory-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202242113048116-15653%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T21%3A15%3A03Z&sr=b&sp=r&sig=6KbVNJGYKswvGF1zOs5lUdiZUepQJdKkWmD1cJj%2B3D4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 21:28 UTC, FaithOmbongi approved these changes
Thank you @leherpel for the awesome work you've done on this PR. Approved.

2022-02-26 06:19 UTC, merged