App policy custom password block
microsoftgraph/microsoft-graph-docs pull request #15650
Opened 2022-01-26 16:25 UTC by madansr7

2022-01-26 23:29 UTC, opbld30 commented
Docs Build status updates of commit _[66714a8](https://github.com/madansr7/microsoft-graph-docs/commits/66714a832372f2b65b346c0971d0b45f1a7656af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262327522664-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T23%3A29%3A56Z&sr=b&sp=r&sig=56UvrtAG3BaGQaWNIbxdpWs5f75ui179w0KrhExsXbA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 10:32 UTC, FaithOmbongi requested changes
Thank you @madansr7 for your work on this PR. I see you're introducing a new restriction (an enum member) **customPasswordAddition** to the **appCredentialRestrictionType** enum?
- Please update the [parent resource type doc](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) and add the new enum member to the list for restrictionType.
- In the enums.md file, update the appCredentialRestrictionType table, adding the new member after unknownFutureValue
- You'll also need a changelog entry. Feel free to enhance the changelog description by sharing a single sentence describing the purpose of this new value.

2022-01-27 10:32 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationauthenticationmethodpolicy.md
> +| customPasswordAddition | Restrict a custom password secret on application or service principal. | Restrict all new custom password secrets on applications created after 01/01/2015.
Not getting the difference between **customPaswordAddition** and **passwordAddition**.

2022-01-27 10:32 UTC, FaithOmbongi commented on api-reference/beta/api/tenantappmanagementpolicy-update.md
> +| servicePrincipalRestrictions | [appManagementConfiguration](../resources/appManagementConfiguration.md) | Restrictions that apply as default to all service principal objects in the tenant.
Just ordering the properties in alphabetical order for ease of scanning
```suggestion
| applicationRestrictions      | [appManagementConfiguration](../resources/appManagementConfiguration.md) | Restrictions that apply as default to all application objects in the tenant.                     |
| displayName                  | String                                                                   | The display name of the default policy. Inherited from [policyBase](../resources/policybase.md). |
| description                  | String                                                                   | The description of the default policy. Inherited from [policyBase](../resources/policybase.md).  |
| isEnabled                    | Boolean                                                                  | Denotes if the policy is enabled. Default value is false.                                        |
| servicePrincipalRestrictions | [appManagementConfiguration](../resources/appManagementConfiguration.md) | Restrictions that apply as default to all service principal objects in the tenant.               |
```

2022-01-27 10:32 UTC, FaithOmbongi commented on api-reference/beta/resources/passwordcredentialconfiguration.md
> +| restrictForAppsCreatedAfterDateTime | DateTimeOffset               | Enforces the policy for an app created on or after the enforcement date. For existing applications, the enforcement date would b
I don't think the new member would be added before the sentinel unknownFutureValue property. According to the enums guidance, new members are always added after the last value to avoid breaking changes.
Also, if you check the generated stubs, you should see the note about the required header
```suggestion
| restrictionType                     | appCredentialRestrictionType | The type of restriction being applied. The possible values are: `passwordAddition`, `passwordLifetime`, `symmetricKeyAddition`, `symmetricKeyLifetime`, `unknownFutureValue`, `customPasswordAddition`.  Note that you must use the `Prefer: include-unknown-enum-members` request header to get the following value(s) in this [evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations): `customPasswordAddition`. Each value of restrictionType can be used only once per policy.                                                                                        |
| maxLifeTime                         | Duration                     | Value that can be used as the maximum number for setting password expiration time in days, hours, minutes or seconds. Defined in ISO 8601 format for Durations. For example, "P4DT12H30M5S" represents a duration of four days, twelve hours, thirty minutes, and five seconds. This property is required when restriction type is set to `passwordLifetime`. |
| restrictForAppsCreatedAfterDateTime | DateTimeOffset               | Enforces the policy for an app created on or after the enforcement date. For existing applications, the enforcement date would be back-dated. To apply to all applications, this date would be `null`.                                                                                                                                               |
```

2022-01-27 20:25 UTC, opbld34 commented
Docs Build status updates of commit _[8e46333](https://github.com/madansr7/microsoft-graph-docs/commits/8e46333fe86c25a0a5fd3277e8515ff738ebcbf5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272023098846-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T20%3A25%3A12Z&sr=b&sp=r&sig=LRC%2BNv3yb4PIMZipQVYy41MZ0Uwd9dK8mt4mQR7iqDE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 20:55 UTC, madansr7 commented on api-reference/beta/resources/applicationauthenticationmethodpolicy.md
> +| customPasswordAddition | Restrict a custom password secret on application or service principal. | Restrict all new custom password secrets on applications created after 01/01/2015.
The parent doc is already updated with the enum member list. I updated the text to add clarity on what custom means. Will add change log as soon as the engineering PR is ready.

2022-01-27 20:58 UTC, madansr7 commented on api-reference/beta/resources/passwordcredentialconfiguration.md
> +| restrictForAppsCreatedAfterDateTime | DateTimeOffset               | Enforces the policy for an app created on or after the enforcement date. For existing applications, the enforcement date would b
That's not correct. The API review doc has it differently. 
Long term we should come up with an indicator for evolvable enums such that we don't keep adding a blurb of text in our docs. Something for API review and Graph team to think about.

2022-01-27 20:59 UTC, opbld34 commented
Docs Build status updates of commit _[733d6fb](https://github.com/madansr7/microsoft-graph-docs/commits/733d6fb7b38da2a7f86d367f7415514a58fe4f2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272056535816-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T20%3A59%3A10Z&sr=b&sp=r&sig=B9EU2lYr0UFXCvRm%2BWfCd5B31e%2BrulXahp0FGKv%2B0A4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 21:01 UTC, opbld32 commented
Docs Build status updates of commit _[e6abbc5](https://github.com/madansr7/microsoft-graph-docs/commits/e6abbc59c64e768e67379dde89988300de5587f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272059288407-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T21%3A01%3A35Z&sr=b&sp=r&sig=4PsUvnVsjPrEWARHRBQbbWZBb5y1Uk5wlcVyP%2FV0HfA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:33 UTC, opbld30 commented
Docs Build status updates of commit _[f6df5fe](https://github.com/madansr7/microsoft-graph-docs/commits/f6df5fef644ddaffd9c41444dc05373fdceac395)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272331083751-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T23%3A33%3A12Z&sr=b&sp=r&sig=GQ2kjPIBBTdeS7HhPDZiGEXdZuiDNn0rNARnx7UOpHk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:35 UTC, opbld30 commented
Docs Build status updates of commit _[172a695](https://github.com/madansr7/microsoft-graph-docs/commits/172a69511216f8e23122b310c59f8e9af89bbb3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272333036048-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T23%3A35%3A28Z&sr=b&sp=r&sig=1Fj5FiKW8IIuouu1Dwimm63DZJO3VvYEaU3%2B8RGv9SU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 23:41 UTC, opbld33 commented
Docs Build status updates of commit _[861fa2b](https://github.com/madansr7/microsoft-graph-docs/commits/861fa2bbc07a7e99569e2e9c05024c9829ad0dab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201272338553499-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-27T23%3A40%3A59Z&sr=b&sp=r&sig=lIt4xuH4HGozQYkINokBAb1DtNt1I8XBaFsre59M8aY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-01 12:42 UTC, FaithOmbongi requested changes
Hi @madansr7, based on the confirmation, left a few change suggestions before approval.

2022-02-01 12:42 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationauthenticationmethodpolicy.md
> +> Applying customPasswordAddition restriction will block any legacy PowerShell modules that add a client generated password secret on to applications or service principals. This restriction does not
```suggestion
> Applying the **customPasswordAddition** restriction will block any legacy PowerShell modules that add a client-generated password secret to applications or service principals. This restriction does not block Azure AD-generated application or service principal password secrets.
```

2022-02-01 12:42 UTC, FaithOmbongi commented on api-reference/beta/resources/passwordcredentialconfiguration.md
> +| restrictForAppsCreatedAfterDateTime | DateTimeOffset               | Enforces the policy for an app created on or after the enforcement date. For existing applications, the enforcement date would b
```suggestion
| restrictForAppsCreatedAfterDateTime | DateTimeOffset               | Enforces the policy for an app created on or after the enforcement date. For existing applications, the enforcement date would be backdated. To apply to all applications, this date would be `null`.                                                                                                                                               |
```

2022-02-01 12:42 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationauthenticationmethodpolicy.md
> +| customPasswordAddition | Restrict a custom password secret on application or service principal. | Restrict all new custom (non Azure AD generated) password secrets on applications created after 01/
```suggestion
| customPasswordAddition | Restrict a custom password secret on application or service principal. | Restrict all new custom (non-Azure AD generated) password secrets on applications created after 01/01/2015. |
```

2022-02-01 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [customPasswordAddition](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta) enum to passwordCredentialConfi
Seems there's a bug in the tooling. The description generated wasn't completely accurate.
```suggestion
          "Description": "Added the `customPasswordAddition` member to the **appCredentialRestrictionType** enumeration. Use this new restriction for the [application authentication methods policy](https://docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta) to restrict all new custom (non-Azure AD generated) password secrets on applications created after 01/01/2015.",
```

2022-02-02 19:34 UTC, madansr7 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [customPasswordAddition](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta) enum to passwordCredentialConfi
@FaithOmbongi , with the date in the description a user might form an opinion that we are restricting creds on apps created after 2015. I think we should remove the date.

2022-02-02 19:37 UTC, opbld33 commented
Docs Build status updates of commit _[a987bbc](https://github.com/madansr7/microsoft-graph-docs/commits/a987bbcddc1d93d97ae4a7d873fa1e87b24ddfb5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202021935106064-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T19%3A37%3A32Z&sr=b&sp=r&sig=JeAqObDMyyMUuCE%2BrUGni%2Bsi2VsGTZEW%2BateXm5Q42g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 19:40 UTC, opbld34 commented
Docs Build status updates of commit _[977e0b8](https://github.com/madansr7/microsoft-graph-docs/commits/977e0b85b48b489c2cc51abf372e8e066fb7eda4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202021935325681-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T19%3A40%3A10Z&sr=b&sp=r&sig=xhkwc1uzsRRLW2HjnG4uU7qYV209r2QfpACdCMYTPlA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 19:42 UTC, madansr7 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [customPasswordAddition](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta) enum to passwordCredentialConfi
Updated the verbiage a bit. I think we should be good to go.

2022-02-02 19:44 UTC, opbld33 commented
Docs Build status updates of commit _[6908566](https://github.com/madansr7/microsoft-graph-docs/commits/6908566c19f200b3d994f5d70eb60190587e6062)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202021942083494-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T19%3A44%3A15Z&sr=b&sp=r&sig=Nu00X5tXgmL51Atif1m4jY3bNJ6M8oUhe2fNjMQZCIs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 06:52 UTC, FaithOmbongi approved these changes
Thank you for your work on this PR @madansr7. 

Side note: I hope the formatting to the changelog won't trigger file-wide merge conflicts for other authors. :)

2022-02-16 19:49 UTC, madansr7 commented
@FaithOmbongi , @Lauragra can we please merge this PR? The schema was deployed earlier this week.

2022-02-16 20:02 UTC, FaithOmbongi commented
Hi @madansr7, I see that I already approved the PR but it has attracted some merge conflicts since then. Kindly:
1. Resolve those so you'll have a clean and mergeable PR
2. Replace the **do not merge** with the **ready to merge** label

and Laura will see the PR in her merge queue.

2022-02-16 23:23 UTC, opbld34 commented
Docs Build status updates of commit _[cb69eac](https://github.com/madansr7/microsoft-graph-docs/commits/cb69eaca55f6d606d33f3b6b58e8496041409977)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202162321203138-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T23%3A23%3A47Z&sr=b&sp=r&sig=NfaLHK%2BIw6j3GHRJL%2BEt8ioqEfuXXttx5M2o14FRoQU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 23:30 UTC, madansr7 commented
@FaithOmbongi , resolved all conflicts and updated labels. The changelog file is a pain and I have never been able to update docs successfully without getting a merge conflict with the changelog file. I hope someone has it on their radar to fix this experience. 
The file is growing enormously. 
FYI @Lauragra

2022-03-01 13:37 UTC, opbld31 commented
Docs Build status updates of commit _[cb69eac](https://github.com/madansr7/microsoft-graph-docs/commits/cb69eaca55f6d606d33f3b6b58e8496041409977)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3605bab4)

<a id="3605bab4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203011336460018-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T13%3A37%3A49Z&sr=b&sp=r&sig=QHjUu5nuyZC4FB5ZipZu6Zg4j2SA4sy6cZWGEA1lfgc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 17:49 UTC, opbld34 commented
Docs Build status updates of commit _[0afed1e](https://github.com/madansr7/microsoft-graph-docs/commits/0afed1e750f563fedfceca27ec9bdcfeb24bd45c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantappmanagementpolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/api/tenantappmanagementpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/applicationauthenticationmethodpolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/applicationauthenticationmethodpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[api-reference/beta/resources/passwordcredentialconfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/api-reference/beta/resources/passwordcredentialconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-15650) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/appPolicyCustomPasswordBlock/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203011747265744-15650%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-01T17%3A49%3A10Z&sr=b&sp=r&sig=wO7ioRO1iNnM1azfKMD9DCVLXHDrWwGiyS7rsCEKxgU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-02 01:25 UTC, merged