remove the incorrect description
microsoftgraph/microsoft-graph-docs pull request #15651
Opened 2022-01-26 17:42 UTC by payiAzure

2022-01-26 17:44 UTC, opbld31 commented
Docs Build status updates of commit _[4d08475](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d0847521cc015b4b97a8644e885df458bade46b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceannouncementattachment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) | [Details](#user-content-88065f9e41e7baa53c00ad52a00e1b22-43cff097)
[api-reference/v1.0/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceannouncementattachment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) | [Details](#user-content-a1c606864af28986d81493634ee0c9f5-43cff097)

<a id="88065f9e41e7baa53c00ad52a00e1b22-43cff097"></a>
### [api-reference/beta/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceannouncementattachment.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service-communications'.`````

<a id="a1c606864af28986d81493634ee0c9f5-43cff097"></a>
### [api-reference/v1.0/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceannouncementattachment.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service-communications'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201261742150306-15651%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T17%3A44%3A12Z&sr=b&sp=r&sig=VYBhtq%2B9Dlt0T0j6tLCk91QWYpU6TATRFAcWqCE0Hqo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 05:03 UTC, opbld33 commented
Docs Build status updates of commit _[251939c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/251939c7d1db646431485c23b79700e2fbe380c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201280501360450-15651%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T05%3A03%3A41Z&sr=b&sp=r&sig=krXaLUZOBKMp1Sv%2BqJMj3xmOsNxTpNa971hDU1NwLuw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 05:14 UTC, opbld32 commented
Docs Build status updates of commit _[100df47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/100df474bb45cedfc8eb90cf2e6ee1e06a91aea4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201280512011985-15651%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T05%3A14%3A28Z&sr=b&sp=r&sig=M5AlAL66iSsMoDyeAC%2B7Hf4U2lvoST3FfJGtkSkFj%2F0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 07:24 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/servicehealthissue.md
> +|resolved|The health status reserved for future use.|
Lines 62-67:
@payiAzure , I suppose these were exposed unintentionally?
Can you change their descriptions to just "Reserved for future use."?

2022-01-28 07:26 UTC, angelgolfer-ms requested changes
Hi @payiAzure , one comment that applies to servicehealthissue.md in beta and in v1. 
After you incorporate the feedback, the PR is good for publishing. Thanks.

2022-01-28 07:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/servicehealthissue.md
> +|resolved|The health status reserved for future use.|
Lines 64-69:
@payiAzure , can you change their descriptions to "Reserved for future use."?

2022-01-28 17:59 UTC, payiAzure commented on api-reference/v1.0/resources/servicehealthissue.md
> +|resolved|The health status reserved for future use.|
Done

2022-01-28 17:59 UTC, payiAzure commented on api-reference/beta/resources/servicehealthissue.md
> +|resolved|The health status reserved for future use.|
Done

2022-01-28 18:03 UTC, opbld30 commented
Docs Build status updates of commit _[3c57063](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c57063a6e3b87587701c2f6d2c00916818a81c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201281800379007-15651%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T18%3A03%3A06Z&sr=b&sp=r&sig=8NaGrqnVFO99VzZw%2Fo0CIySAPoqKvlbp8fyFFw0Juq4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 18:20 UTC, opbld31 commented
Docs Build status updates of commit _[ddb72ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddb72edd07134971e52cc581a32a8ac762e4e43e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-15651) (graph-rest-beta) |
[api-reference/v1.0/resources/serviceannouncementattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceannouncementattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementattachment?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/api-reference/v1.0/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-1.0&branch=pr-en-us-15651) (>= graph-rest-1.0) |
[concepts/images/service-communications-concept-overview-admin-center-windowshealth2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/concepts/images/service-communications-concept-overview-admin-center-windowshealth2.png) | :white_check_mark:Succeeded | |
[concepts/service-communications-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-RemoveIncorrectSentence/concepts/service-communications-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/service-communications-concept-overview?branch=pr-en-us-15651) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201281817414123-15651%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T18%3A20%3A06Z&sr=b&sp=r&sig=161QLX8IH%2FF9ysmNhzcUwxFUJB%2FWogOr%2FB%2BwCgB7u08%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-29 00:05 UTC, angelgolfer-ms approved these changes
Thanks for the details in email, and for incorporating my previous comments.

2022-02-01 05:40 UTC, merged