EM beta: make adding an app as resource more discoverable
microsoftgraph/microsoft-graph-docs pull request #15752
Opened 2022-02-04 21:55 UTC by markwahl-msft

Improve the links to the access package resource article and provide an example of how to use a request to add an app to a catalog.

2022-02-04 21:57 UTC, opbld30 commented
Docs Build status updates of commit _[53363ac](https://github.com/markwahl-msft/microsoft-graph-docs/commits/53363aca8cb05accab203aaeaeb967aa33e1e10f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202042155227935-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T21%3A57%3A28Z&sr=b&sp=r&sig=fT1X6Fl2FNApmngfbbDDv1rw7S8dIAAEEgK8TGrgnlo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 22:38 UTC, opbld30 commented
Docs Build status updates of commit _[0f71ce2](https://github.com/markwahl-msft/microsoft-graph-docs/commits/0f71ce2f961e67432a512825506bbeb60ae9b11c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-c2e10203)
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) | [Details](#user-content-f469847715c5cabc86f06b0c0a623b9a-c2e10203)
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) | [Details](#user-content-7709820e2f31c84019c49b693b7ef6b0-c2e10203)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-c2e10203)
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-c2e10203"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 16, Column 508**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'user-get.md'.`````

<a id="f469847715c5cabc86f06b0c0a623b9a-c2e10203"></a>
### [api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md)
 - **Line 16, Column 71**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageresouceattribute.md'.`````

<a id="7709820e2f31c84019c49b693b7ef6b0-c2e10203"></a>
### [api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md)
 - **Line 18, Column 172**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageresouceattribute.md'.`````

<a id="051358bc4656d01c44251401d620e1c9-c2e10203"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 16, Column 211**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageresouceattribute.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202042235533259-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T22%3A37%3A59Z&sr=b&sp=r&sig=oZ%2BGCk9FPoADRHHCNxWzww4c1u1D1DWE%2BUNjMTeoXkQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db [...]

2022-02-04 22:54 UTC, opbld32 commented
Docs Build status updates of commit _[c90ae50](https://github.com/markwahl-msft/microsoft-graph-docs/commits/c90ae502abc4d58c6fa225980535038fa3fac2d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202042251577135-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T22%3A54%3A14Z&sr=b&sp=r&sig=kA7NUkKRQcqj8N6IBMmTBT%2FcZiBaLCz4YUeoe37WCH0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 16:26 UTC, FaithOmbongi requested changes
Thank you @markwahl-msft for handling this doc enhancement.

I've raised a Q about attributeDestination and attributeSource and if they relate to the Microsoft Graph extensions. If they do, I think it's important to distinguish which extension types ([schema extensions](https://docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0), [open extensions](https://docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0), or [extensionProperties](https://docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-1.0)) and maybe provide a scenario of a value from the EM API that is written as value X in the extension property.

2022-02-07 16:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresource.md
> +|attributes|[accessPackageResourceAttribute](../resources/accesspackageresourceattribute.md) collection| Contains attribute information for the attributes that are required to be collected from the r
```suggestion
|attributes|[accessPackageResourceAttribute](../resources/accesspackageresourceattribute.md) collection| Contains information about the attributes to be collected from the requestor and sent to the resource application. |
```

2022-02-07 16:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattribute.md
> +If the **attributeSource** of the attribute is an [accessPackageResourceAttributeQuestion](accesspackageresourceattributequestion.md), then the requestor's supplied value is stored as-provided on the
Looks like these are related to Microsoft Graph extensions? (Is it [schema extensions](https://docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0), [open extensions](https://docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0), or [extensionProperties](https://docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-1.0)?)

You may also need to provide an example of how "the attribute indicated by attributeName must be a writable property of the user" just so there's an easier mental correlation. Same case for attributeSource. You can provide these scenarios in the respective property descriptions.
```suggestion
If the **attributeDestination** is [accessPackageUserDirectoryAttributeStore](accesspackageuserdirectoryattributestore.md), then the attribute indicated by **attributeName** must be a writable property of the [user](user.md) object.
 
If the **attributeSource** of the attribute is an [accessPackageResourceAttributeQuestion](accesspackageresourceattributequestion.md), then the requestor's supplied value is stored as provided on the user object, and made available to the application and other Microsoft Graph clients.
```

2022-02-07 16:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattribute.md
> +  "isEditable": true,
This shouldn't be confused with an actual example. So the previous values (the return types) were correct.

2022-02-07 16:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +The only property is `question`, which could be an [accessPackageTextInputQuestion](accesspackagetextinputquestion.md) or a [accessPackageMultipleChoiceQuestion](accesspackagemultiplechoicequestion.m
Minor formatting change for consistency
```suggestion
The only property is **question**, which could be an [accessPackageTextInputQuestion](accesspackagetextinputquestion.md) or a [accessPackageMultipleChoiceQuestion](accesspackagemultiplechoicequestion.md) object type.
```

2022-02-07 16:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
>    }
This too is a JSON representation so the previous values were accurate.

2022-02-07 16:46 UTC, opbld34 commented
Docs Build status updates of commit _[ef4495d](https://github.com/markwahl-msft/microsoft-graph-docs/commits/ef4495dedb80bacefbd0f4c267fb17732f20ab82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071643120655-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T16%3A46%3A10Z&sr=b&sp=r&sig=OrPpUFjY16fY7IzZAUaY7o0FoCMkqW5ARzV%2B4gqD1Ko%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 18:01 UTC, opbld31 commented
Docs Build status updates of commit _[9379b1a](https://github.com/markwahl-msft/microsoft-graph-docs/commits/9379b1a695ee61144d6a448b2993a4cc25f2c7d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071756044723-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T18%3A01%3A39Z&sr=b&sp=r&sig=qvpJnFgTHRiOH7HM3KokgF1yVLETpjolEFhpiivmDS0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 18:12 UTC, opbld31 commented
Docs Build status updates of commit _[4de476b](https://github.com/markwahl-msft/microsoft-graph-docs/commits/4de476b96feedc1dcfe3f37c6ea58f3093b786ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202071810585126-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T18%3A12%3A45Z&sr=b&sp=r&sig=Q4YMUfrqPSP5ZpWy78vFsdNURwo2jcQdYrEEj%2BGaLUA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 20:07 UTC, opbld32 commented
Docs Build status updates of commit _[876221d](https://github.com/markwahl-msft/microsoft-graph-docs/commits/876221dd0efef2ed1b656e697bfa4bcba2dd3bd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202072005490952-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T20%3A07%3A27Z&sr=b&sp=r&sig=t4Ld6VxWFUygyhe%2BSWzBulegmy%2Fe1YWch9spS7OgF%2Fo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 20:32 UTC, opbld32 commented
Docs Build status updates of commit _[426372e](https://github.com/markwahl-msft/microsoft-graph-docs/commits/426372eab216aa18fac6e1cfe7404af14c70be51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202072030471298-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T20%3A32%3A36Z&sr=b&sp=r&sig=VSvN6GL5aEHUL4Bde0tDStezKLB6ZfUFGlv03FVccBU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 18:12 UTC, FaithOmbongi approved these changes
Thank you @markwahl-msft for providing the additional context relating to directory extension properties. Approved with suggestions.

2022-02-08 18:12 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattribute.md
Moved the paragraphs in the API description here
```suggestion


### accessPackageResourceAttribute resource type and extension properties

The **attributeDestination**, **attributeName**, and **attributeSource** properties of an access package resource attribute relate to the [directory extension properties](extensionproperty.md).

If the **attributeDestination** is an [accessPackageUserDirectoryAttributeStore](accesspackageuserdirectoryattributestore.md) object type, then the attribute indicated by **attributeName** must be a writable property of the [user](user.md) object. These writable properties are String types registered as [extension properties](extensionproperty.md) on the target **User** object.

For example, suppose an application requires two user attributes, a user's job title, and their personal title. The values of these attributes could be synchronized to Azure AD from the on-premises Active Directory **jobTitle** and **personalTitle** attributes. Because **personalTitle** is not one of the default properties of the [user](user.md) object, this would require [creating a directory schema extension](../api/application-post-extensionproperty.md) to add the **personalTitle** property to the user object type. When creating a resource request for the application, you can include two access package resource attributes, one for the user property **jobTitle**, and another with the name of the directory schema extension property that was created for the personal title, such as `extension_2b676109c7c74ae2b41549205f1947ed_personalTitle`.

If the **attributeSource** of the attribute is an [accessPackageResourceAttributeQuestion](accesspackageresourceattributequestion.md), then the requestor's supplied value is stored as provided on the user object, and made available to the application and other Microsoft Graph clients.
```

2022-02-08 18:43 UTC, opbld34 commented
Docs Build status updates of commit _[57af242](https://github.com/markwahl-msft/microsoft-graph-docs/commits/57af242ea4f6204a218590bb52ff527476bbb72c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackageresourcerequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-reslink/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-15752) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081839507576-15752%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T18%3A43%3A08Z&sr=b&sp=r&sig=P1b48%2BCKsfzZNGmK3saBc6hGWFdiNpJxeZaO0og5pSY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 18:45 UTC, markwahl-msft commented
#sign-off

2022-02-09 03:16 UTC, merged