Updating UserPurpose API in Graph Beta & adding it to v1.0
microsoftgraph/microsoft-graph-docs pull request #15761
Opened 2022-02-07 07:36 UTC by abheek-das

2022-02-07 07:40 UTC, opbld32 commented
Docs Build status updates of commit _[e8e14f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8e14f1eb6b8a31452cba1a48bced91dd7c20fbc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-6b281355)
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) | [Details](#user-content-d8016986c3a73e86eeb6aabcd43f0b4a-6b281355)
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-6b281355"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **Line 22, Column 8**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#userPurpose-values' in 'beta/resources/userpurpose.md', did you mean '#userpurpose-values'?`````

<a id="d8016986c3a73e86eeb6aabcd43f0b4a-6b281355"></a>
### [api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md)
 - **Line 19, Column 8**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#userPurpose-values' in 'v1.0/resources/userpurpose.md', did you mean '#userpurpose-values'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202070736570327-15761%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T07%3A40%3A04Z&sr=b&sp=r&sig=%2F%2FeyfT%2F2ZVQcVBGgD4cOKWHvjkX5hHnyBwno%2BGs5pmg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 07:44 UTC, opbld33 commented
Docs Build status updates of commit _[7ce99f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ce99f736625889a9fea091370d52837c804c19a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) | [Details](#user-content-d8016986c3a73e86eeb6aabcd43f0b4a-a55258e8)
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="d8016986c3a73e86eeb6aabcd43f0b4a-a55258e8"></a>
### [api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md)
 - **Line 19, Column 8**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#userPurpose-values' in 'v1.0/resources/userpurpose.md', did you mean '#userpurpose-values'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202070741044744-15761%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T07%3A44%3A06Z&sr=b&sp=r&sig=%2FqA4UF2%2BUdcUAKyLOfLcvsEYbXF275nVCk6NXYatnuA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 07:47 UTC, opbld31 commented
Docs Build status updates of commit _[d5cc294](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5cc2946e6436116f803790e224d8343107e5c5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202070744473521-15761%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T07%3A47%3A53Z&sr=b&sp=r&sig=E4zedtcigYoTN88unlKCGHnCLJJs5S47ZPxFAA67rQI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 11:13 UTC, opbld30 commented
Docs Build status updates of commit _[fc3f8b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc3f8b41f8dc338e091c1ce8bec9c28ba4e58599)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081111365950-15761%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T11%3A13%3A44Z&sr=b&sp=r&sig=hjgTrXOzICsA32LBttFBz%2BcYW3s%2ByzfPpzS%2Fa2EMoB8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 11:16 UTC, opbld32 commented
Docs Build status updates of commit _[4c93438](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c93438aa0e933ee252bbb639027d7d5c247ee32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081111545102-15761%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T11%3A16%3A25Z&sr=b&sp=r&sig=zx3JmMDG3AJ2w4OPzpyOsh3rXbN9xJhYr2hPzCt0gzg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/api/user-get-mailboxsettings.md
> +### Example 4
For consistency, this H3 (line 313) should already introduce the meaning of the example. This would also help you to simplify the Request description (line 315). In general, I recommend the following revision:

```
### Example 4: Get specifically the user purpose settings of the signed-in user's mailbox

#### Request

The following is an example of a request.

...

#### Response

The following is an example of the response, which includes only the [user purpose](../resources/userpurpose.md) settings.

```

I know your PR just introduces one new example; however, for consistency, I recommend you to apply these change also to examples 1, 2, and 3. Suggested revision:

```
### Example 1: Get all mailbox settings of the signed-in user's mailbox

Get all the mailbox settings of the signed-in user's mailbox, which include settings for automatic replies, date format, locale (language and country/region), time format, time zone, working hours, and user purpose.

#### Request

The following is an example of a request.

...

#### Response

The following is an example of the response, which includes all mailbox settings of the signed-in user.

...

### Example 2: Get specifically the automatic replies settings of the signed-in user's mailbox

#### Request

The following is an example of a request.

...

#### Response

The following is an example of the response, which includes only the automatic replies settings.

...


### Example 3: Get specifically the working hour settings of the signed-in user's mailbox

#### Request

The following is an example of a request.

...

#### Response

The following is an example of the response, which includes only the working hours settings. Notice that the user's work hours are in a \[custom time zone\](../resources/customtimezone.md).

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/mailboxsettings.md
> +|userPurpose|[userPurpose](userpurpose.md)|The purpose of the mailbox. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online. Read only.|
1) Please, keep the list in alphabetical order. In this case, move "userPurpose" to come before "workingHours".

1) Please, replace "Read only" with "Read-only".

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/mailboxsettings.md
> +  "userPurpose": {"@odata.type": "microsoft.graph.userPurpose"}
Please, keep the list in alphabetical order. In this case, move "userPurpose" to come before "workingHours".

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/userpurpose.md
> +The purpose of the mailbox. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online.
For consistency, the description in line 3 should also be present in line 14. For clarity, I recommend you to replace the first sentence "The purpose of the mailbox." with the description in line 3. Suggested revision:

- Represents the user's recipient or mailbox type in Exchange Online. Used to differentiate a mailbox for a single...

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/userpurpose.md
> +|value|[userPurpose](#userpurpose-values)|Represents the user's recipient or mailbox type in Exchange Online. Possible values are: `user`, `linked`, `shared`, `room`, `equipment`, and `others`. See t
For consistency and readability, we introduce the subject before we provide the link. In this case, I recommend: 

- ...and `others`. For more information, see \[userPurpose\](#userpurpose-values).

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/userpurpose.md
> +Here is a JSON representation of the resource.
For consistency, please replace "Here" with "The following".

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/userpurpose.md
> +|room|A mailbox representing a conference room.|
Please, avoid using gerunds where possible; in this case, you can change "representing" to "that represents". Same for line 28.

2022-02-17 21:49 UTC, JarbasHorst commented on api-reference/v1.0/resources/userpurpose.md
> +|others|Mailbox found but user purpose is different from the ones specified above.|
Please use more articles in this sentence. Also, we avoid using the words "above" and "below" per Microsoft style because those terms don't translate well for a global audience. Instead of above, use "previous".  In general, I recommend the following revision for this description:

- A mailbox was found but the user purpose is different from the ones specified in the previous scenarios.

2022-02-17 21:49 UTC, JarbasHorst commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the **userPurpose** property to [mailboxSettings](https://docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0) entity.",
Please, add "the" before "[mailboxSettings]" and replace "entity" with "resource".

2022-02-17 21:49 UTC, JarbasHorst commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the **userPurpose** property to [mailboxSettings](https://docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0) entity.",
I don't see this change in your PR. Are we missing something or should this changelog entry be just removed from this changelog record?

2022-02-17 21:49 UTC, JarbasHorst commented on changelog/Microsoft.Exchange.json
> +        {
This BETA changelog record is missing two changes. Please, add them to the changelog record.

- Change => Renamed the \*\*mailboxRecipientType\*\* enumeration as \*\*userPurpose\*\* .
- Deletion => Removed the \`unknown\` member from the \*\*userPurpose\*\* enumeration.

2022-02-22 20:53 UTC, JarbasHorst commented on api-reference/v1.0/resources/userpurpose.md
> +
Please, remove this empty line (line 47).

2022-08-15 12:27 UTC, abheek-das commented on api-reference/v1.0/resources/mailboxsettings.md
> +  "userPurpose": {"@odata.type": "microsoft.graph.userPurpose"}
Fixed.

2022-08-15 12:28 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +The purpose of the mailbox. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online.
Fixed

2022-08-15 12:29 UTC, opbld34 commented
Docs Build status updates of commit _[2d78176](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d781768e8e564f773c3182275f287552a7efc9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151227221030-15761/BuildReport?accessString=5daede33b3a8c226f87f9c11fe0f14fa2de6cadd5405d36877cd0b4e77238cf6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 12:29 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +|room|A mailbox representing a conference room.|
Fixed.

2022-08-15 12:30 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +|others|Mailbox found but user purpose is different from the ones specified above.|
Fixed.

2022-08-15 12:32 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the **userPurpose** property to [mailboxSettings](https://docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0) entity.",
Fixed.

2022-08-15 12:37 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +        {
Added.

2022-08-15 12:37 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the **userPurpose** property to [mailboxSettings](https://docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0) entity.",
Yes, the changes you suggested in the below comment were the right change descriptions.

2022-08-15 12:38 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +
Fixed.

2022-08-15 12:40 UTC, opbld30 commented
Docs Build status updates of commit _[772ad02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/772ad021ae4e7e2ed475dfa1d11085b427bf4e78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151237018910-15761/BuildReport?accessString=b5cdc50b9610a5bfb007a3e9108bda45994a9a1ac62d6f36eb329b563a383f0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 12:42 UTC, opbld30 commented
Docs Build status updates of commit _[9dfe444](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dfe4441997e5e405397ce972971e5d0b4745501)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151238067163-15761/BuildReport?accessString=b477ecd1fd52d1842bb4f2d045335ac00bcb36dff479a4fba6971caef40c4a67).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 12:44 UTC, abheek-das commented on api-reference/v1.0/api/user-get-mailboxsettings.md
> +### Example 4
Fixed all as suggested.

2022-08-15 12:48 UTC, opbld32 commented
Docs Build status updates of commit _[1f9dd68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f9dd68993cbfbca98f37aed44c10dc7221b57ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) | [Details](#user-content-1cb8ae3531c100c6cb42015a01b1a932-2ed9905e)
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="1cb8ae3531c100c6cb42015a01b1a932-2ed9905e"></a>
### [api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md)
 - **Line 17, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-3' in 'v1.0/api/user-get-mailboxsettings.md', did you mean '#examples'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151246045338-15761/BuildReport?accessString=fd1e363e6b6467f848166c511f20842c7f513409bba66843e52040ad5cdb4ef6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 12:51 UTC, opbld30 commented
Docs Build status updates of commit _[31c9e5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31c9e5a8bba8b853be0b8851b035d41c8182d53d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) | [Details](#user-content-1cb8ae3531c100c6cb42015a01b1a932-b21e5d77)
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="1cb8ae3531c100c6cb42015a01b1a932-b21e5d77"></a>
### [api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md)
 - **Line 17, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-3' in 'v1.0/api/user-get-mailboxsettings.md', did you mean '#examples'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151247429845-15761/BuildReport?accessString=0aae36305257f0a8aebdc55ae94c552e9e485bb3c38ed5e63731359d2be7b99e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 12:56 UTC, opbld32 commented
Docs Build status updates of commit _[507f3f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/507f3f56e3c5d2ebf90799f19b2713ed5509c5c3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) | [Details](#user-content-1cb8ae3531c100c6cb42015a01b1a932-3624ed05)
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="1cb8ae3531c100c6cb42015a01b1a932-3624ed05"></a>
### [api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md)
 - **Line 17, Column 139**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-2-get-specifically-the-automatic-replies-settings-of-the-signed-in-users-mailbox' in 'v1.0/api/user-update-mailboxsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151253545532-15761/BuildReport?accessString=6a6c6ff4b63bfe4fded167e17339164c2c7c50c6540fe5bdd08b3dc0e5390df4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 13:00 UTC, abheek-das commented on api-reference/beta/resources/userpurpose.md
> +|value|[userPurpose](#userpurpose-values)|Represents the user's recipient or mailbox type in Exchange Online. Possible values are: `user`, `linked`, `shared`, `room`, `equipment`, and `others`. See t
Fixed.

2022-08-15 13:00 UTC, opbld32 commented
Docs Build status updates of commit _[e33583e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e33583ec92e36768dcfd3f7eba460236a8cb6343)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151258259846-15761/BuildReport?accessString=7f8340a3233b0b69a21151f22272cea331e59b17ebad4b2cd4a84b21c6369a44).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 13:02 UTC, abheek-das commented on api-reference/v1.0/resources/mailboxsettings.md
> +|userPurpose|[userPurpose](userpurpose.md)|The purpose of the mailbox. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online. Read only.|
Fixed as suggested.

2022-08-15 13:02 UTC, opbld34 commented
Docs Build status updates of commit _[b77d292](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b77d292b93aa7286b3738bc5373f6e679e45ed96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151300134286-15761/BuildReport?accessString=11f8ac9bdf968d33b390e5e5d22a4cdabcc746b9cc9dcc0a45bf01dc455358e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 13:02 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +|value|[userPurpose](#userpurpose-values)|Represents the user's recipient or mailbox type in Exchange Online. Possible values are: `user`, `linked`, `shared`, `room`, `equipment`, and `others`. See t
Fixed.

2022-08-15 13:03 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +Here is a JSON representation of the resource.
Fixed.

2022-08-15 13:04 UTC, opbld34 commented
Docs Build status updates of commit _[601a278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/601a278ba81296c14b6bebdc5f5f344248bb0d52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151302014504-15761/BuildReport?accessString=aebba11f61914d9333b7638f36d77094188e4d40e5aa17549d1974e0495e6a66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 13:09 UTC, opbld31 commented
Docs Build status updates of commit _[e9d1a27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9d1a27abd9cab04116c4eb5fde6b1866a93ff7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151306087551-15761/BuildReport?accessString=8c181205cc2d3c1e0eb065107f026440c64aa6c6e46783c8d172afe375b1a665).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 18:53 UTC, angelgolfer-ms commented on api-reference/v1.0/api/user-get-mailboxsettings.md
>  GET /users/{id|userPrincipalName}/mailboxSettings/workingHours
Line 51: 
Please update the introduction line and add user's recipient or mailbox type (i.e., user purpose).

2022-08-15 18:55 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/userpurpose.md
> +Represents the user's recipient or mailbox type in Exchange Online. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online.
Line 14:
For the second sentence, "used to" is ambiguous can be misinterpreted by machine translation.
I think you're trying to say - this resource differentiates a mailbox for a single user...?
You don't mean to say this resource used to (in the past) differentiate a mailbox...?

If it's the former, you can just say "Differentiates a mailbox..."

2022-08-15 18:56 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/userpurpose.md
> +Represents the user's recipient or mailbox type in Exchange Online. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online.
Please apply the same update to the beta version of the file.

2022-08-15 19:24 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +        {
@abheek-das , for the first change - renaming the enum:
Line 75 should be "enum type".
Line 76 should be the old enum name "mailboxRecipientType".
Line 79 should be the new enum name "userPurpose".

Please take a look at examples 4 and 9 in the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples) topic.

2022-08-15 19:26 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +        {
As for the second change - removing an enum member:
Please see example 5 of the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples) topic and update the ChangeType and Description accordingly.

2022-08-15 19:29 UTC, angelgolfer-ms requested changes
Hi @abheek-das , I did a quick review of your PR per your request. Please address the few comments. 
@JarbasHorst , can you please follow up with reviewing any upcoming changes to this PR and help bring it to a publishable state? Thanks.

2022-08-16 06:34 UTC, abheek-das commented on api-reference/v1.0/resources/userpurpose.md
> +Represents the user's recipient or mailbox type in Exchange Online. Used to differentiate a mailbox for a single user from a shared mailbox and equipment mailbox in Exchange Online.
Yes, it means the former. Updated in both beta & v1.0 docs.

2022-08-16 06:35 UTC, opbld31 commented
Docs Build status updates of commit _[ceec6da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ceec6dac6f1ac1c5fdba679739d60f8e455112ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160633356251-15761/BuildReport?accessString=c34dffc9671054b57191e84b1c56cef95cb73b46633dd27978d207af44940cd1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 06:37 UTC, opbld33 commented
Docs Build status updates of commit _[4605df9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4605df911fae41a1572acc673cf7ba54b9eb274d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160634186982-15761/BuildReport?accessString=76a18d335880f13659d902da4decb23a1c010a17f562bf817af06649ac02fd6b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 06:50 UTC, opbld30 commented
Docs Build status updates of commit _[670837e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/670837ef7bfb594863d4d317607f39a0b317f61c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160648253672-15761/BuildReport?accessString=711672cd0c5171cd573efeb628cf751e1581166ec0bc4d3be48764c33b69c6c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 06:58 UTC, opbld30 commented
Docs Build status updates of commit _[f62a1fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f62a1fa2f306d1ca1d14610dee68978e0de41ccc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160656191661-15761/BuildReport?accessString=139c9ec6f2757c2bebd7c1335abe1a9267a34d2451002c8ca496ff054034b73b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 06:58 UTC, abheek-das commented on api-reference/v1.0/api/user-get-mailboxsettings.md
>  GET /users/{id|userPrincipalName}/mailboxSettings/workingHours
Added.

2022-08-16 07:00 UTC, opbld32 commented
Docs Build status updates of commit _[98eeb2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98eeb2dfe17f5eea57a707b4cd0e68b84b715e37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160658218393-15761/BuildReport?accessString=8dcf81e04077ded84b30123822a8d41b4b7c52284c759d3c905ba512a7c62701).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 07:07 UTC, opbld32 commented
Docs Build status updates of commit _[3296d3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3296d3e72651f876e26eda709744918885045079)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160705366357-15761/BuildReport?accessString=e57d7504fc358d5baf61da8f7da5692f8ba20882e78d30012a76b084cbf32037).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 17:00 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +        {
@abheek-das , can you please take a look and address the above two comments? 
The properties in the JSON are not all correct yet.

2022-08-17 06:06 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +        {
@angelgolfer-ms Fixed both of these.

2022-08-17 06:08 UTC, opbld32 commented
Docs Build status updates of commit _[b3b517b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3b517bd49263defd674438f0807dd87fd88a59b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208170606481570-15761/BuildReport?accessString=270503c0fa68f7bb8eb359bc9ffff7890597152b0b703fe550192890dc160cf4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 09:08 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [18074](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18074) into this branch to include my final edits.

Also, I am not sure about two things:
- the changelog entry for removing an enum member as I can't access this => Please see example 5 of the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples)
- WorkloadArea in the changelog record

2022-08-17 09:43 UTC, opbld33 commented
Docs Build status updates of commit _[3056f8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3056f8d78f2b1e75afee10855db3e9b8b9ae9743)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208170941172450-15761/BuildReport?accessString=f1fe9e0b6381bee009c9f2353fcfffe2899773c52047f9c5b5be8ce8aaf2168b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 22:59 UTC, opbld34 commented
Docs Build status updates of commit _[1b7012f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b7012fbbfa32d4b5d1b71b82082bf72b7fbc34e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208172257236097-15761/BuildReport?accessString=8ded93377455ef79750ad3dc45b1c66c42e687af8c2055b03213d649125210c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 23:06 UTC, opbld34 commented
Docs Build status updates of commit _[2b9778a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b9778a30b279477a01015264aa25a73eb9c227a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208172304554210-15761/BuildReport?accessString=af5ebfe1ab0ec2807ffaa08892e29117046279c4cb9cfcaced8ff71e3b1a33a5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 23:27 UTC, Lauragra commented on changelog/Microsoft.Exchange.json
> +          "Description": "Renamed the **mailboxRecipientType** enumeration as **userPurpose**.",
This changelog entry seems to imply that userPurpose is an enum, that used to be called mailboxRecipientType and was renamed? In which case, we would not have a topic in beta or v1.0 for "userPurpose resource type". Please clarify.

2022-08-17 23:28 UTC, Lauragra commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
Is there both a resource type and an enum named userPurpose? Please clarify. I don't currently see a userPurpose resource type in the metadata.

2022-08-18 07:10 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
Hi @Lauragra - Yes, it's both a resource type and the enum that it uses is also called userPurpose. The resource topic page primarily talks about what userPurpose is/represents and its potential values. 

Please see below from https://graph.microsoft.com/v1.0/$metadata

![image](https://user-images.githubusercontent.com/65342232/185328306-c030728f-53c0-4d00-a794-f8446320894c.png)

![image](https://user-images.githubusercontent.com/65342232/185327937-7a3857fd-1a9d-4c84-8958-122244879737.png)

And the API supports calls like this:
GET https://graph.microsoft.com/v1.0/me/mailboxSettings/userPurpose
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('XXX')/mailboxSettings/userPurpose",
    "value": "user"
}

2022-08-18 09:52 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +          "Description": "Renamed the **mailboxRecipientType** enumeration as **userPurpose**.",
Clarified in below comment.

2022-08-18 09:55 UTC, opbld33 commented
Docs Build status updates of commit _[b908cb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b908cb82d10d3c679ad6f54e1c5e4ab780724b61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208180951259523-15761/BuildReport?accessString=b68e903757be85710adb631c08e10365d99367309d85bc129633f25e46b8f5e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 06:03 UTC, opbld34 commented
Docs Build status updates of commit _[1142138](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1142138a3d9c78097e933e53496e14f856e1a662)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190600111415-15761/BuildReport?accessString=38fd5d6bccea62594b9a471f7c54a3625d2231797c4b8748d88444e864ab0e2c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-20 07:07 UTC, opbld33 commented
Docs Build status updates of commit _[3367229](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33672292550cd46d87e20c2c2d2428ef786e6f55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208200705200509-15761/BuildReport?accessString=735d936365747e65f8fee9b7e7b0089f75a779442ecb4a5f4d1b9033bd9f0ae1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 06:03 UTC, abheek-das commented
@Lauragra , is there any more clarification required here or are we good to go ahead?

2022-08-23 06:05 UTC, opbld34 commented
Docs Build status updates of commit _[5a2a00c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a2a00ca5dc88dc2bfb1e7d042a0da91054ec6c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208230603064109-15761/BuildReport?accessString=74e88e6134c8aa634c797e70388182f40e54b5b2b78af14df13735855b7ccce7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 00:17 UTC, Lauragra commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
> Hi @Lauragra - Yes, it's both a resource type and the enum that it uses is also called userPurpose. The resource topic page primarily talks about what userPurpose is/represents and its potential values.
> 
> Please see below from https://graph.microsoft.com/v1.0/$metadata
> 
> ![image](https://user-images.githubusercontent.com/65342232/185328306-c030728f-53c0-4d00-a794-f8446320894c.png)
> 
> ![image](https://user-images.githubusercontent.com/65342232/185327937-7a3857fd-1a9d-4c84-8958-122244879737.png)
> 
> And the API supports calls like this: GET https://graph.microsoft.com/v1.0/me/mailboxSettings/userPurpose as wells as returned as one of the properties when https://graph.microsoft.com/v1.0/me/mailboxSettings is called standalone. { "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('XXX')/mailboxSettings/userPurpose", "value": "user" }

@abheek-das, can you show me where in the metadata we have a userPurpose resource/entity type? We don't create resource type topics for properties or enums, that's where the confusion is coming in.

2022-08-24 05:00 UTC, opbld32 commented
Docs Build status updates of commit _[9b7c4e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b7c4e6f642c5f08a839b61f04d4c92508e994ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/userpurpose.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208240458011664-15761/BuildReport?accessString=16ba8d2c8d8095dde2ab9ade7112ec544ddd019f2a3796af3b2ad339bdbab92b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 17:51 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
@Lauragra - I have pasted all metadata references to userPurpose above. If we don't want to create a resource type topic for property/enums - can you tell me what's the right place to put this & details of possible supported values? +@JarbasHorst - Could you please advise on what changes are needed here?

2022-08-25 02:22 UTC, Lauragra commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
@abheek-das , you would remove the userpurpose.md resource type topic and add an H3 to the Properties section of the mailboxSettings.md resource topic that defines the values for the userPurpose enum, so basically move the values table from userpurpose.md to mailboxesettings.md under the Properties table. The link to userpurpose.md in the Properties table can just link to the H3 section.

For details about documenting enums, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations. What I'm describing is the second option.

2022-08-29 22:33 UTC, JarbasHorst commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
Hi @abheek-das, hi @Lauragra,

to speed up the content review process, I incorporated Laura's feedback directly. @Lauragra, please merge PR [18229](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18229) into this branch to include my fixes. Thanks!

2022-08-30 00:19 UTC, opbld30 commented
Docs Build status updates of commit _[f3770d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3770d7add5fc4e79b2001d5bcdc250fbec224ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-5bc55ed7)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-5bc55ed7"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300015385570-15761/BuildReport?accessString=a15594cf82b67516f834829fa347aed5acf15a429d793d4eb66e5c21e47704db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 23:32 UTC, JarbasHorst commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the [userPurpose](https://docs.microsoft.com/en-us/graph/api/resources/userpurpose?view=graph-rest-1.0) resource type.",
@Lauragra, I added a redirection link as you suggested. Please, merge PR [18249](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18249) into this branch to include the redirection link. Thanks!

2022-08-31 00:22 UTC, opbld34 commented
Docs Build status updates of commit _[a622132](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a622132d4b0e30de6240070a427e0d5f9f87027f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-afb9b1f4)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-afb9b1f4"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310020109901-15761/BuildReport?accessString=b28068264c593af5132161e34046e37e67c8a115d230c90beddd1f3a561923cd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 01:44 UTC, opbld30 commented
Docs Build status updates of commit _[fb113c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb113c9dc63c69cac635837699600f22c403a032)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-478437d1)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-478437d1"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080142284477-15761/BuildReport?accessString=14fa64bbcedb1a64571cb63f490423f56e242f73a472da893cb0d03a8a4e19f7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 01:46 UTC, opbld32 commented
Docs Build status updates of commit _[8ad3e7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ad3e7c7e3161e05896b9359e4fd24e59facb509)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-c9501744)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-c9501744"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080143586514-15761/BuildReport?accessString=edf275bb34a86836e4e2315b94582444189bca104b6bd713f3517afaa852bf97).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 17:27 UTC, opbld31 commented
Docs Build status updates of commit _[9152d06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9152d06a3e431a70a98081e384aba26da8a105c4)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted or renamed) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-375a0cad)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-375a0cad"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209211722137662-15761/BuildReport?accessString=b7030562c2e0375c442f7c2d8c2454b40b5034efc610501c4a121e7c5059492a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 17:20 UTC, opbld33 commented
Docs Build status updates of commit _[0f2a8a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f2a8a51c46c373fb95278e8f816ba1e7aa64167)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted or renamed) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-41ee88b1)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-41ee88b1"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221717043784-15761/BuildReport?accessString=b197135a628322eaa3ab57b604f7316826330706ae6a86df22a1c6657741e98d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 17:26 UTC, opbld33 commented
Docs Build status updates of commit _[e8cdd2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8cdd2e6aefdccb80c40708fc26f2a3660513e91)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted or renamed) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-f32c0094)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-f32c0094"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221723301089-15761/BuildReport?accessString=c7c1c4f76d688d41ac09a2a60231b7cde65ec9257fe0b739ec8f1cecb64a4050).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:26 UTC, opbld31 commented
Docs Build status updates of commit _[90509ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90509abea505b348a857cc6fc4c3f9ac571950b9)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md) | :bulb:Suggestion |n/a (file deleted or renamed) | [Details](#user-content-3882d4f0ed0bde9a91d34392ba7246eb-f64d157e)
[api-reference/beta/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/beta/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-beta&branch=pr-en-us-15761) (graph-rest-beta) |
[api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/api/user-get-mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/mailboxsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workinghours.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/v1.0/resources/workinghours.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/workinghours?view=graph-rest-1.0&branch=pr-en-us-15761) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0822.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/redirects/.openpublishing.redirection.0822.json) | :white_check_mark:Succeeded | |

<a id="3882d4f0ed0bde9a91d34392ba7246eb-f64d157e"></a>
### [api-reference/beta/resources/userpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/UserPurpose-API/api-reference/beta/resources/userpurpose.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/resources/userpurpose.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221818460524-15761/BuildReport?accessString=a878808ae46ec8f3508a04a51e82ef154a5388f829360478d9a84c0850de082f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:37 UTC, Lauragra approved these changes

2022-10-04 21:02 UTC, JarbasHorst commented
@abheek-das, please fix the conflicting changes and add the ready to merge label if your PR is ready for external customers to use.

2022-10-04 21:21 UTC, opbld31 commented
Learn Build status updates of commit _[a074e79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a074e79ff07f89bc8487c7c584e2fd34e56b616a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-81d1d254)

<a id="81d1d254"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a074e79ff07f89bc8487c7c584e2fd34e56b616a in branch UserPurpose-API of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 512d45d7b3d9dc7b78bd1a4fb08985d0de70795f). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210042121099482-15761/BuildReport?accessString=cd1062514ccc35c2796e61d8853f3ccb0ae2ccb13a9e2991148b4426bf04dcf9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-03-03 03:15 UTC, merged