Go SDK updates
microsoftgraph/microsoft-graph-docs pull request #15784
Opened 2022-02-08 18:36 UTC by jasonjoh

- Added Go SDK dependencies to installing doc
- Added Go examples to paging doc

2022-02-08 18:39 UTC, opbld31 commented
Docs Build status updates of commit _[a8ed33e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8ed33e4d8e3862bb1b5edac019cfcf58c5095b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk-updates/concepts/sdks/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/paging?branch=pr-en-us-15784) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk-updates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-15784) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081836235197-15784%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T18%3A39%3A03Z&sr=b&sp=r&sig=5gSotmZRXy0rdU1%2BhJFf792NSK4YFJbwwZVTfSAh1ig%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 18:48 UTC, baywet requested changes
Thanks for putting this together, I think you might have discovered a new issue with the implementation.

2022-02-08 18:48 UTC, baywet commented on concepts/sdks/paging.md
> +pageIterator.SetHeaders(map[string]string{"Content-Type": "application/json"})
@jasonjoh it should work without requiring you to set that header. What happens if you remove it?

2022-02-08 18:48 UTC, baywet commented on concepts/sdks/paging.md
> +        "Prefer": "outlook.body-content-type=\"text\"",
this header probably needs to be passed to the page iterator as well to get consistent results across pages.

2022-02-08 19:00 UTC, jasonjoh commented on concepts/sdks/paging.md
> +pageIterator.SetHeaders(map[string]string{"Content-Type": "application/json"})
Yes you're right. I copied this from the original PR that added the iterator to the SDK, and assumed it was needed. I meant to try it without but honestly forgot it was there :D

2022-02-08 19:11 UTC, opbld34 commented
Docs Build status updates of commit _[c185211](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1852112fac9e286a6c7dfb4ec6312a94dee5fb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk-updates/concepts/sdks/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/paging?branch=pr-en-us-15784) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk-updates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-15784) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202081908405106-15784%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T19%3A11%3A29Z&sr=b&sp=r&sig=ob1p%2FWNg6wGJVAILYnT480KtIFQi6Fb8wvSNKQZxngM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 19:56 UTC, baywet approved these changes

2022-02-08 19:56 UTC, baywet commented on concepts/sdks/paging.md
> +pageIterator.SetHeaders(map[string]string{"Prefer": "outlook.body-content-type=\"text\""})
```suggestion
pageIterator.SetHeaders(options.H)
```

I'm not dead set on that if you think that's bad for readability, but we could promote reusability this way

2022-02-09 15:15 UTC, jasonjoh commented on concepts/sdks/paging.md
> +pageIterator.SetHeaders(map[string]string{"Prefer": "outlook.body-content-type=\"text\""})
Yeah, I think this is a good change.

2022-02-09 15:17 UTC, opbld34 commented
Docs Build status updates of commit _[217732a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/217732a61c2699080783f62acd2fdc46bd7c113c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk-updates/concepts/sdks/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/paging?branch=pr-en-us-15784) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk-updates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-15784) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202091515236655-15784%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T15%3A17%3A31Z&sr=b&sp=r&sig=tJvLW6x%2Fu3J5wfvk25irSIs2yu3rB6tckYfzsehXWrw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 15:42 UTC, baywet approved these changes

2022-02-24 04:12 UTC, Lauragra approved these changes

2022-02-25 04:19 UTC, merged