Add api to get user's Cloud PC list and add api to get user's Cloud PC Launch Info
microsoftgraph/microsoft-graph-docs pull request #15791
Opened 2022-02-09 06:31 UTC by andrewku0409

2022-02-09 06:33 UTC, opbld34 commented
Docs Build status updates of commit _[f60f79b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f60f79bc15cc62690ebe97a0ed82d08777ef6719)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/intune-cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/intune-cloudpc-getcloudpclaunchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-ae61666bd877075b97fb86bf23c83d16-0309dfb5)
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-0309dfb5)
[api-reference/beta/resources/intune-cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/intune-cloudpclaunchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-2bc2cd9e046f104344c3478773fabc2e-0309dfb5)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-0309dfb5)

<a id="ae61666bd877075b97fb86bf23c83d16-0309dfb5"></a>
### [api-reference/beta/api/intune-cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/intune-cloudpc-getcloudpclaunchinfo.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/intune-cloudpc-getcloudpclaunchinfo.md(3,14)', 'beta/resources/intune-cloudpclaunchinfo.md(3,14)'.`````

<a id="8c19544f8e60e9a7f35cfc34390e88df-0309dfb5"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List cloudPCs - Microsoft Graph beta' is duplicated in: 'beta/api/user-list-cloudpcs.md(2,8), beta/api/virtualendpoint-list-cloudpcs.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="2bc2cd9e046f104344c3478773fabc2e-0309dfb5"></a>
### [api-reference/beta/resources/intune-cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/intune-cloudpclaunchinfo.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/intune-cloudpc-getcloudpclaunchinfo.md(3,14)', 'beta/resources/intune-cloudpclaunchinfo.md(3,14)'.`````

<a id="a9854c9f614e4703ed375d736557d7fd-0309dfb5"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List cloudPCs - Microsoft Graph beta' is duplicated in: 'beta/api/user-list-cloudpcs.md(2,8), beta/api/virtualendpoint-list-cloudpcs.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090631125638-15791%5Cworkflow_report. [...]

2022-02-09 08:37 UTC, opbld34 commented
Docs Build status updates of commit _[1a8fe79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a8fe79a4a85dc3a5815b0ab08cbf8aa97aa00b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-f2d7eff05666aba1af3a5275f08d6656-0f61d511)
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-0f61d511)
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-3b4577f6911c80c120000cbd4004ea36-0f61d511)

<a id="f2d7eff05666aba1af3a5275f08d6656-0f61d511"></a>
### [api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'AndrewKuSZ' is not a valid GitHub ID.`````
 - **Line 46, Column 69**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-cloudpclaunchinfo.md'.`````

<a id="8c19544f8e60e9a7f35cfc34390e88df-0f61d511"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'AndrewKuSZ' is not a valid GitHub ID.`````

<a id="3b4577f6911c80c120000cbd4004ea36-0f61d511"></a>
### [api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'AndrewKuSZ' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202090835487002-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T08%3A37%3A46Z&sr=b&sp=r&sig=CB%2Fi3oO1kerFmFlWVhkGCAOnZv7tFydK6YGJJxlaKOo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-09 10:29 UTC, opbld33 commented
Docs Build status updates of commit _[1f54096](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f5409604be6f0d8d7799b6860e602f13224a08c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-f2d7eff05666aba1af3a5275f08d6656-bcae1187)
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-bcae1187)
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) | [Details](#user-content-3b4577f6911c80c120000cbd4004ea36-bcae1187)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |

<a id="f2d7eff05666aba1af3a5275f08d6656-bcae1187"></a>
### [api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'AndrewKuSZ' is not a valid GitHub ID.`````
 - **Line 46, Column 69**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-cloudpclaunchinfo.md'.`````

<a id="8c19544f8e60e9a7f35cfc34390e88df-bcae1187"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'AndrewKuSZ' is not a valid GitHub ID.`````

<a id="3b4577f6911c80c120000cbd4004ea36-bcae1187"></a>
### [api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'AndrewKuSZ' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202091027164851-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T10%3A29%3A19Z&sr=b&sp=r&sig=RhCzGqxbOHOuZ56W0MzHTykBzwdrLEPuyE1GOaw90hs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-02 09:22 UTC, RuiHou105 commented on api-reference/beta/api/user-list-cloudpcs.md
> +>**Note:** The response object shown here might be shortened for readability.
You can remove this line.

2022-03-02 09:26 UTC, RuiHou105 commented
@andrewku0409  Could you please also update the Microsoft.CloudManagedDesktop.json file? It records all your changes.

2022-03-03 04:12 UTC, opbld31 commented
Docs Build status updates of commit _[853dbc5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/853dbc5e4b06b9ab48bed8f998f33181cb5021fa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-809ff8bb)

<a id="809ff8bb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030412117851-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A12%3A46Z&sr=b&sp=r&sig=AUlkrI6IIZcnEUB3RA%2B49SCfC%2FIlyPgH2A3cmciAmKg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:22 UTC, opbld30 commented
Docs Build status updates of commit _[2db47db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2db47db5f7db3ea0eeb45734d0937a876e007ceb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030418575179-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A22%3A22Z&sr=b&sp=r&sig=BhVT9jdxa2hPwv6S85VJuDCjIYiIDDGeR2HwWm%2F%2FvZk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:39 UTC, opbld33 commented
Docs Build status updates of commit _[8555b28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8555b287e624497b44c5d56628806e3ce705a1fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030437537528-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A39%3A49Z&sr=b&sp=r&sig=7I47R%2FYrxF7q%2BhVXsBvbDQtDDzi3qor4oQXcYXAlxyw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:42 UTC, opbld30 commented
Docs Build status updates of commit _[63fe555](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63fe5554cc6a534a764862b69b6a52f624f2c74f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030440511397-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A42%3A40Z&sr=b&sp=r&sig=m346TDDZoXMp4K5IQuzHkBl6bITjZ%2F%2Bv76Ih904K%2Bj8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:45 UTC, opbld34 commented
Docs Build status updates of commit _[ec1fd3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec1fd3af4d9850fbf113168e2b8928654d90ab61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030442502567-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A45%3A17Z&sr=b&sp=r&sig=mHZWZll%2F6eF3KmrgiXhBS%2BkHWAoJDC1YqO2i73xsRfo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-13 12:57 UTC, AshleyYangSZ requested changes

2022-03-13 12:57 UTC, AshleyYangSZ commented on api-reference/beta/api/user-list-cloudpcs.md
> +List the [cloudPC](../resources/cloudpc.md) objects of the calling user with the following properties: Id, DisplayName, ImageDisplayName, ServicePlanId, ServicePlanName, ServicePlanType, Status, Last
List the [cloudPC](../resources/cloudpc.md) objects the current sign in user has.

2022-03-17 04:33 UTC, opbld34 commented
Docs Build status updates of commit _[87f26a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87f26a7b85cdbe9b075bcede5ac621d1c4bfe3e9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-292673f2)

<a id="292673f2"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203170433008560-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T04%3A33%3A41Z&sr=b&sp=r&sig=uD3gDtqNvjdCpBR%2Blo01uZ7E6fPiYNDQA8i4WcgzQBg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-17 04:44 UTC, opbld32 commented
Docs Build status updates of commit _[60fa24e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60fa24e02b4dbd4634833014ef4d356561f3cb00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203170442159510-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T04%3A44%3A25Z&sr=b&sp=r&sig=ZWLhjTh2eTO9KpdY3IuJb9SYfNY1IZzBxekY7EBMcq0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-17 07:19 UTC, RuiHou105 commented
Roadmap workitem:

[Feature 13328](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/13328): [DEVICES AND APPS][CLOUD PC] Add api me/CloudPCs, and add cloudPCLaunchInfo complex type, extend function getCloudPCLaunchInfo from CloudPC entity


@Lauragra , @JarbasHorst , @isvargasmsft , could one of you help review this PR when you got time? Thanks in advance!

2022-03-17 15:54 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpclaunchinfo.md
> +description: "Represents the Cloud PC launch info"
Descriptions in lines 3 and 16: We try to avoid using the name of the resource to describe its functionality. My suggestion:
Contains the information to launch a cloudPC (insert reference link to cloudPc resource type).

2022-03-17 17:37 UTC, isvargasmsft commented on api-reference/beta/api/user-list-cloudpcs.md
> +List the [cloudPC](../resources/cloudpc.md) objects the current sign in user has with the following properties: Id, DisplayName, ImageDisplayName, ServicePlanId, ServicePlanName, ServicePlanType, Sta
please end this sentence with a period (.).

2022-03-17 17:39 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpc.md
> +|[Get my Cloud PC launch info](../api/cloudpc-getcloudpclaunchinfo.md)|[cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md)|Get the [cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md) for a call
Line 37: Can we rename this to **Get Cloud PC launch info**?

2022-03-17 17:41 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                }
Is this referring to the LIST operation? In this case please follow the example 6 of this list: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

This is a regular CRUD operation, we are listing the cloudPCs associated to a user, using a navigation property.

2022-03-17 17:47 UTC, isvargasmsft commented on api-reference/beta/api/user-list-cloudpcs.md
> +# List my cloudPCs
Why are we adding a new topic for this List operation? I'd suggest adding the new HTTP request path to the existing List Cloud PC topic. What do you think?

2022-03-17 21:19 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +            href: api/cloudpc-getcloudpclaunchinfo.md
This methods should be added under the User node. Could you please add a cloudPC subnode under user and add these?

In addition, I'd prefer if we say List cloudPCs of a user instead of List my cloud PCs.

2022-03-17 21:19 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpc.md
> +|[Get my Cloud PC launch info](../api/cloudpc-getcloudpclaunchinfo.md)|[cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md)|Get the [cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md) for a call
Line 36: Please rename to List cloudPCs of a user

2022-03-17 21:21 UTC, isvargasmsft requested changes
Hello Rui, thank you very much for your work in this PR. 

There are 2 main topics to review: topic titles and the TOC. 

Since these new methods operate using the user as a parent, we should add them to the User node in the TOC. 

Please ping me if you have questions. 

Warm regards, 

Isaac

2022-03-18 06:49 UTC, andrewku0409 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                }
Yes we are listing the cloudPCs associated to a user using a navigation property. Should I follow example 3 Add a navigation property to a resource or example 6 Add a CRUD operation to a resource?

2022-03-18 06:51 UTC, andrewku0409 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                }
It refers to "List cloudPCs of a user" method.

2022-03-18 07:15 UTC, andrewku0409 commented on api-reference/beta/toc.yml
> +            href: api/cloudpc-getcloudpclaunchinfo.md
Sure. Should I remove them from here?

2022-03-18 07:18 UTC, opbld31 commented
Docs Build status updates of commit _[007c2bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/007c2bd55ff2a5eed3537449a9762874cc3234a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203180716304400-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T07%3A18%3A27Z&sr=b&sp=r&sig=KXsoQurYVOQeAnrM51RY7a5cRaCRMfr3r7PWLcFRR5I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-20 08:05 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +            href: api/cloudpc-getcloudpclaunchinfo.md
Hi @isvargasmsft, although we extended user entity and add CloudPC as a navigation property to user, only /me/cloudpcs API is supported, and we only plan to support current sign in user to get his/her own CloudPCs, don't support /user/id/cloudpcs API to allow admin/user to get other user's CloudPCs. In this situation, do you think we still have to put this method as subnode under user node?

2022-03-20 08:06 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +            href: api/cloudpc-getcloudpclaunchinfo.md
In addition, for the name, may be List my cloudPCs is more accurate? Since as I just said, we don't support users/id/cloudpcs API.

2022-03-30 17:01 UTC, opbld34 commented
Docs Build status updates of commit _[70a979e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70a979e1f867b811cff339c55b6a967ad1e7bf0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301658167635-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T17%3A01%3A31Z&sr=b&sp=r&sig=gwC8tCHmcT1sum4veGHfxJRmNy6lrtn4yhYYB%2BmIm4Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 17:03 UTC, opbld34 commented
Docs Build status updates of commit _[390d5bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/390d5bf10b180ba2e1232abcfaae87c41a17da54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301700139869-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T17%3A03%3A45Z&sr=b&sp=r&sig=PwdLT2%2BuLeVBPrb6Rxo%2BrDKERDS8qfrNmlYeainvPMY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 17:09 UTC, opbld31 commented
Docs Build status updates of commit _[91f510b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91f510b99a03f7d7f8f914f40d6f9ec98f8c0d74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301707092672-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T17%3A09%3A16Z&sr=b&sp=r&sig=A8In5vGd4ltxF2M5TTGMih5SwAC4W8cjfQsfy1bZBak%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 17:21 UTC, isvargasmsft approved these changes

2022-04-06 02:30 UTC, AshleyYangSZ approved these changes

2022-04-06 03:16 UTC, RuiHou105 approved these changes

2022-04-07 03:28 UTC, opbld30 commented
Docs Build status updates of commit _[6a5b486](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a5b4869504ad6c0a9788760056b4897fd1dbed3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204070325464514-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T03%3A28%3A03Z&sr=b&sp=r&sig=ayjoEkup1H6PDZslPjjVAKGHqd8%2Bs8T9JBc8wq6iu38%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 03:37 UTC, Lauragra commented on api-reference/beta/api/user-list-cloudpcs.md
> +List the [cloudPC](../resources/cloudpc.md) objects of the signed-in user.
Can we clarify this description a bit; i.e. "List the [Cloud PC](../resources/cloudpc.md) devices that are attributed to the signed-in user.

Since we're calling this out in the summary description, we don't necessarily need it in the title/H1.

2022-04-07 03:38 UTC, Lauragra commented on api-reference/beta/api/user-list-cloudpcs.md
> +>This operation returns only the following properties: Id, DisplayName, ImageDisplayName, ServicePlanId, ServicePlanName, ServicePlanType, Status, LastModifiedDateTime, AadDeviceId, StatusDetails, Gr
Please update the property names to be lower camel case (first letter lower case) and apply bold formatting.

2022-04-07 03:43 UTC, Lauragra commented on api-reference/beta/resources/cloudpc.md
> +|[List cloudPCs of a user](../api/user-list-cloudpcs.md)|[cloudPC](../resources/cloudpc.md) collection|List the [cloudPC](../resources/cloudpc.md) objects of the calling user|
I think that you want to surface this link in the user resource topic. Likely, you'll want to add a new row to the Methods table for Cloud PC. Since we already have a List cloudPCs operation here for the non-signed-in user, do we need to surface this method here, or only under user?

2022-04-07 03:47 UTC, opbld30 commented
Docs Build status updates of commit _[ab7ad65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab7ad655ee7804121e4e2f4a09a03420ac5c523f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204070345228084-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T03%3A47%3A24Z&sr=b&sp=r&sig=NwoCPk63qDt3Jmrqy5xeWbyXKcMWhoHVie33oYxVTlw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 03:47 UTC, Lauragra commented on api-reference/beta/resources/cloudpc.md
> +|[Get Cloud PC launch info](../api/cloudpc-getcloudpclaunchinfo.md)|[cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md)|Get the [cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md) for a calling
You can use the method name here: getCloudPcLaunchInfo. Please update the description to match the edits in the method topic.

2022-04-07 03:49 UTC, opbld32 commented
Docs Build status updates of commit _[c2dd61a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2dd61a2cb4ea19a6637166989570eff013bb81f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204070346538861-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T03%3A49%3A39Z&sr=b&sp=r&sig=WOTfr33BRsTg5Oocmxmpm7RA3ku7lSJHXtHb4O9FGAg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 03:49 UTC, Lauragra commented on api-reference/beta/resources/cloudpclaunchinfo.md
> +Contains the information to launch a [cloudPC](../resources/cloudpc.md)
Please make sure that the summary description here and in the description field end in periods. Is this description sufficient, i.e. will the target audience understand what we mean by "launch a Cloud PC"? Is that like creating or provisioning a Cloud PC? Generally, it's helpful to use different terms than the resource name to describe/define it.

2022-04-07 03:50 UTC, Lauragra commented on api-reference/beta/resources/cloudpclaunchinfo.md
> +|cloudPcLaunchUrl|String|The launch url of the Cloud PC|
Please change url to URL and add a period to the description.

2022-04-07 03:54 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get Cloud PC launch info
We can probably remove Cloud PC from the TOC entry for brevity.

2022-04-07 10:11 UTC, andrewku0409 commented on api-reference/beta/resources/cloudpclaunchinfo.md
> +Contains the information to launch a [cloudPC](../resources/cloudpc.md)
Good idea! Thanks, I have changed the term to "connect".

2022-04-07 10:12 UTC, opbld32 commented
Docs Build status updates of commit _[0f74fb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f74fb67c65b96ffad8efcfc071c7fa8b3ca0422)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204071010108571-15791%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T10%3A12%3A10Z&sr=b&sp=r&sig=tzifsV1V3WE35MOpfioHHnqwS05G5vKZPwcTlT0Mmpk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 10:12 UTC, andrewku0409 commented on api-reference/beta/api/user-list-cloudpcs.md
> +List the [cloudPC](../resources/cloudpc.md) objects of the signed-in user.
Do you mean that we should use List the cloudPCs as title? Or List cloudPCs of the user is also ok?

2022-04-07 10:35 UTC, andrewku0409 commented on api-reference/beta/resources/cloudpc.md
> +|[Get Cloud PC launch info](../api/cloudpc-getcloudpclaunchinfo.md)|[cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md)|Get the [cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md) for a calling
A question here, since the getCloudPcLaunchInfo is only supported by me/cloudPCs/{id}, should we include "user" in the method name?

2022-04-08 03:24 UTC, Lauragra commented on api-reference/beta/resources/cloudpc.md
> +|[List cloudPCs of a user](../api/user-list-cloudpcs.md)|[cloudPC](../resources/cloudpc.md) collection|List the [cloudPC](../resources/cloudpc.md) objects of the calling user|
FYI, the consensus is to surface the method both here and in the Users section of the TOC, for discoverability. So please do be sure to add the link to the two methods to the user resource topic as well.

2022-04-08 03:26 UTC, Lauragra commented on api-reference/beta/resources/cloudpc.md
> +|[Get Cloud PC launch info](../api/cloudpc-getcloudpclaunchinfo.md)|[cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md)|Get the [cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md) for a calling
> A question here, since the getCloudPcLaunchInfo is only supported by me/cloudPCs/{id}, should we include "user" in the method name?

Actually, my suggestion for the link title here is "Get launch info for user". The Cloud PC context should be clear and that way the link text is concise/understandable.

2022-04-08 03:29 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get Cloud PC launch info
The method topics are nested under Cloud PC, so my view is that sets the context sufficiently and the best practice is to keep TOC entries concise/scannable. My recommendation would be "Get launch info" for the TOC entry.

2022-04-08 03:30 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List Cloud PCs of a user
Maybe we can also shorten these entries to "List for user" and "Get launch info for user", given that the Cloud PC context is clear.

2022-04-19 07:06 UTC, RuiHou105 commented on api-reference/beta/api/user-list-cloudpcs.md
> +List the [cloudPC](../resources/cloudpc.md) objects of the signed-in user.
@andrewku0409 please update this description here to be: List the Cloud PC devices that are attributed to the signed-in user.

2022-04-19 07:08 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +          - name: List Cloud PCs of a user
@andrewku0409  please help update the method names here, according to Laura's suggestion. Thanks.

2022-04-19 07:12 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +        - name: Get Cloud PC launch info
@andrewku0409  Based on the fact that this method is already put under Cloud PC entry (Line 327), we'd better update the method name to "Get launch info" for brevity.

2022-04-19 07:17 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[List cloudPCs of a user](../api/user-list-cloudpcs.md)|[cloudPC](../resources/cloudpc.md) collection|List the [cloudPC](../resources/cloudpc.md) objects of the calling user|
@andrewku0409  As the two methods are added under the Users TOC and Cloud PC TOC,  could you please add these two methods into the user resource file? Just like what you've done in this file.

2022-04-21 06:56 UTC, andrewku0409 commented on api-reference/beta/toc.yml
> +          - name: List Cloud PCs of a user
Thanks @Lauragra and @RuiHou105 . I have updated the names here.

2022-04-21 06:57 UTC, andrewku0409 commented on api-reference/beta/toc.yml
> +        - name: Get Cloud PC launch info
Thanks @Lauragra and @RuiHou105 . I have updated the names here.

2022-04-21 06:57 UTC, opbld32 commented
Docs Build status updates of commit _[8f83722](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f8372290e071d4a85f0c0906dddce7361461a90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210653420447-15791%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T06%3A57%3A35Z&sr=b&sp=r&sig=PZmT6%2Bni2zl3GWgotueCN1rfy3IXu3STF2LOUJM78Hg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 06:57 UTC, andrewku0409 commented on api-reference/beta/resources/cloudpc.md
> +|[Get Cloud PC launch info](../api/cloudpc-getcloudpclaunchinfo.md)|[cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md)|Get the [cloudPCLaunchInfo](../resources/cloudpclaunchinfo.md) for a calling
Good suggestion, thanks @Lauragra. I have also update "List cloudPCs of a user" to "List for user".

2022-04-21 06:59 UTC, opbld31 commented
Docs Build status updates of commit _[7972082](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79720822582d0ef0f0397379c65d4200c607e924)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210656069582-15791%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T06%3A59%3A37Z&sr=b&sp=r&sig=rBoMsJ0EFowGIc4buS61m2a2pvVTvBXyXH10%2FWFG%2FRY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:07 UTC, andrewku0409 commented on api-reference/beta/resources/cloudpc.md
> +|[List cloudPCs of a user](../api/user-list-cloudpcs.md)|[cloudPC](../resources/cloudpc.md) collection|List the [cloudPC](../resources/cloudpc.md) objects of the calling user|
Thanks @Lauragra and @RuiHou105. I have added two methods into the user resource file.

2022-04-21 07:08 UTC, opbld31 commented
Docs Build status updates of commit _[377e39d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/377e39d41f09dc463b58994e17bf9996a69fadde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210705598153-15791%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T07%3A08%3A27Z&sr=b&sp=r&sig=4f3KzTDcC3D%2Fy73CXCKbcY8uBQ8pRMqWhzILZCpOmCY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:26 UTC, opbld32 commented
Docs Build status updates of commit _[d63606f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d63606fc2b7e4414583e617bbd8c4ab8cbe20aaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210724258472-15791%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T07%3A26%3A13Z&sr=b&sp=r&sig=k6yF%2FwFELM1Pqe9yx0NffNvgQ17MZE2o42HCsI1n31o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:48 UTC, andrewku0409 commented on api-reference/beta/api/user-list-cloudpcs.md
> +List the [cloudPC](../resources/cloudpc.md) objects of the signed-in user.
Done.

2022-04-28 04:07 UTC, opbld30 commented
Docs Build status updates of commit _[ca4b8b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca4b8b371eca1163ab1a1caeccb7cda2e4be864b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-15791) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-02-09-tsku-user-cloudpc-update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280405209498-15791%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T04%3A07%3A26Z&sr=b&sp=r&sig=9ryUZwLy8CxhB94%2B55HOzpKZoVFLEfpGDgnvMWJ0jjo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 04:12 UTC, merged