Support MembershipSummary changes in TGS
microsoftgraph/microsoft-graph-docs pull request #15810
Opened 2022-02-10 05:59 UTC by akhilkohlimicrosoft

2022-02-10 06:01 UTC, opbld31 commented
Docs Build status updates of commit _[1df5e66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1df5e6669d9c0c2e16d4fe4e6530ca515c609f51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamSummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamSummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202100559198061-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T06%3A01%3A28Z&sr=b&sp=r&sig=9KNdvqBgrt0RLUyiow88UwU%2BMPqj1%2FSLHLK4bU%2Bd07s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 06:25 UTC, mankadnandan requested changes

2022-02-10 06:25 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "team",
"ChangedApiName": "summary" ? This is generally the newly added property.

2022-02-10 06:25 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the summary property to [team](https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta).",
\*\*summary\*\* to make it bold

2022-02-10 07:15 UTC, opbld34 commented
Docs Build status updates of commit _[8627474](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86274745b9076e383fa0c1e7e740211003793388)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamSummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamSummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202100713094990-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T07%3A15%3A20Z&sr=b&sp=r&sig=W7ljMTytTOQv1Yx%2Fnyr6hpxlLzbIbCMffOh%2FG1w1XhI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-11 04:55 UTC, Lauragra commented on api-reference/beta/resources/teamSummary.md
> +Team summary consists of ownersCount, membersCount, guestsCount in the [team](team.md).
Suggested revision: "Contains information about a team in Microsoft Teams, including numbers of owners, members, and guests."

2022-02-11 04:55 UTC, Lauragra commented on api-reference/beta/resources/teamSummary.md
> +    "ownersCount": 2,
In the JSON representation, we should show the type rather than include example values.

2022-02-11 04:55 UTC, Lauragra commented on api-reference/beta/resources/teamSummary.md
> +|ownersCount|Integer|Count of owners in a team.|
Please list the properties in alphabetical order.

2022-02-11 04:56 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "2272f260-c87f-42b2-88e4-ea84fc822a5f",
Note that you also need an item for the new **teamSummary** resource type.

2022-03-09 11:15 UTC, opbld31 commented
Docs Build status updates of commit _[0ceeb19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ceeb19ac87981b3340793ea2ab9541fed54134d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamSummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamSummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203091111372035-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T11%3A15%3A00Z&sr=b&sp=r&sig=qYwUN%2BmP3Z9S0G%2BhzDEI0muxjOpmS3WbO8hD54sIk3E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 11:19 UTC, opbld34 commented
Docs Build status updates of commit _[1f58989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f58989c893b9eed5c7df43baf8bd29779702426)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamSummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamSummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203091116298612-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T11%3A19%3A48Z&sr=b&sp=r&sig=FyU1eyDwKucYkL2vLZU4BdMaq2gK%2B7GylzjWwz7Dzdk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 11:32 UTC, mankadnandan approved these changes

2022-03-11 15:46 UTC, isvargasmsft commented on api-reference/beta/api/team-get.md
> +    "guestsCount": 4,
Please apply this same change to the **create** method of this resource.

2022-03-11 15:53 UTC, opbld30 commented
Docs Build status updates of commit _[1351b92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1351b92b454156bf2307cf6297984339ae684792)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamSummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamSummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203111551048405-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T15%3A53%3A07Z&sr=b&sp=r&sig=9SQUDS65QqQw0JYzqCgTNFYqenPYXakY2XsJF%2BnLi0U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 15:55 UTC, isvargasmsft commented on api-reference/beta/resources/team.md
> +|summary|[teamSummary](teamSummary.md)| The summary of the team. |
Please add this new property to the json representation section in this document.

2022-03-11 15:56 UTC, isvargasmsft requested changes
Please add the new property to the JSON representation section of the parent resorce topic.

2022-03-14 05:54 UTC, opbld31 commented
Docs Build status updates of commit _[e618919](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e61891903c07f4800c8371a51d829516dd442bfe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamSummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamSummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203140552448549-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-14T05%3A54%3A58Z&sr=b&sp=r&sig=APHbrkkIZ1zEj2Xceb%2Bh6wAE9FWWyBwpylFfVMchScM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-14 15:00 UTC, isvargasmsft approved these changes

2022-03-15 02:27 UTC, opbld30 commented
Docs Build status updates of commit _[24feee9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24feee952e47cf33c7e95562d48098e5a2a4a180)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203150225174925-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T02%3A27%3A22Z&sr=b&sp=r&sig=vy1PUTepxk8%2BamhAe%2BTlIJHfCt7yDT3UMoZpk5FaUKQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-15 02:28 UTC, Lauragra approved these changes

2022-03-15 02:29 UTC, opbld31 commented
Docs Build status updates of commit _[109fb46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/109fb461b1eb89a98b9e37d6a675bc5ddb8c674b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203150227111222-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T02%3A29%3A43Z&sr=b&sp=r&sig=zvBv48erK7KUbAIs4RzuzgPvHY%2B%2ByMVnDFbYHPkzueg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-15 02:31 UTC, opbld32 commented
Docs Build status updates of commit _[5914304](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5914304da1f37f2594605c7397599b535fcd34d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203150227332170-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T02%3A31%3A54Z&sr=b&sp=r&sig=WrU8psTInK1xgE6o9iqnfA%2BU7ej%2F%2Fpxdrk5YUdJ5X1I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-15 02:37 UTC, opbld33 commented
Docs Build status updates of commit _[5511bbe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5511bbe97a1ac2f00f0664ade93e4455a3659808)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[api-reference/beta/resources/teamsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/api-reference/beta/resources/teamsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-beta&branch=pr-en-us-15810) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/membershipsummary-documentation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203150227555178-15810%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T02%3A37%3A13Z&sr=b&sp=r&sig=bqkF1hAA90tpMkCdXsVqDA9Y7U%2BAuLA4KdQz46tKImU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-15 02:54 UTC, merged