Amharris/updating graph docs
microsoftgraph/microsoft-graph-docs pull request #15821
Opened 2022-02-11 01:37 UTC by amharris1331

Updating the Graph documentation for the Delegated Admin API's and objects.

2022-02-11 01:39 UTC, opbld32 commented
Docs Build status updates of commit _[b51870a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b51870a7d5409ca4f32e6d6fc2412203351c1de6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-9435ba52f311ba244f7739f5a7e493a0-f2d6fd40)
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-eb6c54d465b2feb2e536fa2e41158cad-f2d6fd40)
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-eed8c76466ea8d6307a0457d95117753-f2d6fd40)
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-cd683a6c9e0839f6c3dc06be76c84330-f2d6fd40)
[api-reference/beta/api/delegatedadmincustomer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadmincustomer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-75c98a391494d154c3f12664efa7e751-f2d6fd40)
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadmincustomer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-0b68982df911c64c94acce85d4b3167a-f2d6fd40)
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-3c5cd3b954084dbcb2f9a84b2626b2f1-f2d6fd40)
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-0fd50f0e1f2ffe37e3550adbc6819052-f2d6fd40)
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-c3e51071f1066ad269214725632f9d04-f2d6fd40)
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-bc7c93f67dbfad348e23029a1cf78600-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-596f9d17d1aa111417bf20250cf90a0f-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-e2bf35e60b2f02ca07d6528035d6bee1-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-ebbc07a0aa4808f586ae37120018eb4a-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-77b1a41884f9d92b7aaa1631ec04c1ed-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-11d2f758f9b63b193900fd2aba1494fe-f2d6fd40)
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-15821) (grap [...]

2022-02-11 03:47 UTC, ozhang22 requested changes
First stab at feedback

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +|Authorization|Bearer {token}. Required.|
If-Match header required here (and for all update/delete APIs)?

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +Namespace: microsoft.graph
Are we on the main microsoft.graph namespace? I thought we were in a namespace like microsoft.graph.tenantrelationships?

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +DELETE /tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments/{delegatedAdminAccessAssignmentId}
Can we check if it's tenantRelationship or tenantRelationships?

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "lastModifiedDateTime": "String (timestamp)"
From my recollection of seeing other Microsoft Graph documentations, we use an actual response here, not just providing the type values.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Do we need to expand on this and give which specific query parameters are supported?

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
The GET by ID call doesn't support OData query parameters? (but maybe $expand is supported). Same for all other GET by ID calls.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +|status|String|The status of the assignment. Optional.|
This isn't a string; I believe it should be an enum value. Similarly for all fields related to Status and Type.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +If successful, this method returns a `200 OK` response code and an updated [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object in the response body.
Not correct, this should return a 202 Accepted and a response header containing the location of the relationshipOperation object representing the access assignment change

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadmincustomer-delete.md
> +# Delete delegatedAdminCustomer
Do we have to document internal APIs? Partners will not use this API.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-list-operations.md
> +GET /tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/operations
This page is duplicative of delegatedadminoperation-list.md? And similarly for the access assignments and requests pages.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +DELETE /tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments/{delegatedAdminAccessAssignmentId}
Do we also need to use an example using the alternative way of using routes?

DELETE /tenantRelationship/delegatedAdminRelationships({delegatedAdminRelationshipId})/accessAssignments/({delegatedAdminAccessAssignmentId})?

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +[!INCLUDE [table-intro](../../includes/update-property-table-intro.md)]
In the request body, supply a JSON representation of the [delegatedAdminRelationship](../resources/delegatedAdminRelationship.md) object.

You can specify the following properties when creating a **delegatedAdminRelationship**.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +|endDateTime|DateTimeOffset|The date and time (ISO 8601) at which this relationship either terminated or expired, or in the case of an active relationship, the date and time at which it is *scheduled
Since the user can't change these fields do we even need to include these?

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +|accessDetails|[microsoft.partner.customerServiceAdministration.delegatedAdminAccessDetails](../resources/delegatedadminaccessdetails.md)|The access details of the relationship. Required.|
None of these are required in the PATCH call. And then again, if the relationship is not in the "created" status, they can't be updated anyway.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +Represents an assignment of access details (containing roles) to an access container (like a security group). Once it's active, the members of the access container get access to the roles specified i
```suggestion
Represents an assignment of access details (containing roles) to an access container (such as a security group). Once it is active, the members of the access container gain access to the roles specified in the access details.
```

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccesscontainer.md
> +|accessContainerType|String|The type of access container (e.g., security group) that will be assigned one or more roles approved for the associated relationship.|
Same thing here. I don't think any of these "Type" or "Status" fields are strings.

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminoperation.md
> +Represents a long running operation related to a Delegated Admin relationship.
```suggestion
Represents a long running operation related to a delegatedAdminRelationship.
```

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccessdetails.md
> +Represents access details for a delegated admin relationship and delegated admin access assignment.
Consistency between delegated admin and Delegated Admin

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
Needs to be sorted

2022-02-11 03:47 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationshipparticipant.md
> +|tenantId|String|The tenant ID of the participant in the relationship. Must be a valid tenant ID as in AAD.|
```suggestion
|tenantId|String|The tenant ID of the participant in the relationship. Must be a valid ID of a tenant in AAD.|
```

2022-02-14 18:41 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "lastModifiedDateTime": "String (timestamp)"
Might have to backtrack - some other documentations that I've seen follow this format. Let's leave it as is for now (but we still need to check the types of all of these fields)

2022-02-18 02:19 UTC, opbld34 commented
Docs Build status updates of commit _[8938a01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8938a018c7b4d9ce16326dc3dd8b4fa79a044afc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-9435ba52f311ba244f7739f5a7e493a0-46e5c8f6)
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-eb6c54d465b2feb2e536fa2e41158cad-46e5c8f6)
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-eed8c76466ea8d6307a0457d95117753-46e5c8f6)
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-cd683a6c9e0839f6c3dc06be76c84330-46e5c8f6)
[api-reference/beta/api/delegatedadmincustomer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadmincustomer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-75c98a391494d154c3f12664efa7e751-46e5c8f6)
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadmincustomer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-0b68982df911c64c94acce85d4b3167a-46e5c8f6)
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-3c5cd3b954084dbcb2f9a84b2626b2f1-46e5c8f6)
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-0fd50f0e1f2ffe37e3550adbc6819052-46e5c8f6)
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-c3e51071f1066ad269214725632f9d04-46e5c8f6)
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminoperation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-bc7c93f67dbfad348e23029a1cf78600-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-596f9d17d1aa111417bf20250cf90a0f-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-e2bf35e60b2f02ca07d6528035d6bee1-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-ebbc07a0aa4808f586ae37120018eb4a-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-77b1a41884f9d92b7aaa1631ec04c1ed-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-15821) (graph-rest-beta) | [Details](#user-content-11d2f758f9b63b193900fd2aba1494fe-46e5c8f6)
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/UpdatingGraphDocs/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-15821) (grap [...]

2022-02-23 21:53 UTC, dkershaw10 commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +  "@odata.type": "Collection(microsoft.partner.customerServiceAdministration.delegatedAdminAccessAssignment)"
There are a number of references in files to internal namespaces.  Make sure this references public namespaces or API doctor will complain

2022-03-12 02:15 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +Namespace: microsoft.graph
I believe so.  I took a look at other defined classes and they all said microsoft.graph as the namespace.

2022-03-31 03:13 UTC, merged