Ttomi/microsoft application data access settings beta
microsoftgraph/microsoft-graph-docs pull request #15835
Opened 2022-02-14 10:02 UTC by ttomi

2022-02-14 10:08 UTC, opbld31 commented
Docs Build status updates of commit _[cea5c84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cea5c8428659a346e2a70caa41f13c05ab9bec43)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e547f7fa)

<a id="e547f7fa"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141002592058-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T10%3A08%3A13Z&sr=b&sp=r&sig=ZhgsssTml%2FCh36Ii%2BNFNOuYD4KM3krl20Y40mAtFYjI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 12:43 UTC, opbld33 commented
Docs Build status updates of commit _[3aa22f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3aa22f78b54e6c90275ec6be482bc2e5350483ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141241234656-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T12%3A43%3A20Z&sr=b&sp=r&sig=urGYXtbU%2BvfFY0mfDvmRsh5wmEiRiS35TekPkEJ4S9w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 12:58 UTC, opbld32 commented
Docs Build status updates of commit _[8072db7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8072db7f2adc1dd281556bc4ecac27dd00fbee0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141256218954-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T12%3A58%3A39Z&sr=b&sp=r&sig=ecV9ZcNzVzvE51%2BBHJo9XyNG4%2FVFYK9KYqsUwIfHvRI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 08:02 UTC, opbld34 commented
Docs Build status updates of commit _[d6e6756](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6e6756f076319e94d179c853f0bafb3ea9e5a3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150759232435-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T08%3A02%3A34Z&sr=b&sp=r&sig=ja%2Bj7Ax1%2FpzC3cn659aNGIVTXXIuqLY%2FFaGNYDMW5Kg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 08:34 UTC, opbld30 commented
Docs Build status updates of commit _[6e55d2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e55d2b1507689dbc75d78a34a327dd7acc1b267)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150832139815-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T08%3A34%3A26Z&sr=b&sp=r&sig=2nMW4QJqU7oDgslreE83wAJKWtsVRtm6bt3L6mRZVuM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 08:47 UTC, opbld30 commented
Docs Build status updates of commit _[14207de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14207de9cc111d6ddff1419ac4b8f87a0e98b8a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150845038695-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T08%3A47%3A15Z&sr=b&sp=r&sig=ZxDOqy8nRmSFPBr7kHkgTAgDh58Fanadgs8Slrp4Pf4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 09:51 UTC, angelgolfer-ms commented on api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md
> +  "@odata.type": "microsoft.graph.microsoftApplicationDataAccessSetting"
@ttomi , does your metadata specify a resource named microsoftApplicationDataAccessSetting or microsoftApplicationDataAccessSettings, or both?
Your PR includes only a resource topic for the latter, which identifies a JSON representation for microsoftApplicationDataAccessSettings. API Doctor knows only microsoftApplicationDataAccessSettings.

If there is indeed a microsoftApplicationDataAccessSetting, you'd need to create a separate resource topic with a JSON representation section for API Doctor to know about it too.

2022-02-15 09:52 UTC, opbld33 commented
Docs Build status updates of commit _[f51dc76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f51dc763423b0662f47d490cb56229dc12e9ac99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202150950209869-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T09%3A52%3A28Z&sr=b&sp=r&sig=dpGANd2UDAcS5oq9sJYqcdoazoIe%2BJ0VxQFvBARVVms%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 13:41 UTC, opbld30 commented
Docs Build status updates of commit _[54f120c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54f120c4d9b5d60ac478b0a1a988b597b3eee211)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/microsoftapplicationdataaccesssetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssetting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssetting?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) | [Details](#user-content-5edabff1a08d8dcbf0bfdfa03241b2b1-f6fd59b0)
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

<a id="5edabff1a08d8dcbf0bfdfa03241b2b1-f6fd59b0"></a>
### [api-reference/beta/resources/microsoftapplicationdataaccesssetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssetting.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/microsoftapplicationdataaccesssetting-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202151338514860-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T13%3A41%3A01Z&sr=b&sp=r&sig=%2Fws%2BMZP4WyDBOhpY5yHflw3OfjNyyAYcd1%2BqQF6Ws30%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 14:43 UTC, opbld33 commented
Docs Build status updates of commit _[b9ec839](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9ec8390b3f44b599aa72374f4a410b46d5d4847)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssetting-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssetting?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202151441195371-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T14%3A43%3A31Z&sr=b&sp=r&sig=lGD51ealLLVW5GjsVDaW6smYfD4txlWDg%2F0KNrVTVb0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 08:36 UTC, opbld33 commented
Docs Build status updates of commit _[4d59c43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d59c43ef533dc9e65d3ec7fd0f8e267169728a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssetting-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssetting?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202160833323096-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T08%3A36%3A43Z&sr=b&sp=r&sig=azvtSUvF4Z1P7Iz1weO%2BA7jXxUXnBkk0cpGGDKD7fyQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 13:54 UTC, ttomi commented on api-reference/beta/resources/microsoftapplicationdataaccesssetting.md
> +**TODO: Add Description**
Remove comment

2022-02-23 13:59 UTC, ttomi commented on api-reference/beta/api/organizationsettings-get.md
> +<!-- todo: mention microsoftApplicationDataAccessSetting -->
Do it

2022-02-24 13:36 UTC, opbld30 commented
Docs Build status updates of commit _[6cf3941](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cf3941e8f673e89173e244ecdbf00c63e1c730b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202241334435751-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T13%3A36%3A43Z&sr=b&sp=r&sig=6Dx8zrey5k9JNF9wx4hqc7NGXYi8WRyjY0VdIixkC3I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-28 12:55 UTC, opbld30 commented
Docs Build status updates of commit _[98563fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98563fde31858f96a884d11b3ec2cb6c623c6cc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202281253335593-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T12%3A55%3A32Z&sr=b&sp=r&sig=XqyXKjRVJ2RcXIA1%2Fjc9go%2BfFy2RdQ0e4piHdfezxtM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 06:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/microsoftapplicationdataaccesssettings.md
> +|isEnabledForAllMicrosoftApplications|Boolean|When set to 'true', all users in the organization are allowed to access M365 data using any Microsoft application (not restricted to Microsoft 365 applic
Line 29:
Please correct me if I've misunderstood (below). Can we tweak the description and say:

"When set to `true`, all users in the organization can access in a Microsoft app any Microsoft 365 data that the user has been authorized to access. The Microsoft app can be a Microsoft 365 app (e.g., Excel, Outlook) or non-Microsoft 365 app (e.g., Edge). The default is `true`. 

It is possible to disable this access for a subset of users in an Azure AD security group, by specifying the group in the **disabledForGroup** property.

When set to `false`, users can access authorized Microsoft 365 data only in a Microsoft 365 app."

2022-03-01 06:18 UTC, angelgolfer-ms commented on api-reference/beta/resources/microsoftapplicationdataaccesssettings.md
> +
After line 17 in a separate paragraph, we can add one more sentence to clarify the Microsoft 365 data, like this:

"Examples of Microsoft 365 data in an organization include Word, Excel, and PowerPoint documents, Outlook messages, and Teams meeting recordings, which the user has been properly authorized to access."

I see in the api.md file and in our email communications, you use the term "compliance boundary". I think customers are not clear what that means, so I am refraining from using it in the docs.

2022-03-03 04:18 UTC, ttomi commented on api-reference/beta/resources/microsoftapplicationdataaccesssettings.md
> +
Added.

2022-03-03 04:20 UTC, opbld34 commented
Docs Build status updates of commit _[47ae41c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47ae41c634f80d83a63e8d56ca00b8c2227c5ccc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030417465513-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A20%3A19Z&sr=b&sp=r&sig=s3J7rNFYfB2%2Fkfz4eniGw3Dxv%2Blh2EGnixIR7e3kbzo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 04:43 UTC, opbld30 commented
Docs Build status updates of commit _[7e3e17f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e3e17fe8595c30869c446ac993ffebfe6555ed2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203030440068029-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T04%3A43%3A25Z&sr=b&sp=r&sig=xCiJtqxHazAh6IceCGoW3E6cpVHX3OTJIV2XhW1s8XA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 08:17 UTC, opbld34 commented
Docs Build status updates of commit _[2e8c73d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e8c73d08468283b0a010cb8c73da5fde8ffda07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040815152825-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T08%3A17%3A19Z&sr=b&sp=r&sig=GT5TkOPn6TEcWSoYXJfhuaoph4lZGMC0Soxb%2FioSrk8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 10:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/microsoftapplicationdataaccesssettings.md
> +|[List microsoftApplicationDataAccessSettings](../api/organizationsettings-list-microsoftapplicationdataaccess.md)|[microsoftApplicationDataAccessSettings](microsoftapplicationdataaccesssettings.md)|
Line 24:
FYI I am updating the description to be more consistent to that in the parent resource topic,:
Get the _settings_ in a [microsoftApplicationDataAccessSettings](microsoftapplicationdataaccesssettings.md) object that specify access from Microsoft applications to Microsoft 365 user data in an organization.

2022-03-04 10:29 UTC, angelgolfer-ms commented on api-reference/beta/resources/microsoftapplicationdataaccesssettings.md
> +|[Update microsoftApplicationDataAccessSettings](../api/microsoftapplicationdataaccesssettings-update.md)|[microsoftApplicationDataAccessSettings](microsoftapplicationdataaccesssettings.md)|Update th
Line 25:
I'm also updating the description to 👍 Update the settings in a [microsoftApplicationDataAccessSettings](microsoftapplicationdataaccesssettings.md) object that specify access from Microsoft applications to Microsoft 365 user data in an organization.|

2022-03-04 10:31 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationsettings.md
> +| [List microsoftApplicationDataAccessSettings](../api/organizationsettings-list-microsoftapplicationdataaccess.md) | [microsoftApplicationDataAccessSettings](microsoftapplicationdataaccesssettings.m
Line 25:
I made the description closer to how we're describing the "list" operation:
"Get the properties of a [microsoftApplicationDataAccessSettings](microsoftapplicationdataaccesssettings.md) object that specify access from Microsoft applications to Microsoft 365 user data in an organization."

2022-03-04 10:32 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationsettings.md
> +|microsoftApplicationDataAccessSettings|[microsoftApplicationDataAccessSettings](../resources/microsoftapplicationdataaccesssettings.md)| Contains the properties that are configured by an administrat
Line 38:
FYI I'm updating the description as:
"Contains the properties that are configured by an administrator to specify access from Microsoft applications to Microsoft 365 data belonging to users in an organization. [List microsoftApplicationDataAccessSettings](../api/organizationsettings-list-microsoftapplicationdataaccess.md) returns the _settings_ that specify the access."

2022-03-04 10:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/microsoftapplicationdataaccesssettings.md
> +|disabledForGroup|String|The ID of security AAD group whose members will _not_ be allowed to access M365 data using Microsoft applications not part of Microsoft 365. <br> This is only applicable if t
Lines 31, 32:
FYI I am changing "AAD" to the proper branded name "Azure Active Directory (Azure AD)" in first reference in the topic, "Azure AD" in subsequent mentions.
I am changing "M365" to "Microsoft 365" for proper branding.

2022-03-04 10:43 UTC, opbld33 commented
Docs Build status updates of commit _[ff67b59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff67b592c59bc4dee4e8edf6045dcfe20acf5760)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203041041187425-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T10%3A43%3A26Z&sr=b&sp=r&sig=CZUdVOHgycnJsLWFxw7jBjNxRiPoeqcphJS9n0Rsj5A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 10:46 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-get.md
>  ## Permissions
Line 28:
@ttomi , should the delegated permissions be  Organization.Read.All, Organization.ReadWrite.All?

2022-03-04 11:05 UTC, ttomi commented on api-reference/beta/api/organizationsettings-get.md
>  ## Permissions
I don't think so. I thought to make it just as `insightsSettings` and not return this with `microsoftApplicationDataAccessSettings`, but have them use `list microsoftApplicationDataAccessSettings` and in its file mention the Organization.* permission.

Would it make sense to mention the permissions here as well even though they shouldn't be required for GET organizationSettings?

2022-03-04 11:09 UTC, angelgolfer-ms requested changes
Hi @ttomi ,
FYI I made some updates to your PR directly to keep the descriptions consistent in various tables.
I have 2 remaining questions:
(a) The permissions for organizationsettings-get.md, please see my comment there.
(b) Exposing the microsoftApplicationDataAccessSettings entity and the "list" and "update" operations in the TOC. Do you think in the beta reference, under "People and workplace intelligence" is appropriate? 
If you do, then you should please update social-overview.md in the beta reference, and social-intel-concept-overview.md in the conceptual section.
And meanwhile, I'll think of the TOC label to use.

2022-03-04 12:33 UTC, opbld32 commented
Docs Build status updates of commit _[38b1762](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38b1762f198c471da4559926fc3a642458da07d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203041231414870-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T12%3A33%3A42Z&sr=b&sp=r&sig=pY8qEsDyFp%2B5rd2z3JP8q0I%2B6yOtl2k4HMnKq0qzLxA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 12:41 UTC, ttomi commented
> Hi @ttomi , FYI I made some updates to your PR directly to keep the descriptions consistent in various tables. I have 2 remaining questions: (a) The permissions for organizationsettings-get.md, please see my comment there. (b) Exposing the microsoftApplicationDataAccessSettings entity and the "list" and "update" operations in the TOC. Do you think in the beta reference, under "People and workplace intelligence" is appropriate? If you do, then you should please update social-overview.md in the beta reference, and social-intel-concept-overview.md in the conceptual section. And meanwhile, I'll think of the TOC label to use.

Added TOC entries, feel free to update the label with whatever sounds better. Have 2 commits and am only certain about adding the TOC entries to "Organization control (preview)", not so much about People and workplace intelligence. @einarmr what do you think?

2022-03-04 23:11 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-get.md
>  ## Permissions
Oh, perhaps you mistook my question - my comment has nothing to do with line 20 8-)

My comment does apply to LINE 28 in the "Permission" section. But GitHub didn't allow me to put a comment in its vicinity (I guess because neither of us has touched / modified that part of the topic). So yes, my question is, in the "Permission" section, permissions table, should the second row delegated permissions be changed from User.Read, User.Read.All to Organization.Read.All, Organization.ReadWrite.All?

2022-03-08 13:45 UTC, ttomi commented on api-reference/beta/api/organizationsettings-get.md
>  ## Permissions
Yes, I understood. I didn't add them here, because as said in this edited portion, this action does not actually return [microsoftApplicationDataAccessSettings](../resources/microsoftApplicationDataAccessSettings.md) so I left the permissions unchanged as the data returned by this specific action (GET|PATCH https://graph.microsoft.com/beta/organization/{organizationId}/settings) is unchanged and as such should continue working with existing permissions.

Only [microsoftApplicationDataAccessSettings](../resources/microsoftApplicationDataAccessSettings.md) operations require Organization permissions and in their respective files those permissions are listed.

2022-03-09 12:01 UTC, opbld33 commented
Docs Build status updates of commit _[4c207c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c207c5d4ea42d3659fccf90360ec44945eed176)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203091159270023-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T12%3A01%3A30Z&sr=b&sp=r&sig=hThqeJOh%2FsGc63ROaZXEPKfy8c2hCS81f82a4BPoyI0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 11:52 UTC, opbld33 commented
Docs Build status updates of commit _[4b2f8ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b2f8ce73b786e6dfe387050bc586a8f4fdcd2d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203111150270796-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T11%3A52%3A27Z&sr=b&sp=r&sig=GxEZOP9Kz8zIQluv5AxquZDaX43j2ojJmEZbx3HKkFo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 09:29 UTC, opbld30 commented
Docs Build status updates of commit _[e95749a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e95749ac03174eb43e36a06829264ca135fd781e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203160927193868-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T09%3A29%3A19Z&sr=b&sp=r&sig=U%2FogvOLi06HwIzEWir9lPTRtzTk3AGr5iue4cn2LKRA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 10:39 UTC, opbld30 commented
Docs Build status updates of commit _[23c4554](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23c4554a02e1270b67c35fbaf3113669c0bbdc59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203241032147160-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T10%3A39%3A37Z&sr=b&sp=r&sig=A8rVasRsWoQDA9Y2M%2FedWzJZ6yucqYEOQlqLZ%2BGtpcE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 18:00 UTC, opbld32 commented
Docs Build status updates of commit _[8ddb902](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ddb902ec0de28dd46e4b74e9b6887683507e0d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291758462014-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T18%3A00%3A53Z&sr=b&sp=r&sig=sSEaKpMM3jiRt3cu4NqPwXskCdk2r4D9xV66oPWoU2A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 23:58 UTC, opbld33 commented
Docs Build status updates of commit _[7053238](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70532387b8a7ec1a4a1dd5e68ceedd694c52d525)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203292357069234-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T23%3A58%3A51Z&sr=b&sp=r&sig=ZhGEfmxKTf3Nr3DLR%2FyFzTxTr1xtIaEtWuxgf73oa8I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 00:03 UTC, opbld33 commented
Docs Build status updates of commit _[a423f08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a423f080f597c2ffa3665040a7d137f93e37ea6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203292359420415-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T00%3A03%3A08Z&sr=b&sp=r&sig=gsH4d5%2FRGMbGNcxgH6NS4uibCTT9aYjIDKuDNqa0Mwg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 00:05 UTC, opbld33 commented
Docs Build status updates of commit _[d71dbac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d71dbac3ee1f80210c0a1ab5ac7cfb0b3b33c1ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/microsoftapplicationdataaccesssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/api/organizationsettings-list-microsoftapplicationdataaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-microsoftapplicationdataaccess?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/microsoftapplicationdataaccesssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/microsoftapplicationdataaccesssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftapplicationdataaccesssettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftapplicationdataaccesssettings-update?view=graph-rest-beta&branch=pr-en-us-15835) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ttomi/microsoftApplicationDataAccessSettingsBeta/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203300002410109-15835%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T00%3A05%3A47Z&sr=b&sp=r&sig=kQQP9mD8WipD2r1LMPnExZww97byGKaKHIK2YcRLAqM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 01:26 UTC, Lauragra approved these changes

2022-03-31 03:12 UTC, merged