[MS Graph] [ELM] custom extensions for logic apps api
microsoftgraph/microsoft-graph-docs pull request #15869
Opened 2022-02-15 21:37 UTC by ajburnle

2022-02-15 21:39 UTC, opbld34 commented
Docs Build status updates of commit _[cace5db](https://github.com/ajburnle/microsoft-graph-docs/commits/cace5db7234797ff8cc5a41c3cdd18d7adb7b33a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-012d4b6d)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-012d4b6d)
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-df3a14524129ce647d58d1611955c900-012d4b6d)
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-012d4b6d"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-012d4b6d"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 32, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 33, Column 38**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 35, Column 31**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="df3a14524129ce647d58d1611955c900-012d4b6d"></a>
### [api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md)
 - **Line 27, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackagecustomextensionhandlerstatus.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202152137167956-15869%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T21%3A39%3A20Z&sr=b&sp=r&sig=4gLH7ORmABT9rAvY61a81yhom9DHEHJlSFdiflr8mPU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may  [...]

2022-02-15 21:46 UTC, opbld30 commented
Docs Build status updates of commit _[f1092e9](https://github.com/ajburnle/microsoft-graph-docs/commits/f1092e93213bed89ed056c41948521cec4aa00dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-e0501496)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-e0501496)
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-df3a14524129ce647d58d1611955c900-e0501496)
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-e0501496"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-e0501496"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 32, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 33, Column 38**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 35, Column 31**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="df3a14524129ce647d58d1611955c900-e0501496"></a>
### [api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md)
 - **Line 27, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackagecustomextensionhandlerstatus.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202152144207062-15869%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T21%3A46%3A10Z&sr=b&sp=r&sig=lnJKawcTp4iEMkyCDdPpc3%2FXAKozhe5AkjmpjR5ht3Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsof [...]

2022-02-15 21:52 UTC, opbld33 commented
Docs Build status updates of commit _[32e735b](https://github.com/ajburnle/microsoft-graph-docs/commits/32e735b4f41126e79ffb7e8b9ca53af2974343b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-1ba57099)
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-c02fbeed4cd81e8bb3f65ca6fc4a4ef6-1ba57099)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-1ba57099)
[api-reference/beta/resources/intune-deviceconfig-datatype.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/intune-deviceconfig-datatype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-datatype?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-1d30ce95302856de95c3786fddc6f555-1ba57099)
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-1ba57099"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="c02fbeed4cd81e8bb3f65ca6fc4a4ef6-1ba57099"></a>
### [api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'dataType enum type' is duplicated with other articles: 'beta/resources/accesspackagecustomextensionhandlerstatus.md(10,1), beta/resources/intune-deviceconfig-datatype.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-1ba57099"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 32, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invali [...]

2022-02-15 22:01 UTC, opbld30 commented
Docs Build status updates of commit _[f50f249](https://github.com/ajburnle/microsoft-graph-docs/commits/f50f2495d0e6f346f8fb06f7c9c4241d5e46ff9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-ac8f1afe)
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-c02fbeed4cd81e8bb3f65ca6fc4a4ef6-ac8f1afe)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-ac8f1afe)
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-ac8f1afe"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="c02fbeed4cd81e8bb3f65ca6fc4a4ef6-ac8f1afe"></a>
### [api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-ac8f1afe"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 32, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 33, Column 38**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 35, Column 31**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragep [...]

2022-02-15 22:03 UTC, opbld32 commented
Docs Build status updates of commit _[7118ca1](https://github.com/ajburnle/microsoft-graph-docs/commits/7118ca158fb2a6eec52cceb343c36ace166d09d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-1905353e)
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-c02fbeed4cd81e8bb3f65ca6fc4a4ef6-1905353e)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-1905353e)
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-1905353e"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="c02fbeed4cd81e8bb3f65ca6fc4a4ef6-1905353e"></a>
### [api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-1905353e"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 32, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 33, Column 38**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 35, Column 31**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragep [...]

2022-02-15 22:25 UTC, opbld30 commented
Docs Build status updates of commit _[5795775](https://github.com/ajburnle/microsoft-graph-docs/commits/5795775df0943e3b5cd216ee753ce6fa8cf947e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-b6de598b)
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-c02fbeed4cd81e8bb3f65ca6fc4a4ef6-b6de598b)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-b6de598b)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-b6de598b"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/customextensionhandler-post-customextension.md'.`````
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="c02fbeed4cd81e8bb3f65ca6fc4a4ef6-b6de598b"></a>
### [api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-b6de598b"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invali [...]

2022-02-15 22:34 UTC, opbld33 commented
Docs Build status updates of commit _[4889441](https://github.com/ajburnle/microsoft-graph-docs/commits/4889441385c20eecdf4c6ccb40e597371977fcf1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-28d483d1)
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-c02fbeed4cd81e8bb3f65ca6fc4a4ef6-28d483d1)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-28d483d1)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-28d483d1"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="c02fbeed4cd81e8bb3f65ca6fc4a4ef6-28d483d1"></a>
### [api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-28d483d1"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 32, Co [...]

2022-02-15 22:38 UTC, opbld31 commented
Docs Build status updates of commit _[55ad748](https://github.com/ajburnle/microsoft-graph-docs/commits/55ad74883022ff4f42190de5ca030b7fbdcf11d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-c99b8fa3)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-c99b8fa3)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |

<a id="f4ee4517d5e1322e5ba5d0a6499b98dc-c99b8fa3"></a>
### [api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md)
 - **Line 31, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````

<a id="fb384e0862a210c351bdeeaea86dd9cb-c99b8fa3"></a>
### [api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md)
 - **Line 32, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 33, Column 38**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/customextension.md'.`````
 - **Line 35, Column 31**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?br [...]

2022-02-15 23:24 UTC, opbld30 commented
Docs Build status updates of commit _[36b971d](https://github.com/ajburnle/microsoft-graph-docs/commits/36b971da2ae30e8774fc51ceb23ef376b08e542b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-2ec454e1)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-2ec454e1)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-15 23:31 UTC, opbld34 commented
Docs Build status updates of commit _[61240c2](https://github.com/ajburnle/microsoft-graph-docs/commits/61240c219e4d728159ccd33510ea696705918ba4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-ca5bd3e5)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggere [...]

2022-02-15 23:38 UTC, opbld31 commented
Docs Build status updates of commit _[d3c5486](https://github.com/ajburnle/microsoft-graph-docs/commits/d3c548693cb6e68e4ced7873fbdf06443b5447fb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-e516e639)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggere [...]

2022-02-15 23:45 UTC, opbld34 commented
Docs Build status updates of commit _[2d80104](https://github.com/ajburnle/microsoft-graph-docs/commits/2d80104ffac69c482d3c469045aab3afc8703cd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-16 00:13 UTC, markwahl-msft reviewed
Thanks, see comments

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-update.md
> +PATCH https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageCatalogs/{accessPackageCatalogId}/accessPackages/{accessPackageId}/accessPackageAssignmentPolicies/{access
also this URL looks wrong it shouldn't have a catalog or access package in it

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-update.md
> +        "resourceGroupName": "xiaojil",
see previous comments - reader may not know if this is significant to just a example

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/api/customextensionhandler-post-customextension.md
> +POST /identityGovernance/entitlementManagement/ accessPackageCatalogs/{catalogId}/customAccessPackageWorkflowExtensions
space in URL after /

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/api/customextensionhandler-post-customextension.md
> +        "resourceGroupName": "xiaojil",
as with previous

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/api/customextensionhandler-post-customextension.md
> +        "resourceGroupName": "xiaojil",
+

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +    "policyAssignmentType": "RequestBased",
is policyAssignmentType new? did we leave it out earlier?

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagecatalog.md
> +|customAccessPackageWorkflowExtension|[customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md) collection|Read-only.|
read only?

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagecatalog.md
> +|[Create customAccessPackageWorkflowExtension](../api/customextensionhandler-post-customextension.md)|[customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md)|Crea
is there a delete too?

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/azureadtokenauthentication.md
> +Defines an AAD application used for authenticating with custom access package workflow extension. Derived from [customExtensionAuthenticationConfiguration](../resources/customextensionauthenticationc
suggest spell out Azure AD

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/azureadtokenauthentication.md
> +|resourceId|String|Identification of Azure AD application used for authenticating external API.|
this is ambiguous - is this the application ID, the application object ID, or the service princnipal of the application ID?

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +|description|String|Description for customExtension. Read only.|
not sure this and displayname are read only

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/customextensionhandler.md
> +```
not sure why this is in red, newline missing maybe?

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/customextensionhandlerinstance.md
> +|customExtensionId|String|Identification of the custom extension triggered at this instance.|
can this be a MD reference to the type object so they know what it's an identifier for?

2022-02-16 00:13 UTC, markwahl-msft commented on api-reference/beta/resources/customextensionhandlerinstance.md
> +The customExtensionHandlerInstance resource is used to record each instance of custom extension running information and its result.
not sure what "running information and its result" means

2022-02-16 06:46 UTC, ajburnle commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +Deletes a [customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md) object.
@xiaojil-msft Do you know the answer?

2022-02-16 06:48 UTC, opbld30 commented
Docs Build status updates of commit _[0fd67fc](https://github.com/ajburnle/microsoft-graph-docs/commits/0fd67fc1e37c6e4fe868f0ef5afabda15c27fdcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-16 06:53 UTC, opbld34 commented
Docs Build status updates of commit _[05a63c8](https://github.com/ajburnle/microsoft-graph-docs/commits/05a63c8b52a1252e7dc2f5d5341c5941f4189481)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-16 06:56 UTC, opbld32 commented
Docs Build status updates of commit _[111b787](https://github.com/ajburnle/microsoft-graph-docs/commits/111b787a9312f7e680870435483d35e7d46ac4aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-16 07:05 UTC, opbld30 commented
Docs Build status updates of commit _[7fff888](https://github.com/ajburnle/microsoft-graph-docs/commits/7fff88822c4a0ed40c5be2ab3ea639153a469b90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-16 07:15 UTC, opbld34 commented
Docs Build status updates of commit _[77c9e3d](https://github.com/ajburnle/microsoft-graph-docs/commits/77c9e3d8ca9888e5604c5fa5f482b3d06864d003)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-17 07:33 UTC, opbld33 commented
Docs Build status updates of commit _[916515f](https://github.com/ajburnle/microsoft-graph-docs/commits/916515f9074630940afded6c9fdda68d8a9f5334)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-17 19:00 UTC, ajburnle commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +DELETE /identityGovernance/entitlementManagement/accessPackageCatalogs/{catalogId}/customAccessPackageWorkflowExtensions/{customExtensionId}
```suggestion
DELETE /identityGovernance/entitlementManagement/accessPackageCatalogs/{catalogId}/customAccessPackageWorkflowExtensions/{customExtensionId}
```

2022-02-17 23:06 UTC, xiaojil-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +DELETE /identityGovernance/entitlementManagement/ accessPackageCatalogs/{catalogId}/customAccessPackageWorkflowExtensions/{customExtensionId}
Yeah, @ajburnle could you remove the extra space?

2022-02-17 23:51 UTC, xiaojil-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +Deletes a [customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md) object.
Yeah, we have a validation for deletion. The error will be "The custom extension: {displayname} cannot be deleted because there are policies associated with it."

2022-02-18 00:31 UTC, xiaojil-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +    "policyAssignmentType": "RequestBased",
@ajburnle please remove this line.

2022-02-18 00:42 UTC, xiaojil-msft commented on api-reference/beta/api/customextensionhandler-post-customextension.md
> +title: "Create customAccessPackageWorkflowExtension"
The doc link doesn't seem right, should it be `api-reference/beta/api/customaccesspackageworkflowextension-create.md`?

2022-02-18 00:44 UTC, xiaojil-msft commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +|customExtensionHandlerInstances|[customExtensionHandlerInstance](../resources/customextensionhandlerinstance.md) collection|Custom extension handler instance collection within the assignment request
This is readonly

2022-02-18 01:03 UTC, xiaojil-msft commented on api-reference/beta/resources/azureadtokenauthentication.md
> +|resourceId|String|Identification of Azure AD application used for authenticating external API.|
Azure AD application ID

2022-02-18 01:07 UTC, xiaojil-msft commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +|description|String|Description for customExtension. Read only.|
We don't have read-only, and please update to `Description for customAccessPackageWorkflowExtension`

2022-02-18 01:08 UTC, xiaojil-msft commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +|displayName|String|Display name for customExtension. Read only.|
Same here, no read-only, and update to customAccessPackageWorkflowExtension.

2022-02-18 01:08 UTC, xiaojil-msft commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +|id|String|Identification for customExtension.|
Id is read-only. And please also update to `customAccessPackageWorkflowExtension`.

2022-02-18 01:18 UTC, xiaojil-msft commented on api-reference/beta/resources/customextensionauthenticationconfiguration.md
> +Abstract base type used for authenticationConfiguration property of custom access package workflow extension. Derived from [azureAdTokenAuthentication](../resources/azureadtokenauthentication.md).
Should be derived class: `azureAdTokenAuthentication`. As `azureAdTokenAuthentication` is derived from `customExtensionAuthenticationConfiguration`.

2022-02-18 01:28 UTC, xiaojil-msft commented on api-reference/beta/resources/customextensionhandler.md
> +```
I guess a close curly bracket is missing

2022-02-18 01:39 UTC, xiaojil-msft commented on api-reference/beta/resources/customextensionhandlerinstance.md
> +The customExtensionHandlerInstance resource is used to record each instance of custom extension running information and its result.
It is for every time running customAccessPackageWorkflowExtension at assignmentRequest as a new instance, recording the result and other information in this property. @markwahl-msft can you help on rephrasing?

2022-02-22 18:46 UTC, markwahl-msft commented on api-reference/beta/resources/customextensionhandlerinstance.md
> +The customExtensionHandlerInstance resource is used to record each instance of custom extension running information and its result.
How about
The customExtensionHandlerInstance resource is used to record the status of an instance of a custom extension being run on a request.

2022-02-22 20:02 UTC, FaithOmbongi requested changes
Thank you @ajburnle for your work on this PR. I've flagged a few issues and requested changes including the following:
- Please ensure that the assigned author has completed the Get started steps to link their accounts and join required orgs + their name is included in the [Microsoft Graph contacts list](https://aka.ms/graphapicontacts).
- File name fixes following the official file name pattern (please see the CDK):
    - customaccesspackageworkflowextension-list.md => accesspackagecatalog-list-customaccesspackageworkflowextensions.md
    - customextensionhandler-post-customextension.md => accesspackagecatalog-post-customaccesspackageworkflowextensions.md
- Missing customcalloutextension.md file for the customCalloutExtension entity/abstract type. This is the upstream resource for which we have the following downstream types: customExtensionAuthenticationConfiguration, customExtensionClientConfiguration, and customExtensionEndpointConfiguration.
- A plus to have - an example that adds a collection of customExtensionHandlerInstances to an [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentrequests?view=graph-rest-beta).
- You're missing two enums in the enums.md: **accessPackageCustomExtensionHandlerStatus** and **accessPackageCustomExtensionStage**.
- Some of the changelog records seem off. Let me re-review it and verify if this is a Graph Studio bug.

2022-02-22 20:24 UTC, xiaojil-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +Deletes a [customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md) object.
The method should link to `PUT accessPackageAssignmentPolicy`

2022-02-22 20:30 UTC, xiaojil-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-update.md
> +|authenticationConfiguration|microsoft.graph.customExtensionAuthenticationConfiguration|Configuration for securing the API call. For example, using OAuth client-credentials.|
Yes, we should update the "displayName" and "description" description to "customAccessPackageWorkflowExtension"

2022-02-22 20:32 UTC, xiaojil-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-update.md
> +        "resourceGroupName": "xiaojil",
We can replace it by "resourceGroupName"

2022-02-22 21:08 UTC, currenmehta commented on api-reference/beta/api/customaccesspackageworkflowextension-update.md
> +|authenticationConfiguration|microsoft.graph.customExtensionAuthenticationConfiguration|Configuration for securing the API call. For example, using OAuth client-credentials.|
@xiaojil-msft  can you confirm this?

2022-02-22 21:09 UTC, currenmehta commented on api-reference/beta/api/customextensionhandler-post-customextension.md
> +---
@xiaojil-msft

2022-02-22 21:25 UTC, currenmehta commented on api-reference/beta/api/accesspackageassignmentrequest-get.md
> +}
+1.

2022-02-22 21:31 UTC, currenmehta commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +DELETE /identityGovernance/entitlementManagement/ accessPackageCatalogs/{catalogId}/customAccessPackageWorkflowExtensions/{customExtensionId}
New change is correct.

2022-02-23 14:59 UTC, opbld31 commented
Docs Build status updates of commit _[bca4277](https://github.com/ajburnle/microsoft-graph-docs/commits/bca42772ce69691f5641c6ef8f86520414cb9dee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggerendpointconfiguration.md) | :white_check_mark:Succ [...]

2022-02-23 16:03 UTC, opbld34 commented
Docs Build status updates of commit _[19cf60f](https://github.com/ajburnle/microsoft-graph-docs/commits/19cf60ff230170bfb5f2859ef6496942d3c70244)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-fb2c257d)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggere [...]

2022-02-23 16:06 UTC, opbld32 commented
Docs Build status updates of commit _[19cf60f](https://github.com/ajburnle/microsoft-graph-docs/commits/19cf60ff230170bfb5f2859ef6496942d3c70244)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-da15cc2b)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/logicapptriggere [...]

2022-02-23 16:08 UTC, opbld31 commented
Docs Build status updates of commit _[5ba991c](https://github.com/ajburnle/microsoft-graph-docs/commits/5ba991c60d45918eedfbe6eb280a1daef4e43df0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-fe06bee5)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-fe06bee5)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:10 UTC, opbld32 commented
Docs Build status updates of commit _[bab6589](https://github.com/ajburnle/microsoft-graph-docs/commits/bab6589a49740411accf7d370867434b743f0663)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-3de40a3d)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-3de40a3d)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:12 UTC, opbld31 commented
Docs Build status updates of commit _[57464ad](https://github.com/ajburnle/microsoft-graph-docs/commits/57464adb3bb34b936240caf8bf3534fb3c15282b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-1a1c1327)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-1a1c1327)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:14 UTC, opbld32 commented
Docs Build status updates of commit _[c6b95c3](https://github.com/ajburnle/microsoft-graph-docs/commits/c6b95c349a80a74e5d716b2095d47737a2d26f2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-a352bb31)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-a352bb31)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:16 UTC, opbld34 commented
Docs Build status updates of commit _[863ca31](https://github.com/ajburnle/microsoft-graph-docs/commits/863ca31f02c97dd0697a39eb1c47fa1b64683d23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-131923f5)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-131923f5)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:22 UTC, opbld32 commented
Docs Build status updates of commit _[db3fb04](https://github.com/ajburnle/microsoft-graph-docs/commits/db3fb042952d57f5a560f6ea3e53660ffba42dc1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-770ded36)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-770ded36)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:24 UTC, opbld30 commented
Docs Build status updates of commit _[769eb14](https://github.com/ajburnle/microsoft-graph-docs/commits/769eb14712d411dd95df3a801eef1bc75b901ee1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-46305e72)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-46305e72)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:26 UTC, opbld33 commented
Docs Build status updates of commit _[3d3fc12](https://github.com/ajburnle/microsoft-graph-docs/commits/3d3fc125b9d3c6b490acdb62eed67b55bfefaff9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-69bc920a)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-69bc920a)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:30 UTC, opbld33 commented
Docs Build status updates of commit _[a56c3e5](https://github.com/ajburnle/microsoft-graph-docs/commits/a56c3e53b4a32fa257ef7e9597b6bf5a63677a6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-8a0c5467)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-8a0c5467)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 16:52 UTC, opbld30 commented
Docs Build status updates of commit _[a683947](https://github.com/ajburnle/microsoft-graph-docs/commits/a683947723a9e5f2e57012fcda2b86314d8dc206)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-6257556e)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-6257556e)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 17:13 UTC, opbld33 commented
Docs Build status updates of commit _[2dca26a](https://github.com/ajburnle/microsoft-graph-docs/commits/2dca26a62ca386cdcd4648000e2f0ef1fda7e546)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-f4ee4517d5e1322e5ba5d0a6499b98dc-5125b635)
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-5125b635)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-list.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-list?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customextensionhandler-post-customextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customextensionhandler-post-customextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customextensionhandler-post-customextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accessPackageCustomExtensionStage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accessPackageCustomExtensionStage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionstage?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecustomextensionhandlerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecustomextensionhandlerstatus?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-custom [...]

2022-02-23 20:28 UTC, opbld31 commented
Docs Build status updates of commit _[2704c4e](https://github.com/ajburnle/microsoft-graph-docs/commits/2704c4e8dd0163b4ce238b965f94f550867057db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-fb384e0862a210c351bdeeaea86dd9cb-409128e2)
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-7165459ccbecdb1ba2a137c556b0bbf9-409128e2)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-409128e2)
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/logicapptriggerendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/ap [...]

2022-02-23 21:10 UTC, opbld34 commented
Docs Build status updates of commit _[b6c93fc](https://github.com/ajburnle/microsoft-graph-docs/commits/b6c93fc2a2140490bacc164021030f72f2946cc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/enums.md) | :white_check [...]

2022-02-23 22:41 UTC, xiaojil-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +    "policyAssignmentType": "RequestBased",
Policy to add customExtensionHandlers:
`POST 
https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentPolicies
Content-type: application/json

{
    "displayName": "policy with custom access package workflow extension",
    "description": "Run specified custom access package workflow extension at different stages.",
    "accessPackageId": "ba5807c7-2aa9-4c8a-907e-4a17ee587500",
    "expiration": {
        "type": "afterDuration",
        "duration": "P365D"
    },
    "requestApprovalSettings": null,
    "requestorSettings": {
        "acceptRequests": true,
        "scopeType": "AllExistingDirectorySubjects",
	"allowedRequestors": []
    },
    "accessReviewSettings": null,
    "customExtensionHandlers": [
        {
            "stage": "assignmentRequestCreated",
            "customExtension": {
                "id": "219f57b6-7983-45a1-be01-2c228b7a43f8"
            }
        },
        {
            "stage": "assignmentRequestGranted",
            "customExtension": {
                "id": "219f57b6-7983-45a1-be01-2c228b7a43f8"
            }
        }
    ]
}
`

2022-02-23 22:49 UTC, xiaojil-msft commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +Deletes a [customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md) object.
Sample of removing the linked policy:
PUT https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentPolicies/4540a08f-8ab5-43f6-a923-015275799197
Content-Type: application/json

{
    "id": "4540a08f-8ab5-43f6-a923-015275799197",
    "displayName": "policy with custom access package workflow extension",
    "description": "Run specified custom access package workflow extension at different stages.",
    "accessPackageId": "ba5807c7-2aa9-4c8a-907e-4a17ee587500",
    "expiration": {
        "type": "afterDuration",
        "duration": "P365D"
    },
    "requestApprovalSettings": null,
    "requestorSettings": {
        "acceptRequests": true,
        "scopeType": "AllExistingDirectorySubjects",
        "allowedRequestors": []
    },
    "accessReviewSettings": null,
    "customExtensionHandlers": []
}

2022-02-23 23:06 UTC, xiaojil-msft commented on api-reference/beta/resources/customextensionhandler.md
> +None.
And can you add the sample on how to request this resource either in this page or add a section in accessPackageAssignmentPolicy-get.md
Request:
GET /identityGovernance/entitlementManagement/accessPackageAssignmentPolicies/{id}?$expand=customExtensionHandlers($expand=customExtension)

Response:
HTTP/1.1 200 OK
Content-type: application/json

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/entitlementManagement/accessPackageAssignmentPolicies(customExtensionHandlers(customExtension()))/$entity",
    "id": "4540a08f-8ab5-43f6-a923-015275799197",
    "displayName": "policy with custom access package workflow extension",
    "description": "Run specified custom access package workflow extension at different stages.",
    "createdDateTime": "2022-02-23T22:36:45.363Z",
    "createdBy": "xiaojieliu@fimdev.net",
    "modifiedBy": "xiaojieliu@fimdev.net",
    "canExtend": true,
    "durationInDays": 0,
    "expirationDateTime": null,
    "accessPackageId": "ba5807c7-2aa9-4c8a-907e-4a17ee587500",
    "modifiedDateTime": "2022-02-23T22:36:45.443Z",
    "accessReviewSettings": null,
    "questions": [],
    "requestorSettings": {
        "scopeType": "AllExistingDirectorySubjects",
        "acceptRequests": true,
        "allowedRequestors": []
    },
    "requestApprovalSettings": {
        "isApprovalRequired": false,
        "isApprovalRequiredForExtension": false,
        "isRequestorJustificationRequired": false,
        "approvalMode": "NoApproval",
        "approvalStages": []
    },
    "customExtensionHandlers": [
        {
            "id": "5a38d27a-b702-48d9-ac72-dcf158ba1b0d",
            "stage": "assignmentRequestCreated",
            "customExtension": {
                "id": "219f57b6-7983-45a1-be01-2c228b7a43f8",
                "displayName": "test_action_0110-3",
                "description": "this is for graph testing only",
                "createdDateTime": "2022-01-11T05:19:16.97Z",
                "lastModifiedDateTime": "2022-01-11T05:19:16.97Z",
                "endpointConfiguration": {
                    "@odata.type": "#microsoft.graph.logicAppTriggerEndpointConfiguration",
                    "subscriptionId": "38ab2ccc-3747-4567-b36b-9478f5602f0d",
                    "resourceGroupName": "xiaojil",
                    "logicAppWorkflowName": "customextension_test"
                },
                "clientConfiguration": {
                    "timeoutInMilliseconds": 1000
                },
                "authenticationConfiguration": {
                    "@odata.type": "#microsoft.graph.azureAdTokenAuthentication",
                    "resourceId": "f604bd15-f785-4309-ad7c-6fad18ddb6cb"
                }
            }
        },
        {
            "id": "72c3a010-d4ae-435f-a104-15ec4ac0b1e9",
            "stage": "assignmentRequestGranted",
            "customExtension": {
                "id": "219f57b6-7983-45a1-be01-2c228b7a43f8",
                "displayName": "test_action_0110-3",
                "description": "this is for graph testing only",
                "createdDateTime": "2022-01-11T05:19:16.97Z",
                "lastModifiedDateTime": "2022-01-11T05:19:16.97Z",
                "endpointConfiguration": {
                    "@odata.type": "#microsoft.graph.logicAppTriggerEndpointConfiguration",
                    "subscriptionId": "38ab2ccc-3747-4567-b36b-9478f5602f0d",
                    "resourceGroupName": "xiaojil",
                    "logicAppWorkflowName": "customextension_test"
                },
                "clientConfiguration": {
                    "timeoutInMilliseconds": 1000
                },
                "authenticationConfiguration": {
                    "@odata.type": "#microsoft.graph.azureAdTokenAuthentication",
                    "resourceId": "f604bd15-f785-4309-ad7c-6fad18ddb6cb"
                }
            }
        }
    ]
}

2022-02-24 01:33 UTC, rolyon commented on api-reference/beta/toc.yml
> +              href: api/customaccesspackageworkflowextension-delete.md
The custom extensions and logicAppTriggerEndPointConfiguration do not appear in the toc. Is this okay?

2022-02-24 01:33 UTC, rolyon commented on api-reference/beta/resources/accesspackagecatalog.md
> +|[List customAccessPackageWorkflowExtension](../api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md)|[customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflow
Plural "List customAccessPackageWorkflowExtensions" ?

2022-02-24 01:33 UTC, rolyon commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +|[List customAccessPackageWorkflowExtension](../api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md)|[customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflow
Plural "List customAccessPackageWorkflowExtensions" ?

2022-02-24 03:35 UTC, xiaojil-msft commented on api-reference/beta/resources/logicapptriggerendpointconfiguration.md
> +# logicAppTriggerEndPointConfiguration resource type
Good catch, should be lower case "logicAppTriggerEndpointConfiguration"

2022-02-24 09:00 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **customAccessPackageWorkflowExtensions** relationship to [accessPackageCatalog](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageCatalog?view=gra
Good catch, Robert. Seems the tooling has a bug. I'll inspect all changelog objects and resolve.

2022-02-24 09:09 UTC, FaithOmbongi commented on api-reference/beta/resources/logicapptriggerendpointconfiguration.md
> +# logicAppTriggerEndPointConfiguration resource type
Great catch, @rolyon. This is one marker of a manually created resource file :)
Raised a fix.

2022-02-24 09:11 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: api/customaccesspackageworkflowextension-delete.md
Yep, this is right. Only customAccessPackageWorkflowExtension and related methods should be surfaced and it is.

2022-02-24 09:14 UTC, FaithOmbongi commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +|[List customAccessPackageWorkflowExtension](../api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md)|[customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflow
Correct. This is another marker of a manually created section :)
Raised a fix for it.

2022-02-24 09:16 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackagecatalog.md
> +|[List customAccessPackageWorkflowExtension](../api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md)|[customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflow
Good catch. Same comment about manual vs autogenerated stub applies here.
Raised a fix.

2022-02-24 09:17 UTC, FaithOmbongi commented on api-reference/beta/resources/customcalloutextension.md
> +  "openType": false
Good catch. I see even the tool didn't generate the abstract line. I'll file this as a bug with the onboarding team.

2022-02-24 09:19 UTC, FaithOmbongi commented on api-reference/beta/api/customaccesspackageworkflowextension-update.md
> +PUT /identityGovernance/entitlementManagement/accessPackageCatalogs/{catalogId}/customAccessPackageWorkflowExtensions/{customAccessPackageWorkflowExtensionId}
Confirmed that the API supports PUT not PATCH.

2022-02-24 10:11 UTC, opbld30 commented
Docs Build status updates of commit _[ec9a157](https://github.com/ajburnle/microsoft-graph-docs/commits/ec9a157eea3d641aac4e412cbd9b3576cf4e5f68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/enums.md) | :white_check [...]

2022-02-24 11:03 UTC, opbld34 commented
Docs Build status updates of commit _[8ec8fe9](https://github.com/ajburnle/microsoft-graph-docs/commits/8ec8fe9d3e1544fd8c2dfc9f57940fa9c97c5c7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/enums.md) | :white_check [...]

2022-02-24 11:13 UTC, opbld34 commented
Docs Build status updates of commit _[773741d](https://github.com/ajburnle/microsoft-graph-docs/commits/773741d4b8f3802e960c078cb69c3b9646219cda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentpolicies?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandlerinstance?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/enums.md) | :white_check [...]

2022-02-24 11:16 UTC, FaithOmbongi commented on api-reference/beta/resources/logicapptriggerendpointconfiguration.md
> +# logicAppTriggerEndPointConfiguration resource type
Just FYI @rolyon that this casing mismatch but relating to customExtensionEnd~P~pointConfiguration was the cause of 6 validation errors so awesome catch here 🚀

<img width="724" alt="image" src="https://user-images.githubusercontent.com/14026935/155513140-cfed6d45-6f2f-4fb7-aaa1-cb64f76f214c.png">

2022-02-24 11:31 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadtokenauthentication.md
> +|resourceId|String|The **appID** of the Azure AD application to use to authenticate a logic app with a custom access package workflow extension.|
@xiaojil-msft , Kindly confirm if this should be object ID or app ID.

2022-02-24 11:58 UTC, FaithOmbongi commented on api-reference/beta/api/customaccesspackageworkflowextension-delete.md
> +Deletes a [customAccessPackageWorkflowExtension](../resources/customaccesspackageworkflowextension.md) object.
This opens the question of whether we really have all files in this PR. I'd like to think that there are methods for (at a minimum) these operations:
1. Retrieve all customExtensions/customAccessPackageWorkflowExtension objects for a customExtensionHandler
2. Retrieve all policies with a specific customAccessPackageWorkflowExtension object by ID.

Let me start an internal chat.

2022-02-24 12:15 UTC, opbld34 commented
Docs Build status updates of commit _[eb4f4ab](https://github.com/ajburnle/microsoft-graph-docs/commits/eb4f4ab21907ab06f2dd58bb5f376d00bd1e5299)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](http [...]

2022-02-24 12:32 UTC, opbld33 commented
Docs Build status updates of commit _[18f17e8](https://github.com/ajburnle/microsoft-graph-docs/commits/18f17e840c38e02f16d0a303e9a0cb4ac67e1c8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](http [...]

2022-02-24 13:11 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensionhandler.md
> +None.
Added this to the GET accessPackageAssignmentPolicy doc.

2022-02-24 18:17 UTC, FaithOmbongi commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +author: "currenme"
Resolved.

2022-02-24 18:37 UTC, opbld34 commented
Docs Build status updates of commit _[d6c5f30](https://github.com/ajburnle/microsoft-graph-docs/commits/d6c5f30ccb4c9113a90518840fabdb7ed6d08b8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](http [...]

2022-02-24 19:08 UTC, opbld33 commented
Docs Build status updates of commit _[06f2b1e](https://github.com/ajburnle/microsoft-graph-docs/commits/06f2b1e53b0ce5228062ce5ccc1e65c2306cde42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](http [...]

2022-02-24 19:13 UTC, FaithOmbongi approved these changes

2022-02-24 19:13 UTC, xiaojil-msft approved these changes

2022-02-24 19:31 UTC, opbld34 commented
Docs Build status updates of commit _[850942c](https://github.com/ajburnle/microsoft-graph-docs/commits/850942c433a49a5baee7cb8e1cd32edd950a6d90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](http [...]

2022-02-24 19:37 UTC, currenmehta approved these changes

2022-02-24 20:14 UTC, opbld32 commented
Docs Build status updates of commit _[850942c](https://github.com/ajburnle/microsoft-graph-docs/commits/850942c433a49a5baee7cb8e1cd32edd950a6d90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-post-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-delete.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-delete?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-get.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-get?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/api/customaccesspackageworkflowextension-update.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/api/customaccesspackageworkflowextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/customaccesspackageworkflowextension-update?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagecatalog.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/accesspackagecatalog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/azureadtokenauthentication.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/azureadtokenauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customaccesspackageworkflowextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customaccesspackageworkflowextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customcalloutextension.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customcalloutextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionauthenticationconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionauthenticationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionclientconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionclientconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionclientconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionendpointconfiguration.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionendpointconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionendpointconfiguration?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandler.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensionhandler?view=graph-rest-beta&branch=pr-en-us-15869) (graph-rest-beta) |
[api-reference/beta/resources/customextensionhandlerinstance.md](https://github.com/ajburnle/microsoft-graph-docs/blob/msgraph-elm-customextensions/api-reference/beta/resources/customextensionhandlerinstance.md) | :white_check_mark:Succeeded | [View](http [...]

2022-02-25 04:15 UTC, merged