Universal Print - Fixing inconsistencies between docs & schema for Beta and v1.0 APIs
microsoftgraph/microsoft-graph-docs pull request #15875
Opened 2022-02-16 01:06 UTC by braedenp-msft

2022-03-02 19:24 UTC, nilakhan commented on api-reference/v1.0/resources/printjobconfiguration.md
> +|scaling|[printScaling](enums.md#printscaling-values)|Specifies how the printer should scale the document data to fit the requested media. Valid values are described in the following table.|]
There's an extra ']' at the end of line 36

2022-03-02 21:36 UTC, braedenp-msft commented on api-reference/v1.0/resources/printjobconfiguration.md
> +|scaling|[printScaling](enums.md#printscaling-values)|Specifies how the printer should scale the document data to fit the requested media. Valid values are described in the following table.|]
Fixed!

2022-03-02 21:39 UTC, opbld34 commented
Docs Build status updates of commit _[d9e2707](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9e2707ea46a09125313b70498ee437c40bc35a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/print.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/print.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/print?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-89d0a85d137b39cbd51bba5fc6981cfe-201cb7ef)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-101f7b55d61f34deabf32e316cacb30d-201cb7ef)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-b0c5927b5deb66c7782f50a1cb4dd658-201cb7ef)
[api-reference/beta/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printerlocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerlocation?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-3b7e1886cf29d1c17b6c41723abe17d0-201cb7ef)
[api-reference/beta/resources/printjobconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printjobconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-741030b51dbe55a9d049f755e49d4d74-201cb7ef)
[api-reference/beta/resources/printserviceendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printserviceendpoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printserviceendpoint?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-de8139b4a0cf7f7070bbeaebd0ce7d15-201cb7ef)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) |
[api-reference/v1.0/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printconnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printercapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printerdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerdefaults?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printerlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerlocation?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printjobconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printjobconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |

<a id="89d0a85d137b39cbd51bba5fc6981cfe-201cb7ef"></a>
### [api-reference/beta/resources/print.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/print.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="101f7b55d61f34deabf32e316cacb30d-201cb7ef"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b0c5927b5deb66c7782f50a1cb4dd658-201cb7ef"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3b7e1886cf29d1c17b6c41723abe17d0-201cb7ef"></a>
### [api-reference/beta/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printerlocation.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="741030b51dbe55a9d049f755e49d4d74-201cb7ef"></a>
### [api-reference [...]

2022-03-18 15:15 UTC, isvargasmsft commented on api-reference/beta/resources/print.md
> +|operations|[printOperation](../resources/printoperation.md) collection|The list of print long running operations.|
Shouldn't this navigation property have a List operations method? It is a collection. Please clarify.

2022-03-18 15:16 UTC, isvargasmsft commented on api-reference/beta/resources/print.md
>  |shares|[printerShare](printershare.md) collection|The list of printer shares registered in the tenant.|
Missing in this table: 
- reports navigation property

2022-03-18 15:18 UTC, isvargasmsft commented on api-reference/beta/resources/print.md
>  |shares|[printerShare](printershare.md) collection|The list of printer shares registered in the tenant.|
Global: Do all these changes have changelog entries already? If not, please create changelog entries for all.

2022-03-18 15:21 UTC, isvargasmsft commented on api-reference/beta/resources/printconnector.md
> -|registeredBy|[userIdentity](useridentity.md)|The user who registered the connector.|
Please remove this one from the JSON representation section also.

2022-03-18 19:09 UTC, isvargasmsft commented on api-reference/beta/resources/printercapabilities.md
>  |mediaColors|String collection|The media (i.e., paper) colors supported by the printer.|
Missing in this table: 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/70350956/159068691-1acf19a8-ba37-4598-b8b3-a7213dcf7965.png">


Please also add these properties to the JSON representation.

2022-03-18 19:44 UTC, isvargasmsft commented on api-reference/beta/resources/printerlocation.md
>  |countryOrRegion|String|The country or region that the printer is located in.|
missing in this table:
- floorNumber
- roomNumber

2022-03-18 19:44 UTC, isvargasmsft commented on api-reference/beta/resources/printerlocation.md
>  |countryOrRegion|String|The country or region that the printer is located in.|
please apply these changes to the JSON representation section.

2022-03-18 19:46 UTC, isvargasmsft commented on api-reference/beta/resources/printjob.md
> +|createdBy|[userIdentity](useridentity.md)| Read-only. Nullable.|
please update the JSON representation.

2022-03-18 19:47 UTC, isvargasmsft commented on api-reference/beta/resources/printjobconfiguration.md
> +|fitPdfToPage|Boolean|If true, PDF pages are scaled to match the print media size.|
Global: please also update all JSON representations in this PR.

2022-03-18 19:57 UTC, isvargasmsft requested changes
Thank you very much for updating these docs. 

Please take the time to also update the JSON representation sections and review a few missing properties. 

Thank you very much!

Isaac Vargas

2022-04-05 15:55 UTC, isvargasmsft commented
Hello @braedenp-msft, 

What is the status of this PR? Please let me know if you have any questions regarding the comments above. 

Once you have addressed the feedback, please add the label "review feedback addressed". 

Kind regards, 

Isaac

2022-04-05 23:31 UTC, braedenp-msft commented on api-reference/beta/resources/print.md
>  |printers|[printer](printer.md) collection|The list of printers registered in the tenant.|
Please see the `shares` property below.

2022-04-05 23:33 UTC, braedenp-msft commented on api-reference/beta/resources/print.md
>  |shares|[printerShare](printershare.md) collection|The list of printer shares registered in the tenant.|
Our reporting endpoints are under reportRoot (outside of the print entity).

2022-04-05 23:35 UTC, braedenp-msft commented on api-reference/beta/resources/print.md
> +|operations|[printOperation](../resources/printoperation.md) collection|The list of print long running operations.|
I think we need to publish a new page. @nilakhan who's the best person to help with content for a page documenting how to list operations?

2022-04-05 23:37 UTC, braedenp-msft commented on api-reference/beta/resources/print.md
>  |shares|[printerShare](printershare.md) collection|The list of printer shares registered in the tenant.|
Yep. We just didn't update the Beta docs.

2022-04-05 23:41 UTC, opbld32 commented
Docs Build status updates of commit _[b4763d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4763d14b6411468057c81b4ed5cbb266fe45197)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/print.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/print.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/print?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-89d0a85d137b39cbd51bba5fc6981cfe-987e56ac)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-101f7b55d61f34deabf32e316cacb30d-987e56ac)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-b0c5927b5deb66c7782f50a1cb4dd658-987e56ac)
[api-reference/beta/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printerlocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerlocation?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-3b7e1886cf29d1c17b6c41723abe17d0-987e56ac)
[api-reference/beta/resources/printjobconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printjobconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-741030b51dbe55a9d049f755e49d4d74-987e56ac)
[api-reference/beta/resources/printserviceendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printserviceendpoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printserviceendpoint?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) | [Details](#user-content-de8139b4a0cf7f7070bbeaebd0ce7d15-987e56ac)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-15875) (graph-rest-beta) |
[api-reference/v1.0/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printconnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printercapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printerdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerdefaults?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printerlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerlocation?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printjobconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printjobconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/v1.0/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-1.0&branch=pr-en-us-15875) (>= graph-rest-1.0) |

<a id="89d0a85d137b39cbd51bba5fc6981cfe-987e56ac"></a>
### [api-reference/beta/resources/print.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/print.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="101f7b55d61f34deabf32e316cacb30d-987e56ac"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b0c5927b5deb66c7782f50a1cb4dd658-987e56ac"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3b7e1886cf29d1c17b6c41723abe17d0-987e56ac"></a>
### [api-reference/beta/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/up-doc-scan-fixes/api-reference/beta/resources/printerlocation.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="741030b51dbe55a9d049f755e49d4d74-987e56ac"></a>
### [api-reference [...]

2022-06-01 17:19 UTC, isvargasmsft commented on api-reference/beta/resources/printserviceendpoint.md
> +|id|String|A unique name that identifies the service that the endpoint provides. Possible values are: `discovery` (Discovery Service), `notification` (Notification Service), `ipp` (IPP Service), and
please update the JSON representation section on this topic. In addition, please clarify if this is the ID inherited from entity or an enum type. 

If this is the id inherited from entity, then please update the description of the property as well.

2022-08-01 20:02 UTC, braedenp-msft commented
These issues still need to be fixed. Haven't had time to do it yet. Commenting to keep the PR open.

2022-10-08 15:01 UTC, closed without merging