Add APIs to get/set CloudPC's review status.
microsoftgraph/microsoft-graph-docs pull request #15909
Opened 2022-02-18 07:48 UTC by yayang3

2022-02-18 07:51 UTC, opbld32 commented
Docs Build status updates of commit _[b192efc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b192efcd5130d95f559b81d0323e84c563ef409f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) | [Details](#user-content-c28091f4fe7380bfbb93f92c07d39311-62da7859)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-62da7859)
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |

<a id="c28091f4fe7380bfbb93f92c07d39311-62da7859"></a>
### [api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md)
 - **Line 57, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcbulkremoteactionresult.md'.`````

<a id="0094819f09e3340df09eb0358fea0d24-62da7859"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md)
 - **Line 36, Column 87**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcbulkremoteactionresult.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202180748537294-15909%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T07%3A51%3A06Z&sr=b&sp=r&sig=tKN28O03ePjI6bwMPdcc0b05rnv9Eu6tFAN9Ipyg4dE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 05:46 UTC, opbld33 commented
Docs Build status updates of commit _[1e548f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e548f800fc773f92b7623919858b0cbaf215364)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203070544369907-15909%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T05%3A46%3A38Z&sr=b&sp=r&sig=lGMMj2Dwa0tYFnCKTBuVaeAYmxrD1FqIz009exO934k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 06:10 UTC, AshleyYangSZ commented
Please add change-log.

2022-03-10 08:28 UTC, RuiHou105 commented on api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md
> +|managedDeviceIds|String collection|The managed device id for these Cloud PC devices.|
1.Collection(String)

2.`IDs`, not id

2022-03-10 08:29 UTC, RuiHou105 commented on api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md
> +>**Note:** The response object shown here might be shortened for readability.
You can delete this extra line as you already show the response object down below.

2022-03-10 08:31 UTC, RuiHou105 commented on api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
> +If successful, this function returns a `200 OK` response code and a [cloudPcReviewStatus](../resources/cloudpcreviewstatus.md) in the response body.
Add "object" before "in"

2022-03-10 08:32 UTC, RuiHou105 commented on api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
> +>**Note:** The response object shown here might be shortened for readability.
You can delete this extra line.

2022-03-10 08:38 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk set cloudPc review status](../api/manageddevice-bulksetcloudpcreviewstatus.md)|[cloudpcbulkremoteactionresult](../resources/cloudpcbulkremoteactionresult.md)|Perform bulk setting Cloud PC revi
In the naming for the three APIs, please 
1.update first two `cloudPc `to` Cloud  PC`
2.update the last one `cloudPc `to `Cloud PCs`

2022-03-10 08:43 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcreviewstatus.md
> +|userAccessLevel|cloudPcUserAccessLevel|The access level of the Cloud PC's end user, possible values include: `unrestricted`, `restricted`.|
Type should be: [cloudPcUserAccessLevel ](#cloudpcuseraccesslevel-values)

2022-03-10 09:25 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcreviewstatus.md
> +|Member|Description|
In this table, there should be three columns: Member, Value, Description. For example: 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/77313233/157631654-178821fb-7fb8-40ee-8a92-0048f6afab91.png">

2022-03-10 09:29 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +          - name: Set cloudPc review status
Three names should be:
Set Cloud PC review status
Get Cloud PC review status
Bulk set Cloud PCs review status

2022-03-10 09:32 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Target": "setCloudPcReviewStatus"
Target should be  managedDevice

2022-03-10 09:32 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Target": "getCloudPcReviewStatus"
Target should be managedDevice

2022-03-10 09:33 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Target": "bulkSetCloudPcReviewStatus"
Target should be managedDevice

2022-03-10 10:41 UTC, yayang3 commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk set cloudPc review status](../api/manageddevice-bulksetcloudpcreviewstatus.md)|[cloudpcbulkremoteactionresult](../resources/cloudpcbulkremoteactionresult.md)|Perform bulk setting Cloud PC revi
But there are [List cloudPCs] and [Get cloudPC] above?

2022-03-10 10:49 UTC, yayang3 commented on api-reference/beta/resources/cloudpcreviewstatus.md
> +|Member|Description|
But there are other enums only contains two columns...
![image](https://user-images.githubusercontent.com/99868189/157646584-141b2c95-8ba4-474e-9191-20e85081efcc.png)

2022-03-10 10:56 UTC, yayang3 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Target": "bulkSetCloudPcReviewStatus"
Fixed

2022-03-10 10:56 UTC, yayang3 commented on api-reference/beta/toc.yml
> +          - name: Set cloudPc review status
Fixed

2022-03-10 10:57 UTC, yayang3 commented on api-reference/beta/resources/cloudpcreviewstatus.md
> +|userAccessLevel|cloudPcUserAccessLevel|The access level of the Cloud PC's end user, possible values include: `unrestricted`, `restricted`.|
Fixed

2022-03-10 10:57 UTC, yayang3 commented on api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
> +If successful, this function returns a `200 OK` response code and a [cloudPcReviewStatus](../resources/cloudpcreviewstatus.md) in the response body.
Fixed

2022-03-10 10:58 UTC, yayang3 commented on api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md
> +|managedDeviceIds|String collection|The managed device id for these Cloud PC devices.|
Fixed

2022-03-10 10:58 UTC, opbld30 commented
Docs Build status updates of commit _[a615b5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a615b5e5d1d58ed96529eda0be155c09a16945e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203101056101704-15909%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T10%3A58%3A30Z&sr=b&sp=r&sig=pgrYSdD%2BIpoR6OV5D1by0kjcaImHI5%2BBL46YMEzTXYs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 03:50 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk set cloudPc review status](../api/manageddevice-bulksetcloudpcreviewstatus.md)|[cloudpcbulkremoteactionresult](../resources/cloudpcbulkremoteactionresult.md)|Perform bulk setting Cloud PC revi
`cloudPCs `and `cloudPC `are actually coming from the graph schema. They represent the cloud pc object. But no "cloudPc review status" in graph schema. So here if  we don't follow the naming from graph schema, we need to use `Cloud PC`, a standard way to stand for our product.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/77313233/157798216-733d9c51-f8ce-41f7-a672-cdd13a7416bf.png">

![image](https://user-images.githubusercontent.com/77313233/157798256-12fcf587-752b-4cc9-9754-f43e56a58faf.png)

2022-03-17 07:55 UTC, opbld32 commented
Docs Build status updates of commit _[755cda1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/755cda15f22e9725c6fc07f0a0b2ae990fd8d825)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203170753169255-15909%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T07%3A55%3A30Z&sr=b&sp=r&sig=1zNvhfBqyZ1rAOco%2Fkk91pCeNrP6JRICy%2F6%2F8%2FuwLQI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-28 03:48 UTC, RuiHou105 commented
@yayang3 , could you please follow guidance [here ](https://www.intunewiki.com/wiki/CPC_Graph_Onboarding)to create a roadmap workitem and put it in this PR description?

2022-03-28 03:48 UTC, RuiHou105 requested changes
@yayang3  could you please follow guidance [here ](https://www.intunewiki.com/wiki/CPC_Graph_Onboarding)to create a roadmap workitem and put it in this PR description?

2022-04-12 14:50 UTC, AshleyYangSZ commented
@yayang3 please help fix the graph doc api doctor build failure. Then content reviewer can help review this PR.

2022-04-14 06:41 UTC, opbld30 commented
Docs Build status updates of commit _[1834bef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1834befc0245d546d89c9998ce4c49b1d655aeab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204140631207636-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T06%3A41%3A20Z&sr=b&sp=r&sig=8TUfd%2BNsNIHGoqrcdSRjVtc38%2BySz93hXwrjVrL18rM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 07:05 UTC, opbld30 commented
Docs Build status updates of commit _[d064cf6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d064cf6fdacc1df634c22eb2a76b1ffb34abd950)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204140702359839-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T07%3A05%3A11Z&sr=b&sp=r&sig=Ao7jluO3Hft2OQeDvtgbp396kkLftZkLlJxrHHg%2F4as%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 07:31 UTC, opbld34 commented
Docs Build status updates of commit _[08758e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08758e1ce08bfd479ed97f438ba263dc889bc4b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204140730098540-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T07%3A31%3A32Z&sr=b&sp=r&sig=YKl8l7HCW3VWkMsE0ZTbCFanN%2FuDbPZLFKvatCPnDkQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 06:58 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk set cloudPc review status](../api/manageddevice-bulksetcloudpcreviewstatus.md)|[cloudpcbulkremoteactionresult](../resources/cloudpcbulkremoteactionresult.md)|Perform bulk setting Cloud PC revi
@yayang3  could you please update the naming to Set Cloud PC review status, Get Cloud PC review status, Bulk set Cloud PC review status

2022-04-20 03:04 UTC, yayang3 commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk set cloudPc review status](../api/manageddevice-bulksetcloudpcreviewstatus.md)|[cloudpcbulkremoteactionresult](../resources/cloudpcbulkremoteactionresult.md)|Perform bulk setting Cloud PC revi
Already changed it long time ago

2022-04-20 05:45 UTC, RuiHou105 approved these changes

2022-04-20 05:47 UTC, RuiHou105 commented
@Lauragra , @isvargasmsft 

As this graph schema already went alive, could you please give a review on this PR when you got time? Thanks.

2022-04-24 21:10 UTC, JarbasHorst commented
Hello, I reviewed your PR and left some comments. Please, take a look when you will have time.

**Also, to avoid merge conflicts, please merge PR [16635](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16635) into your branch to include my fixes and before addressing my comments.**

2022-04-25 02:34 UTC, opbld30 commented
Docs Build status updates of commit _[84931c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84931c4005383d8ab5da88547ded9b9751608251)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204250232394730-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T02%3A34%3A29Z&sr=b&sp=r&sig=eVxoi9whEEW%2Fnu51QsZxV7zdGPN%2Fi%2FEoDgAnUHZUUyg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 03:29 UTC, opbld33 commented
Docs Build status updates of commit _[31f0414](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31f041437c82e6ccdc9321880eab32dc61bac6da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204250326416886-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T03%3A29%3A41Z&sr=b&sp=r&sig=yxuuWGXFSB59d1fYtoUjkIhyFS%2FOc%2F6ArHPl5TTERKc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 05:26 UTC, yayang3 commented
@JarbasHorst Thanks! Have fixed them according to the comments.

2022-04-26 06:35 UTC, yayang3 commented
@Lauragra sorry I didn't find your comment. what change do you require?

2022-04-26 20:16 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [16672](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16672) into this branch to include my final edits.

2022-04-26 23:26 UTC, opbld33 commented
Docs Build status updates of commit _[483c5da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/483c5dac197b47936c098280258e04f82cd56cb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204262304199136-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T23%3A26%3A26Z&sr=b&sp=r&sig=bDdNxiBlSF0rlXfh1qMrWuYHWnwnJREpuVxb6UTqtF8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 02:32 UTC, opbld33 commented
Docs Build status updates of commit _[394119a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/394119ac7eddb856ae055e95210782326d679e21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280229574491-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T02%3A32%3A07Z&sr=b&sp=r&sig=wa9RxCiP5WiU07zr6kCrIMd0D%2FEOQJlwGVJjckeYFcA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 02:39 UTC, opbld34 commented
Docs Build status updates of commit _[0ab654c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ab654cee69d22a0bd158f8230df2dea3f4506d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280237224428-15909%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T02%3A39%3A54Z&sr=b&sp=r&sig=Tok4la9Ii3Y%2Bl%2BPNiNsDg899cICFal7j9973dSu6dLM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 02:41 UTC, Lauragra commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [bulkSetCloudPcReviewStatus](https://docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta) method to the [Clo
Technically the binding parameter for these actions is managedDevice, not cloudPc. Is it accurate to say that the methods are added to cloudPC? And is the reason we don't also surface these methods in the managedDevice resource topic because it's Intune content that's managed differently?

2022-04-28 02:43 UTC, Lauragra commented
@yayang3 , this looks good; I had one remaining question about the changelog, and whether we should be following up to add these methods to the managedDevice resource topic?

2022-04-28 03:02 UTC, AshleyYangSZ commented
> @yayang3 , this looks good; I had one remaining question about the changelog, and whether we should be following up to add these methods to the managedDevice resource topic?

@Lauragra We don't want to add it to the managedDevice resource topic, since these new functions/actions are only supported on the CloudPCs  which are enrolled to Intune. So, shall we just keep it as is?

2022-05-11 06:51 UTC, RuiHou105 commented
@Lauragra , @isvargasmsft , could you please give a review on this PR as the graph schema already went alive? Thanks.

2022-05-20 05:30 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [bulkSetCloudPcReviewStatus](https://docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta) method to the [Clo
Hi @Lauragra , as Ashley explained, actually these methods are only supported on Cloud PC devices which are enrolled in Intune side. Users can't do these actions on non-Cloud PC devices. Therefore, we directly surface these methods under Cloud PC resource topic. 

We had the same experiences when adding reprovision Cloud PC remote action/bulk reprovision remote action/...

2022-05-22 01:05 UTC, Lauragra approved these changes

2022-05-22 01:11 UTC, opbld30 commented
Docs Build status updates of commit _[d3a297b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3a297b3995a9329b9c573c6b2d27ac410deed79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205220108324527-15909/BuildReport?accessString=fc072d0d81aae25beb4c74c44da5435d27b84ec675bf287267c2d80c69d07286).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-22 01:13 UTC, opbld34 commented
Docs Build status updates of commit _[23ab430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23ab43095614f68951ca7ace78d1028c199da5c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-getcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-setcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreviewstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcreviewstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulksetcloudpcreviewstatus?view=graph-rest-beta&branch=pr-en-us-15909) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addCloudPcReviewStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205220110108322-15909/BuildReport?accessString=2c5be4bec713ea49e03c82e3e26f94ed6fa2dab05e2ba71d3a55c557768a228d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-22 01:16 UTC, merged