Add two new complex types for forensic.
microsoftgraph/microsoft-graph-docs pull request #15907
Opened 2022-02-18 05:36 UTC by xhan2077

Add two new complex types for forensic.

2022-02-18 05:38 UTC, opbld34 commented
Docs Build status updates of commit _[0c9f685](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c9f6852368e2dcc8cddfcd70b0731025b21d541)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202180536292234-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-21T05%3A38%3A40Z&sr=b&sp=r&sig=k%2B7FZLNXce64OU0yjDCcDCkVJYgqzNdqYhzupBkca9A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-18 06:46 UTC, AshleyYangSZ commented
Please add change-log, see this https://github.com/microsoftgraph/microsoft-graph-docs/pull/15556 as an example PR.

2022-03-11 06:16 UTC, opbld34 commented
Docs Build status updates of commit _[bc06565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc06565c5f23b5cd7974fbfc0113e17ca7dc16b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110614124612-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T06%3A16%3A20Z&sr=b&sp=r&sig=8nIboIIuOXd4o3yeU%2B2cdTyB08madq6urjPUNYzLag0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 06:42 UTC, opbld34 commented
Docs Build status updates of commit _[25e4ba3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25e4ba3c6ca35dabaaf192f17faa538a03291516)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110640342001-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T06%3A42%3A47Z&sr=b&sp=r&sig=ZWZX%2FMc8EiZqQ%2BL0JXMXQZeMRita4jQoGZtKHFQKkLI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 07:48 UTC, opbld34 commented
Docs Build status updates of commit _[3c7a9e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c7a9e9e887492c596324e2cfa1e3b2767aac942)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110746232537-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T07%3A48%3A33Z&sr=b&sp=r&sig=2kHhYimDFOUDJSdEe9Afc59yil%2BTM6XLUnu3oEjaClE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 07:54 UTC, opbld30 commented
Docs Build status updates of commit _[91206d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91206d137880aa230ad06c17ce6bb6c6db0b72b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110752088164-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T07%3A54%3A02Z&sr=b&sp=r&sig=j7GKb%2BC%2F7G%2BV8J%2Bpw9z6%2BtMqjOTpyyQX5WXTqWAVJfw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 07:58 UTC, opbld32 commented
Docs Build status updates of commit _[06b3a98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06b3a983f91faa55228925f06cc8b5a757f3b848)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110756481152-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T07%3A58%3A31Z&sr=b&sp=r&sig=FfVR1aZ7qiM6gMIfWebu%2BIRaBA2GyWfjjcZnkZGtmx4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-13 14:02 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +GET /deviceManagement/virtualEndpoint/snapshots/getStorageAccounts
This should be /deviceManagement/virtualEndpoint/snapshots/getStorageAccounts(subscriptionId='{subscriptionId}'), since  https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/snapshots/getStorageAccounts is not supported now.

2022-03-13 14:04 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcsubscription-get.md
> +This method supports the `$select` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Could you help double confirm if "$select" query is supported now?

2022-03-13 14:08 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Id": "07d4dd82-cf73-49cf-98c4-17f03cf18558",
The changeList content can be picked from stub change-log generated in the schema PR .
It should be like this. And also keep the id same.

   {
          "Id": "112e8692-d578-4f1f-b28a-b2d11dc0a5f3",
          "ApiChange": "Resource",
          "ChangedApiName": "cloudPcForensicStorageAccount",
          "ChangeType": "Addition",
          "Description": "Added the [cloudPcForensicStorageAccount](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcForensicStorageAccount?view=graph-rest-beta) resource type.",
          "Target": "cloudPcForensicStorageAccount"
        },
        {
          "Id": "112e8692-d578-4f1f-b28a-b2d11dc0a5f3",
          "ApiChange": "Resource",
          "ChangedApiName": "cloudPcSubscription",
          "ChangeType": "Addition",
          "Description": "Added the [cloudPcSubscription](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcSubscription?view=graph-rest-beta) resource type.",
          "Target": "cloudPcSubscription"
        },
        {
          "Id": "112e8692-d578-4f1f-b28a-b2d11dc0a5f3",
          "ApiChange": "Method",
          "ChangedApiName": "getStorageAccounts",
          "ChangeType": "Addition",
          "Description": "Added the [getStorageAccounts](https://docs.microsoft.com/en-us/graph/api/intune-getStorageAccounts?view=graph-rest-beta) method to the [getStorageAccounts](https://docs.microsoft.com/en-us/graph/api/intune-getStorageAccounts?view=graph-rest-beta) resource.",
          "Target": "getStorageAccounts"
        },
        {
          "Id": "112e8692-d578-4f1f-b28a-b2d11dc0a5f3",
          "ApiChange": "Method",
          "ChangedApiName": "getSubscriptions",
          "ChangeType": "Addition",
          "Description": "Added the [getSubscriptions](https://docs.microsoft.com/en-us/graph/api/intune-getSubscriptions?view=graph-rest-beta) method to the [getSubscriptions](https://docs.microsoft.com/en-us/graph/api/intune-getSubscriptions?view=graph-rest-beta) resource.",
          "Target": "getSubscriptions"
        }

2022-03-13 14:09 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +          - name: Get
The name is used for describe the API functionality, not API verb.

2022-03-16 05:21 UTC, xhan2077 commented on api-reference/beta/toc.yml
> +          - name: Get
Updated as suggested. Thanks.

2022-03-16 05:21 UTC, xhan2077 commented on api-reference/beta/api/cloudpcsubscription-get.md
> +This method supports the `$select` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Updated as suggested. Thanks.

2022-03-16 05:22 UTC, xhan2077 commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +GET /deviceManagement/virtualEndpoint/snapshots/getStorageAccounts
Updated as suggested. Thanks.

2022-03-16 05:23 UTC, opbld33 commented
Docs Build status updates of commit _[cc43b6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc43b6d6583efe0ef2646b9af3a5593da2cd7b4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203160521298477-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T05%3A23%3A53Z&sr=b&sp=r&sig=UnnBghngH9mh0bqdgFrcjqUA%2FK6dPpjvZSlql9qeIuM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 05:55 UTC, opbld31 commented
Docs Build status updates of commit _[500af4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/500af4ba15c904c0bcc70fe98d391e6fdc3f7d02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203160551566560-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T05%3A55%3A12Z&sr=b&sp=r&sig=WJWZzmJd8%2FzVEx6BOVtF3SclE8U8G8BiT9CO8aJCcc8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 06:09 UTC, xhan2077 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Id": "07d4dd82-cf73-49cf-98c4-17f03cf18558",
Updated the changelog. Thanks for pointing it out.

2022-03-16 06:27 UTC, AshleyYangSZ requested changes

2022-03-16 06:27 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcsubscription-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/getSubscriptions
This should be https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/snapshots/getSubscriptions

2022-03-16 06:27 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +This method supports the `$select` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Could you help confirm if this API support select query, I checked with this https://canary.graph.microsoft.com/testprodbeta_cpc_int/deviceManagement/virtualEndpoint/snapshots/getStorageAccounts(subscriptionId='cb6ad4c4-8a17-4245-a644-e4436b1ee204')?$select=storageAccountName  
But seems like it return both id and name.

2022-03-16 06:27 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +Inherits from [entity](../resources/entity.md).
Could you help remove this?

2022-03-16 06:41 UTC, xhan2077 commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +Inherits from [entity](../resources/entity.md).
Removed as suggested. Thanks.

2022-03-16 06:44 UTC, opbld30 commented
Docs Build status updates of commit _[9b932b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b932b8659585985cf1ec8d4c885191e60bcbce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203160641569402-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T06%3A44%3A33Z&sr=b&sp=r&sig=VA1x6zZpfOXpub93ZDd64jfa9u126sXoEsuFa%2FVOf94%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 09:56 UTC, opbld34 commented
Docs Build status updates of commit _[1eb03f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1eb03f71125a3ccccaf8d10023450b6f075e76ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203220954078738-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T09%3A56%3A19Z&sr=b&sp=r&sig=sXgBRr5lX2tUbIQvJRlkyIxUHic262UuLdQkfh4jJcE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 07:06 UTC, opbld32 commented
Docs Build status updates of commit _[3d013cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d013cd54c9c4c3bb9c004fb8e6a78c2673dc89c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203240703189981-15907%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T07%3A06%3A30Z&sr=b&sp=r&sig=Bx8YJOUf5Kx%2FWrSFY%2F6ZdIkEuicXeas9lO2FaL%2Bt080%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 07:38 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsubscription.md
> +description: "Represents a CloudPC Subscription."
CloudPC -> Cloud PC

2022-04-19 07:48 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcsubscription-get.md
> +Read the properties and relationships of a [cloudPcSubscription](../resources/cloudpcsubscription.md) object.
Actually, the method `GetSubscriptions `is to list all subscriptions which can be used to store snapshots of a Cloud PC, not to Read the properties and relationships of a ..... So please correct the description to: List all subscriptions that can be used to store snapshot(s) of a Cloud PC for forensic analysis.

Also update the description in line 3. Thanks.

2022-04-19 07:49 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcsubscription-get.md
> +If successful, this method returns a `200 OK` response code and a [cloudPcSubscription](../resources/cloudpcsnapshot.md) object in the response body.
Actually this method will return one or more subscription objects. So please update the description here.

2022-04-19 07:50 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcsubscription-get.md
> +
Please help remove the extra blank line.

2022-04-19 07:51 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcsubscription-get.md
> +            "id": "8fd04a0b-ed49-46c0-a62d-e7980d829058",
In the response body, the property naming should be subscriptionId, subscriptionName. Please correct.

2022-04-19 09:26 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +Read the properties and relationships of a [cloudPcForensicStorageAccount](../resources/cloudpcforensicstorageaccount.md) object.
The description is kind of away from the real meaning of the method. Please update to: List all storage accounts that can be used to store snapshot(s) of a Cloud PC for forensic analysis. 

Please also update the description in line 3. Thanks.

2022-04-19 09:27 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +If successful, this method returns a `200 OK` response code and a [cloudPcForensicStorageAccount](../resources/cloudpcsnapshot.md) object in the response body.
This method may return a objects or several objects right? So please help the response description here.

2022-04-19 09:28 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/snapshots/getStorageAccounts(subscriptionId='cb6ad4c4-8a17-4245-a644-e4436b1ee204')
Update to: GET /deviceManagement/virtualEndpoint/snapshots/getStorageAccounts(subscriptionId='cb6ad4c4-8a17-4245-a644-e4436b1ee204')

2022-04-19 09:28 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +
Please help remove one extra blank line.

2022-04-19 09:30 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +|[Get cloudPcForensicStorageAccount](../api/cloudpcforensicstorageaccount-get.md)|[cloudPcForensicStorageAccount](../resources/cloudpcforensicstorageaccount.md)|Read the properties and relationships
Please also update this method description, according to my comment in `cloudpcforensicstorageaccount-get.md` file

2022-04-19 09:35 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +title: "cloudPcForensicStorageAccount complex type"
Although it indeed is complex type in graph schema, here you should use resource type to describe it in graph API docs. So please use: cloudPcForensicStorageAccount resource type

2022-04-19 09:36 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +# cloudPcForensicStorageAccount complex type
cloudPcForensicStorageAccount resource type

2022-04-19 09:37 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +## Methods
A complex type will not have `Methods `part in the file. Please remove this part.

2022-04-19 09:37 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsubscription.md
> +# cloudPcSubscription complex type
cloudPcSubscription resource type

2022-04-19 09:38 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsubscription.md
> +title: "cloudPcSubscription complex type"
cloudPcSubscription resource type

2022-04-19 09:39 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsubscription.md
> +## Methods
A complex type doesn't have `Methods `part in the md file. So please remove this part.

2022-04-19 09:41 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsubscription.md
> +  "subscriptionId": "String (identifier)",
Only an entity will have a key which is the entity's unique id/identifier. So please remove (identifier) as it's a complex type.

2022-04-19 09:42 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcforensicstorageaccount.md
> +  "storageAccountId": "String (identifier)",
Only an entity will have a key which is the entity's unique id/identifier. So please remove `(identifier)` as it's a complex type.

2022-04-19 09:46 UTC, RuiHou105 requested changes
@xhan2077 please
1. resolve all comments in this PR
2. Please create a roadmap workitem and attach the workitem id in the PR description.  Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/11551/

2022-04-20 05:46 UTC, xhan2077 commented on api-reference/beta/api/cloudpcsubscription-get.md
> +If successful, this method returns a `200 OK` response code and a [cloudPcSubscription](../resources/cloudpcsnapshot.md) object in the response body.
I've updated it to "zero or more" here, which I think is more accurate. Do you think it's okay? Thanks.

2022-04-20 06:04 UTC, opbld31 commented
Docs Build status updates of commit _[7a341e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a341e6c790f65603f57da29e077e4da3cc3beba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204200602396530-15907%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T06%3A04%3A31Z&sr=b&sp=r&sig=iTrFrJ8%2Br6GUn4oOS5ZS6%2BpB1Hy95qJfFJYfrMydX6o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 05:57 UTC, AshleyYangSZ approved these changes

2022-04-27 06:27 UTC, xhan2077 commented
[Feature 14010](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14010): [Devices and apps][Cloud PC] Add two new complex types and related actions for Forensic

2022-04-27 06:33 UTC, RuiHou105 approved these changes

2022-04-29 15:06 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcsubscription.md
> +Represents the subscription information that can be used to store snapshot(s) of a Cloud PC for forensic analysis.
Line 16: I believe this description was for forensicStorageAccount, not for this one. Please apply the proper description to this complex type.

2022-04-29 15:56 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +title: "Get cloudPcForensicStorageAccount"
The title should be:
cloudPCSnapshot: getStorageAccounts
Guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=guidelines-and-examples


Topic title should be: cloudpcsnapshot-getstorageaccounts.md
Guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming?anchor=microsoft-graph-file-naming-guidelines

2022-04-29 17:29 UTC, opbld32 commented
Docs Build status updates of commit _[61c3562](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61c35624f74d3a29cedaa57a289c0fa709cc468f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcforensicstorageaccount-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcforensicstorageaccount-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcforensicstorageaccount-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204291727494495-15907%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T17%3A29%3A37Z&sr=b&sp=r&sig=0MZiRJ06rg30SyAjNPCKe6uvq0%2Bn5h%2FyENDfn1ZVkZg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 17:33 UTC, isvargasmsft requested changes
Hello Xu, 

Thank you very much for the good work in this PR. 

Please take a look at a few comments for consistency. 

Kind regards, 

Isaac

2022-05-03 09:15 UTC, xhan2077 commented on api-reference/beta/resources/cloudpcsubscription.md
> +Represents the subscription information that can be used to store snapshot(s) of a Cloud PC for forensic analysis.
@isvargasmsft This file was intended for cloudPcSubscription and I think the descripton in Line 16 is correct. Would you please double check on this? Thanks.

2022-05-03 09:18 UTC, xhan2077 commented on api-reference/beta/api/cloudpcforensicstorageaccount-get.md
> +title: "Get cloudPcForensicStorageAccount"
@isvargasmsft Thanks for pointing it out. I've updated this file as suggested. However, should I also update the other one for subscription as well?

2022-05-03 09:20 UTC, opbld33 commented
Docs Build status updates of commit _[486a4fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/486a4fe22e1d878c0d54b09e25bd9637f4cb2a88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7268b573)
[api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsubscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcsubscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsubscription-get?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-7268b573"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 10324, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcforensicstorageaccount-get.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205030918489435-15907%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T09%3A20%3A55Z&sr=b&sp=r&sig=oJpYFvrDmuX1IP643GPTfbGG7MTkoxo%2BpCbquQ0GaC0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 14:06 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcsubscription.md
> +Represents the subscription information that can be used to store snapshot(s) of a Cloud PC for forensic analysis.
My mistake. Thank you!

2022-05-05 03:14 UTC, AshleyYangSZ commented
@xhan2077 @isvargasmsft I removed the ready to merge label, since this schema change doesn't reach prod now. Will add ready to merge once the schema goes alive. Thanks.

2022-05-05 03:18 UTC, xhan2077 commented
> @xhan2077 @isvargasmsft I removed the ready to merge label, since this schema change doesn't reach prod now. Will add ready to merge once the schema goes alive. Thanks.

Thanks for catching this. Let's add the ready to merge label back after the schema goes live.

2022-05-12 03:27 UTC, opbld31 commented
Docs Build status updates of commit _[92fb396](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92fb3967a83bcace0dd2273f51c4678ee949985c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getsubscriptions?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120324253046-15907/BuildReport?accessString=8b19e7a50454964e609d0220598a13ade2d88b477ef56abee0d10a432e9e9fe6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:29 UTC, opbld34 commented
Docs Build status updates of commit _[558a222](https://github.com/microsoftgraph/microsoft-graph-docs/commits/558a22228acfd4c17cb7ed35738ad48da81b782c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getsubscriptions?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120325503046-15907/BuildReport?accessString=9817abd1f9c5da21100c24e9d869cddce6700025e28f794986aa18de1aac06d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:31 UTC, opbld33 commented
Docs Build status updates of commit _[b08f21b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b08f21bfe06c39aea8f5db7d6a2847e39299e797)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getsubscriptions?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120326336901-15907/BuildReport?accessString=1a06f6335d033b80b5bfdd0846c8c8f4b9d2d2c20e15bf12c8734b8d0292ca1a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:33 UTC, opbld34 commented
Docs Build status updates of commit _[0240f68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0240f682d093d8e9fe2f6d5c2a1d34e4af68365c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getsubscriptions?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120328210821-15907/BuildReport?accessString=7b2ac9c44b04f9f99c0b471d6bfe070ca525a7c34aa87b60aa9f906c8a1f363d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:36 UTC, opbld32 commented
Docs Build status updates of commit _[cbe7c31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbe7c31eefca922ce5bdaa07be443bf820840a0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getsubscriptions?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcforensicstorageaccount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcforensicstorageaccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcforensicstorageaccount?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsubscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsubscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsubscription?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcsnapshot-getstorageaccounts?view=graph-rest-beta&branch=pr-en-us-15907) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xhan2077/feature/forensic-graph/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120333509579-15907/BuildReport?accessString=bf9db9d89786f3aa2b18b1da4a4883a220b6b4645b1b376a4db983dc831ffdd4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:40 UTC, merged