Documentation fixes
microsoftgraph/microsoft-graph-docs pull request #15920
Opened 2022-02-21 08:44 UTC by swapnil1993

2022-02-21 08:47 UTC, opbld34 commented
Docs Build status updates of commit _[85590fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85590fc34cea0bc4fa50daec1f9d464a38f79e3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/v1.0/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202210844417240-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T08%3A47%3A51Z&sr=b&sp=r&sig=07EhVusZw31woGg0S0s7K0lAXnqxlNQQzy2lRqUrWvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 20:16 UTC, isvargasmsft commented on api-reference/beta/resources/termcolumn.md
>  | termSet      | microsoft.graph.termStore.set | Termset whose children can be selected as column's value.
These 2 relationships are not defined in the metadata. Are these about to be introduced?

2022-03-07 20:18 UTC, isvargasmsft commented on api-reference/v1.0/resources/documentset.md
>  | welcomePageUrl      | string | Welcome page absolute URL.  |
Please order these properties alphabetically.

2022-03-07 20:19 UTC, isvargasmsft commented on api-reference/beta/resources/termcolumn.md
>  | termSet      | microsoft.graph.termStore.set | Termset whose children can be selected as column's value.
I noticed these properties are defined in v1 but not in beta. Please review and fix accordingly.

2022-03-07 20:21 UTC, isvargasmsft requested changes
Hello, 

Thank you very much for your work in this updates. 

Please take time to review 2 main issues:
- Please order the properties in alphabetically in the Properties table. 
- Please address some inconsistencies in the metadata. 

Feel free to ping me on the side if you have any questions. 

Regards, 

Isaac Vargas

2022-03-07 20:30 UTC, kanchm commented on api-reference/beta/resources/termcolumn.md
>  | termSet      | microsoft.graph.termStore.set | Termset whose children can be selected as column's value.
api-reference/beta/resources/termcolumn.md(18,1): [Microsoft.FileServices] Remove 'parentTerm, termSet' from the documentation or add it to the schema.

2022-03-09 05:39 UTC, swapnil1993 commented on api-reference/beta/resources/termcolumn.md
>  | termSet      | microsoft.graph.termStore.set | Termset whose children can be selected as column's value.
I will be adding it to beta schema

2022-03-09 05:44 UTC, opbld34 commented
Docs Build status updates of commit _[27a0044](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27a00441561ef2eae4c54e2344d053fb7d3fbfe8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/v1.0/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203090542137750-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T05%3A44%3A19Z&sr=b&sp=r&sig=c9Wnd9wtjVbksKVr4EOFlc4dCCchrssLatUHdBazfw4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 09:56 UTC, opbld30 commented
Docs Build status updates of commit _[0e072f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e072f210bd55d6d556c8620b264fd6813960d48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/v1.0/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203100953554335-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T09%3A56%3A09Z&sr=b&sp=r&sig=veFOORhG1lS3WdMQO6%2BFP9iVPSjCCUrZ5CixC886wn0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 04:05 UTC, swapnil1993 commented on api-reference/beta/resources/termcolumn.md
>  | termSet      | microsoft.graph.termStore.set | Termset whose children can be selected as column's value.
I have checked in the changes to update csdl, it should be fully deployed in next few days

2022-03-16 04:05 UTC, swapnil1993 commented
#feedback-addressed

2022-03-16 15:17 UTC, isvargasmsft commented on api-reference/v1.0/resources/documentset.md
>  The following is a JSON representation of a **documentSet** resource.
Please update the JSON representation to reflect the actual structure of the resource.

2022-03-16 16:43 UTC, isvargasmsft requested changes
Please update the JSON representation sections to reflect the changes and remove the nav properties.

2022-03-17 03:10 UTC, swapnil1993 commented
#feedback-addressed

2022-03-17 03:12 UTC, opbld34 commented
Docs Build status updates of commit _[92935d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92935d6cbdbfe189cc10206211b5f7c44e913cbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/v1.0/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203170310042182-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T03%3A12%3A07Z&sr=b&sp=r&sig=ZZYhejoqPuxlb2tNvUlzFz5agbg8T1s6ztcvMyTsXn0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 14:59 UTC, isvargasmsft approved these changes

2022-03-22 00:50 UTC, Lauragra commented on api-reference/beta/resources/documentset.md
> +| shouldPrefixNameToFile | Boolean  | Add the name of the Document Set to each file name.
This description is unclear. It's a Boolean property, so I would expect a description such as: "Indicates whether to add the name of the document set to each file name." You might also want to indicate whether the default value is `true` or `false`.

2022-03-22 00:56 UTC, Lauragra commented on api-reference/beta/resources/termcolumn.md
> +| parentTerm     | microsoft.graph.termStore.term | Specifies the term guid whose children can be selected as column's value.
GUID is an acronym; please capitalize. Suggested revision: "Specifies the GUID of the parent term for which the child terms can be selected as the column value."

2022-03-22 00:57 UTC, Lauragra commented on api-reference/v1.0/resources/documentset.md
> +| shouldPrefixNameToFile | Boolean  | Add the name of the document set to each file name.|
Please fix the description here too.

2022-03-22 05:36 UTC, opbld34 commented
Docs Build status updates of commit _[21f1b14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21f1b149ab779994d5828d5eea77a2358a34fb67)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fa8316e2)

<a id="fa8316e2"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203220535463233-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T05%3A36%3A22Z&sr=b&sp=r&sig=JE7NSqbNiXYQ0oxELUcNvKj29tbbvm2J9eDGPAsh1YE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 05:41 UTC, swapnil1993 commented
#feedback-addressed

2022-03-22 05:42 UTC, opbld33 commented
Docs Build status updates of commit _[b8bc93a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8bc93ae60ac8dd1270f6a8cca94ba342dafd248)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/v1.0/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203220540419183-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T05%3A42%3A43Z&sr=b&sp=r&sig=gECHCaubrSggR%2BxUQfB0y83cFvC96yI9jgefnUPm%2Bs0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 05:43 UTC, swapnil1993 commented on api-reference/beta/resources/documentset.md
> +| shouldPrefixNameToFile | Boolean  | Add the name of the Document Set to each file name.
Made the description change. Booleans are false by default therefore skipping specifying the default value

2022-03-23 01:51 UTC, opbld33 commented
Docs Build status updates of commit _[42d9367](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42d93676295ae066134c8b7b47af7f34540c01fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/beta/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-15920) (graph-rest-beta) |
[api-reference/v1.0/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentset?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/documentsetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/documentsetcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/documentsetcontent?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/hyperlinkorpicturecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/hyperlinkorpicturecolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/hyperlinkorpicturecolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/api-reference/v1.0/resources/termcolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-1.0&branch=pr-en-us-15920) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/apidocfixes/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203230149139068-15920%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T01%3A51%3A55Z&sr=b&sp=r&sig=KP0SbwFpDiWjaHCdMLSzkvaPhEPnfdqoRUP7L0KcJvI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 01:52 UTC, merged