Adtangir/gdap documentation
microsoftgraph/microsoft-graph-docs pull request #15965
Opened 2022-02-23 21:20 UTC by adtangir

2022-02-23 21:22 UTC, opbld32 commented
Docs Build status updates of commit _[f6426b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6426b49191d72f527dd2efb9b6192fe8f423787)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-9435ba52f311ba244f7739f5a7e493a0-6d12fb06)
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-eb6c54d465b2feb2e536fa2e41158cad-6d12fb06)
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-eed8c76466ea8d6307a0457d95117753-6d12fb06)
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-cd683a6c9e0839f6c3dc06be76c84330-6d12fb06)
[api-reference/beta/api/delegatedadmincustomer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadmincustomer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-delete?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-75c98a391494d154c3f12664efa7e751-6d12fb06)
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-0b68982df911c64c94acce85d4b3167a-6d12fb06)
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminoperation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-3c5cd3b954084dbcb2f9a84b2626b2f1-6d12fb06)
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-0fd50f0e1f2ffe37e3550adbc6819052-6d12fb06)
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminoperation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-c3e51071f1066ad269214725632f9d04-6d12fb06)
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminoperation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-bc7c93f67dbfad348e23029a1cf78600-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-596f9d17d1aa111417bf20250cf90a0f-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-e2bf35e60b2f02ca07d6528035d6bee1-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-ebbc07a0aa4808f586ae37120018eb4a-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-77b1a41884f9d92b7aaa1631ec04c1ed-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-15965) (graph-rest-beta) | [Details](#user-content-11d2f758f9b63b193900fd2aba1494fe-6d12fb06)
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir/gdap_documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-e [...]

2022-03-09 19:43 UTC, FaithOmbongi requested changes
Thank you @adtangir for your work on this PR. The PR was huge but you did an excellent job trying to get all required docs into the PR.

I've left suggestions for changes/where to make things clearer etc. In addition, please address the following:
- GLOBAL: The assigned author of the docs should be a user's GitHub alias, not a team's internal mailing alias as per the [Get started steps](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started-with-GitHub). I see **amharris1331** has the necessary memberships  - will she own the feature, docs, and be available for support?
- Please document the **delegatedAdminRelationships** + **delegatedAdminCustomers** relationships in the tenantRelationship resource doc.
- GLOBAL: I think the **directory-management** ms.prod value is suited for these APIs. From what I've understood, they are mostly about delegated administrative role assignments/management between a Partner and a customer tenant.
- We'll need an Overview article to explain the whole crux of these new APIs - how they relate to the Partner Center, VAR, etc. Building blocks. Benefits. Example scenarios. Licensing requirements etc.
- I see you're using the namespace `microsoft.partner.customerServiceAdministration.`. This is also the cause of 3/4 of the validation marked "Unable to locate a definition for resource type: microsoft.partner.customerServiceAdministration.****" I think [ALL Microsoft Graph APIs](https://docs.microsoft.com/en-us/graph/use-the-api#odata-namespace) are defined in the `microsoft.graph` namespace, even though some might be defined in sub-namespaces. If confirmed microsoft.graph namespace is correct, please change all occurrences of `microsoft.partner.customerServiceAdministration.*` to `microsoft.graph.*`
- GLOBAL: All examples in the API articles should be real examples with real data instead of placeholder data types. Customers report to find these more helpful. Please run your queries in a demo tenant to get the values. 
- I see you've introduced two new permissions, please document them in the [permissions reference](docs.microsoft.com/en-us/graph/permissions-reference) doc.
- I see some operations support optional and required headers. Let's document all of them.
- Your API.md claims that delegatedAdminCustomer resource supports only LIST and GET. I see this note: "Not supported; will be supported in future for internal applications only.". Please confirm and make the changes/remove files or entries where applicable.
- delegatedadminoperationmd should be **delegatedadminrelationshipoperation.md** because I see the resource name changed between the API.md approval and the schema release
- The API.md says that CREATE, DELETE, UPDATE operations aren't supported by delegatedAdminRelationshipOperation API. Please confirm.
- Missing APIs for serviceManagementDetails. I see the URL pattern `GET /delegatedAdminCustomers/{ID}/serviceManagementDetails` in the API.md

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationshiprequest.md
> +description: "Represents a request specific to a delegated admin relationship between a partner and customer."
This description isn't completely clear when I look at the values of the two enums

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationshiprequest.md
> +Represents a request specific to a delegated admin relationship between a partner and customer.
Please also make the change here

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationshiprequest.md
> +|status|String|The status of the request.|
status and action are enums. Please copy over the complete list of members from the doc stub.
```suggestion
|action|String|The action to be performed on the delegated admin relationship.|
|createdDateTime|DateTimeOffset|The date and time in ISO 8601 when the relationship request was created and is always in UTC. Read-only.|
|id|String|The unique identifier of the relationship request. Read-only.|
|lastModifiedDateTime|DateTimeOffset|The date and time in ISO 8601 when this relationship request was last modified and is always in UTC. Read-only.|
|status|String|The status of the request.|
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +---
File name is _delegatedadminrelationship-list-requests.md_

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +title: "List delegatedAdminRelationshipRequests"
```suggestion
title: "List requests"
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +# List delegatedAdminRelationshipRequests
```suggestion
# List requests
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
...

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +GET https://graph.microsoft.com/beta/tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/requests
Real ID please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +{
Real payload please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +title: "Create delegatedAdminRelationshipRequest"
```suggestion
title: "Create requests"
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +# Create delegatedAdminRelationshipRequest
```suggestion
# Create requests
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +}
Real ID please
```suggestion
POST https://graph.microsoft.com/beta/tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/requests
Content-Type: application/json

{
  "@odata.type": "#microsoft.partner.customerServiceAdministration.delegatedAdminRelationshipRequest",
  "action": "String",
  "status": "String"
}
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +{
Real payload please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-delete.md
> +---
API.md claims Delete isn't supported.

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-delete.md
> +DELETE https://graph.microsoft.com/beta/tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/requests/{delegatedAdminRelationshipRequestId}
Real ID please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-delete.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
..

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-get.md
> +GET https://graph.microsoft.com/beta/tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/requests/{delegatedAdminRelationshipRequestId}
Real ID please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-get.md
> +}
Real payload please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-update.md
> +
Align these with the changes you make to the resource doc

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-update.md
> +}
Real IDs
Real request body
```suggestion
PATCH https://graph.microsoft.com/beta/tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/requests/{delegatedAdminRelationshipRequestId}
Content-Type: application/json

{
  "@odata.type": "#microsoft.graph.delegatedAdminRelationshipRequest",
  "action": "String",
  "status": "String"
}
```

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshiprequest-update.md
> +{
Real payload please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-list-requests.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
...

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-list-requests.md
> +GET https://graph.microsoft.com/beta/tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/requests
Real ID please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-list-requests.md
> +{
Real payload please

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadmincustomer.md
> +None.
Missing **serviceManagementDetails** relationship

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminservicemanagementdetail.md
> +description: "Contains the management details of a Delegated Admin service."
Let's try to make the description clearer. How does this relate to the main delegatedAdminCustomer API?

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminservicemanagementdetail.md
> +Contains the management details of a Delegated Admin service.
Same changes you apply in the metadata, you'll apply here.

2022-03-09 19:43 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminservicemanagementdetail.md
> +|serviceName|String|The URL of the management portal for the managed service.|
"Managed service" gives the vibes of a service provider. I don't think that's the message you've sent so far about the Partner-Customer relationship. I could be wrong.

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "ApiChange": "EnumType",
```suggestion
          "ApiChange": "Enum type",
```

2022-03-09 19:43 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +      "SubArea": ""
```suggestion
      "WorkloadArea": "Microsoft.Partner.CustomerSvcAdmin",
      "SubArea": ""
```
Let's use these values as per the internal thread. This API seems to be about directory management only in a partner-customer r/ship
```suggestion
      "WorkloadArea": "Identity and access",
      "SubArea": "Directory management"
```

2022-03-22 14:23 UTC, adtangir commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|status|delegatedAdminRelationshipStatus|The status of the relationship.The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`,
The schema for some of the fields above has changed and we have updated the field descriptions accordingly. Please give these a second pass

2022-03-22 14:25 UTC, adtangir commented on api-reference/beta/resources/delegatedadminrelationship.md
> +author: "smrtsec"
I'll check with the team and update the this with a better description

2022-03-22 14:28 UTC, adtangir commented on api-reference/beta/resources/delegatedadminrelationship.md
> +ms.prod: "gdap"
Updated the ms.prod value to directory-management

2022-03-31 03:13 UTC, merged

2023-03-17 09:20 UTC, FaithOmbongi commented
The changes are live. Removing **changes requested** label to avoid unactionable notifications.