Add document for new source cloudPcCrossCloudGovernmentOrganizationMapping and related APIs.
microsoftgraph/microsoft-graph-docs pull request #16001
Opened 2022-02-28 05:58 UTC by SuyliuMS

Add document for new source cloudPcCrossCloudGovernmentOrganizationMapping and related APIs.

2022-02-28 06:01 UTC, opbld32 commented
Docs Build status updates of commit _[52dcebe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52dcebedc5662a6f5ab6c178640e57bb5c5994c4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-c6b16fa540eeea4e4d112b02795c5b06-d0f83b6f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmenorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d0f83b6f)
[api-reference/beta/api/cloudpccrosscloudgovernmenorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmenorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmenorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c6b16fa540eeea4e4d112b02795c5b06-d0f83b6f"></a>
### [api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md'.`````

<a id="0817dce4456c16725d5333633847d38f-d0f83b6f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml)
 - **Line 10175, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpccrosscloudgovernmentorganizationmapping-post.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202280558483594-16001%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T06%3A01%3A01Z&sr=b&sp=r&sig=vy7dhRwZQMFV0uk%2F3sIJL9PIGa2PQ1QVTlaTWbAPvY0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-28 07:26 UTC, opbld34 commented
Docs Build status updates of commit _[ba350d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba350d771db51f73258b66ff7d89cc4a45072ea4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-c6b16fa540eeea4e4d112b02795c5b06-736bf2ec)
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c6b16fa540eeea4e4d112b02795c5b06-736bf2ec"></a>
### [api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202280724324859-16001%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T07%3A26%3A36Z&sr=b&sp=r&sig=4R4qCssXiAWMf69iKw4%2BoQBCSP19zNW%2FR6khKVR7pxo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 08:36 UTC, AshleyYangSZ requested changes

2022-03-04 08:36 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                {
Only include related changeList here.

2022-03-04 08:57 UTC, opbld34 commented
Docs Build status updates of commit _[3e341b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e341b72da229747a2997f73696828458562fc1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-c6b16fa540eeea4e4d112b02795c5b06-d1e3ba57)
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c6b16fa540eeea4e4d112b02795c5b06-d1e3ba57"></a>
### [api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040855515489-16001%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T08%3A57%3A56Z&sr=b&sp=r&sig=918cKXgQkH9u8F57GPIluUecJXQXfXVgGypg5xwcCzA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 09:11 UTC, opbld31 commented
Docs Build status updates of commit _[20122f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20122f62922853b9c6db7b9032851a567d40a98b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040908597272-16001%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T09%3A11%3A02Z&sr=b&sp=r&sig=rE4CkgbzMZj%2FCnpZ%2FPq9Ye4OkX6OXlsU4VBACrgZiyo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 09:23 UTC, opbld31 commented
Docs Build status updates of commit _[d06bbe6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d06bbe620f1cccf1d53c6e8d44cb62d04730295d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040921579438-16001%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T09%3A23%3A58Z&sr=b&sp=r&sig=sY1b%2B2xX0dc15FFCatO7PzDe5FT97A3DyzJLb9iy8i8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 09:53 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +description: "**TODO: Add Description**"
Please update the description here.

2022-03-22 09:55 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +Inherits from [entity](../resources/entity.md).
I suppose we don't need this line.

2022-03-22 10:13 UTC, RuiHou105 commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md
> +>**Note:** The response object shown here might be shortened for readability.
This extra note can be removed.

2022-03-22 10:14 UTC, RuiHou105 commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md
> +POST ** Collection URI for microsoft.graph.cloudPcCrossCloudGovernmentOrganizationMapping not found
POST /deviceManagement/virtualEndpoint/crossCloudGovernmentOrganizationMapping

2022-03-22 10:15 UTC, RuiHou105 commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md
> +|X-MS-CloudPC-USGovCloudTenantAADToken|{token}. Required.|
Please add more description for this header: Represents the AAD token of government cloud tenant.

2022-03-22 10:16 UTC, RuiHou105 commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md
> +>**Note:** The response object shown here might be shortened for readability.
You can remove this extra line.

2022-03-22 10:19 UTC, RuiHou105 requested changes
Please resolve all comments in this PR. Thanks!

2022-09-16 06:12 UTC, opbld32 commented
Docs Build status updates of commit _[fe4088a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe4088a6ffe5f7042f9a1cf05d2a013fb3018466)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d948b1d5)
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d948b1d5"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160608335461-16001/BuildReport?accessString=779a076bac9112c36c6eb93b3853fe3ef06a6b8edf696dc181e9e3ec07044358).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-08 00:59 UTC, AshleyYangSZ requested changes

2022-10-08 00:59 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +|id|String|The tenant ID of the GCC (US Government Community Cloud) tenant in public cloud. Inherited from [entity](../resources/entity.md).|
Could you help remove the `Inherited from [entity](../resources/entity.md).`?

2022-10-08 11:07 UTC, opbld34 commented
Learn Build status updates of commit _[0e203b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e203b1de0e1d7d9c87f9765cd4d4841feb205c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210081104564160-16001/BuildReport?accessString=9c64da63c9a618e8c58d3efd02644cf2eb576ca46373ead0e017cf7a86231338).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-09 01:06 UTC, AshleyYangSZ approved these changes

2022-10-09 01:08 UTC, opbld34 commented
Learn Build status updates of commit _[84b8be3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84b8be3cad1a0a0d43a17abcd096dff695c6508e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210090106257649-16001/BuildReport?accessString=25de0b6166a4b0fcb26a990c5816b6050493c04c1f00d855f9d9b9dddbefd5ad).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-09 02:36 UTC, RuiHou105 commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md
> +POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/cloudPcCrossCloudGovernmentOrganizationMapping
```suggestion
POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/crossCloudGovernmentOrganizationMapping
```

2022-10-09 03:21 UTC, RuiHou105 requested changes
@SuyliuMS 
1.One comment left. Please help resolve.
2. Please create a roadmap workitem and attach the number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15373/). Please do this firstly if no access: 
Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-10-09 04:27 UTC, opbld31 commented
Learn Build status updates of commit _[8b51068](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b51068f96aa8ccb5e64ca7e2edb4ee6df9e9d24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210090425262134-16001/BuildReport?accessString=ced6eea061aef6a029b43e832b480f3dc368815d60e73c1a9b9100c2eff4ef18).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 14:25 UTC, SuyliuMS commented
roadmap workitem number: 15387

2022-10-11 02:27 UTC, RuiHou105 approved these changes

2022-10-11 02:28 UTC, RuiHou105 commented
@Lauragra  @JarbasHorst please help review this PR when you got time. Thanks.

2022-10-11 20:37 UTC, Danielabom commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +description: "Represents Cloud PC organization mapping between public cloud organization and US government cloud organization."
```suggestion
description: "Represents a Cloud PC organization mapping between a public and US government cloud organizations."
```

2022-10-11 20:37 UTC, Danielabom commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +Represents Cloud PC organization mapping between public cloud organization and US government cloud organization.
```suggestion
Represents a Cloud PC organization mapping between a public and US government cloud organizations.
```

2022-10-11 23:21 UTC, opbld33 commented
Learn Build status updates of commit _[39747d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39747d62a526ae7ca25b0e17b1cfd2d89aec0dde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210112318586720-16001/BuildReport?accessString=27e01e5391199f0bd0b343b5ac59ce502081aa04a10321f1120d7b6c8ab02903).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 23:23 UTC, opbld34 commented
Learn Build status updates of commit _[c63a62a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c63a62a2302ba8d7dca7c6f60bea74847c684758)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210112319478628-16001/BuildReport?accessString=65793f7c5d2f7aa0c7554ce478493028332f3147b9dcd0f44f3349b5f965fe1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 14:05 UTC, opbld34 commented
Learn Build status updates of commit _[e2d024c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2d024cce0287017ee46643f685b7165c096a381)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210121402392074-16001/BuildReport?accessString=a0f52b76fda78c9f12279bf30522bc8d550b30bec056a0a0b2845a8436316752).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 14:22 UTC, Danielabom commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +For GCC (US Government Community Cloud) customers, the Azure Active Directory for tenant is in public cloud, but the Azure resources and Windows 365 Cloud PCs are in US government cloud. This mapping
```suggestion
For GCC (US Government Community Cloud) customers, the Azure Active Directory for the tenant is in a public cloud, but the Azure AD resources and Windows 365 Cloud PCs are in the US government cloud. Therefore, tenant mapping should be set up and maintained while updating the security and compliance requirements for the FedRAMP certification and onboarding to the US Government cloud. Tenant mapping is required for customer administrators when setting up & configuring Windows 365 and for GCC end users accessing their Windows 365 Cloud PCs.
```

2022-10-12 14:30 UTC, Danielabom commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +|organizationIdsInUSGovCloud|String collection|The ID of the tenant in Azure Government corresponding to the GCC (US Government Community Cloud) tenant in public cloud. We only support 1:1 mapping fo
Could we update the first sentence: Azure Government ____? 
My suggestion for the second sentence: We only support 1:1 mapping for now, so this collection can only contain one tenant ID.

2022-10-12 15:01 UTC, Danielabom commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md
> +---
Please rename this file based on the guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming

2022-10-12 15:21 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ApiChange": "Resource",
```suggestion
                    "ApiChange": "Relationship",
```

2022-10-12 15:22 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **crossCloudGovernmentOrganizationMapping** relationship to [virtualEndpoint](https://docs.microsoft.com/en-us/graph/api/resources/intune-virtualEndpoint
```suggestion
                    "Description": "Added the **crossCloudGovernmentOrganizationMapping** navigation property to [virtualEndpoint](https://docs.microsoft.com/en-us/graph/api/resources/intune-virtualEndpoint?view=graph-rest-beta) resource.",
```

2022-10-12 15:23 UTC, Danielabom requested changes
HI @SuyliuMS, thank you for working on this PR. Please review and address my comments. Thanks :)

2022-10-12 15:42 UTC, opbld30 commented
Learn Build status updates of commit _[43ce3c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43ce3c2a1e77592f5f7b61bc8a7d8c8b1482ca4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-post?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210121540304411-16001/BuildReport?accessString=c952f14f0d2ace8079128179a2361f8ad6ec3fd701f8ec03974e79d8327338d6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 15:52 UTC, SuyliuMS commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +|organizationIdsInUSGovCloud|String collection|The ID of the tenant in Azure Government corresponding to the GCC (US Government Community Cloud) tenant in public cloud. We only support 1:1 mapping fo
Fixed

2022-10-12 15:52 UTC, SuyliuMS commented on api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-post.md
> +---
Fixed

2022-10-12 15:55 UTC, opbld30 commented
Learn Build status updates of commit _[0b541cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b541cdb5297cd3b63b14eb219eb239e45ebf680)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-c6b16fa540eeea4e4d112b02795c5b06-4a8332f5)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4a8332f5)
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c6b16fa540eeea4e4d112b02795c5b06-4a8332f5"></a>
### [api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/cloudpccrosscloudgovernmentorganizationmapping-post.md'.`````

<a id="0817dce4456c16725d5333633847d38f-4a8332f5"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml)
 - **Line 10479, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpccrosscloudgovernmentorganizationmapping-post.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210121552235697-16001/BuildReport?accessString=d7f8ef0a132d76da4fcf47836b59eecc37b4efa6315ca6a9c66b71134ebc17b0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 07:04 UTC, opbld32 commented
Learn Build status updates of commit _[1766d46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1766d4683b7dbfa29ed9f664196530053aa79f60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210130701525918-16001/BuildReport?accessString=cf1ca19210fe774d1be91b63382381742ead707045841dceb2e43583013f63f3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 15:46 UTC, Danielabom commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +|organizationIdsInUSGovCloud|String collection|The ID of the tenant in Azure Government corresponding to the GCC (US Government Community Cloud) tenant in public cloud. We only support 1:1 mapping fo
```suggestion
|organizationIdsInUSGovCloud|String collection|The tenant ID in the Azure Government cloud corresponding to the GCC (US Government Community Cloud) tenant in the public cloud. Currently, we support 1:1 mappings, so this collection can only contain one tenant ID.|
```

2022-10-13 15:53 UTC, opbld33 commented
Learn Build status updates of commit _[65c7c6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65c7c6b463ec29c4c16cf7a924dd833f4b89fe95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210131550349785-16001/BuildReport?accessString=c60a1640dd55f8c9ce303199d58bee6b8060041ecfb57a44d00e7d475c6e91ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 02:49 UTC, SuyliuMS commented on api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
> +|organizationIdsInUSGovCloud|String collection|The ID of the tenant in Azure Government corresponding to the GCC (US Government Community Cloud) tenant in public cloud. We only support 1:1 mapping fo
Fixed

2022-10-14 02:50 UTC, opbld30 commented
Learn Build status updates of commit _[c69b6c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c69b6c4d2181a61cddf9d742e6e82c6b5dc0ccda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210140248265868-16001/BuildReport?accessString=3ede93ce9c5448e29ce2e42538669191ff6a023dba4e7ab5c6c374744cfbb124).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 01:38 UTC, opbld32 commented
Learn Build status updates of commit _[7104329](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7104329f25621698ba50a2bb23f11cd6755f8e9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180135594789-16001/BuildReport?accessString=03e4164d5880f8fdff767bb95f3b0bd698ac2988114e23ec161a38c497ce94f6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 03:18 UTC, opbld32 commented
Learn Build status updates of commit _[2c34629](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c3462950dc6162508b19a6f639258bf98914f6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180316036115-16001/BuildReport?accessString=1ab74809e93fa89a5cba52d067c3849d2fee78b07b596a2e9e046a97ce18d82b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 03:20 UTC, opbld32 commented
Learn Build status updates of commit _[88a5b8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88a5b8a6904afc67f652b8c5433dfa5627c24f15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180316427125-16001/BuildReport?accessString=c6bceda2e735b7075d1cd8c0a61b15cbe2f00a82f6f9b9fd815307ce64b483a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 03:24 UTC, opbld32 commented
Learn Build status updates of commit _[da211e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da211e67f48420ff3c06fd09d033e3ba668a5533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180322388349-16001/BuildReport?accessString=5e911387bd77661d937cca83e3e382fded23abcf98714fe5f81d4c641bc1921c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 03:37 UTC, opbld34 commented
Learn Build status updates of commit _[4e1cfc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e1cfc1ca65a14ab5f672f54c296b16140924fc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180326022874-16001/BuildReport?accessString=f85645db6f0a69fef0ba947cfc3c5fa6eeabb04335ed186fd1593c0a194294c0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 03:39 UTC, opbld33 commented
Learn Build status updates of commit _[00b9084](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00b908482a2c587cf7f9fd786e29d1fe28abaad4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpccrosscloudgovernmentorganizationmapping?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpccrosscloudgovernmentorganizationmapping-get?view=graph-rest-beta&branch=pr-en-us-16001) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/suyliu/TenantMapping/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180328178083-16001/BuildReport?accessString=2d8b7623781a86f8eb76f9159f8c16f7ad0ea4a6cdb2ac958748a5027d6bb279).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 03:41 UTC, merged