Delete message API for chat and channel
microsoftgraph/microsoft-graph-docs pull request #16011
Opened 2022-02-28 15:57 UTC by sumitgupta3

This documents the details for the Delete message API for chat and channel.
It provides examples of the combinations of request as well.

2022-02-28 15:59 UTC, opbld33 commented
Docs Build status updates of commit _[9029f02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9029f0285cce269b0737f4a135ba0b96284b7654)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-4191b4f34544b9d886b9039d5ab0b9ea-3dedbf31)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-9691d6c29f56fd3ec9d537c046f2515a-3dedbf31)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-3dedbf31)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |

<a id="4191b4f34544b9d886b9039d5ab0b9ea-3dedbf31"></a>
### [api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md)
 - **Line 92, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````
 - **Line 142, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````
 - **Line 193, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````
 - **Line 243, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````

<a id="9691d6c29f56fd3ec9d537c046f2515a-3dedbf31"></a>
### [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md)
 - **Line 29, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 35, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-3dedbf31"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/toc.yml)
 - **Line 6644, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-delete.md'.`````
 - **Line 6694, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202281557185674-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T15%3A59%3A22Z&sr=b&sp=r&sig=2GMOPtmX3llDOlRpFUt19rwkqEyxKHK9wPHmNI7rim4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-28 17:21 UTC, opbld32 commented
Docs Build status updates of commit _[d4daff6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4daff6c0388820fec39586aab7f276e08c31f29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-4191b4f34544b9d886b9039d5ab0b9ea-fedf24bf)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-9691d6c29f56fd3ec9d537c046f2515a-fedf24bf)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-fedf24bf)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="4191b4f34544b9d886b9039d5ab0b9ea-fedf24bf"></a>
### [api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md)
 - **Line 92, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````
 - **Line 142, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````
 - **Line 193, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````
 - **Line 243, Column 33**: **[Warning: link-out-of-scope]** `````File 'beta/includes/snippets/snippets-sdk-documentation-link.md' referenced by link '../includes/snippets/snippets-sdk-documentation-link.md' will not be built because it is not included in build scope.`````

<a id="9691d6c29f56fd3ec9d537c046f2515a-fedf24bf"></a>
### [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md)
 - **Line 29, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 35, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-fedf24bf"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/toc.yml)
 - **Line 6644, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-delete.md'.`````
 - **Line 6694, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202281719174243-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T17%3A21%3A48Z&sr=b&sp=r&sig=0tem0QBkJvWbrBfew6T%2FvvvAdXj3RnAR5Diy%2BtodAWs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 10:50 UTC, RamjotSingh requested changes

2022-03-01 10:50 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]
Remove all the code tags it will be auto generated later. You have added wrong files.

2022-03-01 10:50 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +### Example 3: Undo Soft-Deleted message in a chat
Undelete a message in chat?
OR
Undo deleted message in a chat

2022-03-01 10:50 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +### Example 4: Undo Soft-Deleted a message in a channel
Same

2022-03-01 10:50 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +### Example 4: Undo Soft-Deleted a message in a channel
Delete and undo delete need to be in unique files. Use the auto generated files because Graph has a certain way of naming actions in docs.

2022-03-01 10:50 UTC, RamjotSingh commented on api-reference/v1.0/toc.yml
> +        - name: Delete message
The API is only in beta right? Dont make v1 changes.

2022-03-01 10:50 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for recovering a deleted message in channel [POST /teams/{team-id}/channels/{channel-id}/messages/{message-id}/undoSoftDelete](https://docs.microsoft.com/en-us
Recovering sounds like something that is lost and cant be restored to its original state using normal processes. Change wording.

2022-03-02 10:18 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +|Delegated (work or school account)| ChatMessage.ReadWrite |
This is what we agreed as per API doc review for chat message and this permission exists as well.

2022-03-02 10:23 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +author: "SumitGupta"
changed

2022-03-02 10:23 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +POST /teams/{team-id}/channels/{channel-id}/messages/{message-id}/softDelete
a reply has a message id and if that is passed, it will delete the message. 
What urls you want me to add ?

2022-03-02 10:29 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]
removed

2022-03-02 10:33 UTC, sumitgupta3 commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for recovering a deleted message in channel [POST /teams/{team-id}/channels/{channel-id}/messages/{message-id}/undoSoftDelete](https://docs.microsoft.com/en-us
changed

2022-03-02 10:35 UTC, sumitgupta3 commented on api-reference/v1.0/toc.yml
> +        - name: Delete message
removed.

2022-03-02 10:37 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +### Example 4: Undo Soft-Deleted a message in a channel
Use the auto generated files => I am not aware how that will happen and i did this looking at other commits in this repo.

2022-03-02 10:41 UTC, opbld32 commented
Docs Build status updates of commit _[c841b3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c841b3c721a61d5b2fc9d182a27ec4c071d6bb64)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-9691d6c29f56fd3ec9d537c046f2515a-9baf6aaf)
[api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="9691d6c29f56fd3ec9d537c046f2515a-9baf6aaf"></a>
### [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md)
 - **Line 29, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 35, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203021038205821-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-02T10%3A41%3A25Z&sr=b&sp=r&sig=ERrVge08iE3SQi5mrJ4J5%2BqV8ufvq%2FKZcV4Mij7ER00%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 23:07 UTC, opbld33 commented
Docs Build status updates of commit _[5084180](https://github.com/microsoftgraph/microsoft-graph-docs/commits/508418082b82e016011443e087b72120b2f698c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-9691d6c29f56fd3ec9d537c046f2515a-9045d9a2)
[api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="9691d6c29f56fd3ec9d537c046f2515a-9045d9a2"></a>
### [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md)
 - **Line 29, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 35, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102301461928-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T23%3A07%3A46Z&sr=b&sp=r&sig=NkGVipokR7wyw3w2vwOwsfuBAh0W8%2FOKueKtT0PjkkY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 06:23 UTC, opbld31 commented
Docs Build status updates of commit _[d3b9193](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3b9193c68519e4b4e9d529fdb47a8840ec4e593)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16011) (>= graph-rest-1.0) | [Details](#user-content-9691d6c29f56fd3ec9d537c046f2515a-9ab1ee61)
[api-reference/beta/api/chatmessage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="9691d6c29f56fd3ec9d537c046f2515a-9ab1ee61"></a>
### [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/v1.0/resources/chatmessage.md)
 - **Line 29, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 35, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````
 - **Line 44, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110621344034-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T06%3A23%3A35Z&sr=b&sp=r&sig=v%2BXRaQocWPIvyLoO%2F%2FMfkOWn0OUZirxCxhp8mIVMFg0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 06:33 UTC, RamjotSingh requested changes

2022-03-11 06:33 UTC, RamjotSingh commented on api-reference/v1.0/resources/chatmessage.md
> +|[Delete reply message in channel](../api/chatmessage-delete.md)|[chatMessage](chatmessage.md)| Delete the single reply message in a channel.|
Undo from v1

2022-03-11 06:33 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +POST /teams/{team-id}/channels/{channel-id}/messages/{message-id}/softDelete
/messages/ID/replies/ID/softDelete that url

2022-03-11 06:33 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +title: "Delete chatMessage in a channel or chat"
The file name looks wrong. Please use automation to generate files.

2022-03-11 06:33 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-delete.md
> +title: "Delete chatMessage in a channel or chat"
Filename and title both

2022-03-14 15:54 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for undelete a message in chat [POST /users/{user-id}/chats/{chat-id}/messages/{message-id}/undoSoftDelete](https://docs.microsoft.com/en-us/graph/api/chatmess
changelog entries: Please follow example 7 of this list: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

According to the CSDL we are just adding 2 operations: softDelete and undoSoftDelete. In this case we just need 2 changelog entries. 

<img width="678" alt="image" src="https://user-images.githubusercontent.com/70350956/158210628-ed27f8f2-3efb-463a-9269-dc25f70c0439.png">

2022-03-14 15:57 UTC, isvargasmsft commented on api-reference/beta/api/chatmessage-delete.md
> +# Delete chatMessage in a channel or chat
Titles and file names: Please follow the guidelines for [filenames ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming)and [topic titles](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title). 

Please use the actual name of the operations: softDelete and undoSoftDelete. These are not CRUD Deletes, but custom operations. It should be clear in the documentation.

2022-03-14 16:04 UTC, isvargasmsft requested changes
Thank you very much for your work in this PR. 

Please follow the guidelines in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211738/Guidelines). 

According to the CSDL, we are adding 2 new custom operations: softDelete and undoSoftDelete. This scenario requires:
1. A method topic for each operation. 
2. Adding a line to the methods column in the binding parameter topic. In this case, go to the chatMessage topic and add an entry for each operation in the methods column. 
3. TOC (Table of Contents) entry for each operation in the corresponding node (under chatMessage resource type, after the CRUD operations). 
4. Changelog entries for each operation. 

Please feel free to ping me on the side if you have any questions.

Kind regards, 

Isaac Vargas

PS: Please clarify is this PR was manually generated or if you used a generator tool (Graph Stutio for example).

2022-03-24 09:28 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +# Delete chatMessage in a channel or chat
I have done it manually, still learning how to generate it automatically.

2022-03-24 09:29 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-delete.md
> +POST /teams/{team-id}/channels/{channel-id}/messages/{message-id}/softDelete
No, I have not added this url in code Or in review Or in design doc.

2022-04-05 15:57 UTC, isvargasmsft commented
Hello @sumitgupta3, 

What is the status of this PR? Please feel free to ping me on the side if you have questions regarding the comments above. 

Once you have addressed the feedback, please add the label "review feedback addressed". 

Kind regards, 

Isaac

2022-04-06 05:20 UTC, sumitgupta3 commented
Hello Isaac,
I am willing to close this ASAP.
But the process is broken and I am not able to install graph studio on machine to complete this task.
I am in talks with James, waiting for his response.

Thanks,
Sumit Gupta.
From: Isaac Vargas ***@***.***>
Sent: 05 April 2022 21:28
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Sumit Gupta ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] Delete message API for chat and channel (PR #16011)


Hello @sumitgupta3<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsumitgupta3&data=04%7C01%7Csumitgupta%40microsoft.com%7C55814af64ba34839cc3208da171d0d17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637847710860375433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N7g9u3CEGYJrKm0ilT5SSw5A59xzwd3XY1bJ2GH6u4o%3D&reserved=0>,

What is the status of this PR? Please feel free to ping me on the side if you have questions regarding the comments above.

Once you have addressed the feedback, please add the label "review feedback addressed".

Kind regards,

Isaac

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F16011%23issuecomment-1088920878&data=04%7C01%7Csumitgupta%40microsoft.com%7C55814af64ba34839cc3208da171d0d17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637847710860425434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jd4gZgP3QhYHljbdyIlNEAiXFwwUxx0efRRzLoOtAbY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXYRFZRH476RYAWO53RQOI3VDRPIJANCNFSM5PRPKRXA&data=04%7C01%7Csumitgupta%40microsoft.com%7C55814af64ba34839cc3208da171d0d17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637847710860425434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QPZ%2Bbikq1Z%2Bh5XpSaldcNLeSZv8E3htrDHONOnfzvns%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-07 13:38 UTC, opbld31 commented
Docs Build status updates of commit _[0d4f37c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d4f37cb351564285e1ad106ba84e051f0415bf2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-21e5cb59)

<a id="21e5cb59"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204071338080114-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T13%3A38%3A48Z&sr=b&sp=r&sig=UCZLcIbRolcwdvW9apV9uM2CwAlEdaCNuaXZvlP3YdI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 13:46 UTC, opbld33 commented
Docs Build status updates of commit _[b0c0433](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0c0433ae4a14935b10192625c4f90db83424d3c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1f25af7e)

<a id="1f25af7e"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204071346093433-16011%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T13%3A46%3A43Z&sr=b&sp=r&sig=b0v2dAftkL0zLTRKDUXEaJFI%2BZjg2xdrqVRXQr0yqus%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 13:51 UTC, sumitgupta3 commented
Hello Isaac,
Finally, I was able to generate automated files via graph studio and have added the new files and PR is updated and ready for review.
Please have a look.

From: Isaac Vargas ***@***.***>
Sent: 05 April 2022 21:28
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Sumit Gupta ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] Delete message API for chat and channel (PR #16011)


Hello @sumitgupta3<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsumitgupta3&data=04%7C01%7Csumitgupta%40microsoft.com%7C55814af64ba34839cc3208da171d0d17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637847710860375433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N7g9u3CEGYJrKm0ilT5SSw5A59xzwd3XY1bJ2GH6u4o%3D&reserved=0>,

What is the status of this PR? Please feel free to ping me on the side if you have questions regarding the comments above.

Once you have addressed the feedback, please add the label "review feedback addressed".

Kind regards,

Isaac

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F16011%23issuecomment-1088920878&data=04%7C01%7Csumitgupta%40microsoft.com%7C55814af64ba34839cc3208da171d0d17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637847710860425434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jd4gZgP3QhYHljbdyIlNEAiXFwwUxx0efRRzLoOtAbY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXYRFZRH476RYAWO53RQOI3VDRPIJANCNFSM5PRPKRXA&data=04%7C01%7Csumitgupta%40microsoft.com%7C55814af64ba34839cc3208da171d0d17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637847710860425434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QPZ%2Bbikq1Z%2Bh5XpSaldcNLeSZv8E3htrDHONOnfzvns%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-08 14:21 UTC, isvargasmsft commented on api-reference/v1.0/resources/chatmessage.md
> +|[Undelete message in channel](../api/chatmessage-undoSoftdelete.md)|[chatMessage](chatmessage.md)| Undelete the single root message in a channel.|
Are these methods also being introduced to v1? I didn't see that in the CSDL. Please clarify or remove this from the v1 topic.

2022-04-08 14:22 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "softDelete"
Description: We are adding the method to the chatMessage resource type, please fix this in the description and add the proper link. 
Target: should be chatMessage

2022-04-08 14:22 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "softDelete"
Same for the other entry below.

2022-04-08 14:26 UTC, opbld32 commented
Docs Build status updates of commit _[d87d4a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d87d4a356c90fb8f092acf10d1956a8560b0a77a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4b168c2a)

<a id="4b168c2a"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081425040893-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T14%3A26%3A56Z&sr=b&sp=r&sig=TnCdO2Sqwosv89u%2BCDhQqBE2hjNFcS4qtO5129a4BSY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 14:28 UTC, opbld30 commented
Docs Build status updates of commit _[800621d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/800621deb1188d134ceb50f86ccb3b24476f2312)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8cec839a)

<a id="8cec839a"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081426504058-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T14%3A28%3A44Z&sr=b&sp=r&sig=ynR7bddxlEESAO4eoNzYGuyQaiyqZgWNfTFZ6DcJZU4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 14:29 UTC, isvargasmsft requested changes
Hello @sumitgupta3, 

Excellent work addressing the feedback. Just a couple of pending items:
1. Please clarify if the methods are being introduced to v1 also. In that case we will need to add the topics to v1, the changelog and the TOC. If not, then please just remove the changes to the v1 topic. 
2. Please fix some issues with the changelog: just the target and description of the entries should be fixed to reflect chatMessage. 

Once this is fixed, I think the PR is in good shape. 

Kind regards, 

Isaac

2022-04-11 05:38 UTC, sumitgupta3 commented on api-reference/v1.0/resources/chatmessage.md
> +|[Undelete message in channel](../api/chatmessage-undoSoftdelete.md)|[chatMessage](chatmessage.md)| Undelete the single root message in a channel.|
ahh yes, we release in v1 later. I will remove it.

2022-04-11 05:47 UTC, sumitgupta3 commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "softDelete"
yes added.

2022-04-11 05:50 UTC, opbld30 commented
Docs Build status updates of commit _[1de888f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1de888ff2c7d8709966014f88a42d1180d3be276)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5ffb4ab4)

<a id="5ffb4ab4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204110549395324-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T05%3A50%3A11Z&sr=b&sp=r&sig=Imk9fCVyLc7vNSbhLl0mM1LGTP9OhTYAaC5drynNqhQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 05:52 UTC, sumitgupta3 commented
Thanks, I have updated it and pushed changes. Please have a look !

From: Isaac Vargas ***@***.***>
Sent: 08 April 2022 20:00
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Sumit Gupta ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] Delete message API for chat and channel (PR #16011)


@isvargasmsft requested changes on this pull request.

Hello @sumitgupta3<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsumitgupta3&data=05%7C01%7Csumitgupta%40microsoft.com%7Ccae27e6ee97444127cf508da196c484c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850250123998209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vYKN6%2FwffZT845pE9gGjBGKO1Ys6Zx5oDtE7dvRf0Mw%3D&reserved=0>,

Excellent work addressing the feedback. Just a couple of pending items:

  1.  Please clarify if the methods are being introduced to v1 also. In that case we will need to add the topics to v1, the changelog and the TOC. If not, then please just remove the changes to the v1 topic.
  2.  Please fix some issues with the changelog: just the target and description of the entries should be fixed to reflect chatMessage.

Once this is fixed, I think the PR is in good shape.

Kind regards,

Isaac

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F16011%23pullrequestreview-936531240&data=05%7C01%7Csumitgupta%40microsoft.com%7Ccae27e6ee97444127cf508da196c484c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850250123998209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TKGBixEmRFJaUlAN8%2FG8oRKutjO0BBsNRQ5iX8sFYJ0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXYRFZVM7G7SQVZU2EWVXMDVEA7HBANCNFSM5PRPKRXA&data=05%7C01%7Csumitgupta%40microsoft.com%7Ccae27e6ee97444127cf508da196c484c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850250123998209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z%2FgdK9Qry90%2FISGOQuBtFCysESFtJ5C9iTVCdaIDZUA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-13 10:44 UTC, opbld31 commented
Docs Build status updates of commit _[3deddd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3deddd885e414e6755c2e2e8902720f1b6d37520)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-61b1e95e)

<a id="61b1e95e"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204131044281092-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T10%3A44%3A54Z&sr=b&sp=r&sig=%2BKD%2FjgpAILQWJ0OVUsjP2v2LQyjoKBimiYaTSr%2Fy%2Bu4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 10:46 UTC, opbld33 commented
Docs Build status updates of commit _[d97c1c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d97c1c65c42a137d083cabc09de5811e3c46f88d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-38a422b4)

<a id="38a422b4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204131045423512-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T10%3A46%3A25Z&sr=b&sp=r&sig=7DOc8R1aza5m%2FfdYBS6fq9l82Ny0ykinYLZ%2BIZRXVbY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 10:59 UTC, opbld32 commented
Docs Build status updates of commit _[f47ce44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f47ce4472c4c03020a0b41bf88adb5a0a313a5a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-98877ca6)

<a id="98877ca6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204131058517912-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T10%3A59%3A26Z&sr=b&sp=r&sig=YoWH8FFDO0cYHx0Fu0HXPwwk%2BhbU3T1wFJfsK2SLosg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 11:01 UTC, opbld34 commented
Docs Build status updates of commit _[9009097](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9009097d7a0a54102cd8dd66222db667c1ab2f0b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b5284472)

<a id="b5284472"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204131101255534-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T11%3A01%3A55Z&sr=b&sp=r&sig=Z%2Bb%2FC27tAzZ64cyqhDVYGn3dUR%2BJHhksua1VDi5wLJY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 17:12 UTC, isvargasmsft approved these changes

2022-04-19 01:31 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +description: "Delete a single message (without its replies) in a channel or a chat."
Should we update the description to align with the summary sentence? "Delete a single message or message reply..."

2022-04-19 01:32 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +>**Note:** The response object shown here might be shortened for readability.
Remove this note since there's no response body.

2022-04-19 01:32 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +### Example 1: Soft-Delete message in a chat
Global: Please only cap the first word of the heading, so "Soft-delete". Please change all instances.

2022-04-19 01:33 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST https://graph.microsoft.com/beta/users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
FYI, examples are more useful when they include actual IDs instead of placeholders - please add if you can.

2022-04-19 01:36 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
Because this operation can be performed on a user, we should surface it in the user resource topic and in the TOC under Users/Teamwork.

2022-04-19 01:37 UTC, Lauragra commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +description: "Undelete a single message (without its replies) in a channel or a chat."
Same comment as previous - update to say "single message or message reply...".

2022-04-19 01:39 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +> **Note**: Permissions marked with ** are supported only for backward compatibility. We recommend that you update your solutions to use an alternative permission listed in the previous table and avo
Why is this note here when nothing is marked with **? Please remove. Also, please add periods after Not supported globally.

2022-04-19 01:39 UTC, Lauragra commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/undoSoftDelete
Same comment as previous, please also surface under Users/Teamwork.

2022-04-19 01:40 UTC, Lauragra commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +### Example 1: Undo Soft-Deleted message in a chat
Global: Lowercase "Soft-Deleted".

2022-04-19 01:40 UTC, Lauragra commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +>**Note:** The response object shown here might be shortened for readability.
Global: Remove these notes.

2022-04-19 01:41 UTC, Lauragra commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +### Example 3: Undo Soft-Deleted message of a reply.
Also remove the period from the heading.

2022-04-19 01:43 UTC, Lauragra commented on api-reference/beta/resources/chatmessage.md
> +|[Undelete message in channel](../api/chatmessage-undoSoftdelete.md)|[chatMessage](chatmessage.md)| Undelete the message in a channel.|
Global: Please change "Undelete" to "Undo the deletion of...".

2022-04-19 01:49 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Undelete message
Maybe for this TOC entry: "Undo message deletion". Also please make the file name in the link lowercase.

2022-04-19 01:56 UTC, opbld33 commented
Docs Build status updates of commit _[de011fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de011fe34f588907b19ffb73fe5c770595a37e49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-28812d79)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-28812d79)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-28812d79"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-28812d79"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204190154111459-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T01%3A56%3A02Z&sr=b&sp=r&sig=7JpESUgI8qBnOad32ByIkZD2ZLp8gOxIc%2BbtTa5hDVA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 14:08 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +description: "Delete a single message (without its replies) in a channel or a chat."
updated

2022-04-19 14:08 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +> **Note**: Permissions marked with ** are supported only for backward compatibility. We recommend that you update your solutions to use an alternative permission listed in the previous table and avo
Done

2022-04-19 14:09 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
action is not clear to me. please elaborate.

2022-04-19 14:10 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +### Example 1: Soft-Delete message in a chat
done

2022-04-19 14:18 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST https://graph.microsoft.com/beta/users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
Ok, I have changed it with IDs.

2022-04-19 14:18 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +description: "Undelete a single message (without its replies) in a channel or a chat."
done

2022-04-19 14:20 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +>**Note:** The response object shown here might be shortened for readability.
removed

2022-04-19 14:20 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-undosoftdelete.md
> +### Example 3: Undo Soft-Deleted message of a reply.
done

2022-04-19 14:35 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
The action softDelete is performed on ChatMessage resource and user is just there in heirarchy as chat message happens under a user. sequence-wise => User -> Chat thread -> chat message (action performed on chat message.)

2022-04-19 14:36 UTC, opbld33 commented
Docs Build status updates of commit _[4b3daf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b3daf1a07b9f99a601f2259138b152ee87dd6d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-5e843acd)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-5e843acd)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-5e843acd"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-5e843acd"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204191433001620-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T14%3A36%3A06Z&sr=b&sp=r&sig=jBq7kz5%2Bovf4NQl6YYAaA%2BpWUGiXj32wYz076oOYkUA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 15:54 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
We list operations that can be performed on the signed-in user in the User resource topic: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta

And surface them in the TOC here:
https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta

In addition to surfacing them under the Teamwork node of the TOC.

2022-04-20 08:07 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
I checked this link : https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta 
There is no mention of create / post / update Message here, so I should not be adding about delete message here.

However, I was able to find the create / post / update Message here https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta

I think its not needed, can you check once again ? chat messages are always on user object. And all operations are only defined here https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta inside teamwork.

2022-04-21 03:26 UTC, Lauragra commented on api-reference/beta/api/chatmessage-softdelete.md
> +POST /users/{userId}/chats/{chatsId}/messages/{chatMessageId}/softDelete
Okay, for now let's keep the same pattern and leave as-is.

2022-04-21 03:38 UTC, opbld33 commented
Docs Build status updates of commit _[72fefc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72fefc8f0066cc9112acab87f6852158be675954)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-cfbf6a87)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-cfbf6a87)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-cfbf6a87"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-cfbf6a87"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210329108377-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A38%3A17Z&sr=b&sp=r&sig=q1DL9kD5u5ObpZuncOJsfyqwwRiG1qdWQPip3ktO%2Fko%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:38 UTC, Lauragra approved these changes

2022-04-21 03:41 UTC, opbld34 commented
Docs Build status updates of commit _[a06b3fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a06b3fee914ed9c72c4a4523247b521394c0f8db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-7eb70526)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-7eb70526)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-7eb70526"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-7eb70526"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210332471291-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A41%3A58Z&sr=b&sp=r&sig=7m3lehcGkxa2VGW7DsNEIpQDEce7cyk33SRNQG98svk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:43 UTC, opbld31 commented
Docs Build status updates of commit _[dbc9bab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbc9babf5953a30a96b78879aa3b54c7fbfaa5a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-8911d09e)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-8911d09e)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-8911d09e"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-8911d09e"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210331275614-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A43%3A47Z&sr=b&sp=r&sig=teCxHn2WJySPaOcJRxCM3byJhOB%2BTX4ZFMOcJe7PT7g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:45 UTC, opbld32 commented
Docs Build status updates of commit _[b00d8d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b00d8d09b1d761df72e1b4973df446e8325bea62)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-c57e5c69)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-c57e5c69)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-c57e5c69"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-c57e5c69"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210330483833-16011%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A45%3A33Z&sr=b&sp=r&sig=wDLKwS3LkZDzZ8Y99a7HjfLf%2BIpnrxF9FnRdZYcoTtc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 12:56 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +title: "chatMessage: softDelete"
[DO NOT MERGE] AS ONE OF THE PERMISSION WHITELIST IS STILL PENDING, WE WILL MERGE THIS AFTER PERMISSION IS PRESENT IN PROD.

2022-07-12 10:20 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-softdelete.md
> +title: "chatMessage: softDelete"
permission is launched and code is also deployed. Its safe to push this now.

2022-07-13 03:41 UTC, opbld34 commented
Docs Build status updates of commit _[e4952f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4952f93fcdbbb57a764fde82b1c32104f2d0063)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-softdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-f2a7212b77db47b450dd5d5bf9bbc699-b6164a1a)
[api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-undosoftdelete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) | [Details](#user-content-b5052150b299d9953a192a1126ba933c-b6164a1a)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-softdelete?view=graph-rest-beta&branch=pr-en-us-16011) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2a7212b77db47b450dd5d5bf9bbc699-b6164a1a"></a>
### [api-reference/beta/api/chatmessage-softdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-softdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

<a id="b5052150b299d9953a192a1126ba933c-b6164a1a"></a>
### [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/delete-message/api-reference/beta/api/chatmessage-undosoftdelete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130339338151-16011/BuildReport?accessString=74382e360e529c66f1f7646e285f95ea7f45aecf1b74497cce2d6d1e9f212103).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 03:49 UTC, merged