Adding new resource [SharePointTenantSettings] to FileServices workload. API at /admin/sharepoint/settings
microsoftgraph/microsoft-graph-docs pull request #16047
Opened 2022-03-02 23:40 UTC by liamfernandez

As a part of the SharePoint Tenant Admin team, I am working on exposing a new endpoint through MS-Graph that will allow admins or partial-admin users to read and manage tenant-level settings.

The **SharePointSettings** resource contains information about the organizational settings for SharePoint/OneDrive workload.

Global admin, SharePoint admin, or appropriate partial-admin role can read or update the SharePoint/OneDrive settings at the organization level.

Only Read & Update of tenant settings supported. GET & PATCH @ /admin/sharepoint/settings

2022-03-02 23:42 UTC, opbld34 commented
Docs Build status updates of commit _[2eb82f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eb82f2ca751569cac7d56d7805cdd0af2c04918)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/admin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/admin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/admin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-3c79b62b0c74b60f1892c391044db8dc-7615cfcf)
[api-reference/beta/api/admin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/admin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/admin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e02f093ad000661edf0546578ced5a2c-7615cfcf)
[api-reference/beta/resources/admin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-9fd186f19aa5bd3e7afa759284bf3faa-7615cfcf)
[api-reference/beta/resources/admin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-0d917814610f540d7618266055167de9-7615cfcf)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-7615cfcf)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |

<a id="3c79b62b0c74b60f1892c391044db8dc-7615cfcf"></a>
### [api-reference/beta/api/admin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/admin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Admin'.`````

<a id="e02f093ad000661edf0546578ced5a2c-7615cfcf"></a>
### [api-reference/beta/api/admin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/admin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Admin'.`````

<a id="9fd186f19aa5bd3e7afa759284bf3faa-7615cfcf"></a>
### [api-reference/beta/resources/admin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin-settings.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 15**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 11, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/admin-settings.md(11,1), beta/resources/settings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 11, Column 1**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/admin-settings.md(11,1), beta/resources/settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="0d917814610f540d7618266055167de9-7615cfcf"></a>
### [api-reference/beta/resources/admin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'admin'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-7615cfcf"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/admin-settings.md(11,1), beta/resources/settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/admin-settings.md(11,1), beta/resources/settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203022340076128-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-02T23%3A42%3A04Z&sr=b&sp=r&sig=xKImEZjAasr45sPjmdYIEW5ZHQZXudV3efc3WI9khu8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions [...]

2022-03-04 00:03 UTC, opbld32 commented
Docs Build status updates of commit _[9dc5c69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dc5c69a9b6c723d272a03f711c0ce29170d9472)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-f6503757)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-f6503757)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-4d04fc9d309050b1dc92bd57669049d2-f6503757)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-f6503757)

<a id="b5ab71e4a2043d7003a453eaada36767-f6503757"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Tenant Admin'.`````

<a id="f44e5d89933907c60840042688e5122b-f6503757"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Tenant Admin'.`````

<a id="4d04fc9d309050b1dc92bd57669049d2-f6503757"></a>
### [api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md)
 - **Line 26, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/admin-sharepoint.md'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-f6503757"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 15**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040001256005-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T00%3A03%3A32Z&sr=b&sp=r&sig=y4DWNN4nj8yoQB3b0p9RKOrICnst6RmsI15UUHw2wxI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 00:10 UTC, opbld30 commented
Docs Build status updates of commit _[868c0e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/868c0e02175d0cc0d5710ebd9ce904da2a892cb2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-38624ff6)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-38624ff6)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-4d04fc9d309050b1dc92bd57669049d2-38624ff6)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-38624ff6)
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-38624ff6"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Tenant Admin'.`````

<a id="f44e5d89933907c60840042688e5122b-38624ff6"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Tenant Admin'.`````

<a id="4d04fc9d309050b1dc92bd57669049d2-38624ff6"></a>
### [api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md)
 - **Line 26, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/admin-sharepoint.md'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-38624ff6"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 15**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040008258985-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T00%3A10%3A32Z&sr=b&sp=r&sig=27qHin9cYF21gSFh02EfUVDXr4bP7J%2FR8oDeUesLtsA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 00:12 UTC, opbld33 commented
Docs Build status updates of commit _[0206a20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0206a20e24c23a292080f56a94e672aec0dad196)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-e3e3af56)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-e3e3af56)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-4d04fc9d309050b1dc92bd57669049d2-e3e3af56)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-e3e3af56)
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-e3e3af56"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Tenant Admin'.`````

<a id="f44e5d89933907c60840042688e5122b-e3e3af56"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Tenant Admin'.`````

<a id="4d04fc9d309050b1dc92bd57669049d2-e3e3af56"></a>
### [api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md)
 - **Line 26, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/admin-sharepoint.md'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-e3e3af56"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 15**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040008514722-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T00%3A12%3A31Z&sr=b&sp=r&sig=57n71LYqxhh%2FuZ2NSMb7Noz8z6AWmbo%2BY33OkkS5L%2BU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 00:22 UTC, opbld34 commented
Docs Build status updates of commit _[a1b9802](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1b980239c46df0ee6b278b98af6f1e740df87e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-d6e1e43b)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-d6e1e43b)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-d6e1e43b)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-d6e1e43b)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-d6e1e43b"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-d6e1e43b"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-d6e1e43b"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 15**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-d6e1e43b"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040019572875-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T00%3A22%3A07Z&sr=b&sp=r&sig=RQcQRV9YZz3jEFeE%2BOZ%2Bz0xImB3k1iQ8hcrQ3s35ILs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 03:02 UTC, opbld30 commented
Docs Build status updates of commit _[50206bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50206bfdbd608cf1043c1b7b4c999e8baa34bc60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-e53dd6a1)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-e53dd6a1)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-e53dd6a1)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-e53dd6a1)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-e53dd6a1)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-e53dd6a1"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-e53dd6a1"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-e53dd6a1"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-e53dd6a1"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-e53dd6a1"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040258512792-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T03%3A02%3A10Z&sr=b&sp=r&sig=ZhSdjfXqAFqfsy0UKUDRGa%2B6g3Cjk8fVq1fZ2cSC3iM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 03:24 UTC, opbld33 commented
Docs Build status updates of commit _[5104216](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5104216b5c603a84e891eb40c4f52fce61a08da5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-2180f21a)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-2180f21a)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-2180f21a)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-2180f21a)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-2180f21a)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-2180f21a"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-2180f21a"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-2180f21a"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-2180f21a"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-2180f21a"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040322565013-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T03%3A24%3A52Z&sr=b&sp=r&sig=3Cz8ImQZ9JmEYGD3fA1dz2oX8hV7VacHHXjvt%2FDW6mw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 06:19 UTC, opbld31 commented
Docs Build status updates of commit _[a524904](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a524904bd5cc998951f6101b440b2d01a2e01b93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-5877d38d)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-5877d38d)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-5877d38d)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-5877d38d)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-5877d38d)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-5877d38d"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-5877d38d"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-5877d38d"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-5877d38d"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-5877d38d"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040616590963-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T06%3A19%3A08Z&sr=b&sp=r&sig=Qt1wEZ%2FNhivzmC5eXEdNNXXhOUxbzD%2BOWTE4n43G8n8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 01:32 UTC, opbld30 commented
Docs Build status updates of commit _[217e660](https://github.com/microsoftgraph/microsoft-graph-docs/commits/217e66010f7d8d4f35770f869484fbc398a22ab6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-1dc5c3c3)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-1dc5c3c3)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-1dc5c3c3)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-1dc5c3c3)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-1dc5c3c3)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-1dc5c3c3"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-1dc5c3c3"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-1dc5c3c3"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-1dc5c3c3"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-1dc5c3c3"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203090131036630-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T01%3A32%3A41Z&sr=b&sp=r&sig=AUytF%2FRrm3XdO%2FHz%2B2HLxajxui1qQDLqorq%2F4HO2XCw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 00:04 UTC, opbld33 commented
Docs Build status updates of commit _[08b9204](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08b9204fbc5c522594e35f990219ed6d4ac05463)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-e2bb36ef)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-e2bb36ef)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-e2bb36ef)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-e2bb36ef)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-e2bb36ef)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-e2bb36ef"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-e2bb36ef"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-e2bb36ef"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-e2bb36ef"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-e2bb36ef"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110002368152-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T00%3A04%3A41Z&sr=b&sp=r&sig=UmUmFpZPT0fYcPyLfeDWD0TkIL38wFvDPElD7UR70Kc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 00:45 UTC, opbld34 commented
Docs Build status updates of commit _[e66a867](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e66a867cebcc1796c767fc96edbf97eed1beec9f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-aa76c2a6)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-aa76c2a6)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-aa76c2a6)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-aa76c2a6)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-aa76c2a6)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-aa76c2a6"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f44e5d89933907c60840042688e5122b-aa76c2a6"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-aa76c2a6"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-aa76c2a6"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="e022cc1d2518ec2813116a62b6420aac-aa76c2a6"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203110043097462-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T00%3A45%3A08Z&sr=b&sp=r&sig=ajagk%2Bb1RzuRl%2FcAyC3Dj2maXbHX3AiTCByAXP7%2FdF8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs B [...]

2022-03-11 00:58 UTC, opbld33 commented
Docs Build status updates of commit _[be04ed9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be04ed9ddad165bec83aa28f1d28fe158a8b0d7a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-6f330ca7)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-6f330ca7)
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-1db4daf070078482107cefeb840d1304-6f330ca7)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-6f330ca7)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-6f330ca7)
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-3421c232e169d6e47073a35627f861fb-6f330ca7)
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b517b119fdcedbc3dbd320537699d727-6f330ca7)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-6f330ca7)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-6f330ca7"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="f44e5d89933907c60840042688e5122b-6f330ca7"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="1db4daf070078482107cefeb840d1304-6f330ca7"></a>
### [api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-6f330ca7"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-6f330ca7"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="3421c232e169d6e47073a35627f861fb-6f330ca7"></a>
### [api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="b517b119fdcedbc3dbd32053 [...]

2022-03-17 17:47 UTC, opbld33 commented
Docs Build status updates of commit _[bf4df8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf4df8afc8723a94f542484b1c46872daed05fd1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-f476d882)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-f476d882)
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-1db4daf070078482107cefeb840d1304-f476d882)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-f476d882)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-f476d882)
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-3421c232e169d6e47073a35627f861fb-f476d882)
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b517b119fdcedbc3dbd320537699d727-f476d882)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-f476d882)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-f476d882"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="f44e5d89933907c60840042688e5122b-f476d882"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="1db4daf070078482107cefeb840d1304-f476d882"></a>
### [api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-f476d882"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-f476d882"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="3421c232e169d6e47073a35627f861fb-f476d882"></a>
### [api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="b517b119fdcedbc3dbd32053 [...]

2022-03-31 20:40 UTC, opbld34 commented
Docs Build status updates of commit _[1ce0d6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ce0d6b71a05ca5edf14d315896dafdb73c59161)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-1799d4b9)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-1799d4b9)
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-1db4daf070078482107cefeb840d1304-1799d4b9)
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-52eabb0ef0592ccc719520c1d02ab560-1799d4b9)
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-363d0e405f10b797b6bdf6df89f0f7f0-1799d4b9)
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-3421c232e169d6e47073a35627f861fb-1799d4b9)
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b517b119fdcedbc3dbd320537699d727-1799d4b9)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-1799d4b9)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-1799d4b9"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="f44e5d89933907c60840042688e5122b-1799d4b9"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="1db4daf070078482107cefeb840d1304-1799d4b9"></a>
### [api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="52eabb0ef0592ccc719520c1d02ab560-1799d4b9"></a>
### [api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantAdmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="363d0e405f10b797b6bdf6df89f0f7f0-1799d4b9"></a>
### [api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="3421c232e169d6e47073a35627f861fb-1799d4b9"></a>
### [api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'SharePoint'.`````

<a id="b517b119fdcedbc3dbd32053 [...]

2022-04-01 16:17 UTC, samkabue commented on api-reference/beta/resources/admin.md
> +|sharepoint|[microsoft.graph.tenantAdmin.sharepoint](../resources/tenantAdmin-sharepoint.md)|A container for administrative resources to manage a tenant's SharePoint/OneDrive settings.|
I see "SharePoint and OneDrive" in a lot of other docs; I wonder if that's the formal name for this?

2022-04-01 16:17 UTC, samkabue commented on api-reference/beta/resources/tenantAdmin-settings.md
> +description:  "The settings resource contains information about the organization settings for the SharePoint and OneDrive for Business workload. Refer to [tenant] for details."
"OneDrive for Business" or just "OneDrive"? We should standardize across the pages in this PR

2022-04-01 16:17 UTC, samkabue commented on api-reference/beta/resources/tenantAdmin-settings.md
> +| deletedUserPersonalSiteRetentionPeriodInDays       | Int                          | Integer representing the number of days for preserving a deleted user's OneDrive..
double `..`

2022-04-01 16:17 UTC, samkabue commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +description: "Entity that acts as a container for administrative resources to manage a tenant's sharepoint/onedrive settings."
See other comment about standardizing this

2022-04-01 16:17 UTC, samkabue commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +Entity that acts as a container for administrative resources to manage a tenant's sharepoint/onedrive settings.
same

2022-04-01 16:17 UTC, samkabue commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +|settings|[microsoft.graph.tenantAdmin.settings](../resources/tenantAdmin-settings.md)|Represents the organization settings for the SharePoint and OneDrive for Business workload.|
same

2022-04-01 18:56 UTC, liamfernandez commented on api-reference/beta/resources/admin.md
> +|sharepoint|[microsoft.graph.tenantAdmin.sharepoint](../resources/tenantAdmin-sharepoint.md)|A container for administrative resources to manage a tenant's SharePoint/OneDrive settings.|
Standardized from our thread with Kaarin

2022-04-01 18:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +description:  "The settings resource contains information about the organization settings for the SharePoint and OneDrive for Business workload. Refer to [tenant] for details."
Standardized from our thread with Kaarin. Should not use OneDrive for Business

2022-04-01 18:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +| deletedUserPersonalSiteRetentionPeriodInDays       | Int                          | Integer representing the number of days for preserving a deleted user's OneDrive..
removed here and in the update file

2022-04-01 18:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +Entity that acts as a container for administrative resources to manage a tenant's sharepoint/onedrive settings.
fixed

2022-04-01 18:57 UTC, opbld33 commented
Docs Build status updates of commit _[b03bc2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b03bc2f8bc51cebca6c61b2ef35be6d345bd497e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204011855314168-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T18%3A57%3A34Z&sr=b&sp=r&sig=q8ut6%2FUWdgsFp%2FLaDqklT4jwN8eXV1zSpy4ewfPsJEw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 18:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +description: "Entity that acts as a container for administrative resources to manage a tenant's sharepoint/onedrive settings."
standardized

2022-04-01 18:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +|settings|[microsoft.graph.tenantAdmin.settings](../resources/tenantAdmin-settings.md)|Represents the organization settings for the SharePoint and OneDrive for Business workload.|
fixed

2022-04-01 18:59 UTC, opbld32 commented
Docs Build status updates of commit _[4037d5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4037d5e273848c2c692e358bfda7119cb1b09b4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/api/tenantAdmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204011856369840-16047%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T18%3A59%3A36Z&sr=b&sp=r&sig=AkAXFUTQre5zwinJEtcI83%2BI9pw4LYPCz3HoMGWfUa4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 21:00 UTC, samkabue commented on api-reference/beta/api/tenantAdmin-settings-update.md
> +description: "Update the properties of a settings object. Allows users to update organization-level settings that pertain to SharePoint and OneDrive."
"tenant admin settings resource"?

2022-04-01 21:05 UTC, samkabue approved these changes

2022-04-01 21:06 UTC, liamfernandez commented
Add a section for saying which user roles can GET and UPDATE. link to RBAC documentation

2022-04-26 22:22 UTC, opbld30 commented
Docs Build status updates of commit _[f965a1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f965a1e9c9733a3f3b6731c54004c7c7445655b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-dbf830c3)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-dbf830c3)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-dbf830c3"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 27, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 27, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide. Otherwise, remove the view parameter.`````

<a id="f44e5d89933907c60840042688e5122b-dbf830c3"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 27, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 27, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204262218188812-16047%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T22%3A22%3A15Z&sr=b&sp=r&sig=HnR%2BjhVkdwMsntj%2B%2FAcQnnIuZYxKnJQxICfHfN09Z5c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-e [...]

2022-04-26 22:24 UTC, liamfernandez commented
>

2022-04-26 22:29 UTC, opbld34 commented
Docs Build status updates of commit _[f965a1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f965a1e9c9733a3f3b6731c54004c7c7445655b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-7c6cadc8)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-7c6cadc8)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-7c6cadc8"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 27, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 27, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide. Otherwise, remove the view parameter.`````

<a id="f44e5d89933907c60840042688e5122b-7c6cadc8"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 27, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 27, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204262224206733-16047%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T22%3A29%3A47Z&sr=b&sp=r&sig=IIotciOcUbESgtAZc5XxKB6mnvEkKYjN41LcYCAQjQk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-o [...]

2022-04-26 22:39 UTC, opbld33 commented
Docs Build status updates of commit _[10452bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10452bdacaa8ced423df5302badc472f50bad55a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-377ab945)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-377ab945)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-377ab945"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/add-users/about-admin-roles' will be broken in isolated environments. Replace with a relative link.`````

<a id="f44e5d89933907c60840042688e5122b-377ab945"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/add-users/about-admin-roles' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204262229077755-16047%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T22%3A39%3A52Z&sr=b&sp=r&sig=Y9H8Xw8VM6Omq0tqnmUy5Vz4bBorS98%2BsKan7YM6ENU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 22:54 UTC, opbld31 commented
Docs Build status updates of commit _[9871599](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9871599c52f1d2ad4c67e4fc09fbef794e7c2922)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-15ac6110)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-15ac6110)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-15ac6110"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/add-users/about-admin-roles' will be broken in isolated environments. Replace with a relative link.`````

<a id="f44e5d89933907c60840042688e5122b-15ac6110"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/add-users/about-admin-roles' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205112252587142-16047/BuildReport?accessString=f3c6cb88322f2be0fe5d80951e274a9d38ba711f3269d4f256d630b6f0984e93).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/tenantAdmin-settings.md
> +### ImageTaggingOption property values
For documenting enums, please use the resource topic if you need to provide a description of what a member is. In this case, please use the properties section of the parent topic, instead of having additional files to document the enums. 

Please, remove the following files:

- api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md
- api-reference/beta/resources/tenantAdmin-sharingCapabilities.md
- api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md

Please, replace "ImageTaggingOption" with "imageTaggingChoice".

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +---
GLOBAL: In Microsoft Graph, filenames should be all lowercase. Please, fix the name of the files added with this PR.

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/tenantAdmin-settings.md
> +|[Get settings](../api/tenantadmin-settings-get.md)|[microsoft.graph.tenantAdmin.settings](../resources/tenantadmin-settings.md) | Get the admin settings for the current tenant.|
For consistency, this description should match the description in the API topic => Get the tenant-level settings for SharePoint and OneDrive for Business.

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/tenantAdmin-settings.md
> +|[Update settings](../api/tenantadmin-settings-update.md) | [microsoft.graph.tenantAdmin.settings](../resources/tenantadmin-settings.md) | Update the admin settings for the current tenant.|
For consistency, this description should match the description in the API topic => Update one or more tenant-level settings for SharePoint and OneDrive for Business.

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/tenantAdmin-settings.md
> +title: "tenant admin settings resource type"
For consistency, please replace "tenant admin settings resource type" with "settings resource type (tenantAdmin)".

Same for line 10.

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +title: "Get tenant admin settings"
For consistency, please replace "Get tenant admin settings" with "Get settings (tenantAdmin)".

Same for line 10.

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/api/tenantAdmin-settings-update.md
> +title: "Update tenant admin settings"
For consistency, please replace "Update tenant admin settings" with "Update settings (tenantAdmin)"

Same for line 10.

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +---
Please, include an update to the toc.yml file in the beta folder, to surface the APIs (Get settings and Update settings, including the settings resource topic) in the TOC.

2022-05-12 22:57 UTC, JarbasHorst commented on changelog/Microsoft.FileServices.json
> +          "Id": "87095323-a508-44c8-95b1-5583e8e14167",
The current entries in this changelog record don't exist in the PR and the new changes are still missing. Please update this changelog record to include the following changes:

Relationship added:
- sharepoint

Resources added:
- settings
- sharepoint

Enums added
- imageTaggingChoice           
- sharingCapabilities          
- sharingDomainRestrictionMode

2022-05-12 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/tenantAdmin-settings.md
> +| imageTaggingOption                                 | imageTaggingChoice           | Specifies the image tagging option for the tenant.
For consistency, please include in the description the possible values for imageTaggingChoice. Suggested revision:

- ...for the tenant. Possible values are: \`disabled\`, \`basic\`, \`enhanced\`.

Same for sharingCapabilities and sharingDomainRestrictionMode.

Also, please update the description of these properties here:
- api-reference/beta/api/tenantAdmin-settings-update.md

2022-05-12 23:00 UTC, JarbasHorst commented
Hello @liamfernandez, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [16878](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16878) into your branch to include my fixes and before addressing my new comments.

2022-05-13 05:12 UTC, opbld31 commented
Docs Build status updates of commit _[44c0550](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44c055059508b98c07e64d326aad46a6116eda30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-b5ab71e4a2043d7003a453eaada36767-9099c77f)
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-f44e5d89933907c60840042688e5122b-9099c77f)
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="b5ab71e4a2043d7003a453eaada36767-9099c77f"></a>
### [api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md)
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/add-users/about-admin-roles' will be broken in isolated environments. Replace with a relative link.`````

<a id="f44e5d89933907c60840042688e5122b-9099c77f"></a>
### [api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md)
 - **Line 27, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/add-users/about-admin-roles' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205130510124762-16047/BuildReport?accessString=8f0e629fe1fe76f0f6bdda8f44aa61f2f75e0a272a49037781c80603ca801b15).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 21:49 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +## User Roles
Gotcha, thanks for the tip. Is it okay to lose the `https://docs.microsoft.com` part of the link? Is that how you make it a relative root even if it's apart of another docs repo?

2022-05-16 22:54 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +---
fixed

2022-05-16 22:54 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +---
working with my team to figure out where in the TOC to expose these.

2022-05-16 22:54 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +title: "Get tenant admin settings"
Fixed

2022-05-16 22:54 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +description: "Read the properties and relationships of a tenant admin settings resource."
fixed. Using just "OneDrive" as the content writer on our team informed us not to use "OneDrive For Business"

2022-05-16 22:55 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-update.md
> +title: "Update tenant admin settings"
fixed

2022-05-16 22:55 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-update.md
> +description: "Update the properties of a tenant admin settings resource. Allows users to update organization-level settings that pertain to SharePoint and OneDrive."
fixed

2022-05-16 22:56 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-update.md
> +|Property|Type|Description|
fixed

2022-05-16 22:56 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +title: "tenant admin settings resource type"
fixed

2022-05-16 22:56 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +|[Get settings](../api/tenantadmin-settings-get.md)|[microsoft.graph.tenantAdmin.settings](../resources/tenantadmin-settings.md) | Get the admin settings for the current tenant.|
fixed

2022-05-16 22:56 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +|[Update settings](../api/tenantadmin-settings-update.md) | [microsoft.graph.tenantAdmin.settings](../resources/tenantadmin-settings.md) | Update the admin settings for the current tenant.|
fixed

2022-05-16 22:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +| imageTaggingOption                                 | imageTaggingChoice           | Specifies the image tagging option for the tenant.
fixed

2022-05-16 22:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-settings.md
> +``` json
fixed

2022-05-16 22:57 UTC, liamfernandez commented on api-reference/beta/resources/tenantAdmin-sharepoint.md
> +|id|String|Read-only. Inherited from [entity](../resources/entity.md)|
removed completely as I realized this resource is just a container and has no properties

2022-05-16 22:57 UTC, liamfernandez commented on changelog/Microsoft.FileServices.json
> +          "Id": "87095323-a508-44c8-95b1-5583e8e14167",
fixed

2022-05-16 22:58 UTC, opbld33 commented
Docs Build status updates of commit _[4368586](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4368586dda42104ee61d329b9ed7280903d8b718)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantAdmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantAdmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantAdmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-imagetaggingchoice?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingCapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingCapabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingcapabilities?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharingdomainrestrictionmode?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205162255523343-16047/BuildReport?accessString=addf608772b5f09373d2439262f25e7b840c96cd2680fd0700469202f1032ec0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 23:18 UTC, JarbasHorst commented on api-reference/beta/resources/tenantadmin-settings.md
> +### imageTaggingOption values
For documenting enums, please use the resource topic if you need to provide a description of what a member is. In this case, please use the properties section of the parent topic, instead of having additional files to document the enums. 

Please, remove the following files:

- api-reference/beta/resources/tenantAdmin-imageTaggingChoice.md
- api-reference/beta/resources/tenantAdmin-sharingCapabilities.md
- api-reference/beta/resources/tenantAdmin-sharingDomainRestrictionMode.md

Please, replace "ImageTaggingOption" with "imageTaggingChoice".

2022-05-16 23:20 UTC, liamfernandez commented
@JarbasHorst Do you know why this error occurs in the api-doctor run? 
![image](https://user-images.githubusercontent.com/12795629/168697676-2028bc19-cd12-465c-aeed-2872853e4689.png)

2022-05-16 23:20 UTC, JarbasHorst commented
Hi @liamfernandez, I will check your PR later more in detail. For now, I just readded a previous comment. Please, take a look when you will have time.

2022-05-16 23:25 UTC, liamfernandez commented on api-reference/beta/resources/tenantadmin-settings.md
> +### imageTaggingOption values
I'm assuming this means I can remove the enumType added entries in the changelog as well? I'll keep them in until you respond

2022-05-16 23:28 UTC, opbld33 commented
Docs Build status updates of commit _[868c283](https://github.com/microsoftgraph/microsoft-graph-docs/commits/868c283685a118e82f3aafce86b62baaf3e673e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205162325317504-16047/BuildReport?accessString=4bdf198f13322ba434ebabad6af3db0479780816a59af56f45c65ecdbaf5708a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 23:30 UTC, JarbasHorst commented
@liamfernandez, regarding your question about the API Doctor error. Try to include the following to the HTML comment:

 "@odata.type": "microsoft.graph.tenantAdmin.settings"
 
```
<!-- {
  "blockType": "response",
  "truncated": true,
  "@odata.type": "microsoft.graph.tenantAdmin.settings"
}
```

Also, please change the request name from "list_tenant_settings" to "update_tenant_settings".

2022-05-16 23:36 UTC, opbld34 commented
Docs Build status updates of commit _[19cccba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19cccba06ffc3b0073eabbf4986d207930aeaf69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205162334318813-16047/BuildReport?accessString=55c0bde57b0d1ba896640d82c3c30e0bdacad3604b228c35d6ed28a2dcfd40cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 23:52 UTC, opbld33 commented
Docs Build status updates of commit _[52e4c10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52e4c1059a0d3f5054b7cffe4bc54ce889041de5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205162348026937-16047/BuildReport?accessString=10da41b728e0c948f440bc9c47d03a576decb8b7268a7379434a93ba3ad339bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 23:56 UTC, opbld33 commented
Docs Build status updates of commit _[9b14f53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b14f53f85ee5d68218eff339a57628ab42cc4ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205162354040252-16047/BuildReport?accessString=680f673c1c4e1d75f26fcc2603a610665ea70a7daf757046044bc76794b48cfe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 00:10 UTC, liamfernandez commented
> @liamfernandez, regarding your question about the API Doctor error. Try to include the following to the HTML comment:
> 
> **"@odata.type": "microsoft.graph.tenantAdmin.settings"**
> 
> ```
> <!-- {
>   "blockType": "response",
>   "truncated": true,
>   "@odata.type": "microsoft.graph.tenantAdmin.settings"
> }
> ```
> 
> Also, please change the request name from "list_tenant_settings" to "update_tenant_settings".

I've tried this a couple ways and see the same error. Also seeing error about enum types being referenced incorrectly

2022-05-17 00:24 UTC, opbld31 commented
Docs Build status updates of commit _[85a347c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85a347c2d19661271177f61cf9725d2de5449b34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e9dbef2a)
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-e9dbef2a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 14412, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/tenantadmin-settings-get.md'.`````
 - **Line 14414, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/tenantadmin-settings-update.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205170022093097-16047/BuildReport?accessString=d3c046e8119951272a9f46e3f715d26c6ad666c2a05b1643a70ff65645d5df37).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 04:16 UTC, samkabue requested changes

2022-05-17 04:16 UTC, samkabue commented on api-reference/beta/toc.yml
> +        - name: Tenant Settings
Sentence case, so "Tenant settings"

2022-05-17 21:04 UTC, JarbasHorst commented
Hi @liamfernandez, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [16932](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16932) into your branch to include my fixes and before addressing my new comments.

2022-05-17 21:09 UTC, opbld33 commented
Docs Build status updates of commit _[8691a5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8691a5d7699db3f5ae27e0fa8b133273245a8dbb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205172107248761-16047/BuildReport?accessString=657afe2b903df53d46c40b956e9d2961ab23f4ebb9d749292b054a8bb897b424).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 21:27 UTC, liamfernandez commented on changelog/Microsoft.FileServices.json
> +          "Id": "87095323-a508-44c8-95b1-5583e8e14167",
fixed

2022-05-17 21:28 UTC, liamfernandez commented on api-reference/beta/toc.yml
> +        - name: Tenant Settings
fixed

2022-05-17 21:29 UTC, liamfernandez commented
@JarbasHorst Have any ideas about the API Doctor errors? I see the enum issues and wonder why ImageTaggingChoice isn't also causing an error. My guess is because it's the first enum table in the file. Thoughts?

2022-05-17 21:39 UTC, opbld32 commented
Docs Build status updates of commit _[7873f57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7873f57e13a8e1af1c099c8841803c91cabedc12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205172127462745-16047/BuildReport?accessString=1554160ed98eb047e4bee99f2204cd361247ee03645a2938882b58396d6d451b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 21:47 UTC, JarbasHorst commented
Hi @liamfernandez, I think it is related to the way how the enums are documented in the parent resource topic. I checked the Document enumerations article from the CDK and applied some changes to the settings resource. Please, merge PR [16934](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16934) to include my fixes that should fix those API Doctor issues.

2022-05-17 22:23 UTC, opbld33 commented
Docs Build status updates of commit _[7c1f934](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c1f934b780db6932ad7405054acd92e5c5848ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205172221343165-16047/BuildReport?accessString=a199155c9ecc0ce02bfb6cec4769b8fcbe5df06b8d7a148cf6da2a5c2faeb012).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 22:26 UTC, JarbasHorst commented
@liamfernandez, it looks like my changes did not fix the API Doctor errors. I will ask Laura for help.

2022-05-17 22:41 UTC, liamfernandez commented on api-reference/beta/api/tenantadmin-settings-get.md
> +description: "Get the tenant-level settings for SharePoint and OneDrive."
![image](https://user-images.githubusercontent.com/12795629/168923978-8a601f31-2787-4a6e-ad55-0e1e2dc94213.png)
We have guidance to no longer use "OneDrive for Business". If it is a must, I can re-write as "OneDrive (work or school)"

2022-05-17 23:17 UTC, JarbasHorst commented on api-reference/beta/api/tenantadmin-settings-get.md
> +description: "Get the tenant-level settings for SharePoint and OneDrive."
Right, thanks for providing additional information. I will ask Laura for guidance.

2022-05-17 23:36 UTC, JarbasHorst commented on api-reference/beta/api/tenantadmin-settings-get.md
> +description: "Get the tenant-level settings for SharePoint and OneDrive."
@liamfernandez, if this is the case, for this PR we should just use OneDrive. Since OneDrive for Business should no longer be used, your team should create a new PR to change this globally for the other articles that contain "OneDrive for Business".

2022-05-17 23:38 UTC, JarbasHorst commented
Hi @liamfernandez, I created a new PR [16938](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16938) that hopefully will fix the API Doctor issues. Basically, this PR adds a page annotation to the settings resource topic, containing the namespace. If my fix will not work, Laura can check this more in detail with the engineering team.

2022-05-17 23:42 UTC, samkabue approved these changes

2022-05-17 23:53 UTC, liamfernandez commented on api-reference/beta/api/tenantadmin-settings-get.md
> +description: "Get the tenant-level settings for SharePoint and OneDrive."
Okay sounds good. Fixed

2022-05-17 23:53 UTC, opbld34 commented
Docs Build status updates of commit _[e236949](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e236949a4de73085dd671f2d69f61624b8dca34e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205172351363602-16047/BuildReport?accessString=098305d34f24e02e176ba5b6616d431c21fad3e740be4225d4694338a9fbc50d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 23:58 UTC, liamfernandez commented
Don't think it worked @JarbasHorst

2022-05-18 00:02 UTC, opbld32 commented
Docs Build status updates of commit _[c76f629](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c76f62909e6bc072321b648d5cd8996e7e728204)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205172352585291-16047/BuildReport?accessString=7481ee1233ef02227741ae3d16c49277f6d1caa63731a2b264e423b32f34b5f9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 03:48 UTC, opbld31 commented
Docs Build status updates of commit _[825f478](https://github.com/microsoftgraph/microsoft-graph-docs/commits/825f4782d23de987acefcbaa184f3173a78a672c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205180345097289-16047/BuildReport?accessString=42be6e3732f6ee3003b080f6cab86020fbd4e776230c63ce294ebc6cf19d8794).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 04:01 UTC, isvargasmsft commented
@liamfernandez, @JarbasHorst, I took the liberty of pushing a commit to fix the API Doctor issue. In summary, since you were defining the enum in the parent topic, and the parent topic lives inside the tenantAdmin subnamespace, in the properties table we must indicate it. So, instead of saying enumname, we say tenantAdmin.enumName.

If this enum should not live inside the subnamespace, then we should define it in the enums.md or in its own topic if the members names are not self-explanatory and require a description. 

Kind regards, 

Isaac.

2022-05-18 18:23 UTC, liamfernandez commented
Thank you @isvargasmsft for the fix. Is the final step to apply the "ready for merge" label?

2022-05-18 18:31 UTC, Mengke-Gh approved these changes

2022-05-18 20:34 UTC, liamfernandez commented on api-reference/beta/api/tenantAdmin-settings-get.md
> +title: "Get settings"
I was recommended above to use "Get settings (tenantAdmin)"

2022-05-18 21:21 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [16956](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16956) into this branch to include my final edits. Thanks for the fix, @isvargasmsft :)

@liamfernandez, Laura will final review and approve this PR, after that you can set the ready to merge label to signal that your PR is ready to publish.

2022-05-18 21:21 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [16956](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16956) into this branch to include my final edits. Thanks for the fix, @isvargasmsft :)

@liamfernandez, Laura will final review and approve this PR, after that you can set the ready to merge label to signal that your PR is ready to publish.

2022-05-19 03:41 UTC, opbld31 commented
Docs Build status updates of commit _[7eea315](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7eea3158f6e0b5212d32a5154a5bd7cc59abd769)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190339221626-16047/BuildReport?accessString=703b2230e10527a52e2104d01d2aa546dc46daeabc57d9661414a5fee24e36d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 03:55 UTC, opbld30 commented
Docs Build status updates of commit _[788f907](https://github.com/microsoftgraph/microsoft-graph-docs/commits/788f907fce588f8f5e5e7d5b4156a188f89f2e28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190352561370-16047/BuildReport?accessString=307ddfd01459e07fce8026d99eb2c33d5a17754bea9ec57a0f422e8cf124fba4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 03:58 UTC, opbld33 commented
Docs Build status updates of commit _[af29322](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af293222d8ad42955467f80617b3e789e70fad33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190355578455-16047/BuildReport?accessString=808883b4a3d0722708877446dea9f750fe317bc8c0eea19f7da1abac703dd05b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 04:00 UTC, opbld32 commented
Docs Build status updates of commit _[353c95e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/353c95ed98302e5353776370182baf21985115e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-018aa289)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-018aa289)
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-018aa289"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-018aa289"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190358017917-16047/BuildReport?accessString=96e26a26634b9c32cdf33e0f0d325f7e479517461b73a15aab98bd32ffcc2d8d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 04:35 UTC, Lauragra approved these changes

2022-05-19 22:47 UTC, opbld34 commented
Docs Build status updates of commit _[7622fbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7622fbd5b722e67c84d87b281761b6033cd78e7d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-0e2d05a4)
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-0e2d05a4)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-0e2d05a4)

<a id="0817dce4456c16725d5333633847d38f-0e2d05a4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 14520, Column 16**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-0e2d05a4"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-0e2d05a4"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205192245151257-16047/BuildReport?accessString=6aefb5dd668cbe653d1141669b3053271ab8773108b438f41961ce21322f08d2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 22:51 UTC, liamfernandez commented
@Lauragra @isvargasmsft There seems to be an error with TOC mapping but it's in a section that I did not edit?

2022-05-20 23:37 UTC, opbld34 commented
Docs Build status updates of commit _[161948f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/161948f21cc7541c4f624ef2f5db6f3e449c9923)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-996a860f)
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-996a860f)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-996a860f)

<a id="0817dce4456c16725d5333633847d38f-996a860f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 14521, Column 16**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-996a860f"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-996a860f"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205202335291200-16047/BuildReport?accessString=e838055fc14bd5ad6db067ae62eb164b375e58a9917ae456207b82c77e58fa26).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-23 17:33 UTC, opbld32 commented
Docs Build status updates of commit _[f556e0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f556e0c94cc4cc11f616ac80f725005b1632b3e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-6169d990)
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-6169d990)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-6169d990)

<a id="0817dce4456c16725d5333633847d38f-6169d990"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 14531, Column 16**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-6169d990"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-6169d990"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205231727330860-16047/BuildReport?accessString=3071b0aa66c750f15bb3f863e1063be7221476ed916a51de86dbf66058c5a1a9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-23 17:39 UTC, opbld33 commented
Docs Build status updates of commit _[30fb638](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30fb638c6fb09793d0d91c12935335074e5726c0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-eba8974b)
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-eba8974b)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-eba8974b)

<a id="0817dce4456c16725d5333633847d38f-eba8974b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 14601, Column 16**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-eba8974b"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-eba8974b"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205231736333744-16047/BuildReport?accessString=ed20786b0373bcec25dc0e6792699e36b0bd537e2525d3d03b17c44c94feff43).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-23 17:52 UTC, opbld31 commented
Docs Build status updates of commit _[e460343](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e460343b41a35b992e63939fcb668694710b1496)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-569b3e50)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-569b3e50)
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-569b3e50"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-569b3e50"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205231740242351-16047/BuildReport?accessString=98e7f5e796d7d25fe0aa21e49e8b6ab36b7c379aa089bd1863a62028e280a64b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 02:37 UTC, opbld33 commented
Docs Build status updates of commit _[92bb5e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92bb5e165b3fbc92722dc1ec88c77bf4dd9a23c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-185d7bb9cca001cf53fc9b3ee41a7e7a-13de79cc)
[api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/settings?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) | [Details](#user-content-e022cc1d2518ec2813116a62b6420aac-13de79cc)
[api-reference/beta/api/tenantadmin-settings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/api/tenantadmin-settings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantadmin-settings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-update?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/resources/tenantadmin-sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantadmin-settings-get?view=graph-rest-beta&branch=pr-en-us-16047) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lfernandez/sharepointTenantSettings/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="185d7bb9cca001cf53fc9b3ee41a7e7a-13de79cc"></a>
### [api-reference/beta/resources/tenantadmin-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantadmin-settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e022cc1d2518ec2813116a62b6420aac-13de79cc"></a>
### [api-reference/beta/resources/settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/settings.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'settings resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/settings.md(2,8), beta/resources/tenantadmin-settings.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'settings resource type' is duplicated with other articles: 'beta/resources/settings.md(10,1), beta/resources/tenantadmin-settings.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240225185015-16047/BuildReport?accessString=b2bdc08aae08826d5b2722d23cf49407fd88fa4a07c1e59631c278d4cb2510ca).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 02:37 UTC, merged