Amharris/gdap documentation amharris
microsoftgraph/microsoft-graph-docs pull request #16092
Opened 2022-03-08 00:04 UTC by amharris1331

Continuing the work to refine the GDAP API graph documentation. The updates in this pr include: Updating author, ms.prod value, request headers, removing non-existent API definitions, and adding service management details get api def"

2022-03-08 00:06 UTC, opbld31 commented
Docs Build status updates of commit _[cfd8fdd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfd8fddd4e3fd08dd740cfcc4ce5907198540aab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-805fae63)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/ [...]

2022-03-08 19:45 UTC, ozhang22 reviewed
First round of suggestions.

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +If-Match: "W/\"JyI0NzAwNjg0NS0wMDAwLTE5MDAtMDAwMC02MGY0Yjg4MzAwMDAiJw==\""
Do we know if we should use a specific If-Match value or just a templatized value (like in the Authorization header)?

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +Content-length: 284
I don't think we should include this.

```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminoperation-delete.md
> +|Authorization|Bearer {token}. Required.|
If-Match header missing

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminoperation-update.md
> +Content-length: 138
```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "id": "62bb42bf-e5d9-31d8-cc8c-d1a442d08341",
ID is the only field that isn't templatized - is this expected?

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/tenantrelationship-post-delegatedadmincustomers.md
> +|tenantId|String|**TODO: Add Description** Required.|
To fix.

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +|status|delegatedAdminAccessAssignmentStatus|The status of the assignment.The possible values are: `pending`, `active`, `deleting`, `deleted`, `error`, `unknownFutureValue`.|
```suggestion
|status|delegatedAdminAccessAssignmentStatus|The status of the assignment. The possible values are: `pending`, `active`, `deleting`, `deleted`, `error`, `unknownFutureValue`.|
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +description: "Represents the partner view of a delegated admin relationship between a partner and customer."
Need to be consistent between "Delegated Admin" and "delegated admin"

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +  "@odata.type": "#microsoft.graph.delegatedAdminRelationship",
Do the fields need to be ordered as per above?

2022-03-08 19:45 UTC, ozhang22 commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Id": "864c77db-f273-4a11-8104-8149f3f9566f",
Autogenerated? Do we need unique IDs for each?

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|[Create delegatedAdminAccessAssignment](../api/delegatedadminrelationship-post-accessassignments.md)|[delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md)|Create a new del
Is this intended?

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|[Create delegatedAdminRelationshipRequest](../api/delegatedadminrelationship-post-requests.md)|[delegatedAdminRelationshipRequest](../resources/delegatedadminrelationshiprequest.md)|Create a new del
Is this intended?

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|status|delegatedAdminRelationshipStatus|The status of the relationship.The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`,
```suggestion
|status|delegatedAdminRelationshipStatus|The status of the relationship. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`, `terminating`, `terminationRequested`, `unknownFutureValue`.|
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccesscontainer.md
> +|accessContainerId|String|The identifier of the access container (e.g., security group). For "securityGroup" access containers, this must be a valid ID of an AAD security group in the partner tenant.
```suggestion
|accessContainerId|String|The identifier of the access container (e.g., security group). For `securityGroup` access containers, this must be a valid ID of an AAD security group in the partner tenant.|
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +|[List delegatedAdminAccessAssignments](../api/delegatedadminaccessassignment-list.md)|[delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) collection|Get a list of the [d
Is the order usually List, Create, Get, Update, Delete?

I would imagine the order should be Create, List, Get, Update, Delete

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +If successful, this method returns a `200 OK` response code and an updated [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object in the response body.
This is true, but only in certain cases. In most cases it returns a `202 Accepted`, with a response header pointing to the URL to hit the corresponding delegatedAdminOperation object created.

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +Content-length: 316
```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +Content-length: 152
```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +Content-length: 529
```suggestion
Authorization: Bearer {token}
If-Match: "W/\"JyI0NzAwNjg0NS0wMDAwLTE5MDAtMDAwMC02MGY0Yjg4MzAwMDAiJw==\""
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationshiprequest-update.md
> +Content-length: 120
```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/tenantrelationship-post-delegatedadmincustomers.md
> +Content-length: 148
```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +Content-length: 561
```suggestion
Content-Type: application/json
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
```suggestion
|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed by the caller once the relationship is in the `approvalPending` status or beyond. Must be unique across all relationships from the partner for the customer.|
```

2022-03-08 19:45 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +  "value": {
Not sure if these responses should also include the @odata.etag value?

2022-03-09 00:11 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +If-Match: "W/\"JyI0NzAwNjg0NS0wMDAwLTE5MDAtMDAwMC02MGY0Yjg4MzAwMDAiJw==\""
I took a look at current v.1 documentation that had If-Match values and updated the documentation.  However, long story short: yes, we can use specific etag values. 
https://docs.microsoft.com/en-us/graph/api/plannertask-update?view=graph-rest-1.0&tabs=http

2022-03-09 00:18 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "id": "62bb42bf-e5d9-31d8-cc8c-d1a442d08341",
Actually, in the live documentations that I scanned, none of the fields in the response body are templatized.  They are all real (or as real as you can get) values.

2022-03-09 00:19 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "id": "62bb42bf-e5d9-31d8-cc8c-d1a442d08341",
I think we should actually insert real values into the response bodies instead of using templatized values.

2022-03-09 00:21 UTC, amharris1331 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
Good catch Oliver!

2022-03-09 00:22 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +  "value": {
Nah.  I looked at other documentations response body's and they didn't have etags defined in the either. 
https://docs.microsoft.com/en-us/graph/api/plannertask-get?view=graph-rest-1.0&tabs=http

2022-03-09 00:28 UTC, opbld30 commented
Docs Build status updates of commit _[46add59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46add599cdaf806ee04c022b2dd9205ff5dac212)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succe [...]

2022-03-09 02:43 UTC, amharris1331 commented on api-reference/beta/api/tenantrelationship-post-delegatedadmincustomers.md
> +|tenantId|String|**TODO: Add Description** Required.|
Need to remove this API definition because partners can't create delegated admin customers.

2022-03-09 02:53 UTC, amharris1331 commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Id": "864c77db-f273-4a11-8104-8149f3f9566f",
This was copied from Deepak's Schema PR.  It needs to be exact so that his changes don't break.

2022-03-09 03:37 UTC, amharris1331 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|[Create delegatedAdminRelationshipRequest](../api/delegatedadminrelationship-post-requests.md)|[delegatedAdminRelationshipRequest](../resources/delegatedadminrelationshiprequest.md)|Create a new del
Removed.

2022-03-09 03:38 UTC, amharris1331 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|[Create delegatedAdminAccessAssignment](../api/delegatedadminrelationship-post-accessassignments.md)|[delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md)|Create a new del
Removed.

2022-03-09 03:38 UTC, opbld30 commented
Docs Build status updates of commit _[6b23c65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b23c653fe9cf2cc2b6e5e2c51a3815ada875bac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/delegatedadmincustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/resources/delegatedadmincustomer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadmincustomer?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) | [Details](#user-content-e4d3ca9519c6507f16ffffde4a752a04-6ad7e686)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) |  [...]

2022-03-09 03:38 UTC, amharris1331 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +  "@odata.type": "#microsoft.graph.delegatedAdminRelationship",
Updated field order.

2022-03-09 03:38 UTC, amharris1331 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +description: "Represents the partner view of a delegated admin relationship between a partner and customer."
Went with "delegated admin"

2022-03-09 03:44 UTC, opbld33 commented
Docs Build status updates of commit _[8f49db4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f49db4236fa41c8a1e869d1aefac910b63a35ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succe [...]

2022-03-09 03:53 UTC, opbld34 commented
Docs Build status updates of commit _[74a1f58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74a1f5834569b1dd52ddb274cea95bcf17325be9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succe [...]

2022-03-09 04:01 UTC, opbld30 commented
Docs Build status updates of commit _[14dc6d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14dc6d06dea17e35e4260833948f33342f753fa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succe [...]

2022-03-09 22:18 UTC, ozhang22 reviewed
Some more comments.

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
> +GET /tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments
How is this page different than delegatedadminaccessassignments-list?

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +### Response
Do we need a table listing the descriptions of the response headers?

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +      "@odata.type": "#microsoft.graph.delegatedAdminAccessAssignment",
Example responses for list APIs should ideally have multiple entries

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +Namespace: microsoft.graph
Change this everywhere

```suggestion
Namespace: microsoft.partner.customerServiceAdministration
```

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +|status|delegatedAdminAccessAssignmentStatus|The status of the assignment. The possible values are: `pending`, `active`, `deleting`, `deleted`, `error`, `unknownFutureValue`.|
Do we need to fully quantify these types? (i.e. delegatedAdminAccessAssignmentStatus -> microsoft.partner.customerserviceadministration.delegatedAdminAccessAssignmentStatus)

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationship.md
> +  "@odata.type": "#microsoft.graph.delegatedAdminRelationship",
No, sorry, I meant ordering the fields in the response. I see that in all the other doc pages, you ordered the fields in the table alphabetically. Do the fields in the response bodies also need to be ordered alphabetically?

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/resources/enums.md
> +|Member|
I see some other enums have values and descriptions as table columns - should we add these too?

2022-03-09 22:18 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +|If-Match|Last known ETag value for the **delegated admin access assignment** to be deleted. Required.|
Also, why is it delegated admin access assignment instead of delegatedAdminAccessAssignment? Same elsewhere.

2022-03-10 00:38 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +Namespace: microsoft.graph
Actually this name space wasn't recognized and it was blocking the ApiDoctor build.

2022-03-10 00:51 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +|If-Match|Last known ETag value for the **delegated admin access assignment** to be deleted. Required.|
This is bolded because that was the pattern I saw in other v.1 documents.

2022-03-10 21:18 UTC, opbld30 commented
Docs Build status updates of commit _[8c0e72d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c0e72d1d4d106cedc487083b246de105d47548c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succe [...]

2022-03-11 00:00 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +|If-Match|Last known ETag value for the **delegated admin access assignment** to be deleted. Required.|
This was bolded text because that was the standard set in other v.1 api definitions.  I can revert this though if you think it is unnecessary.

2022-03-11 01:00 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +{
Updating.

2022-03-11 01:00 UTC, amharris1331 commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Asked in the Graph email thread that is currently active, but my POC is OOF until Tuesday. :(

2022-03-11 01:34 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
> +GET /tenantRelationship/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments
Deleted all classes of the form: DelegatedAdminRelationship-list-______

2022-03-11 01:35 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +### Response
No.  I don't see any examples of that in the documentation.

2022-03-11 02:18 UTC, opbld33 commented
Docs Build status updates of commit _[5ed2695](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ed2695f4f19d943ca34db1f4dd33bbebfa7a3d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documen [...]

2022-03-11 02:18 UTC, amharris1331 commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +|status|delegatedAdminAccessAssignmentStatus|The status of the assignment. The possible values are: `pending`, `active`, `deleting`, `deleted`, `error`, `unknownFutureValue`.|
No, we can leave the status and other types as is.  See example: https://docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0

2022-03-11 03:46 UTC, ozhang22 reviewed
More comments.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +Namespace: microsoft.graph
I'm surprised the name space is not recognized, because that is the namespace that we set in the schema.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +      "@odata.type": "microsoft.graph.delegatedAdminAccessContainer"
I think it makes sense to expand these values to also have true values as well.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +Location: https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/5e5594d3-6f82-458b-b567-77db4811f0cd-00000000-0000-0000-0000-000000001234/operations/d8dbb27b-7fe7-4523-a3df
Location header is not present for 200 OK response - move this to the 202 Accepted response.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +    "@odata.type": "microsoft.graph.delegatedAdminAccessContainer"
The request bodies should also have real values for these nested fields.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +  "@odata.type": "#microsoft.graph.delegatedAdminRelationshipRequest",
The @odata.type is typically not passed in the request body.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationshipoperation-list.md
> +      "data": "{\"id\":\"a97a9b4c-f43e-4c47-bbd6-50d8d3c88d94\",\"PartnerGdapRelationshipId\":\"fa803a2f-93b1-4b87-a7ff-a833b149ab01-8119890b-4c3f-465d-9840-599131d14d98\",\"Customer\":{\"TenantId\":
Can the two access assignment operations have different role assignments?

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +    "operationType": "updateGdapRelationshipAccessAssignment",
```suggestion
    "operationType": "delegatedAdminAccessAssignmentUpdate",
```

And same elsewhere

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +|customer|[microsoft.graph.delegatedAdminRelationshipCustomerParticipant](../resources/delegatedadminrelationshipcustomerparticipant.md)|The information of the customer of the relationship. This is s
Since this is a patch API, we don't have to specify the entire relationship object - only the fields we want to update. Would it make sense if we just only specified the fields that the partner can update in the first place?

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md
> +      "displayName": "Delegated Admin Customer"
Can we make up another name for this?

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "@odata.type": "#microsoft.graph.delegatedAdminAccessAssignment",
@odata.context and @odata.etag should also be part of the response, since we return these.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +  "value": {
We don't have a "value" field for any GET by ID APIs, only for List APIs.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +      "createdDateTime": "2022-02-10T00:55:47.1180588Z",
If possible the createdDateTime and lastModifiedDateTime should be different from each other for at least one example (especially this case where the status is active), and they should be different for each access assignment.

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +### Request
Split these with ### Example 1 and ### Example 2, like how it's done for GetGroup: https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http

2022-03-11 03:46 UTC, ozhang22 commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Let's use this example: https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http

It specified which exact OData parameters are usable.

2022-03-11 20:06 UTC, amharris1331 commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Nice!!!  Good find!  I'll use this as a template for the OData query insert!

2022-03-11 23:20 UTC, amharris1331 commented on api-reference/beta/resources/enums.md
> +|Member|
Nah, not necessary.  If you think we should, then we can.

2022-03-11 23:40 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +      "@odata.type": "microsoft.graph.delegatedAdminAccessContainer"
Awe man, sorry about that.  I thought that Graph would insert the values stored in the objects file here.  I'll update this.

2022-03-12 00:11 UTC, amharris1331 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +Location: https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/5e5594d3-6f82-458b-b567-77db4811f0cd-00000000-0000-0000-0000-000000001234/operations/d8dbb27b-7fe7-4523-a3df
Got it.

2022-03-12 02:14 UTC, opbld34 commented
Docs Build status updates of commit _[7019134](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70191347a2ddab75b1db9afd474b52d56139ede1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documen [...]

2022-03-12 02:26 UTC, opbld33 commented
Docs Build status updates of commit _[d0faca1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0faca164f85bcc19bbba62c6745e2683fdadfd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshipoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documentation_amharris/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16092) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/amharris/gdap_documen [...]

2022-03-14 17:38 UTC, adtangir reviewed
Check if the author must be fixed to Microsoft aliasa

2022-03-16 17:56 UTC, deepakku-work requested changes
Few more comments.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +[!INCLUDE [table-intro](../../includes/update-property-table-intro.md)]
Please make sure that the table intro contains the following text: "In the request body, supply only the values for properties that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values.

The following table specifies the properties that can be updated."

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +|accessContainer|[microsoft.graph.delegatedAdminAccessContainer](../resources/delegatedadminaccesscontainer.md)|The access container of the access assignment. Required.|
Same applies to other PATCH API.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +description: "Read the properties and relationships of a delegatedAdminCustomer object."
Remove "and relationships" from description.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +  "displayName": "Contoso"
"Contoso Inc" (same everywhere).

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +|accessContainer|[microsoft.graph.delegatedAdminAccessContainer](../resources/delegatedadminaccesscontainer.md)|The access container of the access assignment. Required.|
Please remove required/optional from all properties since every property is essentially optional but at least one property should be set.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +Read the properties and relationships of a [delegatedAdminRelationshipOperation](../resources/delegatedadminrelationshipoperation.md) object.
Remove "and relationships" from description.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +  "data": "{\"id\":\"a97a9b4c-f43e-4c47-bbd6-50d8d3c88d94\",\"PartnerGdapRelationshipId\":\"5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836\",\"Customer\":{\"TenantId\":\"4f
Replace this with a more recent run (the previous serialization had some issues).

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-list.md
> +      "data": "{\"id\":\"a97a9b4c-f43e-4c47-bbd6-50d8d3c88d94\",\"PartnerGdapRelationshipId\":\"fa803a2f-93b1-4b87-a7ff-a833b149ab01-8119890b-4c3f-465d-9840-599131d14d98\",\"Customer\":{\"TenantId\":
Same here: please update with a more recent run. The serialized data had the repository object serialized previously.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-update.md
> +---
Please remove this file. The PATCH operation is not intended for use by the partner and is an internal API.

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md
> +      "displayName": "Contoso"
Contoso Inc?

2022-03-16 17:56 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +This method supports the `$select`, `$filter`, `$top`, `$orderBy`, `$skip`, `$count`, and `$skipToken`  [OData query parameters](/graph/query-parameters) to help customize the response. The default a
General (for all List API): Can you double check to make sure that the OData query parameters and the listed filter by fields are all accurate?

2022-03-16 20:49 UTC, adtangir commented on api-reference/beta/api/delegatedadminrelationship-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Do you mean to suggest adding the generic description for Optional parameters containing all the filters?

2022-03-16 20:54 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Sorry, ignore this one. My suggestions only apply to the List API. For the GetById ones, keep the more generic description for now.

2022-03-16 22:01 UTC, adtangir commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +ms.prod: "directory-management"
As discussed offline, for now lets use this since these are beta APIs and let IDC team fix it once we move to v1

2022-03-31 03:13 UTC, merged