Added new docs for enabling Large Gallery view API.
microsoftgraph/microsoft-graph-docs pull request #16104
Opened 2022-03-08 16:54 UTC by navali-msft

2022-03-08 17:01 UTC, opbld33 commented
Docs Build status updates of commit _[25627b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25627b2ca817a1a5b106863c181d50eaf0548d1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-enablelargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-enablelargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-enablelargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/enablelargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/enablelargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enablelargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-enablelargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203081659037400-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T17%3A01%3A37Z&sr=b&sp=r&sig=VgR8pz5GjlolvfkKMwyypw4BRKxJOAZjEQkxtU%2Bst%2B0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 07:18 UTC, satyakonmsft commented on api-reference/beta/api/call-enablelargegalleryview.md
> +| Application     | For joining meetings: Calls.JoinGroupCallsasGuest.All or Calls.JoinGroupCalls.All<br/>For initiating peer-to-peer calls: Calls.Initiate.All<br/>For initiating group calls: Calls.I
let us limit this to meeting related ones: Calls.JoinGroupCallsasGuest.All or Calls.JoinGroupCalls.All or Calls.InitiateGroupCalls.All

2022-03-10 07:19 UTC, satyakonmsft commented on api-reference/beta/api/call-enablelargegalleryview.md
> +title: "call: enableLargeGalleryView"
we need to change to "add" everywhere

2022-03-10 07:20 UTC, satyakonmsft commented on api-reference/beta/toc.yml
> +    - name: Devices and apps
should we revert this change?

2022-03-10 07:22 UTC, satyakonmsft commented
you also need a change to: changelog/Microsoft.Skype.Calling.json

2022-03-10 17:50 UTC, opbld32 commented
Docs Build status updates of commit _[30eee14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30eee145f1ada73770d61136972e07622743ec2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203101748007762-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T17%3A50%3A16Z&sr=b&sp=r&sig=m75P4OH79a%2Fsj5gkQ7ZGZluqteNXhaWo6YmP4bCynxU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 17:52 UTC, opbld33 commented
Docs Build status updates of commit _[53af72a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53af72a7b2a4da91de978d5a28a5bb1fec20ac25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203101749400710-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T17%3A52%3A26Z&sr=b&sp=r&sig=NusaGXLt1K5vjHB5QkEqTo%2FNGzEC79K9gcPNt3jPqZo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 17:58 UTC, opbld34 commented
Docs Build status updates of commit _[0adfb1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0adfb1e1e136b889a70208c30df2ed6cbc441ea7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203101756303025-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T17%3A58%3A37Z&sr=b&sp=r&sig=mmf28F8NnhxjBIZmCXgt69EHygZfiZinktUIU%2FihEEE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 18:04 UTC, opbld31 commented
Docs Build status updates of commit _[3b460e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b460e03d439909d3bd6d6cccb17cc2cb3501538)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203101802353068-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T18%3A04%3A37Z&sr=b&sp=r&sig=5XclpvtFG8sweI3mXDWmQcea9F2bYIZlIGo%2BX61h8gs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 18:06 UTC, navali-msft commented on api-reference/beta/api/call-enablelargegalleryview.md
> +title: "call: enableLargeGalleryView"
changed the file name plus all usage of enable

2022-03-10 18:09 UTC, navali-msft commented on api-reference/beta/toc.yml
> +    - name: Devices and apps
fixed it.

2022-03-10 18:48 UTC, opbld31 commented
Docs Build status updates of commit _[fb493b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb493b49bc439b5d25653bbb3b63c19d9ffa1207)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203101845518416-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T18%3A48%3A01Z&sr=b&sp=r&sig=EWy2bqTSoytes8pY5PQ14vj%2FpuN51OjXddSDCO1%2FOu0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 23:49 UTC, satyakonmsft approved these changes

2022-03-30 22:02 UTC, opbld33 commented
Docs Build status updates of commit _[33be421](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33be42114a316e903cc69e2fbe2c0e83a5e11484)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5315dbb2)

<a id="5315dbb2"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203302201403703-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T22%3A02%3A07Z&sr=b&sp=r&sig=UTQ4726V%2FAKzuBxVNjnS%2FrmuiHLh4LllUQdreXuqFgE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 21:49 UTC, JarbasHorst commented on api-reference/beta/api/call-addlargegalleryview.md
> +| Application     | Calls.JoinGroupCallsasGuest.All or Calls.JoinGroupCalls.All or Calls.InitiateGroupCalls.All                       |
Please, make sure that all your permissions are spelled correctly.

Calls.JoinGroupCallsasGuest.All => Calls.JoinGroupCallAsGuest.All
Calls.JoinGroupCalls.All => Calls.JoinGroupCall.All
Calls.InitiateGroupCalls.All => Calls.InitiateGroupCall.All

2022-04-04 21:49 UTC, JarbasHorst commented on api-reference/beta/resources/call.md
> +| [Add Large Gallery View](../api/call-addlargegalleryview.md)       | [addGalleryViewOperation](addlargegalleryviewoperation.md)  | Add Large Gallery view.                                      |
1) For readability and because our guidelines are to avoid over-capitalization, please replace "Large Gallery View" with "large gallery view". 

2) In the description, please replace "Add Large Gallery view." with the same description used in the call-addlargegalleryview API topic. => Add the large gallery view to a call in Microsoft Teams.

2022-04-04 21:52 UTC, JarbasHorst commented
Hello @navali-msft, I reviewed your PR and left some comments. Please, take a look when you will have time.

2022-04-04 22:06 UTC, opbld30 commented
Docs Build status updates of commit _[a165241](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a16524150c585e0566b1f3fb8124d4047c62e43b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204042204013235-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T22%3A06%3A30Z&sr=b&sp=r&sig=Lu3QGFlnbuIavGF0Fq4ANq0n2OyuK6IaSoVICZBY8Z4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 00:40 UTC, isvargasmsft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +title: "adLargeGalleryViewOperation resource type"
Line 2: typo in title: there is a 'd' missing in the name: addLarge...

2022-04-05 00:42 UTC, isvargasmsft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +| status                         | String                      | Possible values are: `notStarted`, `running`, `completed`, `failed`. Read-only.                                                 |
Line 25: Type is not String but an enum type. Please add the name of the enum type in the Type column.

2022-04-05 00:44 UTC, isvargasmsft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +
The api.md file indicates this resource supports the Get operation. Please clarify or add this operation to the docs.

2022-04-05 00:46 UTC, isvargasmsft requested changes
The api.md file indicates that the new entity type supports the Get operation. 

Please clarify the reason to exclude this operation from the docs or add it.

2022-04-05 17:44 UTC, opbld32 commented
Docs Build status updates of commit _[a43f242](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a43f242aaed13c7171df24586ab29aa946233a2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204051742344446-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T17%3A44%3A36Z&sr=b&sp=r&sig=OeqXDEG771vkMKF5EhtmszadQGLSfGVCQNgCiYIOkdY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 18:25 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +| Application     | Calls.JoinGroupCallsasGuest.All or Calls.JoinGroupCalls.All or Calls.InitiateGroupCalls.All                       |
Fixed, thanks.

2022-04-05 18:28 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +POST https://graph.microsoft.com/beta/communications/calls/{id}/addLargeGalleryView
Fixed, thanks.

2022-04-05 18:30 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +The following example shows how to call this API.
We only have one example right now, but I have removed that sentence.

2022-04-05 18:45 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +## Identifying Large Gallery view application from the roster and subscribing to the video feed
This is not a new example but section to show how this large gallery video feed can be consumed by bot who are in the call.

2022-04-05 18:46 UTC, navali-msft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +description: "Describes the response format of adding Large Gallery view operation."
Fixed, thanks.

2022-04-05 18:46 UTC, navali-msft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +| status                         | String                      | Possible values are: `notStarted`, `running`, `completed`, `failed`. Read-only.                                                 |
Added, thanks.

2022-04-05 19:40 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +description: "Add Large Gallery view in a call."
Fixed, thanks.

2022-04-05 19:42 UTC, navali-msft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +| status                         | String                      | Possible values are: `notStarted`, `running`, `completed`, `failed`. Read-only.                                                 |
The values are passed as string over the wire, so should we still put it as enum.

2022-04-05 20:08 UTC, navali-msft commented on api-reference/beta/toc.yml
> +        - name: Add Large Gallery view
Fixed, thanks.

2022-04-05 20:08 UTC, navali-msft commented on api-reference/beta/resources/call.md
> +| [Add Large Gallery View](../api/call-addlargegalleryview.md)       | [addGalleryViewOperation](addlargegalleryviewoperation.md)  | Add Large Gallery view.                                      |
Fixed, thanks.

2022-04-05 21:32 UTC, opbld30 commented
Docs Build status updates of commit _[0829604](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08296042906f7522ddcc4c348ab24d6d4fdddf95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204052128320087-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T21%3A32%3A06Z&sr=b&sp=r&sig=5d%2FeK9WInmwv6JTf6toZwmKihWBIx4CUx2%2BH%2FtIkncE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 21:45 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +For more information about how to handle Large Gallery view operation, see [addLargeGalleryViewOperation](../resources/addlargegalleryviewoperation.md).
Moved to response section.

2022-04-05 21:46 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +##### Notification - operation completed
The similar block type is used by other apis as well, what can be used here since it is neither request not response?

2022-04-05 21:47 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +## Identifying Large Gallery view application from the roster and subscribing to the video feed
Moved it to the other page.

2022-04-05 21:47 UTC, opbld31 commented
Docs Build status updates of commit _[7d1a030](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d1a0303b8abae036173ae24294813156636b27b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204052145300954-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T21%3A47%3A37Z&sr=b&sp=r&sig=izfk6VbcK8sZqxosescUYys2hxzlnn4DaWjvP8%2F0z60%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 21:47 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +The Large Gallery view applications can be identified by using the following pointers:
Moved it to the other page.

2022-04-05 22:40 UTC, opbld33 commented
Docs Build status updates of commit _[0a5cc6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a5cc6d83802393aa7465bca8f126189d22ca73f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-7bb6a05353d9758903999167593898a5-e12d9c68)
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="7bb6a05353d9758903999167593898a5-e12d9c68"></a>
### [api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md)
 - **Line 58, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204052238114420-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T22%3A40%3A12Z&sr=b&sp=r&sig=QgHdnxpsC8%2B6XI%2FcYOkQEAovztoZ0J0ffdAX%2FdiU3%2BQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 22:48 UTC, opbld34 commented
Docs Build status updates of commit _[5d6db4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d6db4b66120f582d9864e60457b8f327ab4b820)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-7bb6a05353d9758903999167593898a5-a076292b)
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="7bb6a05353d9758903999167593898a5-a076292b"></a>
### [api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md)
 - **Line 58, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204052246018170-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T22%3A48%3A28Z&sr=b&sp=r&sig=cjoBqdPAnQx3w6U4CZT3tAhcxpdtP10SpujDguMCwqY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 23:07 UTC, opbld34 commented
Docs Build status updates of commit _[11758fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11758fdb1955491004ed353f1fcaa0710306b8f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-7bb6a05353d9758903999167593898a5-50bf3d64)
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="7bb6a05353d9758903999167593898a5-50bf3d64"></a>
### [api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md)
 - **Line 58, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204052305110960-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T23%3A07%3A09Z&sr=b&sp=r&sig=EOJz7aC5fxyppFMUKS7xbdS4iv%2FGMMzuzSY7NbFG50A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 23:10 UTC, navali-msft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +
Added example to show how Get Operation can be performed.

2022-04-06 17:31 UTC, isvargasmsft commented on api-reference/beta/api/call-addlargegalleryview.md
> +### Example 2: Get the operation status
Please note, a new file is required for the GET operation, an example is not sufficient. Please add a new Get addLargeGalleryViewOperation topic, include it in the Methods table of the addLargeGalleryViewOperation resource topic, in the TOC and in the changelog.

2022-04-06 17:32 UTC, isvargasmsft requested changes
Hello @navali-msft, 

Thank you for addressing the feedback. 

Please note, a new file is required for the GET operation, an example is not sufficient. Please add a new **Get addLargeGalleryViewOperation** topic, include it in the **Methods** table of the **addLargeGalleryViewOperation** resource topic, in the TOC and in the changelog.

2022-04-06 17:38 UTC, isvargasmsft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +| status                         | String                      | Possible values are: `notStarted`, `running`, `completed`, `failed`. Read-only.                                                 |
In the CSDL it is defined as an enum:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/70350956/162034807-95f3e07d-2c8d-4475-b2f5-f2b4ed7c24bd.png">
So, yes, please add the name of the enum in the Type column :)

2022-04-06 20:47 UTC, JarbasHorst commented on api-reference/beta/api/call-addlargegalleryview.md
> +If successful, this method returns a `202 Accepted` response code and
For consistency, please don't repeat this sentence here as it is already available in the Response section.

2022-04-06 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/identifylargegalleryview.md
> +# How to identify the large gallery view application in the roster
We should be surfacing this concept topic in the concept TOC under Learn/Cloud communications, where we surface other cloud communications-related concept topics. Please, apply this change to the TOC. Suggested entry name for the TOC: "Identify large gallery view app"

2022-04-06 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/identifylargegalleryview.md
> +title: "How to identify the large gallery view application in the roster"
For clarity, I recommend you to start the title with a verb. Suggested revision:

- Identify the large gallery view application in the roster

Same for line 10.

2022-04-06 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/identifylargegalleryview.md
> +description: "Describes how the large gallery view application can be identified in the roster."
For clarity and considering that this article goes under the learning section, I recommend the following revision for this description:

- Learn how to identify the large gallery view application in the roster.

2022-04-06 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/identifylargegalleryview.md
> +After the large gallery view is added successfully in the call, the developers need to identify participant from the roster which is sending those large gallery view videos feeds.
I recommend you to introduce the intend of this article before start covering the topic. Suggested revision:

- In this article, you will learn how to identify the large gallery view application in the roster.

2022-04-06 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/identifylargegalleryview.md
> +The following example and guidance can help identify the application which can be subscribed to get the feeds.
Does this sentence only apply to the following section "## Sample roster..." or is this about the entire content of this article. If latter, then please replace "example" with "examples" because this article contains more than one example. If this sentence is only about the next section, please move this sentence to line 20.

2022-04-06 22:24 UTC, opbld34 commented
Docs Build status updates of commit _[6566272](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6566272ec969be75cf172df00102182b04d77ef5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204062219398591-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T22%3A24%3A51Z&sr=b&sp=r&sig=PcQ%2FpOUNp9HCgLK%2BX1MBPxemsnzGiXH0V0wSMJxdNjg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 20:10 UTC, opbld30 commented
Docs Build status updates of commit _[1b15618](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b15618684ea4f4bb41d8ef1cb647ce8175df5e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204072007589067-16104%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T20%3A10%3A21Z&sr=b&sp=r&sig=SgUgOOupN35E38Hy9IF80pPuoZCJA%2FdiURatieSyVUE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 21:45 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +### Example 2: Get the operation status
The Get Operation is common for all other different operations as well including mute, unmute, start hold music, stop hold music and others. Can I create separate PR for adding new topic: Get Operation?

2022-04-08 17:06 UTC, opbld31 commented
Docs Build status updates of commit _[a1c815f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1c815fd622bbecc298b157fc91d51b2a4067967)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identifylargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081703112106-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T17%3A06%3A49Z&sr=b&sp=r&sig=ugtI6JXY8gia%2BZ4rPX5m8ezpqDZ89l7DeNMaFzW1t44%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 17:10 UTC, navali-msft commented on api-reference/beta/resources/identifylargegalleryview.md
> +After the large gallery view is added successfully in the call, the developers need to identify participant from the roster which is sending those large gallery view videos feeds.
Updated.

2022-04-08 17:11 UTC, navali-msft commented on api-reference/beta/resources/identifylargegalleryview.md
> +The following example and guidance can help identify the application which can be subscribed to get the feeds.
Changed to examples.

2022-04-08 17:11 UTC, navali-msft commented on api-reference/beta/resources/identifylargegalleryview.md
> +title: "How to identify the large gallery view application in the roster"
Ignore this one and updated based on other comment.

2022-04-08 17:11 UTC, navali-msft commented on api-reference/beta/resources/identifylargegalleryview.md
> +# How to identify the large gallery view application in the roster
Done.

2022-04-08 17:11 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview.md
> +If successful, this method returns a `202 Accepted` response code and
I removed it but it was added after some merge. Removed it again. Thanks.

2022-04-08 21:02 UTC, isvargasmsft commented on api-reference/beta/resources/identifylargegalleryview.md
> +# Learn how to identify the large gallery view application in the roster
This topic looks like a conceptual topic. Please move it from the reference folder and add it to the conceptual docs, and include it in the conceptual TOC.

2022-04-08 22:21 UTC, navali-msft commented on api-reference/beta/resources/identifylargegalleryview.md
> +# Learn how to identify the large gallery view application in the roster
Moved to conceptual folder and added to toc. Thanks.

2022-04-08 22:22 UTC, opbld33 commented
Docs Build status updates of commit _[253c2a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/253c2a94c3dcf93af21652e19bac5888f13c5da3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :x:Error | | [Details](#user-content-e396c9f20f2661e03d9541d9be239809-3673a6a8)

<a id="e396c9f20f2661e03d9541d9be239809-3673a6a8"></a>
### [concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md)
 - **Line 14, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/beta-disclaimer.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204082220427935-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T22%3A22%3A35Z&sr=b&sp=r&sig=xPo396Aaks4Y9%2B594H%2BChSJPui0cDBfO6z%2Bt3TWiocY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 23:26 UTC, opbld31 commented
Docs Build status updates of commit _[88b1a74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88b1a74695574085a9d21ef609cba19dae3620b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204082324378739-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T23%3A26%3A24Z&sr=b&sp=r&sig=Bb6VAai5iGnfnmk7M22%2F6axzIRRP57l%2FV5lY%2BGg9280%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-09 00:18 UTC, opbld32 commented
Docs Build status updates of commit _[d0e3a65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0e3a65088588b8e3f602e38bca21cd28d61bea0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204090017175566-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-10T00%3A18%3A52Z&sr=b&sp=r&sig=EeHYEKiZ9%2Flwaqbd4gRE%2FRfWZ6M3dH0b%2BGLtu99tJ%2F0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-09 00:53 UTC, opbld34 commented
Docs Build status updates of commit _[ba8ea2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba8ea2e7a46c9484fb2059efbb8f092c7cbb30d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204090050108116-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-10T00%3A53%3A18Z&sr=b&sp=r&sig=4mUXiu8fY9gDJD%2FbX825xOLtk%2ByuK60k4LX7oaQIlls%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-09 02:12 UTC, opbld30 commented
Docs Build status updates of commit _[1f1e5d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f1e5d18163a303ac84754b492b00ae5ec49a2fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204090209280638-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-10T02%3A12%3A14Z&sr=b&sp=r&sig=84QYdh9ax01inSE5gcJCqdldYYSW%2F9IXs%2Bdq6brvUno%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-09 02:12 UTC, satyakonmsft approved these changes

2022-04-09 02:20 UTC, opbld30 commented
Docs Build status updates of commit _[79aa3b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79aa3b176b7de3277ec4bc10fe04a2bb0b320e8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204090218382811-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-10T02%3A20%3A25Z&sr=b&sp=r&sig=cJcs%2BKXqZEmU1tAT8Y7lN76DAfay2VpS71XetbvE0AE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 21:56 UTC, JarbasHorst commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +
Please, add the Methods table to this resource topic to list the new Get addLargeGalleryViewOperation API.

2022-04-11 21:58 UTC, JarbasHorst commented
Hi @navali-msft, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time.

Also, please merge PR [16489](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16489) into your branch to include my fixes.

2022-04-12 18:37 UTC, opbld33 commented
Docs Build status updates of commit _[c74d931](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c74d931501eb53832be8f4d0fd705f7195f672ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204121835416786-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T18%3A37%3A57Z&sr=b&sp=r&sig=U4r2t4eKiTNcGt4x7ru8vjqlCCTEO68aQHgyzBOk3ds%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 19:12 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +| Application                            | None.                                  |
No special capabilities are required to run this api.

2022-04-12 19:13 UTC, navali-msft commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +| status                         | String                      | The status of the operation. Possible values are: `notStarted`, `running`, `completed`, `failed`. Read-only.
I checked the other apis and all of them are putting type as String? The values are going over the wire as String so why we need enum here?

2022-04-12 19:20 UTC, opbld32 commented
Docs Build status updates of commit _[831859e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/831859eaff45389ef814dacdac71500093f677da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204121917137031-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T19%3A20%3A24Z&sr=b&sp=r&sig=j7e1tl4IioVwWvh8JOHeqdjiEyyudUCos9Z%2FL1z3Ryo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 20:10 UTC, JarbasHorst commented on api-reference/beta/resources/addlargegalleryviewoperation.md
> +| status                         | String                      | The status of the operation. Possible values are: `notStarted`, `running`, `completed`, `failed`. Read-only.
Hi @navali-msft, let's include Isaac in this discussion. So, I will move your question to MS Teams.

2022-04-13 20:43 UTC, JarbasHorst commented
Hi @navali-msft, thank you for addressing my comments. Please, merge PR [16518](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16518) into this branch to include my final edits.

@Lauragra, @isvargasmsft, this PR is ready for your final approval. We have currently [this](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16104/files/79aa3b176b7de3277ec4bc10fe04a2bb0b320e8e#r847755901) one open topic that still needs clarification.

2022-04-18 15:42 UTC, isvargasmsft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +Get the status of addLargeGalleryView operation.
Please add the reference link to the addLargeGalleryView operation.

2022-04-18 15:43 UTC, isvargasmsft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +# [HTTP](#tab/http)
Line 52: please remove this line. Those tabs are automatically generated.

2022-04-18 15:43 UTC, isvargasmsft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +```msgraph-interactive
Line 58: please remove msgraph-interactive and replace with http

2022-04-18 15:45 UTC, isvargasmsft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +---
According to the CSDL, the name of this resource is addLargeGalleryViewOperation. Please use the complete name in the file name and in the title to avoid confusion with the operation name.

2022-04-18 22:27 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +---
Not sure why you are seeing old filename here. I have updated the filename and description.

2022-04-18 22:27 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryview-get.md
> +```msgraph-interactive
done.

2022-04-18 22:29 UTC, opbld34 commented
Docs Build status updates of commit _[d271b4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d271b4d8548624bd849cc7aa0ae1773330875bff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204182226284213-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T22%3A29%3A10Z&sr=b&sp=r&sig=v7eiN1aRVDBJ6ZhBaByGhHuUayNQkbdotrJIdHS6hV4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 00:48 UTC, opbld32 commented
Docs Build status updates of commit _[498377d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/498377db41a511ee2b2412ebe623114aa9b708e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/call-addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204190046558020-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T00%3A48%3A32Z&sr=b&sp=r&sig=%2FPrplKQSsfV4WQcoQBtExuB%2BwgiBIqWzkqh8B3hdov8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 00:50 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get large gallery view operation
I recommend adding "status" to this TOC entry for clarity - Get large gallery view operation status.

2022-04-19 00:55 UTC, Lauragra commented on api-reference/beta/api/call-addlargegalleryviewoperation-get.md
> +title: "Get addLargeGalleryViewOperation"
I think the file name here should just be "addlargegalleryviewoperation-get". Not sure why we're prefacing with "call".

2022-04-19 01:03 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get large gallery view operation
For these two new operations, should we follow a pattern similar to what we did for IVR scenarios, Participant, and surface the resource in the TOC, with the two operations nested under it?

2022-04-19 01:05 UTC, Lauragra commented on concepts/cloud-communications-identifylargegalleryview.md
> +# Identify the large gallery view application in the roster
The title and introduction to this article need to better set the context. The title should include important keywords like Microsoft Graph, cloud communications API.

2022-04-19 01:08 UTC, Lauragra commented on concepts/cloud-communications-identifylargegalleryview.md
> +In this article, you will learn how to identify the large gallery view application in the roster. By identifying the large gallery view, application developers can extract relevant information and su
What is the task the developer is trying to do that would lead them to read this article? I think we need more content to set context here. Are they enabling the large gallery view in an online call? 

Also note that we address the target audience as the second person "you", not the third person "application developers".

In this content, you're using the definite article "the" as if you're referring to a specific gallery view, roster, and video feed. To generalize it, I recommend using indefinite articles "a", "an".

2022-04-19 01:09 UTC, Lauragra commented on concepts/cloud-communications-identifylargegalleryview.md
> +## Sample roster with large gallery view
We use "Sample" to refer to code samples; please update to refer to this as an "example". Suggested revision: "Roster example with large gallery view enabled". In general for global English, we use "example" as a noun. Please update the introductory text as well.

2022-04-19 01:10 UTC, Lauragra commented on concepts/cloud-communications-identifylargegalleryview.md
> +The following is a sample of the roster received by the application, once the large gallery view is successfully added to the call.
Suggested revision:
The following example shows a roster the application receives after the large gallery view is successfully added to a call.

2022-04-19 01:10 UTC, Lauragra commented on concepts/cloud-communications-identifylargegalleryview.md
> +<!-- {
This isn't a full example so I think we should remove the HTML comments; we don't want this to be validated.

2022-04-19 01:22 UTC, Lauragra commented on concepts/cloud-communications-identifylargegalleryview.md
> +## Pointers for identifying the large gallery view participant
I suggest shortening this heading to "Large gallery view participants", and then adding an introductory sentence along the lines of:

Use the following data from the roster example to identify the large gallery view participants:

2022-04-19 01:29 UTC, Lauragra commented on concepts/toc.yml
> +          - name: Identify large gallery view app
I'm not sure that this is the right TOC title, the inclusion of "app" seems misleading. The article isn't about identifying an app. Would this work: "Identify large gallery view participants"?

2022-04-19 20:50 UTC, opbld30 commented
Docs Build status updates of commit _[c54aaec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c54aaec46ea697bfbc8bd9a3574aaa8fd1bc6ff4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192048243790-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T20%3A50%3A23Z&sr=b&sp=r&sig=u7ReLWqRJrvifllYX9qLb9fpXCrsw8CKnfT1bqL%2Fix4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 20:58 UTC, navali-msft commented on concepts/cloud-communications-identifylargegalleryview.md
> +The following is a sample of the roster received by the application, once the large gallery view is successfully added to the call.
revised, thanks.

2022-04-19 20:59 UTC, navali-msft commented on concepts/cloud-communications-identifylargegalleryview.md
> +## Sample roster with large gallery view
Fixed, thanks.

2022-04-19 20:59 UTC, opbld31 commented
Docs Build status updates of commit _[e809e89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e809e8924fa10a42821e227fe7a8c515edd6a09c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192057131588-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T20%3A59%3A27Z&sr=b&sp=r&sig=8OYELNPbgG5DUJZMriQ6GGytl6urAUJuoFc1rAbjxmE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 20:59 UTC, navali-msft commented on concepts/cloud-communications-identifylargegalleryview.md
> +In this article, you will learn how to identify the large gallery view application in the roster. By identifying the large gallery view, application developers can extract relevant information and su
Added more context.

2022-04-19 21:01 UTC, navali-msft commented on concepts/cloud-communications-identifylargegalleryview.md
> +<!-- {
Removed html tags

2022-04-19 21:03 UTC, opbld31 commented
Docs Build status updates of commit _[7776b92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7776b9263501d4d383e56624107b7154f0b61829)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192101113762-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T21%3A03%3A09Z&sr=b&sp=r&sig=p4P62EFFLhSZU5MAy13Zx2KraWysRoKHH%2Fpk%2B%2BzBkq0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 21:40 UTC, navali-msft commented on concepts/cloud-communications-identifylargegalleryview.md
> +# Identify the large gallery view application in the roster
add more details in the title, please review. Thank you!

2022-04-19 21:42 UTC, navali-msft commented on api-reference/beta/toc.yml
> +        - name: Get large gallery view operation
I did add hierarchy-based menu but was told that it is not following the pattern. Just added that pattern again.

2022-04-19 21:42 UTC, navali-msft commented on api-reference/beta/api/call-addlargegalleryviewoperation-get.md
> +title: "Get addLargeGalleryViewOperation"
fixed the file name.

2022-04-19 21:42 UTC, navali-msft commented on concepts/cloud-communications-identifylargegalleryview.md
> +### Example of the large gallery view participant
Fixed.

2022-04-19 21:44 UTC, navali-msft commented on concepts/toc.yml
> +          - name: Identify large gallery view app
Fixed.

2022-04-19 21:44 UTC, navali-msft commented on api-reference/beta/toc.yml
> +        - name: Get large gallery view operation
Fixed.

2022-04-20 16:53 UTC, opbld34 commented
Docs Build status updates of commit _[e8fc3b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8fc3b5a8323e70bfcb82121e04d0671ae332fe6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204201652065938-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T16%3A53%3A57Z&sr=b&sp=r&sig=R71GW8Izme1TrdKFNkLkdZfIzBUZV%2BhuvuhR1K0arXw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 18:14 UTC, opbld33 commented
Docs Build status updates of commit _[9a742ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a742ea1065107755013d7748d25a00835c0ce25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204201811059336-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T18%3A14%3A14Z&sr=b&sp=r&sig=kL9YE3h8fKNLtXzQWujgl7qJGuIPOxJ8BJtvTmqdYBk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 02:21 UTC, opbld33 commented
Docs Build status updates of commit _[06c5395](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06c5395691d1002f82499b1c393fb99707f1b713)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210219094864-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T02%3A21%3A20Z&sr=b&sp=r&sig=PXLlfe7GqY47IbklueMhWWjBUeUTL6mDVywrbNu2nVw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 02:58 UTC, opbld33 commented
Docs Build status updates of commit _[bfc2666](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfc266626c8b059e5d56a047915b1f6858e697ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210255252624-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T02%3A58%3A34Z&sr=b&sp=r&sig=EBA4aTociRYbK95gITj%2BE0ZjZao%2BrWv2eXdCKW8zS9s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:00 UTC, opbld30 commented
Docs Build status updates of commit _[9f8a0ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f8a0adf5439f1d4c5d75dd86284793b365516a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-c5923f368a5ece79011ae490da1d42fd-8027b0de)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8027b0de)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="c5923f368a5ece79011ae490da1d42fd-8027b0de"></a>
### [api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md)
 - **Line 53, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/addlargegalleryview.md'.`````

<a id="0817dce4456c16725d5333633847d38f-8027b0de"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1576, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/addlargegalleryview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210256121914-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A00%3A47Z&sr=b&sp=r&sig=ap5cUNjCSVRZqKBx3U4NizSmadt1OTTr98qeC1y%2BoLc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[ccd0bcd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccd0bcdf44afce1847fcec1ec48a0c63bda1a889)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-68510132)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="0817dce4456c16725d5333633847d38f-68510132"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1578, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/largegalleryviewoperation.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210300171904-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A04%3A21Z&sr=b&sp=r&sig=ExErPXNLF2xYxOB5BsPmWIXPGxlVtY%2Fb2oVqiRekCUs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:06 UTC, opbld31 commented
Docs Build status updates of commit _[cb0c89e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb0c89e65fffcad3c77ba8c0c527d5ce2dcb0802)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-df4a5eab)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="0817dce4456c16725d5333633847d38f-df4a5eab"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1578, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/largegalleryviewoperation.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210301353451-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A06%3A29Z&sr=b&sp=r&sig=gkkQZLMedCwgI8RVCMpH2BnTeTRSQ1eGElK81TTyRsQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:08 UTC, opbld34 commented
Docs Build status updates of commit _[72822e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72822e8a8803c8e7ada8a391ff752fdebc1a7e7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-25bbaf3a)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="0817dce4456c16725d5333633847d38f-25bbaf3a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1576, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/addlargegalleryview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210257022587-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A08%3A27Z&sr=b&sp=r&sig=nA7Dd1HTD9dAdNVfspSIk6TjNRLNxqw2c4vvn5LaPMg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:11 UTC, opbld30 commented
Docs Build status updates of commit _[c34c3eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c34c3ebe7a08aaff8e270ab8758bde5f6bee3c73)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b5da697d)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="0817dce4456c16725d5333633847d38f-b5da697d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1578, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/largegalleryviewoperation.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210301058268-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A11%3A52Z&sr=b&sp=r&sig=3vJb0gzCISszGTQWj55L5gTfNPBHhyjBTLhI%2B1IVao8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:14 UTC, opbld33 commented
Docs Build status updates of commit _[0f3cce6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f3cce6f6c4971e8f2324c1368664641f68752f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-92fa4a27)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="0817dce4456c16725d5333633847d38f-92fa4a27"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1578, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/largegalleryviewoperation.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210310457027-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A14%3A02Z&sr=b&sp=r&sig=lKus7PnMRDAYqBjp5alU14os%2BvX%2Fef9NXMWALHEd9ZY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:17 UTC, opbld32 commented
Docs Build status updates of commit _[97d0fc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97d0fc02e62b8ada83a1c7f020fff07e223fe6b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-149377c7)
[api-reference/beta/api/addlargegalleryviewoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/addlargegalleryviewoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/addlargegalleryviewoperation-get?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/api/call-addlargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/call-addlargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/call-addlargegalleryview?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/addlargegalleryviewoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/addlargegalleryviewoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/addlargegalleryviewoperation?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/call.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta&branch=pr-en-us-16104) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/navali-msft-enableLargeGalleryView-api/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-16104) |

<a id="0817dce4456c16725d5333633847d38f-149377c7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 1578, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/largegalleryviewoperation.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210315459975-16104%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A17%3A49Z&sr=b&sp=r&sig=P4cwWuACMmdq9OoJKeu17T1niDrHt3%2B2g3ENRnZmNDU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:56 UTC, Lauragra approved these changes

2022-04-21 03:57 UTC, merged