Added documentation for registrantId
microsoftgraph/microsoft-graph-docs pull request #16131
Opened 2022-03-10 06:25 UTC by frankpeng7

2022-03-10 06:27 UTC, opbld31 commented
Docs Build status updates of commit _[47735f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47735f3ced753034efc3e18b5cf0627cf210d666)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203100625106857-16131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T06%3A27%3A13Z&sr=b&sp=r&sig=lczSkJV3nJ2Ho6kZn3bXh70%2BQo%2F436QNAY4r16hFgkw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 06:29 UTC, opbld32 commented
Docs Build status updates of commit _[f8fbc4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8fbc4aa49bc2ae95b2b8279fff792be7fff4c07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203100627085000-16131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T06%3A29%3A20Z&sr=b&sp=r&sig=dMbacSkHD3WFJMDdnlSr7AUdoW4MKF1o10%2FUeYat8sU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 22:58 UTC, isvargasmsft commented on api-reference/beta/resources/attendancerecord.md
> +| registrantId | String | Unique identifier of a [meetingRegistrant](meetingregistrantbase.md). Presents when the participant has registered for the meeting. |
Please go to the List attendanceRecords topic and edit the responses in the examples section to include this new property.

2022-03-10 22:59 UTC, isvargasmsft requested changes
Please also include this new property in the example responses of the methods that return the attendanceRecord resource type. I believe its only the list operation.

2022-03-11 22:01 UTC, opbld31 commented
Docs Build status updates of commit _[3ec921c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ec921c2aeee3c68a9c60f9c52d57ea08e680107)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203112158509182-16131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T22%3A01%3A03Z&sr=b&sp=r&sig=RfDV5MunczcDdiL6Hsoy%2BdUQKmfUVxNLsgTYcYWRgck%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 22:33 UTC, isvargasmsft approved these changes

2022-03-12 01:36 UTC, Lauragra approved these changes

2022-03-19 00:31 UTC, opbld32 commented
Docs Build status updates of commit _[4ba6598](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ba659879838f161702bdf718ed6649a6cf7cb83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203190030024980-16131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-19T00%3A31%3A52Z&sr=b&sp=r&sig=RUoy5Khuc%2FusaCcjX4DjAi319ykPbdblCDL6q2TGHUs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 00:42 UTC, opbld31 commented
Docs Build status updates of commit _[baff7be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/baff7bed208102f56aaac008eaff0182d8ea3bf9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attendancerecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/api/attendancerecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attendancerecord-list?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[api-reference/beta/resources/attendancerecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/api-reference/beta/resources/attendancerecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-16131) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/registrantId_only/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203190040478636-16131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-19T00%3A42%3A37Z&sr=b&sp=r&sig=hi1B85pOnaCCIPlW%2FQmrz%2BT3L%2F5mlM01evvK7nyokqg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 00:47 UTC, merged