Internal federation api docs
microsoftgraph/microsoft-graph-docs pull request #16140
Opened 2022-03-10 23:42 UTC by akgoel23

2022-03-10 23:44 UTC, opbld31 commented
Docs Build status updates of commit _[331bea3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/331bea3dfa0592e9b1d67559798d2d4522fa97d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-da80ddbe376413863fd2acf2910504cd-ace8ec09)
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-a5bcebed906fb92ee7157dc0dd73d135-ace8ec09)
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-4a9752f6d8029e976aaf2276a024c0d0-ace8ec09)
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-224a04a8a34a90531f92207b80d3a551-ace8ec09)
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-15c145033ef39a19bbb8db8b7c6cb2ac-ace8ec09)

<a id="da80ddbe376413863fd2acf2910504cd-ace8ec09"></a>
### [api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="a5bcebed906fb92ee7157dc0dd73d135-ace8ec09"></a>
### [api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="4a9752f6d8029e976aaf2276a024c0d0-ace8ec09"></a>
### [api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 60, Column 33**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/signingcertificateupdatestatus.md'.`````

<a id="224a04a8a34a90531f92207b80d3a551-ace8ec09"></a>
### [api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 59, Column 33**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/signingcertificateupdatestatus.md'.`````

<a id="15c145033ef39a19bbb8db8b7c6cb2ac-ace8ec09"></a>
### [api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-p [...]

2022-03-11 03:56 UTC, opbld34 commented
Docs Build status updates of commit _[0d2e16c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d2e16c730b513bf7ee41887d63aee3b0884b108)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-da80ddbe376413863fd2acf2910504cd-287fa260)
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-a5bcebed906fb92ee7157dc0dd73d135-287fa260)
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-4a9752f6d8029e976aaf2276a024c0d0-287fa260)
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-224a04a8a34a90531f92207b80d3a551-287fa260)
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-15c145033ef39a19bbb8db8b7c6cb2ac-287fa260)

<a id="da80ddbe376413863fd2acf2910504cd-287fa260"></a>
### [api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="a5bcebed906fb92ee7157dc0dd73d135-287fa260"></a>
### [api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="4a9752f6d8029e976aaf2276a024c0d0-287fa260"></a>
### [api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 60, Column 33**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/signingcertificateupdatestatus.md'.`````
 - **Line 61, Column 586**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 61, Column 586**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="224a04a8a34a90531f92207b80d3a551-287fa260"></a>
### [api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See docu [...]

2022-03-11 04:20 UTC, opbld31 commented
Docs Build status updates of commit _[d27fb23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d27fb237352c6033616c93ccac2cd587f21ed900)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-da80ddbe376413863fd2acf2910504cd-a3b72ff1)
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-a5bcebed906fb92ee7157dc0dd73d135-a3b72ff1)
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-4a9752f6d8029e976aaf2276a024c0d0-a3b72ff1)
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-224a04a8a34a90531f92207b80d3a551-a3b72ff1)
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-15c145033ef39a19bbb8db8b7c6cb2ac-a3b72ff1)

<a id="da80ddbe376413863fd2acf2910504cd-a3b72ff1"></a>
### [api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="a5bcebed906fb92ee7157dc0dd73d135-a3b72ff1"></a>
### [api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="4a9752f6d8029e976aaf2276a024c0d0-a3b72ff1"></a>
### [api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 60, Column 33**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/signingcertificateupdatestatus.md'.`````
 - **Line 61, Column 586**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 61, Column 586**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="224a04a8a34a90531f92207b80d3a551-a3b72ff1"></a>
### [api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See docu [...]

2022-03-21 23:31 UTC, opbld32 commented
Docs Build status updates of commit _[51ec18e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51ec18e53253c3aa37cdfda74b365f46b5e38599)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-4a9752f6d8029e976aaf2276a024c0d0-640af59e)
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-224a04a8a34a90531f92207b80d3a551-640af59e)
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-15c145033ef39a19bbb8db8b7c6cb2ac-640af59e)
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

<a id="4a9752f6d8029e976aaf2276a024c0d0-640af59e"></a>
### [api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md)
 - **Line 61, Column 586**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 61, Column 586**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="224a04a8a34a90531f92207b80d3a551-640af59e"></a>
### [api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md)
 - **Line 60, Column 586**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 60, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 60, Column 586**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="15c145033ef39a19bbb8db8b7c6cb2ac-640af59e"></a>
### [api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md)
 - **Line 16, Column 290**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/hybrid/whatis-fed' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 34, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203212329405595-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T23%3A31%3A48Z&sr=b&sp=r&sig=aRfPF0bajdxv9KFSUvuIcX%2BPQ3zJ%2BktNnyOrhJ3o%2Fmk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your  [...]

2022-03-21 23:38 UTC, opbld31 commented
Docs Build status updates of commit _[ee8fb70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee8fb705f63bd79eebaa41e6088690a4541c8e14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-4a9752f6d8029e976aaf2276a024c0d0-84724559)
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-224a04a8a34a90531f92207b80d3a551-84724559)
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-15c145033ef39a19bbb8db8b7c6cb2ac-84724559)
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

<a id="4a9752f6d8029e976aaf2276a024c0d0-84724559"></a>
### [api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md)
 - **Line 61, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings' will be broken in isolated environments. Replace with a relative link.`````

<a id="224a04a8a34a90531f92207b80d3a551-84724559"></a>
### [api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md)
 - **Line 60, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 60, Column 586**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="15c145033ef39a19bbb8db8b7c6cb2ac-84724559"></a>
### [api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md)
 - **Line 16, Column 290**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/hybrid/whatis-fed' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 34, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203212336179115-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T23%3A38%3A16Z&sr=b&sp=r&sig=n69u%2BasLwwWasbgDEdRjKug5MZRiABuq7OuApuUJtRQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 23:43 UTC, opbld32 commented
Docs Build status updates of commit _[511b7e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/511b7e04385c47c1c1be7c017d43fd4d215dd229)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-4a9752f6d8029e976aaf2276a024c0d0-fac96eb1)
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-224a04a8a34a90531f92207b80d3a551-fac96eb1)
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) | [Details](#user-content-15c145033ef39a19bbb8db8b7c6cb2ac-fac96eb1)
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

<a id="4a9752f6d8029e976aaf2276a024c0d0-fac96eb1"></a>
### [api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md)
 - **Line 61, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings' will be broken in isolated environments. Replace with a relative link.`````

<a id="224a04a8a34a90531f92207b80d3a551-fac96eb1"></a>
### [api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md)
 - **Line 60, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 60, Column 586**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="15c145033ef39a19bbb8db8b7c6cb2ac-fac96eb1"></a>
### [api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md)
 - **Line 16, Column 290**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/hybrid/whatis-fed' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 34, Column 586**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/set-msoldomainfederationsettings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203222340592691-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T23%3A43%3A50Z&sr=b&sp=r&sig=N9XTlo8TIAB81ruF1q%2B22yK4TLqJfjEuviwhHVPCG14%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 07:55 UTC, opbld33 commented
Docs Build status updates of commit _[a057562](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0575625200e14b02f1ae0a581c32be43e1285cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203250753269048-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-25T07%3A55%3A39Z&sr=b&sp=r&sig=Uc4KRX7zwIXzJwGvB4uWJZTy1xOMLQg12yekibpB65Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 08:06 UTC, opbld33 commented
Docs Build status updates of commit _[c3139db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3139dbf771f0dd5f538af1fae57cf89e0672d5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203250803577197-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-25T08%3A06%3A14Z&sr=b&sp=r&sig=brBVyddkgqVK2NfCM7QyKisD9KfzVF3HHAK1JtWFxFc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 08:13 UTC, opbld33 commented
Docs Build status updates of commit _[c3139db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3139dbf771f0dd5f538af1fae57cf89e0672d5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203250810143721-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-25T08%3A13%3A10Z&sr=b&sp=r&sig=MWuXeu6nFXnHUmD3AqB6t8rtGkcdnqWGn2EXpHYFMM0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 08:27 UTC, FaithOmbongi commented on api-reference/beta/api/internaldomainfederation-update.md
> +  "truncated": true
The missing Odata type looks like the reason for the API doctor error _Resource type was null or missing in response metadata, so we assume there is no response to validate._. Basically, the validator doesn't know which object type the response body represents. This OData type declaration is how we tell the validator about it.
```suggestion
  "truncated": true,
  "@odata.type": "microsoft.graph.internalDomainFederation"
```

2022-03-25 17:19 UTC, opbld30 commented
Docs Build status updates of commit _[a833d97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a833d9795c048b0fd56118449490699673e287d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203251717013874-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-25T17%3A19%3A16Z&sr=b&sp=r&sig=3i2jqk%2FCWe2EU6G5JwtiyV3ZJGpj6GKpgXT%2BJxk9L3w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 17:23 UTC, akgoel23 commented on api-reference/beta/api/internaldomainfederation-update.md
> +  "truncated": true
Thanks @FaithOmbongi. The suggestion helped fixed the error. I was able to resolve all the errors.

2022-03-25 20:07 UTC, Justinha commented on api-reference/beta/api/internaldomainfederation-post.md
> +|federatedIdpMfaBehavior|federatedIdpMfaBehavior|Determines whether Azure AD accepts the MFA performed by the identity provider or performs Azure MFA when a federated user accesses an application for
Add a period after configured.

2022-03-28 20:01 UTC, FaithOmbongi requested changes
Thank you @akgoel23 for your work on this PR. A few changes:

- Please document the **federationConfiguration** relationship in the [domain resource doc](https://docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta#relationships). Also indicate that it supports the `$expand `query parameter.
- In the [Get domain](https://docs.microsoft.com/en-us/graph/api/domain-get?view=graph-rest-beta&tabs=http) doc, please add an Example 2 to retrieve the internal domain federation configurations - I see a `/domains/contoso.com?$expand=federationConfiguration` request in your API.md.
- File name fix internaldomainfederation-post.md => **domain-post-federationconfiguration.md** following the file naming guidance.
- You're missing the List federationConfiguration API doc. The file name is domain-list-federationconfiguration.md. Please add the file and also add it to the Methods table.
- GLOBAL: Instead of saying just "identity provider", please use "federated identity provider" where needed to distiguish between Azure AD identity provider and the federated one that's the reason for this set of APIs.
- Update the TOC
- Please add the changelog.

2022-03-29 19:26 UTC, opbld32 commented
Docs Build status updates of commit _[5454bd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5454bd2c7c749d0c30e34f91cd487279dd53b7e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291924023775-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T19%3A26%3A10Z&sr=b&sp=r&sig=TW39SPq2EftMYvK%2BIMwpLzAIhVKBpJA37jmynVXSXV4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 19:46 UTC, opbld34 commented
Docs Build status updates of commit _[abe4d9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abe4d9c0f58c0102f43f84a74d75fd8fc63de2ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291944129573-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T19%3A46%3A15Z&sr=b&sp=r&sig=MyNHMyZkwek8j5KmWrnk8CNwWZFest8hvkcvpPWNLZw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 19:55 UTC, opbld30 commented
Docs Build status updates of commit _[32ba039](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32ba039578eb72c4f54ed2cc660513b2c0b6694e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291947185117-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T19%3A55%3A02Z&sr=b&sp=r&sig=Tk1udpn3hNwCiyY1gdeO5EhVchElSm%2Bz1AGjdFh439w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:00 UTC, opbld33 commented
Docs Build status updates of commit _[b75279d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b75279d91108d6fe13366b5d753f74d87626dd86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291950426327-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T19%3A59%3A59Z&sr=b&sp=r&sig=5qrtVhP9bOlkZ89aD9rYJw%2BhM7rXO7iEEmHVLCCq7JA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:02 UTC, opbld32 commented
Docs Build status updates of commit _[6456d38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6456d386c8950f4c3853bd58b6e372ab092af57e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291949216295-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A02%3A09Z&sr=b&sp=r&sig=dJvASiNDIp34O3Dv1AnCVlItVFJvn0a8MOXmcEbJxWs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:04 UTC, opbld30 commented
Docs Build status updates of commit _[612eb3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/612eb3f1447574d1ece9b435a995dc5c0249975b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291949042190-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A04%3A18Z&sr=b&sp=r&sig=DTCcT%2BDaK35Ae2Lxv3inm7siUxVUZou3Zw%2FVBjjNnio%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:06 UTC, opbld34 commented
Docs Build status updates of commit _[fc565b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc565b7c7018cef92e8f5510ced3facd7a112f70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291949525829-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A06%3A34Z&sr=b&sp=r&sig=8raZHyUi6duk4FmUfnbod99Q43VALfqrla9twfe84Y4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:08 UTC, opbld31 commented
Docs Build status updates of commit _[6f92ccc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f92cccf2639affc41477720cb5c60ab06e57edc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291950010950-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A08%3A35Z&sr=b&sp=r&sig=VsylFH%2FqzaHy1R4YrR%2FBktz5Vn33PObG8ErTbmSM4E8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:12 UTC, opbld33 commented
Docs Build status updates of commit _[fc565b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc565b7c7018cef92e8f5510ced3facd7a112f70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291949422265-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A12%3A32Z&sr=b&sp=r&sig=BK1qg22po9PrJaKZnR4CU%2F3bml4z5GVFKDDcGVGhsR8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:19 UTC, opbld33 commented
Docs Build status updates of commit _[4716ea7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4716ea7db791f187fd9286b7929a8018f3869869)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291950224662-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A19%3A11Z&sr=b&sp=r&sig=vrY7uh3H64Cak5tHgxfblKfZFnfsm67VU00FejP%2BSNI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 20:21 UTC, opbld30 commented
Docs Build status updates of commit _[0632546](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0632546d9529904f8981150264d2b0d1f6c5c666)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-post?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203291947341913-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T20%3A21%3A35Z&sr=b&sp=r&sig=OQYX%2FWks2fFZ7aqgVJWH776wVZDDq4LOJ6AXXJlwyGY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 21:18 UTC, akgoel23 commented on api-reference/beta/resources/internaldomainfederation.md
> +|[Create internalDomainFederation](../api/internaldomainfederation-post.md)|[internalDomainFederation](../resources/internaldomainfederation.md)|Create a new [internalDomainFederation](../resources/i
made changes

2022-03-29 21:19 UTC, akgoel23 commented on api-reference/beta/api/internaldomainfederation-post.md
> +---
Done.

2022-03-29 21:19 UTC, akgoel23 commented on api-reference/beta/api/internaldomainfederation-post.md
> +|Property|Type|Description|
Done.

2022-03-29 21:20 UTC, akgoel23 commented on api-reference/beta/api/internaldomainfederation-update.md
> +|Property|Type|Description|
Done.

2022-03-29 21:24 UTC, opbld31 commented
Docs Build status updates of commit _[885edc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/885edc9bbddc6b8a84cbdeb96a41d008f9287c2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203292121451942-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T21%3A24%3A47Z&sr=b&sp=r&sig=MCxm6gvPlUdQiPbFIlVN2oTuka3laZS3%2Fwv520eJ730%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 22:43 UTC, opbld33 commented
Docs Build status updates of commit _[5352870](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5352870de3717012938a1a6abf15d6ba39f4841f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203292241135057-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T22%3A43%3A07Z&sr=b&sp=r&sig=vuTER2uXsjS0Lvmtba7Lhj2%2B1cpqF0lN5chdgm7R8Bo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 09:50 UTC, FaithOmbongi requested changes
Hi @akgoel23, I've left suggestions for minor fixes to address including the changelog before approval.

2022-03-31 09:50 UTC, FaithOmbongi commented on api-reference/beta/api/domain-post-federationconfiguration.md
> +|preferredAuthenticationProtocol|authenticationProtocol|Preferred authentication protocol. The possible values are: `wsFed`, `saml`, `unknownFutureValue`. Inherited from [samlOrWsFedProvider](../reso
The inheritance relationship isn't necessary in the Create properties table.
```suggestion
|displayName|String|The display name of the federated identity provider.|
|issuerUri|String|Issuer URI of the federation server.|
|metadataExchangeUri|String|URI of the metadata exchange endpoint used for authentication from rich client applications.|
|signingCertificate|String|Current certificate used to sign tokens passed to the Microsoft identity platform. The certificate is formatted as a Base64 encoded string of the public portion of the federated IdP's token signing certificate and must be compatible with the X509Certificate2 class. <br>This property is used in the following scenarios: <li> If a rollover is required outside of the autorollover update <li> A new federation service is being set up <li> If the new token signing certificate isn't present in the federation properties after the federation service certificate has been updated.<br>Azure AD updates certificates via an autorollover process in which it attempts to retrieve a new certificate from the federation service metadata, 30 days before expiry of the current certificate. If a new certificate isn't available, Azure AD monitors the metadata daily and will update the federation settings for the domain when a new certificate is available.|
|passiveSignInUri|String|URI that web-based clients are directed to when signing in to Azure AD services.|
|preferredAuthenticationProtocol|authenticationProtocol|Preferred authentication protocol. The possible values are: `wsFed`, `saml`, `unknownFutureValue`.|
```

2022-03-31 09:50 UTC, FaithOmbongi commented on api-reference/beta/api/internaldomainfederation-update.md
> +|preferredAuthenticationProtocol|authenticationProtocol|Preferred authentication protocol. The possible values are: `wsFed`, `saml`, `unknownFutureValue`. Inherited from [samlOrWsFedProvider](../reso
Inheritances aren't also required in Update docs
```suggestion
|displayName|String|The display name of the federated identity Provider (IdP). |
|federatedIdpMfaBehavior|federatedIdpMfaBehavior|Determines whether Azure AD accepts the MFA performed by the federated IdP when a federated user accesses an application that is governed by a conditional access policy that requires MFA. The possible values are: `acceptIfMfaDoneByFederatedIdp`, `enforceMfaByFederatedIdp`, `rejectMfaByFederatedIdp`, `unknownFutureValue`. For more information, see [federatedIdpMfaBehavior values](#federatedidpmfabehavior-values).|
|isSignedAuthenticationRequestRequired|Boolean|If `true`, when SAML authentication requests are sent to the federated SAML IdP, Azure AD will sign those requests using the OrgID signing key. If `false` (default), the SAML authentication requests sent to the federated IdP are not signed.|
|issuerUri|String|Issuer URI of the federation server.|
|metadataExchangeUri|String|URI of the metadata exchange endpoint used for authentication from rich client applications.|
|nextSigningCertificate|String|Fallback token signing certificate that is used to sign tokens when the primary signing certificate expires. Formatted as Base64 encoded strings of the public portion of the federated IdP's token signing certificate. Needs to be compatible with the X509Certificate2 class. Much like the **signingCertificate**, the **nextSigningCertificate** property is used if a rollover is required outside of the auto-rollover update, a new federation service is being set up, or if the new token signing certificate is not present in the federation properties after the federation service certificate has been updated.|
|passiveSignInUri|String|URI that web-based clients are directed to when signing into Azure AD services. |
|preferredAuthenticationProtocol|authenticationProtocol|Preferred authentication protocol. The possible values are: `wsFed`, `saml`, `unknownFutureValue`. |
```

2022-03-31 09:50 UTC, FaithOmbongi commented on api-reference/beta/api/domain-post-federationconfiguration.md
> +|nextSigningCertificate|String|Fallback token signing certificate that is used to sign tokens when the primary signing certificate expires. Formatted as Base64 encoded strings of the public portion o
```suggestion
|nextSigningCertificate|String|Fallback token signing certificate that is used to sign tokens when the primary signing certificate expires. Formatted as Base64 encoded strings of the public portion of the federated IdP's token signing certificate. Needs to be compatible with the X509Certificate2 class. Much like the **signingCertificate**, the **nextSigningCertificate** property is used if a rollover is required outside of the auto-rollover update, a new federation service is being set up, or if the new token signing certificate is not present in the federation properties after the federation service certificate has been updated.|
```

2022-03-31 09:50 UTC, FaithOmbongi commented on api-reference/beta/api/internaldomainfederation-delete.md
> +>**Note:** The response object shown here might be shortened for readability.
Bump.

2022-03-31 09:50 UTC, FaithOmbongi commented on api-reference/beta/resources/signingcertificateupdatestatus.md
> +|  |  |
You're missing some data here. The suggestion from the previous review was for you to document all the possible statuses of **certificateUpdateResult** except `unknownFutureValue`. Just the value and description required. I see in the API.md there are ~15 possible statuses.

2022-03-31 09:50 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: api/internaldomainfederation-delete.md
Does calling it SAML or WS-Fed internal domain federation make sense and is it applicable for internal federation? I recall we discussed this with Namrata while doing the one for external identities where she advised that we explicitly call it SAML/WS-Fed because there were other protocols used by external IdPs. I wonder if the same can be said for internal IdP. https://docs.microsoft.com/en-us/graph/api/resources/samlorwsfedexternaldomainfederation

Suggestion to just use the verbs Get, Create etc is for scannability and because unlike for external IdP API docs, you don't have other methods that overlap with the basic CRUD methods.
```suggestion
          - name: SAML or WS-Fed internal domain federation
            href: resources/internaldomainfederation.md
            items:             
            - name: Get
              href: api/internaldomainfederation-get.md
            - name: Create
              href: api/domain-post-federationconfiguration.md
            - name: Update
              href: api/internaldomainfederation-update.md
            - name: Delete
              href: api/internaldomainfederation-delete.md
```

2022-03-31 09:50 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ApiChange": "EnumType",
A changelog gen bug generated the incorrect ApiChange value. The fix is underway.
```suggestion
          "ApiChange": "Enum type",
          "ChangedApiName": "federatedIdpMfaBehavior",
          "ChangeType": "Addition",
          "Description": "Added the **federatedIdpMfaBehavior** enumeration type.",
          "Target": "federatedIdpMfaBehavior"
        },
        {
          "Id": "438838d1-a936-4789-9d1c-c929788be1eb",
          "ApiChange": "Enum type",
```

2022-03-31 09:50 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **federationConfiguration** relationship to [domain](https://docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta) resource.",
Changelog gen bug
```suggestion
          "Description": "Added the **federationConfiguration** relationship to the [domain](https://docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta) resource.",
```

2022-03-31 09:50 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [internalDomainFederation](https://docs.microsoft.com/en-us/graph/api/resources/internalDomainFederation?view=graph-rest-beta) resource",
Is the 2nd sentence accurate?
```suggestion
          "Description": "Added the [internalDomainFederation](https://docs.microsoft.com/en-us/graph/api/resources/internalDomainFederation?view=graph-rest-beta) resource and related methods. Use this resource to federate your domains with Azure AD.",
```

2022-03-31 15:53 UTC, opbld32 commented
Docs Build status updates of commit _[7c2a7c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c2a7c7835ebe6830824f35f9855a1a642954d60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311551072152-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T15%3A53%3A04Z&sr=b&sp=r&sig=%2Ff8PZWiVoRIGfFZo6aTnCxVBUq%2F2aBllBS9%2BWdKxmeI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 16:44 UTC, opbld32 commented
Docs Build status updates of commit _[7c1598b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c1598b066cb7fe3d8701e8509a29955f954fffa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311642161892-16140%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T16%3A44%3A06Z&sr=b&sp=r&sig=RzCakAqhsOQng62eptPzq3qXltdG0n%2BDbtC90Ff7vRI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 16:18 UTC, FaithOmbongi approved these changes
Hi @akgoel23 , I've left one suggestion in the signingcertificateupdatestatus.md file, specifically the table of possible response codes. Please tweak, apply that suggestion where possible.

Otherwise, your PR approved with suggestions.

2022-04-01 16:18 UTC, FaithOmbongi commented on api-reference/beta/resources/signingcertificateupdatestatus.md
> +|providerError|Received InternalServerError from the provider.|
Suggestions for minor updates
```suggestion
|success|The certificate update operation was successful.|
|unknownError|The reason for failure is undefined.|
|internalServerError|There was an internal server error while processing the request.|
|noValidExistingCertFound|No valid existing signing certificate was found.|
|noStsAuthUrlFound|No STS authentication URL was found.|
|noFederationProtocolFound|The federation protocol was undefined.|
|noNewCertificateFound|No new certificate was found.|
|couldNotAccessRemoteHost|Could not reach the provider to get the new certificates.|
|connectionError|There was a connection error, for example, a connection time out.|
|xmlParsingError|Failed to parse the XML.|
|badRequest|Received a `400 BadRequest` error code in the fed metadata request.|
|unauthorized|Received `401 Unauthorized` error code in the fed metadata request.|
|forbidden|Received `403 Forbidden` error code in the fed metadata request.|
|notFound|Received `404 NotFound` error code in the fed metadata request.|
|providerError|Received a `500 InternalServerError` error code from the provider.|
```

2022-04-01 16:34 UTC, Justinha approved these changes

2022-04-12 19:54 UTC, opbld30 commented
Docs Build status updates of commit _[9f3547d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f3547d6ec0e9feed6d91f0c7bf0cdcb6b4cab01)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-01b7c670)

<a id="01b7c670"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204121953014190-16140%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T19%3A54%3A31Z&sr=b&sp=r&sig=EnIti5JGioR3cS2EQeQzo0HHipTlKOI8ehFaqWun1dk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 07:30 UTC, opbld32 commented
Docs Build status updates of commit _[676262d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/676262d437a3d37f4bb5f11d4c1c6e33dc48a2e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204130727103228-16140%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T07%3A30%3A11Z&sr=b&sp=r&sig=2ZpI3wWJgS%2BGMJDFh6h783D5llzNLQ%2BkiFyZmmNW7vA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 18:26 UTC, opbld30 commented
Docs Build status updates of commit _[e0b8fc5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0b8fc5a0cd01582c6a5050a9a228e9d28845756)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204141824491063-16140%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T18%3A26%3A32Z&sr=b&sp=r&sig=4kOZbGiJcz%2BYiJY0W1e94xynBr9Q8htns1vXXX665T0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 20:03 UTC, opbld33 commented
Docs Build status updates of commit _[73ee5a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73ee5a63db0287dbdbf4e34cd7dac43108cbff4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/domain-post-federationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-delete?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-get?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/api/internaldomainfederation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/internaldomainfederation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/internaldomainfederation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internaldomainfederation?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/resources/signingcertificateupdatestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/resources/signingcertificateupdatestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signingcertificateupdatestatus?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-beta&branch=pr-en-us-16140) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/InternalFederationAPIDocs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204142001444171-16140%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T20%3A03%3A49Z&sr=b&sp=r&sig=lIOqCNNuvUH37FSYQzpz97vtTPyxvxPNqK%2FSRC18deU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 20:06 UTC, merged