Add Activities related resources and api documentation
microsoftgraph/microsoft-graph-docs pull request #16154
Opened 2022-03-11 21:57 UTC by sacampbe-msft

Creating PR as a start.

2022-03-11 21:59 UTC, opbld33 commented
Docs Build status updates of commit _[70665f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70665f775a10d59b3bff2ceebd7709fd5196199f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-2f9aa8f34d57bb82cc5db79394495860-bce00e77)
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-3cd4fddcc08d90e9203d2166033f54cf-bce00e77)
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-085104483683c97ad934b59cf2025ada-bce00e77)
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-d4e1a79881f312d7485e777690d69906-bce00e77)
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-5e28ca3a938154f0a4721378988b05a2-bce00e77)
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-19b2fdcf2b99f6f73ec6d4f472113de8-bce00e77)
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-40fd6a1f210273963338edfeb0450c32-bce00e77)
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-822a3ffff62d69ddd98a1ab7f74fbbea-bce00e77)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |

<a id="2f9aa8f34d57bb82cc5db79394495860-bce00e77"></a>
### [api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivities.md(3,14)', 'beta/resources/externalconnectors-activitysettings.md(3,14)', 'beta/resources/externalconnectors-externalactivity.md(3,14)', 'beta/resources/externalconnectors-externalactivitybase.md(3,14)', 'beta/resources/externalconnectors-externalactivityresult.md(3,14)'....`````

<a id="3cd4fddcc08d90e9203d2166033f54cf-bce00e77"></a>
### [api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivi [...]

2022-03-14 19:51 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalactivity.md
> +|Method|Return type|Description|
Doesn't this resource have a Create operation?

2022-03-14 19:56 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalactivity.md
> +|[Add identity](../api/externalconnectors-externalactivity-post-performedby.md)|[microsoft.graph.externalConnectors.identity](../resources/externalconnectors-identity.md)|Add performedBy by posting t
These files should also be included in this PR:

- externalconnectors-externalactivity-list.md
- externalconnectors-externalactivity-get.md
- externalconnectors-externalactivity-update.md
- externalconnectors-externalactivity-delete.md
- externalconnectors-externalactivity-list-performedby.md
- externalconnectors-externalactivity-post-performedby.md

2022-03-14 20:17 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +
Please add the new property activitySettings to the externalConnection topic.

2022-03-14 20:18 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalitem.md
Please add the new navigation property (activities) to the Relationships section in this file.

2022-03-14 20:21 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalitem.md
> +|[addActivities](../api/externalconnectors-externalitem-addactivities.md)|[microsoft.graph.externalConnectors.externalActivityBase](../resources/externalconnectors-externalactivityBase.md) collection
Doesn't this include a **List activities** operation?

2022-03-14 20:29 UTC, isvargasmsft requested changes
Thank you very much for the work in this PR. 

Please address the comments and complete all the ToDo's in this PR. 

Kind regards, 

Isaac

2022-03-14 20:29 UTC, opbld32 commented
Docs Build status updates of commit _[5401b09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5401b09e7702c08d46e0c4a6a702185ec8ebfdf5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-2f9aa8f34d57bb82cc5db79394495860-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-3cd4fddcc08d90e9203d2166033f54cf-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-085104483683c97ad934b59cf2025ada-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-d4e1a79881f312d7485e777690d69906-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-5e28ca3a938154f0a4721378988b05a2-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-19b2fdcf2b99f6f73ec6d4f472113de8-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-40fd6a1f210273963338edfeb0450c32-a8a7f6c4)
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-822a3ffff62d69ddd98a1ab7f74fbbea-a8a7f6c4)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |

<a id="2f9aa8f34d57bb82cc5db79394495860-a8a7f6c4"></a>
### [api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivities.md(3,14)', 'beta/resources/externalconnectors-activitysettings.md(3,14)', 'beta/resources/externalconnectors-externalactivity.md(3,14)', 'beta/resources/externalconnectors-externalactivitybase.md(3,14)', 'beta/resources/externalconnectors-externalactivityresult.md(3,14)'....`````

<a id="3cd4fddcc08d90e9203d2166033f54cf-a8a7f6c4"></a>
### [api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivi [...]

2022-03-16 16:51 UTC, opbld31 commented
Docs Build status updates of commit _[e6566c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6566c580d70da88a72f72f3242ece6152d75230)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-2f9aa8f34d57bb82cc5db79394495860-86c743cb)
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-3cd4fddcc08d90e9203d2166033f54cf-86c743cb)
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-085104483683c97ad934b59cf2025ada-86c743cb)
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-d4e1a79881f312d7485e777690d69906-86c743cb)
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-5e28ca3a938154f0a4721378988b05a2-86c743cb)
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-19b2fdcf2b99f6f73ec6d4f472113de8-86c743cb)
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-40fd6a1f210273963338edfeb0450c32-86c743cb)
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-822a3ffff62d69ddd98a1ab7f74fbbea-86c743cb)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |

<a id="2f9aa8f34d57bb82cc5db79394495860-86c743cb"></a>
### [api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivities.md(3,14)', 'beta/resources/externalconnectors-activitysettings.md(3,14)', 'beta/resources/externalconnectors-externalactivity.md(3,14)', 'beta/resources/externalconnectors-externalactivitybase.md(3,14)', 'beta/resources/externalconnectors-externalactivityresult.md(3,14)'....`````

<a id="3cd4fddcc08d90e9203d2166033f54cf-86c743cb"></a>
### [api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivi [...]

2022-03-23 23:30 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalactivity.md
> +|Method|Return type|Description|
It does not have a dedicated create method.

2022-03-23 23:30 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalactivity.md
> +|[Add identity](../api/externalconnectors-externalactivity-post-performedby.md)|[microsoft.graph.externalConnectors.identity](../resources/externalconnectors-identity.md)|Add performedBy by posting t
These operations are not supported in our initial plan.

2022-03-23 23:30 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalactivity.md
> +|[Add identity](../api/externalconnectors-externalactivity-post-performedby.md)|[microsoft.graph.externalConnectors.identity](../resources/externalconnectors-identity.md)|Add performedBy by posting t
These operations will not be supported in the near future.

2022-03-23 23:31 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalactivityresult.md
> +|[Add identity](../api/externalconnectors-externalactivityresult-post-performedby.md)|[microsoft.graph.externalConnectors.identity](../resources/externalconnectors-identity.md)|Add performedBy by pos
Methods are not supported.

2022-03-23 23:31 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalitem.md
> +|[addActivities](../api/externalconnectors-externalitem-addactivities.md)|[microsoft.graph.externalConnectors.externalActivityBase](../resources/externalconnectors-externalactivityBase.md) collection
It does not.

2022-03-23 23:35 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalitem.md
Added in next update.

2022-03-23 23:36 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +
Added in next update.

2022-03-23 23:42 UTC, opbld30 commented
Docs Build status updates of commit _[f9d7319](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9d731910b3cd649fce153b6faf0393a36b9133d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-2f9aa8f34d57bb82cc5db79394495860-2969a005)
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-085104483683c97ad934b59cf2025ada-2969a005)
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-d4e1a79881f312d7485e777690d69906-2969a005)
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-5e28ca3a938154f0a4721378988b05a2-2969a005)
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-40fd6a1f210273963338edfeb0450c32-2969a005)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |

<a id="2f9aa8f34d57bb82cc5db79394495860-2969a005"></a>
### [api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/externalconnectors-externalitem-addactivities.md(3,14)', 'beta/resources/externalconnectors-urlmatchinfo.md(3,14)'.`````

<a id="085104483683c97ad934b59cf2025ada-2969a005"></a>
### [api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md)
 - **Line 36, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-identity.md'.`````

<a id="d4e1a79881f312d7485e777690d69906-2969a005"></a>
### [api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md)
 - **Line 33, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-identity.md'.`````

<a id="5e28ca3a938154f0a4721378988b05a2-2969a005"></a>
### [api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sa [...]

2022-03-23 23:45 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +
Will do, trying to generate it instead of handcrafting.

2022-04-05 16:00 UTC, isvargasmsft commented
Hello @sacampbe-msft, 

What is the status of this PR? Please feel free to ping me on the side if you have questions regarding the comments above. 

Once you have addressed the feedback, please add the label "review feedback addressed" and request re-review. 

Kind regards, 

Isaac

2022-04-07 13:25 UTC, IngarSaltvik commented on api-reference/beta/resources/externalconnectors-itemidresolver.md
> +description: Defines the rules for resolving a given URL to a connector item's id."
See comment below

2022-04-07 13:36 UTC, IngarSaltvik commented on api-reference/beta/resources/externalconnectors-urlmatchinfo.md
> +|baseUrls|String collection|**TODO: Add Description**|
A list of the URL prefixes that must match URLs to be processed by this URL-to-item-resolver.

2022-04-07 13:45 UTC, IngarSaltvik commented on api-reference/beta/resources/externalconnectors-urlmatchinfo.md
> +|urlPattern|String|**TODO: Add Description**|
A regular expression that will be matched towards the URL that is processed by this URL-to-item-resolver. The ECMAScript specification for regular expressions (ECMA-262) is used for the evaluation.

2022-04-07 14:42 UTC, IngarSaltvik commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +|priority|Int32|Priority of each urlToItemResolverBase instance. |
Suggestion: The priority which defines the sequence in which the urlToItemResolverBase instances are evaluated.

2022-04-07 14:47 UTC, IngarSaltvik commented on api-reference/beta/resources/externalconnectors-activitysettings.md
> +      "@odata.type": "microsoft.graph.externalConnectors.itemIdResolver"
This should be urlToItemResolverBase

2022-04-15 07:26 UTC, opbld32 commented
Docs Build status updates of commit _[4560314](https://github.com/microsoftgraph/microsoft-graph-docs/commits/456031475da5b312c8109d51da8aa55b43c6aadb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7d8ea23c)

<a id="7d8ea23c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204150725455940-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T07%3A26%3A18Z&sr=b&sp=r&sig=Og%2FF5dfTSLkKAzoD41OSy1YU1NJlQr1Z7uxq46c6fs4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-itemidresolver.md
> +description: Defines the rules for resolving a given URL to a connector item's id."
Done

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urlmatchinfo.md
> +**TODO: Add Description**
updated to "by an instance of"

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urlmatchinfo.md
> +|baseUrls|String collection|**TODO: Add Description**|
Done

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urlmatchinfo.md
> +|urlPattern|String|**TODO: Add Description**|
Done

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-itemidresolver.md
> +|itemId|String|Pattern representing the item id.|
Done

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +Defines the rules for resolving a given URL to a connector item.
Done

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +|priority|Int32|Priority of each urlToItemResolverBase instance. |
Done

2022-04-15 07:26 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-activitysettings.md
> +      "@odata.type": "microsoft.graph.externalConnectors.itemIdResolver"
Done

2022-04-15 07:28 UTC, opbld31 commented
Docs Build status updates of commit _[a84ca22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a84ca22c6134ec65468635e9848de7a9958bf1a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aca048ce)

<a id="aca048ce"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204150727542351-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T07%3A28%3A18Z&sr=b&sp=r&sig=QUA4i3lMXFkryViJs3vnv9bCFCUDEf2HmcgsNkbWKwU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:05 UTC, IngarSaltvik commented on api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
> +Pattern that specifies how to form the ID of the external item that the URL represents. The named groups from the regular expression in urlPattern within the [urlMatchInfo](..resources/externalconnec
This description is wrong. I think it should be the same description as we have in the subtype itemidresolver, which is:

```
Defines the rules for resolving a URL to the ID of an [externalItem](microsoft.graph.externalConnectors.externalItem](externalconnectors-externalitem.md)

2022-04-25 18:57 UTC, opbld33 commented
Docs Build status updates of commit _[01e7ad2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01e7ad2dbe302e7972d748f065bb0a51dcbdbbe9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-252fb304)

<a id="252fb304"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251854515094-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T18%3A57%3A25Z&sr=b&sp=r&sig=3Oix%2FswstZe%2BcdnMPbiY2VtbZa%2FPvJelUnhkH3QzHNU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[c0492b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0492b803bff00bfc1d7ff237aa2ec413e3b230c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-2f9aa8f34d57bb82cc5db79394495860-3c28d5c8)
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-085104483683c97ad934b59cf2025ada-3c28d5c8)
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-d4e1a79881f312d7485e777690d69906-3c28d5c8)
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-5e28ca3a938154f0a4721378988b05a2-3c28d5c8)
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-19b2fdcf2b99f6f73ec6d4f472113de8-3c28d5c8)
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-40fd6a1f210273963338edfeb0450c32-3c28d5c8)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="2f9aa8f34d57bb82cc5db79394495860-3c28d5c8"></a>
### [api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````

<a id="085104483683c97ad934b59cf2025ada-3c28d5c8"></a>
### [api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md)
 - **Line 36, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-identity.md'.`````

<a id="d4e1a79881f312d7485e777690d69906-3c28d5c8"></a>
### [api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md)
 - **Line 33, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-identity.md'.`````

<a id="5e28ca3a938154f0a4721378988b05a2-3c28d5c8"></a>
### [api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md)
 - **Line 36, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-identity.md'.`````

<a id="19b2fdcf2b99f6f73ec6d4f472113de8-3c28d5c8"></a>
### [api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/be [...]

2022-04-25 19:49 UTC, opbld31 commented
Docs Build status updates of commit _[5a29918](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a299186d45848cfcfd9950744cc68abb77d371c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251947473143-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T19%3A49%3A58Z&sr=b&sp=r&sig=8poEn9Ee2toir6ClD16JjBXkV%2BC45NFUivJJ5lzQN2M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 15:35 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalitem.md
>    "content": { "@odata.type": "microsoft.graph.externalConnectors.externalItemContent" }
Line 67: I believe there is a comma missing at the end, isn't it?

2022-04-26 15:57 UTC, opbld30 commented
Docs Build status updates of commit _[9033431](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90334314c836b8e3eb64ec677eb2e79066d75757)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204261554569492-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T15%3A57%3A50Z&sr=b&sp=r&sig=6ztdkDw0x%2FoTcf0%2FccoTuwVTcospyrCsC5iqwhQE%2B%2Fw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 15:59 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalitem.md
>    "content": { "@odata.type": "microsoft.graph.externalConnectors.externalItemContent" }
yep, that was it. Checking the other api doctor errors...

2022-04-26 16:40 UTC, opbld32 commented
Docs Build status updates of commit _[dd4fabc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd4fabc23122e040401a4185d53b0813e71fdbde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204261638005875-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T16%3A40%3A19Z&sr=b&sp=r&sig=EN2kvxNCrMlCb5DQ0KwmdazME53PLJ%2FYteboHnD9f38%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 16:45 UTC, opbld32 commented
Docs Build status updates of commit _[eaca815](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaca815ade444fc9b7aff5371c03f7a21a8a02b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204261638475264-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T16%3A45%3A07Z&sr=b&sp=r&sig=fwGN3egC0m2QmUqTsB8A5Ca3nnLkN8LCpTuRQGzjU68%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 20:50 UTC, opbld34 commented
Docs Build status updates of commit _[ee02e8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee02e8d082dd7e1c443df151c5e440c4d18643bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204272047282959-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T20%3A50%3A31Z&sr=b&sp=r&sig=GBpU2mGYvDsxvnic2Y8WyIX1t0wFiQV%2BA0WCV7MgYKw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 17:37 UTC, opbld34 commented
Docs Build status updates of commit _[fc507db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc507dbf8d75a1aaf56cdcb1f34c7ea62613d675)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281724572285-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T17%3A37%3A33Z&sr=b&sp=r&sig=f7Fc2PMMWS7kk2%2FDtFVAax0tSwJJ1tumFKFJR%2BkE3gw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 20:58 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| activitySettings|[microsoft.graph.externalConnectors.searchSettings](../resources/externalconnectors-searchsettings.md)| Collects configurable settings related to activities involving connector con
Please update the json representation section of this topic to include, not only the new property, but also all the rest of properties that were not included previously.

2022-04-28 21:20 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +          "Description": "Added the [activitySettings](https://docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalConnection?view=graph-rest-beta) resource",
Please fix this description: it should say: Added the activitySettings property to the externalConnection resource.

2022-04-28 22:07 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalactivitybase.md
> +This is an abstract type.
Please add a sentence: Base type of externalActivity and ExternalActivityResult. 

Please add reference links to both.

2022-04-28 22:08 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalactivityresult.md
> +Represents the result of processing an externalActivity. Null if successful.
Please add reference link to externalActivity.

2022-04-29 14:16 UTC, opbld34 commented
Docs Build status updates of commit _[21668dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21668dd4208dd6a636f3766670120e37c36ebb76)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-eb4ee5d3)

<a id="eb4ee5d3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204291414042473-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T14%3A16%3A23Z&sr=b&sp=r&sig=rnYkDryq7%2F40qjpfxFxQG8vW74IukRwSnDY236feB3A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 14:27 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +        },
Please add a changelog entry for the new complex type urlMatchInfo.

2022-04-29 14:33 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an identity used to set permissions on external content added to Microsoft Graph.
In general, we try to avoid descriptions that use the same name of the resource. Could we rephrase to avoid using the word identity?

2022-04-29 14:33 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-identity.md
> +---
Missing in this PR: TOC (table of contents) entries for the new entities and for the new action.

2022-04-30 01:41 UTC, opbld30 commented
Docs Build status updates of commit _[4763196](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47631961fab7fae653c4ad0170b70ada7cb2be54)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ff66824a)

<a id="ff66824a"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204300140065703-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-31T01%3A41%3A49Z&sr=b&sp=r&sig=7oTGr0COaOkket0XVWg10pABebF7ocX9CiQkTtDQSoY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-30 01:48 UTC, opbld32 commented
Docs Build status updates of commit _[60f18af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60f18af6c25a768ab8efe1e4ccb5bb8154beccab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204300145175090-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-31T01%3A48%3A41Z&sr=b&sp=r&sig=xeVTX9Mx6Rf0hkfRA%2FqkZ8mjrExjxlSdN0O%2BSXmH8nI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-30 02:40 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-identity.md
> +---
Added addActivities action to TOC but I don't think there were any additional entries needed. This PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/14168 should take care of Identity/ExternalGroupMember related updats.

2022-04-30 02:41 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an identity used to set permissions on external content added to Microsoft Graph.
Replaced identity with entity

2022-04-30 02:41 UTC, sacampbe-msft commented on changelog/Microsoft.Search.json
> +        },
Done

2022-04-30 02:41 UTC, sacampbe-msft commented on changelog/Microsoft.Search.json
> +          "Target": "externalItem"
Done

2022-04-30 02:45 UTC, opbld34 commented
Docs Build status updates of commit _[69798f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69798f40bd72035a5f59026c1be8f2e937455fe0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204300241362643-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-31T02%3A45%3A01Z&sr=b&sp=r&sig=Wlj3xl1dlntiDzrBK6PfMKMRgLjv%2BqG0ZmNozKEO5Po%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-30 02:46 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalitem.md
> +  "activities": { "@odata.type": "Collection(microsoft.graph.externalConnectors.externalActivityBase)" }
Done

2022-04-30 02:46 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalitem.md
> +| activities        | [microsoft.graph.externalConnectors.externalActivityBase](externalconnectors-externalActivity.md) collection               | An array of activities performed involving this item
Done

2022-05-02 16:39 UTC, opbld32 commented
Docs Build status updates of commit _[a82a7d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a82a7d43ebdddf720e3076720bf89907c5bfddd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205021637484498-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T16%3A39%3A48Z&sr=b&sp=r&sig=rInFCACUBET%2FgK5jBrMm%2Bs8bK8wtKgtHosjDEubToyI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 16:50 UTC, opbld31 commented
Docs Build status updates of commit _[a8ae6a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8ae6a28f36f36dfeed21b823b8b1c456649cf45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205021647007726-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T16%3A50%3A14Z&sr=b&sp=r&sig=v0K2DpxYXEQBuYirwJZYV7NxrouWuc0Va9iKhxmpR6k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 17:46 UTC, opbld31 commented
Docs Build status updates of commit _[0dc1152](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0dc11528f99cde7a333cb862f514792e3f75a20e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205061742213175-16154%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T17%3A46%3A00Z&sr=b&sp=r&sig=sCdbgH%2Bgy2%2BQOp3NIeSgvXKUkcXMYfB7Gn61LL8XmKc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 19:37 UTC, isvargasmsft approved these changes

2022-05-09 19:37 UTC, isvargasmsft commented
Hi @Lauragra, 

This one is ready for final review. 

Thanks!

2022-05-12 21:58 UTC, opbld30 commented
Docs Build status updates of commit _[5dcbdcb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dcbdcb1168e325ae250cad920c5aed0a59c0141)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f9509164)

<a id="f9509164"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205122157483036-16154/BuildReport?accessString=61214b8f7aa40ffd8d5c48d81834c41df2d9a39ca4befb4cf7832f7fe6ec80d8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 22:01 UTC, opbld32 commented
Docs Build status updates of commit _[4b15115](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b151158144dd21d17d80f1a1270657637e027e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c2e7578d)

<a id="c2e7578d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205122200330132-16154/BuildReport?accessString=0a3dc1d8a03bf087c7458f62fbc524f1ba3a1d43874ee65026b0be5e808094bd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 22:04 UTC, opbld30 commented
Docs Build status updates of commit _[b8ede35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8ede356c25ce155a1783f77e9f38b75bb197b38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205122202124373-16154/BuildReport?accessString=4860ea00dd4f2e6209e7da585d22aa44683cb5801cf864dcbb770da42b87729d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 15:21 UTC, mecampos commented
I added the Do not merge label again, because I removed it by mistake, I am not working on this PR.

2022-08-02 04:44 UTC, opbld34 commented
Docs Build status updates of commit _[c6934ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6934efdc596a97010e89a1a155284c87e23755b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020441451607-16154/BuildReport?accessString=23311881ab4a1b8f888f67521b05f74e22ac715667fc9bf572977fc0723d762f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:46 UTC, opbld31 commented
Docs Build status updates of commit _[834aa15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/834aa15dc10c6047fcf7a12ffefec19725b0f290)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020442443007-16154/BuildReport?accessString=1fe2606253c02dedff922e62d1121a9271c9b9fa019d1f633b34ac74702bea0c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 02:33 UTC, opbld33 commented
Docs Build status updates of commit _[97f0412](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97f0412d207e94aaa6cd5f1227c9b4c9abe7183f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030231236817-16154/BuildReport?accessString=c7b1fe0dce3db0cfcc05f3659c75d78754ba61cc0836a5837191ae4e6fd8f254).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 02:35 UTC, opbld34 commented
Docs Build status updates of commit _[ee86107](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee8610710408b7b79fa46f0780c3e29e96dbeae2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030233449959-16154/BuildReport?accessString=05d2355a0eac5c5f228fb9f58dd987171fcbe61690a1fdf979d0b9436e10ced3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 02:38 UTC, opbld31 commented
Docs Build status updates of commit _[60511ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60511aca66e50745fff6946c4fa4d8e743d1c40f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030235094715-16154/BuildReport?accessString=23f2f379d0bd275535df235886c3db2078764c3b0470433409d63f9174b455ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 02:40 UTC, opbld31 commented
Docs Build status updates of commit _[96c6f8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96c6f8e292db1f5edd61ece85d8b53bbb4bcaeac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-28a030f2)
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-28a030f2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml)
 - **Line 15110, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030237142715-16154/BuildReport?accessString=f3f6d27bcf87d85ee06f46dd366718d3747514438539a5417f47b3660cc7c2c1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in  [...]

2022-08-03 02:42 UTC, opbld31 commented
Docs Build status updates of commit _[631b983](https://github.com/microsoftgraph/microsoft-graph-docs/commits/631b98316056d064a9a02ebb6fa5005414816724)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-fe9b3791)
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-fe9b3791"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml)
 - **Line 15110, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030240452406-16154/BuildReport?accessString=6bbbfeb570d437c2c03ca10f076a3d3cbe5abde6b9a0300b63edf7f59c38e24d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in  [...]

2022-08-03 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[d56218f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d56218f216fb7c9e61e463e44efc3dd12020bfbf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-eddc544d)
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-eddc544d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml)
 - **Line 15110, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030241516317-16154/BuildReport?accessString=7a78d647213859fe73d0bc0cff21dd1376ac5a10f2c1c07ca9756113b7bbe188).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in  [...]

2022-08-03 02:49 UTC, opbld34 commented
Docs Build status updates of commit _[d12f624](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d12f6245aed13fe00236cf79f373b7c6d184d0e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a99c2706)
[api-reference/beta/api/externalconnectors-externalitem-addactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/api/externalconnectors-externalitem-addactivities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-addactivities?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-activitysettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-activitysettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-activitysettings?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivitybase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivitybase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivitybase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalactivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalactivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalactivityresult?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-externalitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-itemidresolver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-itemidresolver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-itemidresolver?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urlmatchinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urlmatchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urlmatchinfo?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-urltoitemresolverbase?view=graph-rest-beta&branch=pr-en-us-16154) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a99c2706"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sacampbe-msft-addActivitiesDocs/api-reference/beta/toc.yml)
 - **Line 15110, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030247053310-16154/BuildReport?accessString=c8238a1f2319305f78f811b143fa430ea613b9be1022125c3422e76c6f239c1e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in  [...]

2022-08-03 02:51 UTC, merged