Update enums-managedtenants.md
microsoftgraph/microsoft-graph-docs pull request #16175
Opened 2022-03-15 17:56 UTC by csgreen

Added two new enum values for granularDelegatedAdminPrivileges and delegatedAndGranularDelegetedAdminPrivileges

2022-03-15 17:59 UTC, opbld33 commented
Docs Build status updates of commit _[9827937](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9827937182ef8afaf299056fcd09c349272f3efa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-managedtenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/api-reference/beta/resources/enums-managedtenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-managedtenants?view=graph-rest-beta&branch=pr-en-us-16175) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203151756186809-16175%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T17%3A59%3A14Z&sr=b&sp=r&sig=FU5BiIpvkWOhEdY9xVm8LCFC72dNjbR69PRserP6V9w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-17 03:09 UTC, Lauragra commented
@csgreen , please add a changelog entry for this change as well. Thanks.

2022-03-18 04:20 UTC, opbld32 commented
Docs Build status updates of commit _[58c07c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58c07c7359d22d83b07a1b23eeb41cfc471a73aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-managedtenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/api-reference/beta/resources/enums-managedtenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-managedtenants?view=graph-rest-beta&branch=pr-en-us-16175) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203180418459310-16175%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T04%3A20%3A33Z&sr=b&sp=r&sig=jX7YKNop7xpKH4ghZoAZUN6znCo2%2Ba2%2BRqYJvPnahCY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 16:31 UTC, csgreen commented
@isvargasmsft is there something else I need to do on this PR? I'm not sure I followed the directions properly.

2022-04-05 20:11 UTC, isvargasmsft commented
@csgreen, you are good, please bear with us while we re-review your PR. Thank you for your work and patience.

2022-07-05 15:06 UTC, isvargasmsft commented on api-reference/beta/resources/enums-managedtenants.md
> +|delegatedAndGranularDelegetedAdminPrivileges|
Hi @csgreen, please add these new members to the description of the properties that have this enum as type.

2022-07-05 15:07 UTC, isvargasmsft requested changes
Hello @csgreen, 

My sincere apologies for the delays in getting back to you. 

Would you be so kind to add these new enums to the description of the property that uses it? 

Thank you!

2022-07-12 15:55 UTC, isvargasmsft commented on api-reference/beta/resources/enums-managedtenants.md
> +|delegatedAndGranularDelegetedAdminPrivileges|
@csgreen, I identified these 2 resources with properties using this enum:
https://docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantstatusinformation?view=graph-rest-beta

https://docs.microsoft.com/en-us/graph/api/resources/managedtenants-roleassignment?view=graph-rest-beta

2022-07-12 15:56 UTC, isvargasmsft requested changes
Please add the new members to the properties table in these 2 topics:
https://docs.microsoft.com/en-us/graph/api/resources/managedtenants-tenantstatusinformation?view=graph-rest-beta

https://docs.microsoft.com/en-us/graph/api/resources/managedtenants-roleassignment?view=graph-rest-beta

2022-08-22 20:00 UTC, isvargasmsft commented
@csgreen gently pinging.

2022-10-26 03:45 UTC, opbld34 commented
Learn Build status updates of commit _[7e9519d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e9519daf4e83b01765897077aacb28f4cf7f653)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210260343020095-16175/BuildReport?accessString=8ad35d402af80641b0a3cdca6c636b8f80587c2b5b193d1bab4ba7ffe0de9ad5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 04:11 UTC, opbld34 commented
Learn Build status updates of commit _[78faef5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78faef566cf198e562522f913e4d3f2c3af52427)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-tenantstatusinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/api-reference/beta/resources/managedtenants-tenantstatusinformation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/managedtenants-tenantstatusinformation?view=graph-rest-beta&branch=pr-en-us-16175) (graph-rest-beta) | [Details](#user-content-ec0f56b32d2505866304fdfd7b49861d-be02b77a)
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="ec0f56b32d2505866304fdfd7b49861d-be02b77a"></a>
### [api-reference/beta/resources/managedtenants-tenantstatusinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/api-reference/beta/resources/managedtenants-tenantstatusinformation.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'microsoft-365-lighthouse'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210260409237265-16175/BuildReport?accessString=75c57246107fdef192c7cc2e962a240ffb36ac01161f619b1fe902c4f5589155).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 04:18 UTC, idwilliams commented
@isvargasmsft the review feedback should be addressed. Let @csgreen and myself know if there are any other changes that are needed.

2022-10-26 21:35 UTC, isvargasmsft approved these changes

2022-10-26 21:36 UTC, isvargasmsft commented
@idwilliams @csgreen thank you for the updates. Approved. Please add the label **ready to merge** when you are ready to publish.

2022-10-28 00:59 UTC, opbld34 commented
Learn Build status updates of commit _[8b40ed1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b40ed1d437f06ad55e39d5f4fa2103fc1c5ac0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-tenantstatusinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/api-reference/beta/resources/managedtenants-tenantstatusinformation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/managedtenants-tenantstatusinformation?view=graph-rest-beta&branch=pr-en-us-16175) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-03-15-new-GDAP-enums/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210280056392176-16175/BuildReport?accessString=13e0eb6fedc4408e9f7aa93ad0191bbda1ba9c8372e605b477a48cdd5c19ebe6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 01:16 UTC, merged