GDAP Documentation (beta APIs)
microsoftgraph/microsoft-graph-docs pull request #16193
Opened 2022-03-16 20:35 UTC by adtangir

Schema PR: 5711767

2022-03-16 20:37 UTC, opbld32 commented
Docs Build status updates of commit _[d0faca1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0faca164f85bcc19bbba62c6745e2683fdadfd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/g [...]

2022-03-16 21:54 UTC, opbld33 commented
Docs Build status updates of commit _[e1ff80e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1ff80e46996c4ed9b5770e78c3a8759b9976897)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshipcustomerparticipant?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-73ca510c58e4bfa178c9a1be4acd47eb-7c595841)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-referenc [...]

2022-03-16 22:15 UTC, opbld30 commented
Docs Build status updates of commit _[8430e67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8430e673d662b56655e55693693727122fb5057b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshipcustomerparticipant?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-73ca510c58e4bfa178c9a1be4acd47eb-6d4e3d91)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-referenc [...]

2022-03-16 22:29 UTC, ozhang22 reviewed
First stab of review comments.

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +description: "Deletes a delegatedAdminAccessAssignment object."
Description should also change deletes -> delete
```suggestion
description: "Delete a delegatedAdminAccessAssignment object."
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +description: "Read the properties and relationships of a delegatedAdminAccessAssignment object."
Remove "and relationships" in the description as well.

```suggestion
description: "Read the properties of a delegatedAdminAccessAssignment object."
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +    "@odata.context": "https://graph.microsoft.com/beta/tenantRelationships/$metadata#accessAssignments/$entity",
Something's odd with the spacing here

```suggestion
    "@odata.type": "#microsoft.graph.delegatedAdminAccessAssignment",
    "@odata.context": "https://graph.microsoft.com/beta/tenantRelationships/$metadata#accessAssignments/$entity",
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +  "@odata.context": "https://graph.microsoft.com/beta/tenantRelationships/$metadata#accessAssignments",
```suggestion
    "@odata.context": "https://graph.microsoft.com/beta/tenantRelationships/$metadata#accessAssignments",
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +      "versionStamp": "\"00002008-0000-0200-0000-622aad3b0000\"",
```suggestion
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
### Response

#### Example 1: Returns a 202 Accepted response

Returns a 202 Accepted response.

>**Note:** The response object shown here might be shortened for readability.
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +description: "Read the properties and relationships of a delegatedAdminCustomer object."
```suggestion
description: "Read the properties of a delegatedAdminCustomer object."
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-get.md
> +description: "Read the properties and relationships of a delegatedAdminRelationship object."
```suggestion
description: "Read the properties of a delegatedAdminRelationship object."
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-get.md
> +
GET by ID does not support query params.

```suggestion
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +  "lastModifiedDateTime": "2022-03-09T20:34:59.3282097Z",
```suggestion
  "lastModifiedDateTime": "2022-02-13T10:33:52.3182097Z",
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +  "lastModifiedDateTime": "2022-02-10T11:26:44.9941884Z"
```suggestion
  "lastModifiedDateTime": "2022-02-10T10:55:47.1180588Z"
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +
Missing location header

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +
Missing location header

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +Update the properties of a [delegatedAdminRelationship](../resources/delegatedadminrelationship.md) object.
```suggestion
Update the properties of a [delegatedAdminRelationship](../resources/delegatedadminrelationship.md) object. A relationship can only be updated if it's in the "created" status.
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +description: "Read the properties and relationships of a delegatedAdminRelationshipOperation object."
```suggestion
description: "Read the properties of a delegatedAdminRelationshipOperation object."
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +      "lastModifiedDateTime": "2022-02-10T06:14:55.5398865Z"
```suggestion
      "lastModifiedDateTime": "2022-02-01T06:15:01.4823412Z"
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationshiprequest-update.md
> +  "lastModifiedDateTime": "2022-02-10T11:26:44.9941884Z"
```suggestion
  "lastModifiedDateTime": "2022-02-10T10:55:47.1180588Z"
```

2022-03-16 22:29 UTC, ozhang22 commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +
Location header missing

2022-03-16 22:45 UTC, ozhang22 commented on api-reference/beta/resources/unifiedrole.md
> +author: "amharris1331"
I don't think this matters but

```suggestion
author: "adtangir"
```

2022-03-16 22:55 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md
> +Contains details of a customer participant in a delegated admin relationship. Inherits from [delegatedAdminRelationshipParticipant](delegatedAdminRelationshipParticipant.md).
Either add base class delegatedAdminRelationshipParticipant.md file or delete this line.

```suggestion
Contains details of a customer participant in a delegated admin relationship.
```

2022-03-16 23:09 UTC, opbld34 commented
Docs Build status updates of commit _[26eaf98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26eaf988ed37c10b7385ff0fd966e36b244f983a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminservicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-p [...]

2022-03-16 23:11 UTC, opbld34 commented
Docs Build status updates of commit _[c385088](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c385088e07905716d5a34d3a5a91fa51b2dd876f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminservicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-p [...]

2022-03-16 23:22 UTC, opbld34 commented
Docs Build status updates of commit _[835ac5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/835ac5cb2191f7d45cf36a6c14483da522f4aa52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminservicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-p [...]

2022-03-16 23:30 UTC, opbld31 commented
Docs Build status updates of commit _[03e5562](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03e55627cbc7211a7cb67cfe7e9e6f197f1b58e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminservicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-p [...]

2022-03-17 00:23 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +DELETE https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments/{delegatedAdminAccessAssignmentId}
The formatting of the request in this example seems to be different from that in some of the other files.

2022-03-17 00:25 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +This method supports the `$select`, `$filter`, `$top`, `$orderBy`, `$skip`, `$count`, and `$skipToken`  [OData query parameters](/graph/query-parameters) to help customize the response.
This doesn't seem right. It seems like you added the description for List here. For GetById, we should only be supporting $select and perhaps, $expand. Please check the API implementation.

2022-03-17 00:28 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|duration|Duration|The duration (ISO 8601) of the relationship. This is set by the partner and cannot be changed by the customer, and once the relationship is in the "approvalPending" status or beyon
The description needs to be fixed. Please change: "This is set by the partner and cannot be changed by the customer, and once the relationship is in the "approvalPending" status or beyond." to "This cannot be changed once the relationship is in the "approvalPending" status or beyond."

2022-03-17 00:28 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
Please change: "This is set by the partner and cannot be changed by the customer, and cannot be changed by the caller once the relationship is in the 'approvalPending' status or beyond." to "This cannot be changed once the relationship is in the "approvalPending" status or beyond."

2022-03-17 00:30 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|customer|[microsoft.graph.delegatedAdminRelationshipCustomerParticipant](../resources/delegatedadminrelationshipcustomerparticipant.md)|The information of the customer of the relationship. This is s
Please change: "can neither be changed by the customer nor by the partner once the relationship is in the "approvalPending" status or beyond." to "cannot be changed once the relationship is in the "approvalPending" status or beyond."

2022-03-17 00:31 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +
The Location header would be in the response. But good catch!

2022-03-17 05:22 UTC, deepakku-work requested changes

2022-03-17 17:08 UTC, adtangir commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +---
I am not clear on this suggestion. Did you mean "tenantrelationship-" prefix?

2022-03-17 17:29 UTC, adtangir commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +DELETE https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments/{delegatedAdminAccessAssignmentId}
@deepakku-work Is there a specific reference of the formatting issue? Not able to find any major differences.

2022-03-17 17:48 UTC, adtangir commented on api-reference/beta/api/delegatedadminaccessassignment-list.md
> +  "@odata.context": "https://graph.microsoft.com/beta/tenantRelationships/$metadata#accessAssignments",
@ozhang22 The spacing seems to be consistent with other examples. Any specific reason you added the extra spacing?

2022-03-17 18:30 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-delete.md
> +DELETE https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/{delegatedAdminRelationshipId}/accessAssignments/{delegatedAdminAccessAssignmentId}
Ignore this one. It seems like the formatting shows up differently when I click on the .md file as opposed to clicking on the "View" link on the main page.

2022-03-17 18:33 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +This method supports the `$select`, `$filter`, `$top`, `$orderBy`, `$skip`, `$count`, and `$skipToken`  [OData query parameters](/graph/query-parameters) to help customize the response.
We can use the same text (just confirm that we do support the $select query option)

2022-03-17 18:41 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +### Example 1: Returns a 200 response
Please remove example 1 entirely.

2022-03-17 18:45 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +If successful, this method returns a `202 Accepted` response code and an updated [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object in the response body, or a `20
```suggestion
If successful, this method returns a `202 Accepted` response code with a location URL to a long running operation in the response headers that can be monitored for completion. (Note: If the values specified in the call are identical to the values in the existing object, the API returns a `200 OK` response code with the original [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object in the response body.
```

2022-03-17 18:48 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +```
It might be worthwhile here to show a GET on the operation that returns a status of "running" followed by a GET that returns a status of "complete" after which a final GET on the original access assignment returns the updated object.

2022-03-17 18:52 UTC, deepakku-work commented on api-reference/beta/api/delegatedadmincustomer-get.md
> +This method supports the `$select`, `$filter`, `$top`, `$orderBy`, `$skip`, `$count`, and `$skipToken`  [OData query parameters](/graph/query-parameters) to help customize the response.
Fix

2022-03-17 18:59 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +If successful, this method returns a `201 Created` response code and a [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object in the response body.
Please also mention that "The Location header in the response points to the created [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object."

2022-03-17 19:00 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +## Response
I think it's worthwhile to add a Response headers section as well here (to mention the Location and RetryAfter headers). See if there are other APIs that do this.

2022-03-17 19:00 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +
Also RetryAfter header

2022-03-17 19:02 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +## Response
I think it's worthwhile to add a Response headers section here for the Location and RetryAfter headers.

2022-03-17 19:02 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +Location: https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/5e5594d3-6f82-458b-b567-77db4811f0cd-00000000-0000-0000-0000-000000001234/operations/d8dbb27b-7fe7-4523-a3df
Missing RetryAfter header.

2022-03-17 19:06 UTC, opbld31 commented
Docs Build status updates of commit _[e2dfb15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2dfb155015db7e89b47c8dbf0c9f9e8549699d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminservicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminservicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resour [...]

2022-03-17 19:07 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +{
Blank line between the headers and the body.

2022-03-17 19:08 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +{
Add a blank line above "{". Same in the other samples as well.

2022-03-17 19:11 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
These descriptions need to be changed. I thought I had made some recommendations yesterday.  Remove the "This is set by the partner and cannot be changed by the customer, and cannot be changed by the caller once the relationship is in the "approvalPending" status or beyond." sentence for all fields since the status is already called out at the top and since the API only apply to a partner, it's not needed to call this out for each field.

2022-03-17 19:11 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
Same apply to the others.

2022-03-17 19:13 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-update.md
> +    "displayName": "Contoso Inc"
Please remove the displayName here since we only populate the display name after the relationship has been approved.

2022-03-17 19:14 UTC, adtangir commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +### Example 1: Returns a 200 response
The API doctor has been erroring out on this as it was expecting a response and hence I included this back for time being

2022-03-17 19:15 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +  "data": "{\"id\":\"a97a9b4c-f43e-4c47-bbd6-50d8d3c88d94\",\"PartnerGdapRelationshipId\":\"5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836\",\"Customer\":{\"TenantId\":\"4f
Please fix this; it contains serialized fields that the partners are not supposed to see. I had made a mention of this in my previous review as well.

2022-03-17 19:17 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-list.md
> +      "data": "{\"id\":\"a97a9b4c-f43e-4c47-bbd6-50d8d3c88d94\",\"PartnerGdapRelationshipId\":\"fa803a2f-93b1-4b87-a7ff-a833b149ab01-8119890b-4c3f-465d-9840-599131d14d98\",\"Customer\":{\"TenantId\":
As in the GET method, please fix the data field with the value from the latest run.

2022-03-17 19:17 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-list.md
> +      "data": "{\"id\":\"a97a9b4c-f43e-4c47-bbd6-50d8d3c88d94\",\"PartnerGdapRelationshipId\":\"fa803a2f-93b1-4b87-a7ff-a833b149ab01-8119890b-4c3f-465d-9840-599131d14d98\",\"Customer\":{\"TenantId\":
Please fix data.

2022-03-17 19:18 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshiprequest-get.md
> +Read the properties and relationships of a [delegatedAdminRelationshipRequest](../resources/delegatedadminrelationshiprequest.md) object.
```suggestion
Read the properties of a [delegatedAdminRelationshipRequest](../resources/delegatedadminrelationshiprequest.md) object.
```

2022-03-17 19:19 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshiprequest-list.md
> +    {
It'll be nice if there's more than one item in this list here, preferably with a different action (like terminate) and a different status (like running).

2022-03-17 19:21 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
> +      "lastModifiedDateTime": "2021-09-29T16:57:20.2101088Z",
```suggestion
      "lastModifiedDateTime": "2021-10-29T16:57:20.2101088Z",
```

2022-03-17 19:22 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
> +      "lastModifiedDateTime": "2021-09-29T16:57:20.2101088Z",
In this case, the last modified date time should match the end date time.

2022-03-17 19:26 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +---
I'm confused about the pattern used for the file names. We just need to make them consistent. In some cases, the verb (get/list/post) are mentioned at the end and in some as a prefix. All I'm suggesting is making them consistent.

2022-03-17 20:08 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This is set by the partner and cannot be changed by the customer, and cannot be changed b
The display name of the relationship. This is primarily meant for ease of identification. Must be unique across all relationships of the partner. This is set by the partner (only when the relationship is in the "created" status) and cannot be changed by the customer.

2022-03-17 20:09 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|duration|Duration|The duration (ISO 8601) of the relationship. This is set by the partner and cannot be changed by the customer, and once the relationship is in the 'approvalPending' status or beyon
```suggestion
|duration|Duration|The duration (ISO 8601) of the relationship. Must be a value between P1D and P2Y inclusive. This is set by the partner (only when the relationship is in the "created" status) and cannot be changed by the customer.|
```

2022-03-17 20:12 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|customer|[delegatedAdminRelationshipCustomerParticipant](../resources/delegatedadminrelationshipcustomerparticipant.md)|The information of the customer of the relationship. This is set either by the
```suggestion
|customer|[delegatedAdminRelationshipCustomerParticipant](../resources/delegatedadminrelationshipcustomerparticipant.md)|The information of the customer of the relationship. This is set either by the partner at the time of relationship creation or by the system after customer approval of the relationship if the partner did not originally set it. This cannot be changed by the customer.|
```

2022-03-17 20:13 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|status|delegatedAdminRelationshipStatus|The status of the relationship. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`
```suggestion
|status|delegatedAdminRelationshipStatus|The status of the relationship. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`, `terminating`, `terminationRequested`. This is set by the system and cannot be set by the caller.|
```

2022-03-17 20:16 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminaccesscontainer.md
> +|accessContainerType|delegatedAdminAccessContainerType|The type of access container (e.g., security group) that will be assigned one or more roles approved for the associated relationship. The possib
```suggestion
|accessContainerType|delegatedAdminAccessContainerType|The type of access container (e.g., security group) that will be assigned one or more roles approved for the associated relationship. The possible values are: `securityGroup`.|
```

2022-03-17 20:17 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +|[Delete delegatedAdminAccessAssignment](../api/delegatedadminaccessassignment-delete.md)|None|Deletes a **delegatedAdminAccessAssignment** object.|
```suggestion
|[Delete delegatedAdminAccessAssignment](../api/delegatedadminaccessassignment-delete.md)|None|Delete a **delegatedAdminAccessAssignment** object.|
```

2022-03-17 20:18 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|customer|[microsoft.graph.delegatedAdminRelationshipCustomerParticipant](../resources/delegatedadminrelationshipcustomerparticipant.md)|The information of the customer of the relationship. This is s
```suggestion
|customer|[microsoft.graph.delegatedAdminRelationshipCustomerParticipant](../resources/delegatedadminrelationshipcustomerparticipant.md)|The information of the customer of the relationship.|
```

2022-03-17 20:19 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. This cannot be changed once the relationship is in the "approvalPending" status or beyond
```suggestion
|displayName|String|The display name of the relationship. This is primarily meant for ease of identification. Must be unique across *all* delegated admin relationships of the partner.|
```

2022-03-17 20:20 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|duration|Duration|The duration (ISO 8601) of the relationship. This cannot be changed once the relationship is in the "approvalPending" status or beyond. Must be a value between P1D and P2Y inclusiv
```suggestion
|duration|Duration|The duration (ISO 8601) of the relationship. Must be a value between P1D and P2Y inclusive.|
```

2022-03-17 20:20 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +Location: https://traf-pcsvcadmin-prod.trafficmanager.net/CustomerServiceAdminApi/Web/v1/granularAdminRelationships/5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836
```suggestion
Location: https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836
```

2022-03-17 20:23 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|id|String|The unique identifier of the relationship. This is set by the system and cannot be set by the caller.|
For the sentence "This is set by the system and cannot be set by the caller.", can you check how the others have mentioned it? I'm thinking just calling out "Read-only" should be good enough.

2022-03-17 20:24 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +Represents a delegated admin relationship between a partner and customer.
I think we need a little more content here to describe what a delegated admin relationship is.

2022-03-21 13:05 UTC, adtangir commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +## Response
Why would we want to mention about Retry-After header in a POST call

2022-03-21 13:39 UTC, opbld34 commented
Docs Build status updates of commit _[dd2432a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd2432a4f4927187e42d34a164e0bf7527ae6cbf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminaccessassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminaccessassignment?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-f2537d870ed9e24345d3210be0afcdad-2d552b6c)
[api-reference/beta/resources/delegatedadmincustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadmincustomer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadmincustomer?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-e4d3ca9519c6507f16ffffde4a752a04-2d552b6c)
[api-reference/beta/resources/delegatedadminrelationship.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationship.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationship?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-ff0b1f6f79edb9fd061e9b94e6756eb5-2d552b6c)
[api-reference/beta/resources/delegatedadminrelationshiprequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationshiprequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshiprequest?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-20c1e48a3d80641004d724bd0bf1b06e-2d552b6c)
[api-reference/beta/resources/delegatedadminservicemanagementdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminservicemanagementdetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminservicemanagementdetail?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-3cf27b87f2d2aabc9dadf401ffa9464a-2d552b6c)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) [...]

2022-03-21 19:45 UTC, opbld32 commented
Docs Build status updates of commit _[772c8cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/772c8cc75a0937b95d63f2a435e50a8e77bfef0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminservicemanagementdetail-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminservicemanagementdetail-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminservicemanagementdetail-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminaccessassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminaccessassignment?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessconta [...]

2022-03-28 12:18 UTC, opbld32 commented
Docs Build status updates of commit _[ce443aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce443aa00802cc847aa96ff0d9ba5cd6c9d25205)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-post?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminservicemanagementdetail-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminservicemanagementdetail-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminservicemanagementdetail-list?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminaccessassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminaccessassignment?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessconta [...]

2022-03-28 12:42 UTC, FaithOmbongi requested changes
Hi @adtangir 

**Bumped up from the [previous review feedback](https://github.com/microsoftgraph/microsoft-graph-docs/pull/15965#pullrequestreview-904213034):**
- Please document the **delegatedAdminRelationships** + **delegatedAdminCustomers** relationships in the **tenantRelationship** resource doc as per the schema.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/14026935/160334985-d18caf44-c6a1-41e3-bb7e-7164d0ae0400.png">

- Please add the **partner** property which is of delegatedAdminRelationshipParticipant complex type.
- Please document the serviceManagementDetails relationship in delegatedAdminCustomer resource.
- File name changes for POST and LIST operations because these files follow the pattern _parententityname-list/post-navigationpropertyname.md_ After changing the file names, also change the links in the Methods table of the respective resource pages. Samples.
   - delegatedadminrelationship-list.md =>tenantrelationship-list-delegatedadminrelationships.md
   - delegatedadminrelationship-post.md => tenantrelationship-post-delegatedadminrelationships.md
   - delegatedadminaccessassignment-list.md => delegatedadminrelationship-list-accessassignments.md.
   - delegatedadminaccessassignment-post.md => delegatedadminrelationship-post-accessassignments.md
   - delegatedadminrelationshiprequest-post.md => delegatedadminrelationship-post-requests.md
   - delegatedadmincustomer-list.md => tenantrelationship-list-delegatedadmincustomers.md
   - delegatedadminservicemanagementdetail-list.md => delegatedadmincustomer-list-servicemanagementdetails.md
   - delegatedadminrelationshipoperation-list.md => delegatedadminrelationship-list-operations.md
- Please indicate all optional and required request headers and response headers that a customer might encounter.
- All request URLs in the Examples section should have REAL IDs instead of placeholders like `{delegatedAdminRelationshipId}`.

**New**
- Mostly formatting fixes
- Corrections for example, the JSON representation shouldn't be confused with a real payload.
- **GLOBAL:** Please remove the **Authorization: Bearer {token}** header from all request objects. This header is inferred and we advise that client apps treat is as an opaque value.
- Note that for enumeration types, it's always important to document the unknownFutureValue member because it allows customers to know that the enum is evolvable so they can plan for future changes without their app breaking.
- I pushed a commit to reorg the TOC. Please check
- I've added suggestions to enhance the changelog descriptions and also added changelog entries for the 2 new relationships and the 2 new permissions.


**Major Q:**

The description of delegatedAdminRelationshipRequest is still not clear. How is it different from a delegatedAdminRelationship object?

2022-03-28 12:42 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +## DelegatedAdminRelationship permissions
```suggestion
## Delegated admin relationship permissions
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminAccessContainer](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminAccessContainer?view=graph-rest-beta) resource type.",
Suggestion to enhance the description
```suggestion
          "Description": "Added the [delegatedAdminAccessContainer](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminAccessContainer?view=graph-rest-beta) resource type. Use this resource to define the details of the security group in a Microsoft partner's tenant through which delegated access to the customer tenant will be assigned.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminAccessDetails](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminAccessDetails?view=graph-rest-beta) resource type.",
```suggestion
          "Description": "Added the [delegatedAdminAccessDetails](https://docs.microsoft.com/en-us/graph/api/resources/c?view=graph-rest-beta) resource type. Represents the administrative roles that a Microsoft partner has in a customer tenant through a delegated admin relationship.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationshipCustomerParticipant](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationshipCustomerParticipant?view=graph-rest-
```suggestion
          "Description": "Added the [delegatedAdminRelationshipCustomerParticipant](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationshipCustomerParticipant?view=graph-rest-beta) resource type. Represents identification details of a customer in a delegated admin relationship.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [unifiedRole](https://docs.microsoft.com/en-us/graph/api/resources/unifiedRole?view=graph-rest-beta) resource type.",
```suggestion
          "Description": "Added the [unifiedRole](https://docs.microsoft.com/en-us/graph/api/resources/unifiedRole?view=graph-rest-beta) resource type. Represents the directory roles that can be assigned to a Microsoft partner through a delegated admin relationship.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminAccessAssignment](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminAccessAssignment?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [delegatedAdminAccessAssignment](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminAccessAssignment?view=graph-rest-beta) resource and related methods. Represents an assignment of administrative roles to a Microsoft partner by a customer through a delegated admin relationship.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminCustomer](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminCustomer?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [delegatedAdminCustomer](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminCustomer?view=graph-rest-beta) resource. Represents an Azure AD tenant that is a customer of a Microsoft partner and has a delegated admin relationship with the Microsoft partner.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationship](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationship?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [delegatedAdminRelationship](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationship?view=graph-rest-beta) resource and related methods. Represents the details of the administrative privileges that a Microsoft partner has in a customer tenant.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationshipOperation](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationshipOperation?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [delegatedAdminRelationshipOperation](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationshipOperation?view=graph-rest-beta) resource and related methods.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationshipRequest](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationshipRequest?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [delegatedAdminRelationshipRequest](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationshipRequest?view=graph-rest-beta) resource and related methods.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminServiceManagementDetail](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminServiceManagementDetail?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [delegatedAdminServiceManagementDetail](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminServiceManagementDetail?view=graph-rest-beta) resource and related methods.",
```

2022-03-28 12:42 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +      ],
New changelog entries for the 2 new relationships in **tenantRelationship** and the 2 new permissions.
```suggestion
        },
        {
          "Id": "864c77db-f273-4a11-8104-8149f3f9566f",
          "ApiChange": "Relationship",
          "ChangedApiName": "delegatedAdminRelationships",
          "ChangeType": "Addition",
          "Description": "Added the [delegatedAdminRelationships](https://docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationships?view=graph-rest-beta) navigation property to the [tenantRelationship](https://docs.microsoft.com/en-us/graph/api/resources/tenantrelationship?view=graph-rest-beta) resource.",
          "Target": "tenantRelationship"
        },
        {
          "Id": "864c77db-f273-4a11-8104-8149f3f9566f",
          "ApiChange": "Relationship",
          "ChangedApiName": "delegatedAdminCustomer",
          "ChangeType": "Addition",
          "Description": "Added the [delegatedAdminCustomer](https://docs.microsoft.com/en-us/graph/api/resources/delegatedadmincustomer?view=graph-rest-beta) navigation property to the [tenantRelationship](https://docs.microsoft.com/en-us/graph/api/resources/tenantrelationship?view=graph-rest-beta) resource.",
          "Target": "tenantRelationship"
        },
        {
          "Id": "864c77db-f273-4a11-8104-8149f3f9566f",
          "ApiChange": "Permission",
          "ChangedApiName": "DelegatedAdminRelationship.Read.All",
          "ChangeType": "Addition",
          "Description": "Added the `DelegatedAdminRelationship.Read.All` delegated permission to read the details of delegated admin relationship between a Microsoft partner and a customer.",
          "Target": "delegatedAdminRelationship"
        },
        {
          "Id": "864c77db-f273-4a11-8104-8149f3f9566f",
          "ApiChange": "Permission",
          "ChangedApiName": "DelegatedAdminRelationship.ReadWrite.All",
          "ChangeType": "Addition",
          "Description": "Added the `DelegatedAdminRelationship.ReadWrite.All` delegated permission to manage the delegated admin relationship between a Microsoft partner and a customer.",
          "Target": "delegatedAdminRelationship"
        },
      ],
```

2022-03-28 20:02 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|endDateTime|DateTimeOffset|The date and time (ISO 8601) at which this relationship either terminated or expired, or in the case of an active relationship, the date and time at which it is *scheduled
We don't want to expose the partner participant in the contract. We'll remove it from the schema soon.

2022-03-28 20:04 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|operations|[delegatedAdminRelationshipOperation](../resources/delegatedadminrelationshipoperation.md) collection|The long running operations associated with the delegated admin relationship.|
@FaithOmbongi, we haven't implemented $expand at the moment (that's still in progress). I think it's best if we add this once the implementation is complete.

2022-03-28 20:06 UTC, deepakku-work commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationship](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationship?view=graph-rest-beta) resource",
@FaithOmbongi, these changelogs are automatically generated. I understand that you're adding some context to this description but isn't this extra description redundant with the resource's documentation?

2022-03-28 20:13 UTC, deepakku-work commented
> @FaithOmbongi - A delegatedAdminRelationshipRequest represents a request related to a delegatedAdminRelationship. Examples are locking a relationship for approval or terminating it. These are modeled as "actions" in the delegatedAdminRelationshipRequest. This resource was introduced to allow for a way for the partner to perform these actions on the delegatedAdminRelationship object instead of modifying its status (which is how it was originally modeled). This makes it possible for us to enforce the fact that only the system can change the status of the delegatedAdminRelationship object and not the partner (which is consistent with the pattern followed by the rest of the Graph API).

2022-03-28 20:18 UTC, deepakku-work commented on api-reference/beta/resources/unifiedrole.md
> +description: "The directory roles specified for access."
Amit wanted us to specify the link to the Graph GET /unifiedRoleDefinitions API: https://docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&tabs=http

2022-03-29 07:00 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationship.md
> +description: "Represents a delegated admin relationship between a partner and customer."
Hi @deepakku-work, this detailed information is excellent, but this is the wrong file to include it. Let us work to add it to an **Overview** article that will accompany this set of API docs. We'll not manage to get that done in this iteration, but we can follow up and see if we can get it ready and published by next week.

2022-03-29 07:02 UTC, FaithOmbongi commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationship](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationship?view=graph-rest-beta) resource",
Hi @deepakku-work, the goal is to provide a brief teaser/context about the change/addition for any customer who views or has subscribed to the changelog, without them having to deep dive into our docs.

2022-03-29 07:02 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|operations|[delegatedAdminRelationshipOperation](../resources/delegatedadminrelationshipoperation.md) collection|The long running operations associated with the delegated admin relationship.|
Noted. Saw it in the API.md file though.

2022-03-29 07:13 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|endDateTime|DateTimeOffset|The date and time (ISO 8601) at which this relationship either terminated or expired, or in the case of an active relationship, the date and time at which it is *scheduled
Noted. If the schema change will be live in the next few days and the **partner** property and associated **delegatedAdminRelationshipParticipant** complex type is being deleted (and not deprecated first), then we can exclude them from this PR.

2022-03-29 16:33 UTC, opbld34 commented
Docs Build status updates of commit _[9c45bf8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c45bf8ab13ae7f09d5e0aae0291474be3b1ab8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-146157c1)
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminaccessassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminaccessassignment?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-f2537d870ed9e24345d3210be0afcdad-146157c1)
[api-reference/beta/resources/delegatedadmincustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadmincustomer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadmincustomer?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-e4d3ca9519c6507f16ffffde4a752a04-146157c1)
[api-reference/beta/resources/delegatedadminrelationship.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationship.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationship?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-ff0b1f6f79edb9fd061e9b94e6756eb5-146157c1)
[api-reference/beta/resources/delegatedadminrelationshipoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationshipoperation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshipoperation?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-0c9d4717ebe1659d13c29759a90919cd-146157c1)
[api-reference/beta/resources/delegatedadminrelationshiprequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationshiprequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshiprequest?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-20c1e48a3d80641004d724bd0bf1b06e-146157c1)
[api-reference/beta/resources/delegatedadminservicemanagementdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminservicemanagementdetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminservicemanagementdetail?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-3cf27b87f2d2aabc9dadf401ffa9464a-146157c1)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-146157c1)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-9435ba52f311ba244f7739f5a7e493a0-146157c1)
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-cd683a6c9e0839f6c3dc06be76c84330-146157c1)
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-596f9d17d1aa111417bf20250cf90a0f-146157c1)
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-d5c8344b579d291a9a864efc1d3ce99b-146157c1)
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adt [...]

2022-03-29 17:42 UTC, ozhang22 commented on api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md
> +GET https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminCustomers/{delegatedAdminCustomerId}/serviceManagementDetails
Real customer ID here and in the example response

2022-03-29 17:42 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-delete.md
> +DELETE /tenantRelationships/delegatedAdminRelationships/{delegatedAdminRelationshipId}
Real ID in example request and response

2022-03-29 17:42 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
Max top is 300. I'm not sure about skip.

2022-03-29 17:42 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +  "name": "create_delegatedadminaccessassignment_from_"
Do you need \_from\_?

2022-03-29 17:42 UTC, ozhang22 commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +Location: https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/c45e5ffb-3de2-4938-a214-b7eed802db66-4be56058-bb48-4a8e-8282-6cf0e98e6c9d/requests/5a6666c9-7282-0a41-67aa-2
Relationship ID here does not match with ID passed in example request

2022-03-29 17:42 UTC, ozhang22 commented on api-reference/beta/toc.yml
> +              href: api/delegatedadminaccessassignment-list.md
Aren't the list MDs of the format tenantrelationship-list-___ ?

2022-03-29 17:44 UTC, opbld33 commented
Docs Build status updates of commit _[9163c92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9163c92ce1bcd5cf701a276496912bdf75705994)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-602ed55c)
[api-reference/beta/resources/delegatedadmincustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadmincustomer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadmincustomer?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-e4d3ca9519c6507f16ffffde4a752a04-602ed55c)
[api-reference/beta/resources/delegatedadminrelationshipoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/resources/delegatedadminrelationshipoperation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshipoperation?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-0c9d4717ebe1659d13c29759a90919cd-602ed55c)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-9435ba52f311ba244f7739f5a7e493a0-602ed55c)
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-cd683a6c9e0839f6c3dc06be76c84330-602ed55c)
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-596f9d17d1aa111417bf20250cf90a0f-602ed55c)
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-d5c8344b579d291a9a864efc1d3ce99b-602ed55c)
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.mi [...]

2022-03-29 18:09 UTC, opbld32 commented
Docs Build status updates of commit _[9d55473](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d554733b652bd0b8cd5f574d9a95f9e7130c746)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-c368a5fc)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-29 18:17 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +Returns a 202 response.
Delete - not required because the H3 Response section below has covered this description.
```suggestion
```

2022-03-29 18:19 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md
> +description: "Get a list of the [delegatedAdminServiceManagementDetail](../resources/delegatedAdminServiceManagementDetail.md) objects and their properties."
@adtangir Links don't "work" in the metadata. We can remove this from here.
```suggestion
description: "Get a list of the delegatedAdminServiceManagementDetail objects and their properties."
```

2022-03-29 18:19 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md
> +GET https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminCustomers/{delegatedAdminCustomerId}/serviceManagementDetails
+1

2022-03-29 18:20 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md
> +  "@odata.context": "https://graph.microsoft.com/beta/tenantRelationships/$metadata#delegatedAdminCustomers/{delegatedAdminCustomerId}/serviceManagementDetails",
Same comment as before.

2022-03-29 18:21 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-delete.md
> +DELETE /tenantRelationships/delegatedAdminRelationships/{delegatedAdminRelationshipId}
Not here but in the Examples section (Request URL and Response payload)

2022-03-29 18:21 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-delete.md
> +DELETE https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships/{delegatedAdminRelationshipId}
Real ID

2022-03-29 18:21 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +description: "Represents an assignment of administrative roles to a Microsoft partner security group."
```suggestion
description: "Represents an assignment of administrative roles to a Microsoft partner access container."
```

2022-03-29 18:23 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
Got the 500 from the API.md. Guess we'll need to fix both. @adtangir

2022-03-29 18:24 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
> +  "name": "create_delegatedadminaccessassignment_from_"
I think these were autogenerated. Not a problem anyway.

2022-03-29 18:26 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +This method supports the $select OData query parameter to retrieve specific user properties, including those that are not returned by default.
Bumping @adtangir

2022-03-29 18:28 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +description: "Represents an assignment of administrative roles to a Microsoft partner security group."
Minor fix @adtangir 
```suggestion
description: "Represents an assignment of administrative roles to a Microsoft partner's security group."
```

2022-03-29 18:30 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationship.md
> +Represents a delegated admin relationship between a partner and customer.
Bumped @adtangir

2022-03-29 18:32 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          displayName: Partner Center, CSP, VAR
Additional suggestion to align this with the search terms @adtangir 
```suggestion
        - name: Granular delegated admin relationships
          displayName: Partner Center, GDAP, CSP, VAR
```

2022-03-29 18:38 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +## Delegated admin relationship permissions
Minor change suggestion to align with the terminology everywhere else (including admin docs + the upcoming overview article).
```suggestion
## Granular delegated admin relationship permissions
```

2022-03-29 18:46 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationshiprequest.md
> +|id|String|The unique identifier of the relationship request. Read-only. Inherited from [entity](../resources/entity.md).|
Good for completeness because **id** isn't defined in the **delegatedAdminRelationshipRequest** resource as per the schema.

2022-03-29 18:47 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +|status|delegatedAdminRelationshipOperationStatus|The status of the operation. The possible values are: `notStarted`, `running`, `complete`, `failed`, `unknownFutureValue`. Read-only. Supports `$orde
Found it in the API.md. Might need to be fixed in both.

2022-03-29 18:47 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +description: "Represents an assignment of administrative roles to a Microsoft partner security group."
+1

2022-03-29 19:12 UTC, ozhang22 approved these changes

2022-03-29 19:12 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +|status|delegatedAdminRelationshipOperationStatus|The status of the operation. The possible values are: `notStarted`, `running`, `complete`, `failed`, `unknownFutureValue`. Read-only. Supports `$orde
Let's file a bug to get this fixed. Keep $orderby

2022-03-29 19:12 UTC, ozhang22 commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +|id|String|The unique identifier of the delegated admin long-running operation. Read-only.|
Entity

2022-03-29 19:25 UTC, opbld32 commented
Docs Build status updates of commit _[a2198f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2198f873e2813c5887e8d0d2735ea35c9b189f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-f1169eae)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-29 19:36 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
We recently removed the limit for skip completely. @adtangir, please remove "`$skip` supports up to 500 objects" comment entirely.

2022-03-29 19:38 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
The limit for $top was also increased to 300 to keep it consistent with server-side paging. Can you fix that as well?

2022-03-29 19:39 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +description: "Represents a delegated admin relationship between a partner and customer."
That works. Thanks.

2022-03-29 19:40 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|endDateTime|DateTimeOffset|The date and time (ISO 8601) at which this relationship either terminated or expired, or in the case of an active relationship, the date and time at which it is *scheduled
Yup, thanks.

2022-03-29 19:41 UTC, deepakku-work commented on changelog/Microsoft.Partner.CustomerSvcAdmin.json
> +          "Description": "Added the [delegatedAdminRelationship](https://docs.microsoft.com/en-us/graph/api/resources/delegatedAdminRelationship?view=graph-rest-beta) resource",
Sure, thanks.

2022-03-29 19:44 UTC, opbld33 commented
Docs Build status updates of commit _[b0c64d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0c64d086eb70f4efb7b56e00593498b46561186)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-b1d27562)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-29 19:45 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
`$top` supports up to 300 objects

2022-03-29 19:45 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
```suggestion
$top supports up to 300 objects.
```

2022-03-29 19:48 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|displayName|String|The display name of the relationship used for ease of identification. Must be unique across *all* delegated admin relationships of the partner.|
```suggestion
|displayName|String|The display name of the relationship used for ease of identification. Must be unique across *all* delegated admin relationships of the partner. Required.|
```

2022-03-29 19:48 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +|duration|Duration|The duration of the relationship in ISO 8601 format. Must be a value between `P1D` and `P2Y` inclusive.|
```suggestion
|duration|Duration|The duration of the relationship in ISO 8601 format. Must be a value between `P1D` and `P2Y` inclusive. Required.|
```

2022-03-29 19:50 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +The response contains a **Location** header which contains a URL to the long-running operation for the status of the delegated admin relationship request. Each **delegatedAdminRelationship** object c
```suggestion
The response contains a **Location** header which contains a URL to the created delegated admin relationship. Each **delegatedAdminRelationship** object contains an **@odata.etag** property as per RFC2616.
```

2022-03-29 19:51 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
> +  "status": "approvalPending",
```suggestion
  "status": "created",
```

2022-03-29 19:55 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
> +|Prefer|@odata.maxpagesize=n. Where **n** is the desired number of results per page. The maximum value is 300. Optional.|
I don't know if this actually works (I haven't personally tested this header). Please validate and remove if it's not supported.

2022-03-29 19:58 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-delete.md
> +|If-Match|If-match: {etag}. Last known ETag value for the **delegatedAdminRelationship** to be deleted. Retrieve the ETag value from a LIST or GET operation.Required.|
```suggestion
|If-Match|If-match: {etag}. Last known ETag value for the **delegatedAdminRelationship** to be deleted. Retrieve the ETag value from a LIST or GET operation. Required.|
```

2022-03-29 20:03 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +|action|delegatedAdminRelationshipRequestAction|The action to be performed on the delegated admin relationship. Required. The possible values are: `lockForApproval`, `approve`, `terminate`, `unknownF
```suggestion
|action|delegatedAdminRelationshipRequestAction|The action to be performed on the delegated admin relationship. Required. The possible values are: `lockForApproval`, `terminate`.|
```
Please note that "approve" is not something that the Partner would use and we're trying to remove that from the schema. "unknownFutureValue" should not be used by the partner.

2022-03-29 20:04 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-post-requests.md
> +
I see that you haven't made a mention of the Location header (unlike delegatedAdminRelationship Create)

2022-03-29 20:06 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-list-requests.md
> +|Prefer|@odata.maxpagesize=n. Where **n** is the desired number of results per page. The maximum value is 300. Optional.|
Please test this.

2022-03-29 20:08 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationship-list-operations.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
Please fix this based on my comments in the relationship API

2022-03-29 20:10 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +ms.prod: "directory-management"
If we're changing the TOC, wouldn't the ms.prod value change as well (to something like "customer-relationship-management")?

2022-03-29 20:14 UTC, FaithOmbongi approved these changes
Thank you @adtangir for your extensive work on this PR. 

Approved with suggestions - Please apply @deepakku-work comments where they apply. I see comments about removing $skip, changing limits for $top, and verifying the Prefer header. All sounds good.

After this, please let's work on the Overview article so we can have a brief about this API for customers.

2022-03-29 20:15 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md
> +`$skip` supports up to 500 objects while `$top` supports up to 20 objects.
Please fix this comment based on my recommendation in the List relationships API.

2022-03-29 20:15 UTC, deepakku-work commented on api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md
> +|Prefer|@odata.maxpagesize=n. Where **n** is the desired number of results per page. The maximum value is 300. Optional.|
Please test this.

2022-03-29 20:15 UTC, FaithOmbongi commented on api-reference/beta/api/delegatedadminrelationshipoperation-get.md
> +ms.prod: "directory-management"
@deepakku-work, yes it will. Once it's created. All dependencies might not be fully set up before this PR is ready to merge, but we can easily change this ms.prod value after the docs are merged.

2022-03-29 20:16 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminservicemanagementdetail.md
> +  "serviceId": "String",
```suggestion
```

2022-03-29 20:16 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminservicemanagementdetail.md
> +  "serviceId": "String",
Remove serviceId.

2022-03-29 20:22 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|status|delegatedAdminRelationshipStatus|The status of the relationship. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`
```suggestion
|status|delegatedAdminRelationshipStatus|The status of the relationship. Read Only. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`, `terminating`, `terminationRequested`. Supports `$orderBy`.|
```
Note that the status is *always* read-only. Also, I don't know if we need to mention "unknownFutureValue" here.

2022-03-29 20:23 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|endDateTime|DateTimeOffset|The date and time in ISO 8601 format and in UTC time when the **status** of relationship will either be `terminated` or `expired`. Calculated as `endDateTime = activatedDa
```suggestion
|endDateTime|DateTimeOffset|The date and time in ISO 8601 format and in UTC time when the **status** of relationship changes to either `terminated` or `expired`. Calculated as `endDateTime = activatedDateTime + duration`. Read-only.|
```

2022-03-29 20:25 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +The following is a JSON representation of the resource.
This needs fixing to remove actual values.

2022-03-29 20:26 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|requests|[delegatedAdminRelationshipRequest](../resources/delegatedadminrelationshiprequest.md) collection|The requests associated with the delegated admin relationship. Supports `$expand`|
```suggestion
|requests|[delegatedAdminRelationshipRequest](../resources/delegatedadminrelationshiprequest.md) collection|The requests associated with the delegated admin relationship.|
```
Support for $expand is yet to be added.

2022-03-29 20:28 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +Represents a long-running operation related to a delegated admin relationship. An example of a long-running operation can be an update to the [delegatedAdminRelationship](delegatedadminrelationship.m
```suggestion
Represents a long-running operation related to a delegated admin relationship. An example of a long-running operation can be an update to the [delegatedAdminAccessAssignment](delegatedadminaccessassignment.md) object.
```

2022-03-29 20:30 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +|createdDateTime|DateTimeOffset|The time in ISO 8601 format and in UTC time when the request was created. Read-only.|
```suggestion
|createdDateTime|DateTimeOffset|The time in ISO 8601 format and in UTC time when the long-running operation was created. Read-only.|
```

2022-03-29 20:30 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +|lastModifiedDateTime|DateTimeOffset|The time in ISO 8601 format and in UTC time when the request was last modified. Read-only.|
```suggestion
|lastModifiedDateTime|DateTimeOffset|The time in ISO 8601 format and in UTC time when the long-running operation was last modified. Read-only.|
```

2022-03-29 20:31 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|[Delete delegatedAdminRelationship](../api/delegatedadminrelationship-delete.md)|None|Deletes a **delegatedAdminRelationship** object.|
```suggestion
|[Delete delegatedAdminRelationship](../api/delegatedadminrelationship-delete.md)|None|Delete a **delegatedAdminRelationship** object.|
```

2022-03-29 20:33 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminaccessassignment.md
> +|status|delegatedAdminAccessAssignmentStatus|The status of the access assignment. The possible values are: `pending`, `active`, `deleting`, `deleted`, `error`, `unknownFutureValue`.|
```suggestion
|status|delegatedAdminAccessAssignmentStatus|The status of the access assignment. Read-only. The possible values are: `pending`, `active`, `deleting`, `deleted`, `error`, `unknownFutureValue`.|
```

2022-03-29 20:34 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationshipoperation.md
> +|status|delegatedAdminRelationshipOperationStatus|The status of the operation. The possible values are: `notStarted`, `running`, `complete`, `failed`, `unknownFutureValue`. Read-only. Supports `$orde
```suggestion
|status|delegatedAdminRelationshipOperationStatus|The status of the operation. Read-only. The possible values are: `notStarted`, `running`, `complete`, `failed`, `unknownFutureValue`. Supports `$orderBy`.|
```

2022-03-29 20:39 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-get.md
> +  "id": "84c586df-0943-416e-b95f-7289cb8d3bd5",
```suggestion
  "id": "da9d6cf90-083a-47dc-ace2-1da98be3f344",
```
"id" should match the value in the URL.

2022-03-29 20:41 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +|accessContainer|[delegatedAdminAccessContainer](../resources/delegatedadminaccesscontainer.md)|The access container through which members are assigned access. For example, a security group.|
```suggestion
```
Remove the accessContainer field here since it cannot be updated.

2022-03-29 20:42 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +|Location|The location of the resource object.|
```suggestion
|Location|The location of the long-running operation.|
```

2022-03-29 20:42 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +|Retry-After|The time after which a subsequent API call can be made.|
```suggestion
|Retry-After|The time after which a subsequent API call can be made to the Location URL to check the status of the long-running operation.|
```

2022-03-29 20:43 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +This method returns a `202 Accepted` response code with a URL to a long-running operation in the **Location** response header that can be monitored for completion. If the values specified in the call
```suggestion
This method typically returns a `202 Accepted` response code with a URL to a long-running operation in the **Location** response header that can be monitored for completion. If the values specified in the call are identical to the values in the existing object, the API returns a `200 OK` response code with the original [delegatedAdminAccessAssignment](../resources/delegatedadminaccessassignment.md) object in the response body.
```

2022-03-29 20:44 UTC, deepakku-work commented on api-reference/beta/api/delegatedadminaccessassignment-update.md
> +The following is an example response that returns a `202 Accepted` response code and a **Retry-After** header.
```suggestion
The following is an example response that returns a `202 Accepted` response code along with **Location** and **Retry-After** headers.
```

2022-03-29 21:28 UTC, deepakku-work commented on api-reference/beta/resources/enums.md
> +|approve|
```suggestion
```

2022-03-29 21:37 UTC, deepakku-work approved these changes
I added a few more comments for issues that I found. Please take a look and address them.

2022-03-30 11:55 UTC, opbld33 commented
Docs Build status updates of commit _[7fe9e87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fe9e8751fb99deae7d01f8498f8037bfa9b8a60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-9b2704f5)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-30 12:53 UTC, FaithOmbongi reviewed
Hi @adtangir - Minor fixes.
1. Please remove mentions of `$skip` from the **Optional query parameters** section of LIST files.
2. I added notes for the other 2 changes required - adding the unknownFutureValue member and updating the permissions reference.

2022-03-30 12:53 UTC, FaithOmbongi commented on api-reference/beta/resources/delegatedadminrelationship.md
> +|status|delegatedAdminRelationshipStatus|The status of the relationship. Read Only. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `
`unknownFutureValue` may be unusable and not a real status, but we need it here to tell customers that delegatedAdminRelationshipStatus is an evolvable enum. That way you can add future members to this enum and customers won't have breaking changes - and they can handle those changes safely. Please see more [Handling future members in evolvable enumerations](https://docs.microsoft.com/en-us/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations).
```suggestion
|status|delegatedAdminRelationshipStatus|The status of the relationship. Read Only. The possible values are: `activating`, `active`, `approvalPending`, `approved`, `created`, `expired`, `expiring`, `terminated`, `terminating`, `terminationRequested`, `unknownFutureValue`. Supports `$orderBy`.|
```

2022-03-30 12:53 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +| _DelegatedAdminRelationship.ReadWrite.All_ | Read and write partner customer service administration data | Allows the app to read and write the delegated administration related information, on beha
Please realign these with the official permission string. If these need to be updated, the permission string should be updated first.

For delegated permissions

<img width="858" alt="image" src="https://user-images.githubusercontent.com/14026935/160838318-2bd99810-0220-4d36-b57d-43c501718c65.png">


For application permissions - Add the missing application permissions section before the ending ---
<img width="844" alt="image" src="https://user-images.githubusercontent.com/14026935/160838048-b712c3e8-b583-47a7-84fb-c36de798eb9e.png">

2022-03-30 14:35 UTC, opbld30 commented
Docs Build status updates of commit _[3a94ae5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a94ae54ba636d9f7d57396dca800e29fd865ff4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-6c151fe9)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-30 18:36 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationshiprequest.md
> +|action|delegatedAdminRelationshipRequestAction|The action to be performed on the delegated admin relationship.|
Mention possible values here (including "unknownFutureValue")

2022-03-30 18:38 UTC, deepakku-work commented on api-reference/beta/resources/delegatedadminrelationshiprequest.md
> +|action|delegatedAdminRelationshipRequestAction|The action to be performed on the delegated admin relationship.|
```suggestion
|action|delegatedAdminRelationshipRequestAction|The action to be performed on the delegated admin relationship. The possible values are: `lockForApproval`, `terminate`, `unknownFutureValue`|
```
Mention possible values here (including "unknownFutureValue")

2022-03-30 18:42 UTC, deepakku-work commented on api-reference/beta/resources/tenantrelationship.md
> +|delegatedAdminCustomers|[delegatedAdminCustomer](../resources/delegatedadmincustomer.md) collection|The customer who has a delegated admin relationship with a Microsoft partner.|
The customers who have a delegated admin relationship with a Microsoft partner.

2022-03-30 18:42 UTC, deepakku-work commented on api-reference/beta/resources/tenantrelationship.md
> +|delegatedAdminCustomers|[delegatedAdminCustomer](../resources/delegatedadmincustomer.md) collection|The customer who has a delegated admin relationship with a Microsoft partner.|
```suggestion
|delegatedAdminCustomers|[delegatedAdminCustomer](../resources/delegatedadmincustomer.md) collection|The customers who have a delegated admin relationship with a Microsoft partner.|
```

2022-03-30 18:43 UTC, deepakku-work commented on api-reference/beta/resources/tenantrelationship.md
> +|delegatedAdminRelationships|[delegatedAdminRelationship](../resources/delegatedadminrelationship.md) collection|The details of the delegated administrative privileges that a Microsoft partner has in
```suggestion
|delegatedAdminRelationships|[delegatedAdminRelationship](../resources/delegatedadminrelationship.md) collection|The list of delegated administrative relationships that a Microsoft partner with multiple customers.|
```

2022-03-31 03:07 UTC, opbld33 commented
Docs Build status updates of commit _[32fb8e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32fb8e8e113961acacc5d1517c48eee94aac4a34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-9e2b59f5)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-31 03:10 UTC, opbld32 commented
Docs Build status updates of commit _[32fb8e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32fb8e8e113961acacc5d1517c48eee94aac4a34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-e4aff06e)
[api-reference/beta/api/delegatedadminaccessassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminaccessassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminaccessassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminaccessassignment-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadmincustomer-list-servicemanagementdetails?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-delete?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-list-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-list-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-accessassignments?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-post-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-post-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-post-requests?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationship-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationship-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-update?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshipoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshipoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshipoperation-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/delegatedadminrelationshiprequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/delegatedadminrelationshiprequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationshiprequest-get?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadmincustomers?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adtangir-gdap-documentation/api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-beta&branch=pr-en-us-16193) (graph-rest-beta) |
[api-reference/beta/resources/delegatedadminaccessassignment.md](https://github.com/microsoftgraph/micros [...]

2022-03-31 03:13 UTC, merged