Grant Microsoft Graph permissions programmatically
microsoftgraph/microsoft-graph-docs pull request #16217
Opened 2022-03-18 11:10 UTC by FaithOmbongi

You can grant API permissions through Microsoft Graph instead of using the consent experience on the Azure portal. These articles guide the customer how to achieve this for delegated vs app-only scenarios.

2022-03-18 11:12 UTC, opbld34 commented
Docs Build status updates of commit _[8f30faf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f30fafdede314f0ed0cc9c5cf441d5c0535178a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-1c8253aa)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-1c8253aa)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-1c8253aa"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-1c8253aa"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203181110283956-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T11%3A12%3A33Z&sr=b&sp=r&sig=k0vDz7xPpfYiXtuIwT33%2FkGWlRt8gBSGFsNDnt9dhGQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 11:23 UTC, opbld31 commented
Docs Build status updates of commit _[5819f24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5819f2431dcb0aa6d1b080e23498f82b884178ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-de35388b)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-de35388b)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-de35388b"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-de35388b"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203181120574383-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T11%3A23%3A00Z&sr=b&sp=r&sig=xvRb3XhKQgcrHgilkFSvVlezSTBzw3IpcKj8jkE7v%2BU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 11:33 UTC, opbld32 commented
Docs Build status updates of commit _[ed10986](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed109862fd278eca76111e06c7e9dcea1fb706cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-8fbc7a7e)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-8fbc7a7e)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-8fbc7a7e"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-8fbc7a7e"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203181130313467-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T11%3A33%3A19Z&sr=b&sp=r&sig=LDEaSY4cGVvWRU7aSp%2BbhPC1DbQkGSO5vBv%2Ffgl54Tc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 11:51 UTC, opbld32 commented
Docs Build status updates of commit _[141bad8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/141bad87d6c2770b2c4792fb5aa0679387ec7554)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-02ba0f03)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-02ba0f03)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-02ba0f03"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-02ba0f03"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203181149553270-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T11%3A51%3A52Z&sr=b&sp=r&sig=JCreplwJChUFaH33bXXf%2B0qAQ3l7Jwwg9L05u2vgcIE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-21 10:06 UTC, omondiatieno commented on concepts/permissions-app-grant-msgraph.md
> +POST https://graph.microsoft.com/v1.0/servicePrincipals/943603e4-e787-4fe9-93d1-e30f749aae39/appRoleAssignedTo
Should we not show how to retrieve the resource ID and the app role ID before this step?

2022-03-21 10:44 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +To complete this tutorial, you need the following resources and privileges:
Good catch. Definitely a how-to.

2022-03-21 11:14 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +POST https://graph.microsoft.com/v1.0/servicePrincipals/943603e4-e787-4fe9-93d1-e30f749aae39/appRoleAssignedTo
I'm thinking that this will end up extending the scope of this article to a tutorial that first creates an app that exposes an API, then we use that app's object ID as the resourceID and use the ID of the appRole it has exposed. So the flow of the tutorial might be:
1. Create an app 1
2. Create a SP1 for app 1
3. Create appRoles for SP1
4. Expose API for SP1
5. Create an app 2 <--- we are here

In the scope of this article, I'm using Microsoft Graph and the appRoles it exposes.

2022-03-21 11:42 UTC, msewaweru commented on concepts/permissions-app-grant-msgraph.md
> +
I think that we need an introduction of what the customer will accomplish in this how-to.

2022-03-21 11:43 UTC, msewaweru commented on concepts/permissions-delegated-grant-msgraph.md
> +
Proposing to add an introduction.

2022-03-21 11:46 UTC, msewaweru commented on concepts/permissions-delegated-grant-msgraph.md
> +}
Neither the ClientId nor the ResourceId matches the service principal you created in step 2. I think we should use the created service principal to represent the resourceId.

2022-03-21 12:04 UTC, opbld31 commented
Docs Build status updates of commit _[723e0a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/723e0a21497286c573e425e4977a0b39e0be1f1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-6695c8ea)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-6695c8ea)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-6695c8ea"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-6695c8ea"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use the Microsoft Graph API to grant Microsoft Graph API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203211201172947-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T12%3A04%3A24Z&sr=b&sp=r&sig=CE2utDrO3ArGoQqleusjpC8jMDxerbRV9ZzgsRpBN0k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-21 12:30 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +
Added.

2022-03-21 12:30 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +
Added

2022-03-21 12:31 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +}
Mixed up outputs. Fixed.

2022-03-21 12:32 UTC, opbld31 commented
Docs Build status updates of commit _[634c26d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/634c26d87f1dd6e4fa21c2e420e1e9720312e32f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-ba2233bf)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-ba2233bf)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-ba2233bf"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-ba2233bf"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203211230028838-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T12%3A32%3A00Z&sr=b&sp=r&sig=ckKMKHlH%2FAEyM4t94iev5Vn1EoW7M%2BrUqp6UEOVF9kU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 17:58 UTC, opbld30 commented
Docs Build status updates of commit _[2d555db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d555db17ab9a9cb8f423ecc7694a860319b09fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-b18d8805)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-b18d8805)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-b18d8805"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-b18d8805"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203231756185653-16217%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T17%3A58%3A24Z&sr=b&sp=r&sig=e7tMEvk%2B%2F%2Bw8yrYRCe77n%2Bgn4b%2BSonCjf5DYBzI4FVA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 19:36 UTC, Jackson-Woods commented on concepts/permissions-app-grant-msgraph.md
> +  "displayName": "My application"
@FaithOmbongi should we give this a "scarier" or more informative name? "Permissions management client" or something?

2022-04-07 19:41 UTC, Jackson-Woods commented on concepts/permissions-app-grant-msgraph.md
> +In this step, we'll assign an app role that's exposed by Microsoft Graph. In the following example, the object ID of Microsoft Graph is `943603e4-e787-4fe9-93d1-e30f749aae3`. The app role is `Adminis
I'd add a small clarification "...the object ID of Microsoft Graph in this tenant is `943...`"

2022-04-07 19:43 UTC, Jackson-Woods commented on concepts/permissions-app-grant-msgraph.md
> +You've granted an app role to a service principal. This method of granting permissions using Microsoft Graph bypasses the consent workflow and should be used with caution.
Replace "workflow" to say "...bypasses interactive consent and should be used with caution."

2022-04-07 20:02 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +
Should have a warning similar to the one for app only. 

"> [!CAUTION]
> The `DelegatedPermissionGrant.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app or user in your organization. Access to this service must be properly secured and should be limited to as few users as possible."

2022-04-07 22:34 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +In this step, we'll grant the service principal a delegated permission (or scope) that's exposed by Microsoft Graph. In the following example, the object ID of Microsoft Graph is `943603e4-e787-4fe9-
Same feedback as app-only page, I'd recommend "...the object ID of Microsoft Graph in this tenant is `9436...`"

2022-04-07 23:37 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +    "consentType": "AllPrincipals",
Would prefer if we could illustrate this with a user id and a grant on behalf of the specific user. Or show both options.

2022-04-07 23:39 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +## Step 5 [Optional]: Create an app role assignment for a user to the app
Not sure if this is the right doc for this. AppRoleAssignments are sort of the opposite of delegated scopes. They're direct grants of access to the app for that user, not a permission for the app to act on the user's behalf.

2022-04-07 23:39 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +You've granted delegated permissions (or scopes) to a service principal. This method of granting permissions using Microsoft Graph bypasses the consent workflow and should be used with caution.
Same as other page, recommend replacing "consent workflow" with "interactive consent"

2022-04-07 23:41 UTC, Jackson-Woods requested changes
Hey Faith - this looks great! We should resolve the fundamental scenarios on the delegated page though. I think we should show:
- delegated grant on behalf of a specific user
- delegated grant on behalf of all principals
- remove or move the approleassignment example, which is a different kind of permission grant

Let me know what you think.

2022-04-25 13:50 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +In this step, we'll grant the service principal a delegated permission (or scope) that's exposed by Microsoft Graph. In the following example, the object ID of Microsoft Graph is `943603e4-e787-4fe9-
Done for both.

2022-04-25 14:25 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +    "consentType": "AllPrincipals",
Updated to show both options. I've changed the main example to be a grant for a specific user; then showed the way to grant for all users.

2022-04-25 17:17 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +## Step 5 [Optional]: Create an app role assignment for a user to the app
Hmm, bumping this internally for discussion.

2022-04-25 17:26 UTC, opbld30 commented
Docs Build status updates of commit _[e1ddc7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1ddc7cfd5407d0342d5bb8cc97fedea0f6e9d4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-bee40b1e)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-bee40b1e)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-bee40b1e"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-bee40b1e"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251723327856-16217%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T17%3A26%3A51Z&sr=b&sp=r&sig=K0BBJ4y%2FQsH55wgsW%2F9XjF7v0pX9f1DHVxHuGtCRKaY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 19:57 UTC, opbld34 commented
Docs Build status updates of commit _[7cc1ce2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cc1ce21c24251656f5988a28ed868fe07c4938e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-319ac63c)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-319ac63c)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-319ac63c"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-319ac63c"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091955404758-16217%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T19%3A57%3A40Z&sr=b&sp=r&sig=m6GjRctv1QNNlIOartQCnId5OtWdrZ7lGGcIaB6o2f8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 12:00 UTC, opbld32 commented
Docs Build status updates of commit _[bdf5d18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdf5d18a1f5f5897da7623a002869078b3026771)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-eb4e2db9)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-eb4e2db9)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-eb4e2db9"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-eb4e2db9"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121157570796-16217/BuildReport?accessString=81775574e3f4e981aea1ddc98274d1adb7f76c67afd94429eea53360b2667056).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 07:55 UTC, Jackson-Woods approved these changes
LGTM!

2022-05-14 03:22 UTC, Lauragra commented on concepts/permissions-app-grant-msgraph.md
> +# How-To: Grant API application permissions programmatically
Do we need to include "How to" in the title here, or can the title simply begin with a verb? We don't explicitly have "how to" as a content type in our content set, just conceptual/task-based articles. Also, it would be helpful to add "Microsoft Graph" to the H1 title.

2022-05-14 03:24 UTC, Lauragra commented on concepts/permissions-app-grant-msgraph.md
> +Use the following instructions to grant application permissions that are exposed by an API to an app. Application permissions allow an app to call an API with its own identity, and may sometimes be c
For the second sentence, I suggest revising as: 
Application permissions, also called app roles, app-only permissions, or direct access permissions, allow an app to call an API with its own identity.

2022-05-14 03:29 UTC, Lauragra commented on concepts/permissions-app-grant-msgraph.md
> +1. A working Azure AD tenant.
These numbered steps aren't parallel. I suggest revising as follows:
To complete these instructions, you need a working Azure AD tenant, and you must complete the following steps:

Then just have the three numbered steps.

2022-05-14 03:30 UTC, Lauragra commented on concepts/permissions-app-grant-msgraph.md
> +4. Get the object ID of a resource service principal that exposes app roles, and the ID of the app role to grant. In this guide, we'll use the Microsoft Graph resource service principal.
For the second sentence, I suggest avoiding using the first person plural; you can revise as:
This article uses the Microsoft Graph resource service principal.

2022-05-14 03:31 UTC, Lauragra commented on concepts/permissions-app-grant-msgraph.md
> +In this step, we'll assign our app an app role that's exposed by Microsoft Graph, thereby creating an app role assignment. In the following example, the object ID of Microsoft Graph in this tenant is
In this section, please avoid using first person plural; you can change "we'll" and "our" to "you'll" ad "your".

2022-05-14 03:31 UTC, Lauragra commented on concepts/permissions-app-grant-msgraph.md
> +You've granted an app role to a service principal. This method of granting permissions using Microsoft Graph bypasses [interactive consent](/azure/active-directory/develop/application-consent-experie
Please add the missing period here.

2022-05-14 03:33 UTC, Lauragra commented on concepts/permissions-delegated-grant-msgraph.md
> +# How-To: Grant delegated permissions programmatically
Please reference my comments on the previous topic and apply similar updates here as well.

2022-05-14 03:33 UTC, Lauragra commented on concepts/permissions-delegated-grant-msgraph.md
> +Alternatively, you can choose to grant consent on behalf of all users in the tenant. The request body is similar to the above except with the following changes:
Please delete "to this above".

2022-05-16 08:49 UTC, psignoret requested changes

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +# How-To: Grant API application permissions programmatically
Also, I'd prefer leading with "app roles" as the thing being granted, leaving "application permissions" as one of the alternate names. @Jackson-Woods, is this aligned with the direction the terminology conversation is going in?

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +Use the following instructions to grant application permissions that are exposed by an API to an app. Application permissions allow an app to call an API with its own identity, and may sometimes be c
As mentioned earlier, I propose we lead with the "app role" term, which avoids perpetuating the idea that apps roles assigned to users/groups are any different from app roles assigned to an app's service principal. (Pending @Jackson-Woods's thoughts on this.)

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +1. A working Azure AD tenant.
I would add the authorization needed to do all of the below as pre-requisites. It's important we include the authorization needed by both the user and the app in the app+user (delegated) case, and the authorization needed by the app in the app-only case. (Not to be confused with the fact that what we're doing here happens to be granting another app roles to an app.)

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +4. Get the object ID of a resource service principal that exposes app roles, and the ID of the app role to grant. In this guide, we'll use the Microsoft Graph resource service principal.
I suggest this be part of the how-to, rather than a pre-requisite, as this is where many people get confused.

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +> The `AppRoleAssignment.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app, user, or group in your organization. Access to this service
It's unclear what we're trying to warn about here. Are we warning about "AppRoleAssignment.ReadWrite.All" being the app role that will be granted later on? If so, then this warning should be expanded to warn about all super privileged permissions (e.g. RoleManagement.ReadWrite.Directory, etc.), and I suggest moving this to later, at the step where we actually grant the app role. Or are we warning about the fact that in order to grant app roles, the app needs to the "AppRoleAssignment.ReadWrite.All" permission? If that's the case, then the actions to take don't really align with the pre-req step of "sign in to Graph Explorer or Postman", since the former is a Microsoft-owned app, and the latter is a third-party installed client app (and has no service to secure).

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +## Step 1: Register an application with Azure AD
I don't think the "how to grant app roles" article should include as necessary steps the steps to register an application and create its service principal. The pre-requisite is to have a service principal for the application to which the app role is being assigned. This service principal _could_ be the result of creating an app registration in this same tenant (and we could link off to a separate article describing that process), but it could also be the service principal for a third-party multi-tenant application, or the service principal for a managed identity.

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +In this step, we'll assign our app an app role that's exposed by Microsoft Graph, thereby creating an app role assignment. In the following example, the object ID of Microsoft Graph in this tenant is
> In the following example, the object ID of Microsoft Graph in this tenant is `943603e4-e787-4fe9-93d1-e30f749aae3`. The app role `User.Read.All` is identified by ID `df021288-bdef-4463-88db-98f22de89214`.

How did we come up with these values? I think _that_ is what we should be illustrating above (i.e. how to get a resource service principal by app ID or URI, and how the appRoles collection includes each app role's ID).

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +To confirm all apps with a role assignment to the app, run the following request.
This will return all objects which have been granted a direct app role assignment for this resource app. This could include users, groups, or service principals.

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +You've granted an app role to a service principal. This method of granting permissions using Microsoft Graph bypasses [interactive consent](/azure/active-directory/develop/application-consent-experie
Please do not use the term "bypasses". This is an _alternative_ to the interactive consent experience, yes, but using the term "bypasses" has a negative connotation that we're working around an important or necessary experience.

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +description: "Learn how to use Microsoft Graph to grant API permissions to an app."
I would suggest we include in the same article how to do this with Microsoft Graph PowerShell as well (i.e. with tabs).

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +author: "FaithOmbongi"
Please set me as additional author (if possible) or as reviewer. (I.e. so that I get notified automatically for issues and PRs to these docs.)

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-delegated-grant-msgraph.md
> +GET https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$filter=clientId eq 'ef969797-201d-4f6b-960c-e9ed5f31dab5'
The response could include hundreds or thousands of grants (e.g. one per user). I suggest further narrowing this down by including `consentType` and `principalId` in the filter.

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-delegated-grant-msgraph.md
> +## Step 4 [Optional]: Grant more delegated permissions to the service principal
The same process is followed to remove some (but not all) granted delegated permissions. Can this be updated to be more general and cover both granting more and fewer (i.e. revoking) permissions (e.g. "change which permissions are granted")?

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-delegated-grant-msgraph.md
> +    "scope": "User.Read.All"
I think the example should illustrate granting _two_ delegated permissions (e.g. `"scope": "User.Read User.ReadBasic.All"), to be clear that's how you do it. Otherwise, a reader might expect that to grant additional permissions, they should repeat the same process and create a new delegated permission grant (which won't work).

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-delegated-grant-msgraph.md
> +# How-To: Grant delegated permissions programmatically
Same with my comments, please.

2022-05-16 08:49 UTC, psignoret commented on concepts/permissions-app-grant-msgraph.md
> +title: "How-To: Grant API application permissions programmatically"
If we publish "how to grant" articles, we also need to simultaneously publish "how to revoke". Alternatively, the same article could cover both ("how to grant and revoke...", or "how to manage...").

2022-05-16 18:08 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +description: "Learn how to use Microsoft Graph to grant API permissions to an app."
The code snippets _may_ be generated though not guaranteed - the SDK team is investigating why snippets aren't generated for conceptual articles.  Given the PowerShell properties are differently named, we can alternatively use [zone pivots](https://review.docs.microsoft.com/en-us/help/contribute/zone-pivots?branch=main) and have REST API and PowerShell as selectors - might have to revisit this after Build.

2022-05-16 18:14 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +When you grant API permissions to a client app or user in Azure Active Directory (Azure AD), they're recorded as objects that can be accessed, updated, or deleted like any other. Using Microsoft Grap
Reworded to "..., the permission grants are recorded...".

We're introducing the term "app role assignment" in Step 3 so the customer can correlate the term to the process, hopefully making it easier to correlate with the respective API.

2022-05-16 18:34 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +In this step, we'll assign our app an app role that's exposed by Microsoft Graph, thereby creating an app role assignment. In the following example, the object ID of Microsoft Graph in this tenant is
Done. Applied the same guidance to other sections.

2022-05-16 18:55 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +To confirm all apps with a role assignment to the app, run the following request.
Changed from "all apps" to "all principals" to cover all identities that may be referenced by principalId in the appRoleAssignment object.

2022-05-16 18:56 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +Alternatively, you can choose to grant consent on behalf of all users in the tenant. The request body is similar to the above except with the following changes:
Changed to "similar to the previous request body except.."

2022-05-16 19:15 UTC, opbld34 commented
Docs Build status updates of commit _[93fe89b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93fe89b6679415266814dcbb11c612347a518d5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-e6a9b52dbea0ea1b9f434d7fa94293c2-22ff3f3e)
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-b6377c5197c4817d25d10b506d4effa0-22ff3f3e)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

<a id="e6a9b52dbea0ea1b9f434d7fa94293c2-22ff3f3e"></a>
### [concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

<a id="b6377c5197c4817d25d10b506d4effa0-22ff3f3e"></a>
### [concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to use Microsoft Graph to grant API permissions to an app.' is duplicated in 'permissions-app-grant-msgraph.md(3,14)', 'permissions-delegated-grant-msgraph.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205161913489796-16217/BuildReport?accessString=4a4612171bc9f33a9bee38c0e3d504c83e59cd56c0cd374cab0caa224cb3a50e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 15:14 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +4. Get the object ID of a resource service principal that exposes app roles, and the ID of the app role to grant. In this guide, we'll use the Microsoft Graph resource service principal.
OK, so changing pre-requisite 4 to be "Have/Get object ID of the client service principal", and replacing Steps 1+2 with how to get the object ID of the resource service principal.

2022-05-18 15:49 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +title: "How-To: Grant API application permissions programmatically"
Good idea. I'll change the scope of the articles to grant and revoke.

2022-05-18 17:29 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +    "scope": "User.Read.All"
Done.

2022-05-18 17:31 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +## Step 4 [Optional]: Grant more delegated permissions to the service principal
Done. Changed the scope of the articles to grant and revoke.

2022-05-18 17:37 UTC, opbld32 commented
Docs Build status updates of commit _[824e8b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/824e8b04ec519aad921c7984100b6930c54a2782)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181735389650-16217/BuildReport?accessString=069f24d581e78a5b04f8aae244a5eae810e7fdd8b8bb0a69cbcf209220aebc8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 17:39 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +## Step 1: Register an application with Azure AD
Applied this suggestion. Thanks.

2022-05-18 18:10 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +> The `AppRoleAssignment.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app, user, or group in your organization. Access to this service
@psignoret - We're trying to warn about the latter scenario. Not sure I understand the full privileges of the `AppRoleAssignment.ReadWrite.All` permission - do you recommend we remove this warning altogether?

2022-05-18 18:12 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +    3. Get the object ID of the client service principal to which you'll grant app roles. In this article, the client service principal is identified by ID `b0d9b9e3-0ecf-4bfd-8dab-9273dd055a94`.
Hi @psignoret - You posted this comment about the pre-requisites:
> I would add the authorization needed to do all of the below as pre-requisites. It's important we include the authorization needed by both the user and the app in the app+user (delegated) case, and the authorization needed by the app in the app-only case. (Not to be confused with the fact that what we're doing here happens to be granting another app roles to an app.)

Not sure I fully understand your ask. Could you offer the suggestion inline as guidance? Thanks.

2022-05-18 19:11 UTC, opbld30 commented
Docs Build status updates of commit _[0d18f7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d18f7f984cec6b63f5ce43bc38a751b7469fd28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181909163503-16217/BuildReport?accessString=28d03450ab7591910f6599c03803fd1a4a4886e1a71909f8f400ed658ff2dfb8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 00:47 UTC, Jackson-Woods commented on concepts/permissions-app-grant-msgraph.md
> +> The `AppRoleAssignment.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app, user, or group in your organization. Access to this service
I think this gets at some confusion in the doc/scenario...

1. Am I signing in to some other tool, like Graph Explorer, and making calls there? Or,
2. Am I writing an automated client app / script to manage consent in my tenant, that runs in app only mode?

If it's #2, I think we are saying "be extremely careful which apps you grant these types of permissions and who can access the script." If it's #1 the warning makes less sense, and we should probably say something like "don't grant consent for your entire organization if you're using Graph Explorer."

Idk, @psignoret is that what you were getting at?

2022-08-10 11:19 UTC, opbld31 commented
Docs Build status updates of commit _[0d18f7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d18f7f984cec6b63f5ce43bc38a751b7469fd28)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bdf2724b)

<a id="bdf2724b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101118438913-16217/BuildReport?accessString=61b433c6b159c7a6d54cccfcc85a7e48df69bd1c44552e8e7e1fb64c87e94568).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 17:56 UTC, opbld34 commented
Docs Build status updates of commit _[d5c9921](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5c9921f1543992d1adc9c41f5f91e47aa14faa2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-f77779f9)
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |

<a id="d6641161fd46c78dd4128bccd65500b6-f77779f9"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml)
 - **Line 95, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'displayName' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121754043975-16217/BuildReport?accessString=a5d50b28598ec8507630012e3b72c311408b97958b715876a9f19f23c08d9371).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 18:02 UTC, opbld32 commented
Docs Build status updates of commit _[57587c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57587c91b70294a64b6b161035a59f8fec2970da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121800240106-16217/BuildReport?accessString=df43a9efc05a31769b90f9851c25a59a21b30e2b8de85ec1fbcc1dcae9136b7f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 18:18 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +> The `AppRoleAssignment.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app, user, or group in your organization. Access to this service
Hi @Jackson-Woods - The scenario relates to # 1 so I've commented out this warning.

2022-08-17 18:19 UTC, opbld30 commented
Docs Build status updates of commit _[520145d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/520145deaf75f63021b66f4203c700123ed88d6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171817478786-16217/BuildReport?accessString=a1186dcf65aebc658d4cfc24215e7b104b164e98c1e1e2cd3053163b009d0626).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-17 16:27 UTC, opbld30 commented
Learn Build status updates of commit _[520145d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/520145deaf75f63021b66f4203c700123ed88d6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210171613182406-16217/BuildReport?accessString=c38d7494c183935efce46cd7a8b4d840e3dafb84485cd690f52a3b5fe83bae2a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 17:06 UTC, FaithOmbongi commented
@Jackson-Woods for re-review and approval.

2022-11-02 23:31 UTC, Jackson-Woods approved these changes
Looks good Faith, thank you! Please see some minor comments in the PR.

2022-11-02 23:31 UTC, Jackson-Woods commented on concepts/permissions-app-grant-msgraph.md
> +> The `AppRoleAssignment.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app, user, or group in your organization. Access to this service
What if we just reword second sentence to say "Apps that have been granted this permission should only be accessed by appropriate users."

2022-11-02 23:31 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +    2. In the app you've signed in to, consent to the `Application.ReadWrite.All`, `DelegatedPermissionGrant.ReadWrite.All` delegated permissions on behalf of the signed-in user. You don't need to co
Which calls is Application.ReadWrite.All required for? Could this be Application.Read.All and DelegatedPermissionGrant.ReadWrite.All?

2022-11-02 23:31 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +> The `DelegatedPermissionGrant.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app or user in your organization. Access to this service
Consider changing along the lines of the suggestion for appRoles: "Apps that have been granted this permission should only be accessed by appropriate users."

2022-11-02 23:31 UTC, Jackson-Woods commented on concepts/permissions-delegated-grant-msgraph.md
> +If a service principal has been granted multiple delegated permission grants on behalf of a user, you can choose to revoke either one or some grant or all grants.
suggest simplify end of statement as "... you can choose to revoke either specific grants or all grants."

2022-11-04 16:07 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +> The `DelegatedPermissionGrant.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app or user in your organization. Access to this service
Done.

2022-11-04 16:07 UTC, FaithOmbongi commented on concepts/permissions-app-grant-msgraph.md
> +> The `AppRoleAssignment.ReadWrite.All` permission allows an app or service to manage permission grants and elevate privileges for any app, user, or group in your organization. Access to this service
Done.

2022-11-04 16:22 UTC, FaithOmbongi commented on concepts/permissions-delegated-grant-msgraph.md
> +    2. In the app you've signed in to, consent to the `Application.ReadWrite.All`, `DelegatedPermissionGrant.ReadWrite.All` delegated permissions on behalf of the signed-in user. You don't need to co
Yep, you're right. Application.Read.All is enough. Fixed.

2022-11-04 16:29 UTC, opbld31 commented
Learn Build status updates of commit _[a38bdc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a38bdc0998627f142faec24d6e3cb79aca106e1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-app-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-app-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |
[concepts/permissions-delegated-grant-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-delegated-grant-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-delegated-grant-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-app-grant-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211041627258755-16217/BuildReport?accessString=c0a138a562571efc7b646661c9ca6c35380e79188335d06380088d5abbb5ceef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 16:50 UTC, opbld30 commented
Learn Build status updates of commit _[60c4ade](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60c4ade14053688c916ce4a6127e7f782d984a8f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-grant-via-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-grant-via-msgraph.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?branch=pr-en-us-16217) | [Details](#user-content-97bf6ddb88313f2429901c8482138e18-f286d02e)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?branch=pr-en-us-16217) |

<a id="97bf6ddb88313f2429901c8482138e18-f286d02e"></a>
### [concepts/permissions-grant-via-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-grant-via-msgraph.md)
 - **Line 215, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'permissions-delegated-grant-msgraph.md'.`````
 - **Line 478, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'permissions-app-grant-msgraph.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211081647459376-16217/BuildReport?accessString=d72fd17bb777bfd3bd11fa0cdd30d2c80d2841dedcc9adde39d76a015723c073).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 16:59 UTC, opbld32 commented
Learn Build status updates of commit _[8616142](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86161425e92b64bfc19bcb0a90dd1b28687a35d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-grant-via-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-grant-via-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211081656447131-16217/BuildReport?accessString=882cb81a05091f520c1d14c664b1790f41937a65e2a291dba4b112e9d7fae01f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 02:50 UTC, Lauragra approved these changes

2022-11-09 02:53 UTC, opbld32 commented
Learn Build status updates of commit _[e68dbf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e68dbf29b31b9efd81de23414ca8203e9fe963a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-grant-via-msgraph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/permissions-grant-via-msgraph.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?branch=pr-en-us-16217) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grantPermsViaAPI/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-grant-via-msgraph?branch=pr-en-us-16217) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211090250215320-16217/BuildReport?accessString=c6013816556bb01234387e6e1bbba921aa4d156fae7546f2c1cac242694c964c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 02:54 UTC, merged