[Azure AD roles] assignedPrincipals method
microsoftgraph/microsoft-graph-docs pull request #16222
Opened 2022-03-18 23:26 UTC by rolyon

2022-03-18 23:28 UTC, opbld34 commented
Docs Build status updates of commit _[e0d31bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0d31bb34b56a884f3d97a810063e139b2ba7e24)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) | [Details](#user-content-e939fda223a2e6d1a4621b9d0a976008-433e1c68)
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="e939fda223a2e6d1a4621b9d0a976008-433e1c68"></a>
### [api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203182326089810-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T23%3A28%3A13Z&sr=b&sp=r&sig=KyPXS4v7hAiL5%2FIhnFiOrItV4Rj5GJh8WlaWTE89gsI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 23:40 UTC, opbld30 commented
Docs Build status updates of commit _[1b96122](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b96122d97f35875a3c29fb9f9f139a35c41a511)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203182338511389-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T23%3A40%3A34Z&sr=b&sp=r&sig=8eMgQJ58OKGvd652S3Hri7U6V%2BMPOgKTuDzSY%2F7FFtk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 23:52 UTC, opbld33 commented
Docs Build status updates of commit _[38b1001](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38b1001fa2d900857ea37a7e96037078b0e6b581)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203182350285319-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T23%3A52%3A06Z&sr=b&sp=r&sig=YrxNdvauAUwcUijzYRTXsQiL9zuDM3Ykow7QBCW83Rk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 15:48 UTC, abhijeetsinha commented
@rolyon  - I am unable to add comment in this PR. Can you add me as reviewer?

2022-03-22 17:16 UTC, rolyon commented
Hi @abhijeetsinha 
You are a reviewer on this PR. I also added you as an assignee.
Can you add comments now?

2022-03-24 17:43 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +description: "**TODO: Add Description**"
@rolyon - test comment

2022-03-28 23:30 UTC, opbld31 commented
Docs Build status updates of commit _[1a8028a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a8028aa46a39f880799e302c53b688515bd607f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203282328020553-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-28T23%3A30%3A54Z&sr=b&sp=r&sig=YEoADRT83A8jY4J%2BUgOVl0Asumvu6RCyRNgSrI5Hp3A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 07:02 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +description: "Get the users and groups assigned to a role across all scopes."
@rolyon  - Should it be 'all scopes' or 'different scopes'?. Do you also want to talk about count in description so that search engine pick it up

2022-03-31 07:08 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +title: "assignedPrincipals"
@rolyon - we need better title for search engines. Some options - 
List assignedPrincipals
List transitive assignedPrincipals,
List and count assignedPrincipals

2022-03-31 07:11 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +Get the users and groups assigned to a role across all scopes.
@rolyon  - Suggestion: 
Get direct and transitive principals assigned to a specific role across different scopes. You can use `count` query parameter to get the count as well. If you want to get direct and transitive role assignments for a specific principal, use List transitiveRoleAssignments API.

2022-03-31 07:15 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Scopes
@rolyon - Shouldn't the heading be 'directoryScopeType' or something of this sort? Basically, this section is explaining how to use directoryScopeType in different scenarios.

2022-03-31 07:16 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +
@rolyon - We need to talk about `count` parameter as discussed in the API. It is a key reason for building this API. Probably, we will have to include a section for 'Optional query parameters'

2022-03-31 07:17 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Request
@rolyon - We need more examples here. Refer to api doc.

2022-03-31 07:20 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedroledefinition.md
> +| [assignedPrincipals](../api/unifiedroledefinition-assignedprincipals.md) | [directoryObject](../resources/directoryobject.md) collection|Get the users and groups assigned to a role across all scope
@rolyon - This name is not right. Consider something like this - List <>.
Second point, should we have this API be listed unifiedRoleDefinition or under unifiedRoleAssignment (where List transitiveRoleAssignment lives)?

2022-04-01 00:11 UTC, opbld30 commented
Docs Build status updates of commit _[e182a4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e182a4e72a1f56aba0e9528ccfe60067b29759aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204010009334376-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T00%3A11%3A22Z&sr=b&sp=r&sig=oKIQa80dgHkpJgQSkmJ4bzBnmUemHuqIu2AO1QsA9lA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 22:15 UTC, opbld30 commented
Docs Build status updates of commit _[17e135b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17e135b78ceabf1e238b229ee498496f56fa7aab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012212597445-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T22%3A15%3A25Z&sr=b&sp=r&sig=hU%2FByU8Xau0AVRAcklTQ9TvEfOd%2FT6DQAmOW81PWQT0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:20 UTC, opbld33 commented
Docs Build status updates of commit _[92e7e77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92e7e77f4330160eb858f1d5908560614df730e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204020018212628-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-03T00%3A20%3A13Z&sr=b&sp=r&sig=Y9%2FxpfCT5cqFqp5jikW6fjgu%2FpWH3j%2Fi%2Bsy6me1P5Ds%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:31 UTC, opbld33 commented
Docs Build status updates of commit _[31ec8a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31ec8a776cd6fac2420f3c4330b2c4aac43d1e43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204020029356095-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-03T00%3A31%3A40Z&sr=b&sp=r&sig=O7VUyKqdJer3S1NIJ565%2BFME1nc63xY%2F7ITd7o2vfHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:37 UTC, opbld31 commented
Docs Build status updates of commit _[595a941](https://github.com/microsoftgraph/microsoft-graph-docs/commits/595a941318fcc2b77553c89b30de5f3341662cd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204020035189691-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-03T00%3A37%3A05Z&sr=b&sp=r&sig=mpvOnrLjdXAM7Yhlg1f3kIgyypd4TXaEV63evKnWq6Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:48 UTC, opbld33 commented
Docs Build status updates of commit _[4666e11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4666e1136c4f920f00b12f34ec950392b39e6ba2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204020044528279-16222%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-03T00%3A48%3A16Z&sr=b&sp=r&sig=PT8u19dY1NjT42HSEv1bTI0jTyu6mys7VxFpOqQ%2FtXU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:52 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +description: "Get the users and groups assigned to a role across all scopes."
Changed to different scopes. Just included count info in intro paragraph.

2022-04-02 00:52 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +title: "assignedPrincipals"
Changed to List assignedPrincipals

2022-04-02 00:52 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +Get the users and groups assigned to a role across all scopes.
I updated

2022-04-02 00:53 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Scopes
I updated

2022-04-02 00:53 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +
Added an Optional query parameters section

2022-04-02 00:54 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Request
Added examples from api doc

2022-04-02 00:58 UTC, rolyon commented on api-reference/beta/resources/unifiedroledefinition.md
> +| [assignedPrincipals](../api/unifiedroledefinition-assignedprincipals.md) | [directoryObject](../resources/directoryobject.md) collection|Get the users and groups assigned to a role across all scope
Graph Studio stub generator positions it in unifiedroledefinition.md.
I agree that logically it fits better under Role assignment, but I'm inclined to leave where generated.

2022-04-06 19:31 UTC, FaithOmbongi requested changes
Thank you @rolyon for your work on this PR.

I've left suggestions for minor fixes and some recommended tweaks to how we present the information.

Allow me to get back to you on the permissions listed in Line 32-56. Let me investigate the better way to document this and ping you internally for clarification.

2022-04-06 19:31 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/roleDefinitions/b0f54661-2d74-4c50-afa3-1ec803f12efe/assignedPrincipals(directoryScope='administrativeUnit', directoryScopeId ='<guid>')
Same comment as in directoryScopeId property. Please use an actual value that will help customers correlate with the pattern.

2022-04-06 19:31 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/roleDefinitions/b0f54661-2d74-4c50-afa3-1ec803f12efe/assignedPrincipals
I see the API.md shows the syntax as `/assignedPrincipals()`. Please verify.

2022-04-06 19:31 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Example 4: Get directly assigned users only for a particular scope
This correct?
```suggestion
### Example 4: Get directly assigned users only for a tenant-wide scope
```

2022-04-06 19:31 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Read role assignments
Coming to the permissions last because I needed to correlate with your examples first.

Can I assume this represents permissions for direct role assignments only? If so, let's change the header to "Read direct role assignments".

2022-04-06 19:31 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +|Application|RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All|
Let's avoid listing Directory.ReadWrite.All unless the others won't work.
```suggestion
|Permission type|Permissions (from least to most privileged)|
|:---|:---|
|Delegated (work or school account)|RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory|
|Delegated (personal Microsoft account)|Not supported.|
|Application|RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory|
```

2022-04-06 19:31 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +|Application|User.Read.All, Directory.Read.All, User.ReadWrite.All, Directory.ReadWrite.All|
Let me get back to you on this because I don't think these permissions by themselves work for this API, right? They work in combination with the RoleManagement* permissions. So we need a better way to represent these.

2022-04-25 19:23 UTC, opbld31 commented
Docs Build status updates of commit _[9d0affb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d0affba767e7e26e54ddc3273df0ad86238c81c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251920004024-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T19%3A23%3A01Z&sr=b&sp=r&sig=tsiq%2FQEDrCQJC62dPIJwA2Ath880GE6d2wOALiRqDp0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 19:25 UTC, opbld32 commented
Docs Build status updates of commit _[41ad66d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41ad66d6f4197e70b3ac7c75209ed71bf7661b8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251922022997-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T19%3A25%3A41Z&sr=b&sp=r&sig=lu%2Fsi3BZv6ieCPabz9zLKLVgv4KpZFnbkUdFCka3DpQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 19:43 UTC, opbld31 commented
Docs Build status updates of commit _[71fc529](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71fc529aa5a11b1c88224006738d27bdd7cc78ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251941106385-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T19%3A43%3A14Z&sr=b&sp=r&sig=WdCAjKnG%2FP6G6xGMSft82aIS62tc7Mt1FvsoJOqbfH0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 19:49 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/roleDefinitions/b0f54661-2d74-4c50-afa3-1ec803f12efe/assignedPrincipals
When I include the empty parentheses, apidoctor beta displays the following error:
Error: unifiedroledefinition_assignedprincipals_allscopes:
Malformed function params . Expected key-value params e.g. /function1(key=value). Remove parentheses if no params are expected.

2022-04-25 19:49 UTC, opbld31 commented
Docs Build status updates of commit _[0aa7664](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0aa766488f8b2547fde187d8fab74ecf66f59fb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251947259884-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T19%3A49%3A35Z&sr=b&sp=r&sig=PrpLegLj75dLSaQGqp7j%2FPkFlDx7juubeVn5OYQPalc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 19:52 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +|  | Group3<br/>`b93d5379-a464-4db5-b8e1-694910f1e11e`<br/>(User2 is a member)<br/>(User3 is a member) | Role1 | Scope3 |
I think better to have User column blank to show that role assignment is on group instead of user.

2022-04-25 20:22 UTC, opbld33 commented
Docs Build status updates of commit _[c24f456](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c24f456b1ef678b181e42de45cdeb5ce4fa2481c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252020070288-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T20%3A22%3A09Z&sr=b&sp=r&sig=XU4sGiNLDXKQjFTWfjtEDJfAZ9UVO7Emqm9KdfFazDk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 20:31 UTC, opbld32 commented
Docs Build status updates of commit _[4b6a697](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b6a6970624671d3bf19ebf21136e4d2509f5305)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252029310244-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T20%3A31%3A18Z&sr=b&sp=r&sig=y7EL5dwCoHfKkC27wbwQKzD7eVTbpJrGtd9Mr4LIGTo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 20:41 UTC, opbld31 commented
Docs Build status updates of commit _[c67f08b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c67f08bca7126f0de079b7ad815255ae94b0bce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252038100217-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T20%3A41%3A11Z&sr=b&sp=r&sig=RtZ8u7jOio02mb%2FZfhkZdVn81WuLk%2FpeCqUaOFNcIFI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 20:48 UTC, opbld34 commented
Docs Build status updates of commit _[fcf50ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcf50ee850e790ab1ff7e8af7f9723a8d925b673)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252045499849-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T20%3A48%3A36Z&sr=b&sp=r&sig=tshva0QXLYyz13YoyOfqClKzD6J5xA%2F9Rq8U7O5%2FVx4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 20:50 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +description: "Get the list of principals (users and groups) directly or transitively assigned to a specific role for different scopes."
@abhijeetsinha - Can you review?

2022-04-25 20:50 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Read role assignments
@abhijeetsinha - Can you review?

2022-04-25 21:03 UTC, opbld32 commented
Docs Build status updates of commit _[3f816a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f816a4e5739ceda144ab3c420c3087ba559c351)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252100171047-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T21%3A03%3A42Z&sr=b&sp=r&sig=ke%2F8NH1uSPQFOD2ctZ%2BRxlEYZeah6mP9hLOuRxQoJ2o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 08:07 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +description: "Get the list of principals (users and groups) directly or transitively assigned to a specific role for different scopes."
@rolyon , @FaithOmbongi - Service principals will also be returned, along with users and groups. Either use 'security principals' or add 'service principals' in the list.

2022-04-27 08:11 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Read role assignments
@rolyon , @FaithOmbongi - Agreed. To read transitve role assignments, the app should have the permission to read group memberships as well.

2022-04-27 08:49 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +description: "Get the list of principals (users and groups) directly or transitively assigned to a specific role for different scopes."
I changed to
security principals (users, groups, and service principals)

2022-04-27 08:49 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +### Read role assignments
I changed header to
Read direct role assignments

2022-04-27 08:50 UTC, opbld33 commented
Docs Build status updates of commit _[26263f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26263f33dcf3ea37d6b7c7eade7ec4a8c8363e0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204270847288505-16222%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T08%3A50%3A07Z&sr=b&sp=r&sig=9Zynpk0fTO8cFnb3I%2BLbpr8ngEhbR6JNc5F8IyT%2FkBc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 12:38 UTC, FaithOmbongi reviewed
Minor feedback. Let me follow up with you internally to understand more about the permissions requirements.

2022-05-05 12:38 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [assignedPrincipals](https://docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals) method to the [unifiedRoleDefinition](https://docs.micros
Suggestion to enhance changelog description so customer know the benefit of the API before they can get into the docs.
```suggestion
          "Description": "Added the [assignedPrincipals](https://docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals) method to the [unifiedRoleDefinition](https://docs.microsoft.com/en-us/graph/api/resources/unifiedRoleDefinition?view=graph-rest-beta) resource. Use this API to retrieve the principals (users, groups, and service principals) directly or transitively assigned to a specific role for different scopes.",
```

2022-05-06 19:38 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +
Suggestion - given this API can be used to get either direct assignments or direct+transitive assignments
```suggestion
The following query syntax retrieves only principals with direct assignments.
```

2022-05-06 19:38 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +
Same suggestion as the into statement above
```suggestion
To retrieve principals with both direct and transitive assignments, apply the **transitive** [function parameter](#function-parameters).
```

2022-05-06 19:38 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +This method supports the `$count` OData query parameter to help customize the response. You can also filter by OData casts, for example, `microsoft.graph.user` and `microsoft.graph.group`. For genera
Suggestions to include more query parameters based on tests
```suggestion
This method supports the `$count`, `$select`, `$filter`, and `$orderBy` OData query parameters to help customize the response. You can also filter by the type of object using OData casts. For example, `/assignedPrincipals(transitive=false)/microsoft.graph.user` and `/assignedPrincipals(transitive=true)/microsoft.graph.servicePrincipal/$count`. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-05-09 15:55 UTC, FaithOmbongi requested changes
Thank you @rolyon for your patience in this review. I've tested the scenarios you've documented and shared some additional feedback to consider.

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +>**Note:** The response object shown here might be shortened for readability.
Q: Given that the response below doesn't indicate the user1 twice (at scope1 & scope2), should we indicate in a response description that the response shows only unique instances of assignments to that role, regardless of whether a principal has multiple assignments to that role at different scopes?

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +        "userPrincipalName": "user1@contoso.com"
Assuming only RoleManagement.Read is granted (it's inferred by lack of additional info in the example intro), should be `null`. 
```suggestion
        "displayName": null,
        "userPrincipalName": null
```

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +        "userPrincipalName": "user1@contoso.com"
Same comment as Example 3 applies
```suggestion
        "displayName": null,
        "userPrincipalName": null
```

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +    },
Tested and I don't see user 2 and user 3 getting returned because your request URL doesn't include `transitive=true`. Can you confirm?
```suggestion
    {
        "@odata.type": "#microsoft.graph.user",
        "id": "6c62e70d-f5f5-4b9d-9eea-ed517ed9341f",
        "displayName": null,
        "userPrincipalName": null
    },
```

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +        "displayName": null
Value of displayName will be returned for groups even without _Group.*_ permissions. It's only for users that it'll be `null`.
```suggestion
        "displayName": "Group 1"
    },
    {
        "@odata.type": "#microsoft.graph.group",
        "id": "182351a6-d974-4d18-88ae-8a148da44cd2",
        "displayName": "Group 2"
    },
    {
        "@odata.type": "#microsoft.graph.group",
        "id": "b93d5379-a464-4db5-b8e1-694910f1e11e",
        "displayName": "Group 3"
```

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +The following example gets the transitive assigned principals and inline count with ([RoleManagement.Read.Directory](/graph/permissions-reference#role-management-permissions) + [GroupMember.Read.All]
- Tested and the query doesn't return transitive assigned principals until you explicitly use the `transitive=true` parameter in the function.
- Assigning the Group permissions also has no bearing on the results compared with just RoleManagement.Read permission - so no need to add this overhead.

```suggestion
### Example 5: Get directly assigned principals and inline count

The following example gets the directly assigned principals and displays an inline count.
```

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET https://graph.microsoft.com/beta/roleManagement/directory/roleDefinitions/b0f54661-2d74-4c50-afa3-1ec803f12efe/assignedPrincipals(directoryScope='administrativeUnit', directoryScopeId ='d0c2e067-
Fixed function parameter
```suggestion
GET https://graph.microsoft.com/beta/roleManagement/directory/roleDefinitions/b0f54661-2d74-4c50-afa3-1ec803f12efe/assignedPrincipals(directoryScopeType='administrativeUnit', directoryScopeId ='d0c2e067-9ae9-4dbf-a280-51a51c46f432')
```

2022-05-09 15:55 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +        "id": "6c62e70d-f5f5-4b9d-9eea-ed517ed9341f"
OK, it might be inconsequential but in Example 4, this same user ID (user1) is scoped to the tenant - might be confusing for customers using your scenario as a reference point.

2022-05-27 15:53 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +
@FaithOmbongi , @rolyon - We are talking about just schema at this point in the doc. Why do you want to suggest about direct/transitive here? 

The API in general supports both transitive as well as direct principals via a paramtere. We should not leave customers with the impression that it is only for principals who are directly assigned.

2022-05-27 15:55 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET /roleManagement/directory/roleDefinitions/{unifiedRoleDefinitionId}/assignedPrincipals()
@FaithOmbongi - I cannot recall how functions are expressed in HTTP call. I think parentheses are required, but if you have tested it and know for sure, then its fine.
cc: @rolyon

2022-05-27 15:58 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +
@FaithOmbongi - We have a full section on Function Parameters. Why do you want to add a blurb which talks about just transitive/direct? If we go by the this convention, then we have to express the details of the parameters in text. 
BTW, these are my thoughts. You all the are expert and I would go with what you suggest.
cc: @rolyon

2022-05-27 17:49 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET /roleManagement/directory/roleDefinitions/{unifiedRoleDefinitionId}/assignedPrincipals()
@abhijeetsinha - When parentheses are included, they should have explicitly function parameters - Robert hit a validation error when he used empty parentheses. Then this syntax aligns with examples 3,5.

2022-07-27 23:35 UTC, opbld30 commented
Docs Build status updates of commit _[309349d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/309349def79bd7e1c2aee819b29fc6db2d095b20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207272331099827-16222/BuildReport?accessString=752a91bc949f98e4944745c3a3eba930caa05ec9759d40e3ac691d16933a6250).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-30 21:10 UTC, Licantrop0 commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +|All scopes|`/assignedPrincipals(transitive={true | false})`|All roles|
you need to escape every pipe (`|`) character inside a table with `\|` otherwise it will confuse the markdown engine.

2022-10-04 14:01 UTC, opbld32 commented
Learn Build status updates of commit _[bbec2ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbec2ed32ce34e8d78c3dbd25d98a72985322b40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041359215373-16222/BuildReport?accessString=0fa9f725faf248f2cbbb058cfba9e431676dfeda1caa93e16ed9be4148a21422).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 16:51 UTC, opbld33 commented
Learn Build status updates of commit _[73d59b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73d59b799d0b02e73a6e1b70c301aac53b5de54f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210131649075449-16222/BuildReport?accessString=a277b8764607be612f881b4953ae191c15d5d99c04a98f0cf07c54faeda24d89).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-23 20:12 UTC, opbld33 commented
Learn Build status updates of commit _[acb6045](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acb60455ce435cb76c58fd0bfbd055fb9cc6702f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210232009583199-16222/BuildReport?accessString=7ca71d4e7c7bf6d0a47be2e1dce2124e0d1735e078fbe4f5fa64e1872a37fd33).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 20:31 UTC, opbld32 commented
Learn Build status updates of commit _[065aa37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/065aa37297ff3af7c812024434289329b371bbb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210242028129627-16222/BuildReport?accessString=caee57391bcad9e5514a5dbb59a36d6571f630454f6636f797ce1087d5ae4de5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 20:44 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +    },
I think you are correct. I see the same thing when I test. I removed user2 and user3.

2022-10-24 20:47 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +|  | Group3<br/>`b93d5379-a464-4db5-b8e1-694910f1e11e`<br/>(User2 is a member)<br/>(User3 is a member) | Role1 | Scope3 |
I think more understandable to have group in a separate column.

2022-10-24 20:49 UTC, rolyon commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +|All scopes|`/assignedPrincipals(transitive={true | false})`|All roles|
Since formatted as inline code, I think okay. It renders correctly in build.

2022-10-24 21:13 UTC, opbld33 commented
Learn Build status updates of commit _[fc00aa9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc00aa9838aa41ce464bf772cadc49f65c71293d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210242110460562-16222/BuildReport?accessString=39e1afb291df69888a7e3b00b38615aba4176421d7e9ed150fe403e15ccd2a20).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 22:31 UTC, Licantrop0 approved these changes

2022-11-02 17:49 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
> +GET /roleManagement/directory/roleDefinitions/{unifiedRoleDefinitionId}/assignedPrincipals()
Latest test results: API has been fixed and no longer throws an error when you use empty parentheses.

2022-11-02 18:07 UTC, FaithOmbongi approved these changes

2022-11-03 00:12 UTC, opbld31 commented
Learn Build status updates of commit _[36e2b70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36e2b7076b45cbd8e5240839ed4b77fe0378dc4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211030001006311-16222/BuildReport?accessString=2dec24b712540d2dd4833a4cc4c129c5eb3f356f9d55bf2a572f808cf9306ba1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-03 00:16 UTC, opbld30 commented
Learn Build status updates of commit _[49e3a40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49e3a400ccf26479ce50e81db3887839194a4890)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211030013371745-16222/BuildReport?accessString=30f020164c4edc0be349363f2d3842322168e9ffe8b84a867a46232141bcbdc9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-03 18:36 UTC, opbld30 commented
Learn Build status updates of commit _[85e2d91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85e2d9173d225cfa0cab6c294fe191ab45c92aec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211031834099484-16222/BuildReport?accessString=47e4222e00ce5415865b0cf77987ee82a7f4fad5546ba06204d50bcdb0a1c9ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-05 01:17 UTC, opbld33 commented
Learn Build status updates of commit _[2235d66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2235d667deb76e5747dccfa75864339034d0198a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-assignedprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/api/unifiedroledefinition-assignedprincipals.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-assignedprincipals?view=graph-rest-beta&branch=pr-en-us-16222) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-assignedprincipals/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211050113389703-16222/BuildReport?accessString=90e74a819eef3703dfdf8af9ac1f8d05ff01eb2bfbe49ca54e83f65cc7539902).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-05 01:22 UTC, merged