Security threat submission placeholder for test
microsoftgraph/microsoft-graph-docs pull request #16242
Opened 2022-03-22 04:17 UTC by caigen

2022-03-22 04:19 UTC, opbld31 commented
Docs Build status updates of commit _[243407c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/243407cb2eed91478b5e6bf96e078b68133d295f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-threat-submission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-threat-submission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-threat-submission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-cee6ef7941c41e62efb5c7a0f0f2157a-7dd7ecae)

<a id="cee6ef7941c41e62efb5c7a0f0f2157a-7dd7ecae"></a>
### [api-reference/beta/api/security-threat-submission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-threat-submission.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203220417278024-16242%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T04%3A19%3A27Z&sr=b&sp=r&sig=c7HHC8pETbHo9FU1HasfBefsuStlODrCDhh8tND0NnI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 05:38 UTC, opbld32 commented
Docs Build status updates of commit _[de7fc6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de7fc6da2f933c4aded9b2da2ce38ec8608324e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailcontentthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailcontentthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-73efdffbb83b8766d170b45e29f55a87-e9f0fcb0)
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-e9f0fcb0)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-e9f0fcb0)
[api-reference/beta/api/security-emailcontentthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailcontentthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-a4c091306a596263196d734268c7a617-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-fb8ce42f18e201df272b8c52066a8f3b-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-01cd9dd8fcd0023b2c4b1dccf8dffc6f-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e9f0fcb0)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-e9f0fcb0)
[api-reference/beta/api/security-emailurlthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailurlthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46654df462fadf080099976150b479d2-e9f0fcb0)
[api-reference/beta/api/security-emailurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-ca26b142503f6aa730d8879e8d9bfd37-e9f0fcb0)
[api-reference/beta/api/security-emailurlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailurlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-38b5607b9d24 [...]

2022-05-11 10:16 UTC, opbld30 commented
Docs Build status updates of commit _[bb0e9dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb0e9dc3390b9eef1509fa934466c9dfbc7e9224)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ea3e94a8)

<a id="ea3e94a8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205111015394998-16242/BuildReport?accessString=d9c5a7f754e51f10cd0ed3b8e5fc92442cede5d4e6342448c7cc1282b80d437a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 10:34 UTC, opbld31 commented
Docs Build status updates of commit _[2ef86c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ef86c4146ea9adf0b7b4673033197a08e9b8693)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalgroup-delete-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete-members?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-36df75d7d67c2cfe0fcefbbe87356c18-95143763)
[api-reference/beta/api/externalconnectors-externalgroup-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalgroup-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-list-members?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-349c67c0ce1c759b2b47a31fdaeeaaea-95143763)
[api-reference/beta/api/externalconnectors-intune-identity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-intune-identity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-intune-identity-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-584c4363054eac6dec39befbee6ff53f-95143763)
[api-reference/beta/api/externalconnectors-intune-identity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-intune-identity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-intune-identity-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1f6011d718ee11a5945a456336d1c169-95143763)
[api-reference/beta/api/security-emailcontentthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-73efdffbb83b8766d170b45e29f55a87-95143763)
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-95143763)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-95143763)
[api-reference/beta/api/security-emailcontentthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-a4c091306a596263196d734268c7a617-95143763)
[api-reference/beta/api/security-emailthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-fb8ce42f18e201df272b8c52066a8f3b-95143763)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-95143763)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-95143763)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-95143763)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-95143763)
[api-reference/beta/api/security-emailthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-01cd9dd8fcd0023b2c4b1dccf8dffc6f-95143763)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-95143763)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-95143763)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-95143763 [...]

2022-05-11 10:53 UTC, opbld33 commented
Docs Build status updates of commit _[9e5e53b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e5e53b06d02df7ed939de6dd363a67a6622c98d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalgroup-delete-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete-members?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-36df75d7d67c2cfe0fcefbbe87356c18-13c58a30)
[api-reference/beta/api/externalconnectors-externalgroup-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalgroup-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-list-members?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-349c67c0ce1c759b2b47a31fdaeeaaea-13c58a30)
[api-reference/beta/api/externalconnectors-intune-identity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-intune-identity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-intune-identity-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-584c4363054eac6dec39befbee6ff53f-13c58a30)
[api-reference/beta/api/externalconnectors-intune-identity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-intune-identity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-intune-identity-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1f6011d718ee11a5945a456336d1c169-13c58a30)
[api-reference/beta/api/security-emailcontentthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-73efdffbb83b8766d170b45e29f55a87-13c58a30)
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-13c58a30)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-13c58a30)
[api-reference/beta/api/security-emailcontentthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-a4c091306a596263196d734268c7a617-13c58a30)
[api-reference/beta/api/security-emailthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-fb8ce42f18e201df272b8c52066a8f3b-13c58a30)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-13c58a30)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-13c58a30)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-13c58a30)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-13c58a30)
[api-reference/beta/api/security-emailthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-01cd9dd8fcd0023b2c4b1dccf8dffc6f-13c58a30)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-13c58a30)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-13c58a30)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-13c58a30 [...]

2022-05-11 10:55 UTC, opbld32 commented
Docs Build status updates of commit _[beca2e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beca2e55b3889c1c57218d229f89705338b11012)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailcontentthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-73efdffbb83b8766d170b45e29f55a87-a7d667cd)
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-a7d667cd)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-a7d667cd)
[api-reference/beta/api/security-emailcontentthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-a4c091306a596263196d734268c7a617-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-fb8ce42f18e201df272b8c52066a8f3b-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-01cd9dd8fcd0023b2c4b1dccf8dffc6f-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-a7d667cd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-a7d667cd)
[api-reference/beta/api/security-emailurlthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46654df462fadf080099976150b479d2-a7d667cd)
[api-reference/beta/api/security-emailurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Deta [...]

2022-05-11 11:05 UTC, opbld34 commented
Docs Build status updates of commit _[7ab47dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ab47ddad835c02fee2e062317d9a3136d8f1c90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailcontentthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-73efdffbb83b8766d170b45e29f55a87-48ec6c7a)
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-48ec6c7a)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-48ec6c7a)
[api-reference/beta/api/security-emailcontentthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-a4c091306a596263196d734268c7a617-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-fb8ce42f18e201df272b8c52066a8f3b-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-01cd9dd8fcd0023b2c4b1dccf8dffc6f-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-48ec6c7a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-48ec6c7a)
[api-reference/beta/api/security-emailurlthreatsubmission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46654df462fadf080099976150b479d2-48ec6c7a)
[api-reference/beta/api/security-emailurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Deta [...]

2022-05-12 08:41 UTC, opbld33 commented
Docs Build status updates of commit _[3e9b407](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e9b407d6a7bc9fd16f3dec57e659d3873869c8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-edc5bfae)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-edc5bfae)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-edc5bfae)
[api-reference/beta/api/security-emailurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-ca26b142503f6aa730d8879e8d9bfd37-edc5bfae)
[api-reference/beta/api/security-emailurlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-38b5607b9d24ee62587e5282e8de3b49-edc5bfae)
[api-reference/beta/api/security-filecontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03b4fdd98674989bb5b832f70c1fc6e3-edc5bfae)
[api-reference/beta/api/security-filecontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b845393cdf21cd76738a2ca8d0173d70-edc5bfae)
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-82d9f30ea46c586bdf1d524dae58599c-edc5bfae)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad5 [...]

2022-05-12 08:56 UTC, opbld31 commented
Docs Build status updates of commit _[a6d432d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6d432d8ecd179af94e1c152166b48c922fccb5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailcontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5ca060c32f63b8df9a330d34e712396f-e966d3e7)
[api-reference/beta/api/security-emailcontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailcontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailcontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d936c321d6e70441de032d6d4ac82eb0-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-e966d3e7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-e966d3e7)
[api-reference/beta/api/security-emailurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-ca26b142503f6aa730d8879e8d9bfd37-e966d3e7)
[api-reference/beta/api/security-emailurlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-38b5607b9d24ee62587e5282e8de3b49-e966d3e7)
[api-reference/beta/api/security-filecontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03b4fdd98674989bb5b832f70c1fc6e3-e966d3e7)
[api-reference/beta/api/security-filecontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b845393cdf21cd76738a2ca8d0173d70-e966d3e7)
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-82d9f30ea46c586bdf1d524dae58599c-e966d3e7)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad5 [...]

2022-05-12 08:58 UTC, opbld31 commented
Docs Build status updates of commit _[a4a229e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4a229e58017b02ae888ea6930ef02f88e4fd861)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-e575a3e6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-e575a3e6)
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-82d9f30ea46c586bdf1d524dae58599c-e575a3e6)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-e575a3e6)
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-821528efaa0335ed97e73c474442e686-e575a3e6)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-e575a3e6)
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-30cdb74aefb1b0137bed9ae831e97763-e575a3e6)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-e575a3e6)
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f4b38e235e0a3f3af8a04c027015b8ae-e575a3e6)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-e575a3e6)
[api-reference/beta/api/u [...]

2022-05-12 09:01 UTC, opbld34 commented
Docs Build status updates of commit _[77ea8ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77ea8eea25d4acc8ed3e671495b7664b40f3d06f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-b32f5268)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-b32f5268)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-b32f5268)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-b32f5268)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-b32f5268)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-b32f5268)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-b32f5268)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-b32f5268)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-b32f5268)
[api-reference/beta/api/security-emailurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-ca26b142503f6aa730d8879e8d9bfd37-b32f5268)
[api-reference/beta/api/security-emailurlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailurlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailurlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-38b5607b9d24ee62587e5282e8de3b49-b32f5268)
[api-reference/beta/api/security-filecontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03b4fdd98674989bb5b832f70c1fc6e3-b32f5268)
[api-reference/beta/api/security-filecontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b845393cdf21cd76738a2ca8d0173d70-b32f5268)
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-82d9f30ea46c586bdf1d524dae58599c-b32f5268)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-b32f5268)
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-821528efaa0335ed97e73c474442e686-b32f5268)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008 [...]

2022-05-12 09:03 UTC, opbld34 commented
Docs Build status updates of commit _[99466d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99466d8dd289ca9431ed398f24a4f2dde27c6b01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-ae6fcc1b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-ae6fcc1b)
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-82d9f30ea46c586bdf1d524dae58599c-ae6fcc1b)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-ae6fcc1b)
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-821528efaa0335ed97e73c474442e686-ae6fcc1b)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-ae6fcc1b)
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-30cdb74aefb1b0137bed9ae831e97763-ae6fcc1b)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-ae6fcc1b)
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f4b38e235e0a3f3af8a04c027015b8ae-ae6fcc1b)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-ae6fcc1b)
[api-reference/beta/resou [...]

2022-05-12 09:05 UTC, opbld33 commented
Docs Build status updates of commit _[ff76be4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff76be48ba03d29f3bada86b67d9ba282ff57271)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-240b2d387a2e9e9eb8f36c844d4a8b4a-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-45c5824d7c0f28ebc3334a91109ae08d-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-175641d8fb4914fec0838408474cb4a6-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-1a0d68854d8bbe76dc03c68d86641555-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-68e7f2b5)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-68e7f2b5)
[api-reference/beta/api/security-filecontentthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03b4fdd98674989bb5b832f70c1fc6e3-68e7f2b5)
[api-reference/beta/api/security-filecontentthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filecontentthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filecontentthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b845393cdf21cd76738a2ca8d0173d70-68e7f2b5)
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-82d9f30ea46c586bdf1d524dae58599c-68e7f2b5)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-68e7f2b5)
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-821528efaa0335ed97e73c474442e686-68e7f2b5)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-68e7f2b5)
[api-reference/beta/api/security-fileurlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-fileurlthreatsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-fileurlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-280b20144d37b1afc6c757e8666a7e00-68e7f2b5)
[api-reference/beta/api/security-fileurlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-fileurlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-fileurlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8a3c63cd15d2bccb6797006d4527e313-68e7f [...]

2022-05-12 09:21 UTC, opbld33 commented
Docs Build status updates of commit _[8faddab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8faddab3d59b5744455e4d85ba71625455550c4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-d446eb1a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-d446eb1a)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-d446eb1a)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-d446eb1a)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-d446eb1a)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-d446eb1a)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-d446eb1a)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-d446eb1a)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-d446eb1a)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-d446eb1a)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-d446eb1a)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-d446eb1a)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-d446eb1a)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-d446eb1a)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-d446eb1a)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-d446eb1a)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-d446eb1a)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filet [...]

2022-05-12 10:25 UTC, opbld32 commented
Docs Build status updates of commit _[69249f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69249f39fe13566906ced256e0e9f4c5966ee6f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-8ced30c6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-8ced30c6)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-8ced30c6)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-8ced30c6)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-8ced30c6)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-8ced30c6)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-8ced30c6)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-8ced30c6)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-8ced30c6)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-8ced30c6)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-8ced30c6)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-8ced30c6)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-8ced30c6)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-8ced30c6)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-8ced30c6)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-8ced30c6)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-8ced30c6)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:33 UTC, opbld33 commented
Docs Build status updates of commit _[69b98e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69b98e8ca0218ff5cdc1a46175958f967bf054dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-d67a2a28)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-d67a2a28)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-d67a2a28)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-d67a2a28)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-d67a2a28)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-d67a2a28)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-d67a2a28)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-d67a2a28)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-d67a2a28)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-d67a2a28)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-d67a2a28)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-d67a2a28)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-d67a2a28)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-d67a2a28)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-d67a2a28)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-d67a2a28)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-d67a2a28)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:35 UTC, opbld33 commented
Docs Build status updates of commit _[af103c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af103c55d5d05c6213250ec2bdcd0532c174c868)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-f3b3d9e8)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-f3b3d9e8)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-f3b3d9e8)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-f3b3d9e8)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-f3b3d9e8)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-f3b3d9e8)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-f3b3d9e8)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-f3b3d9e8)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-f3b3d9e8)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-f3b3d9e8)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-f3b3d9e8)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-f3b3d9e8)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-f3b3d9e8)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-f3b3d9e8)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-f3b3d9e8)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-f3b3d9e8)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-f3b3d9e8)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:37 UTC, opbld33 commented
Docs Build status updates of commit _[6b15c49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b15c491169f39eba2aee1163db5b5b429993a59)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-72451e36)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-72451e36)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-72451e36)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-72451e36)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-72451e36)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-72451e36)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-72451e36)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-72451e36)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-72451e36)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-72451e36)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-72451e36)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-72451e36)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-72451e36)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-72451e36)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-72451e36)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-72451e36)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-72451e36)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:39 UTC, opbld34 commented
Docs Build status updates of commit _[ab215fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab215fa37cfb32a2ae8e5f9ac7b70fed339374f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-5794b0cd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-5794b0cd)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-5794b0cd)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-5794b0cd)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-5794b0cd)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-5794b0cd)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-5794b0cd)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-5794b0cd)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-5794b0cd)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-5794b0cd)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-5794b0cd)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-5794b0cd)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-5794b0cd)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-5794b0cd)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-5794b0cd)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-5794b0cd)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-5794b0cd)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:49 UTC, opbld32 commented
Docs Build status updates of commit _[e7e08e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7e08e682ec960676123c33e6f75024dd9ece85a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-a9cc03f2)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-a9cc03f2)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-a9cc03f2)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-a9cc03f2)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-a9cc03f2)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-a9cc03f2)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-a9cc03f2)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-a9cc03f2)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-a9cc03f2)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-a9cc03f2)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-a9cc03f2)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-a9cc03f2)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-a9cc03f2)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-a9cc03f2)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-a9cc03f2)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-a9cc03f2)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-a9cc03f2)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:54 UTC, opbld32 commented
Docs Build status updates of commit _[9c081ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c081ac83518ac3b97ce54609c1e2393bdc500ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-be498c9b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-be498c9b)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-be498c9b)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-be498c9b)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-be498c9b)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-be498c9b)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-be498c9b)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-be498c9b)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-be498c9b)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-be498c9b)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-be498c9b)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-be498c9b)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-be498c9b)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-be498c9b)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-be498c9b)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-be498c9b)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-be498c9b)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:56 UTC, opbld30 commented
Docs Build status updates of commit _[0bd43dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bd43ddfdddf5e45abb0aae6f7b555b875c2dabf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-ebc2af1d)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-ebc2af1d)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-ebc2af1d)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-ebc2af1d)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-ebc2af1d)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-ebc2af1d)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-ebc2af1d)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-ebc2af1d)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-ebc2af1d)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-ebc2af1d)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-ebc2af1d)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-ebc2af1d)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-ebc2af1d)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-ebc2af1d)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-ebc2af1d)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-ebc2af1d)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-ebc2af1d)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 10:58 UTC, opbld31 commented
Docs Build status updates of commit _[f3b47b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3b47b650f59c89d176e03ffae91522a25c908c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-8941d094)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-8941d094)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-8941d094)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-8941d094)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-8941d094)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-8941d094)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-8941d094)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-8941d094)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-8941d094)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-8941d094)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-8941d094)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-8941d094)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-8941d094)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-8941d094)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-8941d094)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-8941d094)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-8941d094)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 11:00 UTC, opbld34 commented
Docs Build status updates of commit _[8f4cfbc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f4cfbc7ee64b475c445610fe61ca208e2f0e03d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-a85f33dd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-a85f33dd)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-a85f33dd)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-a85f33dd)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-a85f33dd)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-a85f33dd)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-a85f33dd)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-a85f33dd)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-a85f33dd)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-a85f33dd)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-a85f33dd)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-a85f33dd)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-a85f33dd)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-a85f33dd)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-a85f33dd)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-a85f33dd)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-a85f33dd)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 11:03 UTC, opbld31 commented
Docs Build status updates of commit _[14361e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14361e17fe4d782c2a82292912af9c7070c565c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-c289175e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-c289175e)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-c289175e)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-c289175e)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-c289175e)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-c289175e)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-c289175e)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-c289175e)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-c289175e)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-c289175e)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-c289175e)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-c289175e)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-c289175e)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-c289175e)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-c289175e)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-c289175e)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-c289175e)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 11:05 UTC, opbld33 commented
Docs Build status updates of commit _[3019b62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3019b6212982ea7ef8e11d91ee28048ed1f163ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-2041c604)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-2041c604)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-2041c604)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-2041c604)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-2041c604)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-2041c604)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-2041c604)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-2041c604)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-2041c604)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-2041c604)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-2041c604)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-2041c604)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-2041c604)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-2041c604)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-2041c604)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-2041c604)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-2041c604)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-12 11:08 UTC, opbld33 commented
Docs Build status updates of commit _[a1373b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1373b63ee3046f59781ef78603ff7bf38f48ba4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-e0425c68)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e0425c68)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-e0425c68)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-e0425c68)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-e0425c68)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-e0425c68)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-e0425c68)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-e0425c68)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-e0425c68)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-e0425c68)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-e0425c68)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-e0425c68)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-e0425c68)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-e0425c68)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-e0425c68)
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-2a3473c57d76327931ac0eedcb783cfd-e0425c68)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-e0425c68)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [V [...]

2022-05-13 08:43 UTC, opbld31 commented
Docs Build status updates of commit _[4d55acc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d55acca44934e303c3e007afbc64b097f6518a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-a033a5bd)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-a033a5bd)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-a033a5bd)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-a033a5bd)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-a033a5bd)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-a033a5bd)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-a033a5bd)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-a033a5bd)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-a033a5bd)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-a033a5bd)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-a033a5bd)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-a033a5bd)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-a033a5bd)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-a033a5bd)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-a033a5bd)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-a033a5bd)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-a033a5bd)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 08:46 UTC, opbld30 commented
Docs Build status updates of commit _[4355905](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43559053b8b8727f5899c446c1b8667d7397554c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-de9750e7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-de9750e7)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-de9750e7)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-de9750e7)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-de9750e7)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-de9750e7)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-de9750e7)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-de9750e7)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-de9750e7)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-de9750e7)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-de9750e7)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-de9750e7)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-de9750e7)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-de9750e7)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-de9750e7)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-de9750e7)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-de9750e7)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 08:49 UTC, opbld32 commented
Docs Build status updates of commit _[64ee65c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64ee65c7c2985122b944bcf4195ae9cc52c01017)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-d00e261f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-d00e261f)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-d00e261f)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-d00e261f)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-d00e261f)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-d00e261f)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-d00e261f)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-d00e261f)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-d00e261f)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-d00e261f)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-d00e261f)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-d00e261f)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-d00e261f)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-d00e261f)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-d00e261f)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-d00e261f)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-d00e261f)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 08:51 UTC, opbld34 commented
Docs Build status updates of commit _[85c3f94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85c3f940c74ed8519ab8d79afbedb86e490f3992)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-b6894b00)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-b6894b00)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-b6894b00)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-b6894b00)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-b6894b00)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-b6894b00)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-b6894b00)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-b6894b00)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-b6894b00)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-b6894b00)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-b6894b00)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-b6894b00)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-b6894b00)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-b6894b00)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-b6894b00)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-b6894b00)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-b6894b00)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 08:53 UTC, opbld34 commented
Docs Build status updates of commit _[69f928e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69f928e0519e203824226e65849f6d578cc97c3c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-35a43825)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-35a43825)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-35a43825)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-35a43825)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-35a43825)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-35a43825)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-35a43825)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-35a43825)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-35a43825)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-35a43825)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-35a43825)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-35a43825)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-35a43825)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-35a43825)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-35a43825)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-35a43825)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-35a43825)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 08:55 UTC, opbld34 commented
Docs Build status updates of commit _[87f87be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87f87be9997caaca636bb9e4311a8f74770078ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-82dba274)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-82dba274)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-82dba274)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-82dba274)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-82dba274)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-82dba274)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-82dba274)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-82dba274)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-82dba274)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-82dba274)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-82dba274)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-82dba274)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-82dba274)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-82dba274)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-82dba274)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-82dba274)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-82dba274)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 08:58 UTC, opbld33 commented
Docs Build status updates of commit _[bf3c16d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf3c16df0ca07237f7d91b8391c74f58708fdbb1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-c8c00b35)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-c8c00b35)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-c8c00b35)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-c8c00b35)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-c8c00b35)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-c8c00b35)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-c8c00b35)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-c8c00b35)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-c8c00b35)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-c8c00b35)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-c8c00b35)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-c8c00b35)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-c8c00b35)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-c8c00b35)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-c8c00b35)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-c8c00b35)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-c8c00b35)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 09:04 UTC, opbld34 commented
Docs Build status updates of commit _[4369664](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4369664910876c38869bdc6ead71395a6dce3a4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-7631dc51)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-7631dc51)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-7631dc51)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-7631dc51)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-7631dc51)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-7631dc51)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-7631dc51)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-7631dc51)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-7631dc51)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-7631dc51)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-7631dc51)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-7631dc51)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-7631dc51)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-7631dc51)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-7631dc51)
[api-reference/beta/api/security-filethreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-aa4d37e02b9545615b9f3aef87473008-7631dc51)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-7631dc51)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 09:06 UTC, opbld32 commented
Docs Build status updates of commit _[a02e122](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a02e1228ff19c019e3c81c9b02d9bcad39f7a0ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-26f9faa4)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-26f9faa4)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-26f9faa4)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-26f9faa4)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-26f9faa4)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-26f9faa4)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-26f9faa4)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-26f9faa4)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-26f9faa4)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-26f9faa4)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-26f9faa4)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-26f9faa4)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-26f9faa4)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-26f9faa4)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-26f9faa4)
[api-reference/beta/api/security-urlthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-review.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-21bcb603b4f3bd8d74fdff272268e00a-26f9faa4)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03f7435741ed6646e45e02bda8bd705e-26f9faa4)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View [...]

2022-05-13 09:13 UTC, opbld31 commented
Docs Build status updates of commit _[19e8678](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19e86784eb3cfb75a121432aa0b51fa7a4f04333)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-b88e7b8a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-b88e7b8a)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-b88e7b8a)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-b88e7b8a)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-b88e7b8a)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-b88e7b8a)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-b88e7b8a)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-b88e7b8a)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-b88e7b8a)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-b88e7b8a)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-b88e7b8a)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-b88e7b8a)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-b88e7b8a)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-b88e7b8a)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-b88e7b8a)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03f7435741ed6646e45e02bda8bd705e-b88e7b8a)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-b88e7b8a)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestio [...]

2022-05-13 09:19 UTC, opbld32 commented
Docs Build status updates of commit _[e6cd0a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6cd0a7d7027edf92b285f3545cf39f94af6cd79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-40f0cf84)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-40f0cf84)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-40f0cf84)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-40f0cf84)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-40f0cf84)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-40f0cf84)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-40f0cf84)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-40f0cf84)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-40f0cf84)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-40f0cf84)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-40f0cf84)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-40f0cf84)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-40f0cf84)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-40f0cf84)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-40f0cf84)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03f7435741ed6646e45e02bda8bd705e-40f0cf84)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-40f0cf84)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestio [...]

2022-05-13 09:21 UTC, opbld34 commented
Docs Build status updates of commit _[1a4ee4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a4ee4bec8d21d88b1e77b4d75f1f3c6173d4a59)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-8d86f1ca)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-8d86f1ca)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-8d86f1ca)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-8d86f1ca)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-8d86f1ca)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-8d86f1ca)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-8d86f1ca)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-8d86f1ca)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-8d86f1ca)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-8d86f1ca)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-8d86f1ca)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-8d86f1ca)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-8d86f1ca)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-8d86f1ca)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-8d86f1ca)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03f7435741ed6646e45e02bda8bd705e-8d86f1ca)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-8d86f1ca)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestio [...]

2022-05-13 09:23 UTC, opbld30 commented
Docs Build status updates of commit _[08b2465](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08b2465d554ba19a772fb65ce57e00d16b3c380b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-b36122d6)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-b36122d6)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-b36122d6)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-b36122d6)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-b36122d6)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-b36122d6)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-b36122d6)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-b36122d6)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-b36122d6)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-b36122d6)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-b36122d6)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-b36122d6)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-b36122d6)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-b36122d6)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-b36122d6)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-b36122d6)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-b36122d6)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [V [...]

2022-05-13 09:34 UTC, opbld33 commented
Docs Build status updates of commit _[5834cc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5834cc7ceaab983d9367f197db8e53a2586020d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-adca1794)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-adca1794)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-adca1794)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-adca1794)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-adca1794)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-adca1794)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-adca1794)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-adca1794)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-adca1794)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-adca1794)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-adca1794)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-adca1794)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-adca1794)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-adca1794)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-adca1794)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-adca1794)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-adca1794)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 09:37 UTC, opbld33 commented
Docs Build status updates of commit _[c2fd821](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2fd82105c3ee9db48426997a42c680f7c2ba9e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-62e7ee83)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-62e7ee83)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-62e7ee83)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-62e7ee83)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-62e7ee83)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-62e7ee83)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-62e7ee83)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-62e7ee83)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-62e7ee83)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-62e7ee83)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-62e7ee83)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-62e7ee83)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-62e7ee83)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-62e7ee83)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-62e7ee83)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-62e7ee83)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-62e7ee83)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Sugges [...]

2022-05-13 09:39 UTC, opbld33 commented
Docs Build status updates of commit _[d1d8e76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1d8e76a341c054c062c1a6108b5f785dc0fae82)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-89ffc049)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-89ffc049)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-89ffc049)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-89ffc049)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-89ffc049)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-89ffc049)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-89ffc049)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-89ffc049)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-89ffc049)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-89ffc049)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-89ffc049)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-89ffc049)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-89ffc049)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-89ffc049)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-89ffc049)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-89ffc049)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-89ffc049)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 09:50 UTC, opbld31 commented
Docs Build status updates of commit _[faa3d27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/faa3d273a8782d4511cc3d702da84b2d8c2313d5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-402dd6c3)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-402dd6c3)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-402dd6c3)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-402dd6c3)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-402dd6c3)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-402dd6c3)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-402dd6c3)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-402dd6c3)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-402dd6c3)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-402dd6c3)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-402dd6c3)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-402dd6c3)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-402dd6c3)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-402dd6c3)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-402dd6c3)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-402dd6c3)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-402dd6c3)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded [...]

2022-05-13 09:52 UTC, opbld30 commented
Docs Build status updates of commit _[4d81f10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d81f105ccaf23aa5cc84fa2498672307bdb3595)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-149bec7f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-149bec7f)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-149bec7f)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-149bec7f)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-149bec7f)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-149bec7f)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-149bec7f)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-149bec7f)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-149bec7f)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-149bec7f)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-149bec7f)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-149bec7f)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-r [...]

2022-05-13 09:54 UTC, opbld30 commented
Docs Build status updates of commit _[7f39ac1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f39ac19faaefa1e82a4840fabee613f1b393aa4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-fa97b98a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-fa97b98a)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-fa97b98a)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-fa97b98a)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-fa97b98a)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-fa97b98a)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-fa97b98a)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-fa97b98a)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-fa97b98a)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-fa97b98a)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-fa97b98a)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-fa97b98a)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-fa97b98a)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[ap [...]

2022-05-13 09:56 UTC, opbld31 commented
Docs Build status updates of commit _[e2d84a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2d84a10d60000489356b39a9773b44e1a81059f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-2111b624)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-2111b624)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-2111b624)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-2111b624)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-2111b624)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-2111b624)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-2111b624)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-2111b624)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-2111b624)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-2111b624)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-2111b624)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-2111b624)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-2111b624)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-2111b624)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-2111b624)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-2111b624)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-2111b624)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 09:58 UTC, opbld34 commented
Docs Build status updates of commit _[cb44c5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb44c5ade94df301b4205d4aab4fb2fe930062b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-749b4089)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-749b4089)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-749b4089)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-749b4089)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-749b4089)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-749b4089)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-749b4089)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-749b4089)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-749b4089)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-749b4089)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-749b4089)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-749b4089)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-749b4089)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-749b4089)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-749b4089)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-749b4089)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-749b4089)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](h [...]

2022-05-13 10:00 UTC, opbld33 commented
Docs Build status updates of commit _[ca081a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca081a8c49afa3e668111a012978a88da16191f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-17c56b03)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-17c56b03)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-17c56b03)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-17c56b03)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-17c56b03)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-17c56b03)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-17c56b03)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-17c56b03)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-17c56b03)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-17c56b03)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-17c56b03)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-17c56b03)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-17c56b03)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-17c56b03)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-17c56b03)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-17c56b03)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-17c56b03)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded [...]

2022-05-13 10:02 UTC, opbld30 commented
Docs Build status updates of commit _[3d5c2a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d5c2a353655ee23426c517bcdb3d03d4dea3844)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-78f4e329)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-78f4e329)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-78f4e329)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-78f4e329)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-78f4e329)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-78f4e329)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-78f4e329)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-78f4e329)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-78f4e329)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-78f4e329)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-78f4e329)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmi [...]

2022-05-13 10:05 UTC, opbld34 commented
Docs Build status updates of commit _[7d43d5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d43d5b3bd785aa90a6cf78897ce4fc7940fa40e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-56e6cfb3)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-56e6cfb3)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-56e6cfb3)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-56e6cfb3)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-56e6cfb3)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-56e6cfb3)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-56e6cfb3)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-56e6cfb3)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-56e6cfb3)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-56e6cfb3)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:07 UTC, opbld34 commented
Docs Build status updates of commit _[7a0902a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a0902aac0cb2588886a176880323952bbc67d54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-4b922434)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-4b922434)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-4b922434)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-4b922434)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-4b922434)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-4b922434)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-4b922434)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-4b922434)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-4b922434)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-4b922434)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:09 UTC, opbld30 commented
Docs Build status updates of commit _[2094d2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2094d2f64d115374d95df5bc1145342cfa83ecf1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-7f07ff5e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-7f07ff5e)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-7f07ff5e)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-7f07ff5e)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-7f07ff5e)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-7f07ff5e)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-7f07ff5e)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-7f07ff5e)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-7f07ff5e)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-7f07ff5e)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:11 UTC, opbld34 commented
Docs Build status updates of commit _[073c23d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/073c23d1bafea8bc91b429c832f8d7823432db36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-bf480d40)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-bf480d40)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-bf480d40)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-bf480d40)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-bf480d40)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-bf480d40)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-bf480d40)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-bf480d40)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-bf480d40)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-bf480d40)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-bf480d40)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-bf480d40)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-bf480d40)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-bf480d40)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-bf480d40)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission [...]

2022-05-13 10:14 UTC, opbld30 commented
Docs Build status updates of commit _[1a63063](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a63063021f8da1e6ae0674a473692327c37b9b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-61983ed2)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-61983ed2)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-61983ed2)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-61983ed2)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-61983ed2)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-61983ed2)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-61983ed2)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-61983ed2)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-61983ed2)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-61983ed2)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:16 UTC, opbld32 commented
Docs Build status updates of commit _[191db66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/191db6620f2ed968f121a7f1d35fa343f6730f1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-20fd45f8)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-20fd45f8)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-20fd45f8)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-20fd45f8)
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7a06a077be730e0dbf7444dd2a2ed623-20fd45f8)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-20fd45f8)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-20fd45f8)
[api-reference/beta/resources/security-emailurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-3de2c6554f833090995df18364c6fcd3-20fd45f8)
[api-reference/beta/resources/security-filecontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filecontentthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filecontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-97ba45071fbf52414d10964c699042c8-20fd45f8)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-20fd45f8)
[api-reference/beta/resources/security-fileurlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileurlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileurlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b7b608d99dd9e424ccc2c909a01cd983-20fd45f8)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-20fd45f8)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-20fd45f8)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-20fd45f8)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-20fd45f8)
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-03f7435741ed6646e45e02bda8bd705e-20fd45f8)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-20fd45f8)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestio [...]

2022-05-13 10:20 UTC, opbld33 commented
Docs Build status updates of commit _[3b32050](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b3205002c511bd0d916ba85c1c1b46cd15dc6b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-addc17c7)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-addc17c7)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-addc17c7)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-addc17c7)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-addc17c7)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-addc17c7)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-addc17c7)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-addc17c7)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-addc17c7)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-addc17c7)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-addc17c7)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-addc17c7)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-addc17c7)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-addc17c7)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en- [...]

2022-05-13 10:22 UTC, opbld31 commented
Docs Build status updates of commit _[580dc1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/580dc1aed06bd1cb6d472acc7b80a89d24b9f99b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-04de5949)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-04de5949)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-04de5949)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-04de5949)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-04de5949)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-04de5949)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-04de5949)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-04de5949)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-04de5949)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-04de5949)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:24 UTC, opbld32 commented
Docs Build status updates of commit _[a01f5e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a01f5e8e831fe633005b253334f1ffbb273c7040)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-ffe984fc)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-ffe984fc)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-ffe984fc)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-ffe984fc)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-ffe984fc)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-ffe984fc)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-ffe984fc)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-ffe984fc)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-ffe984fc)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-ffe984fc)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-ffe984fc)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-ffe984fc)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-ffe984fc)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[ap [...]

2022-05-13 10:26 UTC, opbld34 commented
Docs Build status updates of commit _[d3c3a86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3c3a86c2baed1dd396fea9393861b8f345fb441)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-e23bbb82)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e23bbb82)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-e23bbb82)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-e23bbb82)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-e23bbb82)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-e23bbb82)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-e23bbb82)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-e23bbb82)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-e23bbb82)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-e23bbb82)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:28 UTC, opbld31 commented
Docs Build status updates of commit _[83f041e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83f041e3643afb5892d56ce3f642da323c56f0ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-b1cbfa6f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-b1cbfa6f)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-b1cbfa6f)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-b1cbfa6f)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-b1cbfa6f)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-b1cbfa6f)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-b1cbfa6f)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-b1cbfa6f)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-b1cbfa6f)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-b1cbfa6f)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:30 UTC, opbld32 commented
Docs Build status updates of commit _[769d768](https://github.com/microsoftgraph/microsoft-graph-docs/commits/769d768d568dfe97bdc3bdf34902cbbdc4870366)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-fecf4a41)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-fecf4a41)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-fecf4a41)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-fecf4a41)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-fecf4a41)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-fecf4a41)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-fecf4a41)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-fecf4a41)
[api-reference/beta/resources/security-threatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-threatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-threatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-b92f237ec4bb9493354b37f04177b179-fecf4a41)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-fecf4a41)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-fecf4a41)
[api-reference/beta/resources/security-submissionadminreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionadminreview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionadminreview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-dbd3176128b880a32557f0c9c7dc0b85-fecf4a41)
[api-reference/beta/resources/security-submissiondetectedfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissiondetectedfile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissiondetectedfile?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-e9da9882327d4c325879749af0156d65-fecf4a41)
[api-reference/beta/resources/security-submissionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-00429404358275c9ae465644991d54d5-fecf4a41)
[api-reference/beta/resources/security-tenantallowblocklistentryresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantallowblocklistentryresult.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantallowblocklistentryresult?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-8d741896468e4a69081d4f1ef96c10dc-fecf4a41)
[api-reference/beta/resources/security-tenantalloworblocklistaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-tenantalloworblocklistaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-tenantalloworblocklistaction?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-096d88ef9621b52652747d3a00864d20-fecf4a41)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ [...]

2022-05-13 10:36 UTC, opbld32 commented
Docs Build status updates of commit _[a838b45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a838b455828988bf2a72653eacb77160b0a422eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-e308482c)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e308482c)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-e308482c)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-e308482c)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-e308482c)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-e308482c)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-e308482c)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-e308482c)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-e308482c)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-e308482c)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:38 UTC, opbld31 commented
Docs Build status updates of commit _[3109fc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3109fc9eca42c174696f289e36ff026047f8ba5a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-8cab7a64)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-8cab7a64)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-8cab7a64)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-8cab7a64)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-8cab7a64)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-8cab7a64)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-8cab7a64)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-8cab7a64)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-8cab7a64)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-8cab7a64)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:41 UTC, opbld31 commented
Docs Build status updates of commit _[2d90757](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d90757382c7a27042cdd3c15dca5fe396c0b029)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-8025126f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-8025126f)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-8025126f)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-8025126f)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-8025126f)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-8025126f)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-8025126f)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-8025126f)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-8025126f)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-8025126f)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:43 UTC, opbld30 commented
Docs Build status updates of commit _[c1766aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1766aa22e86f7ccb84b8903029a75784ba9d26a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-f123e6a3)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-f123e6a3)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-f123e6a3)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-f123e6a3)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-f123e6a3)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-f123e6a3)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-f123e6a3)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-f123e6a3)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-f123e6a3)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-f123e6a3)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:51 UTC, opbld31 commented
Docs Build status updates of commit _[96162ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96162edd7de16e1732982093002f8e3a93e68af2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-d7bb1964)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-d7bb1964)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-d7bb1964)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-d7bb1964)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-d7bb1964)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-d7bb1964)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-d7bb1964)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-d7bb1964)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-d7bb1964)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-d7bb1964)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:53 UTC, opbld34 commented
Docs Build status updates of commit _[c3c0f0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3c0f0dcaf2051e446b085536054ac95a322a93b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-4588b9ae)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-4588b9ae)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-4588b9ae)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-4588b9ae)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-4588b9ae)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-4588b9ae)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-4588b9ae)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-4588b9ae)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-4588b9ae)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-4588b9ae)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:55 UTC, opbld34 commented
Docs Build status updates of commit _[8844825](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8844825fb34735a5865736da2bae1ecbefcb7600)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-9f878ce9)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-9f878ce9)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-9f878ce9)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-9f878ce9)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-9f878ce9)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-9f878ce9)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-9f878ce9)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-9f878ce9)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-9f878ce9)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-9f878ce9)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 10:57 UTC, opbld31 commented
Docs Build status updates of commit _[3e76d64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e76d646fb284a798c20e993396ef6e7ff70bde4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-452dceb9)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-452dceb9)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-452dceb9)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-452dceb9)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-452dceb9)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-452dceb9)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-452dceb9)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-452dceb9)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-452dceb9)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-452dceb9)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 11:08 UTC, opbld33 commented
Docs Build status updates of commit _[bf2ce2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf2ce2a5960078e408a8eb9fed2184bf38ff036e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-ab67d269)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-ab67d269)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-ab67d269)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-ab67d269)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-ab67d269)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-ab67d269)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-ab67d269)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-ab67d269)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-ab67d269)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-ab67d269)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 11:10 UTC, opbld30 commented
Docs Build status updates of commit _[74ecf87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74ecf87e533332840471efcb3be165290c4b0d83)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-769020bdb2292bd8dfdb73c3a6b9f7b9-4dbd3916)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-4dbd3916)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-4dbd3916)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-4dbd3916)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-4dbd3916)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-4dbd3916)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-4dbd3916)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-4dbd3916)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-4dbd3916)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-4dbd3916)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsof [...]

2022-05-13 11:14 UTC, opbld32 commented
Docs Build status updates of commit _[35c8602](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35c86021d395aceaa0bc83b0f029bb7379ef8d1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5a83e7a490f181980d758cc48207c77b-e1174207)
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-e1174207)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-e1174207)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-e1174207)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-e1174207)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-e1174207)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-e1174207)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-e1174207)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-e1174207)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta [...]

2022-05-13 11:24 UTC, opbld31 commented
Docs Build status updates of commit _[3fd06c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fd06c7ab0b4537ba3f8f202f8e402751bfb0a2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9f4a40f8897dcb124088811403ad51eb-e93ca1c7)
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-e93ca1c7)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-e93ca1c7)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-e93ca1c7)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-e93ca1c7)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-e93ca1c7)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-e93ca1c7)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-e93ca1c7)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md)  [...]

2022-05-13 11:26 UTC, opbld32 commented
Docs Build status updates of commit _[aea9a8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aea9a8d23cfb420d6edeaed33e54c45ff2f01566)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-0932d7e3)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-0932d7e3)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-0932d7e3)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-0932d7e3)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-0932d7e3)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (gra [...]

2022-05-13 11:29 UTC, opbld30 commented
Docs Build status updates of commit _[749fcc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/749fcc9c4859dfa2a50ce49a4eb777553c2488cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-a7c33754)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-a7c33754)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-a7c33754)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-a7c33754)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-a7c33754)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (gra [...]

2022-05-13 11:36 UTC, opbld31 commented
Docs Build status updates of commit _[f8d0d25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8d0d256bf1e2a7d074a94daf47a8b686f21705f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-7fbcf89d)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-7fbcf89d)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-7fbcf89d)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-7fbcf89d)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md [...]

2022-05-13 11:38 UTC, opbld30 commented
Docs Build status updates of commit _[33000aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33000aaeb84ffc8fe1ffe86e65278a40630a414b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-7cc8a623)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-7cc8a623)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-7cc8a623)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security [...]

2022-05-13 11:40 UTC, opbld32 commented
Docs Build status updates of commit _[5b29320](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b293209c1d41f73b0260227b8c3effb9923ddcc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-46659cb89d0950bfe3b5907185b79a63-a3e72542)
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-a3e72542)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-a3e72542)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-a3e72542)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-a3e72542)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-a3e72542)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-a3e72542)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2022-05-13 11:42 UTC, opbld31 commented
Docs Build status updates of commit _[a310ec0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a310ec0c6a5f219ff3533c65607ec3ec5fc2debe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-c6e5d4ccd11dda01ca9aa286c52cbba9-80ab0219)
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmissionpolicy?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-6c4ac0031d229302ac031185ffb30dab-80ab0219)
[api-reference/beta/resources/security-filethreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filethreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filethreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-f8e54351db948397da2f804d976a0546-80ab0219)
[api-reference/beta/resources/security-submissionuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-submissionuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-submissionuseridentity?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-d70fe8e490816e2ce13563be64b7dcd3-80ab0219)
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-80ab0219)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-80ab0219)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-url [...]

2022-05-13 11:44 UTC, opbld33 commented
Docs Build status updates of commit _[3cc84cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3cc84cb716a1530bd86670779e239f1edc292549)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-urlthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-urlthreatsubmission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-urlthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-9c2f3690426f5a3fb2c544e454945ca2-cd7a1f95)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-cd7a1f95)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark: [...]

2022-05-13 11:46 UTC, opbld33 commented
Docs Build status updates of commit _[3981e6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3981e6e0d1cff06740703d4461ec6e10047f147e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-7ae019cbb6cfaba8ee7b76f41fca876b-aeee3b17)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.micr [...]

2022-05-13 11:49 UTC, opbld30 commented
Docs Build status updates of commit _[d63b360](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d63b360c9ecaea48ebd01b70f606354861d2395b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 11:56 UTC, opbld34 commented
Docs Build status updates of commit _[3b3631f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b3631fc55e74972cfb6618f95d98012d27de1e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:05 UTC, opbld34 commented
Docs Build status updates of commit _[05b73e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05b73e1d981d89ac145a4211c417822df1593206)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:18 UTC, opbld30 commented
Docs Build status updates of commit _[9eb939b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9eb939b7ea6a6ccad02341e2e7219f3c541cdd14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:23 UTC, opbld33 commented
Docs Build status updates of commit _[0aa00d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0aa00d3679e76081cfc1c014588078c32301e992)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:25 UTC, opbld31 commented
Docs Build status updates of commit _[d795dcc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d795dcc55aea4274a7146af70a6f32388b159f81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:28 UTC, opbld31 commented
Docs Build status updates of commit _[73fea11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73fea1177675f95f1f05e5d0572b55d0390f8e7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:30 UTC, opbld30 commented
Docs Build status updates of commit _[922d705](https://github.com/microsoftgraph/microsoft-graph-docs/commits/922d7058d736cac7cb4e49abb6b3217969802be5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:32 UTC, opbld30 commented
Docs Build status updates of commit _[abfa73c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abfa73c4fe0f8a0e9c9d6d69bec214e476465319)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:34 UTC, opbld32 commented
Docs Build status updates of commit _[fb5d7b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb5d7b6f35a429daa72169952d52466f9bf3cf1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:45 UTC, opbld32 commented
Docs Build status updates of commit _[d2b6d33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2b6d338ee192119fc7d70ab5799e81fdfb60da3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:47 UTC, opbld33 commented
Docs Build status updates of commit _[297db53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/297db53de9bf689247d4d1b160ec1d492bdce6a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-13 12:50 UTC, opbld30 commented
Docs Build status updates of commit _[7635556](https://github.com/microsoftgraph/microsoft-graph-docs/commits/763555655973443fad1ce38cdced8562bba788c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:32 UTC, opbld34 commented
Docs Build status updates of commit _[3ffa0c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ffa0c6b1c6fb51e4a854cda3ad7a5034374e326)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:34 UTC, opbld32 commented
Docs Build status updates of commit _[347905d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/347905d42a8b2f4de4a3b5af3d9bd268ea40416d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:36 UTC, opbld32 commented
Docs Build status updates of commit _[11f48e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11f48e5d088ba9694ceb1188f14900d96f0f0269)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:38 UTC, opbld32 commented
Docs Build status updates of commit _[414c255](https://github.com/microsoftgraph/microsoft-graph-docs/commits/414c255d1add276ba435de4f3936fe2f3eb2a51c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:49 UTC, opbld31 commented
Docs Build status updates of commit _[7245af9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7245af945f152f9421db753712d62c085ec0b1d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:51 UTC, opbld32 commented
Docs Build status updates of commit _[c1786ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1786ae96697d1b32ff1bdf8821617a0a1744804)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:53 UTC, opbld33 commented
Docs Build status updates of commit _[7c1dd0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c1dd0a289bec08c0f7f6b457cd370c374c7c182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:55 UTC, opbld31 commented
Docs Build status updates of commit _[41cd22a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41cd22acdae32bd83a5d9f77d64b3ac722ce101c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:57 UTC, opbld30 commented
Docs Build status updates of commit _[e8f19e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8f19e01304dd46a7986c71c31ab98554f653c71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 06:59 UTC, opbld34 commented
Docs Build status updates of commit _[10cf305](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10cf30599920a9ba0c12f1c853e6e2a8b9349b27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-16 07:01 UTC, opbld32 commented
Docs Build status updates of commit _[a02c73d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a02c73d84e5112606b73035ad68a702299342ee4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-18 20:27 UTC, opbld34 commented
Docs Build status updates of commit _[fc10c95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc10c95be52e914e1e91105eab2f928b03918533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-18 20:41 UTC, millicentachieng commented on api-reference/beta/resources/security.md
> +|threatSubmission|[threatSubmissionRoot](../resources/security-threatsubmission.md)|Threat submission sent to Microsoft which could be suspicious email threat, url threat, file threat etc.|
```suggestion
|threatSubmission|[threatSubmission](../resources/security-threatsubmission.md)|Threat submission sent to Microsoft which could be suspicious email threat, url threat, file threat etc.|
```
From the definition in the `../resources/security-threatsubmission.md` file, the name of the type should be `threatSubmission` and not `threatSubmissionRoot`.

2022-05-18 20:43 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +description: "email threat submission policy"
Description in line 3 (and 16):
1. Usually, these description match. 
2. This description is used by search engines to display results, so put yourself in the shoes of someone performing a search and needs this topic as result. 
3. Preferably, start with a verb in present tense: Represents, Indicates.

A suggestion in this case:
Represents the guidelines to report potential threads and spam in Microsoft Outlook for an organization.

2022-05-18 20:44 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +## Properties
Please do not add additional columns to the Properties table. These reference topics follow a template for consistency. In this case, please remove the Key and Required columns.

2022-05-18 20:48 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +## Properties
In addition, please list properties in alphabetical order.

2022-05-18 20:54 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +description: "threat submission base type"
Lines 3 and 16: Please add a description.

2022-05-18 20:54 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +## Properties
Apply to all docs in this PR.

2022-05-18 20:56 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +description: "email threat submission policy"
Please improve the description in all topics in this PR.

2022-05-18 21:05 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +title: "emailThreatSubmission: review"
Title in line 2 and 10, and file name: According to the CSDL, the binding parameter name is threadSubmission, please remove the "email" word at the front.

2022-05-18 21:06 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +
Missing: topic for threatSubmissionRoot entity.

2022-05-18 21:10 UTC, opbld30 commented
Docs Build status updates of commit _[16ae16e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16ae16e51ab9749c73ace527b5c00d5c3c88e02a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-19 01:40 UTC, isvargasmsft commented on changelog/Microsoft.Security.Submission.json
> +          "ApiChange": "EntityContainer",
Was this changelog generated or manually updated? 

If this was manually updated, please follow the guidance for changelog entries here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

The values in ApiChange are not complaint.

2022-05-20 03:12 UTC, caigen commented on changelog/Microsoft.Security.Submission.json
> +          "ApiChange": "EntityContainer",
This changelog is generated by graph pipeline. The unhidden PR is https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/6064226.
I removed some other workload related stud docs.

2022-05-20 03:16 UTC, opbld30 commented
Docs Build status updates of commit _[cd75195](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd751951b2fc0bb753f1bdf892688add8bfae9eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-20 03:28 UTC, opbld31 commented
Docs Build status updates of commit _[408bc48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/408bc4876b3a9f04b83d8be68fb6a97a4952ce66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 08:54 UTC, opbld31 commented
Docs Build status updates of commit _[c1aebc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1aebc807da6012105076afe72b2ec3ce07aa565)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 08:57 UTC, opbld30 commented
Docs Build status updates of commit _[13692bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13692bbe36ddbec6b579d05777f42a83735bd966)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 08:59 UTC, opbld31 commented
Docs Build status updates of commit _[bfe73ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfe73acdb6ad6eaf0c639774a502c3f6c01a7baf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:01 UTC, opbld32 commented
Docs Build status updates of commit _[995b89e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/995b89ed2b5def90af9d02efa291c451c07b67e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:13 UTC, opbld33 commented
Docs Build status updates of commit _[95ba78f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95ba78ff11b2bc9f907a2a6f3354782181386c61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:21 UTC, opbld33 commented
Docs Build status updates of commit _[3c51cd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c51cd5da574a39e09b1e0c40caf01c9e2e4f240)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:23 UTC, opbld34 commented
Docs Build status updates of commit _[b5747fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5747fd8643ffb801e73c1e07bdaba52aa692d8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:26 UTC, opbld31 commented
Docs Build status updates of commit _[4de74da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4de74da958a919219d20d48d00c57749fcc1c4ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:29 UTC, opbld30 commented
Docs Build status updates of commit _[a66203d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a66203d3ca7c98a404bad33152f9a57a1ad57fea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:34 UTC, opbld30 commented
Docs Build status updates of commit _[fc6670a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc6670a5d4f199bd37444702e0f89db75323dd36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:40 UTC, opbld34 commented
Docs Build status updates of commit _[c79df6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c79df6a29feddb1d958adac66fe2cd202a5f8b6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:50 UTC, opbld34 commented
Docs Build status updates of commit _[08ce108](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08ce1084439d953a249d077b698b31fa32f9c96b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:53 UTC, opbld32 commented
Docs Build status updates of commit _[4a11533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a11533b348983ae6a049a4be91f5c6930ee9a19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-25 09:59 UTC, opbld32 commented
Docs Build status updates of commit _[1969e15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1969e15f2a5f0f90a825c4d4638bb51e8c8190c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 06:55 UTC, opbld32 commented
Docs Build status updates of commit _[a79e75b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a79e75bed4e6dcea4084c835f2d4777206513d83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 06:58 UTC, opbld31 commented
Docs Build status updates of commit _[cbe2c29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbe2c29fd9ce43395b819be73f49a819d6675436)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 07:04 UTC, opbld34 commented
Docs Build status updates of commit _[3a07d0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a07d0c1a936ae71da60e9cd98fe43585041d35d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 07:06 UTC, opbld30 commented
Docs Build status updates of commit _[9e8f31d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e8f31d20d2d79a9b60ad0acfcefd16422d73919)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 07:09 UTC, opbld34 commented
Docs Build status updates of commit _[4d2a3e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d2a3e28b3640a0cb3fc87f93f9cbfd5fc8ad544)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 07:12 UTC, opbld34 commented
Docs Build status updates of commit _[4ce22a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ce22a6f308f346773fda1cdb5acf38f054a4d20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-26 07:27 UTC, opbld33 commented
Docs Build status updates of commit _[dc2006e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc2006eebd1e5fedfe12c8e0a2b736af1555af79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 04:19 UTC, opbld30 commented
Docs Build status updates of commit _[5e59eb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e59eb5390f2f6020c62b61e2a110bcb939d256e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 04:27 UTC, opbld33 commented
Docs Build status updates of commit _[922aa8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/922aa8d22697b262523ef688302728e713daa4a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 04:48 UTC, opbld32 commented
Docs Build status updates of commit _[d8d7484](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8d748436bf579e579e7ff109357fd67e507e043)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 04:59 UTC, opbld34 commented
Docs Build status updates of commit _[20e4955](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20e4955cb2285c3da6f3b587f86780ee6c4e85d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:16 UTC, opbld34 commented
Docs Build status updates of commit _[5d657cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d657cddec04c17252f014379982e745e1e41ea5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:24 UTC, opbld30 commented
Docs Build status updates of commit _[4b505fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b505fb5f865c7f568a62b2f4a53ed6ce40d4036)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:35 UTC, opbld33 commented
Docs Build status updates of commit _[6095fa3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6095fa30b840c8afae8a262314ea376acea3b7fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:38 UTC, opbld32 commented
Docs Build status updates of commit _[1f0659b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f0659b5e70050a29d96f794dd7626fd1abf6a36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:48 UTC, opbld32 commented
Docs Build status updates of commit _[0272947](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02729471d0a259906820abf9877079540eceb59e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:52 UTC, opbld34 commented
Docs Build status updates of commit _[b0a6cff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0a6cff3facd5f1046d2a24a2aff3086740ed29e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:54 UTC, opbld32 commented
Docs Build status updates of commit _[7c4be95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c4be95b911d337b023df7ebf8def7bf31849804)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 05:58 UTC, opbld30 commented
Docs Build status updates of commit _[7579cc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7579cc2b5ab105237fc12aa4dac0257156c09df0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 06:01 UTC, opbld31 commented
Docs Build status updates of commit _[631bb73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/631bb7307e359f98ac95cc3bdb0f2d3b7904b588)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 06:14 UTC, opbld30 commented
Docs Build status updates of commit _[d119e84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d119e844fe3c27b84addc7ea9224eed151099fbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 06:17 UTC, opbld33 commented
Docs Build status updates of commit _[557f607](https://github.com/microsoftgraph/microsoft-graph-docs/commits/557f6079468a230c48808d7de652a611de88c779)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 06:28 UTC, opbld31 commented
Docs Build status updates of commit _[8b0ef8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b0ef8ca9d726671bed04e3cf9b13b9ce01e4579)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 16:04 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +Represents email threat submission policy. It is used for customizing your organization's experience and policy when reporting potential threats and spam in Microsoft Outlook.
Description in lines 3 and 16: In general, we avoid using the name of the resource to explain what the resource does. The second sentence in line 16 is actually good.

In addition, this description is used by search engines to display results. so we try to compose in a way someone would search for this resource in a search engine. 

The current description generates questions like:
In which way can I customize the organization's experience using this resource? It kind of implies that the resource has 2 functions: customize the org experience and set the policy for reporting emails and spam. 

Suggestion:
Represents the guidelines of an organization to report potential threats and spam.

2022-05-30 17:29 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +Represents email threat submission policy. It is used for customizing your organization's experience and policy when reporting potential threats and spam in Microsoft Outlook.
The beta topic still displays the former information. 
<img width="567" alt="image" src="https://user-images.githubusercontent.com/70350956/171038598-ca1d4439-362a-4aed-8762-06a62f89be40.png">

2022-05-30 17:46 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +Represents email threat submission policy. It is used for customizing your organization's experience and policy when reporting potential threats and spam in Microsoft Outlook.
In a previous comment I also suggested: 
Represents the guidelines to report potential threads and spam in Microsoft Outlook for an organization.

2022-05-30 18:00 UTC, opbld34 commented
Docs Build status updates of commit _[14ee72a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14ee72a35a408f00e17c60012a0906fbbe0fa3a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-30 21:11 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +---
General for the PR: Please include TOC (Table of Contents) entries for all new entities and its methods.

2022-05-30 21:21 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
In general, it provides a good experience when we list or mention which query parameters are supported. If the filter parameter is supported, then please indicate which properties can be filtered.

2022-05-30 21:24 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Please apply to all List and Get topics in this PR.

2022-05-30 21:34 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isReportFromQuarantineEnabled            | Boolean | If enabled, submission could be created from security portal quarantine page.              |
Please order these properties alphabetically.

2022-05-30 21:35 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
Please order these properties alphabetically.

2022-05-30 21:42 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +```
In the example request: the api.md file says that all the properties of the entity are required, but in this example, we are only initializing one. 

Are the other properties optional? Do they have default values that populate automatically? Can they be null? 

The answer to those questions should be answered in the properties table of the resource topic, in the description column. 

Please add a sentence to the description column to clarify whether there are default values to these properties, or if they support null or if they are optional.

2022-05-30 21:50 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isReportFromQuarantineEnabled            | Boolean | If enabled, submission could be created from security portal quarantine page.              |
GLOBAL: please always list properties in alphabetical order.

2022-05-30 22:07 UTC, isvargasmsft commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
Regarding the description of the properties, please take in consideration 2 main principles:
1. We avoid constructions with 3 or more nouns in a row because they are hard to understand for readers whose native language is not English. For example: customized notification sender email address, review notification email/message, security portal quarantine page. In such cases, a better composition would be: The email address of the sender of customized notifications, an email notification of a review/for a review, the quarantine page in the security portal.
2. It is important to put yourself in the shoes of the developer who is reading and trying to use the API. When we say " the email address for review notification message" it's not clear what is the email for. Does it receive notification messages? Does it send notification messages? What's the functionality? 
Similar to "When customized address enabled", what is customized address and how to you enable it? Are we referring to a property of this resource? In that case, its better to call the property by its actual name. 
Another example when we say "If enabled, notificationSenderAddress is used to ..." what is notificationSenderAddress? Is it a property? a resource type? If it is a resource type then we should be including a reference link to its topic. 


Please note the changes made to this table should be reflected in the tables in the Create and Update topics as well.

Feel free to ping me on the side if you have questions around these property descriptions.

2022-05-30 22:11 UTC, opbld31 commented
Docs Build status updates of commit _[3f0d2ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f0d2ed45d0b5bd684f5b7fbe6083d9bd3515954)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-31 20:55 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +Inherits from [entity](../resources/entity.md).
Descriptions in lines 3 and from 16 to 22. 

Let's work together on this to make it clearer for developers. By know, let's add a list of the children types in line 22. 

- Inherits from entity. Base type of {list of children types with reference links for each}.

2022-05-31 20:57 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| User submission admin review |
Line 27, Description: We avoid using 3 or more nouns in a row. In this case "User submission admin review". It is not quite clear what do we mean by this. 

A suggestion would be:
Represents an administrative review of an alert submitted by a user.

2022-05-31 21:01 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +| category        | submissionCategory         | not junk, spam, phishing or malware.                                             |
Line 28: If this is an enum type, please follow the guidelines for the description here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations?anchor=examples

In this case, a suggestion would be:
The category of the submission. Possible values are: `not junk`, `spam`, `phishing`, `malware` and `unknownFutureValue`.

2022-05-31 21:01 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +| category        | submissionCategory         | not junk, spam, phishing or malware.                                             |
Please apply this to all the other descriptions of enum types in this table.

2022-05-31 21:02 UTC, isvargasmsft commented on api-reference/beta/resources/security-threatsubmission.md
> +| createdBy       | [security.submissionUserIdentity](../resources/security-submissionuseridentity.md)     | The submitter of the threat submission.   |
Line 31, description: Please revise to: The sender of the threat submission.

2022-05-31 21:55 UTC, opbld32 commented
Docs Build status updates of commit _[e4b8961](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4b896143089dd9c72dd87e625c525505302eb8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-05-31 22:07 UTC, opbld33 commented
Docs Build status updates of commit _[2a68e35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a68e357a14113461dd761a902038b3b6cd4d5bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-01 00:38 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-get.md
> +|Delegated (personal Microsoft account)|N/A|
Line 23: Instead of "N/A" please use "Not supported."

Please apply to all topics in this PR.

2022-06-01 00:43 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +In the request body, supply a JSON representation of the [emailContentThreatSubmission](../resources/security-emailcontentthreatsubmission.md) object or the [emailUrlThreatSubmission](../resources/se
This is a CRUD operation to create emailThreatSubmission resources, please clarify why are also using it to create another resource (emailContentThreatSubmission). Different entities should have their own CRUD operations AFAIK.

2022-06-01 00:45 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +or with tenantAllowOrBlockListAction provided
Lines 70 and 90: Let's create separate examples for separate scenarios. 

The structure should be:
H2 Examples
H3 Example 1: Description
H4 Request
H4 Response

H3 Example 2: Description "with tenantAllowOrBlockListAction provided
H4 Request
... 
Etc.

2022-06-01 00:52 UTC, isvargasmsft requested changes
Thank you for your work in this PR. 

Please dedicate time to the descriptions of enumeration types in Properties table. I left the link to the guidance in my comments. 
Please create TOC entries for the new entities and their methods. 
Please also take a look at some comments regarding format. 

Kind regards, 

Isaac

2022-06-02 08:32 UTC, opbld30 commented
Docs Build status updates of commit _[ae1f87e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae1f87edc308a36f19aa70679456eed836c0f26b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 08:41 UTC, opbld30 commented
Docs Build status updates of commit _[fe3f13b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe3f13bf66430915986a89be0236e684ed3abd2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 08:43 UTC, opbld30 commented
Docs Build status updates of commit _[434919c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/434919c48c06d8f6830cc19d202a366c6ec8b541)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 08:46 UTC, opbld30 commented
Docs Build status updates of commit _[6e62b06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e62b068b23d540288faa2f8d2585ed374508655)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 08:52 UTC, opbld32 commented
Docs Build status updates of commit _[24d1d50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24d1d5003bbbc60c3d7fffdf7e9359a95b6021f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 08:55 UTC, opbld30 commented
Docs Build status updates of commit _[8ad7132](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ad7132233d08ad4f3f4bf3b7243a57a55da9cf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 08:59 UTC, opbld30 commented
Docs Build status updates of commit _[3db473a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3db473aa362156f884256d43484a17617c9cffe2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 09:01 UTC, opbld34 commented
Docs Build status updates of commit _[b55cfce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b55cfce0e68276df2b3e99db4ea0a68a19d85efc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 09:04 UTC, caigen commented on api-reference/beta/resources/security-threatsubmission.md
> +| category        | submissionCategory         | not junk, spam, phishing or malware.                                             |
Will change but will ignore `unkownFutureValue` since it is a graph suggested common special value.

2022-06-02 09:52 UTC, opbld31 commented
Docs Build status updates of commit _[dfeabc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfeabc9529998a7b8c9fcaa69610b2a3750c03a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 09:55 UTC, opbld32 commented
Docs Build status updates of commit _[b67052b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b67052be2ae43571f5712590ae322e00c90a9c15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 09:58 UTC, opbld33 commented
Docs Build status updates of commit _[fa31381](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa313816fcee753f95e06c9ec071e6271bd11df0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 10:11 UTC, opbld32 commented
Docs Build status updates of commit _[5974a19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5974a1948c88693eddeae7c3717527716d375abf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 10:13 UTC, opbld34 commented
Docs Build status updates of commit _[8bc3a59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bc3a59c882d5e5ba8ba1b7b56c769e414368be7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-02 10:19 UTC, opbld31 commented
Docs Build status updates of commit _[0e11791](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e117918032c9cf664c3c42533897b047e674338)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-08 08:37 UTC, caigen commented on api-reference/beta/resources/security-attacksimulationinfo.md
> +
```suggestion
If one email is an attack simulation email, the email threat submission will contain attack simulation information.

```

2022-06-08 08:41 UTC, opbld33 commented
Docs Build status updates of commit _[1238405](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1238405b84e944def4924db1e325b7b7cc870755)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:16 UTC, opbld34 commented
Docs Build status updates of commit _[6f778f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f778f4a1beefe0037818b55a93d9b92be87fb21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:18 UTC, opbld33 commented
Docs Build status updates of commit _[5a47b22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a47b22d3b1fed66f779a1643b587dcc0ca682cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:22 UTC, opbld31 commented
Docs Build status updates of commit _[291a99b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/291a99b16b2f837d8f9023b4df15c2adcf4f7e30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:26 UTC, opbld33 commented
Docs Build status updates of commit _[77ab739](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77ab73904252388913e364dd3e3e1c3bbed2a82b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:28 UTC, opbld32 commented
Docs Build status updates of commit _[b5b3051](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5b305163776c9677fdaeb32aad3a53edb45111f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:30 UTC, opbld31 commented
Docs Build status updates of commit _[30b1be6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30b1be680b259e07844b7c003c391f4c64118148)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:33 UTC, opbld33 commented
Docs Build status updates of commit _[b51a045](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b51a0455d6578d1a32d3bcfdcca3b01276c514d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:36 UTC, opbld30 commented
Docs Build status updates of commit _[543f9a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/543f9a6587a3fe1de95f3031c5517d7017ce98ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:39 UTC, opbld34 commented
Docs Build status updates of commit _[c8c237c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8c237cb8de4b19ed4387cc8333318023daa826b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:41 UTC, opbld31 commented
Docs Build status updates of commit _[f7fb2ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7fb2ed764ab8ea269feb53d55af9d0c315622f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 10:43 UTC, opbld30 commented
Docs Build status updates of commit _[d227215](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d227215c33511fcb48c0302f326628f84c3c616a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 11:01 UTC, opbld32 commented
Docs Build status updates of commit _[da3c7a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da3c7a1bd7a5243079122debba04bbd0e6bf2d60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 11:07 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +
```suggestion
Only `Patch` request is supported by now. `Put` is not supported.

```

2022-06-09 11:08 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +Only `Patch` request is supported by now. `Put` is not supported.
```suggestion
Only HTTP `PATCH` request is supported by now. HTTP `PUT` is not supported.
```

2022-06-09 11:09 UTC, opbld32 commented
Docs Build status updates of commit _[4454fd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4454fd1c0693fc71518f22694cef05ac54c5e7a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 11:13 UTC, opbld32 commented
Docs Build status updates of commit _[ffa427a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffa427a474f25f88553434c8789acbde338229f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-09 22:52 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-get.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 22:53 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-get.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 22:56 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-list.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).

2022-06-09 22:57 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-list.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 22:57 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-list.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 22:58 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 22:59 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +In the request body, supply a JSON representation of the [emailContentThreatSubmission](../resources/security-emailcontentthreatsubmission.md) object or the [emailUrlThreatSubmission](../resources/se
```suggestion
In the request body, either supply a JSON representation of the [emailContentThreatSubmission](../resources/security-emailcontentthreatsubmission.md) object or the [emailUrlThreatSubmission](../resources/security-emailurlthreatsubmission.md) object.
```

2022-06-09 23:00 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +The emailContentThreatSubmission and emailUrlThreatSubmission are both emailThreatSubmission but submitted with different ways.
```suggestion
The emailContentThreatSubmission and emailUrlThreatSubmission are both subtypes of emailThreatSubmission and helps to make submission in different ways. 
```

2022-06-09 23:01 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +* The emailContentThreatSubmission is created with email content itself.
```suggestion
* If you want to create a submission with the email content itself, use the emailContentThreatSubmission.
```

2022-06-09 23:02 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +* The emailUrlThreatSubmissino is created by email url which points to the email.
```suggestion
* If you want to create a submission with a URL which points to the email, use the emailUrlThreatSubmission.
```

2022-06-09 23:05 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +* After emailContentThreatSubmission and emailUrlThreatSubmision are created, threat submission service itself does not store the email content and just some metadata are stored. So, the creation res
```suggestion
* After emailContentThreatSubmission and emailUrlThreatSubmision are created, the threat submission service just stores some metadata about the email. The email content is not stored. So, the created entity from both methods is an emailThreatSubmission entity.
```

2022-06-09 23:08 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:08 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:09 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:09 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md
> +Read the properties and relationships of an [emailThreatSubmissionPolicy](../resources/security-emailthreatsubmissionpolicy.md) object.
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:09 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:10 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md
> +Do not supply a request body for this method.
A request body is not required for this method.

2022-06-09 23:10 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:10 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:11 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:11 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md
> +Not suppported by now since only 1 email threat submission policy is supported by now and it is designed for future usage.
```suggestion
Not supported as of today since only one email threat submission policy is supported as of today.  It is designed for future usage.
```

2022-06-09 23:12 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:12 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +In the request body, supply a JSON representation of the [emailThreatSubmissionPolicy](../resources/security-emailthreatsubmissionpolicy.md) object.
```suggestion
In the request body, you need to provide a JSON representation of the [emailThreatSubmissionPolicy](../resources/security-emailthreatsubmissionpolicy.md) object.
```

2022-06-09 23:13 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:13 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +Only HTTP `PATCH` request is supported by now. HTTP `PUT` is not supported.
```suggestion
Only HTTP `PATCH` request is supported as of today. HTTP `PUT` is not supported.
```

2022-06-09 23:14 UTC, dhairyya commented on api-reference/beta/api/security-filethreatsubmission-get.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:14 UTC, dhairyya commented on api-reference/beta/api/security-filethreatsubmission-get.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:15 UTC, dhairyya commented on api-reference/beta/api/security-filethreatsubmission-list.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:15 UTC, dhairyya commented on api-reference/beta/api/security-filethreatsubmission-list.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:15 UTC, dhairyya commented on api-reference/beta/api/security-filethreatsubmission-post-filethreats.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:16 UTC, dhairyya commented on api-reference/beta/api/security-filethreatsubmission-post-filethreats.md
> +In the request body, supply a JSON representation of the [fileContentThreatSubmission](../resources/security-filecontentthreatsubmission.md) object. The [fileUrlContentThreatSubmission](../resources/
```suggestion
In the request body, supply a JSON representation of the [fileContentThreatSubmission](../resources/security-filecontentthreatsubmission.md) object. The [fileUrlContentThreatSubmission](../resources/security-fileurlthreatsubmission.md) is reserved and not supported as of today.
```

2022-06-09 23:16 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-get.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:17 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-get.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:17 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-list.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:17 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-list.md
> +Do not supply a request body for this method.
```suggestion
A request body is not required for this method. 
```

2022-06-09 23:17 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```suggestion
One of the following permissions is required to call this API. To learn more permissions, including how to choose one, see [Permissions](/graph/permissions-reference).
```

2022-06-09 23:24 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md
> +You can specify the following properties when creating an **urlThreatSubmission**.
```suggestion
You may also specify the following properties when creating an **urlThreatSubmission**.
```

2022-06-09 23:24 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +You can specify the following properties when creating an **emailThreatSubmissionPolicy**.
```suggestion
You may also specify the following properties when creating an **emailThreatSubmissionPolicy**.
```

2022-06-09 23:26 UTC, dhairyya commented on api-reference/beta/resources/security-attacksimulationinfo.md
> +If one email is an attack simulation email, the email threat submission will contain attack simulation information.
```suggestion
If an email was an attack simulation email, the email threat submission would contain corresponding attack simulation information.
```

2022-06-09 23:53 UTC, dhairyya commented on api-reference/beta/resources/security-emailcontentthreatsubmission.md
> +Represents email content threat submission which is submitted by email file content.
```suggestion
Represents email content threat submission object which is created when submission is made using email file content.
```

2022-06-09 23:55 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +Represents the guidelines of an organization to report potential threats and spam. It is used for customizing your organization's end user threat submission experience when reporting potential threat
```suggestion
Represents organizational guidelines about reporting potential threats and spam messages. It is used for customizing your organization's end user threat submission experience when reporting potential threats and spam in Microsoft Outlook.
```

2022-06-09 23:56 UTC, dhairyya commented on api-reference/beta/resources/security-emailurlthreatsubmission.md
> +Represents email url threat submission which is submitted by email url.
```suggestion
Represents email url threat submission object which is created when submission is made using email URL.
```

2022-06-09 23:57 UTC, dhairyya commented on api-reference/beta/resources/security-filecontentthreatsubmission.md
> +Represents file content threat submission which is submitted by file content.
```suggestion
Represents file content threat submission object which is created when submission is made using file content.
```

2022-06-09 23:58 UTC, dhairyya commented on api-reference/beta/resources/security-filethreatsubmission.md
> +Currently, file threat submission is routed to Microsoft 365 Defender for Office. In future, it may be routed to Mcirosoft 365 Defender for Endpoint. This is a unified interface for file threat submi
```suggestion
Currently, file threat submission is routed to Microsoft 365 Defender for Office. In future, it may be routed to Microsoft 365 Defender for Endpoint. This is a unified interface for file threat submission no matter where it is routed to.
```

2022-06-10 00:11 UTC, dhairyya commented on api-reference/beta/resources/security-fileurlthreatsubmission.md
> +Represents file threat submission which is submitted by file url. It is a reserved api and not supported by now.
```suggestion
Represents file threat submission object which is created when submission is made using file URL. It is a reserved api and not supported as of today.
```

2022-06-10 00:14 UTC, dhairyya commented on api-reference/beta/resources/security-submissionadminreview.md
> +Represents admin review information for threat submission. Currently, only user reported email threat submission is supported and could be reviewed by administrator.
```suggestion
Represents admin review information for threat submission. Currently, only user reported email threat submission is supported and can be reviewed by administrator.
```

2022-06-10 00:14 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +Represents threat submission result when threat submission is processed by Microsoft.
```suggestion
Represents threat submission result after threat submission is processed by Microsoft.
```

2022-06-10 00:21 UTC, dhairyya commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +Represents tenant allow block list entry result. It is an entry for tenant allow block list item which could be url, attachment or senders.
```suggestion
Represents result of tenant allow block list entry. It is an entry for tenant allow block list item that could be url, attachment or senders.
```

2022-06-10 00:27 UTC, dhairyya commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +Represents tenant allow or block list action. When admin creates email threat submission, tenant allow block list operation could be provided. When tenant allow block list operation is provided, the
```suggestion
Represents tenant allow or block list action. When admin creates email threat submission, tenant allow block list operation can also be provided. When tenant allow block list operation is provided, the threat submission will auto add related items (urls/attachments/senders) into tenant allow block list.
```

2022-06-10 00:30 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +It is used to submit suspected spam emails, malware emails, phish emails, malware urls, phish urls and malware email attachments to Microsoft 365 Defender for Office (MDO), as well as to submit suspi
```suggestion
It is used to submit suspected spam emails, malware emails, phish emails, malware urls, phish urls, phish email attachments and malware email attachments to Microsoft 365 Defender for Office (MDO), as well as to submit suspicious files to M365 Defender for Endpoint (MDE).
```

2022-06-10 06:19 UTC, opbld34 commented
Docs Build status updates of commit _[a9ec006](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9ec0062e28c38dfac4723b0775f3fd0daaf5e5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:21 UTC, opbld31 commented
Docs Build status updates of commit _[081d3d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/081d3d5174a862044f96c76ead663000faabe43f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:24 UTC, opbld30 commented
Docs Build status updates of commit _[c3a9e7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3a9e7e90a3129dad3d85f1aad8514642400aecd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:26 UTC, opbld33 commented
Docs Build status updates of commit _[ab09ef8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab09ef803033abf8b92c6e5cd242249ff3ef2c42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:28 UTC, opbld30 commented
Docs Build status updates of commit _[67b5177](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67b5177686745b9f9813ff902e75a2893c2dbd8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:33 UTC, caigen commented on api-reference/beta/api/security-urlthreatsubmission-list.md
> +Do not supply a request body for this method.
It is **auto generated.** So let us keep it so it is aligned with other docs.

2022-06-10 06:33 UTC, opbld33 commented
Docs Build status updates of commit _[0e31a85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e31a856f7a1f093e1ee3bd1cb79b4e4ef231f79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:38 UTC, opbld31 commented
Docs Build status updates of commit _[0f84a6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f84a6e06dc954e340b737a6c637484cd6f8796f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:40 UTC, opbld32 commented
Docs Build status updates of commit _[5f2466b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f2466bc20c2fb4e66a6fbafcb2854bb2e5febe7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:42 UTC, opbld32 commented
Docs Build status updates of commit _[725fad2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/725fad27d06d991be03eef7d6c4acda3a44bf2d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:45 UTC, opbld31 commented
Docs Build status updates of commit _[40f8d47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40f8d471364943b27fdce40453457743f364559e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:47 UTC, opbld31 commented
Docs Build status updates of commit _[b2313d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2313d1f0305b6fc917b423dd1983914b5860729)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:47 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
@dhairyya This one.

2022-06-10 06:49 UTC, opbld31 commented
Docs Build status updates of commit _[a90490f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a90490f05a09f4e51895b356f1c921f5563ccfbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:51 UTC, opbld31 commented
Docs Build status updates of commit _[b007f3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b007f3f0f6e8b0aa3d4bb4c3102c305288374a33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:53 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +---
@isvargasmsft What is the format of the TOC? Is there a sample? Or you can use `suggestion` to provide one sample.
+ @dhairyya

2022-06-10 06:54 UTC, opbld34 commented
Docs Build status updates of commit _[dd4f60a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd4f60a20ad9128cd59b9b494cf55e2ebc7c8db9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:56 UTC, opbld30 commented
Docs Build status updates of commit _[7688f26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7688f2657bb287b777f19db852255b43d1f1dbf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 06:59 UTC, opbld31 commented
Docs Build status updates of commit _[90624fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90624fa49f079e2737c03086aa31926ae966821c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 07:01 UTC, opbld33 commented
Docs Build status updates of commit _[00c061f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00c061fce9ea52c9c46bcefc1ea8628fb2008d04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 07:03 UTC, opbld30 commented
Docs Build status updates of commit _[09de5df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09de5df3ef4af77e51d995fb7c59e8d750ef3b4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 07:06 UTC, opbld30 commented
Docs Build status updates of commit _[45baa51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45baa5169e4c0f96dda697098658f7000a5197b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 07:08 UTC, opbld31 commented
Docs Build status updates of commit _[36621df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36621dffbb22640a38758b5f050179a56eea91d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 07:25 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| customizedNotificationSenderEmailAddress | String  | Customized notification sender address for review notification message.                    |
```suggestion
| customizedNotificationSenderEmailAddress | String  | The email address of the sender of customized notifications |
```

2022-06-10 07:26 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| customizedReportRecipientEmailAddress    | String  | When customized address enabled, the message will be sent to this address.                 |
```suggestion
| customizedReportRecipientEmailAddress    | String  | The reported messages from end users will be sent to this address.
```

2022-06-10 07:36 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isAlwaysReportEnabledForUsers            | Boolean | User could use 'Always report the message' option. The default value is true.              |
```suggestion
| isAlwaysReportEnabledForUsers            | Boolean | It is used to specify whether end users can report a message directly without a confirmation. Its default value is true |
```

2022-06-10 07:37 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isAskMeEnabledForUsers                   | Boolean | User could use 'Ask me before reporting the message' option. The default value is true.    |
```suggestion
| isAskMeEnabledForUsers                   | Boolean | It is used to specify whether end users can confirm using a popup before reporting messages as spam, phish or not junk. Its default value is true |
```

2022-06-10 07:41 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isCustomizedMessageEnabled               | Boolean | If enabled, customized message is enabled.                                                 |
```suggestion
| isCustomizedMessageEnabled               | Boolean | It is used to specify whether the email notifications sent to end users to inform them whether an email is phish, spam or junk is customized or not? |
```

2022-06-10 07:42 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isCustomizedMessageEnabledForPhishing    | Boolean | If enabled, customized message only shows when email is reported as phishing.              |
```suggestion
| isCustomizedMessageEnabledForPhishing    | Boolean | It is used to specify whether the email notifications sent to end users is to be sent for phish or not? |
```

2022-06-10 07:43 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| id                                       | String  | Policy id.                                                                                 |
```suggestion
| id                                       | String  | As of today, only one id is supported. The default value is 'DefaultReportSubmissionPolicy'. |
```

2022-06-10 07:45 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isCustomizedNotificationSenderEnabled    | Boolean | If enabled, notificationSenderAddress is used by review notification email.                |
```suggestion
| isCustomizedNotificationSenderEnabled    | Boolean | It is used to specify whether we should use the sender email address which we set earlier for sending email notifications to end users or not?|
```

2022-06-10 08:05 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isNeverReportEnabledForUsers             | Boolean | User could use 'Never report the message' option. The default value is true.               |
```suggestion
| isNeverReportEnabledForUsers             | Boolean |  It is used to specify whether end users can simply move the message from one folder to another based on the action of spam, phish or not junk without actually reporting it. Its default value is true |
```

2022-06-10 08:08 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isReportFromQuarantineEnabled            | Boolean | If enabled, submission could be created from security portal quarantine page.              |
```suggestion
| isReportFromQuarantineEnabled            | Boolean | It is used to specify whether end users can submit from the quarantine page or not?  |
```

2022-06-10 08:09 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isReportToCustomizedEmailAddressEnabled  | Boolean | If enabled, the email will be sent to customizedReportRecipientEmailAddress.               |
```suggestion
| isReportToCustomizedEmailAddressEnabled  | Boolean | It is used to specify whether emals reported by end users should be send to the custom mailbox which was configured above using customizedReportRecipientEmailAddress  |
```

2022-06-10 08:11 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isReportToMicrosoftEnabled               | Boolean | If enabled, the email will be sent to Microsoft for analysis.                              |
```suggestion
| isReportToMicrosoftEnabled               | Boolean |It is used to specify whether the email messages reported by end users as junk, phish or not junk be sent to Microsoft or not? |
```

2022-06-10 08:12 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isReviewEmailNotificationEnabled         | Boolean | If enabled, system sends email notification to reporter when admin reviews the submission. |
```suggestion
| isReviewEmailNotificationEnabled         | Boolean | It is used to specify whether an email notification be sent to the end user who reported the email when it has been reviewed by the Admin? |
```

2022-06-10 08:13 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
```suggestion
| isOrganizationBrandingEnabled            | Boolean | It is used to specify whether the branding logo should be used in the email notifications or not which are being sent to end users? |
```

2022-06-10 08:15 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +|category|String|notSpam, junk, phishing, malware. Case insensitive.|
```suggestion
|category|String|The email is being reported as notSpam, junk, phishing, malware. Case insensitive.|
```

2022-06-10 08:19 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isReportToMicrosoftEnabled               | Boolean | If enabled, the email will be sent to microsoft for analysis.                              |
```suggestion
| isReportToMicrosoftEnabled               | Boolean |It is used to specify whet                              |
```
```suggestion
| isReportToMicrosoftEnabled               | Boolean | It is used to specify whether the email messages reported by end users as junk, phish or not junk be sent to Microsoft or not?|
```

2022-06-10 08:19 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isReportToCustomizedEmailAddressEnabled  | Boolean | If enabled, the email will be sent to customizedReportRecipientEmailAddress.               |
```suggestion
| isReportToCustomizedEmailAddressEnabled  | Boolean | It is used to specify whether emals reported by end users should be send to the custom mailbox which was configured using customizedReportRecipientEmailAddress? | 
```

2022-06-10 08:20 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isAskMeEnabledForUsers                   | Boolean | User could use 'Ask me before reporting the message' option. The default value is true.    |
```suggestion
| isAskMeEnabledForUsers                   | Boolean | It is used to specify whether end users can confirm using a popup before reporting messages as spam, phish or not junk. Its default value is true |
```

2022-06-10 08:20 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isAlwaysReportEnabledForUsers            | Boolean | User could use 'Always report the message' option. The default value is true.              |
```suggestion
| isAlwaysReportEnabledForUsers            | Boolean | It is used to specify whether end users can report a message as spam, phish or junk directly without a confirmation(popup). Its default value is true |
```

2022-06-10 08:21 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isNeverReportEnabledForUsers             | Boolean | User could use 'Never report the message' option. The default value is true.               |
```suggestion
| isNeverReportEnabledForUsers             | Boolean | It is used to specify whether end users can submit from the quarantine page or not? |
```

2022-06-10 08:22 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isCustomizedMessageEnabledForPhishing    | Boolean | If enabled, customized message only shows when email is reported as phishing.              |
```suggestion
| isCustomizedMessageEnabledForPhishing    | Boolean | It is used to specify whether the customized email notifications sent to end users is to be sent for phish or not? |
```

2022-06-10 08:22 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isCustomizedMessageEnabled               | Boolean | If enabled, customized message is enabled.                                                 |
```suggestion
| isCustomizedMessageEnabled               | Boolean |It is used to specify whether the email notifications sent to end users to inform them whether an email is phish, spam or junk is customized or not? |
```

2022-06-10 08:23 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| customizedReportRecipientEmailAddress    | String  | When customized address enabled, the message will be sent to this address.                 |
```suggestion
| customizedReportRecipientEmailAddress    | String  | It is used to specify the destination where the reported messages from end users will land whenever they report something as phish, junk or not junk.   |
```

2022-06-10 08:24 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isReviewEmailNotificationEnabled         | Boolean | If enabled, system sends email notification to reporter when admin reviews the submission. |
```suggestion
| isReviewEmailNotificationEnabled         | Boolean | If enabled, system sends email notification to reporter when admin reviews the submission. |
```
```suggestion
| isReviewEmailNotificationEnabled         | Boolean |It is used to specify whether an email notification be sent to the end user who reported the email when it has been reviewed by the Admin? |
```

2022-06-10 08:24 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isCustomizedNotificationSenderEnabled    | Boolean | If enabled, notificationSenderAddress is used by review notification email.                |
```suggestion
| isCustomizedNotificationSenderEnabled    | Boolean | It is used to specify whether we should use the sender email address which we set earlier using customizedNotificationSenderEmailAddress for sending email notifications to end users or not? |
```

2022-06-10 08:25 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
```suggestion
| isOrganizationBrandingEnabled            | Boolean | It is used to specify whether the branding logo should be used in the email notifications or not which are being sent to end users? |
```

2022-06-10 08:26 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| customizedNotificationSenderEmailAddress | String  | Customized notification sender address for review notification message.                    |
```suggestion
| customizedNotificationSenderEmailAddress | String  | It is used to specify the email address of the sender from which email notifications will be sent to end users to inform them whether an email is spam, phish or clean. |
```

2022-06-10 08:26 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +| isReportFromQuarantineEnabled            | Boolean | If enabled, submission could be created from security portal quarantine page.              |
```suggestion
| isReportFromQuarantineEnabled            | Boolean | It is used to specify whether end users can submit from the quarantine page or not? |
```

2022-06-10 08:27 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isReportToMicrosoftEnabled               | Boolean | If enabled, the email will be sent to microsoft for analysis.                              |
```suggestion
| isReportToMicrosoftEnabled               | Boolean | It is used to specify whether the email messages reported by end users as junk, phish or not junk be sent to Microsoft or not?|
```

2022-06-10 08:28 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isReportToCustomizedEmailAddressEnabled  | Boolean | If enabled, the email will be sent to customizedReportRecipientEmailAddress.               |
```suggestion
| isReportToCustomizedEmailAddressEnabled  | Boolean | It is used to specify whether emails reported by end users should be send to the custom mailbox which will be configured below using customizedReportRecipientEmailAddress? |
```

2022-06-10 08:28 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isAskMeEnabledForUsers                   | Boolean | User could use 'Ask me before reporting the message' option. The default value is true.    |
```suggestion
| isAskMeEnabledForUsers                   | Boolean | It is used to specify whether end users can confirm using a popup before reporting messages as spam, phish or not junk. Its default value is true |
```

2022-06-10 08:29 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isAlwaysReportEnabledForUsers            | Boolean | User could use 'Always report the message' option. The default value is true.              |
```suggestion
| isAlwaysReportEnabledForUsers            | Boolean | It is used to specify whether end users can report a message as spam, phish or junk directly without a confirmation(popup). Its default value is true|
```

2022-06-10 08:29 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isNeverReportEnabledForUsers             | Boolean | User could use 'Never report the message' option. The default value is true.               |
```suggestion
| isNeverReportEnabledForUsers             | Boolean | It is used to specify whether end users can simply move the message from one folder to another based on the action of spam, phish or not junk without actually reporting it. Its default value is true. |
```

2022-06-10 08:30 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isCustomizedMessageEnabledForPhishing    | Boolean | If enabled, customized message only shows when email is reported as phishing.              |
```suggestion
| isCustomizedMessageEnabledForPhishing    | Boolean | It is used to specify whether the customized email notifications sent to end users is to be sent for phish or not? |
```

2022-06-10 08:30 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isCustomizedMessageEnabled               | Boolean | If enabled, customized message is enabled.                                                 |
```suggestion
| isCustomizedMessageEnabled               | Boolean | It is used to specify whether the email notifications sent to end users to inform them whether an email is phish, spam or junk is customized or not? |
```

2022-06-10 08:31 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isReviewEmailNotificationEnabled         | Boolean | If enabled, system sends email notification to reporter when admin reviews the submission. |
```suggestion
| isReviewEmailNotificationEnabled         | Boolean |It is used to specify whether an email notification be sent to the end user who reported the email when it has been reviewed by the Admin? |
```

2022-06-10 08:35 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isCustomizedNotificationSenderEnabled    | Boolean | If enabled, notificationSenderAddress is used by review notification email.                |
```suggestion
| isCustomizedNotificationSenderEnabled    | Boolean | It is used to specify whether we should use the sender email address which we will set below using customizedNotificationSenderEmailAddress for sending email notifications to end users or not?|
```

2022-06-10 08:35 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
```suggestion
| isOrganizationBrandingEnabled            | Boolean | It is used to specify whether the branding logo should be used in the email notifications or not which are being sent to end users? |
```

2022-06-10 08:35 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| customizedNotificationSenderEmailAddress | String  | Customized notification sender address for review notification message.                    |
```suggestion
| customizedNotificationSenderEmailAddress | String  | It is used to specify the email address of the sender from which email notifications will be sent to end users to inform them whether an email is spam, phish or clean. |
```

2022-06-10 08:36 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +| isReportFromQuarantineEnabled            | Boolean | If enabled, submission could be created from security portal quarantine page.              |
```suggestion
| isReportFromQuarantineEnabled            | Boolean | It is used to specify whether end users can submit from the quarantine page or not?|
```

2022-06-10 08:42 UTC, dhairyya commented on api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md
> +|category|submissionCategory|Inherited from [threatSubmission](../resources/security-threatsubmission.md). The possible values are: `notJunk`, `spam`, `phishing`, `malware`, `unknownFutureValue`. Req
```suggestion
|category|submissionCategory|Inherited from [threatSubmission](../resources/security-threatsubmission.md) and required field. The possible values are: `notJunk`, `spam`, `phishing`, `malware`, `unknownFutureValue`. It is use to tell what you are reporting the URL as?|
```

2022-06-10 08:45 UTC, dhairyya commented on api-reference/beta/resources/security-attacksimulationinfo.md
> +| attackSimDateTime     | DateTimeOffset | The attack simulation date time.     |
```suggestion
| attackSimDateTime     | DateTimeOffset | It is used to specify the date time of the attack simulation.   |
```

2022-06-10 08:46 UTC, dhairyya commented on api-reference/beta/resources/security-attacksimulationinfo.md
> +| attackSimDurationTime | Duration       | The attack simulation duration time. |
```suggestion
| attackSimDurationTime | Duration       | It is used to specify the duration (in time) for the attack simulation  |
```

2022-06-10 08:46 UTC, dhairyya commented on api-reference/beta/resources/security-attacksimulationinfo.md
> +| attackSimId           | Guid           | The attack simulation activity id.   |
```suggestion
| attackSimId           | Guid           |It is used to specify the activity id for the attack simulation. |
```

2022-06-10 08:46 UTC, dhairyya commented on api-reference/beta/resources/security-attacksimulationinfo.md
> +| attackSimUserId       | String         | The attack simulation user id.       |
```suggestion
| attackSimUserId       | String         | It is used to specify the user id for the attack simulation.   |
```

2022-06-10 08:48 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| attackSimulationInfo         | [security.attackSimulationInfo](../resources/security-attacksimulationinfo.md) | If the email is phishing simulation, the field will not be null.|
```suggestion
| attackSimulationInfo         | [security.attackSimulationInfo](../resources/security-attacksimulationinfo.md) | If the email is phishing simulation, this field will not be null.|
```

2022-06-10 08:49 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| originalCategory             | submissionCategory           | notJunk, spam, phishing, malware.                                                                      |
```suggestion
| originalCategory             | submissionCategory           | The category the email is being reported as. The values are "not junk", "spam", "phishing" and "malware".|
```

2022-06-10 08:50 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| receivedDateTime             | DateTimeOffset               | The received date time of the submitted email.                                                         |
```suggestion
| receivedDateTime             | DateTimeOffset               | It is used to specify the date timestamp of when the email was received?| 
```

2022-06-10 08:51 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| recipientEmailAddress        | String                       | The email recipient smtp address string.                                                               |
```suggestion
| recipientEmailAddress        | String                       | It is used to specify the email address (in smtp format) of the recipient who received the email which is being submitted?|
```

2022-06-10 08:52 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| sender                       | String                       | The sender of the submitted email.                                                                     |
```suggestion
| sender                       | String                       | It is used to specify the email address of the sender. | 
```

2022-06-10 08:53 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| senderIP                     | String                       | The sender IP of the submitted email.                                                                  |
```suggestion
| senderIP                     | String                       | It is used to specify the IP address of the sender who send the email which is being submitted.|
```

2022-06-10 08:53 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| subject                      | String                       | The subject of the submitted email.                                                                    |
```suggestion
| subject                      | String                       | It is used to specify the subject of the email being submitted.                                                                    |
```

2022-06-10 08:54 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| tenantAllowOrBlockListAction | [security.tenantAllowOrBlockListAction](../resources/security-tenantalloworblocklistaction.md) | Used to auto add urls/attachments/senders of the email threat submiss
```suggestion
| tenantAllowOrBlockListAction | [security.tenantAllowOrBlockListAction](../resources/security-tenantalloworblocklistaction.md) | It is used to automatically add allows for the components such as URL, file, sender which are deemed bad by Microsoft so that similar messages in the future can be allowed.|
```

2022-06-10 08:55 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| internetMessageId            | String                       | The internet message id of the submitted email.                                                        |
```suggestion
| internetMessageId            | String                       | It is used to specify the internet message id of the email which is being submitted. This information is present in the email header. |
```

2022-06-10 08:56 UTC, dhairyya commented on api-reference/beta/resources/security-emailurlthreatsubmission.md
> +| messageUrl | String | The graph message url to be submitted. |
```suggestion
| messageUrl | String | It specifies the url of the graph message which is to be submitted. |
```

2022-06-10 08:56 UTC, dhairyya commented on api-reference/beta/resources/security-filecontentthreatsubmission.md
> +| fileContent | String | Base64 encoded file content. |
```suggestion
| fileContent | String | It specifies the file content in base 64 format. |
```

2022-06-10 08:57 UTC, dhairyya commented on api-reference/beta/resources/security-filethreatsubmission.md
> +| fileName | String | The file name to be submitted. |
```suggestion
| fileName | String | It specifies the file name to be submitted. |
```

2022-06-10 08:58 UTC, dhairyya commented on api-reference/beta/resources/security-fileurlthreatsubmission.md
> +| fileUrl  | String | The file url to be submitted. |
```suggestion
| fileUrl  | String | It specifies the URL of the file which needs to be submitted. |
```

2022-06-10 08:58 UTC, dhairyya commented on api-reference/beta/resources/security-submissionadminreview.md
> +| reviewBy       | String                   | The reviewer email or other identity string. |
```suggestion
| reviewBy       | String                   | It specifies who reviewed the email? The identification is done using email id or other identity strings|
```

2022-06-10 08:59 UTC, dhairyya commented on api-reference/beta/resources/security-submissionadminreview.md
> +| reviewDateTime | DateTimeOffset           | The review date time.                        |
```suggestion
| reviewDateTime | DateTimeOffset           | It is used to specify the date time of when the review occurred.|
```

2022-06-10 08:59 UTC, dhairyya commented on api-reference/beta/resources/security-submissionadminreview.md
> +| reviewResult   | submissionResultCategory | The review result                            |
```suggestion
| reviewResult   | submissionResultCategory | It is used to specify what the review result was? |
```

2022-06-10 09:00 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| category           | submissionResultCategory           | The submission result category.                                         |
```suggestion
| category           | submissionResultCategory           | It is used to specify what the result of the analysis from the Microsoft was? |
```

2022-06-10 09:01 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| detail             | submissionResultDetail             | The submission result detail.                                           |
```suggestion
| detail             | submissionResultDetail             | It is used to specify the additional details provided by Microsoft to substantiate their analysis result. |
```

2022-06-10 09:02 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| detectedFiles      | Collection([security.submissionDetectedFile](../resources/security-submissiondetectedfile.md)) | Detected files in the email submission. |
```suggestion
| detectedFiles      | Collection([security.submissionDetectedFile](../resources/security-submissiondetectedfile.md)) | It is use to specify the files which were detected by Microsoft in the submitted emails|
```

2022-06-10 09:03 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| detectedUrls       | Collection(String)                 | Detected urls in the email submission.                                  |
```suggestion
| detectedUrls       | Collection(String)                 | It is used to specify the URLs which were detected by Microsoft in the submitted email.|
```

2022-06-10 09:04 UTC, dhairyya commented on api-reference/beta/resources/security-submissionuseridentity.md
> +| email       | String | The email of submission user for delegated token case.                                                         |
```suggestion
| email       | String | The email of user for which you are making a submission using delegated token case.                                                         | 
```

2022-06-10 09:06 UTC, dhairyya commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| entryType          | tenantAllowBlockListEntryType | The tenant allow block list entry type.                 |
```suggestion
| entryType          | tenantAllowBlockListEntryType | It specifies whether it is an "allow" or "block" type of entry in the tenant allow block list.  |
```

2022-06-10 09:06 UTC, dhairyya commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| expirationDateTime | DateTimeOffset                | The expiration date time for this entry.                |
```suggestion
| expirationDateTime | DateTimeOffset                | It is used to specify when will this entry expire in date time? |
```

2022-06-10 09:08 UTC, dhairyya commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| status             | longRunningOperationStatus    | The tenant allow block operation result for this entry. |
```suggestion
| status             | longRunningOperationStatus    | It is used to specify whether the tenant allow block list entry creation operation was successful or not |
```

2022-06-10 09:09 UTC, dhairyya commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| value              | String                        | The tenant allow block list value.                      |
```suggestion
| value              | String                        | It is used to specify the value of the created Tenant allow block list entry.  |
```

2022-06-10 09:12 UTC, dhairyya commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| action             | tenantAllowBlockListAction                  | The tenant allow block list action.                                              |
```suggestion
| action             | tenantAllowBlockListAction                  | It is used to specify whether the tenant allow block list is an allow or block. |
```

2022-06-10 09:14 UTC, dhairyya commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| expirationDateTime | DateTimeOffset                              | The tenant allow block list auto expiration date time.                           |
```suggestion
| expirationDateTime | DateTimeOffset                              | It is used to specify when the Tenant allow block list expires in date time,  |
```

2022-06-10 09:15 UTC, dhairyya commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| note               | String                                      | The tenant allow block list note string.                                         |
```suggestion
| note               | String                                      | It specifies the note added to the tenant allow block list entry in the format of string. |
```

2022-06-10 09:17 UTC, dhairyya commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| results            | Collection([security.tenantAllowBlockListEntryResult](../resources/security-tenantallowblocklistentryresult.md)) | The result which contains tenant allow block list items of th
```suggestion
| results            | Collection([security.tenantAllowBlockListEntryResult](../resources/security-tenantallowblocklistentryresult.md)) | It contains the result of the submission which lead to this Tenant allow block list entry creation |
```

2022-06-10 09:22 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| category        | submissionCategory         | not junk, spam, phishing or malware.                                             |
```suggestion
| category        | submissionCategory         | It is used to specify what we are submitting as to Microsoft? The values are are "not junk", "spam", "phishing" or "malware".   |
```

2022-06-10 09:25 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| clientSource    | submissionClientSource     | microsoft or other client.                                                       |
```suggestion
| clientSource    | submissionClientSource     | It is used to specify what the source for this submission is? Is it Microsoft or other clients which is specified by 'other' |
```

2022-06-10 09:26 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| contentType     | submissionContentType      | email, url, file or app.                                                         |
```suggestion
| contentType     | submissionContentType      | It is used to specify the type of content which is being submitted. The values can be email, URL, file or app.|
```

2022-06-10 09:27 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| createdBy       | [security.submissionUserIdentity](../resources/security-submissionuseridentity.md)     | The submitter of the threat submission.   |
```suggestion
| createdBy       | [security.submissionUserIdentity](../resources/security-submissionuseridentity.md)     | It is use to specify who submitted the email as a threat.|
```

2022-06-10 09:27 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| createdDateTime | DateTimeOffset             | When the threat submission was created.                                          |
```suggestion
| createdDateTime | DateTimeOffset             | It is used to specify when the threat submission was created.                                          |
```

2022-06-10 09:28 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| id              | String                     | Threat submission id. When creation on post, it is not necessary.                |
```suggestion
| id              | String                     | It specifies the id of Threat submission. When creating using post method, it is not required.                |
```

2022-06-10 09:28 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| result          | [security.submissionResult](../resources/security-submissionresult.md)          | The threat submission check result.  |
```suggestion
| result          | [security.submissionResult](../resources/security-submissionresult.md)          | It is used to specify the result of the analysis which Microsoft had done. |
```

2022-06-10 09:29 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| source          | submissionSource           | The threat submission source. Administrator or user.                             |
```suggestion
| source          | submissionSource           |It is used to specify who is doing the threat submission? Is it a user or an administrator. |
```

2022-06-10 09:31 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| tenantId        | String                     | The tenant id. When creation on post, it is not necessary. Extracted from token. |
```suggestion
| tenantId        | String                     | It denotes the the tenant id from which submission was done. When creation using post method, it is not required. It is extracted from the token of the post API call. |
```

2022-06-10 09:33 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| User submission admin review |
```suggestion
| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| It specifies the admin review property which constitutes of who it reviewed the user submission, when and what was it identified as? |
```

2022-06-10 09:34 UTC, dhairyya commented on api-reference/beta/resources/security-urlthreatsubmission.md
> +| webUrl   | String | The webUrl to be submitted. |
```suggestion
| webUrl   | String | It denotes the webUrl which needs to be submitted. |
```

2022-06-10 09:45 UTC, opbld32 commented
Docs Build status updates of commit _[283436e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/283436e2e268f787a7a5001e94f5678028808c53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 09:47 UTC, opbld32 commented
Docs Build status updates of commit _[22b7826](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22b7826505e7695a64873437270c6e24a706104b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 09:49 UTC, opbld30 commented
Docs Build status updates of commit _[f70cd6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f70cd6b026a88c73a3f4c1648e3c8a2c45bc5472)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 09:54 UTC, opbld32 commented
Docs Build status updates of commit _[de21e51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de21e5152b341cfaf597f90a56fc5d0f51939556)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 09:57 UTC, opbld31 commented
Docs Build status updates of commit _[1324937](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13249377c7ea8f3697cb37721710add21851a944)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 09:59 UTC, opbld33 commented
Docs Build status updates of commit _[503d9cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/503d9ccb1610fcacc2b334b359fb8cc77045f2da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:01 UTC, opbld33 commented
Docs Build status updates of commit _[016fe7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/016fe7ab573a4cd91cf701e4661513ca78b23d48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:06 UTC, opbld34 commented
Docs Build status updates of commit _[6f67ef3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f67ef3684f4e51406f0ded58afebaf94f9da07a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:09 UTC, opbld30 commented
Docs Build status updates of commit _[133af8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/133af8f1977e942f7df090d19aaf14f7fc79bcec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:11 UTC, opbld30 commented
Docs Build status updates of commit _[d027354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0273543f5692fa6f5805f04ff0640647830b4a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:13 UTC, opbld34 commented
Docs Build status updates of commit _[173532b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/173532bea97b362b5ef031e8a7eea646d2af84c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:13 UTC, caigen commented on api-reference/beta/resources/security-threatsubmission.md
> +| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| User submission admin review |
```suggestion
| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| It specifies the admin review property which constitutes of who it reviewed the user submission, when and what was it identified as? |
```

2022-06-10 10:16 UTC, opbld32 commented
Docs Build status updates of commit _[4ccae02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ccae0210c7da8904ee0ce328d955b31b94568f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:18 UTC, opbld32 commented
Docs Build status updates of commit _[c5acf7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5acf7f885a85c72355254523ed0d8714fe815b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:19 UTC, caigen commented on api-reference/beta/resources/security-threatsubmission.md
> +| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| Represents an administrative review of an threat submitted by a user. |
```suggestion
| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| It specifies the admin review property which constitutes of who it reviewed the user submission, when and what was it identified as? |
```

2022-06-10 10:20 UTC, opbld31 commented
Docs Build status updates of commit _[a4899dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4899dc36db9c9115592a1a7466784363aa1feb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:24 UTC, caigen commented on api-reference/beta/resources/security-threatsubmission.md
> +| tenantId        | String                     | It denotes the the tenant id from which submission was done. When creation using post method, it is not required. It is extracted from the token of th
```suggestion
| category        | submissionCategory         | It is used to specify what we are submitting as to Microsoft. The possible values are: `notJunk`, `spam`, `phishing` and `malware`.|
| clientSource    | submissionClientSource     | It is used to specify what the source for this submission is. The possible values are: `microsoft` and `other`. |
| contentType     | submissionContentType      | It is used to specify the type of content which is being submitted. The possible values are: `email`, `url`, `file` and `app`.  |
| createdBy       | [security.submissionUserIdentity](../resources/security-submissionuseridentity.md)     | It is use to specify who submitted the email as a threat.|
| createdDateTime | DateTimeOffset             | It is used to specify when the threat submission was created.                                          |
| id              | String                     | It specifies the id of Threat submission. |
| result          | [security.submissionResult](../resources/security-submissionresult.md)          | It is used to specify the result of the analysis which Microsoft had done.  |
| source          | submissionSource           | It is used to specify who is doing the threat submission? Is it a user or an administrator. The possible values are: `administrator` and `user`.  |
| status          | longRunningOperationStatus | It denotes whether the threat submission has been analyzed by Microsoft or not. The possible values are: `notStarted`, `running`, `succeeded`, `failed` and `skipped`. |
| tenantId        | String                     | It denotes the the tenant id from which submission was done. When creation using post method, it is not required. It is extracted from the token of the post API call. |
```

2022-06-10 10:25 UTC, opbld31 commented
Docs Build status updates of commit _[d87364a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d87364ae98b2e9ef33fa16ef13fe16794420b100)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:26 UTC, caigen commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| action             | tenantAllowBlockListAction                  | The tenant allow block list action.                                              |
```suggestion
| action             | tenantAllowBlockListAction                  | It is used to specify whether the tenant allow block list is an allow or block.  |
```

2022-06-10 10:27 UTC, opbld31 commented
Docs Build status updates of commit _[7ddbdbe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ddbdbeded5116ff98543aeebd12b397da6be016)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:29 UTC, caigen commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| action             | tenantAllowBlockListAction                  | The tenant allow block list action.                                              |
```suggestion
| action             | tenantAllowBlockListAction                  | It is used to specify whether the tenant allow block list is an allow or block.                                             |
```

2022-06-10 10:29 UTC, opbld33 commented
Docs Build status updates of commit _[2b8b108](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b8b10836278ce4bf6f5166c8cfeaebf4c8a44d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:31 UTC, caigen commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| action             | tenantAllowBlockListAction                  | The tenant allow block list action. The possible values are: `allow` and `block`.|
```suggestion
| action             | tenantAllowBlockListAction                  | It is used to specify whether the tenant allow block list is an allow or block. The possible values are: `allow` and `block`.|
```

2022-06-10 10:32 UTC, opbld31 commented
Docs Build status updates of commit _[24fc8b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24fc8b7d2d689a4bcadc546df3f75cff25941c6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:34 UTC, opbld34 commented
Docs Build status updates of commit _[a37ab4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a37ab4d20be54149f1f7c71c07f625aa4cd22622)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:34 UTC, caigen commented on api-reference/beta/resources/security-submissionresult.md
> +| userMailboxSetting | userMailboxSetting                | The user mailbox setting flag string which is a comma separated string from a bitfield enum. |
```suggestion
| userMailboxSetting | userMailboxSetting                | It is a flag which specifies the setting for user mailbox denoted by a comma separated string. |
```

2022-06-10 10:36 UTC, opbld31 commented
Docs Build status updates of commit _[07879a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07879a6302c97afeca8e3727ec3b5387c76af010)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:37 UTC, caigen commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| status             | longRunningOperationStatus    | The tenant allow block operation status for this entry. The possible values are: `notStarted`, `running`, `succeeded`, `failed` and `skipped`. |
```suggestion
| status             | longRunningOperationStatus    | It is used to specify whether the tenant allow block list entry creation operation was successful or not. The possible values are: `notStarted`, `running`, `succeeded`, `failed` and `skipped`. |
```

2022-06-10 10:38 UTC, opbld34 commented
Docs Build status updates of commit _[186f756](https://github.com/microsoftgraph/microsoft-graph-docs/commits/186f756b85cd8c4b7f338675c406c5d6e50d6aa6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:41 UTC, opbld33 commented
Docs Build status updates of commit _[d02e635](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d02e6351080680e3b18389791d2b36325f1fbed0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:43 UTC, opbld30 commented
Docs Build status updates of commit _[4dd526f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dd526fa74676c9a875176e3618efa9db646f16c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:45 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message.              |
Resolving this one since it is outdated. Some sentences have been refined.

2022-06-10 10:48 UTC, opbld34 commented
Docs Build status updates of commit _[399aec5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/399aec5faafb067cc97dc7c4725bde5c3e87cefa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:50 UTC, opbld33 commented
Docs Build status updates of commit _[2609b85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2609b858955c146c6dd2f122688efb5b696fec4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:52 UTC, opbld30 commented
Docs Build status updates of commit _[2e2bb1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e2bb1cbe38aafe9f0bef442da6c415ab006876b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:55 UTC, opbld31 commented
Docs Build status updates of commit _[f1db6e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1db6e6f94342b983aa96b9d81ce793204b4c7b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:57 UTC, opbld30 commented
Docs Build status updates of commit _[53308ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53308eac5028ddec8d3c89c03b07e5f1b2f7fea0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 10:57 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isReviewEmailNotificationEnabled         | Boolean | If enabled, system sends email notification to reporter when admin reviews the submission. The default value is `false`. Optional for creation.
```suggestion
| customizedNotificationSenderEmailAddress | String  | It is used to specify the email address of the sender from which email notifications will be sent to end users to inform them whether an email is spam, phish or clean. The default value is `null`. Optional for creation.                   |
| customizedReportRecipientEmailAddress    | String  | It is used to specify the destination where the reported messages from end users will land whenever they report something as phish, junk or not junk. The default value is `null`. Optional for creation. |
| id                                       | String  | Policy id. Only 1 policy is supported by now. The default value is `DefaultReportSubmissionPolicy`. |
| isAlwaysReportEnabledForUsers            | Boolean | It is used to specify whether end users can report a message as spam, phish or junk directly without a confirmation(popup). The default value is `true`.  Optional for creation.          |
| isAskMeEnabledForUsers                   | Boolean | It is used to specify whether end users can confirm using a popup before reporting messages as spam, phish or not junk. The default value is `true`.  Optional for creation.   |
| isCustomizedMessageEnabled               | Boolean | It is used to specify whether the email notifications sent to end users to inform them whether an email is phish, spam or junk is customized or not? The default value is `false`. Optional for creation.                  |
| isCustomizedMessageEnabledForPhishing    | Boolean | It is used to specify whether the customized email notifications sent to end users is to be sent for phish or not. The default value is `false`. Optional for creation. |
| isCustomizedNotificationSenderEnabled    | Boolean | It is used to specify whether we should use the sender email address which we set earlier using customizedNotificationSenderEmailAddress for sending email notifications to end users or not? The default value is `false`. Optional for creation.               |
| isNeverReportEnabledForUsers             | Boolean | It is used to specify whether end users can simply move the message from one folder to another based on the action of spam, phish or not junk without actually reporting it. The default value is `true`. Optional for creation.         |
| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message. The default value is `false`. Optional for creation.        |
| isReportFromQuarantineEnabled            | Boolean | It is used to specify whether end users can submit from the quarantine page or not? The default value is `true`. Optional for creation.              |
| isReportToCustomizedEmailAddressEnabled  | Boolean | It is used to specify whether emails reported by end users should be send to the custom mailbox which was configured above using customizedReportRecipientEmailAddress.  The default value is `false`. Optional for creation.              |
| isReportToMicrosoftEnabled               | Boolean | It is used to specify whether the email messages reported by end users as junk, phish or not junk be sent to Microsoft or not? The default value is `false`. Requried for creation.  |
| isReviewEmailNotificationEnabled         | Boolean | It is used to specify whether an email notification be sent to the end user who reported the email when it has been reviewed by the Admin? The default value is `false`. Optional for creation.  |
```

2022-06-10 10:59 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isOrganizationBrandingEnabled            | Boolean | If enabled, tenant branding logo will be used in review notification message. The default value is `false`. Optional for creation.        |
```suggestion
| isOrganizationBrandingEnabled            | Boolean | It is used to specify whether the branding logo should be used in the email notifications or not which are being sent to end users? The default value is `false`. Optional for creation.        |
```

2022-06-10 10:59 UTC, opbld31 commented
Docs Build status updates of commit _[1a89533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a895335b152e634d712bfdd841ed0e0456eef4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 11:01 UTC, caigen commented on api-reference/beta/resources/security-submissionadminreview.md
> +| reviewResult   | submissionResultCategory | The review result. The possible values are: `notJunk`, `spam`, `phishing`, `malware`, `allowedByPolicy`, `blockedByPolicy`, `spoof`, `unknown` and `noRes
```suggestion
| reviewResult   | submissionResultCategory | It is used to specify what the review result was? The possible values are: `notJunk`, `spam`, `phishing`, `malware`, `allowedByPolicy`, `blockedByPolicy`, `spoof`, `unknown` and `noResultAvailable`.  |
```

2022-06-10 11:01 UTC, opbld32 commented
Docs Build status updates of commit _[d2e33fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2e33fd4f125e714cf094a2dd154f49607f7adb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 11:04 UTC, opbld32 commented
Docs Build status updates of commit _[e80feb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e80feb3dc34ab4e363654165c11de19b99c77d67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 11:06 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +
```suggestion
| internetMessageId            | String                       | It is used to specify the internet message id of the email which is being submitted. This information is present in the email header.                                                       |
| originalCategory             | submissionCategory           | The original category of the submission. The possible values are: `notJunk`, `spam`, `phishing` and `malware`. |
| receivedDateTime             | DateTimeOffset               | It is used to specify the date timestamp of when the email was received?                                                        | 
| recipientEmailAddress        | String                       | It is used to specify the email address (in smtp format) of the recipient who received the email which is being submitted?                                                              |
| sender                       | String                       | It is used to specify the email address of the sender.                                                                    | 
| senderIP                     | String                       | It is used to specify the IP address of the sender who send the email which is being submitted.                                                                 |
| subject                      | String                       | It is used to specify the subject of the email being submitted.                                                                   |
| tenantAllowOrBlockListAction | [security.tenantAllowOrBlockListAction](../resources/security-tenantalloworblocklistaction.md) | It is used to automatically add allows for the components such as URL, file, sender which are deemed bad by Microsoft so that similar messages in the future can be allowed. |

```

2022-06-10 11:06 UTC, opbld33 commented
Docs Build status updates of commit _[77c9f9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77c9f9f1d67b40e4670560384be8b48b4e45003a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 11:09 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| id                                       | String  | Policy id. Only 1 policy is supported by now. The default value is `DefaultReportSubmissionPolicy`. |
```suggestion
| id                                       | String  | As of today, only one id is supported. The default value is `DefaultReportSubmissionPolicy`. |
```

2022-06-10 11:10 UTC, opbld30 commented
Docs Build status updates of commit _[a87576c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a87576cfd00ec4ed5b8c671291767ad8326a4689)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 11:12 UTC, opbld30 commented
Docs Build status updates of commit _[e6f94d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6f94d79f53894edb8b120eb6490f144b881a642)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-10 11:15 UTC, opbld32 commented
Docs Build status updates of commit _[a5398d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5398d51bbe21fc8a2e1f19e1265c66f2d390c62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-13 04:02 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +| isReviewEmailNotificationEnabled         | Boolean | It is used to specify whether an email notification be sent to the end user who reported the email when it has been reviewed by the Admin? The d
```suggestion
| isCustomizedMessageEnabled               | Boolean | It is used to specify whether the email notifications sent to end users to inform them whether an email is phish, spam or junk is customized or not. The default value is `false`. Optional for creation.                  |
| isCustomizedMessageEnabledForPhishing    | Boolean | It is used to specify whether the customized email notifications sent to end users is to be sent for phish or not. The default value is `false`. Optional for creation. |
| isCustomizedNotificationSenderEnabled    | Boolean | It is used to specify whether we should use the sender email address which we set earlier using customizedNotificationSenderEmailAddress for sending email notifications to end users or not. The default value is `false`. Optional for creation.               |
| isNeverReportEnabledForUsers             | Boolean | It is used to specify whether end users can simply move the message from one folder to another based on the action of spam, phish or not junk without actually reporting it. The default value is `true`. Optional for creation.         |
| isOrganizationBrandingEnabled            | Boolean | It is used to specify whether the branding logo should be used in the email notifications or not which are being sent to end users. The default value is `false`. Optional for creation.        |
| isReportFromQuarantineEnabled            | Boolean | It is used to specify whether end users can submit from the quarantine page or not. The default value is `true`. Optional for creation.              |
| isReportToCustomizedEmailAddressEnabled  | Boolean | It is used to specify whether emails reported by end users should be send to the custom mailbox which was configured above using customizedReportRecipientEmailAddress.  The default value is `false`. Optional for creation.              |
| isReportToMicrosoftEnabled               | Boolean | It is used to specify whether the email messages reported by end users as junk, phish or not junk be sent to Microsoft or not. The default value is `false`. Requried for creation.  |
| isReviewEmailNotificationEnabled         | Boolean | It is used to specify whether an email notification be sent to the end user who reported the email when it has been reviewed by the Admin. The default value is `false`. Optional for creation.  |
```

2022-06-13 04:05 UTC, opbld33 commented
Docs Build status updates of commit _[52b549d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52b549d78be20cf39a15fc91b51fb3574b8260a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-13 04:07 UTC, opbld32 commented
Docs Build status updates of commit _[544c9f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/544c9f0b28a2b1a1dc487cd7d3b6a342eeca07bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-13 04:09 UTC, opbld34 commented
Docs Build status updates of commit _[4c48799](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c48799b717abcc72b57f5beeb8bc79b9b665b7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmissionpolicy.md) | :white_check_mark:Succeeded | [V [...]

2022-06-13 05:24 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +You may also specify the following properties when creating an **emailThreatSubmissionPolicy**.
```suggestion
You may also specify the following properties when creating an **emailThreatSubmissionPolicy**. These properties are related with the user reported message settings and to know more check out this documentation - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide
```

2022-06-13 05:28 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +
```suggestion
These properties are related with the user reported message settings and to know more check out this documentation - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide
```

2022-06-13 05:53 UTC, opbld33 commented
Docs Build status updates of commit _[46a83f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46a83f6ccdfe64b26c59faa0401c1f0ae27e66a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-1091404e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-1091404e)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmissionpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main [...]

2022-06-14 01:24 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
> +---
TOC has been added.

2022-06-14 01:28 UTC, opbld33 commented
Docs Build status updates of commit _[3bb8a63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bb8a63f89470302e8a697772470379f61d75928)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-db4e3430)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-db4e3430)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-db4e3430)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-15 15:45 UTC, opbld31 commented
Docs Build status updates of commit _[3ef625f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ef625fade5fd35bb4a0698fd41a1bfeff53ba41)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-422fd254)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-422fd254)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-422fd254)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-15 15:52 UTC, opbld31 commented
Docs Build status updates of commit _[a31fe99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a31fe99ab28ca313391d0a6fb9398f5dcf89c5f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-42b3a7fe)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-42b3a7fe)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-42b3a7fe)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-15 15:57 UTC, opbld32 commented
Docs Build status updates of commit _[2e108a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e108a694899bbcece5a8ccd4ec7a2833e993940)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f14eb1ce)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-f14eb1ce)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-f14eb1ce)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-15 20:15 UTC, opbld33 commented
Docs Build status updates of commit _[3958859](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3958859c1c9622d9d38240d88aae8727743cac3c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a7d63ce8)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-a7d63ce8)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-a7d63ce8)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-16 03:22 UTC, opbld30 commented
Docs Build status updates of commit _[5ae92e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ae92e20e1fd7f56b4037753c3f106981c93dd95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-78cf41fa)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-78cf41fa)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-78cf41fa)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-17 15:49 UTC, opbld30 commented
Docs Build status updates of commit _[3a8bf6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a8bf6b90d378211212b232f5dd3970a905aefaf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7d60d7d3)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-7d60d7d3)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-7d60d7d3)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-17 16:06 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-list.md
> +| Filter                 |     ✓     | `/emailThreats?$filter=source eq 'value'`                    |       |
The Supported and Notes columns are not really meeting any function in the doc. On the other hand, please let me take this to the rest of the team to decide the best way to display the optional query parameters.

2022-06-17 16:08 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-list.md
> +| Filter                 |     ✓     | `/emailThreats?$filter=source eq 'value'`                    |       |
```suggestion
| Pattern                | Syntax                                                       | 
| ---------------------- | ------------------------------------------------------------ |
| Server-side pagination | `@odata.nextLink`                                            | 
| Filter                 | `/emailThreats?$filter=emailSubject eq 'value'`              | 
| Filter                 | `/emailThreats?$filter=sender eq 'value'`                    | 
| Filter                 | `/emailThreats?$filter=id eq 'value'`                        | 
| Filter                 | `/emailThreats?$filter=createdDateTime ge 'value' and createdDateTime lt 'value'` |
| Filter                 | `/emailThreats?$filter=category eq 'value'`                  | 
| Filter                 | `/emailThreats?$filter=createdBy eq 'value'`                 |
| Filter                 | `/emailThreats?$filter=status eq 'value'`                    | 
| Filter                 | `/emailThreats?$filter=source eq 'value'`                    | 
```

2022-06-17 19:41 UTC, isvargasmsft commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +# emailThreatSubmission: review
According to the CSDL, the binding parameter if this action is threatSubmission, not emailThreatSubmission. Could you please clarify and fix accordingly?

2022-06-17 19:44 UTC, opbld31 commented
Docs Build status updates of commit _[e131206](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1312068b63ba488b1d6070f3e4c034eb8df7b21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-79fc2d5a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-79fc2d5a)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-79fc2d5a)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-17 19:47 UTC, isvargasmsft commented on api-reference/beta/resources/enums.md
> +
Missing values:

- skipped
- unknownFutureValue

2022-06-17 19:52 UTC, isvargasmsft commented on api-reference/beta/resources/enums.md
> +### submissionResultDetail values
submissionResultDetail enum type. I'd consider defining this enum in a table or in its own topic to add descriptions to each value. Due to the amount of members, I think it is a good thing to have descriptions for each. 

Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations?anchor=third-option%3A-in-a-separate-dedicated-enum-topic

2022-06-17 20:07 UTC, isvargasmsft commented on changelog/Microsoft.Security.Submission.json
> +﻿{
Missing in this PR:
- Resource topics for the following complex types: tenantAllowBlockListEntryResult, tenantAllowOrBlockListAction, attackSimulationInfo, submissionAdminReview, submissionDetectedFile, submissionResult, submissionUserIdentity,

2022-06-17 20:25 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +      - name: Threat submission
Proposed structure:



Threat submission
- Email threat submission
    - List 
    - Get
    - Create
    - Review
    - Email content threat submission
    - Email URL threat submission
- Email threat submission policy
    - List
    - Get
    - Create
    - Update
    - Delete
- URL threat submission
    - List
    - Get
    - Create
- File threat submission
    - List
    - Get
    - Create
    - File URL threat submission
    - File content threat submission

2022-06-17 20:29 UTC, isvargasmsft requested changes
Hello team, 

Thank you very much for addressing my previous feedback. We are getting close to completion. 

Additional comments:
- Please add resource topics to the complex types. 
- Please review a couple of comments regarding the enumerations. Once is a suggestion, the other is related to missing members.
- Please review my proposal for the TOC structure. 
- Please clarifu whether the Review action belongs to the threatSubmission entity or to emailThreatSubmission. According to the CSDL the binding parameter is threatSubmission. 
- I'll work with my team to define the best way to present the optional query parameters. Usually we use a paragraph/sentence instead of a table. 

Thank you very much, feel free to ping me on the side if you have questions. 

Kind regards, 

Isaac

2022-06-18 02:14 UTC, opbld34 commented
Docs Build status updates of commit _[35f2fd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35f2fd83fefe7cd15c0537812c9bda29b56e7cda)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0f08dbea)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-0f08dbea)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-0f08dbea)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailcontentthreatsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailcontentthreatsubmission?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailthreatsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resource [...]

2022-06-20 23:39 UTC, dhairyya commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +# emailThreatSubmission: review
Gen I think you should take care of this

2022-06-20 23:41 UTC, dhairyya commented on api-reference/beta/resources/enums.md
> +
Gen you should take care of this as well

2022-06-20 23:54 UTC, dhairyya commented on changelog/Microsoft.Security.Submission.json
> +﻿{
Gen cai could you please take care if this

2022-06-21 00:22 UTC, dhairyya commented on api-reference/beta/toc.yml
>          href: resources/security-error-codes.md
```suggestion
      - name: Threat submission
        href: resources/security-threatsubmission.md
        items:
        - name: Email threat submission
          href: resources/security-emailthreatsubmission.md
          items:
          -name: List
          href: api/security-emailthreatsubmission-list.md
          -name: Get
          href: api/security-emailthreatsubmission-get.md
          - name: Create
          href: api/security-emailthreatsubmission-post-emailthreats.md
          - name: Review 
          href: api/security-emailthreatsubmission-review.md
          -name: Email content threat submission
          href: resources/security-emailcontentthreatsubmission.md
          -name: Email URL threat submission
          href: resources/security-emailurlthreatsubmission.md
        - name: Email threat submission policy
          href: resources/security-emailthreatsubmissionpolicy.md
          items:
          - name: List email threat submissions policies
          href: api/security-emailthreatsubmissionpolicy-list.md
          - name: Get email threat submission policy
          href: api/security-emailthreatsubmissionpolicy-get.md
          - name: Create email threat submission policy
          href: api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
          - name: Update email threat submission policy
          href: api/security-emailthreatsubmissionpolicy-update.md
          - name: Delete email threat submission policy
          href: api/security-emailthreatsubmissionpolicy-delete.md
        - name: Url threat submission
          href: resources/security-urlthreatsubmission.md
          items:
          - name: List url threat submissions
          href: api/security-urlthreatsubmission-list.md
          - name: Get url threat submission
          href: api/security-urlthreatsubmission-get.md
          - name: Create url threat submission
          href: api/security-urlthreatsubmission-post-emailthreats.md
        - name: File threat submission
          href: resources/security-filethreatsubmission.md
          items:
          - name: List file threat submissions
          href: api/security-filethreatsubmission-list.md
          - name: Get file threat submission
          href: api/security-filethreatsubmission-get.md
          - name: Create file threat submission
          href: api/security-filethreatsubmission-post-emailthreats.md
          -name: File URL threat submission
          href: resources/security-fileurlthreatsubmission.md
          -name: File content threat submission
          href: resources/security-filecontentthreatsubmission.md
      - name: Errors
        href: resources/security-error-codes.md
```

2022-06-21 01:31 UTC, isvargasmsft commented on api-reference/beta/resources/enums.md
> +|unknownFutureValue|
Please note, to add descriptions to the members we should document the enum outside this file, in either the parent resource file or in its own enum topic. Please follow the guidelines carefully: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations?anchor=document-enumerations

2022-06-22 09:55 UTC, opbld31 commented
Docs Build status updates of commit _[7958382](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79583822732b69d036d748a0ba89c200f7d10480)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-999acf4f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-999acf4f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-999acf4f)

<a id="0817dce4456c16725d5333633847d38f-999acf4f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-999acf4f"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-999acf4f"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220952058566-16242/BuildReport?accessString=cfdb49082cbff9da37b30189899c3cbb5e6bd38cfaf022f61513b8bf1f2bd92b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 11:27 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +Review a threat submission. Only email threats submitted from end users support reviews by an administrator.
```suggestion
Review a threat submission. Only `emailThreatSubmission` submitted from end user supports `review` action now. `review` action for `urlThreatSubmission` and `fileThreatSubmission` are reserved for future usage.
```

2022-06-22 11:29 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +Review a threat submission. Only `emailThreatSubmission` submitted from end user supports `review` action now. `review` action for `urlThreatSubmission` and `fileThreatSubmission` are reserved for fu
```suggestion
Review a threat submission. Only `emailThreatSubmission` submitted from end user supports `review` action now. `review` actions for `urlThreatSubmission` and `fileThreatSubmission` are reserved for future usage. `urlThreatSubmission` and `fileThreatSubmission` have not been supported for end user now.
```

2022-06-22 11:30 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +# emailThreatSubmission: review
some sentences have been added below. url/file threat submission review are reserved for future usage.

2022-06-22 11:31 UTC, opbld34 commented
Docs Build status updates of commit _[98ada80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98ada80661dca7f1d550443330e61a8801cb6261)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-74ddf878)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-74ddf878)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-74ddf878)

<a id="0817dce4456c16725d5333633847d38f-74ddf878"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-74ddf878"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-74ddf878"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221127316913-16242/BuildReport?accessString=890aeacf8147ce7cff6e865e1958c5b91ab20b872718028ee133e408eb1671ee).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 11:35 UTC, opbld33 commented
Docs Build status updates of commit _[6040842](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60408429d0f4acf862e24ba47c39154eafa315bd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-ec9011e9)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-ec9011e9)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-ec9011e9)

<a id="0817dce4456c16725d5333633847d38f-ec9011e9"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-ec9011e9"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-ec9011e9"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221129548682-16242/BuildReport?accessString=a70f09c8e20707196e5a607f037366314c41f2358ae777366d2814a1180e1bb0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 11:47 UTC, caigen commented on api-reference/beta/resources/security-submissionresult.md
> +| detectedFiles      | Collection([security.submissionDetectedFile](../resources/security-submissiondetectedfile.md)) | It is use to specify the files which were detected by Microsoft in the submitte
```suggestion
| detail             | [submissionResultDetail](../resources/security-submissionresultdetail.md)             | It is used to specify the additional details provided by Microsoft to substantiate their analysis result. |
| detectedFiles      | Collection([security.submissionDetectedFile](../resources/security-submissiondetectedfile.md)) | It is use to specify the files which were detected by Microsoft in the submitted emails|
```

2022-06-22 11:48 UTC, opbld30 commented
Docs Build status updates of commit _[538e200](https://github.com/microsoftgraph/microsoft-graph-docs/commits/538e2002b5ac4e0b094d3cfdd26e0fe4a71a8d73)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-02f20f6e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-02f20f6e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-02f20f6e)

<a id="0817dce4456c16725d5333633847d38f-02f20f6e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-02f20f6e"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-02f20f6e"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221145100654-16242/BuildReport?accessString=99279780ef11144a050f77e8407a2a9d106560d08eb9d3cc426d09e159e1a648).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 11:52 UTC, opbld30 commented
Docs Build status updates of commit _[40ee562](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40ee56273b8792669197c9cf3e0fad47b82d7c9d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-5d36113f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-5d36113f)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-5d36113f)

<a id="0817dce4456c16725d5333633847d38f-5d36113f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-5d36113f"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-5d36113f"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221147128733-16242/BuildReport?accessString=d4bd50062b72288c653f74236d1eb3075902a44ad02cb765bc71a12f3f577a26).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 11:55 UTC, opbld31 commented
Docs Build status updates of commit _[aeea33f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aeea33f5e7351ece79bef7982bfa9c5939a6028d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-f32ed806)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-f32ed806)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-f32ed806)

<a id="0817dce4456c16725d5333633847d38f-f32ed806"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-f32ed806"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-f32ed806"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221151080122-16242/BuildReport?accessString=a562adb49ce28342cbc122fc72c52bfc14a85da91e3802d222c9a5564b1a58cc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 12:11 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresultdetail.md
> +| zeroHourAutoPurgeBlocked               | The Reported message was not zapped despite turning malicious after delivery as the message was bad |
```suggestion
| zeroHourAutoPurgeBlocked               | The Reported message was not zapped despite turning malicious after delivery as zap was disabled |
```

2022-06-22 12:12 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresultdetail.md
> +| badReclassifiedAsCannotMakeDecision    | The reported message does not have a decision at the moment  |
```suggestion
| badReclassifiedAsCannotMakeDecision    | The reported message does not have a verdict at the moment  |
```

2022-06-22 15:42 UTC, caigen commented on api-reference/beta/resources/security-submissionresultdetail.md
> +| zeroHourAutoPurgeBlocked               | The Reported message was not zapped despite turning malicious after delivery as the message was bad |
```suggestion
| zeroHourAutoPurgeAllowed               | The reported message was zapped and allowed after delivery as the message was good |
| zeroHourAutoPurgeBlocked               | The Reported message was zapped and blocked after delivery as the message was bad |
```

2022-06-22 15:44 UTC, opbld34 commented
Docs Build status updates of commit _[259c36f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/259c36f4528087c134f52d45fff21c0c027477cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-eab32c01)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-eab32c01)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-eab32c01)

<a id="0817dce4456c16725d5333633847d38f-eab32c01"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-eab32c01"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-eab32c01"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221542304520-16242/BuildReport?accessString=76d375e05e679fefecc688b357b2329f78684804bb017f5bd99393feb153a74a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 15:45 UTC, caigen commented on api-reference/beta/resources/security-submissionresultdetail.md
> +| badReclassifiedAsCannotMakeDecision    |   At the moment Microsoft cannot reach a verdict on the reported message and so please submit again |
```suggestion
| badReclassifiedAsCannotMakeDecision    | At the moment Microsoft cannot reach a verdict on the reported message and so please submit again |
```

2022-06-22 15:47 UTC, opbld31 commented
Docs Build status updates of commit _[cee3696](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cee369622476a602321cf20e065159586a1db201)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-e4941d3e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-e4941d3e)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-e4941d3e)

<a id="0817dce4456c16725d5333633847d38f-e4941d3e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml)
 - **Line 15019, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 15016, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 15017, Column 11**: **[Warning: yaml-duplicate-key]** `````Key '-name' is already defined, remove the duplicate key.`````
 - **Line 15018, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="120f281283db49b9eb8fc6c8b22303c0-e4941d3e"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md)
 - **Line 46, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

<a id="5d4e4c589ccb81784fb8958a2f4276c2-e4941d3e"></a>
### [api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md)
 - **Line 46, Column 90**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221545235675-16242/BuildReport?accessString=12143b2b83100efb49b103d1a612a26b2f5046f5e77551019ad2e8ef106e3c8f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 19:32 UTC, opbld34 commented
Docs Build status updates of commit _[8f7e7e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f7e7e19ffc4c68490bda3a04aa50ba85a0e2559)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f58f346b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-f58f346b)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-f58f346b)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/be [...]

2022-06-22 19:44 UTC, opbld32 commented
Docs Build status updates of commit _[d781830](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7818307b9598c715eddf85d85a83456bbc0b55b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-120f281283db49b9eb8fc6c8b22303c0-49ae1d80)
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) | [Details](#user-content-5d4e4c589ccb81784fb8958a2f4276c2-49ae1d80)
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest [...]

2022-06-22 22:27 UTC, isvargasmsft commented on api-reference/beta/resources/enums.md
> +|unknownFutureValue|
I believe it is the submissionResult resource that has a property of this enum type.

2022-06-22 22:41 UTC, isvargasmsft commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| identity           | String                        | The identity. |
Line 23: Is this description clear enough for developers? I think it generates questions like: The identity of what? What type of information is supposed to be provided in the string?

2022-06-22 22:43 UTC, isvargasmsft commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| entryType          | tenantAllowBlockListEntryType | The entry type of tenant allow block list. The possible values are: `url`, `fileHash`, `sender` and `recipient`.  |
Please remember to always add unknownFutureValue to the list of possible values.

2022-06-23 02:56 UTC, caigen commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| identity           | String                        | The identity. |
```suggestion
| identity           | String                        | The identity of the entry which is generated by tenant allow block list system. |
```

2022-06-23 02:58 UTC, opbld34 commented
Docs Build status updates of commit _[c899dc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c899dc2b60fced4f8ebf7f25fc12aa6b0ba81d56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 06:26 UTC, opbld32 commented
Docs Build status updates of commit _[81120b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81120b090ee3fae9f21725228801f332e759523a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 06:48 UTC, opbld30 commented
Docs Build status updates of commit _[969b9bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/969b9bba0ae9eaa8a6bc94c5f572cbc2c146acb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 06:49 UTC, caigen commented on api-reference/beta/resources/security-submissionresult.md
> +| userMailboxSetting | userMailboxSetting                | Specifies the setting for user mailbox denoted by a comma separated string. |
```suggestion
| userMailboxSetting | [userMailboxSetting](../resources/security-usermailboxsetting.md) | Specifies the setting for user mailbox denoted by a comma separated string. |
```

2022-06-23 06:51 UTC, opbld33 commented
Docs Build status updates of commit _[95148f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95148f582bb35240335411110b32f11512eb1ffb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 06:55 UTC, opbld31 commented
Docs Build status updates of commit _[9eb2b37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9eb2b37b8627ec8a5bef8ab81a2fe3d4ebafae74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 07:28 UTC, caigen commented on api-reference/beta/resources/security-tenantallowblocklistentryresult.md
> +| value              | String                        | It is used to specify the value of the created tenant allow block list entry.  |
```suggestion
| entryType          | tenantAllowBlockListEntryType | The entry type of tenant allow block list. The possible values are: `url`, `fileHash`, `sender`, `recipient` and `unkownFutureValue`.  |
| expirationDateTime | DateTimeOffset                | Specifies when will this entry expire in date time. |
| identity           | String                        | The identity of the entry which is generated by tenant allow block list system. |
| status             | longRunningOperationStatus    | It is used to specify whether the tenant allow block list entry creation operation was successful or not. The possible values are: `notStarted`, `running`, `succeeded`, `failed`, `skipped` and `unkownFutureValue`. |
| value              | String                        | It is used to specify the value of the created tenant allow block list entry.  |
```

2022-06-23 07:29 UTC, caigen commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +| originalCategory             | submissionCategory           | The original category of the submission. The possible values are: `notJunk`, `spam`, `phishing` and `malware`. |
```suggestion
| originalCategory             | submissionCategory           | The original category of the submission. The possible values are: `notJunk`, `spam`, `phishing`, `malware` and `unkownFutureValue`. |
```

2022-06-23 07:31 UTC, opbld34 commented
Docs Build status updates of commit _[02c05ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02c05bad963d3e54951776cb8b17cf3f0e1b2a2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 07:33 UTC, opbld30 commented
Docs Build status updates of commit _[54c911a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54c911ae853e6ed58b251bba3e1f1187bde0180d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 08:16 UTC, caigen commented on api-reference/beta/resources/security-submissionresult.md
> +| category           | submissionResultCategory           | The submission result category. The possible values are: `notJunk`, `spam`, `phishing`, `malware`, `allowedByPolicy`, `blockedByPolicy`, `s
```suggestion
| category           | submissionResultCategory           | The submission result category. The possible values are: `notJunk`, `spam`, `phishing`, `malware`, `allowedByPolicy`, `blockedByPolicy`, `spoof`, `unknown`, `noResultAvailable` and `unkownFutureValue`. |
```

2022-06-23 08:17 UTC, caigen commented on api-reference/beta/resources/security-tenantalloworblocklistaction.md
> +| action             | tenantAllowBlockListAction                  | Specifies whether the tenant allow block list is an allow or block. The possible values are: `allow` and `block`.|
```suggestion
| action             | tenantAllowBlockListAction                  | Specifies whether the tenant allow block list is an allow or block. The possible values are: `allow`, `block` and `unkownFutureValue`.|
```

2022-06-23 08:18 UTC, opbld31 commented
Docs Build status updates of commit _[3cc05d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3cc05d270ab446f9b1a69b4137660dd0fff48591)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 08:21 UTC, opbld33 commented
Docs Build status updates of commit _[f20577c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f20577cb7f61797d5e95e0231f2b231172f05b86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 08:22 UTC, caigen commented on api-reference/beta/resources/security-threatsubmission.md
> +| status          | longRunningOperationStatus | Indicates whether the threat submission has been analyzed by Microsoft. The possible values are: `notStarted`, `running`, `succeeded`, `failed` and `s
```suggestion
| category        | submissionCategory         | Specifies the category of the submission. The possible values are: `notJunk`, `spam`, `phishing`, `malware` and `unkownFutureValue`.|
| clientSource    | submissionClientSource     | Specifies the source of the submission. The possible values are: `microsoft`,  `other` and `unkownFutureValue`. |
| contentType     | submissionContentType      | Specifies the type of content being submitted. The possible values are: `email`, `url`, `file`, `app` and `unkownFutureValue`.  |
| createdBy       | [security.submissionUserIdentity](../resources/security-submissionuseridentity.md)     | Specifies who submitted the email as a threat.|
| createdDateTime | DateTimeOffset             | Specifies when the threat submission was created.                                          |
| id              | String                     | Specifies the id of threat submission. |
| result          | [security.submissionResult](../resources/security-submissionresult.md)          | Specifies the result of the analysis performed by Microsoft.  |
| source          | submissionSource           | Specifies the role of the submitter. The possible values are: `administrator`,  `user` and `unkownFutureValue`.  |
| status          | longRunningOperationStatus | Indicates whether the threat submission has been analyzed by Microsoft. The possible values are: `notStarted`, `running`, `succeeded`, `failed`, `skipped` and `unkownFutureValue`. |
```

2022-06-23 08:25 UTC, opbld31 commented
Docs Build status updates of commit _[485937a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/485937ac620b2a7e0ae0b62ce929166e790a2426)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-23 18:15 UTC, opbld33 commented
Docs Build status updates of commit _[1c4e0b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c4e0b5b8d175ce00c289169e5b20ff41b8d17a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-24 03:53 UTC, caigen commented on api-reference/beta/resources/security-threatsubmission.md
> +| status          | longRunningOperationStatus | Indicates whether the threat submission has been analyzed by Microsoft. The possible values are: `notStarted`, `running`, `succeeded`, `failed`, `skip
```suggestion
| adminReview     | [security.submissionAdminReview](../resources/security-submissionadminreview.md)| Specifies the admin review property which constitutes of who reviewed the user submission, when and what was it identified as. |
| category        | submissionCategory         | Specifies the category of the submission. Supports `$filter = category eq 'value'`. The possible values are: `notJunk`, `spam`, `phishing`, `malware` and `unkownFutureValue`.|
| clientSource    | submissionClientSource     | Specifies the source of the submission. The possible values are: `microsoft`,  `other` and `unkownFutureValue`. |
| contentType     | submissionContentType      | Specifies the type of content being submitted. The possible values are: `email`, `url`, `file`, `app` and `unkownFutureValue`.  |
| createdBy       | [security.submissionUserIdentity](../resources/security-submissionuseridentity.md)     | Specifies who submitted the email as a threat. Supports `$filter = createdBy/email eq 'value'`. |
| createdDateTime | DateTimeOffset  | Specifies when the threat submission was created. Supports `$filter = createdDateTime ge 2022-01-01T00:00:00Z and createdDateTime lt 2022-01-02T00:00:00Z`.             |
| id              | String                     | Specifies the id of threat submission. |
| result          | [security.submissionResult](../resources/security-submissionresult.md)          | Specifies the result of the analysis performed by Microsoft.  |
| source          | submissionSource           | Specifies the role of the submitter. Supports `$filter = source eq 'value'`. The possible values are: `administrator`,  `user` and `unkownFutureValue`.  |
| status          | longRunningOperationStatus | Indicates whether the threat submission has been analyzed by Microsoft. Supports `$filter = status eq 'value'`. The possible values are: `notStarted`, `running`, `succeeded`, `failed`, `skipped` and `unkownFutureValue`. |
```

2022-06-24 03:56 UTC, opbld32 commented
Docs Build status updates of commit _[88e0c87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88e0c87d08d6b8a31c96340e79ed59dcf1cc244a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-24 04:24 UTC, caigen commented on api-reference/beta/api/security-filethreatsubmission-list.md
> +| Filter                 |     ✓     | `/fileThreats?$filter=source eq 'value'` |       |
```suggestion
This method supports `$filter`, `$top`, `$skipToken` and `$count` to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-06-24 04:26 UTC, caigen commented on api-reference/beta/api/security-urlthreatsubmission-list.md
> +| Filter                 |     ✓     | `/urlThreats?$filter=source eq 'value'` |       |
```suggestion
This method supports `$filter`, `$top`, `$skipToken` and `$count` to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-06-24 04:27 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-list.md
> +| Filter                 | `/emailThreats?$filter=source eq 'value'`                    |
```suggestion
This method supports `$filter`, `$top`, `$skipToken` and `$count` to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-06-24 04:28 UTC, opbld30 commented
Docs Build status updates of commit _[9348650](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9348650c3f3e7c7f809bcd6483308843c09dac7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-24 04:31 UTC, opbld30 commented
Docs Build status updates of commit _[195807c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/195807c36da2d6aa53d9d5448186a63e78575ea4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-24 04:33 UTC, opbld33 commented
Docs Build status updates of commit _[22b3100](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22b31004d232bcd31784010afa4ad5b9bb751057)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-24 17:25 UTC, opbld34 commented
Docs Build status updates of commit _[1d79166](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d79166502e715e30e548888b679391465620efc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-06-24 17:27 UTC, isvargasmsft approved these changes

2022-06-28 02:45 UTC, Lauragra commented on api-reference/beta/toc.yml
> +      - name: Threat submission
Please add (preview) to this node to indicate that this API is debuting in beta/not yet available in v1.0.

2022-06-28 02:46 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List
Global: In all TOC nodes, please make sure to list the operations in this order: List, Create, Get, Update, Delete.

2022-06-28 02:46 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List email threat submissions policies
For readability/scannability, please just use the verbs here without repeating the resource name.

2022-06-28 02:47 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Url threat submission
Please use all caps for URL.

2022-06-28 02:47 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List url threat submissions
You can just use the verbs here too.

2022-06-28 02:48 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: File URL threat submission
Why are we exposing these resource types here? Note that we do not expose complex types in the TOC.

2022-06-28 02:52 UTC, Lauragra commented
@caigen , can you please updating the associated concept topics to introduce threat submission, for consistency/completeness: https://docs.microsoft.com/en-us/graph/security-concept-overview and https://docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&preserve-view=true. Thanks.

2022-07-02 01:59 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +          - name: File URL threat submission
Hi @Lauragra, these are entities that inherit from the parent in the top of the node:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/70350956/176982564-44324f33-3f1a-459e-accb-0a68893969fb.png">

Both are the 2 possible forms of File threat submission. Same for Email threat submission.

2022-07-02 02:02 UTC, opbld30 commented
Docs Build status updates of commit _[e5a98da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5a98da751e646eda6a47633882fd1f986dc2131)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-07-02 02:10 UTC, opbld33 commented
Docs Build status updates of commit _[63af7cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63af7cb05c805324dd4197a6a53744b82ed50b29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-07-02 02:24 UTC, opbld31 commented
Docs Build status updates of commit _[6f5404a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f5404a97b02b5a70a6c97d4776ab8d20e88e045)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-attacksimulationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-attacksimulationinfo?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-emailcontentthreatsubmission.md](https://github.com/microsoftgra [...]

2022-07-02 04:20 UTC, opbld31 commented
Docs Build status updates of commit _[f178d98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f178d98d41e6936d69ac3964d14504d0b6797148)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-02 05:02 UTC, opbld30 commented
Docs Build status updates of commit _[e4b9623](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4b9623313942956aa729b35800bbb052e901d22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-05 13:25 UTC, dhairyya commented on api-reference/beta/resources/security-api-overview.md
>  **Threat assessment** - The Microsoft Graph threat assessment API helps organizations to assess the threat received by any user in a tenant. This empowers customers to report spam emails, phishing UR
```suggestion
**Threat assessment** - The Microsoft Graph threat assessment API helps organizations to assess the threat received by any user in a tenant. This empowers customers to report spam and suspicious emails, phishing URLs, or malware attachments they receive to Microsoft. The policy check result and rescan result can help tenant administrators understand the threat scanning verdict and adjust their organizational policy.
```

2022-07-05 13:31 UTC, dhairyya commented on api-reference/beta/resources/security-api-overview.md
> +The Microsoft Graph Threat Submission API helps organizations to submit the threat received by any user in a tenant. This empowers customers to report spam emails, phishing URLs, or malware attachmen
```suggestion
The Microsoft Graph Threat Submission API helps organizations to submit the threat received by any user in a tenant. This empowers customers to report spam or suspicious emails, phishing URLs, or malware attachments they receive to Microsoft. Microsoft check the sample in question by running it through the stack again and checking the organizational policies in play and even sending it to human graders for analysis before generating a result so that tenant administrators understand the threat scanning verdict and adjust their organizational policy.  They can also use it to report legitimate emails as well which are getting blocked. 
```

2022-07-06 03:29 UTC, caigen commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:**  The new **Threat Submission** API will deprecate the Information Protection **Threat Assessment** API. This new version is a unified security threat submission which is redesigned and ad
```suggestion
> **NOTE:**  The new **Threat Submission** API will deprecate the Information Protection **Threat Assessment** API. This new version is a unified security threat submission which is redesigned and adds unified result support, user submission query support, tenant allow block list support, admin review support and app only mode support.
```

2022-07-06 03:30 UTC, caigen commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:**  The **Threat Assessment** will be deprecated by unified security **Threat Submission** as the new version.
```suggestion
> **NOTE:** The **Threat Assessment** will be deprecated by unified security **Threat Submission** as the new version.
```

2022-07-06 03:31 UTC, opbld32 commented
Docs Build status updates of commit _[e0dc37c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0dc37c6811e8ce69f61cac153355331da1d6fae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-06 03:33 UTC, opbld31 commented
Docs Build status updates of commit _[e3a3711](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3a371161dac5497ca5462bbbadaeb6a3dde5cf9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-06 14:13 UTC, isvargasmsft approved these changes

2022-07-08 03:34 UTC, Lauragra commented on api-reference/beta/resources/security-threatsubmission.md
> +It is used to submit suspected spam emails, malware emails, phish emails, malware urls, phish urls, phish email attachments and malware email attachments to Microsoft 365 Defender for Office (MDO), a
Please revise this description. What does the article "It" refer to? Generally, a description of a resource starts with a third-person verb, i.e. "Represents" or "Contains". Note that URL is an acronym and should be capitalized. Also, please verify the use of the acronyms; per branding guidelines, we don't form acronyms for trademarked product names like Microsoft.

2022-07-08 03:38 UTC, Lauragra commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:** The **threat assessment** API set will be deprecated by the unified security [threat submission](#threat-submission) as the new version.
Please revise this note text. If the deprecation is going to happen in the future, please provide a date or a timeline. If the thread assessment API is currently deprecated, please revise the note as follows:

> **Note:** The threat assessment API is currently deprecated. We recommend that you use the [threat submission](#threat-submission) API instead.

Is there a PR to add a deprecation notice to the thread assessment API topics? I notice that those APIs are available in both beta and v1.0. It's more unusual to deprecate APIs that are already GA.

2022-07-08 03:41 UTC, Lauragra commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:** The new **threat submission** API will deprecate the Information Protection **threat assessment** API. This new version is a unified security threat submission which is redesigned and add
This note needs to be rewritten as well, an API does not deprecate another API. Suggested revision:

>**Note:** We recommend that you use this API instead of the deprecated Information Protection threat assessment API. The threat submission API provides unified security threat submission functionality and adds unified result support, user submission query support, tenant allow block list support, admin review support and app-only mode support.

2022-07-08 03:45 UTC, Lauragra commented on api-reference/beta/resources/security-api-overview.md
> +The Microsoft Graph threat submission API helps organizations to submit a threat received by any user in a tenant. This empowers customers to report spam or suspicious emails, phishing URLs, or malwa
Please revise as follows:

The Microsoft Graph threat submission API helps organizations to submit a threat received by any user in a tenant. This empowers customers to report spam or suspicious emails, phishing URLs, or malware attachments they receive to Microsoft. Microsoft checks the submission against the organizational policies in effect and sends it to human graders for analysis. The result then helps tenant administrators understand the threat scanning verdict and adjust their organizational policy. Admins can also use the results to report legitimate emails to prevent them from getting blocked.

2022-07-08 06:27 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| none                                   | Microsoft has no additional details on the result.            |
```suggestion
| none                                   | Microsoft is still investigating the item submitted. Please check later for analysis details  |
```

2022-07-08 06:32 UTC, caigen commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:** The new **threat submission** API will deprecate the Information Protection **threat assessment** API. This new version is a unified security threat submission which is redesigned and add
```suggestion
> **Note: ** We recommend that you use this API instead of the deprecated Information Protection threat assessment API. The threat submission API provides unified security threat submission functionality and adds unified result support, user submission query support, tenant allow block list support, admin review support and app-only mode support.
```

2022-07-08 06:32 UTC, caigen commented on api-reference/beta/resources/security-api-overview.md
> +The Microsoft Graph threat submission API helps organizations to submit a threat received by any user in a tenant. This empowers customers to report spam or suspicious emails, phishing URLs, or malwa
```suggestion
The Microsoft Graph threat submission API helps organizations to submit a threat received by any user in a tenant. This empowers customers to report spam or suspicious emails, phishing URLs, or malware attachments they receive to Microsoft. Microsoft checks the submission against the organizational policies in effect and sends it to human graders for analysis. The result then helps tenant administrators understand the threat scanning verdict and adjust their organizational policy. Admins can also use the results to report legitimate emails to prevent them from getting blocked.
```

2022-07-08 06:35 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| zeroHourAutoPurgeAllowed               | The reported message was zapped and allowed after delivery as the message was good. |
```suggestion
| zeroHourAutoPurgeAllowed               | The reported message was reverse zapped as after delivery the message was found to be good. |
```

2022-07-08 06:35 UTC, caigen commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:** The **threat assessment** API set will be deprecated by the unified security [threat submission](#threat-submission) as the new version.
```suggestion
> **Note:** We recommend that you use the [threat submission](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16242/files#threat-submission) API instead.
```

2022-07-08 06:35 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| zeroHourAutoPurgeBlocked               | The Reported message was zapped and blocked after delivery as the message was bad. |
```suggestion
| zeroHourAutoPurgeBlocked               | The Reported message was zapped as after delivery the message was found to be bad. |
```

2022-07-08 06:36 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| outboundNotRescanned                   | At the Moment Microsoft cannot reach a verdict as the message cannot be analyzed without taking outside the environment or due to other reasons. |
```suggestion
| outboundNotRescanned                   | At the Moment Microsoft cannot reach a verdict as the message cannot be analyzed without taking it outside the environment or due to other reasons. |
```

2022-07-08 06:37 UTC, caigen commented on api-reference/beta/resources/security-api-overview.md
> +> **NOTE:** The **threat assessment** API set will be deprecated by the unified security [threat submission](#threat-submission) as the new version.
Not yet. So let us just add the recommendation. We will follow the API deprecation process after we release this API to v1.0.

2022-07-08 06:39 UTC, opbld32 commented
Docs Build status updates of commit _[9c9bfc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c9bfc67a152d828e9fedf3a01f748b2d00aa252)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-08 06:49 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +It is used to submit suspected spam emails, malware emails, phish emails, malware urls, phish urls, phish email attachments and malware email attachments to Microsoft 365 Defender for Office (MDO), a
```suggestion
Represents threat submission, which is an abstract for representing suspected spam, malware, phish and legitimate emails; malware, phish and legitimate URLs; phish, malware and legitimate email attachments to Microsoft Defender for Office 365(MDO), as well as suspicious files to Microsoft Defender for Endpoint 365(MDE).
```

2022-07-08 06:50 UTC, dhairyya commented on api-reference/beta/resources/security-threatsubmission.md
> +description: "Represents threat submission which is used to submit suspected email, url, file threats to Microsoft 365 Defender."
```suggestion
description: "Represents threat submission which is used to submit suspected email, url, file threats to Microsoft Defender."
```

2022-07-08 06:51 UTC, dhairyya commented on api-reference/beta/resources/security-filethreatsubmission.md
> +
```suggestion
Represents a threat submission related to a file. It is used to submit suspected malware email attachments to Microsoft Defender for Office 365. It could also be used to submit false positive cases which should not have been blocked by Microsoft Defender for Office 365, for example, a safe email attachment.

Currently, file threat submission is routed to Microsoft Defender for Office 365. In future, it may be routed to Microsoft Defender for Endpoint. This is a unified interface for file threat submission no matter where it is routed to.

```

2022-07-08 06:52 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +description: "Reports suspected spam, malware or phishing emails to Microsoft 365 Defender for Office."
```suggestion
description: "Reports suspected spam, malware or phishing emails to Microsoft Defender for Office 365."
```

2022-07-08 06:53 UTC, dhairyya commented on api-reference/beta/resources/security-emailthreatsubmission.md
> +An abstract type to report suspected spam, malware or phishing emails to Microsoft 365 Defender for Office. You can also submit false positive cases, that should not have been blocked by Microsoft 36
```suggestion
An abstract type to report suspected spam, malware or phishing emails to Microsoft Defender for Office 365. You can also submit false positive cases, that should not have been blocked by Microsoft Defender for Office 365, for example, emails incorrectly categorized as junk or spam.
```

2022-07-08 06:53 UTC, opbld31 commented
Docs Build status updates of commit _[2c7fa8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c7fa8faff398d7a6ccc5417e7625bb2aea43614)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-08 06:53 UTC, dhairyya commented on api-reference/beta/resources/security-urlthreatsubmission.md
> +It is used to submit suspected phishing urls to Microsoft 365 Defender for Office (MDO). It could also be used to submit false positive cases which should not have been blocked by MDO, e.g, safe urls
```suggestion
It is used to submit suspected phishing urls to Microsoft Defender for Office 365 (MDO). It could also be used to submit false positive cases which should not have been blocked by MDO, e.g, safe urls.
```

2022-07-08 07:43 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| messageNotFound                        | The reported message could not be analyzed as it cannot be found. |
```suggestion
| allowedByThirdPartyFilters             | The reported message was allowed by Third party filters working with MDO. |
| allowedBySecops                           | The reported message was allowed by advance delivery as part of security operators flow | 
| messageNotFound                        | The reported message could not be analyzed as it cannot be found. |
```

2022-07-08 09:02 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| zeroHourAutoPurgeQuarantineReleased    | The Reported message was released from Quarantine despite being zapped as it turned malicious after delivery. |
```suggestion
| zeroHourAutoPurgeQuarantineReleased    | The reported message was released from Quarantine despite being quarantined due to zap as message turned malicious after delivery. |
```

2022-07-08 09:07 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| quarantineReleasedThenBlocked          | The reported message was blocked as intended but then released from quarantine and blocked by user setting. |
```suggestion
| quarantineReleasedThenBlocked          | The reported message was blocked by user setting after being released from Quarantine. Remove the user setting so that the mail can be released to the inbox |
```

2022-07-08 09:55 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| blockedByConnection                    | The reported message was blocked as the sending IP is on the hosted connection filter policy. |
```suggestion
| Member                                  | Description                                                  |
| :------------------------------------- | :----------------------------------------------------------- |
| none                                   | Microsoft has no additional details on the result to share.            |
| underInvestigation                     | Microsoft is still analyzing the sample and the results should be available soon.      |
| simulatedThreat                        |  The reported message was blocked as it is a phish simulated email send to users for phish education. To configure EOP/MDO to allow it check out advanced delivery|
| allowedBySecOps                          | The reported message was allowed due to advanced delivery flow for security operators mailbox. So, remove it from advanced delivery to block it |
| allowedByThirdPartyFilters             | The reported message was allowed/blocked due third-party filters working in conjunction with EOP/MDO. Configure enhanced filtering so that EOP/MDO can filter accurately   |
| messageNotFound                        | Microsoft cannot provide a verdict on the reported message as Microsoft cannot find the actual message. Please resubmit by uploading the email using submissions in security.microsoft.com |
| urlFileShouldNotBeBlocked              | Microsoft finds the reported entity to be clean. Existing emails containing it have been released. The phish and malware filters will learn from this after a few weeks. Till then to allow it, create an allow entry in Tenant allow/block list if not done already. |
| urlFileShouldBeBlocked                 | Microsoft finds the reported entity to be malicious. Existing emails containing it have been quarantined. The phish and malware filters will learn from this after a few weeks. Till then to block it, create a block entry in Tenant allow/block list if not done already |
| urlFileCannotMakeDecision              | Microsoft cannot reach a verdict at this time. Resubmit it to get a verdict on it after analysis. Use Tenant allow/block list to immediately allow/block it. |
| domainImpersonation                    | The reported message was allowed/blocked due to domain impersonation policy settings. Configure domain impersonation policy so that EOP/MDO can filter accordingly |
| userImpersonation                      | The reported message was allowed/blocked due to user impersonation policy settings. Configure user impersonation policy so that EOP/MDO can filter accordingly |
| brandImpersonation                     | The reported message was allowed/blocked due to brand impersonation policy settings. Configure brand impersonation policy so that EOP/MDO can filter accordingly |
| outboundShouldNotBeBlocked             | The reported outgoing messages has been found clean and Microsoft will update its machine learning based outbound filters in the coming weeks. |
| outboundShouldBeBlocked                | The reported outgoing messages has been found malicious and Microsoft will update its machine learning based outbound filters in the coming weeks. |
| outboundBulk                           | Microsoft find the reported message to be spam/junk. The outbound filters will learn after a few weeks |
| outboundCannotMakeDecision             | Microsoft cannot reach a verdict at this time. Resubmit it to get to a verdict on it after analysis.  |
| outboundNotRescanned                   | Microsoft cannot provide a verdict on the reported outbound message as Microsoft cannot find the actual message. Please resubmit by uploading the email using submissions in security.microsoft.com |
| zeroHourAutoPurgeAllowed               | The reported message was zapped as organization has zero-hour auto purge on. |
| zeroHourAutoPurgeBlocked               | The Reported message could not be zapped as organization has turned off zero-hour auto purge. Turn on zero-hour auto purge for EOP/MDO to zap messages if they turn malicious after delivery|
| zeroHourAutoPurgeQuarantineReleased    | The reported message was released from Quarantine despite being quarantined due to zap as message turned malicious after delivery. |
| onPremisesSkip                         | The reported message cannot be analyzed as this went through a onprem setup of exchange online protection. Configure your hybrid setup so that EOP/MDO can scan messages before delivering to exchange onprem mailboxes |
| allowedByTenantAllowBlockList          | The reported message was allowed as one or more entities in the email are on the tenant allow/ block list. Remove allows from Tenant allow/block list so that EOP/MDO can filter accordingly |
| blockedByTenantAllowBlockList          | The reported message was blocked as one or more entities in the email are on the tenant allow/ block list. Remove blocks from Tenant allow/block list so that EOP/MDO can filter accordingly |
| allowedUrlByTenantAllowBlockList       | The reported URL was allowed as it is on the Tenant allow/block list. Remove the allow from Tenant allow/block list so that EOP/MDO can filter accordingly |
| allowedFileByTenantAllowBlockList      | The reported file was allowed as it is on the Tenant allow/block list. Remove the allow from Tenant allow/block list so that EOP/MDO can filter accordingly |
| allowedSenderByTenantAllowBlockList    | The reported message was allowed as the sender of the email is on the Tenant allow/block list. Remove allow from Tenant allow/block list so that EOP/MDO can filter accordingly|
| allowedRecipientByTenantAllowBlockList | The reported outgoing message was allowed as recipient is on the Tenant allow/block list. Remove allow from Tenant allow/block so that EOP/MDO can filter accordingly |
| blockedUrlByTenantAllowBlockList       | The reported URL was blocked as it is on the Tenant allow/block list. Remove the block from Tenant allow/block list so that EOP/MDO can filter accordingly |
| blockedFileByTenantAllowBlockList      | The reported file was blocked as it is on the Tenant allow/block list. Remove the block from Tenant allow/block list so that EOP/MDO can filter accordingly |
| blockedSenderByTenantAllowBlockList    | The reported message was blocked as the sender of the email is on the Tenant allow/block list. Remove block from Tenant allow/block list so that EOP/MDO can filter accordingly|
| blockedRecipientByTenantAllowBlockList | The reported outgoing message was blocked as recipient is on the Tenant allow/block list. Remove block from Tenant allow/block so that EOP/MDO can filter accordingly |
| allowedByConnection                    | The reported message was allowed as the sending IP is on the hosted connection filter policy. Remove the IP from the hosted connection filter policy so that EOP/MDO can filter accordingly |
| blockedByConnection                    | The reported message was blocked as the sending IP is on the hosted connection filter policy. Remove the IP from the hosted connection filter policy so that EOP/MDO can filter accordingly |
```

2022-07-08 10:07 UTC, dhairyya commented on api-reference/beta/resources/security-submissionresult.md
> +| unknownFutureValue                     | Any future value which is not in use now.                     |
```suggestion
| allowedByExchangeTransportRule         | The reported message was allowed as the organization has a related exchange transport rule. Remove the exchange transport rule so that EOP/MDO can filter accordingly. |
| blockedByExchangeTransportRule         | The reported message was blocked as the organization has a related exchange transport rule. Remove the exchange transport rule so that EOP/MDO can filter accordingly. |
| quarantineReleased                     | The reported message was released from Quarantine despite being quarantined by EOP/MDO |
| quarantineReleasedThenBlocked          | The reported message was blocked by user setting after being released from Quarantine. Remove the user setting so that the mail can be released to the inbox |
| junkMailRuleDisabled                   | The reported message was bound to be delivered to the junk folder, but junk folder has been disabled. Turn on junk folder setting so that EOP/MDO can deliver emails accordingly |
| allowedByUserSetting                   | The reported message was allowed due to user safe or trusted sender setting in outlook. Remove the safe or trusted sender setting so that EOP/MDO can filter accordingly |
| blockedByUserSetting                   | The reported message was blocked due to user blocked or trusted sender setting in outlook. Remove the blocked or trusted sender setting so that EOP/MDO can filter accordingly |
| allowedByTenant                        | The reported message was allowed due to tenant policy or policy action settings. Review the EOP/MDO policy or policy action settings so that EOP/MDO can filter accordingly |
| blockedByTenant                        | The reported message was blocked due to tenant policy or policy action settings. Review the EOP/MDO policy or policy action settings so that EOP/MDO can filter accordingly |
| invalidFalsePositive                   | The reported message is already allowed by EOP/MDO.                  |
| invalidFalseNegative                   | The reported message is already blocked by EOP/MDO.                     |
| spoofBlocked                           | The reported message has been determined by spoof by our system and so blocked. Create a spoof allow in Tenant allow/block list so that EOP/MDO can allow emails from this spoofed sender    |
| goodReclassifiedAsBad                  | Microsoft finds the reported message to be malicious. Existing emails have been quarantined. The phish and malware filters will learn from this after a few weeks. Till then to block it, create a block entry in Tenant allow/block list if not done already |
| goodReclassifiedAsBulk                 | Microsoft finds the reported message to be spam. The spam and bulk filters will learn from this after a few weeks. Till then to block it, create a block entry in Tenant allow/block list if not done already |
| goodReclassifiedAsGood                 | Microsoft finds the reported message to be clean. If you disagree with this verdict resubmit the email. Till then to block it, create a block entry in Tenant allow/block list if not done already |
| goodReclassifiedAsCannotMakeDecision   | Microsoft cannot reach a verdict at this time. Resubmit it to get a verdict on it after analysis. Use Tenant allow/block list to immediately block it if not done already. |
| badReclassifiedAsGood                  | Microsoft finds the reported message to be clean. Existing emails have been released. The phish and malware filters will learn from this after a few weeks. Till then to allow it, create an allow entry in Tenant allow/block list if not done already |
| badReclassifiedAsBulk                  | Microsoft finds the reported message to be spam. The spam and bulk filters will learn from this after a few weeks. Till then to allow it, create an allow entry in Tenant allow/block list if not done already |
| badReclassifiedAsBad                   | Microsoft finds the reported message to be malicious. If you disagree with this verdict resubmit the email. Till then to allow it, create an allow entry in Tenant allow/block list if not done already |
| badReclassifiedAsCannotMakeDecision    | Microsoft cannot reach a verdict at this time. Resubmit it to get a verdict on it after analysis. Use Tenant allow/block list to immediately allow it if not done already. |
| unknownFutureValue                     | Any future value which is not in use now.                     |
```

2022-07-08 10:28 UTC, opbld31 commented
Docs Build status updates of commit _[eb98a66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb98a66fc425bc75ab39de2b0c0d4ba45dca9378)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-08 10:31 UTC, opbld32 commented
Docs Build status updates of commit _[cc375a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc375a921f4d4d21dde314427bb93bf80bd7b11a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-08 10:34 UTC, opbld33 commented
Docs Build status updates of commit _[f26e88b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f26e88b96e2cb35d1deb0b54b8efdd9b4cb2d418)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-08 10:37 UTC, opbld30 commented
Docs Build status updates of commit _[eaf6b69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaf6b69a9689003bda138c1d8efbb3e398802f3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-08 10:38 UTC, caigen commented on api-reference/beta/resources/security-submissionresult.md
> +| blockedByConnection                    | The reported message was blocked as the sending IP is on the hosted connection filter policy. |
```suggestion
| Member                                  | Description                                                  |
| :------------------------------------- | :----------------------------------------------------------- |
| none                                   | Microsoft has no additional details on the result to share.            |
| underInvestigation                     | Microsoft is still analyzing the sample and the results should be available soon.      |
| simulatedThreat                        |  The reported message was blocked as it is a phish simulated email send to users for phish education. To configure EOP/MDO to allow it check out advanced delivery|
| allowedBySecOps                          | The reported message was allowed due to advanced delivery flow for security operators mailbox. So, remove it from advanced delivery to block it |
| allowedByThirdPartyFilters             | The reported message was allowed/blocked due third-party filters working in conjunction with EOP/MDO. Configure enhanced filtering so that EOP/MDO can filter accurately   |
| messageNotFound                        | Microsoft cannot provide a verdict on the reported message as Microsoft cannot find the actual message. Please resubmit by uploading the email using submissions in security.microsoft.com |
| urlFileShouldNotBeBlocked              | Microsoft finds the reported entity to be clean. Existing emails containing it have been released. The phish and malware filters will learn from this after a few weeks. Till then to allow it, create an allow entry in Tenant allow/block list if not done already. |
| urlFileShouldBeBlocked                 | Microsoft finds the reported entity to be malicious. Existing emails containing it have been quarantined. The phish and malware filters will learn from this after a few weeks. Till then to block it, create a block entry in Tenant allow/block list if not done already |
| urlFileCannotMakeDecision              | Microsoft cannot reach a verdict at this time. Resubmit it to get a verdict on it after analysis. Use Tenant allow/block list to immediately allow/block it if not already done. |
| domainImpersonation                    | The reported message was allowed/blocked due to domain impersonation policy settings. Configure domain impersonation policy so that EOP/MDO can filter accordingly |
| userImpersonation                      | The reported message was allowed/blocked due to user impersonation policy settings. Configure user impersonation policy so that EOP/MDO can filter accordingly |
| brandImpersonation                     | The reported message was allowed/blocked due to brand impersonation policy settings. Configure brand impersonation policy so that EOP/MDO can filter accordingly |
| outboundShouldNotBeBlocked             | The reported outgoing messages has been found clean and Microsoft will update its machine learning based outbound filters in the coming weeks. |
| outboundShouldBeBlocked                | The reported outgoing messages has been found malicious and Microsoft will update its machine learning based outbound filters in the coming weeks. |
| outboundBulk                           | Microsoft find the reported message to be spam/junk. The outbound filters will learn after a few weeks |
| outboundCannotMakeDecision             | Microsoft cannot reach a verdict at this time. Resubmit it to get to a verdict on it after analysis.  |
| outboundNotRescanned                   | Microsoft cannot provide a verdict on the reported outbound message as Microsoft cannot find the actual message. Please resubmit by uploading the email using submissions in security.microsoft.com |
| zeroHourAutoPurgeAllowed               | The reported message was zapped as organization has zero-hour auto purge on. |
| zeroHourAutoPurgeBlocked               | The Reported message could not be zapped as organization has turned off zero-hour auto purge. Turn on zero-hour auto purge for EOP/MDO to zap messages if they turn malicious after delivery|
| zeroHourAutoPurgeQuarantineReleased    | The reported message was released from Quarantine despite being quarantined due to zap as message turned malicious after delivery. |
| onPremisesSkip                         | The reported message cannot be analyzed as this went through a onprem setup of exchange online protection. Configure your hybrid setup so that EOP/MDO can scan messages before delivering to exchange onprem mailboxes |
| allowedByTenantAllowBlockList          | The reported message was allowed as one or more entities in the email are on the tenant allow/ block list. Remove allows from Tenant allow/block list so that EOP/MDO can filter accordingly |
| blockedByTenantAllowBlockList          | The reported message was blocked as one or more entities in the email are on the tenant allow/ block list. Remove blocks from Tenant allow/block list so that EOP/MDO can filter accordingly |
| allowedUrlByTenantAllowBlockList       | The reported URL was allowed as it is on the Tenant allow/block list. Remove the allow from Tenant allow/block list so that EOP/MDO can filter accordingly |
| allowedFileByTenantAllowBlockList      | The reported file was allowed as it is on the Tenant allow/block list. Remove the allow from Tenant allow/block list so that EOP/MDO can filter accordingly |
| allowedSenderByTenantAllowBlockList    | The reported message was allowed as the sender of the email is on the Tenant allow/block list. Remove allow from Tenant allow/block list so that EOP/MDO can filter accordingly|
| allowedRecipientByTenantAllowBlockList | The reported outgoing message was allowed as recipient is on the Tenant allow/block list. Remove allow from Tenant allow/block so that EOP/MDO can filter accordingly |
| blockedUrlByTenantAllowBlockList       | The reported URL was blocked as it is on the Tenant allow/block list. Remove the block from Tenant allow/block list so that EOP/MDO can filter accordingly |
| blockedFileByTenantAllowBlockList      | The reported file was blocked as it is on the Tenant allow/block list. Remove the block from Tenant allow/block list so that EOP/MDO can filter accordingly |
| blockedSenderByTenantAllowBlockList    | The reported message was blocked as the sender of the email is on the Tenant allow/block list. Remove block from Tenant allow/block list so that EOP/MDO can filter accordingly|
| blockedRecipientByTenantAllowBlockList | The reported outgoing message was blocked as recipient is on the Tenant allow/block list. Remove block from Tenant allow/block so that EOP/MDO can filter accordingly |
| allowedByConnection                    | The reported message was allowed as the sending IP is on the hosted connection filter policy. Remove the IP from the hosted connection filter policy so that EOP/MDO can filter accordingly |
| blockedByConnection                    | The reported message was blocked as the sending IP is on the hosted connection filter policy. Remove the IP from the hosted connection filter policy so that EOP/MDO can filter accordingly |
```

2022-07-08 10:40 UTC, opbld31 commented
Docs Build status updates of commit _[85b60ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85b60ff02e21f7655ddd3dad0ef309bad4103573)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 04:00 UTC, Lauragra commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +title: "Create emailThreatSubmission"
Is this the correct file name? There doesn't appear to be a nav property named **emailThreats** on the emailThreatSubmission resource.

2022-07-13 04:13 UTC, Lauragra commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +The **emailContentThreatSubmission** and **emailUrlThreatSubmission** resources are both subtypes of the **emailThreatSubmission** entity and helps to make submission in different ways.
Can you please clarify the phrase "and helps to make submission in different ways"? Maybe this is what you mean:

"Choose what to include in the request body based on the following:"

2022-07-13 04:13 UTC, opbld31 commented
Docs Build status updates of commit _[28b9716](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28b97160f842fe72889abacea8ccb274b0ab360e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 04:16 UTC, Lauragra commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +Review actions for [urlThreatSubmission](../resources/security-urlthreatsubmission.md) and [fileThreatSubmission](../resources/security-filethreatsubmission.md) objects are not supported for end user
By "are not supported for end user", do you mean "Review actions for [urlThreatSubmission](../resources/security-urlthreatsubmission.md) and [fileThreatSubmission](../resources/security-filethreatsubmission.md) objects submitted by end users are not supported"?

2022-07-13 04:20 UTC, opbld32 commented
Docs Build status updates of commit _[3432ab1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3432ab1884d21924f26f4ed254830babfbc9f4f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 04:22 UTC, opbld30 commented
Docs Build status updates of commit _[162a0e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/162a0e3cff6ce1c47e6892157d23f42187e9e28f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 04:25 UTC, Lauragra commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +title: "Create emailThreatSubmissionPolicy"
I'm not sure that this file name is correct. It looks like emailThreatSubmissionPolicies is a nav property of threatSubmissionRoot, in which case we would have the file name security-emailthreatsubmissionroot-post-emailthreatsubmissionpolicies? I actually think the file name should just be security-emailthreatsubmissionpolicy-post.

2022-07-13 04:29 UTC, opbld33 commented
Docs Build status updates of commit _[8f59e96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f59e962c28cc5a449c99e5a3f3ea71188661b80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 04:33 UTC, Lauragra commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +> **Note:** Use HTTP `PATCH` request. HTTP `PUT` is not supported.
Curious why we need this note since we show in the syntax that it's a PATCH request? If there's a reason to keep the note, please revise as: "Use HTTP `PATCH` for this request. HTTP `PUT` is not supported."

2022-07-13 04:34 UTC, Lauragra commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +> **Note:** The response object shown here might be shortened for readability.
Global: When there's no response body, please be sure to remove this note.

2022-07-13 05:44 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
> +The **emailContentThreatSubmission** and **emailUrlThreatSubmission** resources are both subtypes of the **emailThreatSubmission** entity and helps to make submission in different ways.
```suggestion
The **emailContentThreatSubmission** and **emailUrlThreatSubmission** resources are both subtypes of the **emailThreatSubmission** entity. Choose what to include in the request body based on the following:  
```

2022-07-13 05:47 UTC, opbld33 commented
Docs Build status updates of commit _[b3f0a71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3f0a71da9a7d21b68022cf65057563de7c2ea5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 05:47 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +Review actions for [urlThreatSubmission](../resources/security-urlthreatsubmission.md) and [fileThreatSubmission](../resources/security-filethreatsubmission.md) objects are not supported for end user
Yes. since current there is no urlThreatSubmisson and fileThreatSubmission from end user as our system has not supported it.

2022-07-13 05:49 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
> +title: "Create emailThreatSubmissionPolicy"
@Lauragra  the file name is generated **by the graph pipeline**.  The url path is /security/threatSubmission/emailThreatSubmissionPolices.

2022-07-13 05:52 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +> **Note:** Use HTTP `PATCH` request. HTTP `PUT` is not supported.
@Lauragra since @isvargasmsft commented that if both are supported but only patch is supported.   
Let me remove it. + @isvargasmsft  for visibility.

2022-07-13 05:53 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +> **Note:** Use HTTP `PATCH` request. HTTP `PUT` is not supported.
```suggestion
```

2022-07-13 05:55 UTC, opbld30 commented
Docs Build status updates of commit _[d986f0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d986f0df58e5992b2ea546b6d294e47f6422605e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 05:55 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +> **Note:** The response object shown here might be shortened for readability.
```suggestion
```

2022-07-13 05:57 UTC, caigen commented on api-reference/beta/api/security-emailthreatsubmission-review.md
> +> **Note:** The response object shown here might be shortened for readability.
```suggestion
```

2022-07-13 05:58 UTC, opbld31 commented
Docs Build status updates of commit _[02631bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02631bc3684efa288c1778c1d130755c3c2d4cc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-13 06:02 UTC, opbld31 commented
Docs Build status updates of commit _[97d935e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97d935e88572c4fcd37e05c024642df3deed44c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:00 UTC, opbld31 commented
Docs Build status updates of commit _[6c496ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c496adcf922481ac9ec3d59858cdafffb5fa672)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:02 UTC, opbld34 commented
Docs Build status updates of commit _[0343b47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0343b47c119f91989129aa484f798f3550ecf23b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:05 UTC, opbld33 commented
Docs Build status updates of commit _[8a2a630](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a2a6304e0373181dc13b7183a57c281b32dad53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:07 UTC, opbld33 commented
Docs Build status updates of commit _[8514f90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8514f904cf486a44f667bbef3227f9996ca4eee2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:11 UTC, opbld30 commented
Docs Build status updates of commit _[13de6a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13de6a588571e42865cb471c4c1e4aceced576b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:13 UTC, opbld32 commented
Docs Build status updates of commit _[08dccbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08dccbdf49ab40b28f322edde5bd71343a791a2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:15 UTC, opbld34 commented
Docs Build status updates of commit _[fcec1af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcec1af716cf190a0a356fe29b89a819b585924b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:18 UTC, opbld34 commented
Docs Build status updates of commit _[bb5a9f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb5a9f6f4fafa30e6c3858c1d979cedfd74f47ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:20 UTC, opbld30 commented
Docs Build status updates of commit _[76bb807](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76bb8076a3a4a5d3d14c2fe6d4174cd5a468e93d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-emailthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-delete?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-update?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-post-emailthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-emailthreatsubmission-review.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-emailthreatsubmission-review.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-emailthreatsubmission-review?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-filethreatsubmission-post-filethreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-filethreatsubmission-post-filethreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-filethreatsubmission-post-filethreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-get?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-list?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-urlthreatsubmission-post-urlthreats?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/caigen-security-threat-submission-beta/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-16242) (graph-rest-beta) |
[api-reference/beta/resources/security-attacksimulationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cai [...]

2022-07-19 04:31 UTC, merged