Cloud pc/add windows settings
microsoftgraph/microsoft-graph-docs pull request #16255
Opened 2022-03-23 03:00 UTC by Guoan-Tang

add windowsSettings into CloudPCOrganizationSetting

2022-03-23 03:02 UTC, opbld30 commented
Docs Build status updates of commit _[e81d59a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e81d59a3cb9af81f7f50a9d9680895ee1995cc3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203230300092146-16255%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T03%3A02%3A04Z&sr=b&sp=r&sig=xWHJUVC2OEohXmmYCCQp5H3TcDT%2FCE5aSkWNMfZ5wmU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 06:52 UTC, RuiHou105 requested changes
Hi @Guoan-Tang , could you please create a roadmap workitem and attach it in the description? You can follow this [guidance ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211772/Content-review-process-summary).  Here is a roadmap workitem example https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/11551/

2022-03-29 05:36 UTC, Guoan-Tang commented
**Roadmap workitem**:

https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/13582
[Devices and apps][Cloud PC] Add properties windowsSettings to cloudPcOrganizationSettings

2022-03-30 03:13 UTC, AshleyYangSZ approved these changes

2022-03-30 06:39 UTC, RuiHou105 approved these changes

2022-04-06 17:06 UTC, Danielabom approved these changes
This PR has been reviewed.

2022-04-07 04:25 UTC, Lauragra commented on api-reference/beta/api/cloudpcorganizationsettings-update.md
> +|windowsSettings|cloudPcWindowsSettings|The settings to apply to Windows while creating Cloud PCs for this organization. The default value is a WindowsSettings with default language value "en-US".|
The second sentence is a little confusing - by this do we mean, "The default language value is `en-us`? If so, please update.

2022-04-07 04:27 UTC, Lauragra commented on api-reference/beta/resources/cloudpcorganizationsettings.md
> +|windowsSettings|[cloudPcWindowsSettings](../resources/cloudpcwindowssettings.md)|Represents the Cloud PC organization settings for a tenant. A tenant has only one cloudPcOrganizationSettings object.
Please make the resource name cloudPcOrganizationSettings bold.

2022-04-07 05:17 UTC, opbld30 commented
Docs Build status updates of commit _[d850015](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8500152885e222d1045e68a22b335e02e0c1782)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204070515525454-16255%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T05%3A17%3A42Z&sr=b&sp=r&sig=Vv5A4o5u%2FBIl3e%2B2nuKnwvHjoPGrK%2BKKzUt%2F8%2F88YzU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 05:18 UTC, Guoan-Tang commented on api-reference/beta/api/cloudpcorganizationsettings-update.md
> +|windowsSettings|cloudPcWindowsSettings|The settings to apply to Windows while creating Cloud PCs for this organization. The default value is a WindowsSettings with default language value "en-US".|
Nice point, had fixed it

2022-04-08 03:39 UTC, opbld33 commented
Docs Build status updates of commit _[bd8f112](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd8f112b927ad63760beed44617ca20e45ddab9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-16255) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/addWindowsSettings/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204080336497175-16255%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T03%3A39%3A10Z&sr=b&sp=r&sig=X64XdmW%2BK2oGajyQdb4oXGU0SdLOcQIi6uP5rSAkd1s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 03:45 UTC, merged