Cloud PC/Add external partner settings
microsoftgraph/microsoft-graph-docs pull request #16264
Opened 2022-03-23 13:09 UTC by Shaowei-Dong

2022-03-23 13:11 UTC, opbld30 commented
Docs Build status updates of commit _[5e962f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e962f8a62f9911524992202d22a7233b17cd43c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d4f38a2d)
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d4f38a2d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml)
 - **Line 10229, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpcexternalpartnersettings.md'.`````
 - **Line 10229, Column 11**: **[Warning: missing-attribute]** `````Missing required attribute: 'name'.`````
 - **Line 10234, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcexternalpartnersettings-get.md'.`````
 - **Line 10238, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcexternalpartnersettings-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203231309348362-16264%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T13%3A11%3A45Z&sr=b&sp=r&sig=OYBqH9fwhP7dJqV%2Fc4uSlaT5XkDyq4avJoI9MUIJoBU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 14:23 UTC, opbld30 commented
Docs Build status updates of commit _[8af74d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8af74d6cb4d2a90a0fada6439d4a95532a231648)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203231421137484-16264%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T14%3A23%3A26Z&sr=b&sp=r&sig=KxK4EUFNPCTgBgahlRWuRCfSwAOatCWNbgDyLbqjsWw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 03:20 UTC, Yitengyu commented on api-reference/beta/resources/cloudpcexternalpartnersetting.md
> +Represents a external partner setting on Cloud PC.
should be `an` external partner setting

2022-03-24 03:20 UTC, Yitengyu commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +  "status": "active",
It should be `available` once it's created

2022-03-24 03:20 UTC, Yitengyu commented on api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md
> +      "status": "unresponsive",
`unresponsive` is not of the status enum

2022-03-24 04:56 UTC, timefrozen19 commented on api-reference/beta/toc.yml
> +        - name: Cloud PC external partner settings
No s to be consistent

2022-03-24 04:58 UTC, timefrozen19 commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +|partnerId|String|The external partner ID. Required|
period at the end

2022-03-24 05:04 UTC, timefrozen19 commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +  "enableConnection": true,
extra comma

2022-03-24 05:57 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcexternalpartnersetting-get.md
> +>**Note:** The response object shown here might be shortened for readability.
You can remove this extra note.

2022-03-24 05:59 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcexternalpartnersetting-update.md
> +>**Note:** The response object shown here might be shortened for readability.
You can remove this extra note here and other places within this PR.

2022-03-24 06:04 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +
As property `status `is required, why not provide it when creating a cloudPcExternalPartnerSetting oject?

2022-03-24 06:08 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcexternalpartnersetting-get.md
> +  "status": "active",
The enum `cloudPcExternalPartnerStatus `only includes: notAvailable, available, healthy, unhealthy. But why you use active in some examples of this PR?

2022-03-24 06:10 UTC, RuiHou105 requested changes
@Shaowei-Dong  
1.could you please resolve the comments in your PR? 
2.Please follow this [guidance ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211772/Content-review-process-summary)to create a roadmap workitem and then attach it into the description here. Thanks.

2022-04-20 03:18 UTC, Shaowei-Dong commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +
status is required in this entity, but the value comes from some mechanism so user can't assign any value to it.

2022-04-20 03:22 UTC, Shaowei-Dong commented on api-reference/beta/api/cloudpcexternalpartnersetting-get.md
> +  "status": "active",
Updated

2022-04-20 03:23 UTC, Shaowei-Dong commented on api-reference/beta/resources/cloudpcexternalpartnersetting.md
> +Represents a external partner setting on Cloud PC.
updated

2022-04-20 03:23 UTC, Shaowei-Dong commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +  "status": "active",
updated

2022-04-20 03:23 UTC, Shaowei-Dong commented on api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md
> +      "status": "unresponsive",
updated

2022-04-20 03:23 UTC, Shaowei-Dong commented on api-reference/beta/toc.yml
> +        - name: Cloud PC external partner settings
removed

2022-04-20 03:24 UTC, Shaowei-Dong commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +|partnerId|String|The external partner ID. Required|
added

2022-04-20 03:24 UTC, Shaowei-Dong commented on api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
> +  "enableConnection": true,
removed

2022-04-20 03:24 UTC, Shaowei-Dong commented on api-reference/beta/api/cloudpcexternalpartnersetting-get.md
> +>**Note:** The response object shown here might be shortened for readability.
removed

2022-04-20 03:25 UTC, opbld31 commented
Docs Build status updates of commit _[50b6d5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50b6d5c5a4f5c62f79adc91500c9bce991d3afb0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204200323238062-16264%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T03%3A25%3A08Z&sr=b&sp=r&sig=39YQoGh2f%2FSj461yuXBsswrYhHUMo4FnTrYU5bUJDo0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 05:39 UTC, RuiHou105 commented
@Shaowei-Dong 
1.Some comments are not resolved. Please help resolve them to move forward the review process.
2.Please create a roadmap workitem for your change and attach the workitem NO. in the comment. Here is an example:

2022-05-20 05:40 UTC, RuiHou105 approved these changes

2022-06-23 06:26 UTC, opbld32 commented
Docs Build status updates of commit _[50b6d5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50b6d5c5a4f5c62f79adc91500c9bce991d3afb0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a7dea8c1)

<a id="a7dea8c1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230626282551-16264/BuildReport?accessString=c4829208317908ab03cc64da837004cedcf0a6948d72b079fb8a31f50d2d57e7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 07:53 UTC, AshleyYangSZ commented on api-reference/beta/resources/virtualendpoint.md
> +|[List externalPartnerSettings](../api/virtualendpoint-list-externalpartnersettings.md)|[cloudPcExternalPartnerSetting](../resources/cloudpcexternalpartnersetting.md) collection|Get a list of the [cl
Will externalPartnerSettings support get by ID,  update and delete API? If yes please add here, if no, please remove the get, update, delete API files.

2022-06-23 07:54 UTC, AshleyYangSZ requested changes
Do you support get,update, and delete externalPartnerSetting APIs? If no please remove these files

2022-06-23 13:54 UTC, Shaowei-Dong commented on api-reference/beta/resources/virtualendpoint.md
> +|[List externalPartnerSettings](../api/virtualendpoint-list-externalpartnersettings.md)|[cloudPcExternalPartnerSetting](../resources/cloudpcexternalpartnersetting.md) collection|Get a list of the [cl
Do you mean here? I've added them in cloudpcexternalpartnersetting.md file.

2022-06-24 11:59 UTC, opbld31 commented
Docs Build status updates of commit _[2fa95f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fa95f1b503714b69edbe7c7879796a39f20c169)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206241157300596-16264/BuildReport?accessString=baa2129af0b96129880afdb135bee14279dc4a40244f9b274cd4e0afa42d9e42).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 09:24 UTC, AshleyYangSZ approved these changes

2022-07-12 23:18 UTC, JarbasHorst commented
Hello @Shaowei-Dong, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [17664](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17664) into your branch to include my fixes and before addressing my comments.

2022-07-13 00:52 UTC, opbld34 commented
Docs Build status updates of commit _[b8916f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8916f6fdf8509145ccde0b275d2dc09b710ce74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130049395911-16264/BuildReport?accessString=4338f1c8c4ae6869e9287c579dec6734e4eb56b7aa91d39fceb239ac3cd5723d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 10:27 UTC, Shaowei-Dong commented on api-reference/beta/api/cloudpcexternalpartnersetting-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/externalPartnerSettings/{id}
thanks, updated.

2022-07-14 10:27 UTC, Shaowei-Dong commented on api-reference/beta/api/cloudpcexternalpartnersetting-update.md
> +|enableConnection|Boolean|Enable or disable external partner connection. If true, external partner api will accept incoming calls from external partner. Required.|
prefer to the first one, updated in 3 files.

2022-07-14 10:29 UTC, opbld30 commented
Docs Build status updates of commit _[111b0f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/111b0f59cb93f85f5e1020e23c975b222649e11e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207141026483484-16264/BuildReport?accessString=58ab4274a3c81fcf370873ddc70a68d78948776fc9f197d4507aa0a7a3a8c263).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 23:49 UTC, opbld31 commented
Docs Build status updates of commit _[7e1c05a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e1c05a2497adef0e7b328717969366fa11d19cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207182347317139-16264/BuildReport?accessString=7b3a5c01ac2256ee4b43e90f19122358d44ea5f9eda0f35d5b21cb9b1415f372).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:36 UTC, opbld32 commented
Docs Build status updates of commit _[6e80bd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e80bd1e958ca42df05d24b3f2743063e3b7c533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211234118366-16264/BuildReport?accessString=5fab5997d8254140c19a10f5c99c0c22b4aee48845605b3f106abc2a686d1788).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 06:24 UTC, Shaowei-Dong commented
@Lauragra @MSFT-Jarbas Please let me know if you any question/comments on this PR

2022-07-22 11:04 UTC, JarbasHorst commented
Hi @isvargasmsft, can you please final check this PR and set the label "content review complete" if possible?

2022-07-22 13:58 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcexternalpartnersetting.md
> +|statusDetails|String|Status details message.|
Please indicate in the description of the properties which ones support $filter.

2022-07-22 14:01 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md
> +## Examples
Could you please include a second example using the $select query parameter? In general, we have been promoting the use of $select in Graph and that includes having examples in our docs.

2022-07-22 14:03 UTC, isvargasmsft requested changes
HEllo @Shaowei-Dong 

Excellent work in this PR. Before we merge, would you be so kind to include an example using the $select parameter to the list operation? 
In addition, please indicate which properties support filter in the description of the properties table. 

Kind regards, 

Isaac

2022-07-25 04:22 UTC, opbld32 commented
Docs Build status updates of commit _[7d984ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d984bae2308ba621af53351f6cc9ee38cca0a65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207250420396438-16264/BuildReport?accessString=234b4fa8129522b699ae2ffd5988a887211979f5cb0865c119d50065ef33d418).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 04:35 UTC, Shaowei-Dong commented on api-reference/beta/resources/cloudpcexternalpartnersetting.md
> +|statusDetails|String|Status details message.|
$filter added

2022-07-25 04:35 UTC, Shaowei-Dong commented on api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md
> +## Examples
a second example added

2022-07-27 07:54 UTC, Shaowei-Dong commented
@isvargasmsft please help review this PR, I expect this PR can be merged before the end of this month.

2022-08-01 02:22 UTC, Shaowei-Dong commented
kindly ping @isvargasmsft  @JarbasHorst  @Lauragra

2022-08-01 20:11 UTC, isvargasmsft approved these changes

2022-08-02 04:39 UTC, opbld33 commented
Docs Build status updates of commit _[6fcfdfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fcfdfb8f5a58800eab67ec3047bcf67c7595f87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexternalpartnersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/cloudpcexternalpartnersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/cloudpcexternalpartnersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-update?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-externalpartnersettings?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexternalpartnersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/cloudpcexternalpartnersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexternalpartnersetting?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexternalpartnersetting-get?view=graph-rest-beta&branch=pr-en-us-16264) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/microsoftgraph/user/shdo/EPA/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020437120417-16264/BuildReport?accessString=4088ac8082bd9c03a95ab3e07d6caaf96cddff97e46ed6bd2b9767712ea08700).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:52 UTC, merged